### ISSUE TITLE
Support building TensorFlow Serving on OS X

### ISSUE THREAD

**Issue by kirilg** [tensorflow/serving#1]

**Comment by kirilg** [comment]
Even though we don't yet have full support for it, it does work if you run it in a docker container - http://tensorflow.github.io/serving/docker

We should still add full support without requiring docker.

**Comment by Shaikjalal** [comment]
I have issues compiling serving on mac, i guess its still not supported for mac.
tensorflow_serving/core/test_util/BUILD:52:1: C++ compilation of rule '//tensorflow_serving/core/test_util:fake_loader' failed: osx_cc_wrapper.sh failed: error executing command external/bazel_tools/tools/cpp/osx_cc_wrapper.sh '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote ... (remaining 101 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from tensorflow_serving/core/test_util/fake_loader.cc:16:
./tensorflow_serving/core/test_util/fake_loader.h:59:10: error: thread-local storage is not supported for the current target
  static thread_local bool was_deleted_in_this_thread_;
         ^
tensorflow_serving/core/test_util/fake_loader.cc:24:1: error: thread-local storage is not supported for the current target
thread_local bool FakeLoader::was_deleted_in_this_thread_;
^
2 errors generated.
INFO: Elapsed time: 1583.096s, Critical Path: 1409.25s

**Comment by unclepeddy** [comment]
Closing as the recommended way to build is using the development docker image.
