### ISSUE TITLE
HELP！Has anyone tried the asynchronous c++ client？？Just like example/mnist_client.py？？

### ISSUE THREAD

**Issue by JoneJay** [tensorflow/serving#1009]
The example/inception_client.cc is only a synchronization one. 
Their interfaces are as below.
inception_client.cc:
    Status status = stub_->Predict(&context, predictRequest, &response);
mnist_client.py:
    result_future = stub.Predict.future(request, 5.0)  # 5 seconds
    result_future.add_done_callback(_create_rpc_callback(1, result_counter))

looking for a c++ version just like mnist_client.py.

**Comment by JoneJay** [comment]
And mnist_client.py there maybe a problem of mem leak. I changed it to inception , and run in docker, the docker's memory increase after running a large number loop.

**Comment by simon-mo** [comment]
@JoneJay This might be late. I did implement [an async C++ client](https://gist.github.com/simon-mo/e24d9bbd11182cdc97505a39a0919d70) referencing https://github.com/grpc/grpc/blob/v1.14.1/examples/cpp/helloworld/greeter_async_client2.cc
