### ISSUE TITLE
Invalid JSON format response

### ISSUE THREAD

**Issue by seizeTheDayMin** [tensorflow/serving#1014]
### System information
- **OS Platform and Distribution**: Ubuntu 18.04
- **TensorFlow Serving installed from (source or binary)**: binary (
- **TensorFlow Serving version**: tensorflow-model-server_1.8.0_all.deb

### Describe the problem
TF-Serving rarely responses invalid json format.
It does not matter if we process it in raw form, but the problem occurs in json format (with json parse).

Client-sides which use POSTMAN(with json) or json parser receive an **Expected ',' instead of '.'** error message. (json parsing error)

The problem areas are float numbers like **6e-07.0** (expected 6e-07).

- full request body: [ebytech_error_req_sample.txt](https://github.com/tensorflow/serving/files/2226167/ebytech_error_req_sample.txt)
- full response : [ebytech_error_req_sample.txt](https://github.com/tensorflow/serving/files/2226168/ebytech_error_req_sample.txt)

**Comment by netfs** [comment]
See #989 (this has been fixed upstream)

**Comment by netfs** [comment]
Fix: https://github.com/tensorflow/serving/commit/6ff5d9f80ef4ae7b69af2e114fed969c163d6c47
