### ISSUE TITLE
Docker with GPU failed call to cuInit: CUresult(-1) 

### ISSUE THREAD

**Issue by aclowkey** [tensorflow/serving#1015]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 17.10
- **TensorFlow Serving installed from (source or binary)**: binary
- **TensorFlow Serving version**: 1.9
- **Docker version**: 18.03.1-ce
- **Nvidia docker version**: 2.0.3
### Describe the problem
I'm attempting to run a tensorflow serving in a container which needs GPU.
When I'm starting the container and use it I don't see the process in host of `nvidia-smi`
Looking at the log I saw few weird issues. 

### Exact Steps to Reproduce
This is a simple example which shows the same error
`
docker run -p 8501:8501 \
-v /tmp/tfserving/serving/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_three:/models/half_plus_three \
-e MODEL_NAME=half_plus_three -t tensorflow/serving:1.9.0-devel-gpu \
tensorflow_model_server \
 --port=8500 \
 --rest_api_port=8501 \
 --model_name=half_plus_three \
 --model_base_path=/models/half_plus_three
`

### Source code / logs
> 2018-07-26 05:55:57.044214: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2018-07-26 05:55:57.044874: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUresult(-1)
> 2018-07-26 05:55:57.045256: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program

**Comment by rdwrt** [comment]
Likely the stubs used in building are still there.

**Comment by rdwrt** [comment]
A good way to test if the GPU drivers of your container are setup correctly before you start building the model server is this script, which should return the details of your video card: https://gist.github.com/f0k/63a664160d016a491b2cbea15913d549

**Comment by aclowkey** [comment]
Could you help me with the workaround? What exactly did you comment out?

**Comment by aclowkey** [comment]
Also I'm not using the image as build server, rather as a production server. Loading the necessary model and actually using it.

**Comment by aclowkey** [comment]
I tried running the gist and got : 

> Traceback (most recent call last):
>   File "cuda_check.py", line 117, in <module>
>     sys.exit(main())
>   File "cuda_check.py", line 52, in main
>     raise OSError("could not load any of: " + ' '.join(libnames))
> OSError: could not load any of: libcuda.so libcuda.dylib cuda.dll

**Comment by rdwrt** [comment]
Ok so here a link to the Dockerfile and changes I made to create a working instance

https://github.com/tensorflow/tensorflow/issues/19840

**Comment by rdwrt** [comment]
Maybe a double check, are you running in nvidia-docker and can you run 
```
nvidia-smi 
```
?

**Comment by aclowkey** [comment]
I am. Nvidia-smi works for the container and host machine

**Comment by gautamvasudevan** [comment]
> docker run -p 8501:8501 \ -v 

You need to use nvidia-docker to run the GPU build.

**Comment by rydee** [comment]
I spent the last day debugging the same error in a similar configuration (Ubuntu 16.04, TFServing 1.9, Tesla P100).  The GPU worked fine in tensorflow/tensorflow.  Running in tensorflow/serving:nightly-devel-gpu fixed the problem.  

https://github.com/tensorflow/serving/commit/4cbac38c307ea11527d0e45a3b18fd41f1b67601#diff-5442e32f8ca43e5ee752e24804404913

**Comment by gautamvasudevan** [comment]
This should be fixed in the next release (and is fixed in the master branch)

**Comment by rdwrt** [comment]
@gautamvasudevan 

The following lines that probably break the CUDA functionality in nvidia-docker are still included in the next release (r1.10) : https://raw.githubusercontent.com/tensorflow/serving/r1.10/tensorflow_serving/tools/docker/Dockerfile.devel-gpu

RUN ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:${LD_LIBRARY_PATH}

**Comment by gautamvasudevan** [comment]
That's intentional - they only apply to that command, and are needed so the stubs exist to build the binary.

**Comment by rdwrt** [comment]
But the binary can be built succesfully without the stubs! And the stubs stop the container from using the GPU when running in nvidia-docker.

**Comment by rdwrt** [comment]
See a solution here: https://github.com/tensorflow/serving/issues/1031

**Comment by adelnobel** [comment]
Had this issue running tensorrt on tfserving-devel-gpu
similar to CLIsVeryOK solution, removing the entire stubs folder worked for 

`rm -r /usr/local/cuda/lib64/stubs/libcuda.so.1` fixed my problem
