### ISSUE TITLE
error happens while "bazel build serving": no such package '@org_tensorflow//tensorflow': java.io.IOException: thread interrupted

### ISSUE THREAD

**Issue by PayneJoe** [tensorflow/serving#1018]
This problem has also been issued #844 , but I do not know why it was closed WITHOUT a complete solution? 

Is there anyone has a solution about this?

**Comment by gautamvasudevan** [comment]
You likely don't have all the installation prerequisites. Please file a bug with the full bug report template filled out. Thanks!
