### ISSUE TITLE
basic_batch_scheduler_benchmark is timeout on ci.bazel.io

### ISSUE THREAD

**Issue by meteorcloudy** [tensorflow/serving#102]
http://ci.bazel.io/job/TensorFlow_Serving/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/141/console

**Comment by kirilg** [comment]
Could you please provide additional info about the failure (logs)? All of these tests are passing for TF Serving at head with Bazel 0.2.1 and the batching code hasn't changed recently, so I suspect it could be something with Bazel at head rather than TF Serving.

**Comment by damienmg** [comment]
```
//tensorflow_serving/batching:basic_batch_scheduler_benchmark           TIMEOUT in 305.0s
  /home/ci/.cache/bazel/_bazel_ci/e409f7152fa45ddf3337f1660b5273b9/execroot/linux-x86_64/bazel-out/local-fastbuild/testlogs/tensorflow_serving/batching/basic_batch_scheduler_benchmark/test.log
```

It's time out after 305 seconds. There is not much in the output:
```
        Testing //tensorflow_serving/batching:basic_batch_scheduler_benchmark, 304 s
TIMEOUT: //tensorflow_serving/batching:basic_batch_scheduler_benchmark (see /home/ci/.cache/bazel/_bazel_ci/e409f7152fa45ddf3337f1660b5273b9/execroot/linux-x86_64/bazel-out/local-fastbuild/testlogs/tensorflow_serving/batching/basic_batch_scheduler_benchmark/test.log)
____From Testing //tensorflow_serving/batching:basic_batch_scheduler_benchmark:
==================== Test output for //tensorflow_serving/batching:basic_batch_scheduler_benchmark:
Latency benchmark w/ batch timeout 0ms; task injection rate 1000/sec	...	99.9% latency: 697.319ms	99% batch size: 25.6976
================================================================================
```

The first issue is http://ci.bazel.io/job/TensorFlow_Serving/118/. It seems like after changes to tensorflow serving. It was with 0.2.3. Previous build did not timed-out at was already with 0.2.3.

**Comment by hermione521** [comment]
It's also timeout for bazel 0.2.1 on my machine, which doesn't look like a bazel problem.

**Comment by damienmg** [comment]
Looking for basic_batch_scheduler_benchmark on ci.tensorflow.org log gives nothing...  Are you sure this test is run on tensorflow CI ?

**Comment by damienmg** [comment]
http://ci.tensorflow.org/view/Serving/job/serving-master-cpu/39/console

**Comment by kirilg** [comment]
Ah, yes sorry. This test is actually marked as "manual" and "local". Our Jenkins is configured to run
'bazel test tensorflow_serving/...'  while yours includes all test targets by testing "bazel query 'tests(tensorflow_serving/...)'"

Since this is a benchmark and not a real test, it's safe for you to ignore it and remove from your automated testing as well.

**Comment by damienmg** [comment]
SGTM readding filter on manual to ci.bazel.io
