### ISSUE TITLE
Tensorflow serving get_model_status_pb2 import error.

### ISSUE THREAD

**Issue by AswathKiruba** [tensorflow/serving#1026]
Using Tensorflow 1.9.0 and Tensorflow Serving API 1.9.0, the following code:
`from tensorflow_serving.apis import get_model_status_pb2`

gives me the error:

```Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/usr/local/lib/python3.5/dist-packages/tensorflow_serving/apis/get_model_status_pb2.py", line 17, in <module> from tensorflow_serving.util import status_pb2 as tensorflow__serving_dot_util_dot_status__pb2 ImportError: No module named 'tensorflow_serving.util'```

**Comment by gautamvasudevan** [comment]
Fixed by #999
