### ISSUE TITLE
Missing Multi-Model Documentation

### ISSUE THREAD

**Issue by jhorowitz** [tensorflow/serving#1029]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
N/A
- **TensorFlow Serving installed from (source or binary)**:
N/A
- **TensorFlow Serving version**:
All versions of the documentation

### Describe the problem
After reading through main.cc, I was able to get a multi-model serving session running but it was kind of a painful process. 
I would love to help others who faced similar troubles and contribute documentation back to the community. Making it would take a bit of work so I wanted to check here to make sure it's a welcome contribution before doing that.

**Comment by gautamvasudevan** [comment]
Sure thing! look inside the g3docs folder. If there's a good file to add this documentation to, that's great. Otherwise feel free to create a new markdown file.

**Comment by ymodak** [comment]
@jhorowitz Just wanted to follow up. Did you get a chance to prepare documentation for multi-model serving session as you suggested?. That will be an interesting contribution.

**Comment by jhorowitz** [comment]
Hey @ymodak, I'm slowly writing it up. I hope to get it done in about 2 weeks. In the meantime, if you have any specific questions, I'm happy to answer them here.

**Comment by ymodak** [comment]
@jhorowitz Yes. It just helps us to keep track of the status. In this case it means that we are waiting for your contribution / user's update.

**Comment by jhorowitz** [comment]
Ah, makes sense.

**Comment by ymodak** [comment]
@jhorowitz Any updates on this? Thanks!

**Comment by gautamvasudevan** [comment]
@chrisolston  managed to get around to documenting this. Thanks Chris!
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/serving_config.md
