### ISSUE TITLE
like this

### ISSUE THREAD

**Issue by ShaunZheng** [tensorflow/serving#1035]
^
ERROR: /home/shaun/.cache/bazel/_bazel_shaun/a1f0bc16eec023f42bba4ce8af962f96/external/org_tensorflow/tensorflow/core/BUILD:2457:1: C++ compilation of rule '@org_tensorflow//tensorflow/core:framework_internal_impl' failed (Exit 4)
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Target //tensorflow_serving/example:mnist_saved_model failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 403.511s, Critical Path: 100.31s
INFO: 307 processes: 307 local.
FAILED: Build did NOT complete successfully

**Comment by gautamvasudevan** [comment]
Please fill out the issue template.
