### ISSUE TITLE
Inception example server can't load model

### ISSUE THREAD

**Issue by rsln-s** [tensorflow/serving#104]
In [this tutorial](https://tensorflow.github.io/serving/serving_inception.html) after completing step 1 and building everything, the server fails with `I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:147] Aspiring version for servable default from path: inception-export/00157585`

The model in `inception-export/00157585/export` weights 104Mb, so maybe that causes some overflowing? [There is some discussion of protobufs >64Mb](https://github.com/tensorflow/tensorflow/issues/2046), but I couldn't find a solution there or [here](https://github.com/tensorflow/serving/issues/24).

I've got protobuf beta3 installed:
`pip list | grep proto`
`protobuf (3.0.0b3)`

Full log:
`root@s1056:~/serving# bazel-bin/tensorflow_serving/example/inception_inference --port=9000 inception-export                   
I tensorflow_serving/core/basic_manager.cc:189] Using InlineExecutor for BasicManager.
I tensorflow_serving/example/inception_inference.cc:380] Waiting for models to be loaded...
I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:147] Aspiring version for servable default from path: inception-export/00157585
I tensorflow_serving/session_bundle/session_bundle.cc:130] Attempting to load a SessionBundle from: inception-export/00157585
I tensorflow_serving/session_bundle/session_bundle.cc:107] Running restore op for SessionBundle
I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:147] Aspiring version for servable default from path: inception-export/00157585
I tensorflow_serving/example/inception_inference.cc:380] Waiting for models to be loaded...
I tensorflow_serving/session_bundle/session_bundle.cc:119] Running init op for SessionBundle
I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:147] Aspiring version for servable default from path: inception-export/00157585
I tensorflow_serving/example/inception_inference.cc:346] Running...
I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:147] Aspiring version for servable default from path: inception-export/00157585
I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:147] Aspiring version for servable default from path: inception-export/00157585
I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:147] Aspiring version for servable default from path: inception-export/00157585`

**Comment by fangweili** [comment]
Those are normal INFO logs. When you say "server fails", what symptoms were
you seeing? Did request from inception_client failed? If so, what's the
error message?

Thanks,
/Fangwei

**Comment by rsln-s** [comment]
As far as I can see, one of client's functions times out. Here are the full logs from client:
![2016-06-13 23 43 41](https://cloud.githubusercontent.com/assets/11508369/16022487/2cc1625e-31c9-11e6-91fc-aab1ab1c30ab.png)

The last line in `inception_log` is
 `E0613 23:43:19.504689750   13820 inception_inference.cc:328] assertion failed: ok`

**Comment by jharmsen** [comment]
It does look like the request is timing out.  Recently submitted cc568860a981e7750c2b1cbcaac91dfaf4515524 fixes an issue where the server would fail on timeouts.  Could you try again with that change included?

**Comment by schaaf23** [comment]
The classify function in the client sets a timeout of 10 secs, if your machine does not manage to get the image classified in less than 10 secs, you get this error.
this is not an server issue.
I had the same problem - raised the timeout in `inception_client.py` to 3600, and it worked.

`line 51:    result = stub.Classify(request, 3600.0)  # 10 secs timeout`

classification took on my VM about 30 secs.
or: get faster hardware :)
