### ISSUE TITLE
Cannot load model - no OpKernel found

### ISSUE THREAD

**Issue by dmansfield** [tensorflow/serving#105]
I've been trying to export "Parsey McParseface" and import it into serving.  To this end, I have modified syntaxnet/parser_eval.py to export the model, and have begin to modify one of the examples in tf_serving to load the exported model.

I have managed to get past the fact that the example (in this case I'm locally modifying mnist_inference.cc) needs to link a bunch of syntaxnet ops libararies (and around the fact that syntaxnet is out-of-date with respect to current tensorflow submodule).

Now I'm getting this error:

```
I tensorflow_serving/session_bundle/session_bundle.cc:130] Attempting to load a SessionBundle from: /tmp/model/brain_parser/00000001
I tensorflow_serving/session_bundle/session_bundle.cc:107] Running restore op for SessionBundle
F tensorflow_serving/example/mnist_inference.cc:215] Check failed: ::tensorflow::Status::OK() == (bundle_factory->CreateSessionBundle(bundle_path, &bundle)) (OK vs. Invalid argument: No OpKernel was registered to support Op 'UnpackSparseFeatures' with these attrs
	 [[Node: evaluation/while/UnpackSparseFeatures_2 = UnpackSparseFeatures[](evaluation/while/feature_2)]])
Aborted (core dumped)
```
I've examined the graph and I don't believe there is any issue. Is the system unable to infer the attr types in some situations?

I've also exported the graph def as a pbtxt, AND using the SummaryWriter to load into tensorboard.  Tensorboard has no problem loading the model written out.  Here's the code I'm using to write the model, etc:
```
  logging.info('Exporting trained model to /tmp/model/%s', FLAGS.arg_prefix)
  saver = tf.train.Saver()
  model_exporter = exporter.Exporter(saver)
  signature = exporter.classification_signature(input_tensor=sink)
  model_exporter.init(sess.graph.as_graph_def(),
                      default_graph_signature=signature)
  model_exporter.export('/tmp/model/%s' % FLAGS.arg_prefix, tf.constant(1), sess)
   
  writer = tf.train.SummaryWriter('/tmp/model/%s' % FLAGS.arg_prefix, sess.graph)
  writer.flush()

  f1 = open('/tmp/model/%s/graph.pbtxt' % FLAGS.arg_prefix, 'w+');
  print >>f1,str(tf.get_default_graph().as_graph_def()) 
```

The graph.txt attached is the graph.pbtxt (renamed for github).  Unfortunately, github won't allow the actual model (checkpoint, export and export.meta) to be included due to their size.  I can easily provide them if someone provides a means.

[Graph pbtxt: graph.pbtxt](https://github.com/tensorflow/serving/files/317486/graph.txt)
[Tensorboard Logdir: events.tar.gz](https://github.com/tensorflow/serving/files/317491/events.tar.gz)

**Comment by dmansfield** [comment]
I found the cause (and lost 8 hours of my life!).  In syntaxnet BUILD file, the target for UnpackSparseFeatures is missing "alwayslink = 1" so the actual OpKernel is not getting linked in even though the op is registered.

Adding this one line and it is able to build the graph.

This is a syntaxnet bug, not a serving bug.

**Comment by szz-dvl** [comment]
Hi dmansfield!

I'm trying to reuse your work to serve different models for a set of languages,  at this point I'm willing to generate the files "export" and "export.meta" for parsey universal pre-trained models, so I'm looking at the script located at "/models/syntaxnet/syntaxnet/parsey_mcparseface.py", however if I try to run it it will yield the following import error:

ImportError: No module named syntaxnet

As you can see I'm far from being an expert with tensorflow and syntaxnet and, at this point, I'm pretty lost, so if you can point me to the right direction or you know where I can find syntaxnet python module It will be really appreciated.

Thanks in advance.

Szz

**Comment by szz-dvl** [comment]
Hi again dmansfield,

I realized that the module wasn't in use, so please ignore my last post ... 

Thanks again, and sorry for the inconvenience ... =S

Szz.
