### ISSUE TITLE
TF-serving -1.10.0 unable to build from source

### ISSUE THREAD

**Issue by gautamkmr89** [tensorflow/serving#1051]
bazel build -c opt --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-O3 --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" tensorflow_serving/...
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/5a5e187bba58f25ed3cabee3518e39d1/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:117:1: file '@bazel_tools//tools/cpp:windows_cc_configure.bzl' does not contain symbol 'setup_vc_env_vars'
ERROR: error loading package '': Extension file 'third_party/gpus/cuda_configure.bzl' has errors
ERROR: error loading package '': Extension file 'third_party/gpus/cuda_configure.bzl' has errors
INFO: Elapsed time: 0.040s
FAILED: Build did NOT complete successfully (0 packages loaded)
(tensorflow_p27) ubuntu@ip-172-31-44-75:~/src/serving_tensorflow_p27$

**Comment by gautamkmr89** [comment]
Feel free to close it.

Looks like TF-serving-1.10.0 needs Bazel -0.15.0  I had 0.11.1

**Comment by memesi** [comment]
@gautamkmr89 how did you solve it ?
