### ISSUE TITLE
RPM binary for TF-serving 

### ISSUE THREAD

**Issue by gautamkmr89** [tensorflow/serving#1052]
TF-serving has debian binary but not the rpm. Would you be able to release rpm binary so that it will be helpful for them who uses RHEL ?

**Comment by harshini-gadige** [comment]
@gautamvasudevan  -  Hi, anyone working on this feature ? Or can this be changed to Contributions Welcome ?

**Comment by gautamvasudevan** [comment]
This is something we'd have to change internally in our release process, so unfortunately contributions aren't possible. If you're interested in this feature, feel free to up-vote the issue or comment on your use case.

**Comment by unclepeddy** [comment]
This is not something that we are prioritizing at the moment. Our advice to RHEL users (like other users) is to use Docker for installation. Please feel free to open and voice your concerns if this is not an option for you.

**Comment by a7744hsc** [comment]
https://github.com/harshad16/tensorflow-model-serving/tree/master/tensorflow-model-server-rpm  
This repo saved me，though the version is a little outdated.
