### ISSUE TITLE
half_plus_three:predict --》half_plus_two:predict

### ISSUE THREAD

**Issue by zyxcambridge** [tensorflow/serving#1062]
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md

error

GPU

curl -d '{"instances": [1.0, 2.0, 5.0]}' \
  -X POST http://localhost:8501/v1/models/half_plus_three:predict
should

curl -d '{"instances": [1.0, 2.0, 5.0]}' \
  -X POST http://localhost:8501/v1/models/half_plus_two:predict

**Comment by chrisolston** [comment]
Thanks for pointing out this documentation bug. I'm fixing it in the internal (google) copy and the fix should get propagated to github soon.
