### ISSUE TITLE
[Feature Request] Version argument when calling tensorflow_model_server

### ISSUE THREAD

**Issue by tmlabonte** [tensorflow/serving#1064]
It would be very useful for A/B testing and deployment to be able to easily serve specific model versions when calling `tensorflow_model_server` from the command line. Right now it just defaults to serving the latest version of the model, instead of letting the user select a version.

I'd like to see a version argument added to the `tensorflow_model_server` command to direct the server towards a certain version within the model directory. This argument would be a FLAG in [main.cc ](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc) representing the name of the version subdirectory, and would have no default. It could then be passed as an optional argument to `BuildSingleModelConfig` in [server.cc](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/server.cc). I can't seem to find the class methods for `ModelServerConfig`, so I'm not sure what would happen next, but we might be able to utilize the `model_version_policy` member variable in [model_server_config.proto](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/config/model_server_config.proto) and specify the selected version number in the `Specific` option in [file_system_storage_path.proto](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/sources/storage_path/file_system_storage_path_source.proto).

Adding a version argument seems like a relatively easy addition that would make deployment of models more customizable and efficient without having to write custom code or override the version policies yourself.

**Comment by chrisolston** [comment]
You can already request specific version#s to be served via the --model_config_file flag (using the Specific option of the ServableVersionPolicy message as you mentioned).
