### ISSUE TITLE
Serving frequent request timeouts

### ISSUE THREAD

**Issue by dsafaric** [tensorflow/serving#1074]
### Problem description

The problem we encounter is the following. Serving is configured to load and serve 7 models, and with an increase in the number of models, Serving requests timeout more frequently. On the contrary, with a decrease in the number of models request timeouts are insignificant. From the client's side, timeout was configured to 5 seconds. 

Interestedly, the maximum batch processing duration is approximately 700ms, with a configured maximum batch size of 10. The average batch processing duration is ~60ms.

### Logs and screenshots

We've checked the TensorFlow Serving logs but no warnings nor errors were found. In addition to, we've monitored the network of the running GPU machines and hosts executing inference requests towards Serving, but no network issues were identified neither.  

### Describe the solution
Decreasing the number of loaded and served models, however not the expected solution because this requires setting up multiple distinct GPU instance each loading and serving only a subset of models.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow Serving installed from (source or binary)**: source
- **TensorFlow Serving version**: 1.9

TensorFlow serving runs on multiple AWS g2.2xlarge instances. We run TensorFlow Serving using Docker, with a base image `nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04`.

**Comment by chrisolston** [comment]
Cross-posted on stackoverflow [1]. Deleting here.

[1] https://stackoverflow.com/questions/52150656/tensorflow-serving-frequent-request-timeouts

**Comment by thomasSve** [comment]
Found a solution to this @dsafaric ? I'm experiencing the same trying to serving 7 models at the same time. The average response time is very low, but I'm getting some weird timeouts.

**Comment by songboyu** [comment]
same issue, waiting for help.

**Comment by spraveen420** [comment]
0


I am trying to serve model using docker Tensorflow-serving in VM(Linux) and Tensorboard WhatIf tool in my laptop(windows) But I am getting this error Inference request is failing from WhatIf tool with 500 Internal Server Error

raise _Rendezvous(state, None, None, deadline) grpc._channel._Rendezvous: <_Rendezvous of RPC that terminatedenter code here with: status = StatusCode.DEADLINE_EXCEEDED details = "Deadline Exceeded" debug_error_string = "{"created":"@1574320102.966000000","description":"Error received from peer ipv4:35.202.142.154:8500","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Deadline Exceeded","grpc_status":4}"
