### ISSUE TITLE
Model loaded successfully even if variable files are absent

### ISSUE THREAD

**Issue by agupta74** [tensorflow/serving#1086]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 14.04
- **TensorFlow Serving installed from (source or binary)**: Sources
- **TensorFlow Serving version**: 1.5.0

### Describe the problem
Got the following message when TF serving model is getting loaded: **external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:165] The specified SavedModel has no variables; no checkpoints were restored.**

The issue seems to be that variables folder got created while the variable files were being copied/unzipped to this folder and it takes some time to copy/unzip these variable files as the variable file size is in GBs. As per the TF serving source code, it assumes that variable files not being present is OK but it should be returning an error since a model would typically have trained variables to be loaded.

### Exact Steps to Reproduce
Export any model to protobuf format and copy the model while delaying the the copy (or not copying at all) of variable files

### Source code / logs
Here are the logs:

2018-09-11 15:06:02.360258: I tensorflow_serving/core/basic_manager.cc:705] Successfully reserved resources to load servable {name: my_model version: 12}
2018-09-11 15:06:02.360271: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: my_model version: 12}
2018-09-11 15:06:02.360280: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: my_model version: 12}
2018-09-11 15:06:02.360302: I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:360] Attempting to load native SavedModelBundle in bundle-shim from: /my_path/my_model/12
2018-09-11 15:06:02.360314: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:236] Loading SavedModel from: /my_path/my_model/12
2018-09-11 15:06:03.172504: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:155] Restoring SavedModel bundle.
**2018-09-11 15:06:03.172561: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:165] The specified SavedModel has no variables; no checkpoints were restored.**
2018-09-11 15:06:03.172579: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:190] Running LegacyInitOp on SavedModel bundle.
2018-09-11 15:06:03.293689: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:284] Loading SavedModel: success. Took 932896 microseconds.
2018-09-11 15:06:03.296419: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: my_model version: 12}

Here is the source code snippet which is printing this message in loader.cc file:

.....
LOG(INFO) << "Restoring SavedModel bundle.";
  // Find path to variables to be restored in export directory.
  const string variables_directory =
      io::JoinPath(export_dir, kSavedModelVariablesDirectory);
  // Check for saver checkpoints in v2 format. Models exported in the checkpoint
  // v2 format will have a variables.index file. The corresponding
  // variables are stored in the variables.data-?????-of-????? files.
  const string variables_index_path = io::JoinPath(
      variables_directory, MetaFilename(kSavedModelVariablesFilename));
  if (!Env::Default()->FileExists(variables_index_path).ok()) {
    LOG(INFO) << "The specified SavedModel has no variables; no checkpoints "
                 "were restored.";
    return Status::OK();
  }
.........

**Comment by netfs** [comment]
@karmel can you help?

it seems we should not (but presently do) load a model that does not have associated variables alongside.

**Comment by karmel** [comment]
Variables are not strictly necessary-- one can imagine you have a bit of graph to serialize with ins and outs but no variables. (Consider, for example, TF Hub, and the use-cases there.) It doesn't make sense to restrict this on the saved model building or loading side explicitly. 

Presumably the model throws an error with no vars at some point? What does that error look like?

**Comment by agupta74** [comment]
The error is thrown during the predict call with error message:
**Error calling PredictServing: rpc error: code = FailedPrecondition desc = Attempting to use uninitialized value Model/xxxxx.**

**Comment by karmel** [comment]
It's hard to tell a priori that Variables will be missing. The best practice here is likely to send a few sample queries/warm-up the model; is that feasible in this case?

**Comment by karmel** [comment]
Yes-- please see the [saved_model_cli](https://www.tensorflow.org/guide/saved_model#cli_to_inspect_and_execute_savedmodel) for a command line interface, or [SavedModelEstimator](https://www.tensorflow.org/versions/r1.11/api_docs/python/tf/contrib/estimator/SavedModelEstimator) for a python API.

**Comment by netfs** [comment]
@karmel -- @agupta74 is asking about hot-reloading of the model. neither the cli nor the estimator would allow for that. please use [HandleReloadConfigRequest](https://github.com/tensorflow/serving/blob/bec76d47a337ee6865ce0b4fcc9e97d5ab67b38f/tensorflow_serving/apis/model_service.proto#L22) API instead.

**Comment by harshini-gadige** [comment]
@agupta74  - Hi, is this still an issue ?

**Comment by Noctune** [comment]
I just ran into this issue as well. The copying function copied the saved_model first and then variables after. This caused serving to load the model without any variables - even after copying the variables finished.

Easy enough to fix in my case - just copy the saved_model last - but it is still a easy way to shoot yourself in the foot.

**Comment by harshini-gadige** [comment]
@agupta74  Did you get a chance to try on HandleReloadConfigRequest API as asked above ? If so, please post your observations.

**Comment by harshini-gadige** [comment]
Closing as this is inactive and in "awaiting response" status for more than a week. Feel free to post your comments(if any) and we will reopen.

**Comment by colinmorelli** [comment]
Just replying here to say I ran into this today also. Using `gsutil` to upload a model directory, TF serving picked up the new version immediately after saved_model.pb was uploaded, before the variables were uploaded. It successfully loads the model, but fails evaluation.

I haven't tried HandleReloadConfigRequest, which I'm sure would work (as would changing the order of the uploads), because I'm not particularly concerned about it - but I don't think this should be closed either.

Is there some way we could get TF serving to validate the loaded model before it assumes that the version update has been completed successfully? So far as I can tell, your options for ensuring models are successfully loaded are:
 - Not using latest version strategy (and manually setting versions when the upload is complete)
 - Force reloading config after the upload is complete (not 100% sure this will work)
 - Writing the model atomically (not possible on cloud filesystems)
 - Writing the model in a specific order such that loading will fail until all files are uploaded (i.e. writing saved_model.pb last)

Thoughts?

**Comment by aginpatrick** [comment]
@colinmorelli Just read your comment above while I'm having a hard time to find the source of my error (see this [post](https://stackoverflow.com/questions/64879548/tensorflow-server-returns-an-error-when-using-model-on-s3) on SO)
