### ISSUE TITLE
how to docker a  tensorflow serving's file ?

### ISSUE THREAD

**Issue by jluite** [tensorflow/serving#11]
As mentioned in https://tensorflow.github.io/serving/docker,  it doesn't work because there isn't  one url linkage for tensorflow serving  like b.gcr.io/tensorflow/tensorflow for tensorflow .  Please tell me Anything I misunderstand or misinformation . Thanks alot .

**Comment by wjarek** [comment]
The docker file is here: https://github.com/tensorflow/serving/tree/master/tensorflow_serving/tools/docker - does this answer your question?

**Comment by jluite** [comment]
Yes . Thank you very much, wjarek  . 

 When I type  " docker build -t $USER/tensorflow-serving-devel -f Dockerfile.devel . " on the  ubuntu 15.10 with docker 1.10.2 , the result of this command  indicates " Sending build context to Docker daemon 484.6 MB , Step 1 : <!DOCTYPE   Unknown instruction: <!DOCTYPE  " .  
 How to handle this case ?  Thank you in advance .

**Comment by jharmsen** [comment]
It looks like your Dockerfile.devel has some extraneous text in the beginning.

Please make sure you have the raw file:
https://raw.githubusercontent.com/tensorflow/serving/master/tensorflow_serving/tools/docker/Dockerfile.devel

It should start with:
FROM ubuntu:14.04

**Comment by jluite** [comment]
Yes and thank you very much,  @jharmsen  .

**Comment by vodp** [comment]
Hi,

With the downloaded .devel file, I still meet the error 
```
dp@monster:/amy$ docker build --pull -t dp/tensorflow-serving-devel -f Dockerfile.devel .
Sending build context to Docker daemon 1.414 GB
Step 1 : <!DOCTYPE 
Unknown instruction: <!DOCTYPE
```

**Comment by jharmsen** [comment]
Hi D.P.,

Looks like the same issue jluite had.

Please make sure you have downloaded the raw file:
https://raw.githubusercontent.com/tensorflow/serving/master/tensorflow_serving/tools/docker/Dockerfile.devel

It should start with:
FROM ubuntu:14.04

**Comment by vodp** [comment]
Yeah. It turns out that I downloaded the html page of the file. After building successfully, I guess I have to install cuda toolkit and cudnn manually? The docker seems do not contain those.
