### ISSUE TITLE
"Tensor :0, specified in either feed_devices or fetch_devices was not found in the Graph"

### ISSUE THREAD

**Issue by haotianteng** [tensorflow/serving#1100]
Os system: Ubuntu16.04
Tensorflow version: 1.10.1
Tesnroflow serving apis version: 1.10.1
Can you add more information to the error output message? As this indicates a Tensor named " :0" is not found in the graph which is quite confusing.

**Comment by haotianteng** [comment]
After some digging I found the problem, it is caused when I try to export a SparseTensor as the output Tensor:
```
A minimum reproduce example:
a = tf.constant([[[1.0]]])
b = tf.constant([1])
output,prob = tf.nn.ctc_beam_search_decoder(a,b)
a = tf.saved_model.utils.build_tensor_info(a)
```

And one can see that a has a name:
a
name: "Const_15:0"
dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 1
  }
  dim {
    size: 1
  }
  dim {
    size: 1
  }
}

while the SparseTensor does not has a name:
dtype: DT_INT64
tensor_shape {
  dim {
    size: -1
  }
  dim {
    size: -1
  }
}
coo_sparse {
  values_tensor_name: "CTCBeamSearchDecoder_12:1"
  indices_tensor_name: "CTCBeamSearchDecoder_12:0"
  dense_shape_tensor_name: "CTCBeamSearchDecoder_12:2"
}
Which cause the error:
ValueError: The name '' looks like an (invalid) Operation name, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".
and  also the above error, when export it into a saved_model and request it.

The reason is when building a TensorProto for the SaprseTensor, no name is assigned to it:
https://github.com/tensorflow/tensorflow/blob/r1.10/tensorflow/python/saved_model/utils_impl.py#L46
This is issue is related to the same problem a issue I submitted before: #1096

**Comment by Kritamook** [comment]
with new_detection_graph.as_default() and general_detection_graph.as_default():
    for vid in listing:  
        vid = r"C:/vid/"+vid  
        video = cv2.VideoCapture(vid)  
        count = 0  
        counter+=1  
        risk_count = 0  
        success = True  
        print('Video : %d'%counter)  
        while success:
            success, image_np = video.read()  
            if success == True:
                output = road_lines(image_np)  
                image_np_expanded = np.expand_dims(image_np, axis=0)                  
                new_image_tensor = new_detection_graph.get_tensor_by_name('image_tensor:0')  
                new_detection_boxes = new_detection_graph.get_tensor_by_name('detection_boxes:0')  
                new_detection_scores = new_detection_graph.get_tensor_by_name('detection_scores:0')  
                new_detection_classes = new_detection_graph.get_tensor_by_name('detection_classes:0')  
                new_num_detections = new_detection_graph.get_tensor_by_name('num_detections:0')  
                (boxes, scores, classes, num_detections) = new_sess.run([ new_detection_boxes, new_detection_scores, new_detection_classes, new_num_detections], feed_dict={new_image_tensor: image_np_expanded})  
                vis_util.visualize_boxes_and_labels_on_image_array(  
                    image_np,  
                    np.squeeze(boxes),  
                    np.squeeze(classes).astype(np.int32),  
                    np.squeeze(scores),  
                    new_category_index,  
                    use_normalized_coordinates=True,  
                    min_score_thresh=0.4,  
                    line_thickness=8)  
                      
                new_objects = []  
                for index, value in enumerate(classes[0]):  
                    new_object_dict = {}  
                    if scores[0, index] >= 0.40:  
                        new_object_dict[(new_category_index.get(value)).get('name').encode('utf8')] = scores[0, index]  
                        new_objects.append(new_object_dict)



My error is down below :
Tensor batch_normalization_1_input:0, specified in either feed_devices or fetch_devices was not found in the Graph

pls help me to solve this thx a lot.

**Comment by zxgm** [comment]
You can convert sparse tensor to dense tensor by tf.sparse.to_dense funtion

**Comment by danial459** [comment]
> 
> 
> with new_detection_graph.as_default() and general_detection_graph.as_default():
> for vid in listing:
> vid = r"C:/vid/"+vid
> video = cv2.VideoCapture(vid)
> count = 0
> counter+=1
> risk_count = 0
> success = True
> print('Video : %d'%counter)
> while success:
> success, image_np = video.read()
> if success == True:
> output = road_lines(image_np)
> image_np_expanded = np.expand_dims(image_np, axis=0)
> new_image_tensor = new_detection_graph.get_tensor_by_name('image_tensor:0')
> new_detection_boxes = new_detection_graph.get_tensor_by_name('detection_boxes:0')
> new_detection_scores = new_detection_graph.get_tensor_by_name('detection_scores:0')
> new_detection_classes = new_detection_graph.get_tensor_by_name('detection_classes:0')
> new_num_detections = new_detection_graph.get_tensor_by_name('num_detections:0')
> (boxes, scores, classes, num_detections) = new_sess.run([ new_detection_boxes, new_detection_scores, new_detection_classes, new_num_detections], feed_dict={new_image_tensor: image_np_expanded})
> vis_util.visualize_boxes_and_labels_on_image_array(
> image_np,
> np.squeeze(boxes),
> np.squeeze(classes).astype(np.int32),
> np.squeeze(scores),
> new_category_index,
> use_normalized_coordinates=True,
> min_score_thresh=0.4,
> line_thickness=8)
> 
> ```
>             new_objects = []  
>             for index, value in enumerate(classes[0]):  
>                 new_object_dict = {}  
>                 if scores[0, index] >= 0.40:  
>                     new_object_dict[(new_category_index.get(value)).get('name').encode('utf8')] = scores[0, index]  
>                     new_objects.append(new_object_dict)
> ```
> 
> My error is down below :
> Tensor batch_normalization_1_input:0, specified in either feed_devices or fetch_devices was not found in the Graph
> 
> pls help me to solve this thx a lot.

did you solved it?
