### ISSUE TITLE
 Error loading package '@org_tensorflow//tensorflow/python/keras

### ISSUE THREAD

**Issue by jennings1716** [tensorflow/serving#1106]
I implementing tensorflow serving Ubuntu 16.04 Google GPU instance.Siraj Tutorial .I built dockerfile for GPU and ran the container.Since the Tensorflow serving is updated, I cudnt find the tensorflow folder within the serving.Following some github suggestion i skipped that step and executed " bazel build -c opt tensorflow_serving/...".It gaveme the following error.

**ERROR: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/org_tensorflow/tensorflow/python/BUILD:73:1: error loading package '@org_tensorflow//tensorflow/python/keras': Extension file not found. Unable to load package for '@pip_deps//:requirements.bzl': The repository could not be resolved and referenced by '@org_tensorflow//tensorflow/python:no_contrib'

ERROR: Analysis of target '//tensorflow_serving/servables/tensorflow/testdata:export_half_plus_two' failed; build aborted: error loading package '@org_tensorflow//tensorflow/python/keras': Extension file not found. Unable to load package for '@pip_deps//:requirements.bzl': The repository could not be resolved INFO: Elapsed time: 1.530s INFO: 0 processes. FAILED: Build did NOT complete successfully (25 packages loaded) currently loading: @org_tensorflow//tensorflow/core ... (4 packages)** Have I gone anywhere wrong? How shall I proceed?

**Comment by netfs** [comment]
thanks for the report! our continuous builds are also failing with similar errors:

https://source.cloud.google.com/results/invocations/7beb7cfd-56e5-4975-8b25-c91473e1b001/log

a fix is being prepared and will be submitted soon.
