### ISSUE TITLE
No Proper Documentation For tensorflow serving Installation

### ISSUE THREAD

**Issue by jennings1716** [tensorflow/serving#1109]
It is so difficult to install tensorflow serving in the Ubuntu instance 16.04 with GPU support.Please do come with some proper documentation.Struggling for a week

**Comment by ymodak** [comment]
@jennings1716 Sorry to hear that you are struggling with TF Serving installation. I would like to recommend using [docker for TF Serving installation](https://www.tensorflow.org/serving/setup) . It also provides GPU support. Did you get a chance to try this? Also feel free to post any issues you are running into while using it.
