### ISSUE TITLE
Build Serving Offline Error

### ISSUE THREAD

**Issue by hengdos** [tensorflow/serving#1114]
Hi everyone.

I attempt to build tensorflow serving from source without internet.

While I run this build command:
```shell
bazel build -c opt tensorflow_serving/...
```
It tries to download some packages from internet.

However, my machine can not connect to internet, and meets errors!

Then I try to download all dependency packages manually and upload them to local network. 

After edited all urls in `WORKSPACE`, `repo.bzl` and `workspace.bzl` like this:

```
# TensorFlow depends on "io_bazel_rules_closure" so we need this here.
# Needs to be kept in sync with the same target in TensorFlow's WORKSPACE file.
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "a38539c5b5c358548e75b44141b4ab637bba7c4dc02b46b1f62a96d6433f56ae",
    strip_prefix = "rules_closure-dbb96841cc0a5fb2664c37822803b06dab20c7d1",
    urls = [
        "##local_network_address##",
    ],
)
```

All dependency packages are able to access while running the build command. But I got a new error message as follows:

```
ERROR: error loading package 'tensorflow_serving/resources': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_archive//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/google/protobuf/archive/v3.6.0.tar.gz, https://github.com/google/protobuf/archive/v3.6.0.tar.gz] to /usr/local/qspace/.cache/bazel/_bazel_qspace/569e8150401aea0383da34f5b3eee0e4/external/protobuf_archive/v3.6.0.tar.gz: All mirrors are down: []
INFO: Elapsed time: 57.223s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (15 packages loaded)
    currently loading: tensorflow_serving/resources ... (12 packages)
```

It seems that the building process depends on a extension file `protobuf.bzl` which defines the urls for "protobuf".

However, I checked all folders of tensorflow_serving, and didn't find the file `protobuf.bzl` .

Could anyone help me? Where can I find the extension file `protobuf.bzl` ?

**Comment by christisg** [comment]
Local compilation is not supported at this point. The workaround is to use [bazel fetch](https://docs.bazel.build/versions/master/user-manual.html#fetch) and then replace tensorflow_http_archive with local_repository in WORKSPACE.
