### ISSUE TITLE
Add REST API support for GetModelMetadata request/response 

### ISSUE THREAD

**Issue by sagravat** [tensorflow/serving#1115]
### Describe the problem the feature is intended to solve
TF Serving doesn't allow you to make a REST API call to get the model metadata. You currently have to use the saved_model_cli to get the signature definition. A REST API method would enable the capability to remotely get the the model metadata with JSON representation and it doesn't require direct access to the saved model file.

### Describe the solution
Implement the GET action handler for the method :getmodelmetadata in Status HttpRestApiHandler::ProcessRequest (within http_rest_api_handler.cc) and implement the code to write the json buffer in json_tensor.cc

### Describe alternatives you've considered
Alternative is to just use saved_model_cli

### Additional context
I've already started development of this work and would be happy to contribute it.

**Comment by netfs** [comment]
See https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/api_rest.md#model-status-api

This mimics the existing gRPC api. If we want more information (that the CLI returns), we should
extend the gRPC API. That would automatically return same information via the REST API.

**Comment by sagravat** [comment]
Just to be clear, I'm proposing to implement [get_model_metadata](https://github.com/tensorflow/serving/blob/5369880e9143aa00d586ee536c12b04e945a977c/tensorflow_serving/apis/get_model_metadata.proto) which is different than [model status](https://github.com/tensorflow/serving/blob/5369880e9143aa00d586ee536c12b04e945a977c/tensorflow_serving/apis/get_model_status.proto). It's not currently implemented here in [http_rest_api_handler.cc](https://github.com/tensorflow/serving/blob/54b5c76fd860d5e8c08fdb9bca8e01ab2f04b061/tensorflow_serving/model_servers/http_rest_api_handler.cc#L77)

**Comment by netfs** [comment]
Noted. Thanks for offering to implement this. Before you go ahead and implement,
we need to settle on the API structure (uri, verbs and params (if any)). There are
two options:

-  Extend [Model Status API](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/api_rest.md#model-status-api) to return metadata also. This will change the response format (and probably break existing users). Given that this API is not yet released as part of 1.11 release, there should be no actual production users of this API -- so we have a chance to unify model status+metadata fetch under one URI.

- Add a new API: `/v1/models/${model}[/versions/${version}]/metadata` or `/v1/models/metadata/${model}[/versions/${version}]` that mimics the gRPC API

Open to other proposals too. I will think over this a bit and respond (mostly sometime early next week).

**Comment by sagravat** [comment]
I was planning to support the API as follows: `/v1/models/<name>[/versions/<version>]/metadata?fields=signature_def,foo,bar`
But the [server_request_interface](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/util/net_http/server/public/server_request_interface.h) doesn't currently support query parameters; so the http_rest_api_handler  doesn't have any awareness of query parameters.

I could implement the functionality to support query parameters as a separate feature enhancement but in the meantime, I propose the following API without query parameters: `/v1/models/<name>[/versions/<version>]/metadata` which will just return the `GetModelMetadataResponse` object.

**Comment by netfs** [comment]
sounds good. we don't yet need query params, as only one metadata field (signature_def) is supported.

**Comment by harshini-gadige** [comment]
@sagravat - Hi, any update on your contribution ? If there's any PR is created, please share those details here.

**Comment by sagravat** [comment]
@harshini-gadige Yes, it is in master now.

**Comment by seezha** [comment]
Hey, Can someone help with the documentation for this feature? I am unable to use this. i keep running into the Malformed request error. It is unclear how the request is to be formed. The REST api documentation does not include an example for this.

**Comment by sagravat** [comment]
The REST API is a GET request with the following path:

/v1/models/<name>[/versions/<version>]/metadata

For example, curl http://localhost:8501/v1/models/my_model/metadata
