### ISSUE TITLE
Link for TensorFlow Serving architecture on the Readme is broken

### ISSUE THREAD

**Issue by ispmarin** [tensorflow/serving#1120]
### System information
- Github

### Describe the problem
The link for Serving architecture, https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/architecture_overview.md, is broken on the Readme.

### Exact Steps to Reproduce
1. Click on the link "Serving architecture overview"
2. Receive 404.

**Comment by netfs** [comment]
seems like a side-effect of 070e915164211850dd9b56f7ffd52f67ec91d0ef

**Comment by netfs** [comment]
fixed in 9a04fbd140cd33f39cc326ab881d36350bb246b1
