### ISSUE TITLE
'@local_config_nccl//': key "NCCL_HDR_PATH" not found in dictionary and referenced

### ISSUE THREAD

**Issue by gr8Adakron** [tensorflow/serving#1125]
**GPU: DEFORCE GTX 1080i**

- Ubuntu =16.04
- Python=3.6
- Cuda=9.0
- Cudnn=7.0
- NVCC=9.0
- NCCL=2.0
- Bazel = 0.15.2
- Tensorflow-gpu=1.7.0

**TF-serving installation command:**

> **bazel build -c opt --config=cuda tensorflow_serving/...**

============ ERROR ============

> 
> WARNING: /home/afzal/.cache/bazel/_bazel_afzal/ebff775d353ee2682d0e8d53b3b6631f/external/org_tensorflow/tensorflow/contrib/timeseries/python/timeseries/BUILD:354:1: in py_library rule @org_tensorflow//tensorflow/contrib/timeseries/python/timeseries:ar_model: target '@org_tensorflow//tensorflow/contrib/timeseries/python/timeseries:ar_model' depends on deprecated target '@org_tensorflow//tensorflow/contrib/distributions:distributions_py': TensorFlow Distributions has migrated to TensorFlow Probability (https://github.com/tensorflow/probability). Deprecated copies remaining in tf.contrib.distributions are unmaintained, unsupported, and will be removed by late 2018. You should update all usage of `tf.contrib.distributions` to `tfp.distributions`.
> ERROR: /home/afzal/.cache/bazel/_bazel_afzal/ebff775d353ee2682d0e8d53b3b6631f/external/org_tensorflow/tensorflow/contrib/nccl/BUILD:71:1: no such package '@local_config_nccl//': key "NCCL_HDR_PATH" not found in dictionary and referenced by '@org_tensorflow//tensorflow/contrib/nccl:nccl_kernels'
> ERROR: Analysis of target '//tensorflow_serving/model_servers:server_lib' failed; build aborted: Analysis failed
> INFO: Elapsed time: 0.549s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded)
> 
> 

Any help?

**Comment by gr8Adakron** [comment]
@ewilderj  @kchodorow @montanaflynn any help I have spend almost a day with this error. NCCL_HDR?

**Comment by gautamvasudevan** [comment]
Closing - if the dockerfile for gpu builds is unclear, feel free to respond.

**Comment by yiyele** [comment]
same error
