### ISSUE TITLE
Several ideas from analogous open source project

### ISSUE THREAD

**Issue by MisteryX** [tensorflow/serving#1131]
-----------------------
## Feature Request
Hi guys! I was developing just analogous open source project independently for 1 year (https://github.com/MisteryX/0Mind), but now I have found yours. Most of project ideas we are invented just identically, but may be some ideas from my work can be useful for tf.serving.

### Problems and the features
1. Filters pipeline: often before inputting or outputting to\from model the data should be transformed in appropriate form for NN processing. More than that, for typical tasks NLP\Image recognition\Sound processing the set of such filters is standard. This kind of module can be a set of plugins (user composed). Of course, pre\postprocessing can be done on clients, but it still useful when you do group model inference.

2. If you plan a distributive architecture, I guess, you should develop an independent arbitrary module, that routes requests, balances loading on cluster nodes and follows the execution graph of the skill network for group model inference. I have it in my project.

3. If you plan for developing the web interface - it can be useful to load models as one file\arch, specify some model metadata, compose graph for group inference and so on...

4. I know that you should follow the Google corp. standards, but for end users is more conveniently to load models prepared not only in TF but also in other frameworks, so ONNX support for model Loader will be useful.

**Comment by harshini-gadige** [comment]
@gautamvasudevan  - Hi, can this be changed to Contributions welcome ?

**Comment by gautamvasudevan** [comment]
I think some of these changes need some thorough design review.

It would make it easier to track if these were broken into separate feature requests :)

**Comment by harshini-gadige** [comment]
@MisteryX  -  Hi, thanks for your ideas. Request you to break this into simple features(by creating a new issue for each as a **feature request** with clear explanation on the approach). That would help us to track them clearly and would make it easy for your contribution. Hence closing this issue. Thanks !
