### ISSUE TITLE
resnet_client.py doesn't work well

### ISSUE THREAD

**Issue by lightsocks** [tensorflow/serving#1133]
When i use [resnet_client.py](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/resnet_client.py) to invoke the REST API provided by the[model](https://github.com/tensorflow/models/tree/master/official/resnet) i downloaded. it returns http status 400 and "Type: Object is not of expected type: float" }"  error.
How to invoke it correctly.

**Comment by netfs** [comment]
can you please post complete list of commands use to start the model server (with resnet model) and the corresponding command line that you used to invoke the resnet_client.py?

**Comment by gautamvasudevan** [comment]
Try downloading a SavedModel from there that uses JPEG as input and see if that works. I’m guessing you built or downloaded on that expects a tensor.

**Comment by harshini-gadige** [comment]
@lightsocks  - Hello, is this still an issue ? Feel free to close this issue if it has been resolved.

**Comment by gautamvasudevan** [comment]
Please see [this blog post](https://medium.com/tensorflow/serving-ml-quickly-with-tensorflow-serving-and-docker-7df7094aa008) for a clear example of how to use the script.
