### ISSUE TITLE
Version constants not updated for 1.11.0 tensorflow_model_server

### ISSUE THREAD

**Issue by emacski** [tensorflow/serving#1134]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow Serving installed from (source or binary)**: source
- **TensorFlow Serving version**: 1.11.0

### Describe the problem
The current `tensorflow_model_server` version constants in the source for the `1.11.0` tag (and `master`) produce this version string: `1.10.0-dev`

https://github.com/tensorflow/serving/blob/1.11.0/tensorflow_serving/model_servers/version.h
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/version.h

Example:
```bash
tensorflow_model_server --version
TensorFlow ModelServer: 1.10.0-dev
TensorFlow Library: 1.11.0
```

**Comment by netfs** [comment]
clearly this commit did not update version.h file (it should have):

https://github.com/tensorflow/serving/commit/c1286a83133ed57ed797c8ce4ec0466bbc561d79

**Comment by netfs** [comment]
thanks for reporting the bug!

**Comment by harshini-gadige** [comment]
Closing this issue as a fix is submitted and merged. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
