### ISSUE TITLE
Error with tools/bazel_in_docker.sh if username == groupname

### ISSUE THREAD

**Issue by vfdev-5** [tensorflow/serving#1137]
Following code:
https://github.com/tensorflow/serving/blob/28d1c0d7349fe1392c8b7170d5d7dfc64a9d284d/tools/bazel_in_docker.sh#L48-L49
will produce the error:
```
useradd: group user exists - if you want to add this user to that group, use -g.
chroot: invalid user
```
if username and groupname are the same.

**EDIT:** A simple solution can be to add `-N`:
```
 cmdline+="; id -u ${username} &>/dev/null || useradd -N ${username} && usermod -o -u ${uid} -g ${gid} ${username}" 
```

**Comment by netfs** [comment]
Thanks for the report. Can you please send a PR to fix this issue? Thanks again!
