### ISSUE TITLE
Cannot decode web-safe b64 string input when inferencing with RESTful API

### ISSUE THREAD

**Issue by lagidigu** [tensorflow/serving#1141]
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow Serving installed from (source or binary)**: Source
- **TensorFlow Serving version**: Latest

A model exported for serving takes in a string as an input that gets b64 decoded:
```
x_input = tf.placeholder(tf.string, shape=[None], name='input_variable_00')

x_input_ = tf.io.decode_base64(x_input)
```
I then call it in postman with the following body: 

```
{
	"instances": [
		{
			"b64": "HBwcIiIiIiIiHh4eGhoaGBgYExMTEBAQERERERERDw8PCQkJBQ.."
		}
	]
}
```

The b64 string has been encoded in python using base64.urlsafe_b64encode().

The only error received is: 

`{ "error": "Failed to process element: 0 of \'instances\' list. Error: Invalid argument: Unable to base64 decode" }`

**Comment by lagidigu** [comment]
Update: There should be no web safe encoding, just regular encoding with "+" and "/", and no `tf.io.decode_base64(x_input)`, because serving takes care of that. 

This solves the issue.

**Comment by xuehuachunsheng** [comment]
So, if we do not use tf.decode_base64(x_input), what should we do for the input with base64 encoding string?

**Comment by lagidigu** [comment]
> So, if we do not use tf.decode_base64(x_input), what should we do for the input with base64 encoding string?

Serving automatically decodes the b64 string to a bytestring. You could therefore use a string tensor, and then use something like tf.image.decode_image or tf.image.decode_jpeg. This will convert the bytestring to a tensor of the specified type.

**Comment by Paperone80** [comment]
@lagidigu, thanks a lot for figuring this out! I went through the trouble myself! 
```
This works for me:
import base64
import requests
import json

image_path = '/home/IMG_2409.jpg'

image_base64 = base64.b64encode(open(image_path, 'rb').read()).decode("utf-8")

data = json.dumps(
    {'instances': [
        {'inputs': {'b64': image_base64}}
        , {'inputs': {'b64': image_base64}}
        ,
               ]
    }
)

json_response = requests.post("http://localhost:8501/v1/models/1:predict", data=data)
```

For completeness the following request formats did work for me as well:

```
data = json.dumps(
    {'instances': [
        {'b64': base64.b64encode(encoded_jpg).decode("utf-8")}
        , {'b64': base64.b64encode(encoded_jpg).decode("utf-8")}
        , 
               ]
    }
)

data = json.dumps(
    {'inputs': [
        {'b64': base64.b64encode(encoded_jpg).decode("utf-8")}
        , {'b64': base64.b64encode(encoded_jpg).decode("utf-8")}
        , 
               ]
    }
)
```

> #NB: creates a json_response['outputs'] with len of [detection_masks==2, raw_detection_scores==2, num_detections==2, detection_classes==2, detection_boxes==2, raw_detection_boxes==2, detection_scores==2]


If someone from the Google TF SERVING team reads this, please put a note in your documentation that your very own function is NOT compatible: 

`image_base64 = tf.io.encode_base64(input=open(image_path, 'rb').read(), pad=False, name=None).eval().decode("utf-8")`

I understand that it creates a web-safe base64 encoding. That is very frustrating and inconsistent that especially on GCP you seem to require web-safe but not in TF SERVING. 

Also, even though it is unlikely that you have access to tf.io.encode_base64() in a client which generates the JSON request. However, outsourcing some preprocessing to the server via a FLASK service or similar which uses tf.io.encode_base64() and then sends the JSON sends TF SERVING is not unlikely though.

**Comment by benjtlv** [comment]
> > So, if we do not use tf.decode_base64(x_input), what should we do for the input with base64 encoding string?
> 
> Serving automatically decodes the b64 string to a bytestring. You could therefore use a string tensor, and then use something like tf.image.decode_image or tf.image.decode_jpeg. This will convert the bytestring to a tensor of the specified type.

How do you know that ? And how is it done ? Because I am currently stuggling with that. A data scientist in my team wrote a prediction script and I'm trying to get the same results going through tf serving but what I get is totally different

**Comment by lagidigu** [comment]
> 
> 
> > > So, if we do not use tf.decode_base64(x_input), what should we do for the input with base64 encoding string?
> > 
> > 
> > Serving automatically decodes the b64 string to a bytestring. You could therefore use a string tensor, and then use something like tf.image.decode_image or tf.image.decode_jpeg. This will convert the bytestring to a tensor of the specified type.
> 
> How do you know that ? And how is it done ? Because I am currently stuggling with that. A data scientist in my team wrote a prediction script and I'm trying to get the same results going through tf serving but what I get is totally different

If you send me the specific extract from the script as well as the expected output I can help you out :)
