### ISSUE TITLE
End to end documentation on Inference using TensorFlow Serving

### ISSUE THREAD

**Issue by gautamkmr** [tensorflow/serving#1152]
Currently TF Serving documentation provides a very minimal example [here](https://www.tensorflow.org/serving/serving_basic) to perform inference. There is a no documentation on using TensorFlow Serving based on checkpoint. 

For e.g. lets say I trained resnet50 on ImageNet data set using below command 

`tf_cnn_benchmarks.py --model resnet50 --num_epochs=90 --batch_size 128 --data_name=imagenet  --data_dir=/imagenet/data --train_dir=/model/checkpoint  --variable_update horovod --horovod_device gpu --weight_decay=1e-4 --use_fp16 `

At the end it creates check points. Is there any documentation which talks about how can I use this generated checkpoint on TensorFlow Serving and perform inference? Having such documentation will be really helpful.

**Comment by harshini-gadige** [comment]
@gautamkmr - Hi, please check [this link](https://towardsdatascience.com/how-to-deploy-machine-learning-models-with-tensorflow-part-1-make-your-model-ready-for-serving-776a14ec3198). It takes you thorough steps to deploy and make your model ready for serving.

**Comment by harshini-gadige** [comment]
@gautamkmr  - Hi, feel free to close this issue if it's solved.

**Comment by gautamkmr** [comment]
@harshini-gadige the above documentation still helps I am yet to try it out. But yeah feel free to close it.
