### ISSUE TITLE
Op type not registered 'TanhGrad'

### ISSUE THREAD

**Issue by Mazecreator** [tensorflow/serving#116]
I have the latest development version of TF 0.9.0 and have a python script I have been running and saving the check point files.  Tensor_serving is not part of that bundle so I couldn't include the session_bundle to build the inference directly from that script.

I wrote a 2nd script that is compiled with TensorFlow_serving session bundle which sets up the same graph and loads the checkpoint file and saves it as a session bundle.  This all worked well and I can see all the files.

The problem when I then load the session bundle into the C++ program to run the inference.  I get the following error:
E tensorflow_serving/LoadModel/inference.cc:233] Fail to load tensorflow export: Op type not registered 'TanhGrad'

I due use Tanh as the Nonlinear activation function for each layer of this network.

Any ideas?  I assume something changed in the name of the Gradient Opt for Tanh but this is not syncronised to Tensorflow_serving?  I tried re-installing the latest Tensorflow_serving clone as well.  I have an Ubuntu 15.10 box, with CUDA 7.5/cuDNN 4.0.

**Comment by chrisolston** [comment]
I think what you mentioned about tensorflow_serving not being synced to the latest tensorflow is probably the culprit. There was a change to tensorflow's tanh on june 30 (https://github.com/tensorflow/tensorflow/commit/5a8faefbad514c88ca5161ebc901bb9bd74d932d), and the most recent time tensorflow_serving updated to tensorflow head was on June 20 (https://github.com/tensorflow/serving/commit/e960bfd33033a82cc7733dfed0cf55d61c464fe1).

I will work on updating tensorflow_serving to tensorflow head this week. Stay tuned.

**Comment by chrisolston** [comment]
Quick update: we've hit a speed-bump on updating to tensorflow head. It may not happen until early next week.

In the mean time, you can unblock yourself by patching in tensorflow head yourself.

**Comment by Mazecreator** [comment]
Hi Chris,

I am not sure how to patch the tensorflow_serving with the tensorflow.  I would love to!  Is this a simply copy over ~/serving/tensorflow with the ~/tensorflow/ repository?

**Comment by kirilg** [comment]
From the tensorflow serving repo, you can run:

```
cd tensorflow
git checkout master
git pull
git log -1  # To verify the latest commit is from yesterday
cd ..
```

**Comment by Mazecreator** [comment]
Thanks,

Worked like a charm.

**Comment by kirilg** [comment]
Tensorflow Serving is now synced to the latest Tensorflow, so the op should be available at head.
