### ISSUE TITLE
BUG: cp: cannot stat 'bazel-serving/tensorflow_serving/apis/*_pb2.py': No such file or directory

### ISSUE THREAD

**Issue by karthikvadla** [tensorflow/serving#1160]
Hi, I'm working on creating a dockerfile with MKL settings, but prior to that tried building docker image based of this [dockerfile](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel)  from official repo, then found below error.

```
cp: cannot stat 'bazel-serving/tensorflow_serving/apis/*_pb2.py': No such file or directory
The command '/bin/sh -c bazel build --color=yes --curses=yes     ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS}     tensorflow_serving/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package     /tmp/pip &&     pip --no-cache-dir install --upgrade /tmp/pip/tensorflow_serving*.whl &&     rm -rf /tmp/pip' returned a non-zero code: 1
```

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  CentOS Linux release 7.5.1804 (Core)
- **TensorFlow Serving installed from (source or binary)**:  using commit : 274e97a

### Exact Steps to Reproduce
Used below command to build image
```
docker build -f Dockerfile.devel -t tensorflow/serving:devel  --build-arg TF_SERVING_VERSION_GIT_COMMIT=274e97a  --build-arg TF_SERVING_BUILD_OPTIONS="-c opt"  .
```

### Source code
Failing at this step
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/pip_package/build_pip_package.sh#L47

**Comment by karthikvadla** [comment]
/type:bug/performance

**Comment by netfs** [comment]
does this work on master or on commit that is very recent (say yesterday's)?

**Comment by karthikvadla** [comment]
Okay let me try that once.

**Comment by karthikvadla** [comment]
Tested with laster `master` commit. Things are good now. 
Closing this issue.
