### ISSUE TITLE
Tutorial examples don't work

### ISSUE THREAD

**Issue by raam86** [tensorflow/serving#1161]
### System information
Docker on OSx, following this guide: 
https://www.tensorflow.org/serving/serving_advanced

### Describe the problem
This commit https://github.com/tensorflow/serving/commit/793fd90ee41ac34fa4c9261eef2d2c908dca9735
Broke the examples since the build targets no longer exist

### Exact Steps to Reproduce
```
tools/bazel_in_docker.sh bazel build -c opt \
  tensorflow_serving/example:mnist_saved_model
```
complains it can't find the file and suggests a add .py extension which is wrong.

###  Possible fix: 
either change the tutorial to use `//tensorflow_serving/example:resnet_client_cc` target or replace the examples back in. 

I would be happy to take this if you have a few pointers

**Comment by gautamkmr** [comment]
Have the same issue with this document 
https://www.tensorflow.org/serving/serving_inception

I really feel we should have a better document to use TF serving directly from checkpoint, at least saved model, simple save etc solutions are too confusing and requires code changes in training script.

**Comment by gautamvasudevan** [comment]
Do [these instructions](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/serving_advanced.md) work for you?

**Comment by charlesverge** [comment]
I've also put together a sample with the intention as to be simple as possible to create a saved_model.pb file for use with the Tensorflow server and use a Tensorflow estimator. Feedback welcome. https://github.com/charlesverge/tensorflow_examples

**Comment by gautamkmr** [comment]
@gautamvasudevan  yes that works but how about `https://www.tensorflow.org/serving/serving_inception` . I know this has been deprecated by TensorFlow but I don't see any docker image with tensorflow_model_server. Would you please point me some docker image which has below path so that I can make use of `https://www.tensorflow.org/serving/serving_inception` ?

**`serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server`**

**Comment by raam86** [comment]
@gautamvasudevan yes it does!

**Comment by gautamvasudevan** [comment]
The site has been updated and serving_inception has been removed. Please follow [this blog](https://medium.com/tensorflow/serving-ml-quickly-with-tensorflow-serving-and-docker-7df7094aa008) for updated instructions.
