### ISSUE TITLE
ERROR: Unrecognized option: --input_file=/Users/jyy/model/frozen_inference_graph.pb

### ISSUE THREAD

**Issue by wangyongqi** [tensorflow/serving#1171]
Hello, I trained the ". pb" file on the cloud server through ssdmobilenet. Now I want to convert it into tflite format, but it failed, and the following error occurred. This is my code. Who can help me? Thank you. 

bazel run --config=opt tensorflow/contrib/lite/toco:toco --input_file=/Users/jyy/model/frozen_inference_graph.pb  --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --output_file=/Users/jyy/wechat_model/wechat.lite --inference_type=FLOAT --input_type=FLOAT --input_arrays=input --output_arrays=predictions --input_shapes=1,224,224,3
ERROR: Unrecognized option: --input_file=/Users/jyy/model/frozen_inference_graph.pb

**Comment by wangyongqi** [comment]
> Hello, I trained the ". pb" file on the cloud server through ssdmobilenet. Now I want to convert it into tflite format, but it failed, and the following error occurred. This is my code. Who can help me? Thank you.
> 
> bazel run --config=opt tensorflow/contrib/lite/toco:toco --input_file=/Users/jyy/model/frozen_inference_graph.pb --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --output_file=/Users/jyy/wechat_model/wechat.lite --inference_type=FLOAT --input_type=FLOAT --input_arrays=input --output_arrays=predictions --input_shapes=1,224,224,3
> ERROR: Unrecognized option: --input_file=/Users/jyy/model/frozen_inference_graph.pb

**Comment by Davari393** [comment]
i have same error when i run :
bazel run /home/davari/virtualenvironments/detection_on_mobile/lib/python3.6/site-packages/tensorflow_core/lite/toco --output_file=converted_model.tflite --input_arrays=image_tensor --output_arrays=concat --input_shapes=1,300,300,3 --input_file=./ssdlite_mobilenet_v2_coco_2018_05_09/tflite_graph.pb

and my error is:
ERROR: Unrecognized option: --output_file=converted_model.lite
or:
ERROR: Unrecognized option: --output_file=converted_model.tflit
