### ISSUE TITLE
Start gRPC ModelServer if at least one model's version is present

### ISSUE THREAD

**Issue by asamadiya** [tensorflow/serving#1175]
### Describe the problem the feature is intended to solve
Tensorflow (TF) serving's gRPC server doesn't startup until there is at least one version of each model listed in the Model Config.
But it is not always possible to have all the models listed in Model Config ready at TF serving process startup. This stops me from serving whatever model we have available at that point in time. 
As part of this feature request, I want to also understand any technical reasons behind this restriction and explore options to optionally remove this restriction.

### Describe the solution
TF process is spawned with a Model Config that lists ModelA and ModelB. ModelA version 1 is present on the filesystem. I want TF process to startup its gRPC server and start serving ModelA.1 whilst waiting for ModelB's versions to show up.
Pro: Model Config lists all the Models that TF process would serve in its life time. If at least one version of some model becomes available, TF process is ready to serve traffic.

Another solution:
A holistic solution would be to make (if it isn't already) Model Config reload efficient and only proportionally expensive, by optionally auto-inferring "add Model" (and "remove Model") Model Config mutations. 

### Describe alternatives you've considered
Say I have ModelA version 1 ready but ModelB version 1 and 2 are pending deployment, one alternative is to start off TF serving process with a Model Config that lists only ModelA. As ModelB's versions become available,  Model Config can be reloaded with a new one listing both Model A and Model B.
Con: Any potential overhead of reloading the entire Model Config for every new Model's first version.

### Additional context
I want to decouple Model Deployment and Model Serving. I want to be able to deploy and register models lazily, potentially avoiding an expensive Model Config reload. This can happen during model experimentation.

**Comment by vitalyli** [comment]
I started with empty model set. Then I implemented a patch to load models once they are configured on demand. See pending pull request.

**Comment by ajbouh** [comment]
@vitalyli how did you start with an empty model set? When I tried this I kept seeing error messages that prevented the gRPC service from starting

**Comment by christisg** [comment]
This feature request makes sense. We'll evaluate and provide status update at a later time.

**Comment by singhniraj08** [comment]
@asamadiya,

If you would like to serve multiple models, or configure options like polling frequency for new versions, you may do so by writing a Model Server config file. You may provide this configuration file using the `--model_config_file` flag and instruct Tensorflow Serving to periodically poll for updated versions of this configuration file at the specifed path by setting the 
`--model_config_file_poll_wait_seconds` flag.
There is another way to reload model server configurations by issuing [HandleReloadConfigRequest](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/model_service.proto#L22) RPC calls to the server and supplying a new Model Server config programmatically. 

Once your model is deployed, you can update the model config file and set model serve to either reload the file automatically or use HandleReloadConfigRequest RPC call to supply new config file. 

Ref: [Tensorflow Serving Configuration](https://www.tensorflow.org/tfx/serving/serving_config#model_server_configuration). Thank you.
