### ISSUE TITLE
/proc/self/cwd/tools/gen_status_stamp.sh: No such file or directory

### ISSUE THREAD

**Issue by knightcode** [tensorflow/serving#1181]
Mac OS Mojave 10.14.1
Installing tensorflow serving from source
Bazel 0.18.0- installed via macports

My steps:
```
rm -rf /private/var/tmp/_bazel*
bazel clean
git pull origin master    <--- https://github.com/tensorflow/serving
bazel build -c opt tensorflow_serving/...
```

The final lines of output are:
```
WARNING: /docs/projects/therapybot/serving/tensorflow_serving/servables/tensorflow/testdata/BUILD:37:1: in py_binary rule //tensorflow_serving/servables/tensorflow/testdata:export_half_plus_two: target '//tensorflow_serving/servables/tensorflow/testdata:export_half_plus_two' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
INFO: Analysed 357 targets (342 packages loaded).
INFO: Found 357 targets...
ERROR: Process exited with status 127: Process exited with status 127
/bin/sh: /proc/self/cwd/tools/gen_status_stamp.sh: No such file or directory
INFO: Elapsed time: 75.434s, Critical Path: 0.04s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

This seems like a relatively easy fix where ${PWD} could be in place of `/proc/self/cwd`

**Comment by burness** [comment]
I have the same problem, anyone can help it ?

**Comment by gautamvasudevan** [comment]
Unfortunately, this comes from the [bazel.rc file](https://github.com/tensorflow/serving/blob/master/tools/bazel.rc#L39), which AFAIK doesn't support shell script stuff. It *might* work with a path to %workspace% though.

**Comment by knightcode** [comment]
changing it to a normal relative path seemed to get me further down the road:

```
build --workspace_status_command=tools/gen_status_stamp.sh
```

**Comment by burness** [comment]
It seems to be that the issue happens between tensorflow serving  and
macboss, I use docker and it's ok now

PJ <notifications@github.com> 于2018年11月20日周二 上午8:15写道：

**Comment by knightcode** [comment]
Not going to install docker just for this.

**Comment by tobegit3hub** [comment]
Thanks @knightcode  and `--workspace_status_command=tools/gen_status_stamp.sh` work for me.

BTW, building TensorFlow Serving in docker is not good enough if we want the build the binary for MacOS.
