### ISSUE TITLE
HTTP gzip support causes build failure when targeting 32-bit (armhf)

### ISSUE THREAD

**Issue by emacski** [tensorflow/serving#1188]
## (Possible) Bug Report

This issue seems to only affect (some?) 32-bit targets. In my cursory search of this project I didn't come across any official or unofficial directives to support 32-bit platforms, so I understand if this is not within the current scope of things. Regardless, I thought I would err on the side of caution and report this issue anyway.

### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04.5 LTS (x86_64 host, armhf target)
- **TensorFlow Serving installed from (source or binary)**: Source
- **TensorFlow Serving version**: 1.12.0

### Describe the problem

**Note**: Prior to version 1.12.0, there were no perceived issues building for or running on armhf (ARMv7-A)

With the introduction of gzip support for the REST API, `tensorflow_model_server` fails to build when targeting armhf (`arm-linux-gnueabihf-g++ (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9)`, `-march=armv7-a`)

There is a reliance on an implicit pointer type conversion between `size_t*` and the pointer type for the zlib defined `uLongf`. This is valid when targeting x86_64 or aarch64 as the base type of `size_t` and `uLongf` are both defined as `long unsigned int`. However, when targeting armhf (ARMv7-A) `size_t` is defined as `unsinged int` as shown in the log snippet.

By casting the offending pointer just as the other pointers are being cast, I can successfully build for and run on the ARMv7-A target as one possible solution.

### Source code / logs
Build Error

```
tensorflow_serving/util/net_http/server/internal/evhttp_request.cc:
In member function 'void tensorflow::serving::net_http::EvHTTPRequest::UncompressGzipContent(void*, size_t, void**, size_t*)':
tensorflow_serving/util/net_http/server/internal/evhttp_request.cc:218:50:
error: invalid conversion from 'size_t* {aka unsigned int*}' to 'uLongf* {aka long unsigned int*}' [-fpermissive]
       reinterpret_cast<Bytef*>(input), input_size);
                                                  ^
```

See `uncompressed_input_size` in code snippet below.
https://github.com/tensorflow/serving/blob/1.12.0/tensorflow_serving/util/net_http/server/internal/evhttp_request.cc#L205
```cpp
void EvHTTPRequest::UncompressGzipContent(void* input, size_t input_size,
                                          void** uncompressed_input,
                                          size_t* uncompressed_input_size) {
  int64_t max = handler_options_->auto_uncompress_max_size() > 0
                    ? handler_options_->auto_uncompress_max_size()
                    : ZLib::kMaxUncompressedBytes;

  // our APIs don't need expose the actual content-length
  *uncompressed_input_size = static_cast<size_t>(max);

  ZLib zlib;
  int err = zlib.UncompressGzipAndAllocate(
      reinterpret_cast<Bytef**>(uncompressed_input), uncompressed_input_size,
      reinterpret_cast<Bytef*>(input), input_size);
  if (err != Z_OK) {
    ABSL_RAW_LOG(ERROR, "Got zlib error: %d", err);
  }
}
```
https://github.com/tensorflow/serving/blob/1.12.0/tensorflow_serving/util/net_http/compression/gzip_zlib.h#L191
```cpp
int UncompressGzipAndAllocate(Bytef **dest, uLongf *destLen,
                                const Bytef *source, uLong sourceLen);
```

**Comment by wenbozhu** [comment]
Thanks for reporting this and the root-cause.

To confirm: have your verified that tensor-flow-serving actually runs on armhf (ARMv7-A)?
