### ISSUE TITLE
Non-Docker build with CUDA - import error when not setting CUDA path explicitly in ./configure for bazel-0.2.0 / bazel-0.3.0

### ISSUE THREAD

**Issue by revilokeb** [tensorflow/serving#119]
My setup: Ubuntu 14.04 LTS with CUDA 7.5 + cuDNN5, tf serving a4013d5 (tested on two different machines)

Using **bazel 0.2.0** (set up as described [here] (https://tensorflow.github.io/serving/setup)):
- providing symlinked /usr/local/cuda (default) to ./configure results in following error for build command `bazel build -c opt --config=cuda tensorflow_serving/...`: 

> ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory,

 although libcudart.so.7.5 can be found in /usr/local/cuda-7.5/lib64 
- setting /usr/local/cuda-7.5 as CUDA path in ./configure (plus explicitly setting CUDA and cuDNN version) is avoiding the error and gives succesful build

Using **bazel 0.3.0**:
- can't avoid the above import error: 

> ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

Can anyone confirm that error / behavior?

**Comment by LiberiFatali** [comment]
Try this:

> 32-bit: sudo ldconfig /usr/local/cuda/lib

> 64-bit: sudo ldconfig /usr/local/cuda/lib64

**Comment by revilokeb** [comment]
@LiberiFatali many thanks, did the job!
