### ISSUE TITLE
Did you take a look at [this example client](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_client.cc)?

### ISSUE THREAD

**Issue by oregonduckman** [tensorflow/serving#1191]
_Originally posted by @kirilg in https://github.com/tensorflow/serving/issues/625#issuecomment-337946783_
The link is dead does anyone know of another c++ example?

**Comment by ymodak** [comment]
You can take a look at this [example](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/resnet_client.cc) may be. Let me know if this works for you.
