### ISSUE TITLE
 libcusolver.so.9.0: cannot open shared object file

### ISSUE THREAD

**Issue by gautamkmr** [tensorflow/serving#1193]
**Command**:  sudo /tmp/tensorflow_model_server --port=8500 --rest_api_port=8501 --mode_name=mnist --mode_base_path=/home/ubuntu/serving/models/mnist & 

(tensorflow_p27) ubuntu@ip-172-31-89-1:/usr/local/cuda-9.0/lib$ /tmp/tensorflow_model_server: error while loading shared libraries: **libnccl.so.2**: cannot open shared object file: No such file or directory

**:/usr/local/cuda-9.0/lib$ ls -lhrt** 
-rw-rw-r-- 1 root root 83M Sep 21 01:21 libnccl_static.a
-rwxrwxr-x 1 root root 77M Sep 21 01:21 libnccl.so.2.3.5
lrwxrwxrwx 1 root root  16 Sep 21 01:21 libnccl.so.2 -> libnccl.so.2.3.5
lrwxrwxrwx 1 root root  12 Sep 21 01:21 libnccl.so -> libnccl.so.2

(tensorflow_p27) ubuntu@ip-172-31-89-1:/usr/local/cuda-9.0/lib$ echo $LD_LIBRARY_PATH
**/usr/local/cuda-9.0/lib/:**/usr/local/cuda-9.0/lib64:/usr/local/cuda-9.0/extras/CUPTI/lib64:/usr/local/cuda-9.0/lib:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:

(tensorflow_p27) ubuntu@ip-172-31-89-1:/usr/local/cuda-9.0/lib$ **ldd /tmp/tensorflow_model_server** 
	linux-vdso.so.1 =>  (0x00007ffdb4555000)
	libnccl.so.2 => /usr/local/cuda-9.0/lib/libnccl.so.2 (0x00007f41fa43b000)
	libnvinfer.so.4 => not found
	libcusolver.so.9.0 => /usr/local/cuda-9.0/lib64/libcusolver.so.9.0 (0x00007f41f5840000)
	libcublas.so.9.0 => /usr/local/cuda-9.0/lib64/libcublas.so.9.0 (0x00007f41f240a000)
	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f41f148f000)
	libcudnn.so.7 => /usr/local/cuda-9.0/lib64/libcudnn.so.7 (0x00007f41df156000)
	libcufft.so.9.0 => /usr/local/cuda-9.0/lib64/libcufft.so.9.0 (0x00007f41d70b5000)
	libcurand.so.9.0 => /usr/local/cuda-9.0/lib64/libcurand.so.9.0 (0x00007f41d3151000)
	libcudart.so.9.0 => /usr/local/cuda-9.0/lib64/libcudart.so.9.0 (0x00007f41d2ee4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f41d2cc7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f41d2ac3000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f41d28a1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f41d2598000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f41d2390000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f41d200e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f41d1df8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f41d1a2e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4229da7000)
	libnvidia-fatbinaryloader.so.396.44 => /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.396.44 (0x00007f41d17e2000)

**Comment by gautamvasudevan** [comment]
Docker remains our canonical approach to building and testing the GPU environment currently. The [GPU Development Dockerfile](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel-gpu) itself is effectively the set of steps to run to get this to work on Ubuntu 16.04. You can just run those commands manually outside of docker as long as you create the same environment.

RUN means run it
ENV or ARG are just environment variables to set.

Closing this issue - if you're still having trouble, it will be helpful to list out all the details (as asked in the bug template), including what platform you're building on, and what exact steps you ran.

**Comment by gautamkmr** [comment]
Thank you I will also run it on ubuntu 16.04.

However on a side note `FROM nvidia/cuda:9.0-base-ubuntu16.04 as base_build` this itself brings lots of goodies for Docker images where bare metal os will not have unless I go to this NVIDIA docker image and figure out what they do.

**Comment by gautamvasudevan** [comment]
Likely yes - to a degree is this is on purpose, as NVIDIA is the appropriate source of truth for their software. That said, their docker images are (so far) very simple.
