### ISSUE TITLE
tf-serving restful bool type problem? can not distinguish bool for a Scalar?

### ISSUE THREAD

**Issue by Milittle** [tensorflow/serving#1199]
When i use the restful API, I transport the bool to request the result. But i got the follow error:

![7f701bf54643a3c5a373f46f13018bb](https://user-images.githubusercontent.com/9550695/49276085-527ec680-f4b8-11e8-9f47-75c8eaa54643.png)

I use the follow code to dump json data:
![21b6e5fa716e047e1ab222c84654d1e](https://user-images.githubusercontent.com/9550695/49276143-8eb22700-f4b8-11e8-8c8c-5b79c6bd6524.png)

Who can told me why tf-serving can not think this bool is a Scalar?

**Comment by Milittle** [comment]
No One？ any help？

**Comment by harshini-gadige** [comment]
@Milittle  Can you try with the latest version and see if you are running into the same issue ?

**Comment by Milittle** [comment]
> @Milittle Can you try with the latest version of Tensorflow Model Server and see if you are running into the same issue ?

I try the latest version tenosrflow_model_server, but i got the same issue. The next, what should i do. Thanks~

**Comment by Milittle** [comment]
> @Milittle Can you try with the latest version of Tensorflow Model Server and see if you are running into the same issue ?
When i try request the inference, i got the error log:
**2018-12-05 09:29:52.520402: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at conv_ops.cc:437 : Invalid argument: Computed output size would be negative: -1 [input_size: 2, effective_filter_size: 11, stride: 4]**

**Comment by Milittle** [comment]
> @lilao Any inputs please ?
`__author__ = 'Milittle'

import requests
import json
import numpy as np
import glob
import time
from PIL import Image


def get_defect_img_list(path, recursive=True):
    return glob.glob(path)

def inference_defect(img_list):
    infer_img = []
    for i in img_list[0:2]:
        img = Image.open(i)
        img_array = np.array(img).reshape((224, 224))
        infer_img.append(img_array.tolist())
        if len(infer_img) == 2:
            ins = {"in": infer_img, "train_sign": False, "keep_prob": 1.0}
            data = json.dumps({"instances": [ins]})
            begin_time = time.time()
            reponse = requests.post('http://localhost:9001/v1/models/defect:predict', data = data)
            end_time = time.time()
            print('consume time is: {}ms'.format(round((end_time - begin_time) * 1000)))
            infer_img.clear()
            print(reponse.text)
            # pre_data = reponse.json()
            # print(pre_data)
            # if 'error' in pre_data.keys():
            #     print(pre_data)
            # if 'predictions' in pre_data.keys():
            #     for j in pre_data['predictions']:
            #         with open('out.txt','a') as f:
            #             f.write(str(j))
            #             f.write('\n')
def main():
    img_list = get_defect_img_list('./data/test/*/*.bmp')
    # img_list = sorted(img_list, key = lambda x : int(x[15:-4]))
    inference_defect(img_list)

if __name__ == '__main__':
    main()`
I can give you my request code. Then, the infer_img is the image data, and train_sign and keep_prob.

**Comment by netfs** [comment]
few suggestions (in order to try):

- can you try (lowercase) `false` (JSON spec needs it). see [mappings](https://www.tensorflow.org/serving/api_rest#json_mapping) for details.

- can you post the serving signatures from your saved model? you can use [saved_model_cli](https://www.tensorflow.org/guide/saved_model#show_command)

```
$ saved_model_cli show --dir /tmp/saved_model_dir --all
```

- you seem to be sending image (binary) bytes ("in" tensor) in your JSON request. i am surprised that works. if your model/graph requires binary image bytes, you want to enclose these bytes in a JSON object keyed by `b64`. see [encoding binary values](https://www.tensorflow.org/serving/api_rest#encoding_binary_values) section of the AP for more details.

**Comment by hgadig** [comment]
Closing this issue as it is in "awaiting response" status for more than 7 days. Feel free to add your comments and we will reopen the issue.

**Comment by BenoitWang** [comment]
Hi @Milittle , did you solve this problem please?

**Comment by BenoitWang** [comment]
Hi @Milittle , did you solve this problem please? I am having a same problem.
