### ISSUE TITLE
REST Metadata appears to be inconsistent with real usage

### ISSUE THREAD

**Issue by alextdavis** [tensorflow/serving#1208]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Pop!_OS (Ubuntu-like) 18.10
- **TensorFlow Serving installed from (source or binary)**: Docker Hub
- **TensorFlow Serving version**: 1.12.0

### Describe the problem
In some situations, the information provided at the route `/v1/models/model_name/metadata` reports inputs and outputs for SignatureDefs which don't match what works in real usage. In my case, I exported a `tf.estimator.DNNClassifier`, and in the response from the `metadata` route, under the `classification` SignatureDef, it says the input should be a `DT_STRING` of shape `[-1]`, but it accepts an array of JSON Objects, and it says the output should be a `scores`, type `DT_FLOAT`, size `[-1, 3]` and `classes`, type `DT_STRING`, size `[-1, 3]`, but the real output is `"results": [[[<class>, <score>], [<class>, <score>], ...]]`

### Exact Steps to Reproduce
- Clone [github.com/tensorflow/models](https://github.com/tensorflow/models/), and checkout 03612984e9f7565fed185977d251bbc23665396e
- Insert the following lines at [samples/core/get_started/premade_estimator.py:61](https://github.com/tensorflow/models/blob/c9f03bf6a8ae58b9ead119796a6c3cd9bd04d450/samples/core/get_started/premade_estimator.py#L61)

      feature_spec = tf.feature_column.make_parse_example_spec(my_feature_columns)
      serving_input_receiver_fn_parsing = tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)
      classifier.export_saved_model("/tmp/exports/iris_parsing", serving_input_receiver_fn_parsing)

- Run samples/core/get_started/premade_estimator.py
- Start serving, by running:  

      sudo docker run -it -p 8501:8501\
          --mount type=bind,source=/tmp/exports/iris_parsing,target=/models/iris_parsing\
          -e MODEL_NAME=iris_parsing\
          tensorflow/serving:1.12.0

- Run `curl localhost:8501/v1/models/iris_parsing/metadata` and observe the specified input and output for the `classify` SignatureDef.
- Run the following, and observe that it works.

      curl -H "Content-Type: application/json"\
           -X POST\
           -d '{"examples": [{
                     "SepalLength": 2.3, 
                     "SepalWidth": 3.4, 
                     "PetalLength": 2.2, 
                     "PetalWidth": 0.81}]}'\
           localhost:8501/v1/models/iris_parsing:classify

### Source code / logs
(This is redundant if you followed the steps to reproduce)
I used the model at [github.com/tensorflow/samples/core/get_started/premade_estimator.py](https://github.com/tensorflow/models/blob/c9f03bf6a8ae58b9ead119796a6c3cd9bd04d450/samples/core/get_started/premade_estimator.py#L61), with the following lines inserted at [line 61](https://github.com/tensorflow/models/blob/c9f03bf6a8ae58b9ead119796a6c3cd9bd04d450/samples/core/get_started/premade_estimator.py#L61):

    feature_spec = tf.feature_column.make_parse_example_spec(my_feature_columns)
    serving_input_receiver_fn_parsing = tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)
    classifier.export_saved_model("/tmp/exports/iris_parsing", serving_input_receiver_fn_parsing)

The metadata I got for this is: https://gist.github.com/alextdavis/0b351a54909ea1dc0e68477c358648fe#file-iris_parsing_metadata-json

The input JSON I sent to `/v1/models/iris_parsing:classify`: 

    {"examples": [{
              "SepalLength": 2.3, 
              "SepalWidth": 3.4, 
              "PetalLength": 2.2, 
              "PetalWidth": 0.81
    }]}
The output I got:

    {
        "results": [[["0", 0.971662], ["1", 0.0283368], ["2", 1.17796e-06]]
        ]
    }

**Comment by hgadig** [comment]
@alextdavis  Does this issue persist with the latest version of tensorflow and TF Serving ?

**Comment by gowtham-kp** [comment]
Closing the issue due to the lack of recent activity. Please add additional comments and we can reopen the issue again. Thanks!
