### ISSUE TITLE
TF serving as standalone app

### ISSUE THREAD

**Issue by arielscarpinelli** [tensorflow/serving#121]
The common use case for TF Serving should be running inference over an exported TF model. As such seems to me a bit useless to repeat always the same boilerplate code to create a new server, load the exported graph, map the input request protobuf to the placeholdes by the means of the signature, call inference and then map back the output using signature to a result protobuf. 

Can't this be simply a generic process run thru an standalone executable that loads models thru configuration, no need build your own? I believe you could define a generic enough service protobuf that could accomodate any kind of input and even validate before trying to run inference by maybe adding a bit more information in the signatures.

I envision this as an app that you could get to install in your server thru `sudo apt-get install tensorflow-serving`

**Comment by kirilg** [comment]
Good points. I'll mention first that the intent of TensorFlow Serving is to create a set of libraries for building ML servers in a flexible way by using whatever frontend/plugins you wish. In our examples we used gRPC with a custom proto service (to not give the illusion that it's a stable reusable API - it's just an example) + Tensorflow plugins. However, you could envision others not wanting to use gRPC/protos and specifying their own frontend.

With that said, your points are valid. We could still provide a certain gRPC implementation with a stable proto API which may cover the majority of use cases out there, and that's something we're definitely thinking about. We didn't want to rush an API, but stayed tuned.

**Comment by arielscarpinelli** [comment]
Cool! If the desire is to keep it open and not tie it to gRPC, a "plain old JSON REST API" support would be great too :-D

**Comment by arielscarpinelli** [comment]
I was trying to support REST myself but couldn't find any google supported, blaze oriented, dropin libraries for building HTTP based webservices on C++

**Comment by chenleiwhu** [comment]
It's pretty cool to see you already have the plan to do it. @arielscarpinelli you can use any wrapper service framework like node.js or tornado in python.

**Comment by arielscarpinelli** [comment]
I already done it with Python. The spirit of the request is to avoid having
to;
- code the server boilerplate in C++
- avoid the need for two servers

**Comment by kirilg** [comment]
We recently released the [model_server](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc) which addresses your two points above (reusable server + [server_core](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/server_core.h) that eliminates a lot of the boilerplate in C++).

The server uses gRPC, but you can create your own main.cc that uses a different frontend but still reuses server_core. It exposes a [PredictionService](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/prediction_service.proto#L10). See [here](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/predict.proto) for the Request and Response type definitions. Hopefully this is a general enough API, but please re-open this issue or file a new one with new feature requests if this does not meet your needs.

**Comment by promiseofcake** [comment]
@kirilg, quick follow up. In order to reuse `server_core` as a _public_ API, would something need to be changed in the visibility from the BUILD file in order to use those components? If I located my code outside of the `tensorflow_serving` directory (effectively using serving as a submodule of sorts) it seems like I wouldn't have access to it.

```
cc_library(
    name = "server_core",
    srcs = ["server_core.cc"],
    hdrs = ["server_core.h"],
    visibility = [
        "//tensorflow_serving:internal",
    ],
    [...]
```

**Comment by chrisolston** [comment]
We have an internal change in-flight which makes among other things makes server_core public, so expect its visibility to switch to public soon. If you are in a rush feel free to send a PR that makes it public now.

**Comment by promiseofcake** [comment]
Thank you for the quick response @chrisolston, sounds great!
