### ISSUE TITLE
Snap Package Support (Feature Request)

### ISSUE THREAD

**Issue by mikeroyal** [tensorflow/serving#1210]
I was thinking in the install and setup could be improved for Ubuntu and other Linux distros by having a [snap package](https://snapcraft.io/) version. If it's not a priority would you mind if I made the snap as a contribution?

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by unclepeddy** [comment]
Sorry for the late reply - this is not a priority for us since our distribution strategy is centered around use of Docker whose support already gives us a fair number of challenges. Therefore I'm not sure we want to add on the support of official a snap package going forward.
