### ISSUE TITLE
does serving supported load_op_library?

### ISSUE THREAD

**Issue by CLIsVeryOK** [tensorflow/serving#1219]
Does tensorflow-serving support `load_op_library` function?
I would like to use a third party `my_own.so` in my `saved_model.pb`

**Comment by gautamvasudevan** [comment]
TF Serving currently links in libraries statically. The easiest approach here would be to link in the op you want in the build file rules.

**Comment by hgadig** [comment]
Closing this issue as there is no response received from the user. Feel free to post updates(if any), we will reopen the issue.
