### ISSUE TITLE
Documentation or Examples for using assets

### ISSUE THREAD

**Issue by maitham** [tensorflow/serving#1226]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **TensorFlow Serving installed from (source or binary)**: Binary
- **TensorFlow Serving version**: Stable

### Describe the problem
The documentation shows how you can save assets but not how you can load assets back into the model. I have a 14GB embedding that requires preprocessing that I would like to serve using tf serving. Currently I am feeding this as a placeholder due to the 2GB limit on protos. I can save this along with the model in the assets folder but is there a way to load this embedding and feed it into the graph whilst the model is being served ?

### Exact Steps to Reproduce
An alternative I'm considering is doing it all in Keras and saving the vocab list and embeddings as weights.

**Comment by singhniraj08** [comment]
@maitham,

You can save the vocab lists and embeddings as weights, load it to the model with `set_weights` after layer operation and save the model with Keras api. This will save the embeddings matrix in `variables.data` file and not in `saved_model.pb` file and avoids the protobuf limit size of 2GB. The saved model can be loaded in TF serving easily. Thank you!

Example code to save embeddings as weights in Keras:

```
import tensorflow as tf
from tensorflow import keras
import numpy as np

vocab_size =  10**7
emb_dim = 16
np.random.seed(0)
global_emb_weights = np.random.random(size=(vocab_size,emb_dim))
emb = keras.layers.Embedding( mask_zero=True, input_dim=vocab_size, output_dim=emb_dim,
                                     trainable=True,input_length=10)
x = keras.Input((1,))
out = emb(x)
emb.set_weights([global_emb_weights]) #  move the weight init outside of the model definition,
model = keras.Model(inputs=x,outputs=out)
x1 = model.predict([list(range(10))])
 

model.save("/tmp/test_tf",save_format="tf",overwrite=True)
model2 = tf.keras.models.load_model("/tmp/test_tf")
x2 = model2.predict([list(range(10))])
print("x1=x2:{}".format((x1==x2).all()))
```
