### ISSUE TITLE
Passed port not used, serving starts on port 8888

### ISSUE THREAD

**Issue by Industrial** [tensorflow/serving#1228]
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow Serving installed from (source or binary)**: `FROM tensorflow/serving`
- **TensorFlow Serving version**: `latest`

### Describe the problem
Even though I am passing the port to `tensorflow_model_server`, it starts on port 8888. Both the API port and the HTTP port are unreachable.

### Exact Steps to Reproduce
I am extending the dockerfile like so, passing in the ports 8040 and 8041.
```
FROM tensorflow/serving

# Expose the application's ports.
EXPOSE $TF_SERVE_PORT
EXPOSE $TF_SERVE_HTTP_PORT

# Create app directory
RUN mkdir -p /service
WORKDIR /service

# Copy all files into container.
COPY ./services/tf-serve /service

# Run this command to start the application.
CMD tensorflow_model_server \
  --port=${TF_SERVE_PORT} \
  --rest_api_port=${TF_SERVE_HTTP_PORT} \
  --model_name=${TF_SERVE_MODEL_NAME} \
  --model_base_path=/service/${TF_SERVE_MODEL_BASE_PATH}/${TF_SERVE_MODEL_NAME}
```

### Source code / logs
This command shows they should be reachable:
```
$ docker-compose ps
...
testnextjs_tf-serve_1           /run_jupyter.sh --allow-root     Up      6006/tcp, 0.0.0.0:8040->8040/tcp, 0.0.0.0:8041->8041/tcp, 8888/tcp
...
```

The Docker Compose log says:
```
[34mtf-serve_1          |[0m [I 15:58:52.974 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[34mtf-serve_1          |[0m [I 15:58:52.994 NotebookApp] Serving notebooks from local directory: /notebooks
[34mtf-serve_1          |[0m [I 15:58:52.994 NotebookApp] The Jupyter Notebook is running at:
[34mtf-serve_1          |[0m [I 15:58:52.994 NotebookApp] http://(f65a8251f434 or 127.0.0.1):8888/?token=d6ff9ff542fe5c9ee6527105140ad6b953cf3618b7925fae
[34mtf-serve_1          |[0m [I 15:58:52.994 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[34mtf-serve_1          |[0m [C 15:58:52.995 NotebookApp] 
[34mtf-serve_1          |[0m     
[34mtf-serve_1          |[0m     Copy/paste this URL into your browser when you connect for the first time,
[34mtf-serve_1          |[0m     to login with a token:
[34mtf-serve_1          |[0m         http://(f65a8251f434 or 127.0.0.1):8888/?token=d6ff9ff542fe5c9ee6527105140ad6b953cf3618b7925fae
```

If I visit the assigned IP on port 8888 which is `http://192.168.176.4:8888/` for my host, then I get a jupyter instance.

**Comment by Industrial** [comment]
This does not solve this bug, but I have opted to go for https://github.com/tobegit3hub/simple_tensorflow_serving .

**Comment by hgadig** [comment]
I see that you are using 'Expose' here. Instead of using it, you need to declare arg or env variables for this.

Please refer [this documentation](https://www.tensorflow.org/serving/docker) thoroughly which helps you to use arguments to pass to the docker container.

**Comment by Industrial** [comment]
Hi.

I'm doing `EXPOSE $TF_SERVE_HTTP_PORT`. That's an ENV var passed in through Docker compose though a `.env` file.

I'm also calling `tensorflow_model_server` with the options

```
  --port=${TF_SERVE_PORT} \
  --rest_api_port=${TF_SERVE_HTTP_PORT} \
```

These values are also filled in from the env var.

I know the value is correct (My whole project runs on these env vars, all the ports for all the services).

If I change the value for a literal, the port will still be the default.
