### ISSUE TITLE
How to use bazel to build tensorflow serving in win10.I encountered various problems in compiling.I don't know how to use bazel to build tensorflow serving in win10.Is there have specific installation process and requirements? Thanks

### ISSUE THREAD

**Issue by zeqinLi** [tensorflow/serving#1233]
How to use bazel to build tensorflow serving in win10.I encountered various problems in compiling.I don't know how to use bazel to build tensorflow serving in win10.Is there have specific installation process and requirements? Can anybody help me？Thanks

**Comment by hgadig** [comment]
Sorry to hear that you are having trouble in building tensorflow serving using bazel. Please refer below links which help you to understand using Bazel and building tf serving from source.
[Using Bazel on Windows](https://docs.bazel.build/versions/master/windows.html)
