### ISSUE TITLE
Run multiple instances of a model

### ISSUE THREAD

**Issue by hiepph** [tensorflow/serving#1235]
I know that Tensorflow Serving supports multiple versions of a model:

> Sometimes it's helpful to add a level of indirection to model versions. Instead of letting all of your clients know that they should be querying version 42, you can assign an alias such as "stable" to whichever version is currently the one clients should query. If you want to redirect a slice of traffic to a tentative canary model version, you can use a second alias "canary". 
- source: https://www.tensorflow.org/serving/serving_config

So I want to run multiple instances of my model to balance the "traffic" for inference and use the same GPU. Is this able to config by specifying multiple same versions in config, for example I want to run 3 instances of version 42:

```
model_version_policy {
  specific {
    versions: 42
    versions: 42
    versions: 42
  }
}
version_labels {
  key: 'stable'
  value: 42
}
```

Or any other ways to be able to achieve this?

**Comment by gautamvasudevan** [comment]
No. You'll want to have three different model configs pointing to the same model files. You can do this by either using different models, or different model versions, which point to a copy of the model file.

```
model_config_list {
  config {
    name: 'model_one'
    base_path: '/tmp/model_one/'
  }
  config {
    name: 'model_two'
    base_path: '/tmp/model_two/'
  }
}
```

where /tmp/model_one/0000001/* are a copied into /tmp/model_two/0000001/*

Alternatively, you can use versions and specify multiple versions to load, but you'd still have copies of models
/tmp/model_one/0000001/* would be a copy of what's in /tmp/model_one/0000002/*

**Comment by hiepph** [comment]
Thanks for the quick response. Assume I use this, how do I balance the traffic between the models. Because my ultimate goal is to run multiple models for high throughput situation. 

Does Tensorflow (or is going to) support a load balancer to infer these models instead of implementing my own?

**Comment by gautamvasudevan** [comment]
If you're using the REST API, there are many http load balancers available (HAProxy, nginx, etc.). That's probably the easiest way to handle load balancing.

**Comment by hgadig** [comment]
Closing as the questions are answered. Fur any other support related questions, please post in [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow-serving).
