### ISSUE TITLE
When running example exporting python to a PB file when running tensorflow_serving/example/mnist_saved_model.py \ tmp error 

### ISSUE THREAD

**Issue by mcousine** [tensorflow/serving#1239]
python tensorflow_serving/example/mnist_saved_model.py \ tmp 

Training model...
Extracting /tmp\train-images-idx3-ubyte.gz
Extracting /tmp\train-labels-idx1-ubyte.gz
Extracting /tmp\t10k-images-idx3-ubyte.gz
Extracting /tmp\t10k-labels-idx1-ubyte.gz
2019-01-16 07:42:13.555487: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
training accuracy 0.9092
Done training!
Exporting trained model to b'tmp\\1'
Traceback (most recent call last):
  File "tensorflow_serving/example/mnist_saved_model.py", line 147, in <module>
    tf.app.run()
  File "C:\Users\dd1968\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "tensorflow_serving/example/mnist_saved_model.py", line 139, in main
    strip_default_attrs=True)
**TypeError: add_meta_graph_and_variables() got an unexpected keyword argument 'strip_default_attrs'**

i just remove in the python file the line from 

  builder.add_meta_graph_and_variables(
      sess, [tf.saved_model.tag_constants.SERVING],
      signature_def_map={
          'predict_images':
              prediction_signature,
          tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:
              classification_signature,
      },
      main_op=tf.tables_initializer(),
      **strip_default_attrs=False**)

to 
builder.add_meta_graph_and_variables(
      sess, [tf.saved_model.tag_constants.SERVING],
      signature_def_map={
          'predict_images':
              prediction_signature,
          tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:
              classification_signature,
      },
      main_op=tf.tables_initializer(),
    **)**

and fot the exported trained model in tmp directory saved_model.pb

**Comment by hgadig** [comment]
In mnist_saved_model.py, strip_default_attrs was "True" and may I know why you changed it to "False" ?  I see you are trying to use the same mnist_saved_model.py example(correct me if I'm wrong).
If you are trying something new, request you to clearly explain your example and share the code snippet to reproduce the error.

Also provide the following information.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow Serving installed from (source or binary)**:
- **TensorFlow Serving version**:

**Comment by hgadig** [comment]
Closing this issue as there is no response received from the user and the issue is in "awaiting response" status for more than a week.
