### ISSUE TITLE
Installation error with flags

### ISSUE THREAD

**Issue by sonfiree** [tensorflow/serving#1241]
Install according last version to instructions  https://www.tensorflow.org/serving/setup

Good comiled
`tools/run_in_docker.sh bazel build  --copt=-march=native --config=nativeopt tensorflow_serving/...`

And not work 
`tools/run_in_docker.sh bazel build  --copt=mavx2 --config=nativeopt tensorflow_serving/...`

My error 
 
```
ERROR: /home/rtur/serving/.cache/_bazel_root/9a7fc862f917ca824990d070e07d07d4/external/protobuf_archive/BUILD:104:1: C++ compilation of rule '@protobuf_archive//:protobuf' failed (Exit 1)
gcc: error: mavx2: No such file or directory
```
 
What am I to do?

System information
Linux Ubuntu 18.04
TensorFlow Serving installing version: 1.12

**Comment by gautamvasudevan** [comment]
Thanks! That's a bug in the doc, you should use --copt=-mavx2 (though specifying --config=nativeopt will override this and use whatever optimizations your processor supports)
