### ISSUE TITLE
Enable POWER (PPC64le) build for tf serving

### ISSUE THREAD

**Issue by gyliu513** [tensorflow/serving#1247]
I found that tensorflow already support POWER at https://github.com/tensorflow/tensorflow#community-supported-builds , so what is the plan to enable tf serving can also support POWER?

**Comment by gyliu513** [comment]
@hgadig but why tensorflow has POWER support but tf serving do not have such plan? Can you please help explain more? Thanks.

**Comment by wdirons** [comment]
I just saw this issue today. I'm responsible for providing community builds for TensorFlow and TensorFlow Serving on POWER.

Docker images for TensorFlow Serving are now available here:
https://hub.docker.com/r/ibmcom/tensorflow-serving-ppc64le/

They are also available in Watson Machine Learning Community Edition 1.6.1 as either docker images or conda packages. See here: https://www.ibm.com/support/knowledgecenter/en/SS5SF7_1.6.1/welcome/welcome.html
