### ISSUE TITLE
how to build models.config

### ISSUE THREAD

**Issue by aashish-0393** [tensorflow/serving#1249]
I want to host multiple models on tensorflow serving . Tensorflow serving documents states that : Create a file containing an ASCII ModelServerConfig protocol buffer. But I am not able to build this models.config . Please help me with this

**Comment by sonfiree** [comment]
```
model_config_list: {
  config: {
    name:  "detection",
    base_path:  "/home/user/models/detection",
    model_platform: "tensorflow",
    model_version_policy: {
        all: {}
    }
  },
  config: {
    name:  "ocr",
    base_path:  "/home/user/models/myclass",
    model_platform: "tensorflow",
    model_version_policy: {
        all: {}
    }
  } 

}
```

**Comment by hgadig** [comment]
Run the below code when you run the model_server

bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_config_file=<path_to_your_config_on_disk>

Where the config should be a file on disk that looks like this:

model_config_list: {
  config: {
    name: "your_model_name",
    base_path: "/path/to/yourmodel",
    model_platform: "tensorflow"
  },
  config: {
    name: "your_model_name",
    base_path: "/path/to/yourmodel",
    model_platform: "tensorflow"
  },
}

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
