### ISSUE TITLE
error while deploying multiple models with model.config file

### ISSUE THREAD

**Issue by aashish-0393** [tensorflow/serving#1252]
while deploying Docker image with multiple models with model.config file it is resulting in model.config file not found.

Docker command : 
`docker run -p 8501:8501 --mount type=bind,source=/opt/script/TFServingModelFactory/,target=/models/TFServingModelFactory -t $USER/tensorflow-serving --model_config_file=/opt/script/TFServingModelFactory/models.confi`

error ::
`F tensorflow_serving/model_servers/server.cc:97] Non-OK-status: ParseProtoTextFile(file, &proto) status: Not found: /opt/script/TFServingModelFactory/models.config; No such file or directory /usr/bin/tf_serving_entrypoint.sh: line 3:     6 Aborted                 (core dumped) tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"`

When I am deploying the same model.config file with tensorflow_model_server it is successfull.
`tensorflow_model_server --port=8500 --rest_api_port=8501 --model_config_file=/opt/script/models.config`

**Comment by hgadig** [comment]
@aashish-0393  Did you try to build custom image with your models and config file in it, if so you can just point it the config file in the docker image.

**Comment by hgadig** [comment]
Closing as there is no response received and issue is in "awaiting response" status for more than a week.
Feel free to add comments(if any), we will reopen if required. Thanks !
