### ISSUE TITLE
How to process raw data in tf-serving?

### ISSUE THREAD

**Issue by ericyue** [tensorflow/serving#1262]
I am wondering how to process the input data in tf-serving (c++ version).

In the training process, I am use feature-column to define features (doing hash or sometings) . 

So , How to do the samething in tf-serving? I need to deploy predict service in my own c++ server. But I didn't know how to do the feature process which the feature-column does in training. (it's a ctr predict problem, the raw data is all txt format. )

**Comment by hgadig** [comment]
Just to make sure, did you get a chance to take a look at the example mnist_saved_model.py [here](https://www.tensorflow.org/serving/serving_basic)

**Comment by ericyue** [comment]
@hgadig  I have check this demo before. But it didnot use feature_column and do some feature process(such as hash or calc bins).  Can you give me some advice about how to do predict white I'm using feature_column in training ?   I'm in c++ env.

**Comment by hgadig** [comment]
Please find this existing issue #228 which has some valuable suggestions. Also please go through the following tutorial/StackOverflow thread which help in handling feature columns.
[Inspecting Hash buckets for feature columns](https://stackoverflow.com/questions/47282229/tensorflow-inspecting-hash-buckets-for-categorical-and-feature-columns)
[Tensorflow guide for Feature Columns](https://www.tensorflow.org/guide/feature_columns)
