### ISSUE TITLE
Expose language-agnostic protocol buffer library rules

### ISSUE THREAD

**Issue by palmerlao** [tensorflow/serving#1264]
## Feature Request
If this is a feature request, please fill out the following form in full:

### Describe the problem the feature is intended to solve

TFS seems to only exposes language-specific protocol buffer library rules, which makes it hard to integrate with other languages.

TFS doesn't seem to expose language-agnostic protocol buffer library rules (i.e. `proto_library`). `serving_proto_library` seems to be a macro for a `filegroup` (which can't be used to create a `proto_library` outside of the package the `filegroup` was defined in) and a custom (not Bazel native) `cc_proto_library` rule.

### Describe the solution

I would like TFS to expose a `proto_library` (or similar) target that can be used in `deps` fields of `$LANG_proto_library` rules from external workspaces.

### Describe alternatives you've considered

Internally, we've worked around this by patching the `serving_proto_library` macro to also include a `native.proto_library` rule. This mostly seems to work, except we sometimes also find that this newly introduced rule conflicts with the custom `cc_proto_library` rule's underlying `proto_gen` rule:
```
ERROR: file 'external/tfs/tensorflow_serving/apis/model.pb.cc' is generated by these conflicting actions:
Label: @tfs//tensorflow_serving/apis:model_proto_genproto, @tfs//tensorflow_serving/apis:model_proto_lib
RuleClass: proto_gen rule, proto_library rule
```
(In the above, `model_proto_lib` is the newly introduced `native.proto_library` rule.)

**Comment by unclepeddy** [comment]
We're starting to look at priority for this - if you're still in need of this please let us know.

**Comment by palmerlao** [comment]
I would say that this could be useful to us if it were fixed. However, it's not really blocking anything as we have the internal patch I mentioned. I do find the not-`native.proto_library` stuff a little curious and unpredictable though, although even that is less of a worry in my mind as I haven't run into it for a while.

**Comment by singhniraj08** [comment]
@palmerlao,

You can find the Tensorflow Serving language-agnostic protos [here](https://github.com/tensorflow/serving/tree/master/tensorflow_serving/apis). Thanks.
