### ISSUE TITLE
tensorFlow serving batch configure ineffectiveness 

### ISSUE THREAD

**Issue by lebron374** [tensorflow/serving#1267]
## docker run command
docker run -t --rm -p 8500:8500 -p 8501:8501 \
-v /home/zhi.wang/tensorflow-serving/model:/models \
-e MODEL_NAME=beidian_cart_ctr_wdl_model tensorflow/serving:1.12.0 \
--enable_batching=true --batching_parameters_file=/models/batching_parameters.txt &

## batching_parameters.txt
   num_batch_threads { value: 40 }
   batch_timeout_micros { value: 5000}
   max_batch_size {value: 20000000}

## server configuration
40 cpu and 64G memory

## test result
1 thread predict cost 30ms
40 thread predict one predict cost 300ms

## cpu usage
cpu usage in docker can only up to 300% and host cpu usage is low 

## java test script
Features features = Features.newBuilder().putAllFeature(featureMap).build();
        Example example = Example.newBuilder().setFeatures(features).build();

        Predict.PredictRequest.Builder predictRequestBuilder = Predict.PredictRequest.newBuilder();
        Model.ModelSpec.Builder modelSpecBuilder = Model.ModelSpec.newBuilder();
        modelSpecBuilder.setName("beidian_cart_ctr_wdl_model");
        modelSpecBuilder.setSignatureName("predict");

        predictRequestBuilder.setModelSpec(modelSpecBuilder);

        TensorShapeProto.Dim dim = TensorShapeProto.Dim.newBuilder().setSize(200).build();
        TensorShapeProto shapeProto = TensorShapeProto.newBuilder().addDim(dim).build();

        TensorProto.Builder tensor = TensorProto.newBuilder();
        tensor.setTensorShape(shapeProto);
        tensor.setDtype(DataType.DT_STRING);
        for (int i=0; i<200; i++) {
            tensor.addStringVal(example.toByteString());
        }
        predictRequestBuilder.putInputs("examples", tensor.build());

        ManagedChannel channel = ManagedChannelBuilder.forAddress("10.2.176.43", 8500).usePlaintext().build();
        PredictionServiceGrpc.PredictionServiceBlockingStub predictionServiceBlockingStub = PredictionServiceGrpc.newBlockingStub(channel);

        Predict.PredictResponse predictResponse = null;
        while (true) {
            long start = System.currentTimeMillis();
            predictResponse = predictionServiceBlockingStub.predict(predictRequestBuilder.build());
            long end = System.currentTimeMillis();
            System.out.println(end - start);

            List<Float> floatList = predictResponse.getOutputsOrThrow("probabilities").getFloatValList();

            Map<String, TensorProto> outputsMap = predictResponse.getOutputsMap();
        }

**Comment by hgadig** [comment]
Could you please provide system information as asked below 
System information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
TensorFlow Serving installed from (source or binary):
TensorFlow Serving version

**Comment by hgadig** [comment]
Please look at this existing issue https://github.com/tensorflow/serving/issues/89 related to some performance and optimization tips.

**Comment by netfs** [comment]
your code seems to be sending one request at-a-time (via blocking stub). if that is true,
what sort of batching are you expecting on the server?  the batching feature allows you
to batch multiple (concurrent) requests coming into the server.

**Comment by hgadig** [comment]
Closing as it is in "awaiting response" state for more than 3 days. Feel free to add comments and we will reopen.
