### ISSUE TITLE
Latest HEAD at 7/17/2016 Compile Failed

### ISSUE THREAD

**Issue by Mazecreator** [tensorflow/serving#127]
I pulled the latest serving files, executed:
git clean --expunge_async
bazel build tensorflow_serving/...

Build machine is Ubuntu 15.10.

Compilation failed (starting at line 1095 in the attached buildError file):
[buildError.txt](https://github.com/tensorflow/serving/files/368227/buildError.txt)

> ERROR: /home/greg/serving/tensorflow_serving/session_bundle/BUILD:198:1: C++ compilation of rule '//tensorflow_serving/session_bundle:signature_lite' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer ... (remaining 97 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
> In file included from tensorflow_serving/session_bundle/signature.cc:16:0:
> ./tensorflow_serving/session_bundle/signature.h:40:22: error: 'Signatures' has not been declared
>                       Signatures* signatures);
>                       ^
> ./tensorflow_serving/session_bundle/signature.h:43:28: error: 'Signatures' does not name a type
>  Status SetSignatures(const Signatures& signatures,
>                             ^
> ./tensorflow_serving/session_bundle/signature.h:51:5: error: 'ClassificationSignature' has not been declared
>      ClassificationSignature* signature);

**Comment by kirilg** [comment]
It sounds like you synced TensorFlow Serving without syncing submodules so you're still linking in an older TensorFlow. Try:
`git pull --recurse-submodules`
`git submodule update --recursive`

**Comment by Mazecreator** [comment]
Thanks, that got me closer.  "git" is still a bit magical to me so I wrote this done for my bag of tricks.  I am now back to the "half_plus_two" failure (but final step so above did fix my initial problem).  Don't know if we should close this and go back to the "half_plus_two" thread?

> ERROR: /home/greg/.cache/bazel/_bazel_greg/46040455ac0d0cc3199d34afa462e3f6/external/org_tensorflow/tensorflow/contrib/session_bundle/example/BUILD:38:1: Executing genrule @org_tensorflow//tensorflow/contrib/session_bundle/example:half_plus_two failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
> Traceback (most recent call last):
>   File "/home/greg/.cache/bazel/_bazel_greg/46040455ac0d0cc3199d34afa462e3f6/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/tf_serving/../org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.py", line 32, in <module>
>     import tensorflow as tf
>   File "/home/greg/tensorflow.head/_python_build/tensorflow/__init__.py", line 23, in <module>
>     from tensorflow.python import *
>   File "/home/greg/tensorflow.head/_python_build/tensorflow/python/__init__.py", line 48, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/home/greg/tensorflow.head/_python_build/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
>     _pywrap_tensorflow = swig_import_helper()
>   File "/home/greg/tensorflow.head/_python_build/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
> ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

I am wondering if I should try this trick again from the serving directory?  It is likely it caused the sync issue which had me open this report, but seemed to fix the "half_plus_two" at the time:

> cd tensorflow
> git checkout master
> git pull
> git log -1  # To verify the latest commit is from yesterday (or last Tensorflow Build)
> cd ..
