### ISSUE TITLE
Not tensorflow/serving:latest-devel-mkl image, which is used as build image in Dockerfile.mkl

### ISSUE THREAD

**Issue by algorithmdog** [tensorflow/serving#1271]
https://github.com/tensorflow/serving/blob/5fb314ccb24ce60b59e8e333e8ca09842cfca6f4/tensorflow_serving/tools/docker/Dockerfile.mkl#L16

![image](https://user-images.githubusercontent.com/2755653/53630491-23a8f580-3c4b-11e9-8f4c-352b98ceb4f9.png)

**Comment by netfs** [comment]
we do not official build/release MKL docker images. please build
these on your own, using the docker files provided in the repo.
