### ISSUE TITLE
A grpc request took 20 seconds

### ISSUE THREAD

**Issue by aikudexiaohai** [tensorflow/serving#1273]
I started a service using the docker image on the server, sent a 1000*1000 image, and it took 20 seconds to get the response, but it only took 0.x seconds to complete without serving.

**Comment by hgadig** [comment]
Could you please share a sample code snippet to reproduce this issue ? Also, please provide the following information.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow Serving installed from (source or binary)**:
- **TensorFlow Serving version**:

**Comment by hgadig** [comment]
Closing this as it is in "awaiting response" status for more than 3 days. Feel free to provide the information asked above and we will reopen. Thanks!
