### ISSUE TITLE
Usage of 'tensor_content' field for TensorProto response.

### ISSUE THREAD

**Issue by tridemax** [tensorflow/serving#1276]
-----------------------
### Describe the problem the feature is intended to solve
Current implementation of predict code (`SessionBundlePredict`) at
[https://github.com/tensorflow/serving/blob/master/tensorflow_serving/servables/tensorflow/predict_impl.cc](url) uses `AsProtoField` function to compose the response protobuf field. This fills one of the `*_val` fields in protobuf which are really slow to deserialize in Python 3 (not sure about other languages) for large data, like millions of floats. In comment to 'tensor_content' field in TensorProto ([https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.proto](url)) this is clearly stated.

### Describe the solution
Implementation ([https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.h](url)) contains other method `AsProtoTensorContent` which uses `tensor_content` to encode the response. This works much faster for larger payloads to deserialize.

### Describe alternatives you've considered
Recompilation of TensorFlow Serving is a viable option but it makes NVidia Docker usage harder as you need to build a separate image and support it.

**Comment by minglotus-6** [comment]
This FR is fulfilled in the sense that the representation of TensorProto is configurable [1].

Runners of servers can configure the option to specify how tensors are serialized.

[1] Code defined in https://github.com/tensorflow/serving/blob/492381f38c1c8274d3f2ac42b88efc13f768309d/tensorflow_serving/model_servers/server_core.h#L186

**Comment by tridemax** [comment]
@minglotus-6 How to set this option in ServerCore from the outside? I don't see the binding to  ServerCore from command line. Should I rebuild an image to get this option enabled? (then it is pretty useless)

**Comment by csachs** [comment]
Any update here? I do have the same problem, and deserializing a TF Serving response with `tf.make_ndarray` takes ~100 ms (for a response taking ~200ms for prediction). So it's roughly wasting 1/3 of total time on copying stuff around … slowly (RAM-wise it should by <1ms).
Interstingly, `tf.io.parse_tensor(tensor_proto.SerializeToString())` is faster, but has other downsides.

**Comment by tridemax** [comment]
@csachs we just recompiled the image with this enum set by default. Speed grew up tremendously.
