### ISSUE TITLE
Why there are two package of tensorflow-serving-api?

### ISSUE THREAD

**Issue by gr8Adakron** [tensorflow/serving#1278]
I don't understand, why there are two different packages of **_tensorflow-serving-api_**.

- https://pypi.org/project/tensorflow-serving-api/

- https://pypi.org/project/tensorflow-serving-api-python3/

If I only install the first version: then I can't import the predicts function.
```
from tensorflow_serving.apis import predict_pb2
ImportError: cannot import name 'predict_pb2'
```

If I only install the second packages: then I can't import new features of present in its management methods.
```
from tensorflow_serving.apis import model_management_pb2
ImportError: cannot import name 'model_management_pb2'

```
and if I install both of them then, it causes conflicts.

Any help is there a way to use predict_pb2 function from 1st package itself.

**Comment by gr8Adakron** [comment]
@ewilderj @montanaflynn @lamberta

**Comment by netfs** [comment]
we do not support **unofficial** packages (the xxx-python3 is one of them).

the first one should work. can you describe your environment (os/version/pip list etc.). its nearly impossible to debug without this information. our docker builds (and tests) are all green, so its hard to image this being broken widely.

**Comment by netfs** [comment]
and for the record there is only **ONE** official python package namely `tensorflow-serving-api`

**Comment by netfs** [comment]
i am going to close this (as the issue as filled is NOT correct. there is only one official package).

and if the official package is indeed broke (import not working), please file a new issue that has all the relevant environment details.

thanks a lot!
