### ISSUE TITLE
Client ERROR: tensorflow service python client run failed

### ISSUE THREAD

**Issue by MaybeShewill-CV** [tensorflow/serving#1282]
I have not built the docker from source tensorflow. I have pulled a image from docker hub supplied by tensorflow. 
Here is some information of my local env:
**Docker version**: 18.09.3
**Nvidia Docker version**: 2.0.3
**Os**: linux ubuntu 16/04 LTS
**Image**: tensorflow/serving:1.12.0-devel-gpu
**local tensorflow version** 1.12.0 gpu
**cudnn version**: cudnn 9.0
**python version**: 3.5.2
**python grpc version**: 1.19.0

The tensorflow_moedl_server run normally as I can tell
![server](https://user-images.githubusercontent.com/15725187/54418502-19552400-4740-11e9-9f01-b7ecaa9de5c7.png)

But when I run the python client from https://github.com/Vetal1977/tf_serving_example/blob/master/svnh_semi_supervised_client.py, I got following error
![bug](https://user-images.githubusercontent.com/15725187/54418564-499cc280-4740-11e9-8b1c-8df9e1a4bfc5.png)
 I have tried to change the host ip to 0.0.0.0 and localhost but nothing changed. Could you please help me with it:)

**Comment by hgadig** [comment]
Can you try with the nightly-devel-gpu or latest-devel-gpu and let us know if you are still running into this error ?

**Comment by unclepeddy** [comment]
It seems like your grpc client can't even connect to the server. 
Where are you getting the "172.17.0.2" from? Can you try localhost to see if that works?

If that doesn't work, then it's possible that the client and server processes are not sharing the same networking stack (which can happen if you're running the server within a docker container). If setting the server address to 127.0.0.1 doesn't work, lmk how exactly you're startin the

**Comment by MaybeShewill-CV** [comment]
@unclepeddy Thanks for your reply. 1.As for testing I have run the server and client on the same pc. I have found something strange that if I use localhost and stop the Cisio Anyconnect vpn connection the server and client works fine but when I reconnect the vpn the server client can never work again. I have tried localhost, 0.0.0.0, 127.0.0.1 but none of that help to solve that problem when I have the vpn connection. 
2.The way I start the server is as follows. First I run the command ```docker run -it --runtime=nvidia -p 9000:9000 tensorflow/serving:1.12.0-devel-gpu bash``` to start a container. Second I run the command ```tensorflow_model_server --port=9000 --model_name=nsfw --model_base_path=/serving/nsfw_model``` to start the server. 
If you need some more information please let me know. Thanks a lot:)

**Comment by MaybeShewill-CV** [comment]
@hgadig

**Comment by unclepeddy** [comment]
Thanks for the information. Am I correct to understand that this works when your vpn is turned off? If yes then most likely your firewall is blocking port 9000 - you need to ask your vpn service to open up port 9000. 

If this is the case please consult the manual/guide for your vpn and close this issue since this is not a TFS problem.

Thanks

**Comment by MaybeShewill-CV** [comment]
@unclepeddy I will try if that is the cause:)

**Comment by hgadig** [comment]
@MaybeShewill-CV  Did you get a chance to try ? Please keep us posted for any updates.

**Comment by MaybeShewill-CV** [comment]
@hgadig Still get stuck on this ==!

**Comment by gowtham-kp** [comment]
@MaybeShewill-CV Were you able to resolve the issue?

**Comment by MaybeShewill-CV** [comment]
@gowtham-kp Still get stuck on this ==!

**Comment by christisg** [comment]
@MaybeShewill-CV - since TF serving works fine when your VPN is off, the issue you're experiencing is unrelated to TF serving. It seems like a bad interaction between docker and Cisco AnyConnect VPN. Please see if this link is helpful (https://docs.docker.com/network/bridge/#connect-a-container-to-the-default-bridge-network), or post a question on github.com/docker.

**Comment by MaybeShewill-CV** [comment]
@christisg Thanks a lot I'll have a try:)

**Comment by unclepeddy** [comment]
Plz reopen if issue persists
