### ISSUE TITLE
Premature EOF when run the cmd: tools/run_in_docker.sh bazel build -c dbg tensorflow_serving/... to build tensorflow-serving ,output as follows:

### ISSUE THREAD

**Issue by litaozijin** [tensorflow/serving#1285]
I had encounted a problem of "Premature EOF ” when running the cmd "tools/run_in_docker.sh bazel build -c dbg tensorflow_serving/..."  to build the tensorflow-serving by source after successfully install the docker.Details as follows:

### System information
1.OS Platform and Distribution: LInux ubuntu LTS 16.04 (vitual matchine )
2.Docker version 18.09.3, build 774a1f4
3.TensorFlow Serving installed from source

### Exact Steps to Reproduce
1. first install the docker
2. git clone https://github.com/tensorflow/serving（in this step i used docker accelerator to download this package）
3.cd serving, then run "tools/run_in_docker.sh bazel build -c dbg tensorflow_serving/..."

### Describe the problem
root@ubuntu:/home/taoli5/work/tensorflow/serving# tools/run_in_docker.sh bazel build -c dbg tensorflow_serving/...
== Pulling docker image: tensorflow/serving:nightly-devel
nightly-devel: Pulling from tensorflow/serving
898c46f3b1a1: Already exists 
63366dfa0a50: Already exists 
041d4cd74a92: Already exists 
6e1bee0f8701: Already exists 
0bf715f0dc64: Pull complete 
a4df8c703699: Pull complete 
9b9388462ebf: Pull complete 
635cb62be267: Pull complete 
104770dd2151: Pull complete 
1eb737f36d58: Pull complete 
862a05447b9a: Pull complete 
960fe20e652e: Pull complete 
73ba984a06f1: Pull complete 
Digest: sha256:0d054f7072419f2462250108481b018a72564f049b7a0f791ff2ac2484e5193e
Status: Downloaded newer image for tensorflow/serving:nightly-devel
== Running cmd: sh -c 'cd /home/taoli5/work/tensorflow/serving; TEST_TMPDIR=.cache bazel build -c dbg tensorflow_serving/...'
usermod: no changes
$TEST_TMPDIR defined: output root default is '/home/taoli5/work/tensorflow/serving/.cache' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
INFO: Invocation ID: b86f6547-e6ab-47ee-9d87-d005b0e5feba
ERROR: error loading package '': in /home/taoli5/work/tensorflow/serving/tensorflow_serving/workspace.bzl: Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/8fa58e776283de8d1e877fe6d57d6a3f6e4dc556.tar.gz, https://github.com/tensorflow/tensorflow/archive/8fa58e776283de8d1e877fe6d57d6a3f6e4dc556.tar.gz] to /home/taoli5/work/tensorflow/serving/.cache/_bazel_root/75a2b79ca33f65d1565e671ec0348cbe/external/org_tensorflow/8fa58e776283de8d1e877fe6d57d6a3f6e4dc556.tar.gz: Premature EOF
ERROR: error loading package '': in /home/taoli5/work/tensorflow/serving/tensorflow_serving/workspace.bzl: Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/8fa58e776283de8d1e877fe6d57d6a3f6e4dc556.tar.gz, https://github.com/tensorflow/tensorflow/archive/8fa58e776283de8d1e877fe6d57d6a3f6e4dc556.tar.gz] to /home/taoli5/work/tensorflow/serving/.cache/_bazel_root/75a2b79ca33f65d1565e671ec0348cbe/external/org_tensorflow/8fa58e776283de8d1e877fe6d57d6a3f6e4dc556.tar.gz: Premature EOF
INFO: Elapsed time: 423.978s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @org_tensorflow; fetching 414s

**Comment by hgadig** [comment]
Please fill the new issue[ template ](https://github.com/tensorflow/serving/issues/new)with clear explanation on the steps followed. Also, provide a code snippet to reproduce the error from our end.

**Comment by netfs** [comment]
i just tried this and it works for me.

looking at your error messages, notably `Premature EOF` errors -- it seems to be a network problem between your server and github (maybe after a heavy docker download, something is rate-limiting you. see similar post [here](https://github.com/tensorflow/tensorflow/issues/18740#issuecomment-383253234), where a sleep/delay between docker download and starting the build seems to work :-)
