### ISSUE TITLE
TFServing using only one CPU core on MKL docker image

### ISSUE THREAD

**Issue by karthikvadla** [tensorflow/serving#1287]
Hi Team, 

Recently we noticed that TFServing is using only single CPU core while testing object detection model, even though we set `TENSORFLOW_SESSION_PARALLELISM=14`. `OMP_NUM_THREADS=56` is related to `intel mkl-dnn`. 

```
docker run \
 -p 8501:8501 \
 --name=tfserving_rfcn \
 -v "$(pwd)/rfcn:/models/rfcn" \
 -e MODEL_NAME=rfcn \
 -e OMP_NUM_THREADS=56 \
 -e TENSORFLOW_INTRA_OP_PARALLELISM=14 \
 -e TENSORFLOW_INTER_OP_PARALLELISM=14 \
 tensorflow/serving:mkl
```
**htop** looks as below.
![image](https://user-images.githubusercontent.com/16564109/54577791-617f7b00-49ba-11e9-88e9-1284207f28d3.png)

Is this something to do with how model script is written ? or any other configuration to do at TFServing end.?

**Comment by netfs** [comment]
few questions:
- do you get similar behavior with non-mkl, official docker images?
- where is this env `TENSORFLOW_SESSION_PARALLELISM` used?

if you do not set any --xxx_parallelism flags on the model server, i'd expect the system to use all schedulable CPUs. assuming the docker container has access to all of these. is the `htop` command from within the docker container (i'd guess so, but wanted to confirm).

**Comment by karthikvadla** [comment]
@netfs 
* do you get similar behavior with non-mkl, official docker images?
- I tested commenting [envs](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.mkl#L102-L103) (which makes it similar to offical non-mkl [dockerfile](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile#L54))  , re-build image and use. Assuming TFServing automatically schedules on available CPU's. But still i see same.

* where is this env TENSORFLOW_SESSION_PARALLELISM used?
I Updated above description. We got this `splitting of session_parallelism` merged recently https://github.com/tensorflow/serving/pull/1253. 

We exposed envs explicitly because when using  `intel optimized tensorflow`. Tuning `inter` and `intra` gives optimal performance. Logic goes as explained in above mentioned PR.

I ran *htop` outside of container. But after you comment, i ran it inside container just make sure i'm not missing anything. Still htop looks same inside or outside container.

![image](https://user-images.githubusercontent.com/16564109/54655707-2c3d6080-4a80-11e9-9c6c-4cf93244d883.png)

**Comment by netfs** [comment]
(trying to understand the problem) are you sending multiple concurrent requests to the model server or just one (large) request, and expect the model server to use all the cores to process one request?

**Comment by netfs** [comment]
fwiw i tried running resnet on latest docker serving image, sending N concurrent requests and saw all the cores being used. this is without setting any additional environment variables.

for quick test, just follow this [blog post](https://medium.com/tensorflow/serving-ml-quickly-with-tensorflow-serving-and-docker-7df7094aa008). may want to tweak `num_requests` to some large value in the python client script. and observe docker usage (i did `docker exec -it <container-id> top`)

**Comment by karthikvadla** [comment]
okay let me test and update you.

**Comment by karthikvadla** [comment]
> (trying to understand the problem) are you sending multiple concurrent requests to the model server or just one (large) request, and expect the model server to use all the cores to process one request?

I'm sending multiple concurrent requests to the model server. Expectation was when i assign cores to `TENSORFLOW_INTRA_OP_PARALLELISM`, `TENSORFLOW_INTER_OP_PARALLELISM` OR just `TENSORFLOW_SESSION_PARALLELISM`, its not using as assigned. All the time only one core is utilized  100%.

**Comment by netfs** [comment]
> okay let me test and update you.

any update on your testing with resnet model (from the blog post) i mentioned?

**Comment by karthikvadla** [comment]
yeah i tried from blog, It's using all cores when nothing is set.
```
for i in {1..10};do python /tmp/karthik/git-repo/tfserving/resnet/resnet_client.py; done
```

![image](https://user-images.githubusercontent.com/16564109/54815793-f949c700-4c4f-11e9-9118-dc30e54c6d23.png)

**Comment by karthikvadla** [comment]
I cross checked, testing `resnet50` with intel-optimized tfserving image following this [tutorial](https://github.com/IntelAI/models/blob/master/docs/image_recognition/tensorflow_serving/Tutorial.md) 

```
docker run \
        --name=tfserving_no_parall \
        --rm \
        -d \
        -p 8500:8500 \
        -v "/tmp/karthik/git-repo/tfserving/mkl_resnet/:/models/resnet50" \
        -e MODEL_NAME=resnet50 \
        -e OMP_NUM_THREADS=56 \
        -e TENSORFLOW_INTRA_OP_PARALLELISM=14 \
        -e TENSORFLOW_INTER_OP_PARALLELISM=14 \
        tensorflow/serving:parallel
```
I see it's using more than one core.
![image](https://user-images.githubusercontent.com/16564109/54819924-aaedf580-4c5a-11e9-8c92-1189b8b7d17b.png)

Is there anything to do with way model implemented? or type of client we use `GRPC` vs `REST`?

**Comment by netfs** [comment]
I do not think rest vs grpc matters. They both funnel into the same run session path.

**Comment by netfs** [comment]
yes the model can be a problem. but i'd expect it to impact single evaluation of a request. IOW its possible the model causes 1 core to be used when running a single request (as opposed to using all the available cores for running one request).

the fact that sending lot of multiple concurrent requests also causes just 1 core to be used is a bit puzzling.

**Comment by netfs** [comment]
given that we are not able to reproduce this with standard (resnet) model and test models (in TF serving gitrepo), can you share your model+sample-requests?

**Comment by karthikvadla** [comment]
@mhbuehler did some experiments pinning `TF version` while building docker images. She saw while using `TF 1.13.0`, `R-FCN` is using specified cores. Melanie, can you please share your findings.

**Comment by netfs** [comment]
hmm. so things are working and all cores are being used for R-FCN? i am mildly confused :)

**Comment by mhbuehler** [comment]
As @karthikvadla said, I'm seeing proper usage of multiple cores when I build TFServing with MKL from tag 1.13.0, but not when I build from the head of the master branch. For now, this is a fine workaround, but there might be a regression in master. To replicate the problem:

Build TFServing with MKL with these commands (head of master):
```
$ docker build -f Dockerfile.devel-mkl -t tensorflow/serving:latest-devel-mkl .
$ docker build -f Dockerfile.mkl -t tensorflow/serving:mkl_master .
```
And build it again with these commands (release 1.13.0):
```
$ docker build -f Dockerfile.devel-mkl --build-arg TF_SERVING_VERSION_GIT_BRANCH="1.13.0" -t tensorflow/serving:latest-devel-mkl .
$ docker build -f Dockerfile.mkl --build-arg TF_SERVING_VERSION_GIT_BRANCH="1.13.0" -t tensorflow/serving:mkl_1_13_0 .
```
Now, if you run inference on a model using both the mkl_master and mkl_1_13_0 images, you should see the difference in performance. Let me know if you need any more info and I will try to provide you with a model and more instructions.

**Comment by netfs** [comment]
do you see similar issue if you just use just TF?

you can experiment by building+installing TF+MKL (steps [here](https://www.tensorflow.org/guide/performance/overview#tensorflow_with_intel%C2%AE_mkl_dnn)), and then doing inference using a session with your model loaded (python code))?

i am trying to see if this is a build issue (with TF serving), or something is actually broken in TF.

**Comment by penpornk** [comment]
I saw a similar issue about TF-MKL using only one core when using Anaconda image: https://github.com/tensorflow/tensorflow/issues/24172

But it's about OMP/KMP environment variable settings affecting other operations that also use OpenMP, so it's likely unrelated to this issue.

**Comment by karthikvadla** [comment]
@penpornk just to confirm i re-check envs
```
[kvadla@nervana-skx90 ~]$ docker exec -it 48bdbfa71255 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=48bdbfa71255
TERM=xterm
TENSORFLOW_INTRA_OP_PARALLELISM=14
TENSORFLOW_INTER_OP_PARALLELISM=14
MODEL_NAME=resnet50
OMP_NUM_THREADS=56
LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
MODEL_BASE_PATH=/models
KMP_BLOCKTIME=1
KMP_SETTINGS=1
KMP_AFFINITY=granularity=fine,verbose,compact,1,0
MKLDNN_VERBOSE=0
HOME=/root
``` 
as from reference you mentioned `OMP_PROC_BIND` is not set here.

**Comment by karthikvadla** [comment]
> do you see similar issue if you just use just TF?
> 
> you can experiment by building+installing TF+MKL (steps [here](https://www.tensorflow.org/guide/performance/overview#tensorflow_with_intel%C2%AE_mkl_dnn)), and then doing inference using a session with your model loaded (python code))?
> 
> i am trying to see if this is a build issue (with TF serving), or something is actually broken in TF.

We will follow this [guide](https://github.com/IntelAI/models/blob/master/benchmarks/object_detection/tensorflow/rfcn/README.md#fp32-inference-instructions) and at step 6 `--docker-image` i[ntelaipg/intel-optimized-tensorflow:latest-devel-mkl](https://hub.docker.com/r/intelaipg/intel-optimized-tensorflow/tags) which is based of master . Is that okay?

**Comment by tatianashp** [comment]
+ @penpornk, @ezhulenev
Penporn, Eugene - do you know what can be happening here?

**Comment by penpornk** [comment]
> @netfs
> 
> * **do you get similar behavior with non-mkl, official docker images?**
>   I tested commenting [envs](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.mkl#L102-L103) (which makes it similar to offical non-mkl [dockerfile](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile#L54))  , re-build image and use. Assuming TFServing automatically schedules on available CPU's. But still i see same.

TF-MKL is a different build from normal TF. So commenting the environment variables to TF-Serving will still run TF-MKL underneath (just with different threading configurations).

Could you please try running with TF-Serving + normal TF build and see if you still get the issue? It will help us narrow down the scope a bit. Thank you!

**Comment by karthikvadla** [comment]
> yeah i tried from blog, It's using all cores when nothing is set.
> 
> ```
> for i in {1..10};do python /tmp/karthik/git-repo/tfserving/resnet/resnet_client.py; done
> ```
> ![image](https://user-images.githubusercontent.com/16564109/54815793-f949c700-4c4f-11e9-9118-dc30e54c6d23.png)

@penpornk here i tested using official TFServing +TF docker image. I tested for `resent` . Do you want me to test anything different than this?

**Comment by netfs** [comment]
@karthikvadla can you test R-FCN with stock TF serving? that would help.

**Comment by karthikvadla** [comment]
> @karthikvadla can you test R-FCN with stock TF serving? that would help.

Sure i can do that. ` stock TF serving?` means pulling from docker hub?
Also do you have any location for `R-FCN` pre-trained saved model `.pb` which i can download and use. Right now, i have intel optimized `R-FCN` which uses `MKL-DNN`

**Comment by netfs** [comment]
> > @karthikvadla can you test R-FCN with stock TF serving? that would help.
> 
> Sure i can do that. ` stock TF serving?` means pulling from docker hub?

yes. if you want to test TF+TFS at master, pull tensorflow/serving:nightly

> Also do you have any location for `R-FCN` pre-trained saved model `.pb` which i can download and use. Right now, i have intel optimized `R-FCN` which uses `MKL-DNN`

nope. sorry.

**Comment by karthikvadla** [comment]
```
docker run -p 8501:8501 --name tfserving_resnet \
--mount type=bind,source=/tmp/karthik/git-repo/tfserving/resnet,target=/models/resnet \
-e MODEL_NAME=resnet -t tensorflow/serving:nightly &
```
```
 for i in {1..10};do python /tmp/karthik/git-repo/tfserving/resnet/resnet_client.py; done
```
![image](https://user-images.githubusercontent.com/16564109/54967926-1e7f5380-4f36-11e9-903f-3e5366090abe.png)
`resent` looks good with `nightly` too.
Will check with our data scientist whether i can find `non-mkl` `R-FCN` model.

**Comment by penpornk** [comment]
Thank you! So the normal TF at head works fine.

The only big change related to MKL between r1.13 and head that I'm aware of is enabling MKL contraction kernels, but it is only for normal TF build (doesn't affect TF-MKL), and it has been disabled for a few weeks now.

If the culprit is on the TF side, one way to find it is to do a bisection on the commits. There are about 6,500 commits between TF1.13 and now so it will require testing ~13 times. You can find the commit hash by changing the commit offset (6500 in this case) of this URL
https://github.com/tensorflow/tensorflow/commits/master?after=cdd0dcc6f78d2443d7713094c80a4a169531b6c1+6500

The commit above is the first commit on Dec 12. I think r1.13 contains changes up to Dec 13 (not counting fixes) so this range should cover enough.

I'm working on other issues and can't try this right now. Would appreciate if you can help do the bisection (resnet50 is fine for me since it reproduces the problem). Otherwise, I'll get back to doing this later. Thank you!

**Comment by hgadig** [comment]
@karthikvadla  Any update ?

**Comment by karthikvadla** [comment]
yeah pinning to TF Version `1.13.0` did fix issue. `master` is unstable, still we don't know what causing issue. 

Please see documentation where we are passing `--build-arg TF_SERVING_VERSION_GIT_BRANCH="<release_number>"`
https://github.com/IntelAI/models/blob/master/docs/general/tensorflow_serving/InstallationGuide.md#step-1-build-tensorflow-serving-docker-image 
```
docker build \
     -f Dockerfile.devel-mkl \
     --build-arg TF_SERVING_VERSION_GIT_BRANCH="1.13.0" \
     -t tensorflow/serving:latest-devel-mkl .
```

**Comment by netfs** [comment]
TFS+TF official nightly builds/docker images uses all cores, and these builds use mkl contraction kernels (by default). So MKL runs in this (so called) hybrid mode.

Regarding Docker.devel-mkl not working as expected, I will leave it for the community to contribute and get this working, mostly due to my lack of understanding. Will unassign myself.

**Comment by ginger0106** [comment]
hi，I am using tf serving docker,   I limit the cpu usage of docker with 16cores, but I found that when I send large number requests to TFS, the docker could not use up the cpu (almost only 200%cpu), how could I use up the cpu (nearly 1600%)? Thanks.

**Comment by netfs** [comment]
i am going to mark this issue for "contributions", as this issue is specific to the [MKL docker image](tensorflow_serving/tools/docker/Dockerfile.devel-mkl). people closer to this will be able to help resolve the performance issue seen here.

as I mentioned [above](https://github.com/tensorflow/serving/issues/1287#issuecomment-487817949) official TFServing docker images work well with MKL (hybrid) mode.

@ginger0106 if you are seeing performance issues with official TF serving docker images, can you please open a new issue, with details (sample model, requests etc.) -- thanks!

**Comment by karthikvadla** [comment]
I just tested this issue against `master ` of tensorflow serving. Seems like issue resolved. It' using the number of cores specified
```
docker run \
     --name=tfserving_rfcn \
     -p 8501:8501 \
     -v "/tmp/karthik/git-repo/tfserving/rfcn:/models/rfcn" \
     -e MODEL_NAME=rfcn \
     -e OMP_NUM_THREADS=56 \
     -e TENSORFLOW_INTER_OP_PARALLELISM=2 \
     -e TENSORFLOW_INTRA_OP_PARALLELISM=56 \
     tensorflow/serving:latest &
```
![image](https://user-images.githubusercontent.com/16564109/58501672-cf25f100-8139-11e9-8169-8ab214cc669e.png)

@netfs do you think we should close this?

**Comment by netfs** [comment]
yes we should close it. thanks for taking the time to verify it works with master.

for posterity can you point to the RFCN model that you used (assuming its publicly available), so folks looking at this bug know which model was being tested (as we were never able to reproduce this with stock resnet50 model).

**Comment by karthikvadla** [comment]
yeah sure, I told @mhbuehler to test on a different machine just to re-confirm. I will close once she updates me.

**Comment by tatianashp** [comment]
Great. 
+@penpornk

**Comment by mhbuehler** [comment]
Okay, I've re-tested and confirmed that the issue is resolved. I built the MKL docker image from `master` and did test runs for:
- ResNet50, batch sizes 1 and 128
- InceptionV3, batch sizes 1 and 128
- R-FCN, batch sizes 1 and 128
- SSD-MobileNet, batch sizes 1 and 128
- Transformer-LT, batch sizes 1 and 64 

All tests showed multiple cores being used and good performance. For posterity, the R-FCN model is [here](https://storage.googleapis.com/intel-optimized-tensorflow/models/rfcn_resnet101_fp32_coco_pretrained_model.tar.gz) and instructions/scripts for running it in TFServing+MKL are [here](https://github.com/IntelAI/models/blob/master/docs/object_detection/tensorflow_serving/Tutorial.md).

**Comment by karthikvadla** [comment]
Thanks @mhbuehler .I'm closing this issue now.
