### ISSUE TITLE
Multiple TF serving process can bind on the same port

### ISSUE THREAD

**Issue by pigritia** [tensorflow/serving#1288]
I found that tensorflow-serving allow multiple processes bind on the same port. 
<img width="1048" alt="Screen Shot 2019-03-20 at 1 38 32 PM" src="https://user-images.githubusercontent.com/1179478/54717477-7de3fa80-4b15-11e9-9eb2-d0db40e1abc4.png">

The reproduce steps:
Just run the same launching TF serving process command multiple times. It can be reproduced on both Mac and RHEL7.

**Comment by hgadig** [comment]
@pigritia  Could you confirm if this is just an observation or if you are seeking any answer? If so, please clearly post more information using [this](https://github.com/tensorflow/serving/issues/new) template. Thanks!

**Comment by netfs** [comment]
gRPC uses SO_REUSEPORT when creating the socket, causing this behavior. and is WAI.

does running your server with `--grpc_channel_arguments="grpc.so_reuseport=0"` help avoid this issue (assuming that is what you want)?

**Comment by pigritia** [comment]
I see. @netfs That works. Thanks very much!

@hgadig sorry for the confusion. That's a question. Since I may hot-reload different models for different process, it caused very weird non-reproducible issues. `--grpc_channel_arguments="grpc.so_reuseport=0"` solved my problem. I'll be more clear next time. 

Thanks!
