### ISSUE TITLE
Error when I send more than one instance to the TF-serving

### ISSUE THREAD

**Issue by SefaZeng** [tensorflow/serving#1292]
I transformed a ckpt model to a TF-serving model and the code about the inputs placeholder is like this:
```
        for i in range(len(params.device_list)):
            placeholders.append({
                "source": tf.placeholder(tf.int32, [None, None],
                                         "source_%d" % i),
                "source_length": tf.placeholder(tf.int32, [None],
                                                "source_length_%d" % i)
            })
```
And the saving part is like this:
```
        inference_signature = tf.saved_model.signature_def_utils.predict_signature_def(
            inputs={
                'seq_input': placeholders[0][0],
                'seq_length':placeholders[0][1]
            },
            outputs={
                'seq_output': tf.convert_to_tensor(final_res_str)
            }
        )
```
When I send a one instance request everytime to the TF-serving,it works well.But when I try to send several instances,server reply an error said:

> { "error": "Failed to process element: 1 key: seq_input of \'instances\' list. Error: Invalid argument: Expecting tensor size: 34 but got: 20" }

And the instances of the request is:

```
{"instances":[
{"seq_input":[492,2209,8688,15684,10,13943,33,7327,32,4,3694,1123,665,56,6049,6,5677,9,5298,8,35,140,2310,1863,8010,5562,13,3809,8,15,14,4,870,1],
"seq_length":34},
{"seq_input":[2161,195,762,10,492,2209,8688,15684,6,678,98,285,4442,43,1570,8,15,14,7,1],
"seq_length":20},
{"seq_input":[14349,3032,1715,6202,401,1123,665,56,56,25114,843,6973,11,824,9,347,492,8688,15684,30,2054,192,1],
"seq_length":23}
]}
```
And if I exchange the position of instances[0] and instance[1],the error message will change 34 to 20.So,it seems the server think the first number of seq_length is always the same.

But I do not fix the value of seq_length placeholder.So I am not sure what happed here.

Any help is appreciate.Thx!

**Comment by hgadig** [comment]
Could you please provide the following information which helps us to look into the issue.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow Serving installed from (source or binary)**:
- **TensorFlow Serving version**:

### Exact Steps to Reproduce(if applicable)
Please include all steps necessary for someone to reproduce this issue on their
own machine. If not, skip this section.

**Comment by hgadig** [comment]
Closing this issue as it is in "awaiting response" for more than 3 days. Feel free to add your comments by providing the above information.
