### ISSUE TITLE
Tensorflow Serving performance test on cpu with mkl 

### ISSUE THREAD

**Issue by wangyunxiaa** [tensorflow/serving#1293]
I have a test about the performance of mkl with cpu, but I am confused about the result:
no mkl on cpu, the inferencr time is 32ms
open avx and sse, the inferencr time is 26ms
open mkl and  adjust the config parameters I can get the best result by 12ms
the input data of all the above test is batch=1, and the model's structure is "1 layer CNN + 4 layer LSTM + 2layer FC", with data formate NCHW.
but, when i do  N concurrent requests, the performance become bad：
N=2  20ms;  N=4  40ms
and there is useless by changing tensorflow_intra_op_parallelism and tensorflow_inter_op_parallelism or tensorflow_session_parallelism

all the test is done with docker environment, and the images built with:

`ENV OMP_NUM_THREADS=20
ENV KMP_BLOCKTIME=0
ENV KMP_SETTINGS=1
ENV KMP_AFFINITY='granularity=fine,compact,1,0'
ENV MKLDNN_VERBOSE=0
ENV TENSORFLOW_INTRA_OP_PARALLELISM=0
ENV TENSORFLOW_INTER_OP_PARALLELISM=0
`

run test with following parameters:

`nvidia-docker run  -it -p 8500:8500 \
    -v ${basepath}:${docker_model_path} \
    --env LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib \
    tensorflow/serving:1.13.0-cpu-mkl \
    --file_system_poll_wait_seconds=0 \
    --tensorflow_intra_op_parallelism=20  --tensorflow_inter_op_parallelism=1 \
    --model_config_file=${docker_model_path}/cfg/model.cfg \
`

when i do some change as followings:

the image built with:

`ENV OMP_NUM_THREADS=1
ENV KMP_BLOCKTIME=0
ENV KMP_SETTINGS=1
ENV KMP_AFFINITY='granularity=fine,compact,1,0'
ENV MKLDNN_VERBOSE=0
ENV TENSORFLOW_INTRA_OP_PARALLELISM=20
ENV TENSORFLOW_INTER_OP_PARALLELISM=1
`

run test with following parameters:

`nvidia-docker run  -it -p 8500:8500 \
    -v ${basepath}:${docker_model_path} \
    --env LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib \
    tensorflow/serving:1.13.0-cpu-mkl \
    --file_system_poll_wait_seconds=0 \
    --tensorflow_session_parallelism=10 \
    --model_config_file=${docker_model_path}/cfg/model.cfg \
`

I can do 8 concurrent requests all in 30ms. but when N=1, it is also cost about 30ms
I want to know how to do to run N concurrent requests as fast as one, when N less than the number of physical cores?
By the way:
the cpu is Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz 
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2

**Comment by penpornk** [comment]
I think this is because of the cores are oversubscribed. TF Serving with MKL can under/oversubscribe cores pretty easily in dynamic settings. Please see if my explanation about TF-MKL threading (under "More in-depth threading explanation") applies to your case here. https://github.com/tensorflow/serving/issues/1272#issuecomment-477878180

**Comment by hgadig** [comment]
Closing as this is in "awaiting response" status for more than 3 days. Please take a look at the above answer and feel free to post your comments.
