### ISSUE TITLE
SERVING RNN  : LSTMCell not working correctly

### ISSUE THREAD

**Issue by liaq192** [tensorflow/serving#1297]
RNN LSTMCell Problem with Serving
  I am trying to create a basic RNN with 1 LSTMCELL within dynamic_RNN. When model is created it trains properly. After training testing data is read from file ('modelData.csv') into numpy array (dimensions : [-1,7,10]) and NN is ran against that file_input. Model works fine and gives output (prediction) as expected. Things get interesting when model is saved for serving. When model is loaded by tensorflow_model_server and is asked for prediction using the same file ('modelData.csv') with same dimensions it gives prediction error. I checked signature of model exported (using saved_model_cli) and it looks fine ( dimensions are what they should be ).
 
All the code is at git repo :
https://github.com/liaq192/BugReportingRNN
 
**Run**

1) Goto line 133 of modelGeneration.py and add path relative to _your local directory_. 
2) run modelGeneration.py : `python modelGeneration.py`
it will generate a model in _your local directory_
3) check model signature `saved_model_cli show --dir .modeldir/specificModel --all`
4) Serve the model using tensorflow_model_server : `tensorflow_model_server --port=9000 --model_base_path="_your local directory_"`
5) run modelAccess.py `<python modelAccess.py >`

**Error Description**

`
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "transpose expects a vector of size 2. But input(1) is a vector of size 3
	 [[{{node rnn/transpose}}]]"
	debug_error_string = "{"created":"@1554414774.995726952","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"transpose expects a vector of size 2. But input(1) is a vector of size 3\n\t [[{{node rnn/transpose}}]]","grpc_status":3}
`

**Further Investigation**
  
  Screenshot for tensorboard within the RNN for this project is in Repository ( if its helpful). 
  Error MSG Screenshot also in Repsitory. 
  Both datafiles are within repository.
  if i export TF_CPP_MIN_VLOG_LEVEL=1 , and then run tensorflow_model_server then it gives following error

`Input 68: Tensor<type: float shape: [0], bytes: 0>
2019-04-05 07:09:57.334370: W external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:2369]     Total bytes 420
2019-04-05 07:09:57.334373: W external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:2381]   Iteration:
Segmentation fault (core dumped)`

Python Version : Python 3.6.8 :: Anaconda, Inc.  
tensorflow version : 1.12.0  
TensorFlow ModelServer: 1.13.0-rc1+dev.sha.f16e777  
TensorFlow Library: 1.13.1  
saved_model_cli Version : 0.1.0 
OS : Ubuntu 18.04.02
tensorflow , tensorflow_model_server installed from pip and apt-get respectively.
  
Machine Specifications  
    Intel 8th Gen , 12 GB , 6GB Nvidia 1060 , 500Gb SSD.   

All the code is at git repo :
https://github.com/liaq192/BugReportingRNN

**Comment by unclepeddy** [comment]
You probably meant to pass latestData instead of query_components [here](https://github.com/liaq192/BugReportingRNN/blob/master/modelAccess.py#L109)

**Comment by liaq192** [comment]
> You probably meant to pass latestData instead of query_components [here](https://github.com/liaq192/BugReportingRNN/blob/master/modelAccess.py#L109)

Yes , it was my mistake., Thankyou.
