### ISSUE TITLE
Improve model version discovery 

### ISSUE THREAD

**Issue by shlomiken** [tensorflow/serving#1300]
Hello
I read a lot of material the past week about tensorflow serving - and its truly amazing component.
i think that many times i ran across the same question everyone is interested in , and eventually so am i and there is just don't enough examples , or its too complicated to implement this basic functionality - how to deal with dynamic models loading in runtime. (you may call it reload config , or poll the model config ) , but i'm thinking simpler than that - auto resolving models and their versions.
i'm suggesting that given a model base directory - serving will know to resolve the models and their versions without specifying this in model config. 
i'm not suggesting to drop model_config - just that if one wants to use the version labels he could do that for the models type that needs that , but all the others would be resolved automatically.
what would that give us ?- lets say i have a script that sync entire S3 bucket from AWS and put it in /models folder. the structure is as tensorflow serving expects /models/modelname/version
1. support for dynamically created model versions (for examples models that are trained several times a day)
2. support for static models (trained once in couple of months) and want to use the canary/stable feature 
3. no need to merge model_config_list and call reload all the time.
4. it is up to us (consumers) to decide how often to modify the models directory from a repository 
5. can expose rest API that is much simpler than gRPC to reload all models.

i think most people have the same needs in regards to refreshing their models - some have static models , some of us have dynamic models , and some have both.
this simple implementation can meet everyone needs.

**Comment by unclepeddy** [comment]
I believe almost all the items you mention are supported today. Below, I answer and thus close this issue. Regarding documentation, I agree with you; we could do better. If you can open an issue an clearly articulate a guide or tutorial (with a clear objective) that would help you, I'd greatly appreciate it.

1. This is already supported. Simply add a new versioned savedmodel under /<models_root_dir>/<model_name>/<new_version> and TFS will pick it up and serve the model with the higher numeric version
2. This is already [supported](https://www.tensorflow.org/tfx/serving/serving_config#assigning_string_labels_to_model_versions_to_simplify_canary_and_rollback)
3. this is only needed if you'd like to change labels or add/remove entire models
4. It is :)
5. We expose both grpc and [rest api](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple)

**Comment by shlomiken** [comment]
i think you miss understand me , maybe i was not very clear. 
iim talking about discovery of new model names not versions (i know this is supported already)
