### ISSUE TITLE
Make ModelServer poll for model_config changes from remote (e.g. S3) location

### ISSUE THREAD

**Issue by karlschriek** [tensorflow/serving#1301]
### Describe the problem the feature is intended to solve
I've seen various bits and pieces of this problem discussed in many different issues (now closed, but without a solution being available). The problem is as follows: we need a robust way in which to trigger the server to load / unload models on the fly.

The idea in our orginisation is that we start a cluster of server instances, initially serving no models whatsoever. Multiple clients are then started, each of which gets two pieces of information: (S3) URL of data to predict on, (S3) URL of model to use in prediction. If the model in question is not served yet, the client triggers the server to do a model reload by updating the model config.

For this the only solution I have been able to find is discussed here https://github.com/tensorflow/serving/pull/1065. But the problem (which is also discussed in the PR) is that triggering a reload like this unloads any currently served models. Others have also recognised this problem, leading to requests to such as https://github.com/tensorflow/serving/pull/797 and https://github.com/tensorflow/serving/pull/809 to be able to retrieve the served models from the server, then add them on client side to the new config, and then trigger the reload. Of course that will lead to problems if there are multiple clients, so the suggestion was to do https://github.com/tensorflow/serving/issues/811, but this was then retracted again.

Eventually it was suggested under https://github.com/tensorflow/serving/pull/809 that the server should be able to accept config files in a remote location, and that a separate service should see to it that this config is updated, while the ModelServer polls for changes. To me that seems like a reasonable enough solution.

### Describe the solution
All of the issues/PRs listed above are closed, but as far as I know there is no solution yet. So I would like to reopen it here. To make it concerte what I am asking for:

- [x] Make it possible to start the server with the model_config parameter pointing to a location in S3.
- [ ] Make the ModelServer poll for changes to the remote model_config so that I can trigger updates there.

EDIT:
Ok, so placing the config in S3 is already supported as follows:

```
docker run \
    -e AWS_ACCESS_KEY_ID=somekey \
    -e AWS_SECRET_ACCESS_KEY=someotherky \
    -e S3_ENDPOINT=s3.us-east-1.amazonaws.com \
    -e AWS_REGION=us-east-1 \
    tensorflow/serving \
    --model_config_file=s3://path/to/models.config
```

**Comment by netfs** [comment]
implementing polling of external file is doable, if we are willing to accept the same semantics as reload config rpc endpoint: https://github.com/tensorflow/serving/blob/5a81b85465104d02c6d336114f2e5af65cf92286/tensorflow_serving/apis/model_service.proto#L22

namely, the config reload will unload models not mentioned in the config file. this is for the sake of symmetry with the rpc interface.

a more refined interface would allow for adding/deleting model's explicitly. that will be a larger change  with uncertain ETA.

**Comment by gowtham-kp** [comment]
@karlschriek Did that answer your question. Can I close the issue?

**Comment by karlschriek** [comment]
Just to clarify, this would be that the user would only need to change the config file in the remote location (e.g. on S3) and would not need to manually trigger the reload? I.e. TF Serving will poll, see that something has changed, and then reload?

If so then yes, this would be acceptable for our use case. I agree that a "more refined interface would allow for adding/deleting model's explicitly" would be desirable though!

**Comment by unclepeddy** [comment]
Working on this. Should be able to submit it this week.
