### ISSUE TITLE
How to build index_table_from_file on serving?

### ISSUE THREAD

**Issue by zepen** [tensorflow/serving#1303]
```python
import tensorflow as tf


def input_fn(data, data_len):
    dataset = tf.data.Dataset.from_tensor_slices(data)
    dataset.batch(data_len)
    return dataset


def model(features):
    embeddings = tf.get_variable(
        "embedding",
        initializer=tf.truncated_normal_initializer(stddev=0.1),
        shape=(10, 5),
        dtype=tf.float32
    )
    table = tf.contrib.lookup.index_table_from_file(
        vocabulary_file="dictionary/vocab_dict.txt", num_oov_buckets=0, default_value=0)
    ids = table.lookup(features)
    return tf.nn.embedding_lookup(embeddings, ids)


def save_model_to_pb(session, **kwargs):
    builder = tf.saved_model.builder.SavedModelBuilder("model/001")
    inputs = {
        "input_x": tf.saved_model.utils.build_tensor_info(kwargs["x"])
    }
    output_z = {"output_z": tf.saved_model.utils.build_tensor_info(kwargs["z"])}
    prediction_signature = tf.saved_model.signature_def_utils.build_signature_def(
        inputs=inputs,
        outputs=output_z,
        method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME
    )
    builder.add_meta_graph_and_variables(
        session,
        [tf.saved_model.tag_constants.SERVING],
        {tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY: prediction_signature}
    )
    builder.save()
    tf.logging.info("PB Model is saved!")


if __name__ == '__main__':
    feature = [[["我", "爱", "你"]]]
    inputs_x = input_fn(feature, len(feature)).make_one_shot_iterator().get_next()
    print(inputs_x)
    output = model(inputs_x)
    print(tf.trainable_variables())
    with tf.Session() as sess:
        sess.run([tf.global_variables_initializer(), tf.tables_initializer()])
        print(sess.run(output))
        save_model_to_pb(sess, x=inputs_x, z=output)
```

* The code is work well, and when i build model to docker serving it's running.

**2019-04-08 15:27:11.295055: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:162] Restoring SavedModel bundle.
2019-04-08 15:27:11.302146: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:138] Running MainOp with key legacy_init_op on SavedModel bundle.
2019-04-08 15:27:11.302203: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:259] SavedModel load for tags { serve }; Status: success. Took 24235 microsecond
s.
2019-04-08 15:27:11.302690: I tensorflow_serving/servables/tensorflow/saved_model_warmup.cc:83] No warmup data file found at /models/test/001/assets.extra/tf_serving_warm
up_requests
2019-04-08 15:27:11.305797: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: test version: 1}
2019-04-08 15:27:11.307557: I tensorflow_serving/model_servers/server.cc:285] Running gRPC ModelServer at 0.0.0.0:8500 ...
[warn] getaddrinfo: address family for nodename not supported
2019-04-08 15:27:11.308040: I tensorflow_serving/model_servers/server.cc:301] Exporting HTTP/REST API at:localhost:8501 ...
[evhttp_server.cc : 235] RAW: Entering the event loop ...**

* But when i call REST api, the tell me error like this
**{ "error": "Table not initialized.\n\t [[{{node hash_table_Lookup}} = LookupTableFindV2[Tin=DT_STRING, Tout=DT_INT64, _output_shapes=[[1,3]], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](string_to_index/hash_table, _arg_IteratorGetNext_0_0, string_to_index/hash_table/Const)]]" }**

* it's seem the table not initialized when i call them, but i don't know what should i do make table is initialized on serving. please help me, thanks a lot.

**Comment by hgadig** [comment]
This could be caused if init op of the serving module was wrongly constructed.

Can you try to initialize tables with tf.tables_initializer. Alternatively can you use if MonitoredSession which does initialization can help in this scenario ?

**Comment by zepen** [comment]
* OS **Linux version 3.10.0-957.5.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)**
* TensorFlow Serving installed from docker 
![image](https://user-images.githubusercontent.com/18568380/55771494-dfffa200-5aba-11e9-9297-2d3241ba6ec0.png)
* I don't know what is TS version because i docker pull this. The docker images show it' s latest.
* My code on above when i commit first, the vocab_dict file content like this
![image](https://user-images.githubusercontent.com/18568380/55771815-20135480-5abc-11e9-8f7b-b0cca6b2c526.png)
 I have no idea for this, when i use MonitoredSession instead of tf.Session the error tell me **RuntimeError: Graph is finalized and cannot be modified.** 
```python 
    with tf.train.MonitoredSession() as sess:
        print(sess.run(output))
        save_model_to_pb(sess, x=inputs_x, z=output)
```
When i check trainable_variables by tf.trainable_variables, i only see one variable in list. So i guess the table is not be save in model file. then i call REST API no table could be use.  If another way to build a map between vocab with number on TF Graph.

**Comment by vinuraja** [comment]
You need to provide the initializers while exporting the savedmodel. For example, you can do something like this:
```python
builder.add_meta_graph_and_variables(
        session,
        [tf.saved_model.tag_constants.SERVING],
        signature_def_map={tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY: prediction_signature},
        main_op=tf.tables_initializer())
```

More details are available at https://www.tensorflow.org/tfx/serving/serving_basic#train_and_export_tensorflow_model

**Comment by zepen** [comment]
It‘ s working, thanks a lot!
