### ISSUE TITLE
build error with Eigen on TF Serving 1.13

### ISSUE THREAD

**Issue by helloopenworld** [tensorflow/serving#1313]
serving version：1.13
gcc：4.8.5
os: centos

In file included from /root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/eigen_archive/unsupported/Eigen/CXX11/Tensor:120:0,
                 from /root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/org_tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from /root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/org_tensorflow/tensorflow/core/framework/tensor.h:21,
                 from InferenceApi.cpp:11:
/root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function ‘static void Eigen::internal::TensorBlockIO<Scalar, StorageIndex, NumDims, Layout, BlockRead>::Copy(const Block&, StorageIndex, const Dimensions&, const Dimensions&, const Scalar*, Scalar*)’:
/root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:393:63: error: the value of ‘j’ is not usable in a constant expression
         if (++block_iter_state[j].count < block_iter_state[j].size) {
                                                               ^
/root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:392:16: note: ‘int j’ is not const
       for (int j = 0; j < num_squeezed_dims; ++j) {
                ^
/root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:393:35: error: parse error in template argument list
         if (++block_iter_state[j].count < block_iter_state[j].size) {
                                   ^
/root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function ‘static void Eigen::internal::TensorBlockCwiseUnaryIO<UnaryFunctor, StorageIndex, OutputScalar, NumDims, Layout>::Run(const UnaryFunctor&, const Dimensions&, const Dimensions&, OutputScalar*, Eigen::array<StorageIndex, NumDims>&, const InputScalar*)’:
/root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:604:21: error: parse error in template argument list
         if (++state.count < state.size) {
                     ^
/root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h: In static member function ‘static void Eigen::internal::TensorBlockCwiseBinaryIO<BinaryFunctor, StorageIndex, OutputScalar, NumDims, Layout>::Run(const BinaryFunctor&, const Dimensions&, const Dimensions&, OutputScalar*, Eigen::array<StorageIndex, NumDims>&, const LeftScalar*, Eigen::array<StorageIndex, NumDims>&, const RightScalar*)’:
/root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:758:21: error: parse error in template argument list
         if (++state.count < state.size) {
                     ^
In file included from /root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/eigen_archive/unsupported/Eigen/CXX11/Tensor:143:0,
                 from /root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/org_tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from /root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/org_tensorflow/tensorflow/core/framework/tensor.h:21,
                 from InferenceApi.cpp:11:
/root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorMorphing.h: In member function ‘void Eigen::TensorEvaluator<const Eigen::TensorReshapingOp<NewDimensions, XprType>, Device>::block(Eigen::TensorEvaluator<const Eigen::TensorReshapingOp<NewDimensions, XprType>, Device>::OutputTensorBlock*) const’:
/root/.cache/bazel/_bazel_root/b68f84bd1350ade1c36f452c07321f56/execroot/tf_serving/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorMorphing.h:319:35: error: parse error in template argument list
         if (++block_iter_state[i].count < block_iter_state[i].size) {
                                   ^

**Comment by hgadig** [comment]
Could you please provide the steps followed and a reproducible code snippet(if applicable). This would help us to look into the issue. Thanks!

**Comment by hgadig** [comment]
Closing this issue as it is in "awaiting response" status for more than 3 days. Please provide the information(as asked above) and we will reopen the issue. Thanks!
