### ISSUE TITLE
How to resize the image inside server

### ISSUE THREAD

**Issue by HFrost0** [tensorflow/serving#1321]
Is there any way to give server a image without resize, and prepossess the image using tensorflow serving to make it match the input shape of the model?

**Comment by hgadig** [comment]
Please take a look at [this](https://github.com/tensorflow/serving/issues/878) is a similar issue which has information about defining the pre-processing part using tf.image.resize_images().

**Comment by HFrost0** [comment]
> You may use tf.image.resize_images(...) to resize the input images.
> Please take a look at [this](https://github.com/tensorflow/serving/issues/878), which is a similar issue with information about defining the pre-processing part using tf.image.resize_images().
> 
> tf.image.resize_images(
> images,
> size,
> method=ResizeMethod.BILINEAR,
> align_corners=False,
> preserve_aspect_ratio=False
> )

Thank you for your advice! I'm trying to do that.

**Comment by HFrost0** [comment]
I solved this problem. Thanks to this [issue](https://github.com/tensorflow/serving/issues/878#issue-322144979)
First run this code to save a  saved model including image resize.
`
import os
import tensorflow as tf

string_inp = tf.placeholder(tf.string, shape=(None,))
imgs_map = tf.map_fn(
    tf.image.decode_image,
    string_inp,
    dtype=tf.uint8
)
imgs_map.set_shape((None, None, None, 3))
imgs = tf.image.resize_images(imgs_map, [256, 256])
imgs = tf.reshape(imgs, (-1, 256, 256, 3))
img_float = tf.cast(imgs, dtype=tf.float32) / 255

model = tf.keras.models.load_model("...")
output = model(img_float)

# saved model
version = 2
export_path = os.path.join('classifier', str(version))
tf.saved_model.simple_save(
    tf.keras.backend.get_session(),
    export_path,
    inputs={'input_image': string_inp},
    outputs={'predictions': output})
`

And to request use code like this 

`
import base64
import os
import requests

SERVER_URL = "..."
with open(os.path.join('cat.jpg'), 'rb') as f:
    image_byte = base64.b64encode(f.read()).decode('utf-8')

predict_request = '{"instances" : [{"b64": "%s"}]}' % image_byte
response = requests.post(SERVER_URL, data=predict_request)
response.raise_for_status()
prediction = response.json()['predictions'][0]

print(prediction)
` 
@hgadig thanks again for your advice.

**Comment by kriskorrel-cw** [comment]
@HFrost0 I believe I have done basically the same as you,  but I can't get it to work. Does anyone know what is going wrong here?

I load an already trained model and prepare it for serving with TF Serve:
```python
# model = load_model()

if fixed_shape is not None:
    shape = [None, *fixed_shape]
else:
    shape = [None, None, None, 3]

string_inp = tensorflow.placeholder(
    tensorflow.string, shape=(None,))  # string input for the base64 encoded image
imgs_map = tensorflow.map_fn(
    tensorflow.image.decode_image,
    string_inp,
    dtype=tensorflow.float32
)  # decode the jpeg
imgs_map.set_shape(shape)
pred = model(imgs_map)

model_inputs = list(string_inp)
model_outputs = list(pred)
inputs = {i.name + "_bytes": i for i in model_inputs}
outputs = {f"output {i}:" + o.name: o for i, o in enumerate(model_outputs)}
signature = tensorflow.saved_model.signature_def_utils.predict_signature_def(
    inputs=inputs, outputs=outputs
)

builder = tensorflow.saved_model.builder.SavedModelBuilder("out_dir")
builder.add_meta_graph_and_variables(
    sess=K.get_session(),
    tags=[tensorflow.saved_model.tag_constants.SERVING],
    signature_def_map={
        tensorflow.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:
            signature
    })
builder.save()
```

Then for the client I use
```python
image_byte = base64.b64encode(batch[0]).decode("utf-8")
payload = '{"instances" : [{"b64": "%s"}]}' % image_byte
response = requests.post(predict_url, data=payload)
```
which results in `requests.exceptions.HTTPError: 400 Client Error: Bad Request for url:`. However, if I try the same request in Postman, I get:
```
{
    "error": "2 root error(s) found.\n  (0) Invalid argument: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]\n\t [[{{node map_5/while/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert}}]]\n\t [[GroupCrossDeviceControlEdges_0/map_5/while/decode_image/cond_jpeg/cond_png/cond_gif/DecodeBmp/_4702]]\n  (1) Invalid argument: assertion failed: [Unable to decode bytes as JPEG, PNG, GIF, or BMP]\n\t [[{{node map_5/while/decode_image/cond_jpeg/cond_png/cond_gif/Assert_1/Assert}}]]\n0 successful operations.\n0 derived errors ignored."
}
```

**Comment by Bluewind001** [comment]
@kriskorrel-cw I have same error. Do you solve this?

**Comment by kriskorrel-cw** [comment]
> @kriskorrel-cw I have same error. Do you solve this?

If I recall correctly, this issue was because the image was not encoded correctly. I think you need to use `cv2.imencode`.
However, I have abandoned the REST api completely and instead used gRPC
