### ISSUE TITLE
How to send proper requests to TensorFlow Serving 

### ISSUE THREAD

**Issue by ianhellstrom** [tensorflow/serving#1323]
The TensorFlow Serving documentation does not really cover a lot of realistic (i.e. non-MNIST or trivial) cases. The [sample script](https://github.com/tensorflow/tfx/blob/master/tfx/examples/chicago_taxi/chicago_taxi_client.py) for the Taxi example shows how to properly serialize the examples from CSV for requests to the server, but it requires a Python script in the middle that grabs the schema and uses TFT coders.

Would it be possible to add an example that does not rely on CSV data and instead would use a direct request to the REST API:

`
curl -H 'Content-Type: application/json' -X POST -d "$JSON" http://server:port/v1/models/my_model:predict
`

This would more clearly mimic a scenario where a model is in a production environment and a client connects to it to obtain predictions.

It's unclear (to me) how to format the JSON data (captured in the `JSON` variable).  For instance, the model I created (based on the setup from the Taxi example) leads to the following `SignatureDef`

`
The given SavedModel SignatureDef contains the following input(s):
  inputs['examples'] tensor_info:
      dtype: DT_STRING
      shape: (-1)
      name: input_example_tensor:0
`

What's the recommended way of sending such requests and how would anyone figure out what to send without using the TFT coders and schema file? For instance, if other services are Java-based, how would they be able to serialize the data properly?

An example `curl` command might go a long way to explain the internal mechanics.

**Comment by netfs** [comment]
once you know/figure out what input tensor(s) (shape, size,type) or example(s) (feature names+types) your model excepts (this is very model specific and only known to the author of the model), i'd recommend using the examples shown in [REST API Spec](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/api_rest.md) to compose/structure your JSON request (the [mapping](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/api_rest.md#json-mapping) section is also useful).

**Comment by gowtham-kp** [comment]
Closing this issue as it is in "awaiting response" status for more than a week. Feel free to add your comments and we will reopen.
