### ISSUE TITLE
Is the nightly docker container binary built against tensorflow nightly?

### ISSUE THREAD

**Issue by tedivm** [tensorflow/serving#1328]
We're working with nvidia to resolve a tensorrt issue and they've recommended that we use the nightly versions of tensowflow and tensorflow serving.

When using the tensowflow serving nightly docker containers we can see that it's running tensowflow 1.13.1 rather than the nightly build- what would be the recommended way to use the tensorflow nightly variants?

**Comment by netfs** [comment]
yes presently nightly TF serving (docker image) uses stable upstream TF (1.13.1 presently).

your best bet is to build your container. you can base it off TF serving nightly, and then update TF pip package to nightly version within the docker container. note TF nightly and release PIP packages have different names (not just version differences), so you may need to first uninstall TF 1.13.1 and then install the nightly pip package.

**Comment by tedivm** [comment]
Great, thank you for clarifying!

**Comment by gowtham-kp** [comment]
Closing the issue as it is answered!!
