### ISSUE TITLE
Build to Docker image fails

### ISSUE THREAD

**Issue by kevinashaw** [tensorflow/serving#1329]
### Describe the problem the feature is intended to solve
I am following the [instructions](https://www.tensorflow.org/tfx/serving/setup) to build a docker installation of tensorflow/serving (TFS).
As instructed, I pulled the latest commit TFS and entered:
`tools/run_in_docker.sh bazel build -c opt tensorflow_serving/...`
This resulted in:
ERROR: /Users/myname/tfserving/.cache/_bazel_myname/9f2a464414b9889e97d316bba8331915/external/org_tensorflow/tensorflow/core/BUILD:2797:1: C++ compilation of rule '@org_tensorflow//tensorflow/core:framework_internal_impl' failed (Exit 4)
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
INFO: Elapsed time: 3090.055s, Critical Path: 1253.34s
INFO: 3029 processes: 3029 local.
FAILED: Build did NOT complete successfully

### Describe the solution
Following build instructions:
- pull latest repo for TFS (6f4536d0a40494e0f48b700c6f4eeae1ae11437f)
- install Docker (2.0.0.3::31259)
- From the serving directory, enter: 
`tools/run_in_docker.sh bazel build -c opt tensorflow_serving/...`
- wait an hour and it fails. Brief error message above.
Attached below is the entire transcript of the build session.
[errors.txt](https://github.com/tensorflow/serving/files/3110269/errors.txt)

### Describe alternatives you've considered
Error message is too vague to know what to do.

### Additional context
Full transcript of build session is attached.

## Bug Report
This is it.

### System information
- MacOS 10.14.2 with Docker 2.0.0.3
- TF 1.13.1
- TFS git head = 6f4536d0a40494e0f48b700c6f4eeae1ae11437f

### Describe the problem
Unable to compile TFS to docker image

### Exact Steps to Reproduce
Already described above.

### Source code / logs
Full transcript provided.

**Comment by netfs** [comment]
i think you are running out of resources (notably RAM) during the bazel compile.

try tweaking the resource needs for bazel via `--local_resources` flag:
https://docs.bazel.build/versions/master/command-line-reference.html#flag--local_resources

also see this (search for `--local_resources`) for potential values:
https://www.tensorflow.org/tfx/serving/docker#building_a_container_from_a_dockerfile

**Comment by gowtham-kp** [comment]
Closing this issue as it is in "awaiting response" status for more than a week. Feel free to add your comments and we will reopen.
