### ISSUE TITLE
build failed  due to fft2d checksum mismatches

### ISSUE THREAD

**Issue by richard403** [tensorflow/serving#1330]
`ERROR: /home/whx/.cache/bazel/_bazel_whx/0c1a8c353c81563d651e5a17b5260d00/external/org_tensorflow/tensorflow/core/platform/default/build_config/BUILD:192:1: no such package '@fft2d//': java
.io.IOException: Error downloading [http://mirror.tensorflow.org/www.kurims.kyoto-u.ac.jp/~ooura/fft.tgz, http://www.kurims.kyoto-u.ac.jp/~ooura/fft.tgz] to /home/whx/.cache/bazel/_bazel_wh
x/0c1a8c353c81563d651e5a17b5260d00/external/fft2d/fft.tgz: Checksum was 8aa2b1bc1906ee70da1c704c569181b23587468bad5a3144a2e50749f72b071a but wanted 52bb637c70b971958ec79c9c8752b1df5ff0218a4
db4510e60826e0cb79b5296 and referenced by '@org_tensorflow//tensorflow/core/platform/default/build_config:platformlib'
ERROR: Analysis of target '//tensorflow_serving/util:event_bus_test' failed; build aborted: no such package '@fft2d//': java.io.IOException: Error downloading [http://mirror.tensorflow.org/
www.kurims.kyoto-u.ac.jp/~ooura/fft.tgz, http://www.kurims.kyoto-u.ac.jp/~ooura/fft.tgz] to /home/whx/.cache/bazel/_bazel_whx/0c1a8c353c81563d651e5a17b5260d00/external/fft2d/fft.tgz: Checks
um was 8aa2b1bc1906ee70da1c704c569181b23587468bad5a3144a2e50749f72b071a but wanted 52bb637c70b971958ec79c9c8752b1df5ff0218a4db4510e60826e0cb79b5296`

**Comment by gowtham-kp** [comment]
Can you please fill [this](https://github.com/tensorflow/serving/issues/new) new issue template which helps us to understand more about this issue and look into it.

**Comment by gowtham-kp** [comment]
Closing this issue as it is in "awaiting response" status for more than a week. Feel free to add your comments and we will reopen.
