### ISSUE TITLE
Serving Predict Response Greater than 6 digits of precision gets rounded

### ISSUE THREAD

**Issue by fsudrew07** [tensorflow/serving#1332]
-----------------------
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- Using the latest Docker Hub version of tensorflow/serving 1.13.0 (this issue is also reproducible on nightly, 1.11.1, 1.10.1, 1.9.1 versions as well)

### Describe the problem
Values in the predictions response appear to be rounded to 6 significant digits. 

When I run the example in the README for the tensorflow/serving GitHub repo for the "half_plust_two" model and change one of the input features to "1111111.0" I would expect to get back "555557.5" however what I get back is "555558.0". 

### Exact Steps to Reproduce
`docker pull tensorflow/serving

git clone https://github.com/tensorflow/serving
TESTDATA="$(pwd)/serving/tensorflow_serving/servables/tensorflow/testdata"

docker run -t --rm -p 8501:8501 \\
    -v "$TESTDATA/saved_model_half_plus_two_cpu:/models/half_plus_two" \\
    -e MODEL_NAME=half_plus_two \\
    tensorflow/serving &

curl -d '{"instances": [1111111.0]}' -X POST http://localhost:8501/v1/models/half_plus_two:predict`

I found this issue while running a different model of my own. While debugging this problem I am able to call the model and get the expected return to > 6 significant digits using the saved model CLI. 

This doesn't seem like expected behavior but if it is, could someone please let me know?

**Comment by gowtham-kp** [comment]
@fsudrew07 If you look at the output [variable](https://github.com/tensorflow/serving/blob/2f42c693b22c946bf38a4a5934e95a335379caac/tensorflow_serving/batching/test_util/matrix_half_plus_two_saved_model.py#L31), its of type float32 i.e., if you're using the binary32 form which is commonly selected by C++ compilers for the float type, it holds just over 7 digits. Hence, the digits are limited to 7.Hope this helps!

**Comment by nrfrank** [comment]
@gowtham-kp Your answer is confusing. Are you suggesting that single-precision floats only have 7 digits of precision? I don't think that's accurate (e.g. https://en.wikipedia.org/wiki/Single-precision_floating-point_format). Regardless, the OP is saying that tensorflow/serving HTTP REST endpoints do not return the same results as if the model were called via the saved model cli. This seems like an error of some kind. Additionally, that example does not preserve 7 digits of precision, only 6.

Here's what we might expect based on the float32 type:
```
>>> import tensorflow as tf
>>> tf.enable_eager_execution()
>>> tf.constant(12345678, dtype=tf.float32).numpy()
>>> 12345678.0  # preserves 8 digits of precision
>>> tf.constant(123456789, dtype=tf.float32).numpy()
>>> 123456790.0  # preserves 8 digits of precision
>>> tf.constant(123456789, dtype=tf.float64).numpy()
>>> 123456789.0
```

**Comment by netfs** [comment]
thanks for reporting!

yes this is a bug (and i suspect this has to do the way floating point numbers are printed (converted to string) in our json library, when composing the response. Many float->string routines format with 6 digits precision (%g format specifier in printf).
