### ISSUE TITLE
Tensorflow Object detection model export for serving.

### ISSUE THREAD

**Issue by ashwini-git** [tensorflow/serving#1340]
I have trained a Tensorflow Object detection model. and used export_inference_graph.py script to generate inference graph. following files were created -
""saved_model.pb""
""variables/"" (an empty folder)

Now I want to export model for serving. exporter.py script does not create "variables" which are required to host model on Tensorflow serving.

Please let me know changes might be required to export model for Serving in the exporter.py script.

Any possible help will be much appreciated.
Thanks

**Comment by farzaa** [comment]
Hi there!

You're almost there :). You actually have everything you need for serving - all you need is the `saved_model.pb` file. I can quickly show you my setup and hopefully you can use a similar setup! 

I actually serve two models, at the same time - here is my file structure:

![image](https://user-images.githubusercontent.com/15614124/57428177-26990700-71f5-11e9-8e3c-86d29ad7708d.png)

Note: in both these folders, `variables` is empty. This is not necessary at all. 

And here is my Dockerfile.

```
FROM tensorflow/serving:1.13.0-gpu

WORKDIR /models
COPY all_saved_models .

RUN mkdir -p league-ocr-detector/1
RUN mkdir -p fortnite-ocr-detector/1

RUN mv ./league_saved_model/league_saved_model.pb ./league_saved_model/saved_model.pb
RUN mv ./league_saved_model/saved_model.pb league-ocr-detector/1/
RUN mv ./league_saved_model/variables league-ocr-detector/1/

RUN mv ./fortnite_saved_model/fortnite_saved_model.pb ./fortnite_saved_model/saved_model.pb
RUN mv ./fortnite_saved_model/saved_model.pb fortnite-ocr-detector/1/
RUN mv ./fortnite_saved_model/variables fortnite-ocr-detector/1/
```

Notice how I set up the file structure as `fortnite-ocr-detector/1/` and the working directory is `models`. The `1` is the version of the model.

And that's it! Let me know if you have issues making a REST request or using GRPC.

**Comment by annish07** [comment]
@farzaa Can you please tell me how to make a REST request for the same.

**Comment by ashwini-git** [comment]
@farzaa, Thank You for your response! it was very helpful.
Plz, let us know client script to make REST request.

**Comment by farzaa** [comment]
Hey there! Yeah, so a REST request is **much** simpler. Just be very careful with the naming of your models. 

```
import requests
image = cv2.imread("image.jpg").astype(np.uint8)

def make_request():
    payload = {"instances": [image.tolist()]}
    res = requests.post("http://35.229.22.200:8501/v1/models/league-model:predict", json=payload)
```
In this case, my `league-model` is in the `models` folder. So, my exact file structure is: `league-ocr-detector/1/saved_model.pb` and my `model.config` file properly specifies the names of everything. The `1` is the `version` of the model and is the most confusing thing ever. This is also why we do `v1` within the endpoint. 

This fellow actually goes into it more in depth within his blogpost, so be sure to check it out! 

https://medium.com/@pierrepaci/deploy-tensorflow-object-detection-model-in-less-than-5-minutes-604e6bb0bb04

**Comment by gowtham-kp** [comment]
Thank you @farzaa for your response. I'm closing this issue as it has been answered!
