### ISSUE TITLE
Tensorflow Serving Illegal Instruction core dumped

### ISSUE THREAD

**Issue by karthik922** [tensorflow/serving#1342]
**System information**
 **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
**cat /etc/centos-release** :  CentOS Linux release 7.6.1810 (Core) 
**rpm -q centos-release** : centos-release-7-6.1810.2.el7.centos.x86_64
- **TensorFlow Serving installed from (source or binary)**: source
- **TensorFlow Serving version**: 1.13.0 (tensorflow/serving:1.13.0)

**Source code / logs**
I have saved the model using tf.saved_model.simple_save function. I am using the saved model for serving in the production environment. 

The following image represents the structure of the saved model.

![image](https://user-images.githubusercontent.com/40170831/57281447-a2e1fc00-70c8-11e9-95bb-2f9e34be1d56.png)

I have used my model name as the environment variable and mounted the saved model in the following format:
  tensorflow:
    image: tensorflow/serving:1.13.0
    container_name: tensorflow
    environment:
      - MODEL_NAME=test
    volumes:
      - ./data_pipeline/machine_learning/models/v1/:/models/test/1
    ports:
      - 8501:8501

I have the following message printed out in the docker logs.

/usr/bin/tf_serving_entrypoint.sh: line 3:     6 Illegal instruction     (core dumped) tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"

**Describe the problem**
With same source code, I was able to run the container in my working system which is ubuntu16.04 LTS

Here is the system configuration:
**lsb_release -a**:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

When I run the container in this system, Here are the logs:
2019-05-07 07:48:59.016348: I tensorflow_serving/model_servers/server.cc:82] Building single TensorFlow model file config:  model_name: test model_base_path: /models/test
2019-05-07 07:48:59.016474: I tensorflow_serving/model_servers/server_core.cc:461] Adding/updating models.
2019-05-07 07:48:59.016484: I tensorflow_serving/model_servers/server_core.cc:558]  (Re-)adding model: test
2019-05-07 07:48:59.116880: I tensorflow_serving/core/basic_manager.cc:739] Successfully reserved resources to load servable {name: test version: 1}
2019-05-07 07:48:59.116912: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: test version: 1}
2019-05-07 07:48:59.116925: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: test version: 1}
2019-05-07 07:48:59.116942: I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:363] Attempting to load native SavedModelBundle in bundle-shim from: /models/test/1
2019-05-07 07:48:59.116950: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /models/test/1
2019-05-07 07:48:59.118993: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2019-05-07 07:48:59.121163: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-07 07:48:59.139480: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:182] Restoring SavedModel bundle.
2019-05-07 07:48:59.157194: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:285] SavedModel load for tags { serve }; Status: success. Took 40230 microseconds.
2019-05-07 07:48:59.157249: I tensorflow_serving/servables/tensorflow/saved_model_warmup.cc:101] No warmup data file found at /models/cri/1/assets.extra/tf_serving_warmup_requests
2019-05-07 07:48:59.157347: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: test version: 1}
2019-05-07 07:48:59.159193: I tensorflow_serving/model_servers/server.cc:313] Running gRPC ModelServer at 0.0.0.0:8500 ...
[warn] getaddrinfo: address family for nodename not supported
2019-05-07 07:48:59.159878: I tensorflow_serving/model_servers/server.cc:333] Exporting HTTP/REST API at:localhost:8501 ...
[evhttp_server.cc : 237] RAW: Entering the event loop ...

-----------------------------------------------------------------------------------------------------------------

I couldn't understand what is the reason for this behaviour. Please provide a viable solution.

**Comment by gowtham-kp** [comment]
What CPU are you running this on?

The output of

$ cat /proc/cpuinfo

Would be useful.

**Comment by karthik922** [comment]
`processor    : 0
vendor_id    : GenuineIntel
cpu family    : 6
model        : 44
model name    : Intel(R) Xeon(R) CPU           X5660  @ 2.80GHz
stepping    : 2
microcode    : 0x1a
cpu MHz        : 2793.000
cache size    : 12288 KB
physical id    : 0
siblings    : 2
core id        : 0
cpu cores    : 2
apicid        : 0
initial apicid    : 0
fpu        : yes
fpu_exception    : yes
cpuid level    : 11
wp        : yes
flags        : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes hypervisor lahf_lm epb tsc_adjust dtherm ida arat
bogomips    : 5586.00
clflush size    : 64
cache_alignment    : 64
address sizes    : 42 bits physical, 48 bits virtual
power management:

processor    : 1
vendor_id    : GenuineIntel
cpu family    : 6
model        : 44
model name    : Intel(R) Xeon(R) CPU           X5660  @ 2.80GHz
stepping    : 2
microcode    : 0x1a
cpu MHz        : 2793.000
cache size    : 12288 KB
physical id    : 0
siblings    : 2
core id        : 1
cpu cores    : 2
apicid        : 1
initial apicid    : 1
fpu        : yes
fpu_exception    : yes
cpuid level    : 11
wp        : yes
flags        : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes hypervisor lahf_lm epb tsc_adjust dtherm ida arat
bogomips    : 5586.00
clflush size    : 64
cache_alignment    : 64
address sizes    : 42 bits physical, 48 bits virtual
power management:`

**Comment by karthik922** [comment]
> What CPU are you running this on?
> 
> The output of
> 
> $ cat /proc/cpuinfo
> 
> Would be useful.

This is CPU info of the system in which I was not able to run.

The system information is :
cat /etc/centos-release : CentOS Linux release 7.6.1810 (Core)
rpm -q centos-release : centos-release-7-6.1810.2.el7.centos.x86_64

`processor : 0
vendor_id : GenuineIntel
cpu family : 6
model : 44
model name : Intel(R) Xeon(R) CPU X5660 @ 2.80GHz
stepping : 2
microcode : 0x1a
cpu MHz : 2793.000
cache size : 12288 KB
physical id : 0
siblings : 2
core id : 0
cpu cores : 2
apicid : 0
initial apicid : 0
fpu : yes
fpu_exception : yes
cpuid level : 11
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes hypervisor lahf_lm epb tsc_adjust dtherm ida arat
bogomips : 5586.00
clflush size : 64
cache_alignment : 64
address sizes : 42 bits physical, 48 bits virtual
power management:

processor : 1
vendor_id : GenuineIntel
cpu family : 6
model : 44
model name : Intel(R) Xeon(R) CPU X5660 @ 2.80GHz
stepping : 2
microcode : 0x1a
cpu MHz : 2793.000
cache size : 12288 KB
physical id : 0
siblings : 2
core id : 1
cpu cores : 2
apicid : 1
initial apicid : 1
fpu : yes
fpu_exception : yes
cpuid level : 11
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes hypervisor lahf_lm epb tsc_adjust dtherm ida arat
bogomips : 5586.00
clflush size : 64
cache_alignment : 64
address sizes : 42 bits physical, 48 bits virtual
power management:`

**Comment by gowtham-kp** [comment]
@karthik922 TensorFlow Serving's docker images are published compiled with AVX instructions for performance, and your CPU doesn't have that support.

You'll have to [build your own optimized binary](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md#building-an-optimized-serving-binary) for your CPU.

**Comment by karthik922** [comment]
Yes, It worked with building an optimized binary for my CPU.

Thanks for the help!.

It would be better if these binaries were prebuilt for CPU's which do not support AVX instruction set and made available in the repository.

**Comment by Tian14267** [comment]
excuse me, can you support the flow of `build your own optimized binary for my CPU`. ? I get the same problem, but I can't build my own optimized binary, I don't have a correct process for build it. @karthik-js @gowthamkpr

**Comment by NikolayXHD** [comment]
The above link to "build your own optimized binary" documentation is broken, because it points to a version in master branch head, which has changed since.

Here is a valid [link](https://github.com/tensorflow/serving/blob/2b20315418346837a26a11f640fed0da90048a08/tensorflow_serving/g3doc/building_with_docker.md#building-an-optimized-serving-binary) pointing to the documentation at specific commit.
