### ISSUE TITLE
c++ client restful

### ISSUE THREAD

**Issue by CLIsVeryOK** [tensorflow/serving#1344]
is there anyone use restful api to call serving? I'd like to write a c++ restful client but their is only grpc client, can any one helps me?

**Comment by hzy001** [comment]
You can implement your client based on https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/api_rest.md

**Comment by CLIsVeryOK** [comment]
thanks for your suggestion. I solved it by using curl. 
`#include <curl/curl.h>`

**Comment by muween** [comment]
> thanks for your suggestion. I solved it by using curl.
> `#include <curl/curl.h>`

Could you please show the full imlementation?
