### ISSUE TITLE
CPU usage of TFS docker 

### ISSUE THREAD

**Issue by ginger0106** [tensorflow/serving#1345]
hi，I am using tf serving docker, I limit the cpu usage of docker with 16cores, but I found that when I send large number requests to TFS, the docker could not use up the cpu (almost only 200%cpu), how could I use up the cpu (nearly 1600%)? Thanks.

**Comment by gowtham-kp** [comment]
@ginger0106 There is an issue with docker in this case. Can you please restart the docker and let me know if it works. Thanks!

**Comment by gowtham-kp** [comment]
@ginger0106 Closing this issue as it was in 'awaiting response' for more than a week. Please add additional comments and we can open the issue. Thanks!
