### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by who39** [tensorflow/serving#135]
Hi All:
  I followed these steps https://tensorflow.github.io/serving/docker.html to setup the tensorflow serving in my desktop. but after I type "bazel test tensorflow_serving/..." I got compiling error as following. Does anyone have any idea?

ERROR: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/org_tensorflow/tensorflow/contrib/sessio
n_bundle/example/BUILD:38:1: Executing genrule @org_tensorflow//tensorflow/contrib/session_bundle/example:half_plus_two
failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.bui
ld.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/serving/bazel-out/host/bin/external/org_tensorfl
ow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/external/org_tensorflow/tensorflow/contrib/se
ssion_bundle/example/export_half_plus_two.py", line 32, in <module>
    import tensorflow as tf
  File "/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/serving/bazel-out/host/bin/external/org_tensorfl
ow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/external/org_tensorflow/tensorflow/__init__.p
y", line 23, in <module>
    from tensorflow.python import *
  File "/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/serving/bazel-out/host/bin/external/org_tensorfl
ow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/external/org_tensorflow/tensorflow/python/__i
nit__.py", line 97, in <module>
    from tensorflow.python.platform import test
  File "/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/serving/bazel-out/host/bin/external/org_tensorfl
ow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/external/org_tensorflow/tensorflow/python/pla
tform/test.py", line 77, in <module>
    import mock                # pylint: disable=g-import-not-at-top,unused-import
ImportError: No module named mock
INFO: Elapsed time: 1249.174s, Critical Path: 900.40s

Executed 0 out of 48 tests: 48 fail to build.

Thanks

**Comment by who39** [comment]
I did 2 things and it is fixed. 1. I checked out the commitment a2f3de559b1d19fe10be7bea85e3140860016e9e 2. I installed the mock module by runing "sudo pip install mock" Now build and all tests passed

**Comment by kirilg** [comment]
Just to confirm, was number 2 alone (installing mock) not enough? Does it work if you sync to head instead of an older commit?

**Comment by who39** [comment]
sorry for reply late. Yes it is fixed for #2 alone

**Comment by shenshaoyong** [comment]
It works when  just deleting the lines as below from serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/python/platform/test.py


import mock
from unittest import mock
