### ISSUE TITLE
Issue with TF Serving at high load.

### ISSUE THREAD

**Issue by farzaa** [tensorflow/serving#1354]
I have 30 Docker containers. Each container is processing one frame from a video per second.

I also have a single GPU (w/ a NVIDIA Tesla P100 + 16 CPUs + 80GB RAM) server running `tf-serving` from the Docker image pulled directly from [here](https://hub.docker.com/r/tensorflow/serving). I am using the image w/ the tag `1.13.0-gpu`. It is hosting a Faster-RCNN model taking images as input and giving bounding boxes as output. 

Each Docker container will take a frame (one per second) from the video and send it the GPU server via the gRPC port opened up by `tf-serving`. That means with 30 Docker containers - I am sending 30 frames per second to my `tf-serving` server. This works flawlessly. The average time per request is about `0.25 seconds`. 

The issue comes when I slightly increase the load. At 40 Docker containers I send 40 frames per second the my `tf-serving` server. The issue here is every request starts taking over `2.5 seconds`. Soon - every request begins to timeout and it feels as if a few requests failing turns into all the requests failing. 

This is a _massive_ slowdown and I didn't even increase the load by much. I only increased it by 20 extra requests per second! 

What could be causing these issues? Note: I ran `htop` and the CPUs are being very underutilized and aren't showing signs of a heavy load. 

Here is graph to also illustrate the issue. At 22:00, this indicates the time per requests while hitting tf-serving with 30 requests per second. 23:00 shows request times massively jumping at 40 requests per second. You can see the massive jump from requests taking 0.25s to 2.1 seconds. 

![image](https://user-images.githubusercontent.com/15614124/57995546-b01bc500-7a90-11e9-9af0-44dfd65c98ad.png)

**Comment by gowtham-kp** [comment]
@farzaa Can you please provide the model that you are working with or can you please use the timeline profiler in your model by look at this [issue](https://github.com/tensorflow/tensorflow/issues/21312) and let me know if that helps. Thanks!

**Comment by chanshah** [comment]
@farzaa, We haven't heard from you for many days now. We will close this for now, please feel free to reopen this issue if you still need help.

**Comment by PayneJoe** [comment]
> @farzaa Can you please provide the model that you are working with or can you please use the timeline profiler in your model by look at this [issue](https://github.com/tensorflow/tensorflow/issues/21312) and let me know if that helps. Thanks!

Any progress on this?
