### ISSUE TITLE
Complex model with multiple input/output

### ISSUE THREAD

**Issue by frk1993** [tensorflow/serving#1370]
Hi,
I am trying to serve a complex model with 3 inputs and 7 output. To verify the saved model, I load the saved model and run it with session.run. I am facing slice index error.

Here is information about my model:
<img width="518" alt="Bildschirmfoto 2019-06-01 um 12 35 49" src="https://user-images.githubusercontent.com/45715708/58747854-1d582e80-8471-11e9-8687-efb3cb90fc63.png">

Here the code for loading and running the saved model: 
<img width="871" alt="Bildschirmfoto 2019-06-01 um 12 38 02" src="https://user-images.githubusercontent.com/45715708/58747861-319c2b80-8471-11e9-9c4c-32a807a3c898.png">

And here the error which I get:
<img width="839" alt="Bildschirmfoto 2019-06-01 um 12 41 59" src="https://user-images.githubusercontent.com/45715708/58747867-52648100-8471-11e9-91a5-30b8bbf4fa37.png">

I hope someone can help me.

best regards

**Comment by gowtham-kp** [comment]
@frk1993  Can yo please take a look at the [similar issue](https://github.com/tensorflow/serving/issues/1290) and let me know if that helps. Thanks!

**Comment by frk1993** [comment]
@gowtham-kp  Thanks I could solve the problem.

**Comment by gowtham-kp** [comment]
Closing this issue as the problem has been solved. Thank you for the response @frk1993
