### ISSUE TITLE
Add documentation for enabling and using batching

### ISSUE THREAD

**Issue by unclepeddy** [tensorflow/serving#1379]
Batching is [off by default](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/server.h#L54). 

Consider adding documentation that enables batching for the model server binary and shows an example batching param usage.
At the very least, 

* Add documentation to the top of batching g3doc explaining that users need to use the --enable_batching flag 
* Add small example of an example of a file you'd feed into batching_parameters_file

**Comment by netfs** [comment]
there is extensive doc here:

https://github.com/tensorflow/serving/tree/master/tensorflow_serving/batching

either refer to this if you are composing a new doc, or extend this with 'how to use in modelserver' section.

**Comment by unclepeddy** [comment]
Correct - this guide is what I am referring to by "batching g3doc." No new doc is needed.

One additional todo:

* Add reference to this doc from the main README

**Comment by unclepeddy** [comment]
Working on adding this; it should be in by end of next week.

**Comment by unclepeddy** [comment]
Review taking longer than anticipated. Should be out in the next week.

**Comment by unclepeddy** [comment]
This is now published as a part of the [serving configuration guide](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/serving_config.md)
