### ISSUE TITLE
Why inception serving images so big?

### ISSUE THREAD

**Issue by perhapszzy** [tensorflow/serving#138]
The TensorFlow model is only 381M:
```
-rw-r--r--  1 root   root 381M Jun  1 08:54 inception-v3-2016-03-01.tar.gz
```

but the serving image is  4.8G:
```
inception_serving                     latest              40bf448f3603        7 weeks ago         4.806 GB
```
Why is this image so big? Is there any possible ways to make the image smaller?

**Comment by fangweili** [comment]
Are you referring to the docker image described in g3doc/serving_inception.md?

First of all it's a docker image therefore the base image + installed binaries likely takes more than 1G already. More importantly, it downloads all source code (tf and tf/serving) and builds from scratch. Therefore the image contains all source files, intermediate object files, etc. To trim it, I think you can just keep the built inception_inference binary and delete everything else.

**Comment by perhapszzy** [comment]
That worked and the image size decreased to 500M. Thank you!
