### ISSUE TITLE
adding two tftrt customized plugins in tensorflow serving   failed 

### ISSUE THREAD

**Issue by tilaba** [tensorflow/serving#1380]
How can I serve model with tensorflow-serving, if there are two more customized tftrt_plugin ops? I have tested my customized tftrt ops in tensorflow, they works well. Then I followed the instructions given by "https://stackoverflow.com/questions/53284674/tensorflow-serving-with-contrib-operations". I find it works when I just added one customized tftrt ops. However, when two more tftrt_plugin ops are added, they failed and serving reports some errors which indicate that no tftrt_plugins can  be created.  The error reports like
" F external/org_tensorflow/tensorflow/contrib/tensorrt/plugin/trt_plugin_factory.h:80] Check failed: factory->RegisterPlugin(name, deserialize_func, construct_func) Failed to register plugin: Resize_PluginTRT ./run.sh: line 2: 29057 Aborted   (core dumped) CUDA_VISIBLE_DEVICES=3 ./tensorflow_model_server --port=10000 --model_config_file=./model_config.cfg --platform_config_file=./platform_config_file.cfg"

**Comment by vinuraja** [comment]
Looking at the plugin factory code [here](https://github.com/tensorflow/tensorflow/blob/6a9584ce062079ceb2db74d39195776c593820a8/tensorflow/compiler/tf2tensorrt/plugin/trt_plugin_factory.cc#L54-L64), it seems that you are trying to use the same op_name again. You would need different op_names for the plugins.
