### ISSUE TITLE
centos6.3 and docker1.7 can support GPU?

### ISSUE THREAD

**Issue by tradysun** [tensorflow/serving#1383]
My linux system is centos6.3, which only support docker1.7, and does not support nvidia-docker(need docker>=1.13). How to run tensorflow serving with GPU?

**Comment by minglotus-6** [comment]
Hi there,
   nvidia-docker is just a self-contained docker which already encapsulates gpu integration. To use tfs on GPU w/o nvidia-docker, you shall figure out how to do the integration of docker and gpu, and then start tf serving in it.
