### ISSUE TITLE
Can someone provide a mirror building with dockerfile.mkl?

### ISSUE THREAD

**Issue by Fordisk123** [tensorflow/serving#1385]
Can someone provide a mirror compiled according to dockerfile.mkl? I always report an error when building this image.
 
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/private/defs.bzl:18:17: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/private/defs.bzl:19:18: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/private/defs.bzl:20:16: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/private/defs.bzl:22:21: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/private/defs.bzl:23:17: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: error loading package '': in /tensorflow-serving/tensorflow_serving/workspace.bzl: in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/tensorflow/workspace.bzl: in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/defs.bzl: in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/webfiles/web_library.bzl: Extension file 'closure/private/defs.bzl' has errors
ERROR: error loading package '': in /tensorflow-serving/tensorflow_serving/workspace.bzl: in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/tensorflow/workspace.bzl: in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/defs.bzl: in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/webfiles/web_library.bzl: Extension file 'closure/private/defs.bzl' has errors
INFO: Elapsed time: 417.817s

**Comment by rmothukuru** [comment]
@Fordisk123 ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
