### ISSUE TITLE
build tensorflow_serving/... in mac OS failed

### ISSUE THREAD

**Issue by morningsky** [tensorflow/serving#1387]
The error is:
`Git Configuration Error: Traceback (most recent call last):
  File "/private/var/tmp/_bazel_edz/550329978356774a3c737ee01244b0bc/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 29, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins`

but my computer installed future package, and the terminal runs on python3 environment.
`Requirement already up-to-date: future in /anaconda3/lib/python3.7/site-packages (0.17.1)
`
How can I solved this?

**Comment by gowtham-kp** [comment]
@morningsky Can you please fill the [template](https://github.com/tensorflow/serving/issues/new). Thanks!

**Comment by devimonica** [comment]
@morningsky did you solve this ?

**Comment by npanpaliya** [comment]
If you are building tensorflow-serving using bazel, try adding following two arguments to bazel build command -
--action_env PYTHON_BIN_PATH=<python_exe path>
--define PYTHON_BIN_PATH=<python_exe path>

python_exe path should be the one being used by your build environment.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
