### ISSUE TITLE
Enable SupervisedInputReceiver

### ISSUE THREAD

**Issue by WangYongzhao** [tensorflow/serving#1389]
I want to serving a model with SupervisedInputReceiver, but I found this feature is not official supported by tensorflow. Is there replacement for this feature? if no, I suggest to enable this feature.

**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/export/export.py#L251
this class is not in the related __init__.py, so can't use it officially

**Will this change the current api? How?** I think no.

**Who will benefit with this feature?** who want to serve model with both input/output.

**Comment by gowtham-kp** [comment]
@WangYongzhao Can you please post this issue in [Tensorflow/tensorflow](https://github.com/tensorflow/tensorflow/issues) repository as this is not related to serving. Thanks!

**Comment by WangYongzhao** [comment]
emmm.... dead loop...
https://github.com/tensorflow/tensorflow/issues/30159

**Comment by gowtham-kp** [comment]
This definitely is a tensorflow issue only serves models with features that are a part Tensorflow. As SupervisedInputReceiver is not officially supported by Tensorflow, you cannot use a model that has this feature to serve it in TF Serving. Thanks!

**Comment by dhdaines** [comment]
why are you hiding this useful function from us? why does tensorflow insist on screwing with the namespace?
