### ISSUE TITLE
using CPU and GPU together

### ISSUE THREAD

**Issue by liaocz** [tensorflow/serving#1393]
hello, if i have a tensorflow model, i want some ops to use cpu and others use gpu, what can i do for it? thank you very much!

**Comment by rmothukuru** [comment]
@liaocz ,
Can you please check [this link](https://medium.com/@lisulimowicz/tensorflow-cpus-and-gpus-configuration-9c223436d4ef) if it helps.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tobegit3hub** [comment]
The SavedModel can store the information of device placement if you don't export with `clear_devices=True`. So TensorFlow Serving may place operators in CPU or GPU which is the same for training.
