### ISSUE TITLE
tf.saved_model.loader.load not reading the variable folder 

### ISSUE THREAD

**Issue by gr8Adakron** [tensorflow/serving#1396]
Hey,

I already have one image-segmentation model, which is TF-serving SavedModel model format and it works fine- with the TF-serving inference.
I have been migrating all the models to TRT-5.1.5-inference-server, obviously for the performance efficiency. I did the conversion for other models (ie: classification, object-detection) and it wasn't that complex, but as I trying to convert this image-segmentation model- the file after conversion isn't as big as others, seems like there nothing in the converted graph.

My conversion Script:
```
from tensorflow.python.framework import graph_util
from tensorflow.python.framework import graph_io
import tensorflow as tf

node_info_list_dict = []
export_path         = "/home/serving/serving_models/segmentation/5"

with tf.Session(graph = tf.Graph()) as sess:
    tf.saved_model.loader.load(sess, ["serve"], export_path)
    graph             = tf.get_default_graph()
    nodes_list        = graph.get_operations()
    #print(nodes_list)


for op in graph.get_operations(): 
    for val_obj in op.values():
        #print(str(val_obj.shape))
        node_info_list_dict.append(
            {
                "name" : op.name,
                "shape": str(val_obj.shape),
                "dtype": str(val_obj.dtype),
            }
        )

constant_graph = graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(), [node_info_list_dict[-1]["name"]])    
graph_io.write_graph(constant_graph, "segmentation_trt", "model.graphdef", as_text=False)

```
_**This script worked for other models.**_

The model structure before conversion **(tf-serving format)**:
![trt-issue](https://user-images.githubusercontent.com/16715364/61181167-f7ad7000-a63f-11e9-842e-b5466c3b7d09.png)
Size of the file inside it:

> 
> -rw-rw-r-- 1 serving serving **531K** May 27 09:18 5/saved_model.pb
> -rw-rw-r-- 1 serving serving **5.6K** May 27 09:18 5/variables/variables.index
> -rw-rw-r-- 1 serving serving **424M** May 27 09:19 5/variables/variables.data-00000-of-00001
> 
> 

Size of the files after conversion:

> -rw-rw-r-- 1 serving serving **4.5K** Jul 13 07:39 model.graphdef

I am not sure what going wrong here. 
Any help, is appreciated.

**Comment by gr8Adakron** [comment]
@ewilderj @kchodorow @lamberta @montanaflynn

**Comment by rmothukuru** [comment]
@gr8Adakron ,
When you mentioned **_This script worked for other models_**, can you please mention the Sizes of files before and after conversion for those models.

**Comment by aaroey** [comment]
@gr8Adakron is it possible for you to share the original model before conversion for us to investigate?
Thanks.

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
