### ISSUE TITLE
couldn't find  1.13.0 version in apt package

### ISSUE THREAD

**Issue by golisandeep3** [tensorflow/serving#1399]
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
-  Linux Ubuntu 18.04

### Describe the problem
Couldn't install 1.13.0 version using apt command.

### Exact Steps to Reproduce
apt-get install tensorflow-model-server=1.13.0

**Comment by rmothukuru** [comment]
@golisandeep3 ,
Can you please provide the error message which you are getting. Also, can you please try installing TF Serving using Docker, as it is the recommended and the easy way and let us know on how it goes.

**Comment by orf** [comment]
There isn't anything really to describe: Tensorflow 1.13.0 has been removed from the apt repository.

```
root@3dac626c2e43:/# apt list -a tensorflow-model-server
Listing... Done
tensorflow-model-server/unknown,now 1.14.0 all [installed]
```

Running:
```
apt install tensorflow-model-server=1.13.0
```
Throws an error:
```
E: Version '1.13.0' for 'tensorflow-model-server' was not found
```
Docker is not suitable for all situations, and removing a package like this will break builds.

**Comment by golisandeep3** [comment]
@rmothukuru  I am installing it using docker. We fix the tensorflow serving version inside the dockerfile.

**Comment by rmothukuru** [comment]
@golisandeep3 ,
If I understand your comment correctly, you could install Tensorflow Serving successfully using Docker after changing the TF Serving Version inside the Dockerfile. Please confirm if my understanding is correct.

**Comment by golisandeep3** [comment]
@rmothukuru It doesn't matter where you install it, inside docker or not. The 1.13.0 version is removed from apt package. It has only 1.14.0.   This command fails to run 
`apt-get install tensorflow-model-server=1.13.0`
This command `apt-get install tensorflow-model-server` works because it installs 1.14.0 version.

We have to add all previous versions to apt package.

**Comment by netfs** [comment]
--

**Comment by netfs** [comment]
we do not support installing older packages via apt presently.

you need to manually download the debian package and install it by hand. you can borrow the command line from here:

https://github.com/tensorflow/serving/blob/eeda7713f12be04a47b2facdb15f98a089a25eaf/tensorflow_serving/tools/docker/Dockerfile#L26

**Comment by orf** [comment]
Not gonna lie, that is ridiculous and should be documented in big bold text right after the apt instillation instructions.

If you are not going to actually support apt (of which package versions are a huge part) then just give instructions on how to wget a binary from a bucket. Don’t bother with apt at all.

**Comment by gowtham-kp** [comment]
@orf Closing the issue as it has been resolved. Please add additional comments and we can open the issue again. Thanks!
