### ISSUE TITLE
Ques: Install TFX-GPU into a Docker container?

### ISSUE THREAD

**Issue by joehoeller** [tensorflow/serving#1402]
How do you install TFX-GPU into a custom Docker container?

I have tried the following in my Dockerfile:

```

RUN git clone https://github.com/tensorflow/serving.git
WORKDIR ./serving/tools/
RUN run_in_docker.sh bazel build -c opt tensorflow_serving


```

...but to no avail :(

**Comment by gowtham-kp** [comment]
Do you want to install tfx or tf-serving? As I can see here that, you are trying to install TF Serving not TFX

**Comment by joehoeller** [comment]
Sorry, I must've got my wires crossed, or the documents I read weren't
clear. (It's one or the other). Can you please, first, explain the
difference between TFServing and TFX? That way I can confirm my intent.

**Comment by gowtham-kp** [comment]
@joehoeller A TFX pipeline is a sequence of components that implement an ML pipeline which is specifically designed for scalable, high-performance machine learning tasks. You can also go through through the [TFX guide](https://www.tensorflow.org/tfx/guide) to understand all the components in TFX. Where as TF serving makes it easy to deploy new algorithms and experiments, while keeping the same server architecture and APIs. You can go through the [TF Serving](https://www.tensorflow.org/tfx/guide/serving) guide to understand the functionality of TF Serving.

**Comment by joehoeller** [comment]
Got it. My intent was TF Serving then.

**Comment by gowtham-kp** [comment]
Recommended way of installing TF Serving GPU is by using Docker image inorder to avoid complexities of building from source. This [website](https://www.tensorflow.org/tfx/serving/docker) gives you a clear idea of how to install TF Serving.

**Comment by joehoeller** [comment]
How would I connect it to a separate TensorFlow container then?

**Comment by gowtham-kp** [comment]
@joehoeller Please post these questions on stackoverflow as this is not Related to TF Serving. 
Thanks!
