### ISSUE TITLE
Update: from tensorflow.contrib.session_bundle import exporter

### ISSUE THREAD

**Issue by Mazecreator** [tensorflow/serving#141]
I am not sure how to get to this site directly other than Googling:
tensorflow.github.io/serving/serving_basic

This page should be updated to reflect the changes to contrib.session_bundle as show here:
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/serving_basic.md

**Comment by kirilg** [comment]
Done. Thanks!
