### ISSUE TITLE
Add support for version labels to HTTP server

### ISSUE THREAD

**Issue by habichta** [tensorflow/serving#1413]
### System information
- Ubuntu 18.04
- TensorFlow ModelServer: 1.14.0-rc0+dev.sha.34d9e85
- TensorFlow Library: 1.14.0
Installed from Binary
(Also tried using the latest Docker container and the nightly build)

### Describe the problem
I have installed the latest tensorflow_model_server from the repository (apt)
I am trying to serve a model with multiple versions (which works) using version_labels (does not work). 

I was following: [this tutorial](https://www.tensorflow.org/tfx/serving/serving_config)
(There is also a typo in the docu:  --**alow**_version_labels_for_unavailable_models)

I get 
`unknown argument: --allow_version_labels_for_unavailable_models`
and 

`Failed to start server. Error: Failed precondition: Request to assign label to version 2 of model model1, which is not currently available for inference`

I understand, that the model needs to be available before labels can be used. However, with the current version the option to allow labels for unavailable models is not recognized.

I also tried the nightly docker build. There the option is recognized and I can start the tensorflow_model_server. However, when I try to dispatch a request

`http://localhost:8501/v1/models/model1/versions/{label}:predict`

(If there is a different URI for version labels then I could not find it in the documentary)

it does not recognize the label. Even though the version it refers to is available. For example:

`http://localhost:8501/v1/models/model1/versions/2:predict` 
works

What I tried next was to first deploy the model versions without version labels and then update the model.config later on. However, in the tensorflow_model_server version mentioned above, I was unable to set 
`model_config_file_poll_wait_seconds`
as it was also not recognized.

It does work in the nightly build.

Given that the option to use labels is described in the documentation, I assume that it should work in the currently available version. If not, it should be mentioned (clearly) that the tensorflow_model_server  binary in the repository does not support these options

### Exact Steps to Reproduce

- Start above tensorflow_model_server with 2 versions (this works)
- try version_labels with `--allow_version_labels_for_unavailable_models` flag

### Source code / logs
model.config: (for docker)

```
model_config_list: {
    config: {

        name: "model1"
        base_path: "/models/model1"
        model_platform:"tensorflow"

        model_version_policy:{

            specific:{

                versions:1
                versions:2

                }
             }

              version_labels: {
                key: 'stable'
                  value: 1
              }

              version_labels: {
                key: 'canary'
                  value: 2
              }
   }
}

```

`

**Comment by gowthamkpr** [comment]
@habichta This is similar to the issue #1230 . As of now, a label can be assigned only to a model version that is already loaded and available for serving. We will consider this as a feature request.

**Comment by habichta** [comment]
Thanks for your answer. I encounter this problem (#1230) using the current docker build (latest). 
However, as I mentioned above, I tried a nightly docker build as well (probably including the commit your mentioned). There I could start the server without problems. Yet, when I try to send a request to the server using the label:

`http://localhost:8501/v1/models/model1/versions/{label}:predict` 

I get an error, even though the model is up and running (I can successfully get a prediction using the actual version number instead of the label)

Maybe the structure of the URI I used is incorrect. I couldn't find a clear documentation

**Comment by unclepeddy** [comment]
This is expected behavior
- Re: latest released version of tensorflow-model-server ([1.14](https://github.com/tensorflow/serving/releases/tag/1.14.0)) does not include the change you described - but :latest does so using docker is the way to go (for another week or so before we release next version)
- Re: not being able to access the version using labels via HTTP - this is something that's not possible today (AFAIR) - only through the grpc interface can you declare labels :( 

If I've captured your problem correctly please confirm and I'll change this to a feature request to "Add support for version labels to HTTP server"
/cc @netfs

**Comment by habichta** [comment]
Ok that clears it up. Thank you

**Comment by umang-singhal** [comment]
Any update on this? As it stands, it is not resolved even in tf model server 2.0.

**Comment by tejaslodaya** [comment]
+1

**Comment by abhinavos7a** [comment]
@gowthamkpr Do we have any updates on this. We have been waiting for this feature for quite some time now. 

Having this capability would allow us to do do client side A/B testing with ease. With versions it becomes confusing.

**Comment by marcoadurno** [comment]
Just to mention that the official documentation suggests that labels should work with the REST API (see [here](https://www.tensorflow.org/tfx/serving/serving_config#assigning_string_labels_to_model_versions_to_simplify_canary_and_rollback)), but as of 2.2.0 this is still not working.

Is there any update on this?

Thank you,

Marco

**Comment by misterpeddy** [comment]
Yeah this was fixed in https://github.com/tensorflow/serving/commit/3df036223b66738de1b873e9b163230fb7661cb4 which did not make it to 2.2.

The documentation is unfortunately generated off of master, and so it describes the features that may not be available in the latest release. HTTP support for labels should be available in the latest Docker images and the next release.
