### ISSUE TITLE
question about warm up 

### ISSUE THREAD

**Issue by mcf330** [tensorflow/serving#1414]
I've created warmup data following the official guideline as below, and I launched the  model_server with the option --enable_model_warmup=true, but I did not see any improvement of the latency for the first request and I did not see any logs about loading warmup data.

I tested the issue on both tensorflow-serving:1.12-gpu and tensorflow-sering:latest-gpu docker build.

https://www.tensorflow.org/serving/saved_model_warmup

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by mcf330** [comment]
System information

Ubuntu 16.04
TensorFlow ModelServer: 1.13.0-rc1
TensorFlow Library: 1.13.0
Installed from Docker container 

Describe the problem

I've created warmup data following the official guideline as below, and I launched the model_server with the option --enable_model_warmup=true, but I did not see any improvement of the latency for the first request and I did not see any logs about loading warmup data.I tested the issue on both tensorflow-serving:1.12-gpu and tensorflow-sering:latest-gpu docker 

Exact Steps to Reproduce

1. following the official guideline to create warmup data named 'tf_serving_warmup_requests' and copied it to /models/model/${verison}/assets.extra2
2.  launch the model_server from the latest-gpu docker image, such as
docker run --runtime=nvidia -p 8501:8501 -t tensorflow/serving:latest-gpu --enable_model_warmup=true

**Comment by rmothukuru** [comment]
@mcf330 ,
Can you please confirm if the format of the file, `tf_serving_warmup_requests` is `TFRecord`, that is, if it is like, `tf_serving_warmup_requests.TFRecord`. 

If not, can you please try by adding `TFRecord` extension. 

If it still doesn't work, can you please share

1. SignatureDefs of your model executing the command, `saved_model_cli show`
2. Script you have used to generate `tf_serving_warmup_requests.TFRecord` file
3. As shown in [this Tutorial](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple), can you please run the command, `!tail server.log` and share the logs. As shown in the below screenshot, it gives information if Warm Up File is present or not.  

![image](https://user-images.githubusercontent.com/48206667/62932091-1b99d800-bddd-11e9-8cff-d8f9910d48b6.png)

Thanks.

**Comment by mcf330** [comment]
@rmothukuru  thanks for your help.

adding TFRecord extension did not work for me.

I did not see any information show up about warmup , instead, I saw msg below:

The specified SavedModel has no variables; no checkpoints were restored

I created the saved model from a frozen graph, so I have no variables( the variables folder is empty),  
does it affect warmup? I can run predictions properly

**Comment by christisg** [comment]
The lack of variables folder is orthogonal to the warmup functionality.
For the warmup to work properly, the warmup requests should be placed into a TFRecord file named tf_serving_warmup_requests (no TFRecord extension needed), and it should be placed under /models/model/${verison}/assets.extra/ of your model.
Please confirm that the folder the file tf_serving_warmup_requests is placed under is assets.extra and not assets.extra2.
If the warmup records were consumed successfully, you should see the following in your Model Server logs:
"Finished reading warmup data for model..."

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
