### ISSUE TITLE
Dockerfile.devel-mkl bazel build fails with no such target '@com_google_absl//absl/base:log_severity'

### ISSUE THREAD

**Issue by mohammedayub44** [tensorflow/serving#1417]
Creating the Optimized Tensorflow Binaries from Dockerfile.devel-mkl fails on Ubuntu 16.04

### System information
OS: Ubuntu 16.04
Tensorflow Version: 1.12.0
Python: 3.6.8
Cuda Version: 9.0
![image](https://user-images.githubusercontent.com/7122670/62954004-9f8f9800-bdbc-11e9-8bdc-05e98b024db5.png)

### Exact Steps to Reproduce
Clone the repo.
Change Line 14 in https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel-mkl to `FROM ubuntu:16.04 as base_build` 
run the below command - 
`docker build -t $USER/tensorflow-serving-devel-mkl -f /home/ubuntu/serving/tensorflow_serving/tools/docker/Dockerfile.devel-mkl2 .`

Log Snapshot and File:
[Dockerfile.devel-mkl_log.txt](https://github.com/tensorflow/serving/files/3497700/Dockerfile.devel-mkl_log.txt)

![image](https://user-images.githubusercontent.com/7122670/62954406-568c1380-bdbd-11e9-9658-1cf855200364.png)

**Comment by netfs** [comment]
this should be fixed by 1c0291118f34ec7ba958a9cee594414f6531c0f3.

please retry building from latest sources, and reopen if this is still broken.

thanks!
