### ISSUE TITLE
bazel build tensorflow_serving/... failed

### ISSUE THREAD

**Issue by Vin-Yuan** [tensorflow/serving#142]
Hello,
when i run the "bagel build tensorflow_serving/... " as reference in instruction, the follow problem occur:
`ERROR: /home/xxx/.cache/bazel/_bazel_sfh/8cc9f124026b87a47769e573ad0262de/external/protobuf/BUILD:228:1: C++ compilation of rule '@protobuf//:protoc_lib' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' ... (remaining 46 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.`
Before i guess it was bazel version lead to, then i change 3.0 to 2.2, it still occurred, then i think it may be caused by the gcc version , then i try gcc 4.8 , 4.9 and 5.0, it all can't help, could you please some advice and any solution to tackle it? I would appreciate it!

bellow is my environment:
OS:Ubuntu 16.04 LT
gcc version 4.9.3 
Build label: 0.2.2- (@non-git)
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 26 09:50:57 2016 (1469526657)
Build timestamp: 1469526657
Build timestamp as int: 1469526657

**Comment by xeb** [comment]
Have you used or compared your environment to the [Dockerfile.devel example](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel) in the repository?  I've found that building in a container helps isolate any dependencies and the very least compare against other dependency versions on another system. 

A few ideas based on your log:
- Clear your bazel cache (~/.cache/bazel/)
- Verify you cloned git submodules correctly
- Look over the [Dockerfile.devel example](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel) to see if you're missing any install steps

**Comment by lanlingcloud** [comment]
Hi @Vin-Yuan,
I get the same error with (ubuntu16.04, bazel0.3.2, tensorflow_serving0.41, gcc 5.4), have you solved the problem?

**Comment by kirilg** [comment]
Closing old bug. If you're seeing this issue at current head, please file a new issue.
