### ISSUE TITLE
How to serving models not prediction

### ISSUE THREAD

**Issue by DiMiTriFrog** [tensorflow/serving#1420]
I don’t find samples for serving tensorflow models that not use for predict.
I trying to make a tensorflow serving of pix2pix.

**Comment by gowthamkpr** [comment]
Closing this issue as its has been inactive for more than 14 days. Please add additional comments and we can open the issue again. Thanks!

**Comment by stefanondisponibile** [comment]
How can I use the `classify` api when exporting a `Module` in `tf 2.0`? [It seems](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/save.py#L466) only `PREDICT_METHOD_NAME` will be exported for all the signatures.
