### ISSUE TITLE
Tensorflow serving Batching configuration docs has bunch of broken links

### ISSUE THREAD

**Issue by aaur0** [tensorflow/serving#1421]
### System information
- **MacOS Mojave (Chrome)
- **TensorFlow Serving Website**:
- **NA**:

### Describe the problem
All the link under batching configuration section in the official documents return 404.
Broken URL : https://www.tensorflow.org/tfx/serving/serving_config#batching_configuration

### Exact Steps to Reproduce
Click on following Links

https://www.tensorflow.org/tfx/batching/README#servers_with_multiple_models_model_versions_or_subtasks

https://www.tensorflow.org/tfx/batching/README

https://www.tensorflow.org/tfx/batching/README#batch_scheduling_parameters_and_tuning

### Source code / logs
Screen Shot of the error message : [`404 Error Message`](https://imgur.com/a/L8b1UBY)

**Comment by gowthamkpr** [comment]
@aaur0 Thanks for reporting.

**Comment by minglotus-6** [comment]
Thanks for reporting this!

We are working on fixing broken links. In the meanwhile, https://github.com/tensorflow/serving/blob/master/tensorflow_serving/batching/README.md should be the intended batching guide.

**Comment by unclepeddy** [comment]
This has been fixed
