### ISSUE TITLE
Pinning data on the GPU for post_gpu_model  processing?

### ISSUE THREAD

**Issue by tilaba** [tensorflow/serving#1423]
after runing the tensorflow sess->run API, can the output data of tensorflow model stay in gpu device memory without being transfered to host memory.

**Comment by rmothukuru** [comment]
@tilaba ,
This issue is not related to Serving but it is related to Tensorflow (core functionality). Request you to raise an issue in [Tensorflow Github Repository](https://github.com/tensorflow/tensorflow/issues). Thanks!

**Comment by rmothukuru** [comment]
Closing the issue as it is not related to Tensorflow Serving.
