### ISSUE TITLE
building TF Serving version 1.10.0

### ISSUE THREAD

**Issue by amrithadevadiga** [tensorflow/serving#1424]
Hi all,

Can some one give me steps to build TF Serving version 1.10.0 on centos7 image

**Comment by amrithadevadiga** [comment]
@gowthamkpr Hi , Thank you for the reply.

But i got error.
i followed this steps from the link which you provided:
$ git clone -b r1.10 https://github.com/tensorflow/serving.git
...
$ cd serving
$ tools/run_in_docker.sh -d tensorflow/serving:1.10-devel \
  bazel build tensorflow_serving/...
...
error
tools/run_in_docker.sh -d tensorflow/serving:1.10-devel \
>   bazel build tensorflow_serving/...
bash: tools/run_in_docker.sh: No such file or directory

**Comment by amrithadevadiga** [comment]
@gowthamkpr 

i have tried this method:

yum -y install java-1.8.0-openjdk-devel
yum -y install gcc gcc-c++ kernel-devel make automake autoconf swig git unzip libtool binutils
yum -y install epel-release
yum -y install python-devel python-pip
pip install --upgrade pip
yum -y install freetype-devel libpng12-devel zip zlib-devel giflib-devel zeromq3-devel patch
pip install grpcio_tools mock keras tensorflow
cd /opt
wget git clone -b r1.10 https://github.com/tensorflow/serving.git
wget https://github.com/bazelbuild/bazel/releases/download/0.15.0/bazel-0.15.0-installer-linux-x86_64.sh
sh bazel-0.15.0-installer-linux-x86_64.sh
cd serving/
export PATH=/usr/local/bin:$PATH
bazel build --cxxopt=-std=c++11 -c opt tensorflow_serving/... incompatible_remove_native_http_archive=false --incompatible_package_name_is_a_function=false

but when i tried "bazel build --cxxopt=-std=c++11 -c opt tensorflow_serving/... incompatible_remove_native_http_archive=false --incompatible_package_name_is_a_function=false" this i got an error too

"external/org_tensorflow/tensorflow/core/util/tensor_format.h: In function 'int tensorflow::GetTensorSpatialDims(int, tensorflow::TensorFormat)':

external/org_tensorflow/tensorflow/core/util/tensor_format.h:124:1: warning: control reaches end of non-void function [-Wreturn-type]

 }

 ^

ERROR: /root/.cache/bazel/_bazel_root/9886c9acf011eba2b5d5f211eb97e970/external/org_tensorflow/tensorflow/core/BUILD:2441:1: C++ compilation of rule '@org_tensorflow//tensorflow/core:framework_internal_impl' failed (Killed): gcc failed: error executing command /bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 138 argument(s) skipped)

[3,552 / 6,334] 6 actions running

    @org_tensorflow//tensorflow/core:framework_internal_impl; 117s local

    @org_tensorflow//tensorflow/core:framework_internal_impl; 25s local

    @org_tensorflow//tensorflow/core:framework_internal_impl; 25s local

    @org_tensorflow//tensorflow/core:framework_internal_impl; 11s local

    @org_tensorflow//tensorflow/core:framework_internal_impl; 8s local

    @org_tensorflow//tensorflow/core:framework_internal_impl; 7s local
Server terminated abruptly (error code: 14, error message: '', log file: '/root/.cache/bazel/_bazel_root/9886c9acf011eba2b5d5f211eb97e970/server/jvm.out')"

**Comment by gowthamkpr** [comment]
Did you run this command 
`run_in_docker.sh bazel build tensorflow_serving/model_servers:tensorflow_model_server`

If yes whats the output that you are getting @amrithadevadiga

**Comment by amrithadevadiga** [comment]
Yes i have run that too.(run_in_docker.sh bazel build tensorflow_serving/model_servers:tensorflow_model_server)

output is same
ERROR: 'docker' command missing from PATH.
Usage:
run_in_docker.sh [-d ] [-o ] [args ...]

Examples:
run_in_docker.sh bazel build tensorflow_serving/model_servers:tensorflow_model_server
run_in_docker.sh python tensorflow_serving/example/mnist_saved_model.py /tmp/mnist
run_in_docker.sh -d tensorflow/serving:latest-devel bazel version

**Comment by gowthamkpr** [comment]
Are you building it on windows?

**Comment by amrithadevadiga** [comment]
no am building it on Centos7

**Comment by gowthamkpr** [comment]
Looks like you don't have docker installed @amrithadevadiga Can you please install docker and try running the command again. Thanks!

**Comment by rmothukuru** [comment]
@amrithadevadiga,
You can install Docker from [this link](https://docs.docker.com/get-started/#test-docker-installation).
