### ISSUE TITLE
The grpc interface used by the serving(docker bazel installed) is different from the grpc.io interface(grpc sourcecode make installed).

### ISSUE THREAD

**Issue by HUTOYP** [tensorflow/serving#1427]
### Describe the problem

./include/tensorflow_serving/apis/prediction_service.grpc.pb.h: In constructor 'tensorflow::serving::PredictionService::ExperimentalWithCallbackMethod_Classify<BaseClass>::ExperimentalWithCallbackMethod_Classify()':
_./include/tensorflow_serving/apis/prediction_service.grpc.pb.h:308:196_: **error: wrong number of template arguments (3, should be 2)**
         _new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithCallbackMethod_Classify<BaseClass>, ::tensorflow::serving::ClassificationRequest, ::tensorflow::serving::ClassificationResponse>_(

### Describe alternatives you've considered
**grpc interface dependent on serving（docker bazel autobuild）：**
```
template <class ServiceType, class RequestType, class ResponseType>
class CallbackUnaryHandler : public MethodHandler {
 public:
  CallbackUnaryHandler(
      std::function<void(ServerContext*, const RequestType*, ResponseType*,
                         experimental::ServerCallbackRpcController*)>
          func,
      ServiceType* service)
      : func_(func) {}
```

**grpc sourcecode make：**
```
template <class RequestType, class ResponseType>
class CallbackUnaryHandler : public MethodHandler {
 public:
  CallbackUnaryHandler(
      std::function<void(ServerContext*, const RequestType*, ResponseType*,
                         experimental::ServerCallbackRpcController*)>
          func)
      : func_(func) {}
```

I want to use the static library version compiled with the official version of grpc，what should I do?

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS7.4 + gcc 4.8.5
- **TensorFlow Serving installed from (source or binary)**: docker bazel
- **TensorFlow Serving version**: 1.13.0
- **grpc version**: 1.18.0

**Comment by vinuraja** [comment]
Seems like the the grpc version used by Bazel build rules to create the prediction_service.pb.h files are different from the ones installed via grpc io. Unfortunately I am not aware of how to increase the grpc version bazel depends on. Asking on bazel forums might be a good option.

Another alternative would be to try and reduce the version of grpc to something like 1.10.1, according to the details at https://github.com/pubref/rules_protobuf/#rules.

**Comment by HUTOYP** [comment]
I tried to use V1.14.0(Released on 3 Aug 2018), so It is possible that the older version is right, but I won`t to try temporarily, I can solve this problem by using the Bzel build third_party grpc version.

Thanks.

**Comment by rmothukuru** [comment]
Closing the issue as it has been answered. Thanks!
