### ISSUE TITLE
Why http rest api listen on lo address?

### ISSUE THREAD

**Issue by xxmyjk** [tensorflow/serving#1429]
https://github.com/tensorflow/serving/blob/34d9e855d94bb87614603e0ae91e90674eea68be/tensorflow_serving/model_servers/server.cc#L333

serving  inside docker listening on `localhost` can't get access outside.

**Comment by xxmyjk** [comment]
Is this a bug or designing for other reason?

**Comment by rmothukuru** [comment]
@xxmyjk ,
Can you please provide more details regarding your question. If you feel this is a bug, please fill out the following form in full:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow Serving installed from (source or binary)**:
- **TensorFlow Serving version**:

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in
TensorFlow Serving.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached. Try to provide a reproducible test case that is the bare
minimum necessary to generate the problem.

Thanks!

**Comment by xxmyjk** [comment]
seems this is just a typo or something, `net_http` only listening on port will listen on broadcast address auto, `server_address` of `localhost` in log makes misunderstanding here.

```c++
const string server_address =
          "localhost:" + std::to_string(server_options.http_port);
```
