### ISSUE TITLE
the problem of the resnet_client.py script

### ISSUE THREAD

**Issue by colddew** [tensorflow/serving#1430]
hi, all

https://github.com/tensorflow/serving/blob/r1.14/tensorflow_serving/example/resnet_client.py

when i execute this python script, i always have the error as follow, and i only change the SERVER_URL and IMAGE_URL config, who encounter this problem?

![image](https://user-images.githubusercontent.com/6032545/63875566-4cd9f100-c9f6-11e9-8060-199c4921c628.png)

**Comment by gowthamkpr** [comment]
Please take a look at the similar [issue](https://github.com/tensorflow/serving/issues/1317) and let me know if it helps. Thanks!

**Comment by colddew** [comment]
maybe i use the inception_v3 model and transfer learning, this script does not work properly, and i change to use keras api to handle image, thanks anyway.

**Comment by gowthamkpr** [comment]
sure. Can I close this issue as it has been resolved @colddew

**Comment by colddew** [comment]
ok, thx
