### ISSUE TITLE
bazel-bin folder is missing

### ISSUE THREAD

**Issue by amrithadevadiga** [tensorflow/serving#1431]
i am using centos-7 machine to build a TF model server from source code when i executed a bazel build command "bazel build --cxxopt=-std=c++11 -c opt tensorflow_serving/... --incompatible_remove_native_http_archive=false --incompatible_package_name_is_a_function=false"it is not giving any error but bazel-bin directory is not available.
please find output of the command and help me out to find the TF model bin
![Capture1](https://user-images.githubusercontent.com/44697236/63930664-65d3b800-ca71-11e9-8856-fba1ce84a2d3.PNG)

**Comment by vinuraja** [comment]
Seems like a bazel issue, worth asking in bazel forums.

It might be that you don't have write permissions in that directory you're in.

Some other suggestions to try out:
1. Maybe your .bazelrc has some issue.
```shell
bazel --bazelrc=/dev/null build --cxxopt=-std=c++11 -c opt tensorflow_serving/... --incompatible_remove_native_http_archive=false --incompatible_package_name_is_a_function=false
```
2. Try explicitly providing an output directory.
```shell
bazel --output_base=/tmp/bazel/output --cxxopt=-std=c++11 -c opt tensorflow_serving/... --incompatible_remove_native_http_archive=false --incompatible_package_name_is_a_function=false
```

**Comment by amrithadevadiga** [comment]
Thank you for the reply.

**Comment by rmothukuru** [comment]
Closing the issue as it has been answered.
