### ISSUE TITLE
serving with two inputs for text recognition where it needs input image and the sequence length.

### ISSUE THREAD

**Issue by eravallirao** [tensorflow/serving#1439]
How to pass the inputs to the url for getting the output.
payload_1 = {
   "instances" : [{'image': image1.tolist()},
    {'image_length': seq_len.tolist()}]
}
print(payload_1)
url = "http://localhost:8501/v1/models/serving:predict"
res_1 = requests.post(url, json=payload_1)

I am getting <Response [400]>

**Comment by gowthamkpr** [comment]
Please refer to the following [link](https://sthalles.github.io/serving_tensorflow_models/) which explain in detail of how to serve a tensorflow model and let me know if it helps!

**Comment by gowthamkpr** [comment]
Closing this issue as its inactive for more than 15 days. Please add additional comments and we can open the issue again. Thanks!
