### ISSUE TITLE
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:9000/v1/models/saved_model:predict

### ISSUE THREAD

**Issue by Panshangka** [tensorflow/serving#1442]
When I use the TF serving Rest API:
tensorflow_model_server --rest_api_port=9000 --model_name=saved_model --model_base_path=/home/psk/model-export/pb/

It works fine:
2019-09-17 19:11:46.005431: I tensorflow_serving/model_servers/server.cc:324] Running gRPC ModelServer at 0.0.0.0:8500 ...
2019-09-17 19:11:46.005957: I tensorflow_serving/model_servers/server.cc:344] Exporting HTTP/REST API at:localhost:9000 ...
[evhttp_server.cc : 239] RAW: Entering the event loop ...

When I try to send data, my code looks like this:
`wav1_data, wav2_data, match = feeder.create_infer_batch()

b64_code = base64.b64encode(wav1_data)
b64_code = b64_code.decode('utf-8')

predict_request = '{"instances" : [{"b64": "%s"}]}' % b64_code

response = requests.post(SERVER_URL, data=predict_request)

response.raise_for_status()`

type of wav1_data is numpy array, the I encode this to be base64. Then I get this error:
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:9000/v1/models/saved_model:predict

Then I type http://localhost:9000/v1/models/saved_model, It shows:
{
 "model_version_status": [
  {
   "version": "1",
   "state": "AVAILABLE",
   "status": {
    "error_code": "OK",
    "error_message": ""
   }
  }
 ]
}

Then I type: http://localhost:9000/v1/models/saved_model:predict ,something went wrong:
{ "error": "Malformed request: GET /v1/models/saved_model:predict" }

I didn't know where does it went wrong?

**Comment by gowthamkpr** [comment]
@Panshangka Please take a look at this [answer](https://github.com/tensorflow/serving/issues/1317#issuecomment-483401285) and let me know if it helps. Thanks!

**Comment by Panshangka** [comment]
> @Panshangka Please take a look at this [answer](https://github.com/tensorflow/serving/issues/1317#issuecomment-483401285) and let me know if it helps. Thanks!
Now this error:
response.status_code: 400
response.content: b'{ "error": "Serving signature name: \\"serving_default\\" not found in signature def" }'
When I convert my model, I remembered defining the input signature and output signature.

tensor_info_input = tf.saved_model.utils.build_tensor_info(model.input_batch)
 # output tensor info
tensor_info_output = tf.saved_model.utils.build_tensor_info(model.norm_out)

**Comment by Panshangka** [comment]
> @Panshangka Please take a look at this [answer](https://github.com/tensorflow/serving/issues/1317#issuecomment-483401285) and let me know if it helps. Thanks!

Now this error:
response.status_code: 400
response.content: b'{ "error": "Serving signature name: \"serving_default\" not found in signature def" }'
When I convert my model, I remembered defining the input signature and output signature.

tensor_info_input = tf.saved_model.utils.build_tensor_info(model.input_batch)

output tensor info
tensor_info_output = tf.saved_model.utils.build_tensor_info(model.norm_out)

**Comment by Panshangka** [comment]
> @Panshangka Please take a look at this [answer](https://github.com/tensorflow/serving/issues/1317#issuecomment-483401285) and let me know if it helps. Thanks!

After I add the signature name, It worked! 
Thank you so much!

**Comment by gowthamkpr** [comment]
@Panshangka Closing this issue as it has been resolved.
