### ISSUE TITLE
Served model delivers incorrect predictions

### ISSUE THREAD

**Issue by digital-thinking** [tensorflow/serving#1443]
## Bug Report
When serving a effifientnet model, which was trained in keras and exported to SavedModel format, tensorflow model server gives different predictions compared to 
1. loading the savedModel in Java and making predictions 
2. serving the model with keras and Flask.

### System information
AWS EC2: Deep Learning AMI (Ubuntu) Version 23.1 (ami-0ab24eef0e14017ef)
TensorFlow ModelServer: 1.13.0-rc1+dev.sha.f16e7778
TensorFlow Library: 1.13.1

### Describe the problem
I exported a keras model as a SavedModel, which delivers correct predictions, when loaded in java and also, when using the keras model artifact directly. When serving this model with tensorflow_model_server the model delivers different predictions. They are not completly wrong but the difference is noticable. Some samples are misslcassified with tensorflow_model_server but work with the other solutions above. I wonder especially beacuse it works by loading the savedModel in other languages like java.

**Comment by gowthamkpr** [comment]
@digital-thinking Can you please provide a github gist or a reproducible code for us to explore as to why this is happening as its too vague for us right now to determine the root cause of this issue. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 14 days. Please add additional comments and we can open the issue again. Thanks!

**Comment by Amrimn** [comment]
I have the same problem with tensorflow model server, the predictions are different even if it is the same image. did you find the reason?

**Comment by digital-thinking** [comment]
In my case I updated the version and it was magically fixed. There are still some numerical differences, but overall it works.
