### ISSUE TITLE
Tensorflow Serving Bad Docker Example

### ISSUE THREAD

**Issue by DonaldM164** [tensorflow/serving#1448]
I originally opened this up on the tensorflow repo but I was directed to open it up here, which makes sense. The original ticket can be viewed at this [link](https://github.com/tensorflow/tensorflow/issues/32716). 

Please provide a link to the documentation entry:
https://www.tensorflow.org/tfx/serving/docker

Description of issue (what needs changing):
The first example does not work when you get to this command:

docker run -t --rm -p 8501:8501
-v "$TESTDATA/saved_model_half_plus_two_cpu:/models/half_plus_two"
-e MODEL_NAME=half_plus_two
tensorflow/serving &

The command will repeatedly return the error:
"No versions of servable half_plus_two found under base path /models/half_plus_two"

This happens when you go through all of the steps sequentially, as they are listed in that example.

Additionally, the example has the headline "One of the easiest ways to get started using TensorFlow Serving is with Docker."

This is contradicted by the difficulties experienced with that example.

Submit a pull request?
I'm afraid I don't know what the correct command is, so I currently will not be submitting a pull request.

**Comment by gowthamkpr** [comment]
@DonaldM164 I am unable to reproduce the issue on my system. Please find the image below where I got the predictions back

![image](https://user-images.githubusercontent.com/47574994/65723342-11692b80-e063-11e9-9088-48d67f2876e7.png)

I have ran the same commands on the commandline. Please find it in the image below
![image](https://user-images.githubusercontent.com/47574994/65723442-44132400-e063-11e9-90f2-22fc37376400.png)


Let me explain you where you might be going wrong. I have named 3 steps in the code just to make sure I can reference steps easily.
```
# Step1: Download the TensorFlow Serving Docker image and repo
docker pull tensorflow/serving

git clone https://github.com/tensorflow/serving
# Step2: Location of demo models
TESTDATA="$(pwd)/serving/tensorflow_serving/servables/tensorflow/testdata"

#Step3:  Start TensorFlow Serving container and open the REST API port
docker run -t --rm -p 8501:8501 \
    -v "$TESTDATA/saved_model_half_plus_two_cpu:/models/half_plus_two" \
    -e MODEL_NAME=half_plus_two \
    tensorflow/serving &

# Query the model using the predict API
curl -d '{"instances": [1.0, 2.0, 5.0]}' \
    -X POST http://localhost:8501/v1/models/half_plus_two:predict

# Returns => { "predictions": [2.5, 3.0, 4.5] }
```

In step 3, 
`
/models/half_plus_two`  is looking to copy half_plus_two model from TESTDATA folder. If you dont set the TESTDATA right, i.e., if you don't run step2 that will cause the issue. So I suspect if you run step2 before step 3, this problem should be resolved.

**Comment by DonaldM164** [comment]
Thanks for the reply and detailed explanation gowthamkpr! I've repeated the commands just as you have and I'm still experiencing the same problem. Let me explain exactly what I did. 

Previously, I used the docker terminal to execute the steps but I started this attempt with an anaconda terminal, which performed fine until I attempted to set the TESTDATA location. "TESTDATA" is not a recognized internal command etc. etc. 

![setup](https://user-images.githubusercontent.com/16122798/65822503-356b6f00-e213-11e9-8a17-fb0b9a7ce65d.png)

However, the image was pulled and I cloned the repo. I went to my docker terminal and CD'd into the same directory where I issued the previous commands in the anaconda prompt. 

I then set the TESTDATA and ran the tensorflow-serving container. However, this is where the error occurs. 

![Attempt](https://user-images.githubusercontent.com/16122798/65822531-dd813800-e213-11e9-82b8-051898e66f5b.png)

**Comment by gowthamkpr** [comment]
@DonaldM164 Can you go to the path of the TESRDATA folder and let me know if the servable exists or no?

**Comment by DonaldM164** [comment]
@gowthamkpr The directory that TESTDATA is set to looks like this 
![serving](https://user-images.githubusercontent.com/16122798/65928208-f849dd00-e3ca-11e9-8f30-558e150d38b0.png)

The half_plus_two directory looks like this
![half_plus_two](https://user-images.githubusercontent.com/16122798/65928252-2a5b3f00-e3cb-11e9-99fb-98b16cc1398d.png)

**Comment by gowthamkpr** [comment]
@DonaldM164 Can you see a servable under TESTDATA/saved_model_half_plus_two_cpu path?

**Comment by DonaldM164** [comment]
@gowthamkpr Yes, within  TESTDATA/saved_model_half_plus_two_cpu is the version directory of 0000123, and within that directory is the save_model.pb.

**Comment by gowthamkpr** [comment]
@DonaldM164 Will try to reproduce this issue on windows and I will try to get back to you.

**Comment by DonaldM164** [comment]
@gowthamkpr Thanks, I'll let you know if I find a solution in the meantime!

**Comment by gowthamkpr** [comment]
@DonaldM164 Were you able to figure out the root cause of this error?

**Comment by DonaldM164** [comment]
@gowthamkpr No. I did suspect that it was perhaps because I created a soft link to my anaconda directory and my path depended on that, but if I repeat the process with the full path, I still receive the same error. Were you able to attempt the process on Windows 10?

**Comment by gowthamkpr** [comment]
Yes. I was but I was not able to reproduce the error.

**Comment by DonaldM164** [comment]
@gowthamkpr Can you tell me the system specs? Are you using HyperVisor to support docker?

**Comment by gowthamkpr** [comment]
No @DonaldM164 I am not using HyperVisor.

**Comment by gowthamkpr** [comment]
@DonaldM164 Is the issue still reproducing on windows?

**Comment by gowthamkpr** [comment]
I am closing this issue as it has been inactive for more than 14 days. Please add additional comments and we can open the issue again. Thanks!

**Comment by DavideCatto** [comment]
Same error for me. Followed the tutorial on Tensorflow Serving official page step by step and " No versions of servable" error showed. How to solve it?

I'm running Docker on Windows 10 and Git Bash for the cmd line

**Comment by Samvid95** [comment]
Same error here. I am also running docker on Windows 10 and cmd.
