### ISSUE TITLE
Build error with tf r1.15

### ISSUE THREAD

**Issue by Elizaaaaa** [tensorflow/serving#1453]
https://github.com/tensorflow/serving/blob/81ed5ef2307eea4c9396fd34f33673be072cdcf3/tensorflow_serving/apis/BUILD#L24

ERROR: /tensorflow_serving/tensorflow_serving/model_servers/BUILD:200:1: error loading package 'tensorflow_serving/apis': Label '@org_tensorflow//tensorflow/core:platform/default/build_config.bzl' crosses boundary of subpackage '@org_tensorflow//tensorflow/core/platform' (perhaps you meant to put the colon here: '@org_tensorflow//tensorflow/core/platform:default/build_config.bzl'?) and referenced by '//tensorflow_serving/model_servers:model_service_impl'

The tf r1.15 is having a separate BUILD for core/platform (https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/core/platform/BUILD).
However, the serving apis/BUILD is still point platform as a part of core, which caused error when i run bazel build. Will this be fixed any time? 

Thanks

**Comment by rmothukuru** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by Akrusher** [comment]
when build with tf r1.15 ,this is because your bazel version is too high, you can downgrade it to bazel 0.24, when i used bazel 0.26,  i face this problem too.

**Comment by Elizaaaaa** [comment]
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

my building command is:
`bazel build -c opt //tensorflow_serving/model_servers:tensorflow_model_server --verbose_failures`

and the error logs are:
ERROR: /home/ubuntu/serving/tensorflow_serving/model_servers/BUILD:215:1: error loading package 'tensorflow_serving/apis': Label '@org_tensorflow//tensorflow/core:platform/default/build_config.bzl' crosses boundary of subpackage '@org_tensorflow//tensorflow/core/platform' (perhaps you meant to put the colon here: '@org_tensorflow//tensorflow/core/platform:default/build_config.bzl'?) and referenced by '//tensorflow_serving/model_servers:prediction_service_impl'
ERROR: /home/ubuntu/serving/tensorflow_serving/model_servers/BUILD:215:1: error loading package 'tensorflow_serving/apis': Label '@org_tensorflow//tensorflow/core:platform/default/build_config.bzl' crosses boundary of subpackage '@org_tensorflow//tensorflow/core/platform' (perhaps you meant to put the colon here: '@org_tensorflow//tensorflow/core/platform:default/build_config.bzl'?) and referenced by '//tensorflow_serving/model_servers:prediction_service_impl'
ERROR: /home/ubuntu/serving/tensorflow_serving/model_servers/BUILD:215:1: error loading package 'tensorflow_serving/apis': Label '@org_tensorflow//tensorflow/core:platform/default/build_config.bzl' crosses boundary of subpackage '@org_tensorflow//tensorflow/core/platform' (perhaps you meant to put the colon here: '@org_tensorflow//tensorflow/core/platform:default/build_config.bzl'?) and referenced by '//tensorflow_serving/model_servers:prediction_service_impl'
ERROR: /home/ubuntu/serving/tensorflow_serving/model_servers/BUILD:215:1: error loading package 'tensorflow_serving/apis': Label '@org_tensorflow//tensorflow/core:platform/default/build_config.bzl' crosses boundary of subpackage '@org_tensorflow//tensorflow/core/platform' (perhaps you meant to put the colon here: '@org_tensorflow//tensorflow/core/platform:default/build_config.bzl'?) and referenced by '//tensorflow_serving/model_servers:prediction_service_impl'
ERROR: /home/ubuntu/serving/tensorflow_serving/model_servers/BUILD:215:1: error loading package 'tensorflow_serving/apis': Label '@org_tensorflow//tensorflow/core:platform/default/build_config.bzl' crosses boundary of subpackage '@org_tensorflow//tensorflow/core/platform' (perhaps you meant to put the colon here: '@org_tensorflow//tensorflow/core/platform:default/build_config.bzl'?) and referenced by '//tensorflow_serving/model_servers:prediction_service_impl'
ERROR: /home/ubuntu/serving/tensorflow_serving/model_servers/BUILD:215:1: error loading package 'tensorflow_serving/apis': Label '@org_tensorflow//tensorflow/core:platform/default/build_config.bzl' crosses boundary of subpackage '@org_tensorflow//tensorflow/core/platform' (perhaps you meant to put the colon here: '@org_tensorflow//tensorflow/core/platform:default/build_config.bzl'?) and referenced by '//tensorflow_serving/model_servers:prediction_service_impl'
ERROR: Analysis of target '//tensorflow_serving/model_servers:tensorflow_model_server' failed; build aborted: error loading package 'tensorflow_serving/apis': Label '@org_tensorflow//tensorflow/core:platform/default/build_config.bzl' crosses boundary of subpackage '@org_tensorflow//tensorflow/core/platform' (perhaps you meant to put the colon here: '@org_tensorflow//tensorflow/core/platform:default/build_config.bzl'?)

After modifying tensorflow_serving/api/BUILD from
`load("@org_tensorflow//tensorflow/core:platform/default/build_config.bzl", "tf_jspb_proto_library", "tf_pyclif_proto_library") `
to
 `load("@org_tensorflow//tensorflow/core/platform:default/build_config.bzl", "tf_jspb_proto_library", "tf_pyclif_proto_library") `
my bazel build works fine without error.

Thanks

**Comment by Elizaaaaa** [comment]
> when build with tf r1.15 ,this is because your bazel version is too high, you can downgrade it to bazel 0.24, when i used bazel 0.26, i face this problem too.

haven't thought about this. i'll have a try with it. thanks!

**Comment by rmothukuru** [comment]
@Elizaaaaa ,
Can you please confirm downgrading Bazel's version to 0.24 resolved your issue, as per @Akrusher's comments. Thanks!

**Comment by Akrusher** [comment]
yes，i success build r1. 15发自我的华为手机-------- 原始邮件 --------主题：Re: [tensorflow/serving] Build error with tf r1.15 (#1453)发件人：rmothukuru 收件人：tensorflow/serving 抄送：Akrusher <18813058598@163.com>,Mention @Elizaaaaa ,
Can you please confirm downgrading Bazel's version to 0.24 resolved your issue, as per @Akrusher's comments. Thanks!

**Comment by hygkim95** [comment]
@Elizaaaaa  Hi, I also tried changing lines in BUILD from "platform/default" to "platform:default".
Although the original error (the same one you got) did not appear anymore, different error
"serving/tensorflow_serving/session_bundle/oss/BUILD:1:1: Invalid label: invalid target name 'platform:default/build_config.bzl': target names may not contain ':'" appeared. Have you faced the same issue?

**Comment by Elizaaaaa** [comment]
> @Elizaaaaa Hi, I also tried changing lines in BUILD from "platform/default" to "platform:default".
> Although the original error (the same one you got) did not appear anymore, different error
> "serving/tensorflow_serving/session_bundle/oss/BUILD:1:1: Invalid label: invalid target name 'platform:default/build_config.bzl': target names may not contain ':'" appeared. Have you faced the same issue?

yeah i've seen this. try check which version of tensorflow your serving is using, and check that build_config.bzl from that version of tensorflow. you can find this info at https://github.com/tensorflow/serving/blob/8e514a36efbaccafa7d5551c6dc6c3b3b98a367a/WORKSPACE#L11
