### ISSUE TITLE
[Feature Request]Tensorflow serving version to support TF 2.0

### ISSUE THREAD

**Issue by chengnignzhang** [tensorflow/serving#1454]
Hey,
     We want to use tensorflow serving to serve TF 2.0, can we know when it's available ? or it's already available in the previous release.

**Comment by gowthamkpr** [comment]
@chengnignzhang We are till working on it and it should be released anytime soon. We are delaying the release as we are resolving a few bugs.

**Comment by unclepeddy** [comment]
I will note, you should be able to use TF Serving 1.X to serve TF 2.0 models - if you run into something that doesn't work please open an issue.

**Comment by chengnignzhang** [comment]
Thanks noted.
