### ISSUE TITLE
error :Building an optimized serving binary

### ISSUE THREAD

**Issue by ashwini-git** [tensorflow/serving#1458]
Hi, i am trying to optimize serving binary. Followed instructions over [https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/building_with_docker.md#building-an-optimized-serving-binary]()

the following command results in error - 
```
docker build --pull -t $USER/tensorflow-serving-devel-gpu \
  -f tensorflow_serving/tools/docker/Dockerfile.devel-gpu .
```
![error](https://user-images.githubusercontent.com/37379986/66590428-5edeb000-ebae-11e9-9bcc-7480ba3424e0.png)

I am trying to optimize the tensorflow/serving-gpu to improve response time for my object detection model. The response time is around 3 seconds for now with tensorflow/serving 1.12.3-gpu image.

please let me know how I can optimize the serving image as without it I am getting a poor response time.
Thanks

**Comment by ashwini-git** [comment]
@rmothukuru  Hi , can you help me with above issue ?

**Comment by vinuraja** [comment]
From reading the lines in the [image](https://user-images.githubusercontent.com/37379986/66590428-5edeb000-ebae-11e9-9bcc-7480ba3424e0.png) you posted, seems like it's a GCC compiler issue. It says:
```
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
```

**Comment by peter-mourfield** [comment]
I was experiencing the same issue. I was able to get this to work by increasing the amount of RAM that Docker Engine has allocated. I was using the defaults (2GB). Everything worked once I increased to 4GB
