### ISSUE TITLE
how to use tf-serving deploy the tflite?

### ISSUE THREAD

**Issue by leo-XUKANG** [tensorflow/serving#1459]
how to use it?please!!
`      tensorflow::Flag("use_tflite_model", &options.use_tflite_model,
                       "EXPERIMENTAL; CAN BE REMOVED ANYTIME! Load and use "
                       "TensorFlow Lite model from `model.tflite` file in "
                       "SavedModel directory instead of the TensorFlow model "
                       "from `saved_model.pb` file.")};

`

**Comment by gowthamkpr** [comment]
You can serve the saved model before converting it into TFLite model using Tensorflow serving.
Why do you want to use Tensorflow serving for Tf-Lite model?

**Comment by leo-XUKANG** [comment]
i was try to speed up my inference
@gowthamkpr

**Comment by leo-XUKANG** [comment]
No, i want to deploy in the cloud server

**Comment by leo-XUKANG** [comment]
@gowthamkpr  No, i want to deploy on the cloud server

**Comment by gowthamkpr** [comment]
@leo-XUKANG Can I see the full error message as the error message you posted is too vague for me to understand the issue. Thanks!

**Comment by leo-XUKANG** [comment]
I  fix the issue, just update the dockerfile

**Comment by gowthamkpr** [comment]
Glad that you were able to fix the issue. Closing this issue as it has been resolved.

**Comment by EthanPhan** [comment]
> I fix the issue, just update the dockerfile

Can I see how you use tf serving for TF-Lite model? I think I want to do the same thing with my model.

**Comment by harsh306** [comment]
Any documentation in this direction will be really helpful. I also want to use Tf-lite with TF-serving and deploy on cloud server. Thanks

**Comment by spate141** [comment]
@leo-XUKANG Can you please provide any details how you did that? I've got the `model.tflite` file and not sure how to convert it to use in tf-serving!

**Comment by ElPapi42** [comment]
@leo-XUKANG same here, share your implementation with us

**Comment by liuchangyu1988** [comment]
@leo-XUKANG same here. Could you please share your experience? Thanks

**Comment by michalbrys** [comment]
This could be helpful: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc#L191

**Comment by leo-XUKANG** [comment]
@liuchangyu1988  我直接打中文了啊，我之前寻求使用tensorflow/serving去部署tflite模型，是想可以极致的提升速度，后来我发现这种提升并没有实际的工程作用，因为将模型压缩成tflite格式，精度会大量损失，而且tensorflow官方宣称的速度提升数倍、精度不变，你看看就好，实际工程中别当真。有精力折腾这个还不如去玩TVM、去做模型压缩。结论：我已经放弃在tensorflow/serving上部署tflite模型，转而去开始极致的折腾我的模型，向着更小更强前进，其时tf/serving强在部署便捷稳定，你要是玩极限加速，可以试试nvidia tensorrt，这个优化是几乎没有精度损失的哦。或者你改写tf/serving的源码，将其中一些对你无用的部分剔除掉也行，假设你够强的话。兄弟！加油！

**Comment by liuchangyu1988** [comment]
好的好的，非常感谢。感觉你对tf serving这方面很有经验，有空多交流

**Comment by ElPapi42** [comment]
@leo-XUKANG you say that tflite has no benefits, but you just convert to tflite and no more?, or you apply the 8bit quantization?

**Comment by ethanyanjiali** [comment]
> @liuchangyu1988 我直接打中文了啊，我之前寻求使用tensorflow/serving去部署tflite模型，是想可以极致的提升速度，后来我发现这种提升并没有实际的工程作用，因为将模型压缩成tflite格式，精度会大量损失，而且tensorflow官方宣称的速度提升数倍、精度不变，你看看就好，实际工程中别当真。有精力折腾这个还不如去玩TVM、去做模型压缩。结论：我已经放弃在tensorflow/serving上部署tflite模型，转而去开始极致的折腾我的模型，向着更小更强前进，其时tf/serving强在部署便捷稳定，你要是玩极限加速，可以试试nvidia tensorrt，这个优化是几乎没有精度损失的哦。或者你改写tf/serving的源码，将其中一些对你无用的部分剔除掉也行，假设你够强的话。兄弟！加油！

感谢分享，请问精度大量损失是因为quantization吗？如果不做量子化仅仅是tflite的格式，性能和精度上会有变化吗？

**Comment by le8888e** [comment]
你好 @leo-XUKANG ，

请问tflite不做量化的话，用tf serving部署精度会有损失吗？性能可以提升多少？

谢谢～

**Comment by rujigochsh** [comment]
add param “ --prefer_tflite_model=true ”

**Comment by CHAIRLab** [comment]
tensorflow::Flag("prefer_tflite_model", &options.prefer_tflite_model,
                       "EXPERIMENTAL; CAN BE REMOVED ANYTIME! "
                       "Prefer TensorFlow Lite model from `model.tflite` file "
                       "in SavedModel directory, instead of the TensorFlow "
                       "model from `saved_model.pb` file. "
                       "If no TensorFlow Lite model found, fallback to "
                       "TensorFlow model."),

drwxr-xr-x 4 root root      4096 Sep  2 05:35 ./
drwxr-xr-x 4 root root      4096 Aug 27 06:15 ../
drwxr-xr-x 2 root root      4096 Aug 27 06:15 assets/
-rw-r--r-- 1 root root 131876432 Sep  2 05:35 *model.tflite*
-rw-r--r-- 1 root root  11728161 Sep  2 05:35 saved_model.pb
drwxr-xr-x 2 root root      4096 Sep  2 05:35 variables/
