### ISSUE TITLE
GPU-utils is so low  with tf_serving  !!!!!

### ISSUE THREAD

**Issue by leo-XUKANG** [tensorflow/serving#1460]
![image](https://user-images.githubusercontent.com/28701457/66701113-10a2eb80-ed2b-11e9-98ee-a40bc47c315d.png)

![image](https://user-images.githubusercontent.com/28701457/66701119-23b5bb80-ed2b-11e9-89e6-ae3c6e28bcf1.png)

some one can help me? how can make it better?

**Comment by rmothukuru** [comment]
@leo-XUKANG,
Can you please confirm if this issue is same as the issue, #1440. Thanks!

**Comment by rmothukuru** [comment]
@leo-XUKANG,
Can you please try to run the container with the parameters and check if there is improvement in GPU Utilization.

```
--grpc_channel_arguments=grpc.max_concurrent_streams=1000
--per_process_gpu_memory_fraction=0.7
--enable_batching=true
--batching_parameters_file=/models/flow2_batching.config
--tensorflow_session_parallelism=2 \ 
```

For more information, refer the issue, #1440. Thanks!

**Comment by leo-XUKANG** [comment]
@rmothukuru 
thanks to your reply

my model is so small which just use about 1711MB GPU memory, so i set 
`--per_process_gpu_memory_fraction=0.1`
but it works fine, and my GPU-Util  is 7%


if i use a big batch, it will use a lot of GPU-MEM,

**Comment by rmothukuru** [comment]
@leo-XUKANG,
Closing the issue as it has been resolved. Thanks!
