### ISSUE TITLE
Getting error following steps in 'Building Standard TensorFlow ModelServer'

### ISSUE THREAD

**Issue by peter-mourfield** [tensorflow/serving#1468]
## URL(s) with the issue:

https://www.tensorflow.org/tfx/serving/serving_advanced

## Description of issue (what needs changing):

When I attempt to execute  the 
```
tools/run_in_docker.sh python tensorflow_serving/example/mnist_saved_model.py \
  --training_iteration=100 --model_version=1 /tmp/mnist
```
step in the in the tutorial I get the this error:

```
serving % tools/run_in_docker.sh python tensorflow_serving/example/mnist_saved_model.py \
  --training_iteration=100 --model_version=1 /tmp/mnist
== Pulling docker image: tensorflow/serving:nightly-devel
nightly-devel: Pulling from tensorflow/serving
22e816666fd6: Already exists 
079b6d2a1e53: Already exists 
11048ebae908: Already exists 
c58094023a2e: Already exists 
e9d1145448f7: Pull complete 
3b2b266356de: Pull complete 
9f9b2b982b72: Pull complete 
ede8854b3a01: Pull complete 
7bb55a638df9: Pull complete 
bdd9b510b8a7: Pull complete 
90a5454f6928: Pull complete 
1941316fdbd3: Pull complete 
c9c9a434ee49: Pull complete 
Digest: sha256:3b52152115c73a6be79a86cda94c4c94569df9b490a3e40c2530d5a9a007afac
Status: Downloaded newer image for tensorflow/serving:nightly-devel
docker.io/tensorflow/serving:nightly-devel
== Running cmd: sh -c 'cd /Users/***REMOVED***/GitHub/serving; python tensorflow_serving/example/mnist_saved_model.py --training_iteration=100 --model_version=1 /tmp/mnist'
Traceback (most recent call last):
  File "tensorflow_serving/example/mnist_saved_model.py", line 39, in <module>
    tf.app.flags.DEFINE_integer('training_iteration', 1000,
AttributeError: 'module' object has no attribute 'app'
```
I am running this on Mac OS Catalina w/ 8GB RAM allocated to the Docker Engine.

**Comment by Nochange1001** [comment]
same error

**Comment by suenpun** [comment]
same error +1

**Comment by Nochange1001** [comment]
Would you please tell me the version of tensorflow ?

**Comment by suenpun** [comment]
tensorflow             1.8.0
tensorflow-serving-api 1.12.0

in python2.7

Nochange1001 <notifications@github.com> 于2019年10月22日周二 下午3:14写道：

**Comment by gowthamkpr** [comment]
@peter-mourfield What version of Tensorflow and Tensorflow serving are you using?

**Comment by peter-mourfield** [comment]
I'll double check when I get a chance in the next little bit, but it would be whatever is in tensorflow/serving:nightly-devel. Will report back soon.

**Comment by peter-mourfield** [comment]
Okay, here's what I've been able to figure out. The tensorflow/serving:nightly-devel image is hosting these versions:

`
root@39b1864f4246:/tensorflow-serving# pip list | grep tensorflow

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

tensorflow             2.0.0      
tensorflow-estimator   2.0.1      
tensorflow-serving-api 0.0.0      
`

So, suspecting that the sample referenced in the referenced article isn't TF2.0 ready I changed the command I'm running to include the 1.14.0-devel image which seems to work as long as I run everything in the context of 1.14.0-devel

`tools/run_in_docker.sh -d tensorflow/serving:1.14.0-devel python ./tensorflow_serving/example/mnist_saved_model.py --training_iteration=100 --model_version=1 /tmp/mnist`

I'll submit a PR to the documentation site to update the commands.

**Comment by gowthamkpr** [comment]
@peter-mourfield Can you please try TF Serving 2.0 and let me know if the issue still persists.

**Comment by dimitri320** [comment]
Same issue is with "Use TensorFlow Serving with Kubernetes"  (https://www.tensorflow.org/tfx/serving/serving_kubernetes) tutorial.

**Comment by peter-mourfield** [comment]
Check out #1486 instead of my PR

**Comment by unclepeddy** [comment]
Sorry for the delay - we've submitted a fix for this that will be merged as soon as some of our issues with the CI pipeline are resolved. Thanks for the patience.

**Comment by unclepeddy** [comment]
Should be resolved now.
