### ISSUE TITLE
Compilation Error on both MacOS and Red Hat

### ISSUE THREAD

**Issue by haonans** [tensorflow/serving#147]
ERROR: /home/haonans/.cache/bazel/_bazel_haonans/c4b92d0b49abc3b86029056d06434013/external/boringssl_git/BUILD:91:1: C++ compilation of rule '@boringssl_git//:crypto' failed: gcc failed: error executing command /home/y/bin64/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/home/y/bin64 -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 46 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.

**Comment by kirilg** [comment]
Sorry for the late response, is this still a problem? MacOS is not officially supported so we expect issues, but I think Red Hat should work (thought not explicitly tested by us). Could you try again with TensorFlow Serving @ head now?
