### ISSUE TITLE
 bazel build -c opt tensorflow_serving/...

### ISSUE THREAD

**Issue by linyia01** [tensorflow/serving#1473]
root@hw39:/tensorflow-serving# bazel build -c opt tensorflow_serving/...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: error loading package '': in /tensorflow-serving/tensorflow_serving/workspace.bzl: Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/269e4abc1127aa8eecfc6031bd96f7ececfa771e.tar.gz, https://github.com/tensorflow/tensorflow/archive/269e4abc1127aa8eecfc6031bd96f7ececfa771e.tar.gz] to /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/269e4abc1127aa8eecfc6031bd96f7ececfa771e.tar.gz: Premature EOF
ERROR: error loading package '': in /tensorflow-serving/tensorflow_serving/workspace.bzl: Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/269e4abc1127aa8eecfc6031bd96f7ececfa771e.tar.gz, https://github.com/tensorflow/tensorflow/archive/269e4abc1127aa8eecfc6031bd96f7ececfa771e.tar.gz] to /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/269e4abc1127aa8eecfc6031bd96f7ececfa771e.tar.gz: Premature EOF
INFO: Elapsed time: 256.028s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by wangwenchao-job** [comment]
这个似乎是网络的问题，请问您是如何解决的

**Comment by taozhijiang** [comment]
you can download the dependence source files manually, put it at somewhere on the hosts, and add the locations to the *.bzl start like file:///root/mirrors/xxx.tar.gz

**Comment by aswinskumar67** [comment]
Try using the Tensorflow devel image to build from the source.
