### ISSUE TITLE
Why my tf-serving prediction become slow when I add 3 extra new features？

### ISSUE THREAD

**Issue by TzeSing** [tensorflow/serving#1479]
As before we run the ctr's deepFM model online. It works well. 
The prediction time cost 10-20ms.

But we add some new features to upgrade our model. After training, generating model file, and deploying, we find the prediction time cost up to 500-600ms.
It means it can't work online. Too slow!!!

I hope someone who meat the same problem can give me some advices.
Thanks everyone!

Here is my tf and tf-serving version: Tensorflow-gpu==1.12.0; Tensorflow-serving-gpu also 1.12.0
My model file is generated by `tf.contrib.saved_model.save_keras_model`

**Comment by TzeSing** [comment]
the cost time means the time between the request and response

**Comment by gowthamkpr** [comment]
What version of Tensorflow and Tensorflow serving are you using. Also can you please provide the model that you are using for us to debug the problem. Thanks!

**Comment by TzeSing** [comment]
> What version of Tensorflow and Tensorflow serving are you using. Also can you please provide the model and the exact steps to reproduce this issue. Thanks!

thank you. I find the reason that it's of the high complexity of the model.
