### ISSUE TITLE
Import Pretrained .bin files in tensorflow serving

### ISSUE THREAD

**Issue by prathameshk** [tensorflow/serving#148]

**Comment by prathameshk** [comment]
I am trying to import pre trained models (.bin) files from https://code.google.com/archive/p/word2vec/    . But  I am not sure how to do this. The model exported from mnist_export.py looks much different than .bin file.  Is there a sample code or some document which explains this?

**Comment by kirilg** [comment]
The link you provided is from the original word2vec which predates TensorFlow, so I'm not familiar with the .bin file. You can look at this [TensorFlow tutorial](https://www.tensorflow.org/versions/r0.10/tutorials/word2vec/index.html) that describes the implementation in their repo, specifically [this file](https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/examples/tutorials/word2vec/word2vec_basic.py).

You would need to add exporting capabilities to that file as documented [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/session_bundle/README.md). For an example, take a look at how the [inception example](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_export.py#L26) does it.
