### ISSUE TITLE
Retrieve the latest "Available" model on the Model status API

### ISSUE THREAD

**Issue by tadam75** [tensorflow/serving#1488]
### Describe the problem the feature is intended to solve
We would like to use the model status API (by the http://host:port/v1/models/${MODEL_NAME} uri) to monitor the health of the TF Serving service. However, it seems that the JSON response list all the versions loaded by the service :

```
{
 "model_version_status": [
  {
   "version": "10",
   "state": "END",
   "status": {
    "error_code": "OK",
    "error_message": ""
   }
  },
  {
   "version": "9",
   "state": "AVAILABLE",
   "status": {
    "error_code": "OK",
    "error_message": ""
   }
  },
  {
   "version": "8",
   "state": "END",
   "status": {
    "error_code": "OK",
    "error_message": ""
   }
  },
 ...
 ]
}
```

And that's a problem, because for every new model this response will grow (except if there is a cleaning system or a maximum setting I don't know ?)

### Describe the solution
We would like to have a new endpoint http://host:port/v1/models/${MODEL_NAME}/latest-available which will respond a HTTP 200 with only this data :
```{
 "model_version_status": [
  {
   "version": "9",
   "state": "AVAILABLE",
   "status": {
    "error_code": "OK",
    "error_message": ""
   }
  }
```
And a HTTP 204 or an empty HTTP 200 if no model is available.

Maybe it could interest other people to have an endpoint http://host:port/v1/models/${MODEL_NAME}/latest (that retrieves the 10th model in the previous example) ?

**Comment by nrobeR** [comment]
Thanks for the FR. This is a reasonable feature request, yet it's not something on our roadmap yet. But contributions are welcome!

**Comment by singhniraj08** [comment]
@tadam75,

By default, [Model status API](https://www.tensorflow.org/tfx/serving/api_rest#model_status_api) returns status for all versions in the response. Alternatively, you can use [Model metadata API](https://www.tensorflow.org/tfx/serving/api_rest#model_metadata_api) to monitor the health of TF Serving API, which by default will returns the model metadata for the latest version in the response.

Let us know if this resolves your issue. Thank you!
