### ISSUE TITLE
Very large model size

### ISSUE THREAD

**Issue by chrisruk** [tensorflow/serving#149]
Hi,

I'm using serving, to save my CNN, which was created 
through Keras, the model, is saved and loaded fine.

But I'm wondering, is it normal for a model to be so large, e.g. >2GB?

I'm wondering if anyone has got any ideas why this might be the case, I'm
wondering if somehow the actual training data itself is being saved in the graph file?

cheers
Chris

**Comment by kirilg** [comment]
Without knowing more details about your model, it's hard to tell how big it's supposed to be. 2GB is not unreasonable and many complex models can be bigger than that. The exporter will only include the model graph def and variables, and will not include training data as part of the model. can you include the contents of `ls -l` of your export directory? What files are large?

**Comment by chrisruk** [comment]
Hi,

You can see my model generation code at:
https://github.com/chrisruk/models/blob/master/fam_generate.py#L150

(I'm using Keras as an abstraction over TensorFlow to create the model, and using TensorFlow serving directly, to save the model)

```
chris /tmp/fam/00000001 $  ls -lh
total 5.6G
-rw-r--r-- 1 chris chris  143 Aug 24 13:38 checkpoint
-rw-r--r-- 1 chris chris 1.6G Aug 24 13:38 export-00000-of-00001
-rw-r--r-- 1 chris chris 4.0G Aug 24 13:39 export.meta
```

Cheers
Chris

**Comment by kirilg** [comment]
export-00000-of-00001 contains the actual variables, and that's roughly in line with the 2G number you quoted earlier. You can try using the [inspect_checkpoint](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/inspect_checkpoint.py) tool to look into that file and get a sense for what tensors are the biggest (look at the dimensions in square brackets []) and see if anything is unexpectedly large. If everything seems reasonable, then it just means that your model is large and complex enough that 2G is expected.

To run the command from the TensorFlow Serving repo, run:
```
bazel build @org_tensorflow//tensorflow/python/tools:inspect_checkpoint
bazel-bin/external/org_tensorflow/tensorflow/python/tools/inspect_checkpoint --file_name=/tmp/fam/00000001/export-00000-of-00001
```
(or compile directly by cloning the TensorFlow repo).

If you observe unexpected Tensors in the export or they're unexpectedly large, you can check if there may be a bug in your configuration. If unsure, feel free to re-open the issue.

**Comment by chrisruk** [comment]
Thanks a lot for taking the time to help, it's much appreciated!

**Comment by nbajason** [comment]
Good to know that we're not too crazy, as we have 600M model running.
