### ISSUE TITLE
Tensorflow serving datatype issue i am using tensorboard as client

### ISSUE THREAD

**Issue by spraveen420** [tensorflow/serving#1495]
I am getting this error how to change data type:
raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.INVALID_ARGUMENT
details = "Expects arg[0] to be float but string is provided"
debug_error_string = "{"created":"@1574400948.336107855","description":"Error received from peer ipv6:[::1]:8500","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Expects arg[0] to be float but string is provided","grpc_status":3}

**Comment by gowthamkpr** [comment]
@spraveen420 Please take a look at these 2 issues [[1]](https://github.com/tensorflow/serving/issues/927) and [[2]](https://github.com/tensorflow/serving/issues/497) and it should help you in solving the problem. Thanks!

**Comment by spraveen420** [comment]
I changed as per u told still I'm getting same error like expecting float instead of string

**Comment by gowthamkpr** [comment]
Please provide a minimum reproducible code to reproduce your error @spraveen420

**Comment by spraveen420** [comment]
I used that code in tensorflow/serving GitHub code nothing extra code
docker version

**Comment by gowthamkpr** [comment]
Can you please provide a minimum reproducible code as it is not clear what you are referring to @spraveen420

**Comment by spraveen420** [comment]
I used docker tensorflow/serving with help of docker image in docker hub I
did docker run

Then for client I ran tensorboard cmd from cmdline not used any code

**Comment by gowthamkpr** [comment]
Why do you wanna run tensorboard after installing tensorflow serving? Can I understand the reasoning behind it @spraveen420 ?

**Comment by spraveen420** [comment]
I have my dataset in vm and tensorflow/serving(docker) serving my
classification model .The problem request is going but I am getting error
like input expected is float not string in GitHub of tensorflow/serving on
which file I should change to make it work

**Comment by gowthamkpr** [comment]
@spraveen420 I am sorry to say that I am unable to reproduce your error. Please provide exact steps and the files that you used with the code for me to reproduce the issue. Thanks!

**Comment by spraveen420** [comment]
Hi,
For serving the model i used docker version mentioned in this
https://github.com/tensorflow/serving
For UI to pass dataset as tfrecords and classes i ran tensorboard from
command prompt like this
https://www.datacamp.com/community/tutorials/tensorboard-tutorial
After i gave input while running i am getting this error Float is expected
instead of string
Used classification with 9 classes

**Comment by spraveen420** [comment]
Any update on this @gowthamkpr

**Comment by gowthamkpr** [comment]
I am not sure as to why you are running tensorboard as client @spraveen420. i would recommend you writing your own client file or follow this [question](https://stackoverflow.com/questions/56016549/tfrecords-tensorflow-serving-converting-tfrecords-into-grpc-or-restful-tens) to use tensorflow serving.

Just to be clear "Tensorboard is the interface used to visualize the graph and other tools to understand, debug, and optimize the model" and it cant be used during serving a model with Tensorflow serving. It can only be used while model building and to optimize it. Thanks!

**Comment by spraveen420** [comment]
No from the tensorboard UI I can able to upload dataset as tfrecord and labels file. It  is also reaching TensorFlow serving (Using docker) error coming from that TensorFlow serving I think there is some problem with that TensorFlow GitHub that it expects float instead of string check this link (https://stackoverflow.com/questions/54680499/tensorflow-serving-expects-arg0-to-be-float-but-string-is-provided) this guy told that he changed but I don't know-how

**Comment by spraveen420** [comment]
Any update on this @gowthamkpr

**Comment by gowthamkpr** [comment]
Are you using regress or classify signatures @spraveen420 ?

**Comment by spraveen420** [comment]
classify

**Comment by gowthamkpr** [comment]
@spraveen420 you have to set inputs dtype of signature to string to do classify/regress. Please go through this [comment](https://github.com/tensorflow/serving/issues/927#issuecomment-404248671) and let me know if it helps.

**Comment by spraveen420** [comment]
@gowthamkpr i tried those two but still not worked

**Comment by gowthamkpr** [comment]
@spraveen420  Unfortunately, we cannot reproduce your issue from our side and its not a bug too.

I would recommend you to post this issue on stackoverflow as there is a wider community to help. Thanks!
