### ISSUE TITLE
Behavior of TF_FORCE_GPU_ALLOW_GROWTH=true in tensorflow serving with multiple models (Saved model format)

### ISSUE THREAD

**Issue by shreyanair01** [tensorflow/serving#1496]
### Describe the problem the feature is intended to solve
I have a question about the TF_FORCE_GPU_ALLOW_GROWTH flag option with tensorflow serving.

I am able to run multiple models in a docker container with TF serving. In order to limit the GPU usage, I passed the TF_FORCE_GPU_ALLOW_GROWTH=true flag as an environment variable. So as the model server loads initially, it takes up some ~250 MiB , and after my first inference request, it expands to occupy around ~6.4 GB of GPU memory (out of 10GB total GPU mem). This is irrespective of whether one model was loaded or multiple were loaded.

My question is that

- how do we check the individual memory consumption of each model?
- Does the server load all models to GPU memory which is why the usage does not cross 6.4 GB limit?

### Describe the solution
Does tf serving have any functionality to unload models from GPU after the inferencing has been done? As in the memory usage reverts back to the amount needed to run the model server

### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow Serving installed from**: docker image
- **TensorFlow Serving version**: tensorflow/serving:1.12.0-gpu

**Comment by spraveen420** [comment]
I am getting this erroron how to change data type: tensorflow/serving/predict   [serving-default]
how can i change the datatype
raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.INVALID_ARGUMENT
details = "Expects arg[0] to be float but string is provided"
debug_error_string = "{"created":"@1574400948.336107855","description":"Error received from peer ipv6:[::1]:8500","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Expects arg[0] to be float but string is provided","grpc_status":3}

**Comment by gowthamkpr** [comment]
Can you please go through this [question](https://stackoverflow.com/questions/56012618/eager-load-the-entire-model-to-estimate-memory-consumption-of-tensorflow-serving)  which partially answers your question and let me know if it helps. Thanks!

**Comment by spraveen420** [comment]
I am getting an error like expecting float but we got string on /predict

**Comment by gowthamkpr** [comment]
@shreyanair01 Were you able to solve the issue?

**Comment by shreyanair01** [comment]
Hi @gowthamkpr ,
I tried the saved model warmup, while it improves my first inferencing request latency, it does not provide insight to the GPU usage by specific model. With regards to the second stackoverflow link, I tested loading multiple models on machines with different GPU capability. 

My question is that does tf serving internally restrict the amount of gpu growth when we use the TF_FORCE_GPU_ALLOW_GROWTH flag? When I load similar sized models (based on disk space used by savedmodel), the GPU does not extend beyond the usage of the largest model loaded. Does this mean that once GPU is allocated, inferencing a smaller model will not result in a memory increase?  That is to say that the GPU growth is not linear when using multiple models. Is there a way other than trial and error to see how many similar size models can be accommodated?

The observations are listed below:

**Models**
Resnet model 
- pulled from: curl -s https://storage.googleapis.com/download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz | tar --strip-components=2 -C /tmp/resnet -xvz)
Refer: [Medium tf serving tutorial](https://medium.com/tensorflow/serving-ml-quickly-with-tensorflow-serving-and-docker-7df7094aa008)
- On disk size: 99MB

Inception v3
 - Keras application model converted to savedmodel format
Refer: [tutorial](https://towardsdatascience.com/deploying-keras-models-using-tensorflow-serving-and-flask-508ba00f1037)
- on disk size: 92 MB


On EC2:
---
- Capability: 
  + GPU - 11441MiB [Tesla K80]
  + TF serving image, Cuda - tensorflow/serving:1.15.0-gpu,   CUDA 10.1

- Observations:
  Using nvidia-smi
  <table>
    <tr>
       <th>Experiment</th> 
       <th>GPU before 1st inference (MiB)</th> 
       <th>GPU after inference (MiB)</th> 
    </tr>
    <tr>
       <td>Only load resnet   model</td>
       <td>250</td>
       <td>7892</td>
    </tr>
    <tr>
       <td>Only load inception v3 model</td>
       <td>246</td>
       <td>4304</td>
    </tr>
    <tr>
       <td> Load inception v3 and Resnet model (sequential inference in order of inception, then resnet)</td>
       <td>376</td>
       <td>after inception - 4306 <br> after resnet - 8402</td>
    </tr>
    <tr>
       <td> Load inception v3 and Resnet model (sequential inference in order of resnet, then inception)</td>
       <td>374</td>
       <td>after resnet- 7888<br> after inception- 7888</td>
    </tr>
    <tr>
       <td> Load inception v3 and Resnet model (parallel inference request)</td>
       <td>374</td>
       <td>7892</td>
    </tr>
  </table>

On VM:
---
- Capability: 
  + GPU - 5059MiB [Quadro P2000]
  + TF serving image, Cuda - tensorflow/serving:1.14.0-gpu,   CUDA 10.1

- Observations:
  Using nvidia-smi
  <table>
    <tr>
       <th>Experiment</th> 
       <th>GPU before 1st inference (MiB)</th> 
       <th>GPU after inference (MiB)</th> 
    </tr>
    <tr>
       <td> Load inception v3 and Resnet model (sequential inference in order of inception, then resnet)</td>
       <td>399</td>
       <td>after inception - 3371 <br> after resnet - 3371</td>
    </tr>
    <tr>
       <td> Load inception v3 and Resnet model (sequential inference in order of resnet, then inception)</td>
       <td>393</td>
       <td>after resnet-3877 <br> after inception- 3877</td>
    </tr>
    <tr>
       <td> Load inception v3 and Resnet model (parallel inference request)</td>
       <td>393</td>
       <td>3877</td>
    </tr>
  </table>

Note: I also get the following response on my VM(Not on EC2):
 ```
2019-12-11 05:10:54.727985: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.25GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-12-11 05:10:54.736610: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.26GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available
```

**Comment by spraveen420** [comment]
Any update on this?

**Comment by shreyanair01** [comment]
@spraveen420  I got this explanation on reddit, doesn't completely help my usecase but fairly helpful

https://www.reddit.com/r/MachineLearning/comments/ea083i/d_tensorflow_gpu_memory_management_tf_force_gpu/

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved. Please add additional comments for us to reopen this issue again. Thanks!
