### ISSUE TITLE
tensorflow/serving return predicions=[[0,0,0,0,0,0,0,.....]]

### ISSUE THREAD

**Issue by ddingwang12** [tensorflow/serving#1498]
- **centos **:
- **TensorFlow Serving for docker image**:

### Describe the problem
the docker container of tensorflow/serving  with gpu (Multiple models),return the model preidicions is [0,0,0,0,....],restart docker container may Solve the problem ，but,Another model predictions is [0,0,0,0,....].

thanks

**Comment by gowthamkpr** [comment]
@ddingwang12 Can you please give the exact steps for us to reproduce the issue. Also please follow the template thats given [here](https://github.com/tensorflow/serving/issues/new) as it makes our life easy to understand and answer your questions faster. Thanks!

**Comment by gowthamkpr** [comment]
@ddingwang12 Were you able to solve this issue?

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 3 weeks. Please add additional comments and we can open the issue again. Thanks!
