### ISSUE TITLE
Bazel build with RuntimeError: module compiled against API version a but this version of numpy is 9'

### ISSUE THREAD

**Issue by fredwang222** [tensorflow/serving#15]
Hi,

 Environment is Mac, numpy installed with apt-get  command. What version of numpy does it require?

ERROR: /home/xxxx/tensorflow2/serving/tensorflow_serving/session_bundle/e     xample/BUILD:34:1: Executing genrule //tensorflow_serving/session_bundle/ex     ample:half_plus_two failed: bash failed: error executing command /bin/bash      -c ... (remaining 1 argument(s) skipped).
2546 RuntimeError: module compiled against API version a but this version of num     py is 9
2547 Traceback (most recent call last):
2548   File "/home/yhwang/.cache/bazel/_bazel_yhwang/85b1cab135cf9be23a6843da5c4     16dee/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/     export_half_plus_two.runfiles/tensorflow_serving/session_bundle/example/exp     ort_half_plus_two.py", line 31, in <module>
2549     import tensorflow as tf
2550   File "/home/yhwang/.cache/bazel/_bazel_yhwang/85b1cab135cf9be23a6843da5c4     16dee/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/     export_half_plus_two.runfiles/external/tf/tensorflow/__init__.py", line 23,      in <module>
2551     from tensorflow.python import *

**Comment by wjarek** [comment]
We don't support Mac build yet, unfortunately :( https://github.com/tensorflow/serving/issues/1

**Comment by wjarek** [comment]
Also, on Linux I did run into this once and was able to get around it by using `sudo pip install numpy==1.9`

**Comment by wjarek** [comment]
Btw, a quick way to get around Mac compilation issues is to compile under Docker: http://tensorflow.github.io/serving/docker

**Comment by kirilg** [comment]
Closing this issue as per Jarek's comments about us not supporting OS X yet. Docker should work though. Adding support for OS X is tracked in issue #1
