### ISSUE TITLE
Error with swig_import_helper and PyModule_Create2 when building tensorflow-serving with bazel

### ISSUE THREAD

**Issue by smk508** [tensorflow/serving#150]
I'm trying to install tensorflow-serving using bazel, and when I run

`bazel build tensorflow_serving/...`
to build the source tree, I get this error:

```
ERROR: /home/saad/.cache/bazel/_bazel_saad/e37842e738e0e762fe833f8c0caa8761/external/org_tensorflow/tensorflow/contrib/session_bundle/example/BUILD:38:1: Executing genrule @org_tensorflow//tensorflow/contrib/session_bundle/example:half_plus_two failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "/home/saad/.cache/bazel/_bazel_saad/e37842e738e0e762fe833f8c0caa8761/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/tf_serving/../org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.py", line 32, in <module>
    import tensorflow as tf
  File "/home/saad/.cache/bazel/_bazel_saad/e37842e738e0e762fe833f8c0caa8761/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/saad/.cache/bazel/_bazel_saad/e37842e738e0e762fe833f8c0caa8761/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/saad/.cache/bazel/_bazel_saad/e37842e738e0e762fe833f8c0caa8761/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/saad/.cache/bazel/_bazel_saad/e37842e738e0e762fe833f8c0caa8761/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /home/saad/.cache/bazel/_bazel_saad/e37842e738e0e762fe833f8c0caa8761/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyModule_Create2
```

What do I do?

I'm running python 3.5, gcc/g++ 4.9, CUDA 8.0, have swig installed, and am trying to build on Ubuntu Mate 16.04 with a GTX 1080.

Thanks!

**Comment by smk508** [comment]
If I build the subdirectories individually, I am able to build core,  resources, servables, sources, and test_util, albeit with a warning message:

`/home/saad/.cache/bazel/_bazel_saad/e37842e738e0e762fe833f8c0caa8761/external/boringssl_git/WORKSPACE:1: Workspace name in /home/saad/.cache/bazel/_bazel_saad/e37842e738e0e762fe833f8c0caa8761/external/boringssl_git/WORKSPACE (@boringssl) does not match the name given in the repository's definition (@boringssl_git); this will cause a build error in future versions.`

g3doc, example, and tools do not have build targets. Batching and servables give the error involving half_plus_two. 

When I run bazel test, the batching directory fails to build all tests. Core passes 19/19. Resources passes 2/2. Servables fails to build 0/4. Sources passes 2/2. util passes 11/11.

**Comment by kirilg** [comment]
Not sure, but I suspect this is a python 3 issue in TF serving, particularly about how it's configured in the bazel.rc file. Assuming you ran TensorFlow's ./configure script and configured with Python 3, could you try replacing the contents of [tools/bazel.rc](https://github.com/tensorflow/serving/blob/master/tools/bazel.rc) with the contents of `tensorflow/tools/bazel.rc` (auto-generated file, not bazel.rc.template), but keep the first two `build:cuda` lines unmodified.

**Comment by fabianschilling** [comment]
I replaced `tools/bazel.rc` with `tensorflow/tools/bazel.rc` as you suggested and I'm getting the following error:

    ERROR: /home/fabian/serving/tensorflow_serving/apis/BUILD:82:1: Converting to Python 3: tensorflow_serving/apis/prediction_service_pb2.py failed: 2to3 failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/python/2to3 --no-diffs --nobackups --write --output-dir bazel-out/local-py3-fastbuild/genfiles/python3/tensorflow_serving/apis --write-unchanged-files ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.

Python 3.5, CUDA 8.0, cuDNN 5.1.5, Ubuntu 16.04 LTS with a Tesla K40c.

Any ideas? Thanks in advance!

**Comment by wakahiu** [comment]
For starters, looks like tensorflow [does not support CUDA 8.0 yet.](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html)

**Comment by vtablan** [comment]
You need to add srcs_version="PY2AND3"  annotations to the sections of the BUILD files that correspond to the python files that you get errors for. See this issue: https://github.com/tensorflow/tensorflow/issues/791 for am example. I have succeeded in building tf-serving after adding quite a few of these annotations to the following files:
<pre>
tensorflow_serving/apis/BUILD
tensorflow_serving/example/BUILD
tensorflow_serving/model_servers/BUILD
tensorflow_serving/servables/tensorflow/testdata/BUILD
</pre>

BTW, tensorflow definitely supports CUDA 8.0 (current 0.11 binaries are built for that version by default).

**Comment by kirilg** [comment]
Old issue related to half_plus_two and python 3 are likely not relevant anymore since those targets were moved to a filegroup instead. Closing issue, please reopen if you encounter it at head.

**Comment by MichalLeonBorsuk** [comment]
Hi, 

Look here for a similar problem: https://www.riverbankcomputing.com/pipermail/pyqt/2014-July/034561.html
