### ISSUE TITLE
RuntimeError: build_tensor_info is not supported in Eager mode

### ISSUE THREAD

**Issue by majian** [tensorflow/serving#1501]
When I want to save model used for docker tf serving, accur this error!
The code:
model_input = tf.compat.v1.saved_model.utils.build_tensor_info(model.input)
model_output = tf.compat.v1.saved_model.utils.build_tensor_info(model.output)
Error:
RuntimeError: build_tensor_info is not supported in Eager mode.
My tensorflow is version 2.0.

**Comment by gowthamkpr** [comment]
What version of Tensorflow serving are you using? Can you please fill the template [here](https://github.com/tensorflow/serving/issues/new) as the current information is too vague for us to understand the issue. Thanks!

**Comment by majian** [comment]
> What version of Tensorflow serving are you using? Can you please fill the template [here](https://github.com/tensorflow/serving/issues/new) as the current information is too vague for us to understand the issue. Thanks!

The Tensorflow serving's version is 2.0.0. My full code:
`
import tensorflow as tf
import os


def save_model_for_production(model, version, path='prod_models'):
    tf.keras.backend.set_learning_phase(1)
    if not os.path.exists(path):
        os.mkdir(path)
    export_path = os.path.join(
        tf.compat.as_bytes(path),
        tf.compat.as_bytes(version))
    builder = tf.compat.v1.saved_model.builder.SavedModelBuilder(export_path)

    model_input = tf.compat.v1.saved_model.utils.build_tensor_info(model.input)
    model_output = tf.compat.v1.saved_model.utils.build_tensor_info(model.output)

    prediction_signature = (
        tf.compat.v1.saved_model.signature_def_utils.build_signature_def(
            inputs={'inputs': model_input},
            outputs={'output': model_output},
            method_name=tf.compat.v1.saved_model.signature_constants.PREDICT_METHOD_NAME))

    with tf.keras.backend.get_session() as sess:
        builder.add_meta_graph_and_variables(
            sess=sess, tags=[tf.saved_model.tag_constants.SERVING],
            signature_def_map={
                'predict':
                    prediction_signature,
            })

        builder.save()
        
        
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
mnist_model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])
mnist_model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
mnist_model.fit(x_train, y_train, epochs=10)
mnist_model.evaluate(x_test,  y_test, verbose=2)
save_model_for_production(mnist_model, "1.0", "../model/mnist")

`

**Comment by gowthamkpr** [comment]
This does not belong to Tensorflow serving. Please post this issue in [tensorflow/tensorflow](https://github.com/tensorflow/tensorflow/issues) as this issue is a tensorflow issue
