### ISSUE TITLE
SSL/TLS for HTTP endpoint

### ISSUE THREAD

**Issue by davcamer** [tensorflow/serving#1503]
### The Problem

I am excited that Tensorflow Serving comes with Prometheus metrics built-in! I have set up a Dockerfile that builds off of `tensorflow/serving:2.0.0`, importing my model and configuration and starting the server with my config. Everything works, including gRPC secured with TLS. 😄 However, the Prometheus metrics are served through the `rest_api_port`, which is not secured with any encryption. I work on a security conscious team, so I'd like to also have TLS on this port. 

### The Solution
I'd like the REST API port to serve HTTPS when there is a valid `ssl_config_file`. It should use the same certificate that is being used by the gRPC port.

### The Alternatives
* Maybe it would be ok if only the metrics were on this port, but I can't figure out a configuration to serve metrics over the REST API port without also serving models over the port. I'd prefer the metrics to be TLS encrypted anyway.
* A second separate config file would be possible, but doesn't add value for me.
* Popping an nginx in the same container to sit in front of the serving component is possible. This seems like the long way around, when there is already a cert right there for the gRPC port. (I haven't looked at the code. I suspect I may regret "right there.")

### Additional context
I have a company hack day coming up, where I would like to take a crack at a PR for this feature. I'll clear the CLA if this feature makes sense, and I haven't overlooked some way in which https:// for the REST API port is already supported.

**Comment by davcamer** [comment]
I originally, optimistically thought that maybe https support wasn't included because no one had faced a significant need for it yet. I hoped it would be a straightforward task of wiring some existing, and hopefully already included, libraries together.

The [http serving component] of TensorFlow Serving is built on the [libevent] library. Libevent doesn't include an https component, although it does include an example of how to set up an [https client]. One of the top search results for "libevent https server" leads to an [https-example] project, originally from 2013, with the upfront explanation:
> If you're looking for an https server using libevent and OpenSSL, I don't know of one to recommend. You might want to try asking on the libevent mailing list.
As the author points out, he originally shared the project only to discuss problems with the approach on the libevent mailing list.

A site specific search, `site:archives.seul.org/libevent/ https server`, doesn't turn up much discussion more recent than 2016.

There is [libevhtp], which is an alternative to the http components that ship with libevent. Their examples suggest they [support https] out of the box. But the current http support would need to be changed over. Otherwise, there would be two parallel http implementations.

For my immediate needs, I'll be putting something in front of TensorFlow serving to provide TLS termination. I'm still interested if you find an approach to move this forward. 

[http serving component]: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/util/net_http/server/internal/evhttp_server.cc
[libevent]: https://libevent.org/
[https client]: https://github.com/libevent/libevent/blob/master/sample/https-client.c
[https-example]: https://github.com/ppelleti/https-example
[libevhtp]: https://github.com/criticalstack/libevhtp
[support https]: https://github.com/libevent/libevent/blob/master/sample/https-client.c

**Comment by unclepeddy** [comment]
Thanks for taking a look!
Unfortunately swapping out the http server implementation to use a different library is likely not something we'll be looking into since unless we hear an overwhelming # of requests for it. I'll keep this open so others could +1 it if appropriate.

**Comment by singhniraj08** [comment]
@davcamer,

Are you still looking for a resolution? We are planning on prioritising the issues based on the community interests. Please let us know if this issue still persists with the latest TF Serving 2.12.1 release so that we can work on fixing it. Thank you for your contributions.

**Comment by davcamer** [comment]
Hi. For reasons unrelated to this, I stopped using TF Serving later in January 2020, switching back to a more "pure Python" implementation with scikit-learn. I've moved on to LightGBM since then, but still am not using TF Serving. So, I'm not sure if the problem is the same in further versions.

**Comment by singhniraj08** [comment]
@davcamer,

Could you please close this issue, if this feature request is irrelevant to you. Also, swapping out the http server implementation to use a different library is not in our roadmap right now. Thank you.
