### ISSUE TITLE
tensorflow serving gpu only one thread is busy

### ISSUE THREAD

**Issue by gao8954** [tensorflow/serving#1505]
![image](https://user-images.githubusercontent.com/7404433/70297768-4693b600-182a-11ea-8f11-aa2fe87c274e.png)
tensorflow serving gpu only one thread is busy,and the gpu usage is very low even though set the --enable_batching=true and set max_batch_size 
![image](https://user-images.githubusercontent.com/7404433/70297922-d76a9180-182a-11ea-91ec-3d321feef645.png)
there is some bug?
and the serving version is 1.13.1

**Comment by gowthamkpr** [comment]
Can you please use the latest TF-serving version and let me know if the issue still persists. Also if the issue persists, please provide some reproducible code for us to reproduce the issue preferable on google colab. Thanks!

**Comment by gowthamkpr** [comment]
@gao8954 Did you resolve the issue?

**Comment by gao8954** [comment]
@gowthamkpr not work, the issue is still not resolved, it even in cpu is faster than gpu

**Comment by rmothukuru** [comment]
@gao8954,
Can you try the solution mentioned in [this link](https://github.com/tensorflow/serving/issues/1440#issuecomment-541578798)  and confirm if the issue still persists. Thanks!

**Comment by rmothukuru** [comment]
@gao8954,
Can you please confirm if the above comment has resolved your issue. Thanks!

**Comment by thepycoder** [comment]
@rmothukuru I'm having the exact same problem

I'm using the latest tensorflow serving gpu docker image to serve a model from the object detection model zoo that has been rebuilt to accept base64 images. I send non-parallel requests via HTTP.

Nvidia-smi confirms that the tf-serving binary is using the GPU memory, and with each request the GPU usage goes up and vanishes again quickly and only to about 10-30%. But after that, only a single CPU thread is 100% used for 2 seconds or so and then the request is fulfilled.

I ran the exact same docker image and model but on Google Cloud Kubernetes engine and got 0.4-0.5 seconds of inference time, on my server it's more than 3 seconds after warmup of 9 seconds.

The server has the following specs: 24 cores, 48 threads, V100 GPU, 200GB RAM, Ubuntu 18.04, have tried nvidia driver ranging from 410 to 440 and almost everything in between.

I've been losing my mind over this, it would be awesome if you could help!

**Comment by rmothukuru** [comment]
@thepycoder,
Can you try the solution mentioned in this [link](https://github.com/tensorflow/serving/issues/1440#issuecomment-541578798) and confirm if the issue still persists. Thanks!

**Comment by thepycoder** [comment]
@rmothukuru I passed the parameters, but no dice. It even became slower.

**Comment by gowthamkpr** [comment]
@gao8954 @thepycoder Can you give us the exact steps (with configuration) to reproduce the issue. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as this has been inactive for more than a 3 weeks. Please add additional comments and we can open the issue again. Thanks!
