### ISSUE TITLE
logging / logrotate from tensorflow serving binary

### ISSUE THREAD

**Issue by nishantd** [tensorflow/serving#151]
Hi,

Any tips on how to set up logging / logrotation when running tensorflow serving?

Ideally i'd like to give the process a logfile to log to (env var or cmd line), and then send a signal to reopen the logfile when i logrotate it. But any other ideas will work too - just need to be able to logrotate the logs.

Right now for me they just get written to stderr, which is hard to rotate nicely.

Thanks

(Also not sure if this is the right forum for this since this is not a bug...- please point me to the right place if this is not the right place).

**Comment by nishantd** [comment]
\cc @kirilg @chrisolston

**Comment by kirilg** [comment]
All TensorFlow logging code eventually calls [LogMessage::GenerateLogMessage](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/default/logging.cc#L76) which currently writes to stderr. You could perhaps locally modify that code, or run the server as usual and redirect (or tee) the output to a file + logrotate.

Perhaps the [discussion here](http://superuser.com/questions/291368/log-rotation-of-stdout) will be useful (e.g. see the multilog command example)

**Comment by nishantd** [comment]
That is useful - thanks.
