### ISSUE TITLE
Classification signature on tf serving.

### ISSUE THREAD

**Issue by stefanondisponibile** [tensorflow/serving#1512]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): `no`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Ubuntu 18.04`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: `no`
- TensorFlow installed from (source or binary): `no`
- TensorFlow version (use command below): `2.0.0`
- Python version: `3.7.3`
- Bazel version (if compiling from source): `-`
- GCC/Compiler version (if compiling from source): `-`
- CUDA/cuDNN version: `-`
- GPU model and memory: `-`

**Describe the current behavior**

It seem currently *not* possible to export a `classify` signature to use within `Tensorflow Serving`.

**Describe the expected behavior**
It should be possible to export a `classify` signature to use within `Tensorflow Serving`.
I was able to experience the issue also by exporting directly a `tf.Module` and a subclassed `tf.Model`. In [this](https://github.com/tensorflow/serving/issues/1420#issuecomment-552475340) comment I was also wondering about both the `inference` and `classify` signatures being *deprecated* since it looks like in [_generate_signatures](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/save.py#L466) the `method_name` is assigned to `signature_constants.PREDICT_METHOD_NAME`.

**Code to reproduce the issue**
```python
import tensorflow as tf
import numpy as np

model = tf.keras.Sequential([
    tf.keras.layers.Dense(2, activation="softmax"),
])
model.compile(optimizer="Adam", loss="categorical_crossentropy", metrics=["accuracy"])
X = [0.42]
Y = [[0, 1]]
model.fit(X, Y, epochs=1)
pred_before = model.predict(X)
print(f"*** pred : {pred_before} ***")
model.save("./mymodel/1", save_format="tf")
model = tf.keras.models.load_model("./mymodel/1")
model.predict([X])
print(f"*** signatures : {model.signatures} ***")
pred_after = model([X])
np.testing.assert_almost_equal(pred_before, pred_after)
print(model.predict([X]))
```

```bash
docker run -p 8501:8501 -v /path/to/mymodel:/models/mymodel -e MODEL_NAME=mymodel --name serving_tmp tensorflow/serving
```

```
curl -XPOST http://localhost:8501/v1/models/mymodel:classify -d '{"examples": [{}]}'
# { "error": "Expected classification signature method_name to be tensorflow/serving/classify. Was: tensorflow/serving/predict" }
```

**Other info / logs**
```
{ "error": "Expected classification signature method_name to be tensorflow/serving/classify. Was: tensorflow/serving/predict" }
```

If I modify `tensorflow_core/python/saved_model/save.py@469`
```python
# from
method_name=signature_constants.PREDICT_METHOD_NAME)

# to
method_name=signature_constants.CLASSIFY_METHOD_NAME)
``` 

I'm then able to get what expected:
```
curl -XPOST http://localhost:8501/v1/models/mymodel:classify -d '{"examples": [{}]}'
{ "error": "No classification inputs found in SignatureDef: inputs {\n  key: \"text\"\n  value {\n    name: \"serving_default_text:0\"\n    dtype: DT_FLOAT\n    tensor_shape {\n      dim {\n        size: -1\n      }\n      dim {\n        size: -1\n      }\n    }\n  }\n}\noutputs {\n  key: \"probabilities\"\n  value {\n    name: \"StatefulPartitionedCall_2:0\"\n    dtype: DT_FLOAT\n    tensor_shape {\n      dim {\n        size: -1\n      }\n      dim {\n        size: 99\n      }\n    }\n  }\n}\nmethod_name: \"tensorflow/serving/classify\"\n" }
```

I originally reported [this same issue on the `tensorflow` repository](https://github.com/tensorflow/tensorflow/issues/34968), but [I was told to signal it here](https://github.com/tensorflow/tensorflow/issues/34968#issuecomment-564480493) since it looks like the problem could be related to Tensorflow Serving.

**Comment by gowthamkpr** [comment]
@stefanondisponibile The default signature is predict but you can define your own signature including classify[ here](https://www.tensorflow.org/api_docs/python/tf/saved_model/save). Also we can continue the discussion in tensorflow/tensorflow repo as this issue belongs there. I am gonna close this thread.
