### ISSUE TITLE
Tensorflow Kubernetes tutorial not returning class names

### ISSUE THREAD

**Issue by andreesteva** [tensorflow/serving#152]
I am working my way through this tutorial: https://tensorflow.github.io/serving/serving_inception.html 

And everything works as expected until the very last step, where I query the cloud model from my local machine. The cloud model returns the class scores, but not the class names.

Anyone have any idea what could be happening?

**Comment by chrisolston** [comment]
One possibility is that (somehow) the "classes" tensor in the classification signature is being omitted. AFAIK omitting that tensor would cause the behavior you are seeing.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/session_bundle/manifest.proto#L59

Can you verify that it's being populated. If not, then the question is why not...

**Comment by andreesteva** [comment]
Is there some way to verify if thats the case for the cloud-based docker image?

Note: the classes and properly returned if I run things locally. If run in the cloud, it returns the correct class scores, just without the class names:

docker run -it $USER/inception_serving
cd serving
bazel-bin/tensorflow_serving/example/inception_inference --port=9000 inception-export &> inception_log &
bazel-bin/tensorflow_serving/example/inception_client --server=localhost:9000 --image=cat.jpg

Output:

scores: 8.39175319672
scores: 7.4077091217
scores: 6.79704475403
scores: 5.10931873322
scores: 4.38220119476
classes: "tiger cat"
classes: "Egyptian cat"
classes: "tabby, tabby cat"
classes: "Pembroke, Pembroke Welsh corgi"
classes: "red fox, Vulpes vulpes"

E0809 21:51:36.737833968      45 chttp2_transport.c:1810]    close_transport: {"created":"@1470779496.737802214","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427}


However, once the model is deployed in the cloud:

bazel-bin/tensorflow_serving/example/inception_client --server=104.198.5.4:9000 --image=/home/esteva/Downloads/cat.jpg
D0809 14:50:04.190523684   15944 ev_posix.c:101]             Using polling engine: poll
scores: 8.39175224304
scores: 7.40771055222
scores: 6.79704284668
scores: 5.10931825638
scores: 4.38220310211

E0809 14:50:06.716963201   15944 chttp2_transport.c:1810]    close_transport: {"created":"@1470779406.716912003","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427}

**Comment by fangweili** [comment]
I can't reproduce it locally. Is your image publicly accessible?

Thanks,
/Fangwei

**Comment by andreesteva** [comment]
Locally the image works. Its when pinged in the cloud that it does not.

Here is the image I'm using:
gcr.io/esteva-public/inception-noclassnames

**Comment by promiseofcake** [comment]
What is the output of `inception_log`, there might be something of use in there.
