### ISSUE TITLE
[Feature Request] AMD ROCm suppoert

### ISSUE THREAD

**Issue by nlnjnj** [tensorflow/serving#1520]
### Describe the problem the feature is intended to solve
Recently I did a performance test on the AMD Radeon 7 Graphics Card,
using resnet-50 model with batch size 64, while the performance result is close to Nvidia 2080Ti,
so could this test make this feature request more realistic?

![FB401C5B-5E5A-42fc-8363-27A9FED50ABC](https://user-images.githubusercontent.com/5831940/71149329-34256d80-2269-11ea-83e0-38aad28aeb58.png)
![280A0F3E-F805-4d53-B39C-2181D330DF1C](https://user-images.githubusercontent.com/5831940/71149475-a0a06c80-2269-11ea-9329-b886cf766315.png)

**Comment by rmothukuru** [comment]
@nlnjnj, 
Can you please elaborate about your feature request. Thanks!

**Comment by nlnjnj** [comment]
> elaborate
I hope we could add hardware support for amd gpu aka rocm,

this means we need add support for the unofficial tensorflow-rocm in build steps.
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream

after that we need add some new Dockerfiles for this hardware, like Dockerfile.devel-rocm Dockerfile.rocm.
https://github.com/tensorflow/serving/tree/master/tensorflow_serving/tools/docker

**Comment by unclepeddy** [comment]
If this is officially supported by TensorFlow then we may consider it but as far as I know TF does not support ROCm and so TF Serving cannot either.

**Comment by Arnold1** [comment]
@misterpeddy can I run TensorFlow Serving on the following gpu?
```
Radeon Pro 560X:

  Chipset Model:	Radeon Pro 560X
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	4 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x67ef
  Revision ID:	0x00c2
  ROM Revision:	113-C980AL-075
  VBIOS Version:	113-C97501U-005
  EFI Driver Version:	01.01.075
  Automatic Graphics Switching:	Supported
  gMux Version:	5.0.0
  Metal:	Supported, feature set macOS GPUFamily2 v1
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2880 x 1800 Retina
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
```
