### ISSUE TITLE
enable batching only for one model 

### ISSUE THREAD

**Issue by hbellafkir** [tensorflow/serving#1522]
### Describe the problem the feature is intended to solve
I'm serving multiple models. one of them takes requests with images different size, so I need to disable batching only for that model.

### Describe the solution
configure models file, so that enabling or disabling batching is allowed

**Comment by Stonesjtu** [comment]
Setting `max_batch_size = 1` should work in this case.

**Comment by hbellafkir** [comment]
@Stonesjtu  you cannot set max_batch_size for specific model.

**Comment by Stonesjtu** [comment]
You can set different `platforms` for the models with different `max_batch_size`

**Comment by hbellafkir** [comment]
thnx for the response @Stonesjtu. I didn't get what you mean, but I founded here #836.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved. If you have any more questions please post it in stackoverflow as github is only meant for bug/performance, build/install, feature reqest or docs related issues. Thanks!
