### ISSUE TITLE
tf-serving generate warmup request 

### ISSUE THREAD

**Issue by liaocz** [tensorflow/serving#1528]
some tensorflow model is trained using tf.placeholder and some by tf.esitimator API, there are some difference between this two method when creating warmup data for tf-serving model
- if model is trained using tf.placeholder, we can know all input tensor name and shape from savedModel by executing the command, `saved_model_cli show`, so we can make up data according to input tensor name and shape to generate tf_serving_warmup_requests
- if model is trained using tf.estimator, we can't obtain any information about input tensor in detail, the model's input is format of Example or SequenceExample, so how can we create tf_serving_warmup_requests file just using model without any other input?
Thank you!

**Comment by gowthamkpr** [comment]
You can obtain the information of the tensorflow estimator saved model. You can use Saved_model_cli for saved estimator model as shown [here](https://stackoverflow.com/questions/51212160/how-to-do-a-simple-cli-query-for-a-saved-estimator-model).

**Comment by gowthamkpr** [comment]
@liaocz Did you solve the issue?

**Comment by liaocz** [comment]
We can use 'Saved_model_cli' to show the model's input and output, but we can't make up the data according to the information from 'Saved_model_cli', so how can we generate warmup request as same as the as the 'tf.placehloder'

**Comment by christisg** [comment]
Hi @liaocz,
The warmup data needs to be representative of the actual inference requests sent to the model at serving time.
It should be possible to collect a few example requests (they should already be in PredictionLog format) and use them as the warmup data.
If collecting actual inference requests is hard, you may consider collecting a few examples from the test or eval set and write a script to translate them into PredictionLog format.
More details and example code snippet can be found at www.tensorflow.org/tfx/serving/saved_model_warmup.

**Comment by liaocz** [comment]
ok, thank you very much~ @christisg

**Comment by christisg** [comment]
Let us know if any follow-up is needed, or whether the issue can be closed.
Thanks and good luck!

**Comment by liaocz** [comment]
I have collected a few examples from the testl set and write a script to translate them into PredictionLog format. so this issue can be closed, thany you again~

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved. Thanks!
