### ISSUE TITLE
Grpc Transport closed error

### ISSUE THREAD

**Issue by upwindflys** [tensorflow/serving#1536]
Example
https://tensorflow.google.cn/tfx/serving/serving_basic
run 
tools/run_in_docker.sh python tensorflow_serving/example/mnist_client.py \
  --num_tests=1000 --server=127.0.0.1:8501 
get the following error? 
<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Transport closed"
	debug_error_string = "{"created":"@1579416411.591710831","description":"Error received from peer ipv4:127.0.0.1:8501","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Transport closed","grpc_status":14}"
>
<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Transport closed"
	debug_error_string = "{"created":"@1579416411.592995987","description":"Error received from peer ipv4:127.0.0.1:8501","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Transport closed","grpc_status":14}"
>
<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Transport closed"
	debug_error_string = "{"created":"@1579416411.594129868","description":"Error received from peer ipv4:127.0.0.1:8501","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Transport closed","grpc_status":14}"
>

Inference error rate: 100.0%

**Comment by jusonn** [comment]
Did you run tf serving server with 
```
docker run -p 8500:8500 \
--mount type=bind,source=/tmp/mnist,target=/models/mnist \
-e MODEL_NAME=mnist -t tensorflow/serving &
```
Would you check serving server log

**Comment by gowthamkpr** [comment]
@upwindflys Can you please reply to jusonn's comment. Thanks!

**Comment by gowthamkpr** [comment]
@upwindflys The error is because that the grpc port is 8500 and the restFul API port is 8501
Please change the port in the client script to 8500 as you are using grpc. 

For more info you can refer to the comment [here](https://github.com/tensorflow/serving/issues/1149). Thanks!

**Comment by gowthamkpr** [comment]
@upwindflys Did the above comment help you? Can I close this issue?
