### ISSUE TITLE
Padding Error when Predicting Multiple Instances using TensorFlow Serving

### ISSUE THREAD

**Issue by ericmclachlan** [tensorflow/serving#1538]
### Description
When posting a request to the Model Server's predict endpoint, I receive the following response:

```json
{ "error": "Failed to process element: 1 of 'instances' list. Error: Invalid argument: Expecting tensor size: 270 but got: 252" }
```

This happens when my payload contains 2 instances. The first is a list of integers with length 270. The second is a list of integers with length 252.

If only 1 instance is provided, there is no problem.

### Solution
I have `pad_variable_length_inputs: true` set in my batching parameters file; so my expectation would be that the padding would be performed on the Model Server.

### Alternatives
- I _could_ send through one instance at a time and trust that TS will batch the input in mini-batches but it just seems inefficient to send a REST request for every instance.
- Considering that jagged tensors are now available, it seems inevitable that the requirement for fixed-length batches would need to change.

**Comment by gowthamkpr** [comment]
Can I see your batching config? Also can I know what version of Tensorflow and Tensorflow serving are you using?

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for close to 3 weeks. Please add additional comments and we can open the issue again. Thanks!

**Comment by BorisPolonsky** [comment]
I would like to request this feature as well. I tested with the following image
- tensorflow/serving:1.12.3-gpu
- tensorflow/serving:2.0.0-gpu
with args: `--model_config_file=/etc/tensorflow-serving/config --enable_batching=true --batching_parameters_file /etc/tensorflow-serving/batching_config`
Both of them fails when I post batch of sequences of variable length, e.g. 
```
'{"signature_name": "predict", "instances": [
    {
        "input_ids": [58, 179, 863, 87, 1680, 16],
        "sequence_length": 6}, 
    {
         "input_ids": [1784, 1784, 1784, 3905, 1784, 1784, 1784, 1784, 3905, 1784, 1784, 1784, 3905, 1784, 1784, 1784, 1784, 1784, 1784],
        "sequence_length": 19}
]}'
```
In Addition, the metadata of my model looks like this
```
{"signature_def": {
 "signature_def": {
  "predict": {
   "inputs": {
    "sequence_length": {
     "dtype": "DT_INT32",
     "tensor_shape": {
      "dim": [
       {
        "size": "-1",
        "name": ""
       }
      ],
      "unknown_rank": false
     },
     "name": "sequence_lengths:0"
    },
    "input_ids": {
     "dtype": "DT_INT32",
     "tensor_shape": {
      "dim": [
       {
        "size": "-1",
        "name": ""
       },
       {
        "size": "-1",
        "name": ""
       }
      ],
      "unknown_rank": false
     },
     "name": "word_ids:0"
    }
   },
   "outputs": {
    "labels_ids": {
     "dtype": "DT_INT32",
     "tensor_shape": {
      "dim": [
       {
        "size": "-1",
        "name": ""
       },
       {
        "size": "-1",
        "name": ""
       }
      ],
      "unknown_rank": false
     },
     "name": "cond/Merge:0"
    },
    "labels": {
     "dtype": "DT_STRING",
     "tensor_shape": {
      "dim": [
       {
        "size": "-1",
        "name": ""
       },
       {
        "size": "-1",
        "name": ""
       }
      ],
      "unknown_rank": false
     },
     "name": "index_to_string_Lookup:0"
    }
   },
   "method_name": "tensorflow/serving/predict"
  }
 }
}
}
```
and the `batching_config` looks like this
```
max_batch_size { value: 128 }
batch_timeout_micros { value: 0 }
max_enqueued_batches { value: 1000000 }
num_batch_threads { value: 8 }
pad_variable_length_inputs: true
max-length-in-batch { value: 300 }
```

**Comment by dmdu** [comment]
Can somebody please look back at this question/request and clarify what is the current status of *batching for variable-length requests*? Is there a better way of doing it than manually padding sets of requests to fixed/maximum length? Also, what role is `pad_variable_length_inputs: true` supposed to play if we are manually padding? Many thanks for any comments!
