### ISSUE TITLE
build_pip_package fails

### ISSUE THREAD

**Issue by svenstaro** [tensorflow/serving#1541]
This is on Arch Linux with bazel 2.0.0. We're trying to package the new versiong of serving API.

Our build process is pretty simple:

    bazel build -c opt tensorflow_serving/tools/pip_package:build_pip_package
    bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package /tmp/pip

The first step works but `build_pip_package` fails:

```
bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package /tmp/pip

Tue 28 Jan 2020 05:58:56 AM CET : === Using tmpdir: /tmp/tmp.IYusiyrqYU
Adding python files
cp: cannot stat 'bazel-genfiles/tensorflow_serving/apis/*_pb2.py': No such file or directory
```

Full log:

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/e5bf8de410005de06a7ff5393fafdf832ef1d4ad.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
Loading: 0 packages loaded
Analyzing: target //tensorflow_serving/tools/pip_package:build_pip_package (1 packages loaded, 0 targets configured)
Analyzing: target //tensorflow_serving/tools/pip_package:build_pip_package (5 packages loaded, 5 targets configured)
INFO: Analyzed target //tensorflow_serving/tools/pip_package:build_pip_package (28 packages loaded, 761 targets configured).
INFO: Found 1 target...
[0 / 18] [Prepa] Creating source manifest for @com_google_protobuf//:protoc [for host]
[57 / 271] Compiling external/com_google_protobuf/src/google/protobuf/extension_set.cc [for host]; 1s local ... (64 actions, 63 running)
[121 / 271] Compiling external/com_google_protobuf/src/google/protobuf/descriptor.pb.cc [for host]; 3s local ... (63 actions, 62 running)
[183 / 271] Compiling external/com_google_protobuf/src/google/protobuf/descriptor.cc [for host]; 6s local
Target //tensorflow_serving/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package
INFO: Elapsed time: 25.715s, Critical Path: 8.34s
INFO: 264 processes: 264 local.
INFO: Build completed successfully, 271 total actions
INFO: Build completed successfully, 271 total actions
Tue 28 Jan 2020 06:03:18 AM CET : === Using tmpdir: /tmp/tmp.8N4Drv3vUg
Adding python files
cp: cannot stat 'bazel-genfiles/tensorflow_serving/apis/*_pb2.py': No such file or directory
```

This is on master and 2.1.0.

**Comment by gowthamkpr** [comment]
@svenstaro  Correct me if I am wrong, but this is similar to the issue that has been mentioned [here](https://github.com/tensorflow/serving/issues/1494). If it is can we go ahead and close this issue and track the issue there. Thanks!

**Comment by svenstaro** [comment]
It doesn't seem to be quite the same problem though if you look at the log.

**Comment by shizukanaskytree** [comment]
I have the same problem when I build with 

```
~/tf2/serving/tensorflow_serving/tools/docker$ docker build --pull -t $USER/tensorflow-serving-devel-gpu -f Dockerfile.devel-gpu .
```


```
...
...
INFO: Elapsed time: 17.992s, Critical Path: 12.65s
INFO: 265 processes: 265 local.
INFO: Build completed successfully, 271 total actions
Mon Feb 10 11:50:40 UTC 2020 : === Using tmpdir: /tmp/tmp.Fe770juSI8
Adding python files
cp: cannot stat 'bazel-genfiles/tensorflow_serving/apis/*_pb2.py': No such file or directory
The command '/bin/sh -c bazel build --color=yes --curses=yes     ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS}     tensorflow_serving/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package     /tmp/pip &&     pip --no-cache-dir install --upgrade     /tmp/pip/tensorflow_serving_api_gpu-*.whl &&     rm -rf /tmp/pip' returned a non-zero code: 1
```

Why does it happen? Thanks.

**Comment by gowthamkpr** [comment]
@svenstaro What version of Tensorflow serving are you using??

**Comment by shizukanaskytree** [comment]
@gowthamkpr The tf-serving version I use is commit `950705519372ce89da0c99524e3bb8b5a1fedf3f`.

**Comment by Brayangacely** [comment]
I have the same error.

Adding python files
cp: cannot stat 'bazel-genfiles/tensorflow_serving/apis/*_pb2.py': No such file or directory

The command '/bin/sh -c bazel build --color=yes --curses=yes     ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS} 
    tensorflow_serving/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package     /tmp/pip &&     pip --no-cache-dir install --upgrade     /tmp/pip/tensorflow_serving_api-*.whl &&     rm -rf /tmp/pip' returned a non-zero code: 1

**Comment by svenstaro** [comment]
@gowthamkpr It's tensorflow 2.1.0.

**Comment by gowthamkpr** [comment]
Try to build it using `bazel=1.2.1` and let me know if the error still persists. Thanks!

**Comment by svenstaro** [comment]
Same problem with bazel 1.2.1.

**Comment by minglotus** [comment]
At a super high-level, a temporary workaround is to replace 'bazel-genfiles/tensorflow_serving/apis/*_pb2.py' with the right path, based on the layout of the bazel version.

Say, for the docker image (https://www.tensorflow.org/tfx/serving/building_with_docker#building_a_container_from_a_dockerfile), replace 'bazel-genfiles' with 'bazel-out/k8-opt/bin'.

**Comment by Paperone80** [comment]
Just to add what worked for me: 

My WORKDIR:
`$ /opt/tensorflow/serving# ls -lha`

> total 108K
> drwxr-xr-x  7 root root 4.0K Feb 15 12:18 .
> drwxr-xr-x  5 root root 4.0K Feb 15 05:51 ..
> -rw-r--r--  1 root root  321 Feb 15 05:51 AUTHORS
> lrwxrwxrwx  1 root root  104 Feb 15 06:15 bazel-bin -> /root/.cache/bazel/_bazel_root/235fbe2e0db6dc63104db4cf913de6ec/execroot/tf_serving/bazel-out/k8-opt/bin
> lrwxrwxrwx  1 root root    9 Feb 15 12:18 bazel-genfiles -> bazel-out
> lrwxrwxrwx  1 root root   93 Feb 15 06:15 bazel-out -> /root/.cache/bazel/_bazel_root/235fbe2e0db6dc63104db4cf913de6ec/execroot/tf_serving/bazel-out
> -rw-r--r--  1 root root 1.8K Feb 15 05:51 .bazelrc
> lrwxrwxrwx  1 root root   83 Feb 15 06:15 bazel-serving -> /root/.cache/bazel/_bazel_root/235fbe2e0db6dc63104db4cf913de6ec/execroot/tf_serving
> lrwxrwxrwx  1 root root  109 Feb 15 06:15 bazel-testlogs -> /root/.cache/bazel/_bazel_root/235fbe2e0db6dc63104db4cf913de6ec/execroot/tf_serving/bazel-out/k8-opt/testlogs
> -rw-r--r--  1 root root 1.8K Feb 15 05:51 CONTRIBUTING.md
> drwxr-xr-x  8 root root 4.0K Feb 15 05:51 .git
> drwxr-xr-x  2 root root 4.0K Feb 15 05:51 .github
> -rw-r--r--  1 root root  263 Feb 15 05:51 .gitignore
> -rw-r--r--  1 root root    0 Feb 15 05:51 .gitmodules
> -rw-r--r--  1 root root  12K Feb 15 05:51 LICENSE
> -rw-r--r--  1 root root 5.9K Feb 15 05:51 README.md
> -rw-r--r--  1 root root  21K Feb 15 05:51 RELEASE.md
> drwxr-xr-x 16 root root 4.0K Feb 15 05:51 tensorflow_serving
> drwxr-xr-x  6 root root 4.0K Feb 15 05:51 third_party
> drwxr-xr-x  2 root root 4.0K Feb 15 05:51 tools
> -rw-r--r--  1 root root 2.7K Feb 15 05:51 WORKSPACE

Check the symlink of ```bazel-bin``` that's the folder @minglotus is referring to. 

Create a symlink in your serving WORKDIR: 
`$ ln -sfv bazel-bin bazel-genfiles`
and you should be good to go.

**Comment by svenstaro** [comment]
I made it work using a similar hack in the official Arch package but I'd appreciate a fix for recent bazel versions nonetheless.

**Comment by minglotus** [comment]
With https://github.com/tensorflow/serving/commit/a328ed619b823052bdecfe9f619fbdf3c2a99dbe, this is fixed for the Docker environment [1].

If bazel genfile path can be different in another environment, the suggestion is to find the genfile dir and re-write.

[1] https://www.tensorflow.org/tfx/serving/building_with_docker#building_a_container_from_a_dockerfile
