### ISSUE TITLE
Dockerfile.devel-gpu references a python package that doesn't exist

### ISSUE THREAD

**Issue by jraffield1** [tensorflow/serving#1545]
### System information
- Linux Ubuntu 16.04)
- TensorFlow Serving installing from source
- 2.1.0

### Describe the problem
Dockerfile.devel-gpu uses nvidia/cuda:10.0-base-ubuntu16.04 as a base image but tries to install python3-distutils, which doesn't exist for ubuntu 16.04
When trying to build from source, it displays the error "Unable to locate package python3-distutils"

### Exact Steps to Reproduce
git clone https://github.com/tensorflow/serving.git
cd serving
sudo docker build --pull -t tensorflow-serving-devel-gpu -f tensorflow_serving/tools/docker/Dockerfile.devel-gpu .

### Source code / logs
[logfile.txt](https://github.com/tensorflow/serving/files/4172961/logfile.txt)

**Comment by gowthamkpr** [comment]
@jraffield1 As mentioned in this [comment](https://github.com/pypa/pip/issues/5367#issuecomment-386864941), can you please try istalling `python3-distutils ` using this command
`sudo apt-get install python3-distutils` and let me know if the error still exists.

**Comment by jraffield1** [comment]
Yes, it gives the same "unable to locate package" error.

I was able to work about it by changing 'python3-distutils' to 'python3-distutils-extra' in the dockerfile

**Comment by Danhyal-Masood** [comment]
That moment you commit an update without testing..

**Comment by minglotus-6** [comment]
It should work by now with this commit (https://github.com/tensorflow/serving/commit/b9602b3820dddea0d9fa9423b1ae9eaaf2aec977)
