### ISSUE TITLE
Source based compilation failed，Python Configuration Error: Problem getting python include path.

### ISSUE THREAD

**Issue by wangwenchao-job** [tensorflow/serving#1548]
environment：
ubuntu 18
anaconda env：tf1.14

Compiler directive：
sudo tools/run_in_docker.sh bazel build -c opt tensorflow_serving/...

the error：
`== Pulling docker image: tensorflow/serving:nightly-devel
nightly-devel: Pulling from tensorflow/serving
Digest: sha256:f40edf7bb5419be5011dd662155f8197b63a0db5fc3ec61c33d5d657c94d85ee
Status: Image is up to date for tensorflow/serving:nightly-devel
== Running cmd: sh -c 'cd /home/jianzhi/tf-servimg/serving; TEST_TMPDIR=.cache bazel build -c opt tensorflow_serving/...'
usermod: no changes
$TEST_TMPDIR defined: output root default is '/home/jianzhi/tf-servimg/serving/.cache' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
ERROR: /home/jianzhi/tf-servimg/serving/.cache/_bazel_root/dda64ea0742ddb17d46c151407cafd32/external/org_tensorflow/third_party/python_runtime/BUILD:5:1: no such package '@local_config_python//': Traceback (most recent call last):
        File "/home/jianzhi/tf-servimg/serving/.cache/_bazel_root/dda64ea0742ddb17d46c151407cafd32/external/org_tensorflow/third_party/py/python_configure.bzl", line 345
                _create_local_python_repository(repository_ctx)
        File "/home/jianzhi/tf-servimg/serving/.cache/_bazel_root/dda64ea0742ddb17d46c151407cafd32/external/org_tensorflow/third_party/py/python_configure.bzl", line 295, in _create_local_python_repository
                _get_python_include(repository_ctx, python_bin)
        File "/home/jianzhi/tf-servimg/serving/.cache/_bazel_root/dda64ea0742ddb17d46c151407cafd32/external/org_tensorflow/third_party/py/python_configure.bzl", line 241, in _get_python_include
                _execute(repository_ctx, [python_bin, "-c",...())"], <2 more arguments>)
        File "/home/jianzhi/tf-servimg/serving/.cache/_bazel_root/dda64ea0742ddb17d46c151407cafd32/external/org_tensorflow/third_party/py/python_configure.bzl", line 56, in _execute
                _fail("\n".join([error_msg.strip() if ... ""]))
        File "/home/jianzhi/tf-servimg/serving/.cache/_bazel_root/dda64ea0742ddb17d46c151407cafd32/external/org_tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
                fail(("%sPython Configuration Error:%...)))
Python Configuration Error: Problem getting python include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'sysconfig'
Is the Python binary path set up right? (See ./configure or PYTHON_BIN_PATH.) Is distutils installed?
 and referenced by '@org_tensorflow//third_party/python_runtime:headers'
ERROR: Analysis of target '//tensorflow_serving/model_servers/test_util:tensorflow_model_server_test_base' failed; build aborted: Analysis failed
INFO: Elapsed time: 3.584s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (150 packages loaded, 3953 targets configured)
`

I have no idea. Please help me. Thank you very much

**Comment by gowthamkpr** [comment]
It seems like `python3-distutils` is not installed
Can you install it using
`sudo apt install python3-distutils`

**Comment by wangwenchao-job** [comment]
> It seems like `python3-distutils` is not installed
> Can you install it using
> `sudo apt install python3-distutils`

the python3-distutils is the lastest version

**Comment by wangwenchao-job** [comment]
---To update---

Before, I used bazel version 0.24.1，report errors ：
Current Bazel version is 0.24.1, expected at least 1.2.1

So，I upgraded bazel.
Use command to view version：bazel --version
bazel 2.1.0

but，the error did not change: Current Bazel version is 0.24.1, expected at least 1.2.1

**Comment by gowthamkpr** [comment]
As shown [here](https://github.com/tensorflow/serving/blob/385e7962ceae7e30e58d1e4ad54b0502795b9ef5/tensorflow_serving/tools/docker/Dockerfile.devel-gpu#L97) your bazel version should be 1.2.1 but your system has bazel 2.1.0 which is a mismatch.

Please down grade your bazel version to 1.2.1 using the commands in the comment [here](https://github.com/tensorflow/tensorflow/issues/24101#issuecomment-497740629)

**Comment by gowthamkpr** [comment]
@wangwenchao-job Please confirm so that we can take further action on the issue. Thanks!

**Comment by wangwenchao-job** [comment]
> @wangwenchao-job Please confirm so that we can take further action on the issue. Thanks!

Sorry for my late reply. I know that the version here refers to the version in the image. The problem has been solved. Thank you very much.
