### ISSUE TITLE
How can I run tensorflow serving per core CPU in the same time ?

### ISSUE THREAD

**Issue by pake2070** [tensorflow/serving#1550]

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version and Tensorflow Serving Version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gowthamkpr** [comment]
As shown [here](https://github.com/tensorflow/serving/blob/e085cb37b4b5c62154aa063dcbb781b24d5b3fd4/tensorflow_serving/tools/docker/Dockerfile.mkl#L85), you can set `TENSORFLOW_INTRA_OP_PARALLELISM=n `where 'n' is the No. of Physical cores you want to use.

By controlling `TENSORFLOW_INTRA_OP_PARALLELISM` and `TENSORFLOW_INTER_OP_PARALLELISM` , you can control the performance.

**Comment by geraldstanje** [comment]
@gowthamkpr what is the default setting on TENSORFLOW_INTRA_OP_PARALLELISM and TENSORFLOW_INTER_OP_PARALLELISM?

**Comment by gowthamkpr** [comment]
@geraldstanje You have to either modify the image with the following parameters and commit it or build your serving from source modifying these parameters.

**Comment by Arnold1** [comment]
@gowthamkpr what i mean who determind those settings on what facts? Those seem to be some standard setting?!
‘’’
ENV OMP_NUM_THREADS=2
ENV TENSORFLOW_INTRA_OP_PARALLELISM=2
ENV TENSORFLOW_INTER_OP_PARALLELISM
‘’’

**Comment by geraldstanje** [comment]
@gowthamkpr how did you come up with that settings - those seem to be some standard setting (based on what)?!
```
ENV OMP_NUM_THREADS=2
ENV TENSORFLOW_INTRA_OP_PARALLELISM=2
ENV TENSORFLOW_INTER_OP_PARALLELISM
```

**Comment by gowthamkpr** [comment]
@geraldstanje Please go through this [tutorial](https://hackernoon.com/how-we-improved-tensorflow-serving-performance-by-over-70-f21b5dad2d98) and where they have set those flags.

**Comment by gowthamkpr** [comment]
What is the use case that you are trying to solve here @pake2070 ?

**Comment by pake2070** [comment]
instead of running 2 models on the hardware at the same time, I run 2 models separately hardware, it seems to faster

**Comment by pake2070** [comment]
with the same resource

**Comment by Arnold1** [comment]
hi @pake2070 how many request per second do you have to 1 pod (1 model per pod) and what is the latency? does it use cpu or gpu?

**Comment by pake2070** [comment]
I deployed two models ( per pod ), and I used gRPC instead of RESTfulAPI, for detection and then classification, total about 0.3~0.4 per image

**Comment by Arnold1** [comment]
@pake2070 does it run on gpu? 0.3 seconds?

**Comment by gowthamkpr** [comment]
@pake2070 Tensorflow Serving optimizes and uses the resources that is available to it. I would recommend using GPU to serve multiple models at the same time. Please go through the following [tutorial](https://medium.com/@stephen.odaibo/tensorflow-serving-of-multiple-ml-models-simultaneously-to-a-rest-api-python-client-cd60ac6f71aa).

**Comment by gowthamkpr** [comment]
@pake2070 Can you please respond so we can take the discussion further.

**Comment by gowthamkpr** [comment]
Cloxing this issue as it has been inactive for more than 3 weeks. Please add additional comments for us to open this issue again. Thanks!

**Comment by DachuanZhao** [comment]
> @pake2070 Can you please respond so we can take the discussion further.
I have add ```tensorflow_intra_op_parallelism``` and ```tensorflow_inter_op_parallelism``` , But it doesn't work
```
docker run -p 8501:8501 \
  --mount type=bind,source=/path/to/my_model/,target=/models/my_model \
  -e MODEL_NAME=my_model -t tensorflow/serving --tensorflow_intra_op_parallelism=8 --tensorflow_inter_op_parallelism=8
```
