### ISSUE TITLE
Single GPU underutilized with tensorflow serving

### ISSUE THREAD

**Issue by abhinavos7a** [tensorflow/serving#1556]
I am currently testing performance of seqToseq models on GPU node using tensorflow serving

OS: Rhel 7
GPU: Nvidia V100
CPU: Intel Xeon

Deployment : docker.ouroath.com:4443/ml/tensorflow-serving-gpu

The plan is to start with the simplest experiment where multiple inference request are served and then moving towards complex experiment setting where client/server side batching is enabled, freezing saved model with TensorRT to utilize tensor cores and then finally quantization.
I am stuck in first experiment itself where I am hitting TFS with concurrent single inference requests (no batching), where I am expecting linear relationship b/w rpq and gpu utilization.
This is how I start TFS gpu container

`sudo docker run --gpus 1 -p 8500:8500 -p 80:8501 -v /models:/models tensorflow/serving:latest-gpu --model_config_file=/models/models.config &`

`rps  ---       p50 msec  ---    gpu % (1 gpu)  --- cpu % (72 core)`
`1        -----      250        ---------             10%           ---------------             100 %`
`2        -----      275        ---------             24%           ---------------             200 %`
`3        -----      280        ---------             32%           ---------------             300 %`
`4        -----      420        ---------             40%           ---------------             400 %`
`4.5  ---      760        ---------             40%           -------------        ~  400 %`
`4.7  ---      2160        ---------             40%           -------------        ~  400 %`

GPU Memory utilization was around 5%.
As I am linearly increasing rps , I am expecting that gpu utilization should also increase linearly and the latency should remain constant. Latency goes for a toss the moment qps goes >=4 while gpu is just 40% utilized.

No matter how many concurrent request I make with TFS, the qps never goes above 5.
I have tried playing around with tensorflow_session_parallelism/rest_api_num_threads etc , but they never helped.

When I spawn 2 tensorflow serving instances pointing to the same GPU with different REST port, the gpu utilization does goes 100%.

**Comment by rmothukuru** [comment]
@abhinavos7a,
Can you please try the solution mentioned in [this link](https://github.com/tensorflow/serving/issues/1440#issuecomment-541578798) and let us know if it improves the performance of GPU. Thanks!

**Comment by abhinavos7a** [comment]
@rmothukuru thanks a lot for your reply. The GPU utilization does increases with batching which I have already verified and is also mentioned in the link above. 

The post is regarding single inference requests to have a basic understanding about tf serving performance.

**Comment by lilao** [comment]
Thank you for reporting the problem. Can you take a look at [the performance guide](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/performance.md), and if that does not address your problem, [profile your inference requests with Tensorboard](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/tensorboard.md)?

**Comment by gowthamkpr** [comment]
@abhinavos7a Can you please respond to the above comment so that we can take the discussion further. Thanks!

**Comment by turowicz** [comment]
I'm having a similar problem. I have multiple clients that send images of various sizes for object detection. Batching is impossible as it blocks the asynchronous requests. GPU util never goes higher than 20%.

**Comment by turowicz** [comment]
I've migrated to NVIDIA Triton Inference Server where the problems do not exist.

**Comment by gowthamkpr** [comment]
@abhinavos7a @turowicz Can you please respond to this [comment](https://github.com/tensorflow/serving/issues/1556#issuecomment-595041132) so we can debug the issue. Thanks!

**Comment by huangyz0918** [comment]
> The GPU utilization does increases with batching which I have already verified and is also mentioned in the link above.

That's true.

**Comment by turowicz** [comment]
Sorry I've migrated away from TF Serving.

**Comment by rmothukuru** [comment]
@abhinavos7a ,
Can you please confirm if your issue is resolved so that we can close this issue. Thanks!

**Comment by abhinavos7a** [comment]
@rmothukuru Sorry for my delayed response.

The GPU utilization does increase with batching which I have verified and was also suggested in the [performance link ](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/performance.md)

However the post was about single inference requests and was curious as to how TFS behaves in such scenarios. Since this issue doesn't block any of our requirements, we can close this issue.

**Comment by lilao** [comment]
Closing this issue as requested. For future investigations, please profile your inference requests with Tensorboard as explained here: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/tensorboard.md.
