### ISSUE TITLE
tools/run_in_docker.sh bazel build -c opt tensorflow_serving/... fetching error

### ISSUE THREAD

**Issue by wangwenchao-job** [tensorflow/serving#1557]
`ERROR: error loading package '': Encountered error while reading extension file 'third_party/toolchains/preconfig/generate/archives.bzl': no such package '@org_tensorflow//third_party/toolchains/preconfig/generate': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/2a2c812ab2330c9aac33335f10679a346436acfb.tar.gz, https://github.com/tensorflow/tensorflow/archive/2a2c812ab2330c9aac33335f10679a346436acfb.tar.gz] to /home/jianzhi/govion/tf-serving/serving/.cache/_bazel_root/32bfad5f031b933ad4589923304dc54c/external/org_tensorflow/2a2c812ab2330c9aac33335f10679a346436acfb.tar.gz: Tried to reconnect at offset 2,331,084 but server didn't support it
ERROR: error loading package '': Encountered error while reading extension file 'third_party/toolchains/preconfig/generate/archives.bzl': no such package '@org_tensorflow//third_party/toolchains/preconfig/generate': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/2a2c812ab2330c9aac33335f10679a346436acfb.tar.gz, https://github.com/tensorflow/tensorflow/archive/2a2c812ab2330c9aac33335f10679a346436acfb.tar.gz] to /home/jianzhi/govion/tf-serving/serving/.cache/_bazel_root/32bfad5f031b933ad4589923304dc54c/external/org_tensorflow/2a2c812ab2330c9aac33335f10679a346436acfb.tar.gz: Tried to reconnect at offset 2,331,084 but server didn't support it
`

Error summary：
ERROR: error loading package 

Is that because of the Internet？？

I have tried to download it manually and put it under the specified path.
But the project will clear the path and download again. Where should I turn off the download again? Thank you very much

**Comment by gowthamkpr** [comment]
What OS are you using? What is the version of Tensorflow serving? 
Please provide the steps for us to reproduce the issue. Thanks!

**Comment by wangwenchao-job** [comment]
> What OS are you using? What is the version of Tensorflow serving?
> Please provide the steps for us to reproduce the issue. Thanks!

Thank you very much for your reply.The following procedure is my compilation step：
1、git clone https://github.com/tensorflow/serving.git
2、cd serving
3、git checkout tags/2.1.0 -b lastest
4、bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server

and my os is ubuntu 18.04

**Comment by gowthamkpr** [comment]
@wangwenchao-job Please try the commands given in order [here](https://www.tensorflow.org/tfx/serving/setup#clone_the_build_script) and let me know if the issue still persists. Thanks!

**Comment by Windfarer** [comment]
Set a stable proxy for your docker will resolve this problem, if you are in China mainland.  https://docs.docker.com/network/proxy/

**Comment by gowthamkpr** [comment]
I am closing this issue as this issue is mainly related to your network not Tensorflow serving. Please add additional comments and we can open this issue again. Thanks!

**Comment by wangwenchao-job** [comment]
> I am closing this issue as this issue is mainly related to your network not Tensorflow serving. Please add additional comments and we can open this issue again. Thanks!

Yes, it's really my network problem. It has been compiled through many attempts. Thank you again for your advice

**Comment by wangwenchao-job** [comment]
> Setting a stable network proxy for your docker will resolve this problem, if you are in China mainland. https://docs.docker.com/network/proxy/

Thank you very much for your reply. I'll try it
