### ISSUE TITLE
how to convert nhwc saved_model to nchw saved_model?

### ISSUE THREAD

**Issue by IvyGongoogle** [tensorflow/serving#1560]
Hello, I have a problem. I have trained a tensorflow model using `nhwc` and convert it a saved_model.  Now I want to convert this `nhwc` saved_model to `nchw` saved_model that will be deployed on tf serving. So how to do?

Anyone can give some advises?

**Comment by gowthamkpr** [comment]
Please follow this [tutorial](https://hackernoon.com/how-we-improved-tensorflow-serving-performance-by-over-70-f21b5dad2d98) where  `NHWC` saved_model has been served using Tensorflow serving. Thanks!

**Comment by IvyGongoogle** [comment]
@gowthamkpr sorry, I can not get useful info about how to convert nhwc saved_model to nchw saved_model from above two tutorial you give.

**Comment by gowthamkpr** [comment]
I am saying that you can directly use NHWC saved_model to deploy using Tensorflow serving. I am trying to understand whats the reason behind converting the model from  nhwc saved_model to nchw saved_model?

**Comment by gowthamkpr** [comment]
@IvyGongoogle Can you please respond to the above question. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue at it has been inactive for close to three weeks. Please add additional comments and we can open the issue again. Thanks!

**Comment by IvyGongoogle** [comment]
@gowthamkpr Sorry for replying so late. Because I want to deploy my saved_model onto Nvidia GPU. As we all know the CNN-based model can have faster inference speed when using Nvidia GPU that can better support `nchw` than `nhwc` tensor. So I want to convert the model from `nhwc` saved_model to `nchw` saved_model to get faster inference speed.

Thanks.

**Comment by romil611** [comment]
@IvyGongoogle were you able to convert from nhwc to nchw? I'm using the model i get to work with other applications(deepstream) which specifically need nchw. 
@gowthamkpr can you help me with converting between the 2 formats? I have a trained model in nhwc format.
