### ISSUE TITLE
build tf.serving and pass some opt to tensorflow

### ISSUE THREAD

**Issue by taozhijiang** [tensorflow/serving#1567]
I need some help for building tf.serving at our machine.

* how to pass additional opt and conf flags to tensorflow?
I noticed tensorflow building supports many more configs, such as  --config=noaws --config=nogcp --config=nohdfs, but I can not pass these when build with tf.serving target. So how can I add additional configs and opts when building tensorflow part.
Additional, tensorflow ./configure can generate some other opts, how these opts select when build as part of tf.serving?

* optimize tensorflow for size and speed
We create our own inference environment, so want to change tensorflow code commenting out some non-essential ops. The only way is change the code and archive our own tar.gz, than change the location and sha256, right?

bazel looks like a black-box tool, so I do not know how to track how build behaves. ;-(
Thanks and any hint will be appreciated!

**Comment by taozhijiang** [comment]
I comment out some components for tensorflow original code, tar it and replace the new commit-id, sha256 in serving repos, it works now.
The tensorflow configure flags take affect by ENV, and these can be set in through --action_env to override their default value.

It works great now.

**Comment by hiigao** [comment]
I met for the same issue. Is there any formal way to compile serving without aws support?
