### ISSUE TITLE
The score of the request in the TF serving service is different from the score of the Java call saved_model

### ISSUE THREAD

**Issue by mrchor** [tensorflow/serving#1568]
I trained a deep FM model with estimator. But now there is the problem that the scores of different environments are inconsistent.
1、Java calls the saved model to get the correct score.
![image](https://user-images.githubusercontent.com/10007145/76197062-65895600-6226-11ea-85db-241020bf546f.png)
![image](https://user-images.githubusercontent.com/10007145/76197175-9c5f6c00-6226-11ea-841a-6da1ab92e62e.png)
2、The scores obtained by requesting TF serving service are all 0.0
![image](https://user-images.githubusercontent.com/10007145/76197324-e6485200-6226-11ea-8ca9-b82a608bcd18.png)
3、The above sample is the same in both environments.

**Comment by mrchor** [comment]
Excuse me, what causes TF serving to score incorrectly?

**Comment by gowthamkpr** [comment]
@mrchor TF serving returns the score that your model returns as serving just queries your model to get the predictions.

Can you please share the exact details so that we can reproduce the issue. Thanks!

**Comment by mrchor** [comment]
I'm sorry, but there's something wrong with my code. I've corrected it now. 
The previous code was:
![image](https://user-images.githubusercontent.com/10007145/76284023-164f2e00-62d7-11ea-9507-829b028f71cd.png)


The current code is：
![image](https://user-images.githubusercontent.com/10007145/76283995-059eb800-62d7-11ea-9a1f-900dfead63e0.png)

The reason is that the input data type should be long, while the data type I input is integer.
@gowthamkpr Thank you for your reply~
