### ISSUE TITLE
How to pass new parameters to tensorflow_model_server through container

### ISSUE THREAD

**Issue by wangwenchao-job** [tensorflow/serving#1569]
Now I can compile the source code successfully, and add some parameters to the source code. And the image is successfully packaged through Dockfile and Dockfile.devel. **Then my question is how to pass parameters to the tensorflow_model_server**
For example:
I add the parameter --value1 = sth to the main.cc file
How should I pass the value of input value1 to the program through the instruction：
`docker run -t --rm -p 8501:8501 \
    -v "$TESTDATA/saved_model_half_plus_two_cpu:/models/half_plus_two" \
    -e MODEL_NAME=half_plus_two \
    tensorflow/serving &`

In the dockfile.md file, I notice that 
`docker run -p 8500:8500 -p 8501:8501 \
  --mount type=bind,source=/path/to/my_model/,target=/models/my_model \
  --mount type=bind,source=/path/to/my/models.config,target=/models/models.config \
  -t tensorflow/serving --model_config_file=/models/models.config`

But in my case, I only need a value, not a mount file. What should I do？
Thank you very much for your reply！！

**Comment by gowthamkpr** [comment]
@wangwenchao-job What do you mean by adding parameters? Can you please be more specific about what use case are you trying to solve here. Thanks!

**Comment by patha454** [comment]
@wangwenchao-job I infer you're trying to pass command line arguments to Tensorflow Serving, while starting Tensorflow Serving in Docker.

In this case, the first half of the command `docker run ...` are arguments for Docker: `--rm`, `--p`, `-v`, `-mount` are all Docker's command line arguments. Everything after the image tag `-t tensorflow/serving` is passed *through* Docker into Tensorflow Serving.

So if you've added the command line argument `--value1` to Tensorflow Serving's source, you would pass it like this:
```
docker run -t --rm \
-p 8501:8501  \
-v "$TESTDATA/saved_model_half_plus_two_cpu:/models/half_plus_two" \
-e MODEL_NAME=half_plus_two
-t tensorflow/serving 
# Everything after `-t tensorflow/serving` here are TF Serving's parameters.
--value1=sth
```

If you're wondering about why `-e MODEL_NAME=half_plus_two` is passed to Docker, and not TF Serving, it's because `Docker -e` sets an environment variable in the container, which TF Serving reads to select a model.

'Hope that helps.

**Comment by wangwenchao-job** [comment]
> @wangwenchao-job I infer you're trying to pass command line arguments to Tensorflow Serving, while starting Tensorflow Serving in Docker.
> 
> In this case, the first half of the command `docker run ...` are arguments for Docker: `--rm`, `--p`, `-v`, `-mount` are all Docker's command line arguments. Everything after the image tag `-t tensorflow/serving` is passed _through_ Docker into Tensorflow Serving.
> 
> So if you've added the command line argument `--value1` to Tensorflow Serving's source, you would pass it like this:
> 
> ```
> docker run -t --rm \
> -p 8501:8501  \
> -v "$TESTDATA/saved_model_half_plus_two_cpu:/models/half_plus_two" \
> -e MODEL_NAME=half_plus_two
> -t tensorflow/serving 
> # Everything after `-t tensorflow/serving` here is TF Serving's parameters.
> --value1=sth
> ```
> 
> If you're wondering about why `-e MODEL_NAME=half_plus_two` is passed to Docker, and not TF Serving, it's because `Docker -e` sets an environment variable in the container, which TF Serving reads to select a model.
> 
> 'Hope that helps.

Yes, thank you very much for your reply，I tried it, here are my instructions：
`sudo docker run -t --rm -p 9999:8501 \
> --name test \
> -v /home/model/:/models/half_plus_two \
> -e MODEL_NAME=half_plus_two \
> jianzhi/tensorflow-serving & \
> --my_paramter=some_value`

But it gave an error: no instructions found --my_paramter=some_value

**Comment by wangwenchao-job** [comment]
> @wangwenchao-job What do you mean by adding parameters? Can you please be more specific about what use case are you trying to solve here. Thanks!

That is, I added some specific control parameters in main.cc, and then I want to pass the parameters in by way of docker to create a container.Please see patha454's answer, that is my question. Thanks a lot!

**Comment by wangwenchao-job** [comment]
> @wangwenchao-job What do you mean by adding parameters? Can you please be more specific about what use case are you trying to solve here. Thanks!



> @wangwenchao-job What do you mean by adding parameters? Can you please be more specific about what use case are you trying to solve here. Thanks!

That is, I added some specific control parameters in main.cc, and then I want to pass the parameters in by way of docker to create a container.
Please see patha454's answer, that is my question. Thanks a lot!

**Comment by patha454** [comment]
> ```
> sudo docker run -t --rm -p 9999:8501 \
>--name test \
>-v /home/model/:/models/half_plus_two \
>-e MODEL_NAME=half_plus_two \
>jianzhi/tensorflow-serving & \
>--my_paramter=some_value`
> ```
> But it gave an error: no instructions found --my_paramter=some_value

This is a shell error, and not Tensorflow Serving. I refer you to [the sh man page](https://linux.die.net/man/1/sh) in the first instance. `&` only starts a background process when placed after the entire command. `&`, placed anywhere else, acts by starting the left hand side as a background command and the right hand side as second, blocking, command.

I suggest you move the `&` to the end of your command.

**Comment by gowthamkpr** [comment]
Yes @wangwenchao-job please do as mentioned in the above comment and the issue here as mentioned by @patha454  is not related to serving its related to passing in command line arguments to the docker itself.

**Comment by gowthamkpr** [comment]
@wangwenchao-job Did you resolve the issue?

**Comment by gowthamkpr** [comment]
Closing this issue as it has been in awaiting response for more than 3 weeks. Please add additional comments to open this issue again. Thanks!
