### ISSUE TITLE
How to use base64 image as input 

### ISSUE THREAD

**Issue by Niels-Osnabrugge** [tensorflow/serving#1570]
### System information
- Linux Ubuntu 16.04
-Serving installed from binary
-Tensorflow Serving 2.10
-TensorFlow 2 keras model

### Describe the problem
I have been unable to find a source that describes a way to send an (base64) image over a POST request. I have tried to edit the signature so it accepts base64 images as input but with no success. Is it possible to change the model so that it accepts a (base64) image as input? If not, can I convert my created image to the correct format on my client?
Source code / logs

I am currently saving my keras model with standard signature using:
```javascript
tf.saved_model.save(model, "path")
```
The get requests result says the model is deployed:
```json
{ "version": "4", "state": "AVAILABLE", "status": { "error_code": "OK", "error_message": "" } }
```

I am converting my image to base64 using the 'react-native-image-base64' library and sending it using a post request with the correct format.
However, as the error code says it expects a float

```json
"error": "Failed to process element: 0 of \'instances\' list. Error: Invalid argument: JSON Value: {"Base64 image string here"} Type: Object is not of expected type: float"
```

with the following request :
```curl
curl --request POST \
  --url http://192.168.1.75:8501/v1/models/saved_model:predict \
  --header 'content-type: application/json' \
  --data '
{
   "instances":
   [
	{
	   "b64": "HBwcIiIiIiIiHh4eGhoaGBgYExMTEBAQERERERERDw8PCQkJBQ.."
	}
   ]
}'
```

**Comment by gowthamkpr** [comment]
@Niels-Osnabrugge Please take a look at this canonical [example](https://github.com/tensorflow/serving/blob/r2.1/tensorflow_serving/example/resnet_client.py) and use on the client side to perform inference.

**Comment by Niels-Osnabrugge** [comment]
Hey @gowthamkpr ,
Thankyou for helping. I looked at the example and downloaded a resnet model which accepts base64 jpgs as input. I was sucessfully able to serve it on tensorflow serving and make a POST request.

Although this might not be a tensorflow serving but a tensorflow question. I cant seem to find a way to export/save my (keras) model with a signature so that it accepts JPG's as input. Do you know how this is done?

Thx again, you already saved me a great deal of trouble

**Comment by gowthamkpr** [comment]
Signature just contains input dimensions and output dimensions that the model would accept during predict. And you are gonna feed a tensor lets say with dimensions `( None, 256,256,3)`, which means you have to convert the jpeg image into a tensor in the client file during inference. 

So, the image should be preprocessed in the client file to convert it into a tensor or you can also convert the images into tfrecords to gain significant performance improvement as seen in this [issue](https://stackoverflow.com/questions/54440226/using-tfrecords-with-keras)

**Comment by gowthamkpr** [comment]
@Niels-Osnabrugge I am gonna close this issue as it has been resolved. Please add additional comments for us to reopen this issue again. Thanks!

**Comment by GF-Huang** [comment]
> @Niels-Osnabrugge I am gonna close this issue as it has been resolved. Please add additional comments for us to reopen this issue again. Thanks!

Could you show the solution?
