### ISSUE TITLE
gcc failed: error executing command

### ISSUE THREAD

**Issue by yuxuan2015** [tensorflow/serving#1573]
docker build --pull -t $USRE/tensorflow-serving-devel \
  -f tensorflow_serving/tools/docker/Dockerfile.devel .

ERROR: /tensorflow-serving/tensorflow_serving/batching/BUILD:49:1: C++ compilation of rule '//tensorflow_serving/batching:batching_session' failed (Exit 1): gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/execroot/tf_serving && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/tensorflow_serving/batching/_objs/batching_session/batching_session.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow_serving/batching/_objs/batching_session/batching_session.o' -DTENSORFLOW_USE_CUSTOM_CONTRACTION_KERNEL -DTENSORFLOW_USE_MKLDNN_CONTRACTION_KERNEL -DSQLITE_OMIT_DEPRECATED -DCURL_STATICLIB -DPLATFORM_LINUX -DENABLE_CURL_CLIENT -DENABLE_NO_ENCRYPTION -DTF_USE_SNAPPY -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote . -iquote bazel-out/k8-opt/bin -iquote external/org_tensorflow -iquote bazel-out/k8-opt/bin/external/org_tensorflow -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/k8-opt/bin/external/local_config_sycl -iquote external/nsync -iquote bazel-out/k8-opt/bin/external/nsync -iquote external/gif -iquote bazel-out/k8-opt/bin/external/gif -iquote external/libjpeg_turbo -iquote bazel-out/k8-opt/bin/external/libjpeg_turbo -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/zlib_archive -iquote bazel-out/k8-opt/bin/external/zlib_archive -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/k8-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/bin/external/highwayhash -iquote external/double_conversion -iquote bazel-out/k8-opt/bin/external/double_conversion -iquote external/snappy -iquote bazel-out/k8-opt/bin/external/snappy -iquote external/curl -iquote bazel-out/k8-opt/bin/external/curl -iquote external/boringssl -iquote bazel-out/k8-opt/bin/external/boringssl -iquote external/jsoncpp_git -iquote bazel-out/k8-opt/bin/external/jsoncpp_git -iquote external/aws -iquote bazel-out/k8-opt/bin/external/aws -iquote external/sobol_data -iquote bazel-out/k8-opt/bin/external/sobol_data -iquote external/mkl_dnn -iquote bazel-out/k8-opt/bin/external/mkl_dnn -iquote external/local_config_cuda -iquote bazel-out/k8-opt/bin/external/local_config_cuda -iquote external/local_config_tensorrt -iquote bazel-out/k8-opt/bin/external/local_config_tensorrt -iquote external/png -iquote bazel-out/k8-opt/bin/external/png -iquote external/lmdb -iquote bazel-out/k8-opt/bin/external/lmdb -iquote external/icu -iquote bazel-out/k8-opt/bin/external/icu -iquote external/org_sqlite -iquote bazel-out/k8-opt/bin/external/org_sqlite -iquote external/gemmlowp -iquote bazel-out/k8-opt/bin/external/gemmlowp -Ibazel-out/k8-opt/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual -Ibazel-out/k8-opt/bin/external/local_config_tensorrt/_virtual_includes/tensorrt_headers -isystem external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/nsync/public -isystem bazel-out/k8-opt/bin/external/nsync/public -isystem external/gif -isystem bazel-out/k8-opt/bin/external/gif -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src -isystem external/zlib_archive -isystem bazel-out/k8-opt/bin/external/zlib_archive -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/bin/external/farmhash_archive/src -isystem external/double_conversion -isystem bazel-out/k8-opt/bin/external/double_conversion -isystem external/curl/include -isystem bazel-out/k8-opt/bin/external/curl/include -isystem external/boringssl/src/include -isystem bazel-out/k8-opt/bin/external/boringssl/src/include -isystem external/jsoncpp_git/include -isystem bazel-out/k8-opt/bin/external/jsoncpp_git/include -isystem external/aws/aws-cpp-sdk-core/include -isystem bazel-out/k8-opt/bin/external/aws/aws-cpp-sdk-core/include -isystem external/aws/aws-cpp-sdk-s3/include -isystem bazel-out/k8-opt/bin/external/aws/aws-cpp-sdk-s3/include -isystem external/mkl_dnn/include -isystem bazel-out/k8-opt/bin/external/mkl_dnn/include -isystem external/mkl_dnn/src -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src -isystem external/mkl_dnn/src/common -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/common -isystem external/mkl_dnn/src/cpu -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu -isystem external/mkl_dnn/src/cpu/gemm -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu/gemm -isystem external/mkl_dnn/src/cpu/xbyak -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu/xbyak -isystem external/local_config_cuda/cuda -isystem bazel-out/k8-opt/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include -isystem external/png -isystem bazel-out/k8-opt/bin/external/png -isystem external/icu/icu4c/source/common -isystem bazel-out/k8-opt/bin/external/icu/icu4c/source/common '-march=native' -O3 '-std=c++14' '-D_GLIBCXX_USE_CXX11_ABI=0' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow_serving/batching/batching_session.cc -o bazel-out/k8-opt/bin/tensorflow_serving/batching/_objs/batching_session/batching_session.o)
Execution platform: @local_config_platform//:host
tensorflow_serving/batching/batching_session.cc: In member function 'tensorflow::Status tensorflow::serving::BatchingSession::SplitOutputTensors(const tensorflow::serving::TensorSignature&, const std::vector<tensorflow::Tensor>&, tensorflow::serving::Batch<tensorflow::serving::BatchingSessionTask>*)':
tensorflow_serving/batching/batching_session.cc:500:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < output_tensors.size(); ++i) {
                   ~~^~~~~~~~~~~~~~~~~~~~~~~
tensorflow_serving/batching/batching_session.cc:508:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (tensor.shape().dim_size(0) != batch->size() + padding_size) {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tensorflow_serving/batching/batching_session.cc: In member function 'tensorflow::Status tensorflow::serving::BatchingSession::SplitRunMetadata(tensorflow::RunMetadata*, tensorflow::serving::Batch<tensorflow::serving::BatchingSessionTask>*)':
tensorflow_serving/batching/batching_session.cc:554:59: error: 'const class tensorflow::CostGraphDef' has no member named 'cost_size'; did you mean 'node_size'?
       for (size_t i = 0; i < batch_metadata->cost_graph().cost_size(); ++i) {
                                                           ^~~~~~~~~
                                                           node_size
tensorflow_serving/batching/batching_session.cc:555:9: error: 'CostGraphDef_AggregatedCost' was not declared in this scope
         CostGraphDef_AggregatedCost* cost =
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
tensorflow_serving/batching/batching_session.cc:555:9: note: suggested alternative: 'CostGraphDef_Node'
         CostGraphDef_AggregatedCost* cost =
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
         CostGraphDef_Node
tensorflow_serving/batching/batching_session.cc:555:38: error: 'cost' was not declared in this scope
         CostGraphDef_AggregatedCost* cost =
                                      ^~~~
tensorflow_serving/batching/batching_session.cc:555:38: note: suggested alternative: 'cosl'
         CostGraphDef_AggregatedCost* cost =
                                      ^~~~
                                      cosl
tensorflow_serving/batching/batching_session.cc:556:51: error: 'class tensorflow::CostGraphDef' has no member named 'mutable_cost'; did you mean 'mutable_node'?
             batch_metadata->mutable_cost_graph()->mutable_cost(i);
                                                   ^~~~~~~~~~~~
                                                   mutable_node
tensorflow_serving/batching/batching_session.cc:562:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < batch->num_tasks(); ++i) {
                        ~~^~~~~~~~~~~~~~~~~~~~
Target //tensorflow_serving/model_servers:tensorflow_model_server failed to build
INFO: Elapsed time: 4369.632s, Critical Path: 2543.42s
INFO: 4467 processes: 4467 local.
FAILED: Build did NOT complete successfully
The command '/bin/sh -c bazel build --color=yes --curses=yes     ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS}     tensorflow_serving/model_servers:tensorflow_model_server &&     cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server     /usr/local/bin/' returned a non-zero code: 1

**Comment by gowthamkpr** [comment]
Can I know `on what platform you are trying to build this?
Also can I get exact steps to reproduce this issue? Thanks!

**Comment by yuxuan2015** [comment]
System：ubuntu16.04  64
Docker version：18.09.7
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609


Execute the following command：
docker build --pull -t $USRE/tensorflow-serving-devel -f tensorflow_serving/tools/docker/Dockerfile.devel .

**Comment by yuxuan2015** [comment]
Modified the parameters of TF_SERVING_BUILD_OPTIONS
change
ARG TF_SERVING_BUILD_OPTIONS="--config=nativeopt"
to
ARG TF_SERVING_BUILD_OPTIONS="--copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.1 --copt=-msse4.2 --local_resources=16384,2.0,1.0"，I successed.
