### ISSUE TITLE
Structured logging support

### ISSUE THREAD

**Issue by cep21** [tensorflow/serving#1575]
### Describe the problem the feature is intended to solve

We monitor all of our production systems with a unified logging framework.  This framework assumes structured, \n delimited log messages in JSON format.  We use DataDog, but similar logging systems for AWS and GCP also assume and work best with \n delimited JSON logs.  This allows us to easily correlate issues between requests across our microservice architecture.

The tensorflow/serving docker image we are using outputs many smaller log lines without consolidating them into a single \n line and without extra information, which increases our billing (we are billed per \n line) and makes it difficult to correlate lines across requests.

### Describe the solution
Allow JSON delimited, line consolidated log output.

### Describe alternatives you've considered
We have tried changing the verbosity, but things like request headers appear dangling in our output.

**Comment by minglotus-6** [comment]
To clarify about the feature request, this is about **structured locking in docker image output**, not **structured logging in TF serving**. Could you confirm?

If that's the case, could you point out related lines in TF serving docker image, and give examples (preferably real-world noisy logs) where changing verbosity helps, and where it doesn't help so log sink ends up with dangling request headers?

**Comment by minglotus-6** [comment]
As stated, could you give examples (preferably real-world noisy logs) where changing verbosity helps, and where it doesn't help so log sink ends up with dangling request headers?

**Comment by cep21** [comment]
> where it doesn't help so log sink ends up with dangling request headers

I later discovered my comment was related to #789 and I fixed it with that ticket's advice.  I no longer have dangling request headers.

**Comment by minglotus-6** [comment]
Thanks for the update. I'll close this one since there is no longer dangling request header issues.
