### ISSUE TITLE
error adding additional feature

### ISSUE THREAD

**Issue by Arnold1** [tensorflow/serving#1577]
Hi,

-----------------------
## Feature Request
If this is a feature request, please fill out the following form in full:

### Describe the problem the feature is intended to solve
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

my tfs model uses 10 features, but my grpc request sends 10 features + 1 additional feature (dummy) --> tf serving fails with the following error:
```
{
   "error":"Failed to process element: 0 key: dummy of \\'instances\\' list. Error: Invalid argument: JSON object: does not have named input: dummy"
}
```

error is generated here:
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/util/json_tensor.cc#L532-L575

I could change the code myself and remap the tensors? I want to only use the 10 features which the model requires and ignore the additional feature.

the question I have: why is Tensorflow serving returning an error and not a warning?

### Describe the solution
Can Tensorflow serving somehow ignore features which are not used in the model, run the inference with the features the model needs and not return an error?

### Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've
considered.

## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04
- **TensorFlow Serving installed from (source or binary)**: source
- **TensorFlow Serving version**: TensorFlow Serving 2.1.0

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in
TensorFlow Serving.

### Exact Steps to Reproduce
Please include all steps necessary for someone to reproduce this issue on their
own machine. If not, skip this section.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached. Try to provide a reproducible test case that is the bare
minimum necessary to generate the problem.

**Comment by rmothukuru** [comment]
Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by rmothukuru** [comment]
@Arnold1,
Can you please provide the information asked in the comment above. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
