### ISSUE TITLE
is there any way to build static library and header for Tensorflow-serving client （using c++）？

### ISSUE THREAD

**Issue by ChinaChenp** [tensorflow/serving#1578]
I am write a gRPC client which written in C++ and can run with the inception serving demo.

I use this demo `https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/resnet_client.cc`

but I encountered two problems：
- I use this commd `bazel build //tensorflow:libtensorflow_cc.so`, But only provides dynamic libraries, I can't use bazel to build my project, all my old libraries are static library.
- Is there any way to build all the header files(include all proto file) and static libraries, what I mean is like `include/   lib/`

**Comment by gowthamkpr** [comment]
@ChinaChenp This issue can be posted on tensorflow repo itself as you are trying to build tensorflow.

**Comment by gowthamkpr** [comment]
@ChinaChenp Can you please respond t the above comment so that we can take the discussion forward. Thanks!

**Comment by ChinaChenp** [comment]
I'm very sorry, my purpose is very simple. I hope the official can provide a C++ static library and header files (including proto header files). just like other open source libraries, You can finally generate 2 dependency directories (include/ lib/) through make && make install, Then I can use it directly in my c ++ tensorflow-serving client project.

> @ChinaChenp Can you please respond t the above comment so that we can take the discussion forward. Thanks!

https://github.com/tensorflow/serving/issues/1578#issuecomment-606885766

> @ChinaChenp Can you please respond t the above comment so that we can take the discussion forward. Thanks!



> @ChinaChenp Can you please respond t the above comment so that we can take the discussion forward. Thanks!



> @ChinaChenp Can you please respond t the above comment so that we can take the discussion forward. Thanks!

**Comment by ChinaChenp** [comment]
@gowthamkpr I'm very sorry, my purpose is very simple. I hope the official can provide a C++ static library and header files (including proto header files). just like other open source libraries, You can finally generate 2 dependency directories (include/ lib/) through make && make install, Then I can use it directly in my c ++ tensorflow-serving client project.

**Comment by shadowdragon89** [comment]
I am not sure if you need to build tensorflow:libtensorflow_cc.so to have a client library.
Could you clarify what block you from having a client library following the example?

For the interface provided by tensorflow serving, a client library will be language specific, so we think GRPC will be a more general interface for users.

**Comment by gowthamkpr** [comment]
@ChinaChenp Can you respond to the above comment so that we can take the discussion further. Thanks!

**Comment by lubolaiye** [comment]
> @ChinaChenp Can you respond to the above comment so that we can take the discussion further. Thanks!

I ran into the same problem, and I solved it through this solution ，https://zhuanlan.zhihu.com/p/41505082

**Comment by 372046933** [comment]
FYI.
`bazel build --jobs=2 -c opt --copt=-msse --copt=-msse4.1 --copt=-msse4.2 --copt=-mfma --copt=-mavx --copt=-mavx2 --copt=-fopenmp --linkopt=-fopenmp --linkopt=-static tensorflow_serving/model_servers/tensorflow_model_server`
