### ISSUE TITLE
Basic and Serving Advanced documented client commands fail without tensorflow/serving:1.14.0-devel

### ISSUE THREAD

**Issue by smartinumcp** [tensorflow/serving#1580]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04.1-Ubuntu SMP
- **TensorFlow Serving installed from (source or binary)**: Docker 19.03.06
- **TensorFlow Serving version**: 
TensorFlow ModelServer: 2.1.0-rc1
TensorFlow Library: 2.1.0

### Describe the problem
Following the directions at https://www.tensorflow.org/tfx/serving/serving_basic and https://www.tensorflow.org/tfx/serving/serving_advanced.  None of the tools/run_in_docker.sh commands work without adding in "-d tensorflow/serving:1.14.0-devel".  Multiple issues are listed as closed for this but it's still failing.  Would expect documentation that lists that if this doesn't work.

### Exact Steps to Reproduce
See the below commands within this environment.

### Source code / logs
Example steps

$git clone https://github.com/tensorflow/serving.git
Cloning into 'serving'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 20505 (delta 32), reused 60 (delta 6), pack-reused 20419
Receiving objects: 100% (20505/20505), 5.93 MiB | 11.05 MiB/s, done.
Resolving deltas: 100% (15521/15521), done.
$cd serving
**$tools/run_in_docker.sh python tensorflow_serving/example/mnist_saved_model.py   /tmp/mnist2**
== Pulling docker image: tensorflow/serving:nightly-devel
nightly-devel: Pulling from tensorflow/serving
Digest: sha256:c6d5380383e6b35427e12114763dc385161ef31ce4f144e0c8cca1e628a4d5f0
Status: Image is up to date for tensorflow/serving:nightly-devel
docker.io/tensorflow/serving:nightly-devel
== Running cmd: sh -c 'cd /tmp/serving; python tensorflow_serving/example/mnist_saved_model.py /tmp/mnist2'
Traceback (most recent call last):
  File "tensorflow_serving/example/mnist_saved_model.py", line 35, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
**$tools/run_in_docker.sh  -d tensorflow/serving:1.14.0-devel python tensorflow_serving/example/mnist_saved_model.py   /tmp/mnist2**
== Pulling docker image: tensorflow/serving:1.14.0-devel
1.14.0-devel: Pulling from tensorflow/serving
Digest: sha256:aaffc38717eaaec7b0178b0657bb14030182701af33409a9a9cad6f72415ba8f
Status: Image is up to date for tensorflow/serving:1.14.0-devel
docker.io/tensorflow/serving:1.14.0-devel
== Running cmd: sh -c 'cd /tmp/serving; python tensorflow_serving/example/mnist_saved_model.py /tmp/mnist2'
Training model...
Extracting /tmp/train-images-idx3-ubyte.gz
Extracting /tmp/train-labels-idx1-ubyte.gz
Extracting /tmp/t10k-images-idx3-ubyte.gz
Extracting /tmp/t10k-labels-idx1-ubyte.gz
2020-03-22 02:25:47.344331: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-22 02:25:47.366620: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz
2020-03-22 02:25:47.367009: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562d7d018c00 executing computations on platform Host. Devices:
2020-03-22 02:25:47.367026: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-03-22 02:25:47.380663: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
training accuracy 0.9092
Done training!
Exporting trained model to /tmp/mnist2/1
W0322 02:25:48.011045 140542598219584 deprecation.py:323] From tensorflow_serving/example/mnist_saved_model.py:110: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
I0322 02:25:48.012181 140542598219584 builder_impl.py:636] No assets to save.
I0322 02:25:48.012269 140542598219584 builder_impl.py:456] No assets to write.
I0322 02:25:48.038841 140542598219584 builder_impl.py:421] SavedModel written to: /tmp/mnist2/1/saved_model.pb
Done exporting!

**Comment by gowthamkpr** [comment]
@smartinumcp Can  you please try it with tensorflow==1.15 and let me know if it resolves the issue. Thanks!

**Comment by misterpeddy** [comment]
This was fixed in fb3c70dc8a44720df870d733f885f6a29e5b6a88
