### ISSUE TITLE
How to record HTTP/REST API call logs?

### ISSUE THREAD

**Issue by seafire1991** [tensorflow/serving#1582]
`2020-03-24 07:18:06.077987: I tensorflow_serving/model_servers/server.cc:358] Running gRPC ModelServer at 0.0.0.0:8500 ...
[warn] getaddrinfo: address family for nodename not supported
2020-03-24 07:18:06.078817: I tensorflow_serving/model_servers/server.cc:378] Exporting HTTP/REST API at:localhost:8501 ...`
How to record users's calling logs without launching another service?Thanks.

**Comment by gowthamkpr** [comment]
@seafire1991 Please take a look at this [issue](https://stackoverflow.com/questions/38073432/how-to-suppress-verbose-tensorflow-logging) and let me know if it helps

**Comment by seafire1991** [comment]
Finally I launch another web api service to record users's calling logs,Thanks all the same!

**Comment by seafire1991** [comment]
> @seafire1991 Please take a look at this [issue](https://stackoverflow.com/questions/38073432/how-to-suppress-verbose-tensorflow-logging) and let me know if it helps
Finally I launch another web api service to record users's calling logs,Thanks all the same!

**Comment by gowthamkpr** [comment]
Thanks @seafire1991 Please close this issue as it has been resolved. Thanks!
