### ISSUE TITLE
enable_batching not working

### ISSUE THREAD

**Issue by whatdhack** [tensorflow/serving#1587]
## Bug Report
Using the following command line to enable  batching.  

```
 tensorflow_model_server --enable_batching --port=8500 --rest_api_port=8501 --model_name=model --model_base_path=/models/model
```

Returns the following to the client ( Rest API) 

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://ipxxxxxxxxxxxxx:8501/v1/models/model:predict
```

Works fine if I  remove the --enable_batching.    Does batching require any change on the client side - that will be  bad. 

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:16.04
- **TensorFlow Serving installed from (source or binary)**: docker 
- **TensorFlow Serving version**:1.15

### Describe the problem
see above

### Exact Steps to Reproduce
see above

### Source code / logs
N/A

**Comment by gowthamkpr** [comment]
Can you please share the exact steps used to reproduce this issue? 
Also can you please share the signaturedef of your model with the serving client code. Thanks!

**Comment by whatdhack** [comment]
The signaturedef follows.

```
signature_def['predict']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['image:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, 3)
        name: image:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output/boxes:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 4)
        name: output/boxes:0
    outputs['output/labels:0'] tensor_info:
        dtype: DT_INT64
        shape: (-1)
        name: output/labels:0
    outputs['output/scores:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: output/scores:0
  Method name is: tensorflow/serving/predict

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['image:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, 3)
        name: image:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output/boxes:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 4)
        name: output/boxes:0
    outputs['output/labels:0'] tensor_info:
        dtype: DT_INT64
        shape: (-1)
        name: output/labels:0
    outputs['output/scores:0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: output/scores:0
  Method name is: tensorflow/serving/predict
```
The batch dim is missing from input ? Could that be a reason ?

**Comment by roshanzameer** [comment]
@whatdhack  

> The batch dim is missing from input ? Could that be a reason ?


What is 'batch dim'?

**Comment by gowthamkpr** [comment]
@whatdhack Can I see your client code?

**Comment by whatdhack** [comment]
The model  input does not have a batch dimension  - no batch in shape: (-1, -1, 3).

**Comment by gowthamkpr** [comment]
@whatdhack Please provide us steps to reproduce this issue. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been awaiting response for more than 3 weeks. Please add additional comments for us to open this issue again. Thanks!
