### ISSUE TITLE
Performance issue with tf serving QPS and client latency on float16 NWHC data

### ISSUE THREAD

**Issue by ganler** [tensorflow/serving#1589]
### Performance issue with tf serving QPS and client latency on float16 NWHC data

Hi. Recently I was profiling the performance of tf serving and the gRPC client of tf serving API. And I got some really strange data points.

All the models I discussed are ResNet models with different input shapes and data types.

1. **[gRPC Client + Bad Latency + NHWC DT_HALF]**:  75% Client time was used in serialization and memcpy for the input. This problem is not found in other data types(like FP32).

2. **[TF Serving + Bad QPS + NHWC]**: I found that the same model with different data types will produce dramatically different QPS results. Using models [here](https://github.com/tensorflow/models/tree/master/official/r1/resnet#pre-trained-model), I got 75 QPS using the NHWC model with FP16 input and 230 QPS using NCHW model with FP32 on the P4 machine. And I also found that tf serving's performance is very bad on my other NHWC models(BYTE Input). And I understand that NHWC is less efficient than NCHW on GPUs. But I got 400 FPS using TensorFlow alone(batchsize = 32). 75 QPS is quite confusing. (Maybe an issue with protobuf?)

#### Server

Here's my batching config:

```protoc
max_batch_size { value: 32 }
batch_timeout_micros { value: 5000 }
max_enqueued_batches { value: 1024 }
num_batch_threads { value: 32 }
```

My server flags:

```shell
tensorflow_model_server --model_config_file=resnet50_tf.config --rest_api_port=8501 --grpc_channel_arguments=grpc.max_concurrent_streams=1000 --enable_batching --batching_parameters_file=batching.config
```

#### Client

I test the TF Serving performance using the official client API.

In my testing scenario, I reused the stub and the input tensor_protoc to avoid some overheads. (Cuz I mainly want to test the QPS) 

```python
def _grpc_request_and_run(self, batch_size: int, times=1): 
        request = predict_pb2.PredictRequest()
        request.model_spec.name = self.model_name
        request.model_spec.signature_name = self.signature_name
        for name, data in self._cached_inputs:
            request.inputs[name].CopyFrom(data)
        res = self.stub.Predict(request, 10) 
```

Thanks for your help in advance.

**Comment by ganler** [comment]
Hi, I think I got the answers. The `tf.make_tensor_proto`'s implementation won't put the data into `tensor_content`，but the `repeated half_val`. This is very inefficient. 

So it seems to be a problem with `tf.make_tensor_proto` not tf serving. After I manually set the data into tensor_content, tf serving became great again!

So I think I should go to the tensorflow repo and tell them this issue.

**Comment by leo-XUKANG** [comment]
@ganler 您好，请问您怎么解决的这个问题
是更改这个代码吗：
  if is_same_size and numpy_dtype in _TENSOR_CONTENT_TYPES and shape_size > 1:
    if nparray.size * nparray.itemsize >= (1 << 31):
      raise ValueError(
          "Cannot create a tensor proto whose content is larger than 2GB.")
    tensor_proto.tensor_content = nparray.tostring()
    return tensor_proto

**Comment by ganler** [comment]
@leo-XUKANG Yes, this should work. I also made a PR to tensorflow: https://github.com/tensorflow/tensorflow/pull/38258.

BTW, I suggest we talk in English as GitHub is a global environment. :-)

**Comment by leo-XUKANG** [comment]
@ganler  Thanks
