### ISSUE TITLE
node ParseExample/ParseExampleV2 error 

### ISSUE THREAD

**Issue by kalpa-subbaiah** [tensorflow/serving#1590]
Dear Team,

      
I am trying to use tensorflow serving which is running fine as below:

![image](https://user-images.githubusercontent.com/30182218/78368812-d7647d80-75e1-11ea-92be-6b9963b82353.png)

I am trying to predict on sample data which gives me below error, Looks like I am doing some mistake , can you please help me , it gives me node ParseExample/ParseExampleV2 error.

![image](https://user-images.githubusercontent.com/30182218/78369042-375b2400-75e2-11ea-836e-25909b7b6d80.png)

Best Regards,
Kalpa.

**Comment by gowthamkpr** [comment]
@kalpa-subbaiah I don't think this is an error. Can you give us the exact steps and code to reproduce this issue?

**Comment by kalpa-subbaiah** [comment]
I will try with the link shared here https://github.com/tensorflow/tfx/issues/1584#issuecomment-609983446 , hence this issue can be closed.

**Comment by rothn** [comment]
That link probably works for some TFX models. For my TFX model, which takes a single BYTES input, I needed to use something slightly different:
predictions = model.signatures['predict'](tf.constant(['bytes_list { value: "I am some text" }'], dtype=tf.string))
