### ISSUE TITLE
Recomended docker installation don´t work on CentOS 7 & Intel. No instructions how to install another version or even on how to build.

### ISSUE THREAD

**Issue by IvanBrasilico** [tensorflow/serving#1591]
Installing docker image on CentOS7 with Intel Chipset got the message:

/usr/bin/tf_serving_entrypoint.sh: line 3:     6 Illegal instruction     (core dumped) tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"

Tried to generate another build and got the message:

 sudo docker build -t $USER/tensorflow-serving   --build-arg TF_SERVING_BUILD_IMAGE=$USER/tensorflow-serving-devel   -f tensorflow_serving/tools/docker/Dockerfile .
Sending build context to Docker daemon 10.62 MB
Step 1/18 : ARG TF_SERVING_VERSION=latest
Please provide a source image with `from` prior to commit

$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 44
model name      : Intel(R) Xeon(R) CPU           X5660  @ 2.80GHz
stepping        : 2
microcode       : 0xffffffff
cpu MHz         : 2792.968
cache size      : 12288 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl pni ssse3 cx16 sse4_1 sse4_2 popcnt hypervisor lahf_lm
bogomips        : 5585.93
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

**Comment by gowthamkpr** [comment]
This is similar to the issue [here](https://github.com/tensorflow/serving/issues/1542). It is a well known issue and is being tracked in that issue.
