### ISSUE TITLE
ServerCore only support device_types::kMain type for resource tracker

### ISSUE THREAD

**Issue by sw2921** [tensorflow/serving#1597]
Currently I am trying to use server core for the model management, but from the code, ServerCore only create ResourceTracker with main memory (kMain) support. Do we consider adding the GPU(kGpu) device into resource tracker of ServerCore?  Or do we have some alternatives to support main ram and gpu ram together in resource tracker?

**Comment by netfs** [comment]
i think we should track GPU resource usage under `kGPU` to help differentiate from main. monitoring tools can aggregate (sum/rates etc.) as desired.

**Comment by huijiao1120** [comment]
Has the gpu resource estimator been supported yet? I see a gpu device type is available[ here](https://github.com/tensorflow/serving/blob/7a9209a2bff11888b9acb74cc6bda29ab50ea011/tensorflow_serving/resources/resource_values.cc#L23): 
`const char* const kGpu = "gpu";`
but when I do 
`set_device(tensorflow::serving::device_types::kGpu)`
I get this error:
`tensorflow_serving/resources/ resource _util.cc:116] Invalid argument: Invalid resource allocation: Invalid device gpu`

**Comment by singhniraj08** [comment]
@sw2921,

GPU resource tracker for model server is tracked in `kGpu` as shown [here](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/resources/resource_values.h#L34). Please let us know if this issue can be closed.

@huijiao1120, Please make sure you have installed Tensorflow Serving for GPU and make sure the pre-requisites are met. 

Thank you!
