### ISSUE TITLE
How to record interface log when i using tfs docker

### ISSUE THREAD

**Issue by njustyangkai** [tensorflow/serving#1598]
I use tfs container 2.0.0 to do ctr predict, but I don't know how to record interface log(http restful), can some one help?
I just need to statistics the TPS and the predict result

**Comment by gowthamkpr** [comment]
@njustyangkai Can you please elaborate on what you are trying to accomplish here. Thanks!

**Comment by njustyangkai** [comment]
@gowthamkpr yes, thanks for support. let me describe this demand.
We are now using tensorflow serving restful interface to do ctr predict, the system run good, but we want to log every request to a logFile, and this file can use some rolling policy will be better in case of the storage overflow.
These logFiles like nginx logs, can record the requestInfo like requestTime, elapsedTime, and responseBody etc.
If you pls else question, you can contact, thanks a lot!

**Comment by nrobeR** [comment]
@njustyangkai https://github.com/tensorflow/serving/blob/master/tensorflow_serving/config/model_server_config.proto#L67 allows you configure logging of your requests and response. Let me know if that helps. Thanks.

**Comment by njustyangkai** [comment]
@nrobeR thanks bro, i will try

**Comment by njustyangkai** [comment]
@nrobeR thanks bro, i will try. Do u have refrerence about how to use this param?

**Comment by nrobeR** [comment]
No problem. You can checkout the documentation here: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/config/logging_config.proto

**Comment by nrobeR** [comment]
Closing this per discussions above. Please feel free to re-open if there's some issue with it. Thanks.

**Comment by njustyangkai** [comment]
@nrobeR hi, bro, i still have question about this issue, as you know, i am now using docker tfs to serving, but i don't know which param to set when i startup a container. there are the setup params i can get:

    --port=8500                         
    --grpc_socket_path=""               
    --rest_api_port=0                   
    --rest_api_num_threads=16           
    --rest_api_timeout_in_ms=30000      
    --enable_batching=false             
    --batching_parameters_file=""       
    --model_config_file=""              
    --model_name="default"              
    --model_base_path=""                
    --max_num_load_retries=5            
    --load_retry_interval_micros=60000000
    --file_system_poll_wait_seconds=1   
    --flush_filesystem_caches=true      
    --tensorflow_session_parallelism=0  
    --tensorflow_intra_op_parallelism=0 
    --tensorflow_inter_op_parallelism=0 
    --ssl_config_file=""                
    --platform_config_file=""           
    --per_process_gpu_memory_fraction=0.
    --saved_model_tags="serve"          
    --grpc_channel_arguments=""         
    --enable_model_warmup=true          
    --version=false                     
    --monitoring_config_file=""         

but i don't know which config can i use

**Comment by leo-XUKANG** [comment]
@njustyangkai 你好啊，你需要修改model_config_file，为啥子勒，因为
![image](https://user-images.githubusercontent.com/28701457/86725297-1b8d7100-c05c-11ea-91fc-8ddb4d3cc785.png)
你可以在文件中调整logging的等级，然后使用
model_config_file_poll_wait_seconds参数进行调整，这样不用停掉你的容器也能更新，当然，如果你启动容器的时候没有这两个参数，也是需要停掉容器，重新启动的
