### ISSUE TITLE
[Bug] Single quotes escaped wthin string leads to malformed JSON responses in REST API

### ISSUE THREAD

**Issue by BorisPolonsky** [tensorflow/serving#1600]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **TensorFlow Serving installed from docker (tensorflow/serving:1.12.3-gpu)**:
- **TensorFlow Serving version 1.12.3-gpu**:

### Describe the problem
In REST API responses, single quotes in strings were incorrectly escaped in some cases thus can't be parsed by downstream apps. I would like to suggest that the server either
- remove escape character `"\"` before single quotes `'`, or
- use double quotes instead when applicable (see the responses in  Exact Steps to Reproduce section)

#### Things that will trigger the bug
The following steps will lead to some python downstream app raising exception
(e.g. a  `log_message = json.loads(tf_error.read())["error"]` will trigger `JSONDecodeError` exception) due to malformed strings in returned JSON.
 
- calling REST API with data like `{"signature_name": "serving_default"}`
```
{ "error": "Missing \'inputs\' or \'instances\' key" }
```
- calling REST API with data like `{"signature_name": "no_such_signature"}`
`{ "error": "Missing named input: segment_ids in \'inputs\' object." } `
(calling REST API with some of the named inputs missing`{"signature_name": "predict", "inputs":{}}`)
Something that won't trigger this error:
```
{ "error": "Missing named input: segment_ids in \'inputs\' object." }
```
#### Cases that may trigger the bug (i.e. untested)
- `'` characters in output names for models with multiple outputs.
 
#### Things that won't trigger the bug
```
{ "error": "Serving signature name: \"no_such_name\" not found in signature def" }
```
In this case double quotes were used hence `\"` won't trigger `JSONDecodeError` as it's a valid escape sequences. 
### Source code / logs
Example downstream app
```
import urllib
import urllib.request
import json

request_data = '{"singature_name": "serving_default"}'.encode("utf-8")
url = "http://localhost:8501/v1/models/your_model_name:predict"
request_obj = urllib.request.Request(url, headers={"Content-Type": "application/json"}, data=request_data)
try:
    with urllib.request.urlopen(request_obj, timeout=60) as response:
        content = response.read().decode("utf-8")
except urllib.error.HTTPError as e:
    message =  e.read().decode("utf-8")
    error = json.loads(message)["error"] # Fails when parsing JSON object.
```

**Comment by netfs** [comment]
strings are represented using double quote (") as per [JSON spec](https://tools.ietf.org/html/rfc7159). so any json output that has strings (in errors or otherwise) should be double quoted. and strings that contain double quotes, should be escaped as \\"

**Comment by netfs** [comment]
regarding single quotes, we need to escape them for JSON conformance. python `json` module seem to handle this correctly (and will fail if we do not escape the single quotes): 

```
$ python
>>> import json; json.loads('{ "error": "Missing \'inputs\' or \'instances\' key" }')["error"]
u"Missing 'inputs' or 'instances' key"
>>>
```

**Comment by BorisPolonsky** [comment]
> regarding single quotes, we need to escape them for JSON conformance. python `json` module seem to handle this correctly (and will fail if we do not escape the single quotes):
> 
> ```
> $ python
> >>> import json; json.loads('{ "error": "Missing \'inputs\' or \'instances\' key" }')["error"]
> u"Missing 'inputs' or 'instances' key"
> >>>
> ```

Hello, please try this instead
```
import json
json.loads(r'{ "error": "Missing \'inputs\' or \'instances\' key" }')
```
You'll get
```
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 21 (char 20)
```

**Comment by netfs** [comment]
using `r'...'` (raw) strings will cause problems as escape characters (a valid JSON construct) get interpreted literally. you can probably use `u'...'` if you want.

Quoting from [json.org](https://www.json.org/json-en.html), definition of JSON string is as follows:
> A string is a sequence of zero or more Unicode characters, wrapped in double quotes, using backslash escapes.

**Comment by BorisPolonsky** [comment]
> using `r'...'` (raw) strings will cause problems as escape characters (a valid JSON construct) get interpreted literally. you can probably use `u'...'` if you want.
> 
> Quoting from [json.org](https://www.json.org/json-en.html), definition of JSON string is as follows:
> 
> > A string is a sequence of zero or more Unicode characters, wrapped in double quotes, using backslash escapes.

Hello. Thanks for your reply. But I believe that's exactly what is returned via the `response.read().decode("utf-8")` call in my test code. The slash before the single quote is literally there in the body. 
I believed that the ill-formatted part returned by tensorflow/serving shall be represented as `u"\\'"` (a string of length 2). 
PS:
I don't think this claim suggest that single quotes should be escaped. In your quote from [json.org](https://www.json.org/json-en.html), there's a flow chart for string type. There's no branch for single quotes `'` following the back slash `\` in it.

**Comment by netfs** [comment]
@BorisPolonsky I submitted a fix to correctly escape JSON string to confirm to JSON spec.

If you can help test this from the master branch, that would be highly appreciated. I can then have it cherrypicked in the upcoming TF Serving 2.2 release.

Thanks!
