### ISSUE TITLE
bazel build TFS2.1 cpu version FAILED 

### ISSUE THREAD

**Issue by CreekLou** [tensorflow/serving#1604]
My ENV:

g++ (GCC) 7.2.0

bazel version Build label: 2.2.0

CentOS Linux 3.10.0-693.21.1.std7a.el7.0.x86_64 #1 SMP Mon Apr 9 01:47:10 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

build command

> bazel build --verbose_failures -c opt tensorflow_serving/model_servers:tensorflow_model_server

**ERROR log**
ERROR: /home/work/.cache/bazel/_bazel_work/0833223f9c21beecc46ce1b52a1a0413/external/org_tensorflow/tensorflow/core/kernels/BUILD:349:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:extract_image_patches_op' failed (Exit 1): gcc failed: error executing command 
  (cd /home/work/.cache/bazel/_bazel_work/0833223f9c21beecc46ce1b52a1a0413/execroot/tf_serving && \
  exec env - \
    PATH=/home/work/soft/anaconda3/bin:/home/work/soft/anaconda3/condabin:/usr/local/gcc7/bin:/home/work/soft/infra-client/bin:/usr/java/default/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/lib64/qt-3.3/bin:/usr/bin:/bin:/home/work/opshell:/home/work/opshell:/home/work/opshell:/root/bin:/home/work/opshell:/usr/java/default/bin:/home/work/soft/apache-maven-3.3.9/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
  /usr/local/gcc7/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/extract_image_patches_op/extract_image_patches_op.d '-frandom-seed=bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/extract_image_patches_op/extract_image_patches_op.o' -DTENSORFLOW_USE_CUSTOM_CONTRACTION_KERNEL -DTENSORFLOW_USE_MKLDNN_CONTRACTION_KERNEL -DTF_USE_SNAPPY -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DHAVE_SYS_UIO_H -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote external/org_tensorflow -iquote bazel-out/k8-opt/bin/external/org_tensorflow -iquote external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/k8-opt/bin/external/local_config_sycl -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/mkl_dnn -iquote bazel-out/k8-opt/bin/external/mkl_dnn -iquote external/nsync -iquote bazel-out/k8-opt/bin/external/nsync -iquote external/gif -iquote bazel-out/k8-opt/bin/external/gif -iquote external/libjpeg_turbo -iquote bazel-out/k8-opt/bin/external/libjpeg_turbo -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-opt/bin/external/zlib -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/k8-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/bin/external/highwayhash -iquote external/double_conversion -iquote bazel-out/k8-opt/bin/external/double_conversion -iquote external/snappy -iquote bazel-out/k8-opt/bin/external/snappy -isystem external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/mkl_dnn/include -isystem bazel-out/k8-opt/bin/external/mkl_dnn/include -isystem external/mkl_dnn/src -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src -isystem external/mkl_dnn/src/common -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/common -isystem external/mkl_dnn/src/cpu -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu -isystem external/mkl_dnn/src/cpu/gemm -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu/gemm -isystem external/mkl_dnn/src/cpu/xbyak -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu/xbyak -isystem external/nsync/public -isystem bazel-out/k8-opt/bin/external/nsync/public -isystem external/gif -isystem bazel-out/k8-opt/bin/external/gif -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/k8-opt/bin/external/zlib -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/bin/external/farmhash_archive/src -isystem external/double_conversion -isystem bazel-out/k8-opt/bin/external/double_conversion '-std=c++14' '-D_GLIBCXX_USE_CXX11_ABI=0' -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare '-ftemplate-depth=900' -fno-exceptions -msse3 -DTENSORFLOW_MONOLITHIC_BUILD -pthread -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/org_tensorflow/tensorflow/core/kernels/extract_image_patches_op.cc -o bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/extract_image_patches_op/extract_image_patches_op.o)
Execution platform: @local_config_platform//:host
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:117:0,
                 from external/org_tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from external/org_tensorflow/tensorflow/core/kernels/extract_image_patches_op.h:19,
                 from external/org_tensorflow/tensorflow/core/kernels/extract_image_patches_op.cc:21:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorImagePatch.h: In static member function 'static void Eigen::internal::EvalRange<Evaluator, StorageIndex, true>::run(Evaluator*, StorageIndex, StorageIndex) [with Evaluator = Eigen::TensorEvaluator<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 4, 1, int>, 16, Eigen::MakePointer>, const Eigen::TensorReshapingOp<const Eigen::DSizes<int, 4>, const Eigen::TensorImagePatchOp<-1, -1, const Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 4, 1, int>, 16, Eigen::MakePointer> > > >, Eigen::ThreadPoolDevice>; StorageIndex = int]':
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorImagePatch.h:546:7: internal compiler error: in emit_move_insn, at expr.c:3698
       values[i] = coeff(index+i);
       ^~~~~~
0x85b1ba emit_move_insn(rtx_def*, rtx_def*)
	../../gcc/expr.c:3697
0x84b5ad store_bit_field_1
	../../gcc/expmed.c:814
0x84bc18 store_bit_field(rtx_def*, unsigned long, unsigned long, unsigned long, unsigned long, machine_mode, rtx_def*, bool)
	../../gcc/expmed.c:1122
0x865a5e store_field
	../../gcc/expr.c:6918
0x86311b expand_assignment(tree_node*, tree_node*, bool)
	../../gcc/expr.c:5169
0x774d91 expand_call_stmt
	../../gcc/cfgexpand.c:2656
0x774d91 expand_gimple_stmt_1
	../../gcc/cfgexpand.c:3571
0x774d91 expand_gimple_stmt
	../../gcc/cfgexpand.c:3737
0x775f6f expand_gimple_basic_block
	../../gcc/cfgexpand.c:5744
0x77b0d6 execute
	../../gcc/cfgexpand.c:6357
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
Target //tensorflow_serving/model_servers:tensorflow_model_server failed to build

**Comment by wdirons** [comment]
This is the same issue as https://github.com/tensorflow/tensorflow/issues/25323, using a newer version of gcc will help, or try other suggestions in that issue.

**Comment by gowthamkpr** [comment]
@CreekLou As mentioned above comment this issue is due to GCC not Tensorfow or Tensorflow Serving.  As mentioned [here](https://github.com/tensorflow/tensorflow/issues/25323#issuecomment-491460634) please try using the later version of GCC 7 or GCC 8 to solve this issue. IF you have more questions please post it in GCC related github repo. Thanks!
