### ISSUE TITLE
Deploy Sequence to Sequence model with Tensorflow Serving

### ISSUE THREAD

**Issue by psyfb2** [tensorflow/serving#1607]
I have created a seq2seq model for question and answering by following the tensorflow tutorial here: https://www.tensorflow.org/tutorials/text/nmt_with_attention

The model works well and I want to deploy it with Tensorflow serving. it's not clear how I could do this efficiently because:
- The decoder can only make a prediction for the next word, by taking as input the last predicted word. Surely it's not efficient to send multiple inference requests word by word instead of generating the whole sentence server side?
- is there any way to do the preprocessing server side? (e.g. client only has to send the tensorflow serving text, instead of numpy arrays).

**Comment by JakeTheWise** [comment]
- Could you construct an appropriate tf.function and export it as a model signature that contains the necessary logic to iterate over tokens + predictions? This signature would be loaded by tf-serving and would run for every inference request.
- Have you heard of tensorflow extended? This project creates and fuses a preprocessing graph onto your main tensorflow graph. This would allow you to send raw text to the model and let the preprocessing happen server-side.

**Comment by psyfb2** [comment]
> * Could you construct an appropriate tf.function and export it as a model signature that contains the necessary logic to iterate over tokens + predictions? This signature would be loaded by tf-serving and would run for every inference request.
> * Have you heard of tensorflow transform? This project creates and fuses a preprocessing graph onto your main tensorflow graph. This would allow you to send raw text to the model and let the preprocessing happen server-side.

Oh I have a python function to handle the logic for sentence level predictions. Is this as simple as annotating the function with @tf.function, but then how to export it?
And thanks I wasn't aware of tensorflow transform

**Comment by JakeTheWise** [comment]
For exporting signatures, have you read this documentation? https://www.tensorflow.org/api_docs/python/tf/saved_model/save

**Comment by psyfb2** [comment]
Oh I see, thanks for clarifying.
