### ISSUE TITLE
Unable to get model metadata in TF Serving 2.2.0-rc1

### ISSUE THREAD

**Issue by deliahu** [tensorflow/serving#1612]
### System information
Docker Hub image `tensorflow/serving:2.2.0-rc1` (running on OSX)

### Describe the problem
I have been successfully using [tensorflow-serving-api](https://pypi.org/project/tensorflow-serving-api/) to query the `GetModelMetadata` gRPC API in version 2.1.0 (and before). However, with `2.2.0-rc1`, something seems to be breaking.

### Exact Steps to Reproduce
1\. Deploy a model using the `tensorflow/serving:2.2.0-rc1` Docker Hub image, e.g. following the [tutorial](https://www.tensorflow.org/tfx/serving/docker) (I only modified the image version and the port):

```bash
git clone https://github.com/tensorflow/serving

TESTDATA="$(pwd)/serving/tensorflow_serving/servables/tensorflow/testdata"

docker run -t --rm -p 8500:8500 \
    -v "$TESTDATA/saved_model_half_plus_two_cpu:/models/half_plus_two" \
    -e MODEL_NAME=half_plus_two \
    tensorflow/serving:2.2.0-rc1 &
```

2\. `pip3 install tensorflow-serving-api==2.2.0rc1`

3\. Run this Python code:

```python
import grpc
from tensorflow_serving.apis import prediction_service_pb2_grpc
from tensorflow_serving.apis import get_model_metadata_pb2

channel = grpc.insecure_channel("localhost:8500")
stub = prediction_service_pb2_grpc.PredictionServiceStub(channel)

get_model_metadata_request = get_model_metadata_pb2.GetModelMetadataRequest()
get_model_metadata_request.model_spec.name = "half_plus_two"
get_model_metadata_request.metadata_field.append("signature_def")

resp = stub.GetModelMetadata(get_model_metadata_request)
print(resp)
```

**Output**

```text
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    resp = stub.GetModelMetadata(get_model_metadata_request, timeout=10.0)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "GetModelMetadata API is only available when use_saved_model is set to true"
	debug_error_string = "{"created":"@1587960387.410246939","description":"Error received from peer ipv6:[::1]:8500","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"GetModelMetadata API is only available when use_saved_model is set to true","grpc_status":3}"
```

I tried updating the `tensorflow_model_server` command (in `/usr/bin/tf_serving_entrypoint.sh` in the docker image) to include `--use_saved_model=true`, but that did not help.

**Output when running the same steps, but with `tensorflow-serving-api==2.1.0` and `    tensorflow/serving:2.1.0`**

```text
model_spec {
  name: "half_plus_two"
  version {
    value: 123
  }
}
metadata {
  key: "signature_def"
  value {
    type_url: "type.googleapis.com/tensorflow.serving.SignatureDefMap"
    value: "<omitted for brevity>"
  }
}
```

Is this the recommended way to call the metadata API from Python? Has the API changed?

**Comment by deliahu** [comment]
@gowthamkpr @amahendrakar I just wanted to follow up, have you been able to identify the issue?

**Comment by christisg** [comment]
Thank you for reporting the issue. We'll work on fixing it for TF serving 2.2.0 release.

**Comment by christisg** [comment]
This got broken by [this commit](https://github.com/tensorflow/serving/commit/2090d67f4e5e8ee5aa7faf8437bea096a438450a)
