### ISSUE TITLE
Problems scaling on Kubernetes?

### ISSUE THREAD

**Issue by pselden** [tensorflow/serving#1618]
I have smallish model that I've tuned on Kubernetes to maximize performance for a single instance based on the performance guide.

I ended up with the following setup, which gives me around 1000 requests per second at around 10ms response time for the 99th percentile. My goal is to keep p99 response time below 10ms and get as many requests per second as possible per CPU.

Because there was no shared state, I assumed I could scale horizontally and be able to get 1000 QPS per instance. However when I tried it, performance is drastically decreased and I need to set it to around 700QPS to still maintain that 99th percentile response time.

Running in Google Kubernetes Engine using n2-highcpu-32 machines.

```
communicating over grpc (using GRPC client side load balancer to evenly distribute connections)
batch_timeout_micros: 500
max_batch_size: 4
num_batch_threads: 4
max_enqueued_batches: 0

tensorflow_intra_op_parallelism: 4
tensorflow_inter_op_parallelism: 4

Requests/Limits:
CPUs: 4
Memory: 4Gi
```

If I try to maintain the 1000 requests per second per pod on more than one pod, latency shoots up to >15ms

I realized that when i scaled to 4 pods, 3 of them ended up on the same node, and one on another by itself other. When I broke it down by performance per pod, the one by itself was doing MUCH better than the 3 on the same.

That makes me think there is some sort of CPU or threading contention, even though I specified limits...

**Comment by netfs** [comment]
from TF serving perspective, each pod is independent. and TF serving is oblivious to other pods.

so in theory, if one pod gives you X qps, i'd expect N pods (same sized) to give N*X qps, like one would expect if these were bare-metal machines. so clearly there are isolation issues with kubernetes setup -- something i do not think TF serving can help here.

i ran a simple gprc test on my desktop with latest TF serving docker image, with docker given access to 4 (host) cores in one setup and 12 (host) cores in another, and the first setup did X qps, and the second setup did close to 3*X qps (given that we have 3x the cores) -- at same (~60% utilization) and same latency curves. so clearly TF serving is able to scale out with more cores.

**Comment by shadowdragon89** [comment]
As suggested, it doesn't sound like a TF Serving issue. Instead, you may want to consult kubernetes Engine for how to get better isolation among different pods.
