### ISSUE TITLE
tensorflow protobuf problem about:A protocol message was rejected because it was too big (more than 67108864 bytes)

### ISSUE THREAD

**Issue by haibarasiao** [tensorflow/serving#162]
When trying distributed tensorflow(my tensorflow was installed by pip), I get the error:A protocol message was rejected because it was too big (more than 67108864 bytes),and I read the solution on #582,then pip uninstall protobuf and download the source of protobuf from "https://github.com/google/protobuf/releases/download/v3.0.0-beta-2/protobuf-python-3.0.0-beta-2.tar.gz",changed 64 << 20 to 256 << 20,and then install it with "READme",
but it didn't work.Then I followed the solution in #2046 by @VDalibard ,but the same problem happened.
Then I set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python and reInstalled ,by not worked too. I think the tensorflow hasn't used the new protobuf ,but I don't know how to deal with it.
Could anyone help me( •̥́ ˍ •̀ू ), I am going to mad about this issue...:(

**Comment by kirilg** [comment]
Is this a problem you're seeing in TensorFlow alone or when running TensorFlow Serving? If serving, could you please include what commands you were trying?

**Comment by haibarasiao** [comment]
@kirilg
This happened when I try to run a distribute tensorflow,first I start the ps server,then I run a worker node waiting for the chief node, after I run the chief node, I got this problem, any ideas?

**Comment by kirilg** [comment]
I suggest you file an issue in the [TensorFlow repo](https://github.com/tensorflow/tensorflow) and see if they have any ideas. I believe similar problems were encountered in the past so they'll probably have some suggestions. I'll close this bug since it doesn't seem Serving related, but feel free to reopen if you also observe it here.

**Comment by huyong1109** [comment]
After changing from 64 << 20 to 256 << 20 (you should find the code_stream.h file in ~/.cache/bazel/ if install from source), do you still get the same error "more than 67108864 bytes"? The error should change to "more than 268435456 bytes" if your installation succeed! By this way, it mean that the message between ps and worker are larger than 256M. You would change to 1024<<20, or even bigger. (should smaller than 2048<<20 )
If not, you did not install tensorflow successfully.
