### ISSUE TITLE
GRPC metrics are not collected/exported

### ISSUE THREAD

**Issue by pselden** [tensorflow/serving#1624]
### Describe the problem the feature is intended to solve
When prometheus monitoring is enabled, you get lots of nice stats like graph runtime, loads, etc, that is exported by Tensorflow core, and it looks like if you use HTTP you also will get some useful metrics there. However this does not appear to be implemented for GRPC.

Metrics for the following would be useful for monitoring.

- number of GRPC requests
- GRPC response latency histogram

**Comment by pselden** [comment]
This might be fixed by #1623, but that looks to be specific to the model runtime and not end-to-end request/response times.

**Comment by geraldstanje** [comment]
is it possible to provide metrics to tune the batching?

**Comment by shkwsk** [comment]
@pselden 
> This might be fixed by #1623, but that looks to be specific to the model runtime and not end-to-end request/response times.

#1623 addresses the end-to-end request/response time for Predict method in gRPC API.

**Comment by netfs** [comment]
can we close this issue, and continue discussion on #1623 -- to get all needs addressed.
