### ISSUE TITLE
Load two servables at the same time

### ISSUE THREAD

**Issue by pingfaichan** [tensorflow/serving#163]
May I know if there is a way to make sure that two servables to be loaded at the same time? They belong to the same trained model. One is a hashmap one is a tensorflow graph. Thanks!

**Comment by pingfaichan** [comment]
Just came up with an idea:
1. Put the graph from mnist_export and the hashmap CSV file in the same folder
2. Load the tensorflow servable just like the way in the tutorial
3. Get the servableid of the loaded tensorflow servable
4. Using that servableid, get the servable for the hashmap

**Comment by kirilg** [comment]
It's possible to load multiple models and multiple different Servable types, though we don't have examples of the latter. For multiple models, you can look at [this discussion](https://github.com/tensorflow/serving/issues/45). For different Servable types, unfortunately right now both the [model_server](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc) and the [inception example](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_inference.cc) are limited to TensorFlow servables, but you could have a modified version that uses any other type as well (e.g. Hashmap). When you call `manager_->GetServableHandle`, you'll get a `ServableHandle` to a different type. It may be helpful to look at the [custom servable](https://tensorflow.github.io/serving/custom_servable) documentation and the hashmap example there.
