### ISSUE TITLE
Serving Docker memory usage is growing constantly 

### ISSUE THREAD

**Issue by aniketmaurya** [tensorflow/serving#1631]
System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **TensorFlow Serving installed from (docker:- tensorflow/serving:latest-gpu)**:

Docker memory usage is growing constantly (every time I hit TF serving for inference).

Following is my docker configs:

```
docker run  --gpus all -p 8501:8501 -p 8500:8500 \
        --mount type=bind,source=$MODEL_ROOT_PATH/text_check,target=/models/model_name \
        --mount type=bind,source=$MODEL_CONFIG_PATH,target=/models/model_config.config \
        -t tensorflow/serving:latest-gpu \
        --enable_batching=true \
        --model_config_file=/models/model_config.config \
        > logs/docker.log &
```

**Comment by gowthamkpr** [comment]
@aniketmaurya What version of tensorflow and tensorflow serving are you using. Also can you give us the system details? 
Also specify all the steps inorder for us to reproduce the issue. Thanks!

**Comment by aniketmaurya** [comment]
I'm using tensorflow 2.1.0 and tf serving docker 2.1.0 version as well.

GPU Spec: Tesla T4 - 14 GB, with CUDA 10.1

**Comment by aniketmaurya** [comment]
> I'm using tensorflow 2.1.0 and tf serving docker 2.1.0 version as well.
> 
> GPU Spec: Tesla T4 - 14 GB, with CUDA 10.1

https://github.com/tensorflow/serving/issues/1215

**Comment by christisg** [comment]
Hello @aniketmaurya,
Since it looks like you enable request batching, I'd recommend going over
github.com/tensorflow/serving/blob/master/tensorflow_serving/batching/README.md and trying different values for some of the parameters which might trigger memory growth, specifically max_batch_size, num_batch_threads and max_enqueued_batches.

**Comment by aniketmaurya** [comment]
Hi @christisg 
I followed the guide **github.com/tensorflow/serving/blob/master/tensorflow_serving/batching/README.md**  and tried different batch configs but still facing memory growth problem.

**Comment by christisg** [comment]
Hello @aniketmaurya,

In addition to the batching options have you tried experimenting with lowering the QPS? Is the memory growth still happening for lower QPS?
We'd need the model and the requests to be able to reproduce.

Thanks

**Comment by gowthamkpr** [comment]
@aniketmaurya Can you please respond to the above comment so that we can take the discussion further. Thanks!

**Comment by aniketmaurya** [comment]
> Hello @aniketmaurya,
> 
> In addition to the batching options have you tried experimenting with lowering the QPS? Is the memory growth still happening for lower QPS?
> We'd need the model and the requests to be able to reproduce.
> 
> Thanks

I'm not in a position to provide the model. I've tried both with batching enabled and without batching. When I increase decrease the max queue size then the memory growth happens at a slow rate but still at some time all the RAM is consumed.

**Comment by christisg** [comment]
Hi @aniketmaurya, 

Have you observed memory growth with lower QPS to the model?

**Comment by aniketmaurya** [comment]
yes, I have observed this problem with lower QPS a well

**Comment by duhuajiang** [comment]
i face the same problem，with low qps，the **cpu usage** sharply increase，sametime，the **memory usage** also sharply increase. 

**client：** java，grpc call tensorflow serving，use tensorflow serving api

**Comment by NasimSulaiman** [comment]
Hi @aniketmaurya ,
I am facing the same issue, with multiple concurrent requests to model server for prediction . Did you find any solution to this issue?

**Comment by christisg** [comment]
Would it be possible to provide a model and a set of requests that could be used to reproduce the issue?

**Comment by XBWGC** [comment]
Hi, @NasimSulaiman :
Did you find any solution to this issue ?

**Comment by rudi-mac** [comment]
Hi, I am also facing memory growth problem with tensorflow serving in docker container. Classifying images with custom model and after about 30 classifications I get a warning log: 

W external/org_tensorflow/tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 536870912 exceeds 10% of free system memory.

and the container crashes soon after. 

Any ideas ?

**Comment by duhuajiang** [comment]
you maybe find all request during the memory sharp growing！in my case,there are two problem:
1. the grpc request not set expire time,so the request accumulate when some request run slowly.&nbsp;
2.&nbsp; the input image is illegal, such as the height / width was imbalance



---Original---
From: ***@***.***&gt;
Date: Tue, May 18, 2021 22:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tensorflow/serving] Serving Docker memory usage is growing constantly  (#1631)




 
Hi, I am also facing memory growth problem with tensorflow serving in docker container. Classifying images with custom model and after about 30 classifications I get a warning log:
 
W external/org_tensorflow/tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 536870912 exceeds 10% of free system memory.
 
and the container crashes soon after.
 
Any ideas ?

**Comment by duhuajiang** [comment]
you maybe find all request during the memory sharp growing！in my case,there are two problem:
1. the grpc request not set expire time,so the request accumulate when some request run slowly.
2.  the input image is illegal, such as the height / width was imbalance

---Original---
From: ***@***.***&gt;
Date: Sat, Mar 6, 2021 14:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tensorflow/serving] Serving Docker memory usage is growing constantly  (#1631)




 
Hi @aniketmaurya ,
 I am facing the same issue, with multiple concurrent requests to model server for prediction . Did you find any solution to this issue?

**Comment by gaikwadrahul8** [comment]
Hi, @aniketmaurya 

Apologies for the delay and I found similar issue #[1215](https://github.com/tensorflow/serving/issues/1215) as per this [comment](https://github.com/tensorflow/serving/issues/1215#issuecomment-744988108) this [PR](https://github.com/tensorflow/serving/pull/1785) got merged, for your reference I have added TensorFlow Serving performance optimization youtube video link [here](https://www.youtube.com/watch?v=fnZTVQ1SnDg) and also please go through our official documentation about Tensorflow Serving Configuration [here](https://www.tensorflow.org/tfx/serving/serving_config), I hope it will help you to resolve your issue 

Could you please try it and let us know is it resolving your issue ? If issue still persists please let us know, In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here ?

Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @aniketmaurya 

Closing this issue due to lack of recent activity for couple of weeks. Please feel free to reopen the issue or post comments, if you need any further assistance or update. Thank you!
