### ISSUE TITLE
Different checksum for icu thirdparty dependency

### ISSUE THREAD

**Issue by satishpasumarthi** [tensorflow/serving#1633]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow Serving installed from (source or binary)**: source
- **TensorFlow Serving version**: 2.2.0-rc2

### Describe the problem
While compiling the serving build using native bazel command. The build fails because the checksum was different for icu third party library.

ERROR: Analysis of target '//tensorflow_serving/model_servers:tensorflow_model_server' failed; build aborted: no such package '@icu//': java.io.IOException: Error downloading [https://github.com/unicode-org/icu/archive/release-64-2.zip] to /root/.cache/bazel/_bazel_root/809db859f3e696c0577264463462c64f/external/icu/release-64-2.zip: Checksum was 10cd92f1585c537d937ecbb587f6c3b36a5275c87feabe05d777a828677ec32f but wanted dfc62618aa4bd3ca14a3df548cd65fe393155edd213e49c39f3a30ccd618fc2

**Comment by munagekar** [comment]
sed -ri "/^\W+sha256 = \"[^\"]+\"\W+$/d" tensorflow_serving/workspace.bzl

**Comment by satishpasumarthi** [comment]
> As a hack you can disable verifying the checksum
> 
> ```
> sed -ri "/^\W+sha256 = \"[^\"]+\"\W+$/d" tensorflow_serving/workspace.bzl
> ```

Isn't this way an easy way to miss if the file is corrupted?

**Comment by tobegit3hub** [comment]
Edit the `tensorflow_serving/workspace.bzl` and change to this checksum will work.

```
sha256 = "10cd92f1585c537d937ecbb587f6c3b36a5275c87feabe05d777a828677ec32f",
```

**Comment by christisg** [comment]
Thanks for reporting. This should be fixed by https://github.com/tensorflow/serving/commit/6ad81047a282f0e67ceebe9e25d7f0201e636a84.

**Comment by tobegit3hub** [comment]
Nice and thanks for the fix @christisg .
