### ISSUE TITLE
the memory free of TF serving

### ISSUE THREAD

**Issue by BannockYJQ** [tensorflow/serving#1644]
When i delete the previous model, it has been standing in memory so that i cant do hourly model updates.So is there some solution?

**Comment by gowthamkpr** [comment]
@BannockYJQ Can you please fill the [template](https://github.com/tensorflow/serving/issues/new). Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for a long time. Please add additional comments for us to open this issue again. Thanks!
