### ISSUE TITLE
Consider the unified interface and general inference service for all models

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/serving#165]
TensorFlow serving is the nice service for TensorFlow models. But now we have to write the code and customize the inputs and outputs which depend on the model.

We have already implemented the unified interfaces for inference which is inspired by Google Cloud ML. The idea is simple. We add the inputs and outputs into the model files by `tf.add_to_collection()`. We can add the JSON data with inputs and outputs Tensor and it's flexible enough to add  any number of inputs and outputs with string labels.

The general inference service needs to get the "agreed" inputs and outputs Tensor by `tf.get_collection()`. Then create the session handler to run the "outputs" with the "inputs" as feed_dict, which means that all the information it needs is already in the model file.

We have implemented the general inference service in [gRPC server](https://github.com/tobegit3hub/deep_recommend_system/blob/master/grpc_service/inference_server.py) and [HTTP server](https://github.com/tobegit3hub/deep_recommend_system/blob/master/http_service/cancer_predict/views.py). End users use gRPC or HTTP clients to access the inference service with the specified data format. We don't need to change any code of the inference server for any other TensorFlow model.

**Comment by kirilg** [comment]
[This discussion](https://github.com/tensorflow/serving/issues/121) may be relevant. The code that actually handles requests would not be model specific (only our simple examples are) and it certainly is possible to build a generic interface, it's just important to create the most reusable API (hard to change later).

We recently released the [model_server](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc) which exposes a [PredictionService](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/prediction_service.proto#L10). See [here](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/predict.proto) for the Request and Response type definitions, which I believe should work for your needs.

**Comment by tobegit3hub** [comment]
Thanks @kirilg . I think that's what we want for general inference service.

But we're using the name `Inference` which may be equal to the current name `Predict`. If I'm right, TensorFlow serving may deprecate the APIs about `Classify*` and `Regression*` because now we have the unified interface for them.

And changing the simple examples to this could help because we're actually doing the same thing.
