### ISSUE TITLE
HOW CAN I limit the GPU's MEMORY .

### ISSUE THREAD

**Issue by goodluck4s** [tensorflow/serving#1650]
I want to deploy a model by tensorflowServing+nvidia-docker on GPU .
HOW CAN I limit the GPU's MEMORY .
cause it's tend to use all memory of GPU .
I want to limit the GPU memory used to below 5G (10G in total) .

**Comment by gowthamkpr** [comment]
@goodluck4s This is not related to serving, its related to tensorflow itself. You have to limit the the tensorflow models memory growth itself. You can go through the following [issue](https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory) and the following [article](https://medium.com/@starriet87/tensorflow-2-0-wanna-limit-gpu-memory-10ad474e2528) to understand how to limit GPU usage by tensorflow.

**Comment by goodluck4s** [comment]
Thanks for your reply, ANd I know how to solve this problem

**Comment by goodluck4s** [comment]
if i use the following way to run my model serve , Is there a suitable environment variable to control GPU's memory usage

docker run --runtime=nvidia -p 8501:8501 \
  --mount type=bind, \
  source=/tmp/tfserving/serving/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_two_gpu, \
  target=/models/half_plus_two  \
-e NVIDIA_VISIBLE_DEVICES=3  \
  -e MODEL_NAME=half_plus_two -t tensorflow/serving:latest-gpu &

**Comment by gowthamkpr** [comment]
@goodluck4s You can take a look at this [comment](https://github.com/tensorflow/serving/issues/1440#issuecomment-541578798) where your question has been answered. Thanks!

**Comment by goodluck4s** [comment]
thanks for you reply and i had solve this problem

**Comment by gowthamkpr** [comment]
@goodluck4s Thank you for the reply. I am closing this issue as it has been resolved.

**Comment by junneyang** [comment]
@gowthamkpr   how to solve this problem, thanks
