### ISSUE TITLE
"Expected one input Tensor." error on "regress" REST API

### ISSUE THREAD

**Issue by krikit** [tensorflow/serving#1657]
I have a trouble with "regress" API on TensorFlow serving server,
with following this article: https://www.tensorflow.org/tfx/serving/api_rest

Please see gist link below to read the code more comfortably.
https://gist.github.com/krikit/32c918cc03b52315ade562267a91fa6b

I made a simple Keras model which got two inputs(x1, x2) and showed single output value(y).
With this model, I got error results from serving server when I used "regress" REST API.

```python
# the model
inputs = {
    'x1': tf.keras.layers.Input(shape=(1, ), name='x1', dtype='float32'),
    'x2': tf.keras.layers.Input(shape=(1, ), name='x2', dtype='float32'),
}
concat = tf.keras.layers.Concatenate(name='concat')([inputs['x1'], inputs['x2']])
dense = tf.keras.layers.Dense(10, use_bias=True, activation='relu', name='dense')(concat)
outputs = tf.keras.layers.Dense(1, use_bias=True, activation='sigmoid', name='y')(dense)
model = tf.keras.models.Model(inputs=inputs, outputs=outputs)
model.compile(optimizer='SGD', loss='binary_crossentropy')
model.summary()


# training
num_exam = 10000
model.fit({'x1': np.random.randn(num_exam), 'x2': np.random.rand(num_exam)}, np.random.randn(num_exam))


# save
input_infos = {name: tf.saved_model.build_tensor_info(tensor) for name, tensor in model.input.items()}
output_infos = {'y': tf.saved_model.build_tensor_info(model.outputs[0])}
signature = tf.saved_model.build_signature_def(
    inputs=input_infos,
    outputs=output_infos,
    method_name=tf.saved_model.signature_constants.REGRESS_METHOD_NAME
)
print(signature)

model_dir = './random_regression/1'
shutil.rmtree(model_dir, ignore_errors=True)
model_builder = tf.saved_model.builder.SavedModelBuilder(model_dir)
model_builder.add_meta_graph_and_variables(
    tf.keras.backend.get_session(),
    tags=[tf.saved_model.tag_constants.SERVING, ],
    signature_def_map={tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY: signature}
)
model_builder.save()
```

After I saved model, it seemed to be all right from the output of "saved_model_cli" tool.
```bash
$ saved_model_cli show --dir ./random_regression/1 --all

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['x1'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: x1:0
    inputs['x2'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: x2:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['y'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: y/Sigmoid:0
  Method name is: tensorflow/serving/regress
```

After I started serving server with the model, I tested REST API with "regress" method.
But I got an error like below,
```bash
$ curl -X POST -H "Content-Type: application/json" http://localhost:8501/v1/models/random_regression/versions/1:regress -d '
{
  "examples": [
    {
      "x1": [0.1],
      "x2": [0.2]
    },
    {
      "x1": [0.1],
      "x2": [0.3]
    }
  ]
}'

Response:
{ "error": "Expected one input Tensor." }
```

Although I made a regress signature, the predict API was also available.
```bash
$ curl -X POST -H "Content-Type: application/json" http://localhost:8501/v1/models/random_regression/versions/1:predict -d '
{
  "instances": [
    {
      "x1": [0.1],
      "x2": [0.2]
    },
    {
      "x1": [0.1],
      "x2": [0.3]
    }
  ]
}'

Response:
{
    "predictions": [[0.143165469], [0.124352224]
    ]
}
```

The reason why I use the "regress" method is that I need the "context" field like below.
My "context" features are too heavy to copy them to all of examples.
```bash
$ curl -X POST -H "Content-Type: application/json" http://localhost:8501/v1/models/random_regression/versions/1:regress -d '
{
  "context": {
    "x1": [0.1]
  },
  "examples": [
    {
      "x2": [0.2]
    },
    {
      "x2": [0.3]
    }
  ]
}'

Response:
{ "error": "Expected one input Tensor." }
```

My system information:
* MacOS Catalina with docker image tensorflow/serving:1.14.0
* Both of TensorFlow and TF Serving are version 1.14.0

**Comment by gowthamkpr** [comment]
Regression API calls prescribe that there must be exactly one inputs Tensor, and one outputs Tensor.
This is the reason why you are running into an error.

**Comment by krikit** [comment]
I understand why I was running into an error.
The method named "[PreProcessRegression()](https://github.com/tensorflow/serving/blob/c6b9dcac44a38ad300e9ee16740450f4040476f0/tensorflow_serving/servables/tensorflow/regressor.cc#L161)" shows that "regression" API must have only one "inputs" string Tensor.
I think "regress" API is currently not completely functional as described [here](https://www.tensorflow.org/tfx/serving/api_rest#classify_and_regress_api).
Is it possible to pass "context" input features?

**Comment by gowthamkpr** [comment]
Its deprication in tensorflow 2.x but in 1.x regress api still works. Please take a look at the doc [here](https://www.tensorflow.org/tfx/serving/api_rest#request_format) which talks about how to pass context. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than a week. Please add additional comments for us to open this issue again. Thanks!

**Comment by arnoegw** [comment]
Commit https://github.com/tensorflow/tensorflow/commit/95ae841d7a55b71795faf4e244a2958c71be14f3 belatedly documents the behavior change from https://github.com/tensorflow/serving/commit/b724ceda57b4fdc9b5bd09da231c7186435cd807.
