### ISSUE TITLE
Plugins (dynamically linked user extensions)

### ISSUE THREAD

**Issue by RussianEmpire** [tensorflow/serving#1671]
https://stackoverflow.com/questions/62453370/does-tensorflow-serving-allows-plugins-dynamically-linked-user-extensions

### Describe the problem the feature is intended to solve
When recompiling a code is not an option (for any reason: security, original code is forbidden to be changed, lost, and so on) and so static linking of the user code (custom sources, etc) is unavailable, dynamic extensions would be a great solution.

### Describe the solution
It would be very good to have an ability for the server to support the user plugins (dynamically linked and loaded libraries) which can be hot-plugged and unplugged to the same (and, possibly, others) extension points the server already provided for static linkage (custom sources, custom servables, etc).

### Describe alternatives you've considered
Not sure what alternatives exist in that case.

### Additional context
In my case, I need to have a custom source which can take data (to make predictions by an already trained model ) from Amazon queue, and then able to pass it to the server, but only when it is really ready to process it (and not to return a timeout error instead).

**Comment by christisg** [comment]
Hello @RussianEmpire,

Thank you for reaching out with this request.
The main challenge in supporting dynamic linking is the fact that it requires maintaining ABI compatibility between Model Server and any given dynamically linked library.

For the use-case you're describing, have you looked into implementing and statically linking your custom source (https://www.tensorflow.org/tfx/serving/custom_servable#defining_a_loader_and_sourceadapter_for_yourservable)?

**Comment by arghyaganguly** [comment]
@RussianEmpire , Closing this as there has been no response for a long time.Please feel free to reopen based on the comment by  @christisg .Thanks.
