### ISSUE TITLE
URLs in Installation shell commands are enclosed within anchor tag

### ISSUE THREAD

**Issue by sathyamoorthyrr** [tensorflow/serving#1677]
The Tensorflow Serving Installation **commands** are formatted.

The actual shell command should be,
```
echo "deb [arch=amd64] http://storage.googleapis.com/tensorflow-serving-apt stable tensorflow-model-server tensorflow-model-server-universal" | sudo tee /etc/apt/sources.list.d/tensorflow-serving.list && \
    curl https://storage.googleapis.com/tensorflow-serving-apt/tensorflow-serving.release.pub.gpg | sudo apt-key add -
```

But, the visible Documentation at https://www.tensorflow.org/tfx/serving/setup#installation_2 formats all the URLs.

The URLs are enclosed within the anchor tag and href attribute `<a href="">`
```
echo "deb [arch=amd64] <a href="http://storage.googleapis.com/tensorflow-serving-apt">http://storage.googleapis.com/tensorflow-serving-apt</a> stable tensorflow-model-server tensorflow-model-server-universal" | sudo tee /etc/apt/sources.list.d/tensorflow-serving.list && \
curl <a href="https://storage.googleapis.com/tensorflow-serving-apt/tensorflow-serving.release.pub.gpg">https://storage.googleapis.com/tensorflow-serving-apt/tensorflow-serving.release.pub.gpg</a> | sudo apt-key add -
```

**Comment by rmothukuru** [comment]
@sathyamoorthyrr,
Can you please specify the problem caused by the changed formatting. Thanks!

**Comment by sathyamoorthyrr** [comment]
@rmothukuru 

Do you see the actual commands visible in the Documentation (or the second set of commands above)

It has `<a href=""> ... </a>` which is not accepted by the shell

When we just use the above commands in our terminal directly, the shell simply says,

> bash: syntax error near unexpected token `|'

**Comment by christisg** [comment]
I followed the link at https://www.tensorflow.org/tfx/serving/setup#installation_2 and I do not see the shell commands converted int he way described here. Using "Copy code sample to clipboard" yields the correctly formatted format.

**Comment by sathyamoorthyrr** [comment]
It's works as expected now.

**Comment by christisg** [comment]
I'm closing the issue then. Feel free to reopen if there are further concerns.
