### ISSUE TITLE
Error while running tfserving docker with s3 model

### ISSUE THREAD

**Issue by tiru1930** [tensorflow/serving#1684]
I  am not able to start docker for tfserving where my model is stored in aws s3 and the command i am using is 

```
docker run -p 8501:8501 \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e MODEL_BASE_PATH=s3://bucker-name \
    -e MODEL_NAME=model-name \
    -e S3_ENDPOINT=s3.region-amazonaws.com \
    -e AWS_REGION=region \
    -t tensorflow/serving
```

Here model is stored in bucket

bucket-name/model-name
     saved_mode.pb
     variables 

Error

```
2020-07-06 05:37:14.786914: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:362] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path
```

**Comment by tiru1930** [comment]
issue with storage url  path doesnot have version

**Comment by Suvab-rently** [comment]
HI @tiru1930 , how were you able to resolve this? Were you able to load the model, if so can you tell how?

Also, I want to be able to serve all the models that are present in the S3 (suppose all the saved models are under bucket_name/trained_model/ directory

docker run -p 8501:8501 
-e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID 
-e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY 
-e S3_ENDPOINT=s3.us-east-1.amazonaws.com 
-e AWS_REGION=us-east-1 
-e TF_CPP_MIN_LOG_LEVEL=3
-e MODEL_BASE_PATH=s3://bucket_name/trained-model 
-t tensorflow/serving 
--model_config_file=s3://bucket_name/model_config.config

And my config file looks like this:

```
model_config_list:{
  config:{
         name: '55'
         base_path: 's3://bucket_name/trained_model/55/'
         model_platform: 'tensorflow'
         model_version_policy: {
        	specific:{
        	versions: 1,
        	versions: 2,
        	}
       }
       }
  config:{
        name: '56'
        base_path: 's3://bucket_name/trained_model/56/'
        model_platform: 'tensorflow'
        }
}
```
But I always get **Failed to start server. Error: Failed precondition: AWS Credentials have not been set properly. Unable to access the specified S3 location**
I have checked the credentials are correct and have access.

**Comment by tiru1930** [comment]
@Suvab-rently   In my case storage URL doesn't have version 

so url path should s3://bucker_name/saved_model/1/{saved_model.pd,variables }

so while runing the docker if we give till this s3://bucker_name/saved_model as storage URL , it will take the latest version from that directory and serve in tfserving 

in ur case its not even that, looks like your aws credenials are not set, properly

**Comment by bruceche11** [comment]
@tiru1930 Hello,learn from you.
Here is my addition:
1、I use minio as my storage 
![image](https://user-images.githubusercontent.com/16239670/114666330-b70cea00-9d30-11eb-9b7e-5ae4aac9ad80.png)
![image](https://user-images.githubusercontent.com/16239670/114666447-dad03000-9d30-11eb-969c-1e56db9d50f2.png)
![image](https://user-images.githubusercontent.com/16239670/114668578-7ebadb00-9d33-11eb-86ea-33106713d501.png)
that means I can reach s3 from tensorflow, right?

2、Then,I try tensorflow/serving with locate path(which is the file on minio)
![image](https://user-images.githubusercontent.com/16239670/114668730-a3af4e00-9d33-11eb-90cd-ca7fe3512572.png)
I think that means my model is OK

3、Then,I try with s3 path:
![image](https://user-images.githubusercontent.com/16239670/114669500-8af36800-9d34-11eb-986c-e37534a46711.png)
Why? I am confused...

**Comment by bruceche11** [comment]
@tiru1930 
Sorry, the next moment after I comment, I realized something I change the S3_ENDPOINT from http://127.0.0.1:9000 to my real IP, and it worked
Thank you all the same. Your work inspired me.

**Comment by 521bibi** [comment]
> @tiru1930 Sorry, the next moment after I comment, I realized something I change the S3_ENDPOINT from http://127.0.0.1:9000 to my real IP, and it worked Thank you all the same. Your work inspired me.

![image](https://user-images.githubusercontent.com/38529261/182984425-006ab7ef-b216-469f-a2fa-f0d0d00f3c7c.png)
`docker run --rm -p 8501:8501 --name tfs-s3 -e AWS_ACCESS_KEY_ID=minioadmin -e AWS_SECRET_ACCESS_KEY=minioadmin  -e S3_ENDPOINT=http://127.0.0.1:9000 -e AWS_REGION=us-east-1 --env MODEL_BASE_PATH=S3://models --env MODEL_NAME=half -t tensorflow/serving:latest`
my error is：
![image](https://user-images.githubusercontent.com/38529261/182984603-88f81ba2-71c7-40d4-8bcd-fdaa30c0519c.png)
how do i modify

**Comment by spxcds** [comment]
mark
