### ISSUE TITLE
Outdated docs/examples compared to versions in tensorflow/serving:nightly-devel

### ISSUE THREAD

**Issue by ahakanbaba** [tensorflow/serving#1689]
I think the code in `resnet_client_grpc.py` and the container `tensorflow/serving:nightly-devel` have diverged. It looks like `resnet_client_grpc.py` is using old names. For example uses `tf.app.flags.FLAGS` instead of `tf.compat.v1.app.flags.FLAGS`

Take a look at the [docs](https://github.com/tensorflow/serving/blob/195584c93e53f2461d8fef2f071f53a0a57e4dd9/tensorflow_serving/g3doc/serving_kubernetes.md#query-the-server) mentioning the usage of `resnet_client_grpc.py` 

Uses the command: 
```
tools/run_in_docker.sh python tensorflow_serving/example/resnet_client_grpc.py
```

The `run_in_docker.sh` [uses](https://github.com/tensorflow/serving/blob/195584c93e53f2461d8fef2f071f53a0a57e4dd9/tools/run_in_docker.sh#L72) the `tensorflow/serving:nightly-devel` container.

And the `resnet_client_grpc.py` [uses](https://github.com/tensorflow/serving/blob/195584c93e53f2461d8fef2f071f53a0a57e4dd9/tensorflow_serving/example/resnet_client_grpc.py#L55) names like `tf.app.flags.FLAGS` which does not exist in that nightly container anymore. 

```
$ docker run -it  tensorflow/serving:nightly-devel python -c "import tensorflow as tf; tf.app.flags.FLAGS"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'app'
 ```

But the other path exists. 
```
$ docker run -it  tensorflow/serving:nightly-devel python -c "import tensorflow as tf; print(type(tf.compat.v1.app.flags.FLAGS).__name__)"
_FlagValuesWrapper
```

It looks like there was a prior [change](https://github.com/tensorflow/serving/commit/fb3c70dc8a44720df870d733f885f6a29e5b6a88#diff-dd700320f707279d625f0e70499124eaL60) that did the name change but these were skipped in there. 

The following diff fixes the resnet_client_grpc.py. 
```
--- a/tensorflow_serving/example/resnet_client_grpc.py
+++ b/tensorflow_serving/example/resnet_client_grpc.py
@@ -30,10 +30,10 @@ from tensorflow_serving.apis import prediction_service_pb2_grpc
 # The image URL is the location of the image we should send to the server
 IMAGE_URL = 'https://tensorflow.org/images/blogs/serving/cat.jpg'

-tf.app.flags.DEFINE_string('server', 'localhost:8500',
+tf.compat.v1.app.flags.DEFINE_string('server', 'localhost:8500',
                            'PredictionService host:port')
-tf.app.flags.DEFINE_string('image', '', 'path to image in JPEG format')
-FLAGS = tf.app.flags.FLAGS
+tf.compat.v1.app.flags.DEFINE_string('image', '', 'path to image in JPEG format')
+FLAGS = tf.compat.v1.app.flags.FLAGS

```

But there are other usages of the old names 
```
/tensorflow_serving/example/mnist_client.py|50| FLAGS = tf.app.flags.FLAGS
/tensorflow_serving/servables/tensorflow/testdata/export_counter.py|106| tf.app.run()
/tensorflow_serving/servables/tensorflow/testdata/export_bad_half_plus_two.py|59| tf.app.run()
/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_two.py|400| tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
/tensorflow_serving/model_servers/tensorflow_model_server_test_client.py|32| tf.app.flags.DEFINE_string('server', 'localhost:8500',
/tensorflow_serving/model_servers/tensorflow_model_server_test_client.py|34| FLAGS = tf.app.flags.FLAGS
/tensorflow_serving/model_servers/tensorflow_model_server_test_client.py|51| tf.app.run()
```

Those also need to be re-visited.

**Comment by lilao** [comment]
Thanks @ahakanbaba. I'll send a fix.

**Comment by lilao** [comment]
This should be fixed by https://github.com/tensorflow/serving/commit/06fbf878a98c8bd4202e33bc1c097a6ce184d06e. Please let us know if you see other problems.
