### ISSUE TITLE
Invalid GPG Key for Debian Binary

### ISSUE THREAD

**Issue by Zerthick** [tensorflow/serving#1691]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 10.4 Buster (Docker Image)
- **TensorFlow Serving installed from (source or binary)**: binary (apt)
- **TensorFlow Serving version**: 2.2.0

### Describe the problem
I've noticed today that my docker builds are throwing the following error when I attempt to install `tensorflow-model-server`:

```
Err:3 http://storage.googleapis.com/tensorflow-serving-apt stable InRelease
  The following signatures were invalid: EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>
Reading package lists...
W: GPG error: http://storage.googleapis.com/tensorflow-serving-apt stable InRelease: The following signatures were invalid: EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>
E: The repository 'http://storage.googleapis.com/tensorflow-serving-apt stable InRelease' is not signed.
```

### Exact Steps to Reproduce
Here is the relevant part of my Dockerfile:

```
# Add TensorFlow Serving Distribution as Package Sorce
RUN apt-get install -y curl gnupg && \
    echo "deb [arch=amd64] http://storage.googleapis.com/tensorflow-serving-apt stable tensorflow-model-server tensorflow-model-server-universal" \
    | tee /etc/apt/sources.list.d/tensorflow-serving.list && \
    curl https://storage.googleapis.com/tensorflow-serving-apt/tensorflow-serving.release.pub.gpg | apt-key add -

RUN apt-get update && apt-get install -y tensorflow-model-server
```

I've done a docker build with ` --no-cache` to make sure I wasn't caching old data but this seems to still occur.  Any assistance in resolving this issue would be appreciated. Thanks!

**Comment by ptierno** [comment]
Having same issue. Looks like the Key is expired.

**Comment by ashishalakhani** [comment]
Now i see E: Unable to locate package tensorflow-model-server , Can anyone please fix this

**Comment by ashishalakhani** [comment]
@gowthamkpr @rmothukuru are there any workaround until this get fixed. Like downloading installing previous version etc..
We were planning to launch a feature to production and this is blocking us.

**Comment by lilao** [comment]
Thanks for the report. The key should be renewed. Please reopen if you see any problem.

**Comment by anuragtr** [comment]
getting same issue of invalid signature.
