### ISSUE TITLE
[Question] r2.3 for TF Serving

### ISSUE THREAD

**Issue by satishpasumarthi** [tensorflow/serving#1692]
Hello, when can we expect r2.3 be cut for tensorflow serving?

**Comment by minglotus** [comment]
TF serving team will cut the release by the end of this week (at immediate moment waiting for a fix to be live).

**Comment by minglotus-6** [comment]
TF serving team is working on 2.3 release cut.

**Comment by minglotus-6** [comment]
https://github.com/tensorflow/serving/tree/r2.3 was cut.
