### ISSUE TITLE
Recommended way to call TF Transform graph before model inference?

### ISSUE THREAD

**Issue by thisisandreeeee** [tensorflow/serving#1699]
In TF 1.x, developers were able to execute TF Transform graphs via the serving_input_fn (see: [example](https://github.com/tensorflow/transform/blob/77e862db6dd733d34fb0f1e311228c1535e828db/examples/sentiment_example.py#L267-L299)). What is the recommended way to do so in TF 2.x using the Keras API?

I try to do this by overwriting the serving signature when exporting the saved model:

```python
SERVING_FEATURE_SPEC = {
    name: tf.TensorSpec(shape=None, dtype=tf.float32, name=name) for name in FEATURES
}

class ExportModel(tf.keras.Model):
    def __init__(self, model, tft_dir):
        super().__init__(self)
        self.model = model
        self.tft_output = tft.TFTransformOutput(tft_dir)

    @tf.function(input_signature=[SERVING_FEATURE_SPEC])
    def serving_fn(self, inputs):
        transformed = self.tft_output.transform_raw_features(inputs)
        return {
            'pred' : self.model(transformed)
        }

    def save(self, export_path):
        sigs = {
            'serving_default' : self.serving_fn
        }
        tf.keras.backend.set_learning_phase(0) # inference only
        tf.saved_model.save(self, export_path, signatures=sigs)

sm = ExportModel(model)
sm.save(EXPORT_PATH)
```

However, this approach feels like a hack. Is there a more natural way to be doing this?

An alternative approach would be to [convert the keras model to estimator](https://www.tensorflow.org/api_docs/python/tf/keras/estimator/model_to_estimator), but given that we are trying to move away from the estimator API, I would like to avoid doing so if possible.

**Comment by rmothukuru** [comment]
@thisisandreeeee,
Can you please refer to this [TFX Documentation](https://www.tensorflow.org/tfx/guide/keras#keras_module_file_with_transform)  and let us know if it helps. Thanks!

**Comment by thisisandreeeee** [comment]
Yes, that helps. Thank you @rmothukuru , closing this issue.
