### ISSUE TITLE
While trying to run 3D Unet of mesh-tensorflow

### ISSUE THREAD

**Issue by ved27** [tensorflow/serving#1701]
Hi,

I was trying to run 3D Unet model of mesh-tensorflow. I was able to run the code with few package version tweaks. However the see the following in the logs. I can also see that GPU memory is all being used up as shown by nvidia-smi. The training seems to be slow too. 

**tensorflow/core/common_runtime/colocation_graph.cc:1017] Failed to place the graph without changing the devices of some resources. Some of the operations (that had to be colocated with resource generating operations) are not supported on the resources' devices. Current candidate devices are [
/job:localhost/replica:0/task:0/device:CPU:0].
See below for details of this colocation group:
Colocation Debug Info:
Colocation group had the following types and supported devices:
Root Member(assigned_device_name_index_=-1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
AssignVariableOp: CPU XLA_CPU XLA_GPU
RandomUniform: CPU XLA_CPU XLA_GPU
VarIsInitializedOp: GPU CPU XLA_CPU XLA_GPU
Const: GPU CPU XLA_CPU XLA_GPU
Mul: CPU XLA_CPU XLA_GPU
ReadVariableOp: GPU CPU XLA_CPU XLA_GPU
Sub: CPU XLA_CPU XLA_GPU
VarHandleOp: CPU XLA_CPU XLA_GPU
Add: CPU XLA_CPU XLA_GPU**

**Comment by gowthamkpr** [comment]
@ved27 Please procide us reproducible code for us to reproduce this issue. Thanks!

**Comment by ved27** [comment]
Hi,

I figured out the issue. It's because of the datatype. After I changed to fp32, GPU and everything is utilized well. 
The log should have had more information. 

Thanks for taking time.

**Comment by gowthamkpr** [comment]
Thanks. Closing this issue as it has been resolved.
