### ISSUE TITLE
Unable to run the base example

### ISSUE THREAD

**Issue by Samvid95** [tensorflow/serving#1704]
Hey guys, 

I am trying this [getting started ](https://www.tensorflow.org/tfx/serving/docker)guide with docker but it is unfortunately not working for me. I am using Anaconda cmd on Windows10 with docker. 

When I run the `docker run` it works and gives me this log message: `Successfully loaded servable version {name: half_plus_two version: 123}
`
But unfortunately when I try to run the `curl `command it is giving me an error. 
```
curl: (3) [globbing] bad range in column 2
curl: (6) Could not resolve host: 2.0,
curl: (3) [globbing] unmatched close brace/bracket in column 4
{
    "error": "JSON Parse error: Invalid value. at offset: 0"
}
```

I have also attached the screenshots for all of them. 
![upload2](https://user-images.githubusercontent.com/11596480/88967103-f2cf5480-d272-11ea-9882-7104328f1942.PNG)
![upload1](https://user-images.githubusercontent.com/11596480/88967111-f367eb00-d272-11ea-863f-06a207326775.PNG)

**Comment by gowthamkpr** [comment]
@Samvid95 This is not a tensorflow serving issue, its a windows issue. 

Windows's cmd doesn't support strings with single quotes. Use " and escape the inner ones with \".

Please take a look at this issue [here](https://stackoverflow.com/questions/58788793/curl-query-to-tensorflow-serving-model-to-predict-api-breaks).

Closing this issue as it is not related to tensorflow serving. Thanks!
