### ISSUE TITLE
How to change grpc to brpc in  C++ API?

### ISSUE THREAD

**Issue by muween** [tensorflow/serving#1717]
grpc.    https://github.com/grpc/grpc
brpc.   https://github.com/apache/incubator-brpc

**Comment by muween** [comment]
grpc [https://github.com/grpc/grpc](url)
brpc[https://github.com/apache/incubator-brpc](url)

**Comment by gowthamkpr** [comment]
@muween Can you please be more specific as this issue looks like a generic issue. How is it related to tensorflow serving?

**Comment by muween** [comment]
> @muween Can you please be more specific as this issue looks like a generic issue. How is it related to tensorflow serving?

The client uses the tensorflow serving with the way of grpc to get response from the server inside. Restful way can also work. But now there is a demand that use brpc framework to instead the grpc framework inside the tensorflow serving.

**Comment by misterpeddy** [comment]
Thanks for opening this issue - we don't provide support or documentation for changing the RPC framework for the system as it's a fairly involved process. If you'd like to take a stab at it feel free to take a look at how the [REST](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/http_server.cc) and [gRPC](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/server.cc) servers have been implemented.

**Comment by TheGreatRandall** [comment]
hi muween. I am a junior now and recently I am working on how to replace grpc with another rpc. However, I found it's pretty difficult. Could you give me some hint about how you did that? Thank you!
