### ISSUE TITLE
Tensorflow-serving build error by broken links

### ISSUE THREAD

**Issue by SmartInWhut** [tensorflow/serving#1721]
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- docker:18.04

### Describe the problem
i am following the [guide](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/building_with_docker.md) tenserflow-serving build with docker,no matter which release i used, every time when the building process at

`Step 21/25 : RUN bazel build --color=yes --curses=yes     ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS}     tensorflow_serving/model_servers:tensorflow_model_server &&     cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server     /usr/local/bin/ `

the building will failed with

`WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/2b96f3662bd776e277f86997659e61046b56c315.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found 
`
or other broken link download error.When i open the link in chrome,  i get
  `<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>`

**Comment by rmothukuru** [comment]
@SmartInWhut,
Couldn't find the code, 

`RUN bazel build --color=yes --curses=yes ${TF_SERVING_BAZEL_OPTIONS} --verbose_failures --output_filter=DONT_MATCH_ANYTHING ${TF_SERVING_BUILD_OPTIONS} tensorflow_serving/model_servers:tensorflow_model_server && cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server /usr/local/bin/` 

in the [Guide](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/building_with_docker.md) that you have shared. Can you please provide the steps to reproduce the error. Thanks!

**Comment by SmartInWhut** [comment]
@rmothukuru 
[Building an optimized serving binary](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/building_with_docker.md#building-an-optimized-serving-binary)
at step 2  
`Build an image with an optimized ModelServer
For CPU:`
could this be a network problem？

**Comment by SmartInWhut** [comment]
After limit the resouce  bazel using with ` --local_resources 2048,.5,1.0 `, the building succeed. Turned out to be insufficient memory? i'm usring docker desktop on windows by the way.

**Comment by rmothukuru** [comment]
@SmartInWhut,
That may be the reason. Can you please confirm if we can close this issue as it has been resolved? Thanks!

**Comment by SmartInWhut** [comment]
Yeah,it was solved.  Thanks!
