### ISSUE TITLE
Feature Request - Allow for predictions from multiple models in one request

### ISSUE THREAD

**Issue by codebynumbers** [tensorflow/serving#1722]
In a high volume environment, we often have to query multiple models at once. To reduce the number of network trips and total response time, it would beneficial to expose a multiple prediction endpoint that returns list of predictions. 

Alternatives considered are to wrap the TensorFlow Server with a micro service running on the same machine, that loops over each query in the request, makes a request to locally running service, then bundles up the results into a list and returns it to the client as a single response.

**Comment by rehevkor5** [comment]
> From a scalability perspective this doesn't seem to be a good design, you would be bulking up the model file and the TMS thread. TMS is meant to be light and unary i.e one model per serving to support scalable serving.

I can't speak to technical details of TFServing such as the TMS thread. But, I think there are other aspects to the scalability and "good design" (or lack thereof) that should be considered. Specifically:

- Multiple HTTP requests/responses vs. one
- For models that share some (or all) of the same input features, the client must serialize and send that same data multiple times, and the server must deserialize it multiple times

The overhead involved could easily add up, especially as the number of models increases and the number of shared features increases.

> you can build models in Keras / Tensorflow that predict multiple things at a time from the same input

Doesn't this suffer from the same critique you mentioned in your first paragraph? Namely, that the model file will be "bulked up" and the TMS thread will be occupied handling all of the models in one request, not one at a time.

Also, this requires that the model authors code & build their model artifacts combined in advance. They must know in advance that all requests need to go to all of the models at the same time. Indeed, it is no longer possible to make requests to just one of the models. In practice, this does not always make sense. Individual models might be deployed separately, and the query pattern might be determined at runtime, or might vary based on the configuration of other components of the overall system. I could imagine perhaps writing an automated build process by which multiple SavedModels might be combined together, but I'm not confident if that's feasible, and it suffers from the same weakness that it requires advance knowledge of the request pattern.

**Comment by singhniraj08** [comment]
@codebynumbers,

@gyb997,

Tensorflow Serving can simultaneously serve multiple models but cannot combine the predictions from both the models to create a single REST/gRPC call. A suggested workaround is to load multiple models using Tensorflow serving and then create a python function to make predictions from both models and combine the prediction JSON response to create a single JSON response and return it. Thank you!

Ref: 
[TensorFlow Serving of Multiple ML Models Simultaneously](https://medium.com/retina-ai-health-inc/tensorflow-serving-of-multiple-ml-models-simultaneously-to-a-rest-api-python-client-cd60ac6f71aa)
[Merge multiple JSON objects in single object](https://www.programmingbasic.com/merge-multiple-json-objects-into-one-single-object-python)

**Comment by miguelalba96** [comment]
You can pack all different models in a single graph via tf.Module, then export the graph containing all models, thats the one you call one time
