### ISSUE TITLE
Cannot have slash in model name

### ISSUE THREAD

**Issue by terrykong** [tensorflow/serving#1726]
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow Serving installed from (source or binary)**:
- **TensorFlow Serving version**:
Using docker image `tensorflow/serving:2.2.0-rc2-devel`

### Describe the problem

I'm having trouble getting the RESTful API of the model server working with a model slash in its name. FWIW, this is not an issue over grpc.

The model's name is `debug/saved_model_half_plus_two_cpu` (the model used was this one https://github.com/tensorflow/serving/tree/master/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_two_cpu/00000123)

If the RESTful request is 
```
http://localhost:18196/v1/models/debug/saved_model_half_plus_two_cpu
```
then obviously this fails with error message:
```
{
"error": "Malformed request: GET /v1/models/debug/saved_model_half_plus_two_cpu"
}
```
because `/` is not escaped. If I do escape it in this request:
```
http://localhost:18196/v1/models/debug%2Fsaved_model_half_plus_two_cpu
```
then I get this error
```
{
"error": "Could not find any versions of model debug%2Fsaved_model_half_plus_two_cpu"
}
```

Is there a way to allow slashes in the model name? I have a few cases where it makes sense to naturally scope models the same way they are scoped on the file system/object store.

### Exact Steps to Reproduce
Please include all steps necessary for someone to reproduce this issue on their
own machine. If not, skip this section.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached. Try to provide a reproducible test case that is the bare
minimum necessary to generate the problem.

**Comment by terrykong** [comment]
Hi! Just curious if there is an update or workaround to this?

**Comment by guanxinq** [comment]
The Restful API now does not support slash in model name to simplify the parsing process. We will add the support asap.

**Comment by netfs** [comment]
@guanxinq any updates?
