### ISSUE TITLE
[Feature Request]  How to build serving static and shared lib? this feature is much more useful.

### ISSUE THREAD

**Issue by mocowo** [tensorflow/serving#1732]
Hi,
I'm trying to build a serving lib by blade build tensorflow_serving/model_servers:server_lib. It really generates statitc and shared libs, such as libserver_lib.a and libserver_lib.so . But, these libs can not work, becuase they lack some tensorflow libs. Then, I also build tensorflow_cc.so and tensorflow_framework.so lib and put all of them to my project. It still doesn't work. I use nm cmd to check libserver_lib.a, and find out that it depends on some interface from tensorflow/core/platform which can not be generated to libs from tensorflow build rules.

So, I request two features :
1. Generate a monolithic serving lib with all tensorflow interface integrated.(of course, no need to integrate other third_party such as protobuf)
2. Generate a serving lib along with all depended tensorflow libs are also generated. That is, a serving lib and some tf libs depended by serving.

I prefer the second feature, beacause It's more useful. In some cases, I do some experiments or add some features on serving by changing source code. so, I need to rebuild serving, maybe don't use blade. In those cases, the whole  lib deps is more powerful and easy to use.

By the way, in fact, docker installation is hardly used, because most scenarios are microservices.

**Comment by mocowo** [comment]
any body home?  I was waiting for a serving lib for decades. GOD! anybody can hurry up?  serving lib of static and dynamic.

**Comment by loadingvx** [comment]
@mocowo 

Any more progress for sharing? help~~

**Comment by yimingz-a** [comment]
Hi @loadingvx @mocowo

Apologize this issue slipped through the crack. Since this is a feature request, let me bring this up to the team and confirm the best way forward to support it.
In the meanwhile if you are interested in contributing to the project, you're more than welcomed to send a PR and we'll be happy to review it.

Thanks!

**Comment by singhniraj08** [comment]
@mocowo,

[Dockerfile.devel](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel) and [Dockerfile.devel-gpu](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel-gpu) are minimal VM with all of the dependencies needed to build TensorFlow Serving or TensorFlow Serving with GPU support. You can also build your custom docker image from DockerFile. Also, if there is a need of serving lib along with all depended tensorflow libs,  you're more than welcomed to send a PR and we'll be happy to review it.

Please let us know if that helps. Thank you!
