### ISSUE TITLE
High delay on predictions when the host is connected to a network that hasn't internet connection

### ISSUE THREAD

**Issue by denisb411** [tensorflow/serving#1733]
When I try to make inferences to a object detection model (tf-od api faster_rcnn_resnet101, generated from tf 1.x) and the computer is connected to a network but it's not connected to the internet, causes the predictions to be **way** slower, without any warning or error on the serving's docker container.

If connected to the internet:
![image](https://user-images.githubusercontent.com/13735079/93256945-86e97280-f772-11ea-8778-3a3914863e13.png)

If connected to a network that doesn't has internet connection:
![image](https://user-images.githubusercontent.com/13735079/93257344-13943080-f773-11ea-8cc7-15ceffffd5cc.png)

Docker logs of serving's container doesn't show anything related:
![image](https://user-images.githubusercontent.com/13735079/93258400-9e295f80-f774-11ea-83f8-b46e6e343d14.png)

To reproduce the fault: 

1. Download [this](https://github.com/denisb411/tfserving-od/blob/master/inference-using-tfserving-docker.ipynb) notebook and it's dependencies;
2. Execute all cells and check if it's everything ok;
3. Connect to a network without internet connection (on my case I used a router);
4. Execute the serve and prediction cells and check the problem reported.

Currently I'm using an object detection model produced by tensorflow version <2, tensorflow 2.3.0-gpu (docker image tensorflow/serving:2.3.0-gpu) and Python 3.6 along with Ubuntu 18.04.

**Comment by gowthamkpr** [comment]
DId yo check with tensorflow 1.15 and see the same delay? Thanks!

**Comment by denisb411** [comment]
@gowthamkpr do you mean tensorflow-serving 1.15?

**Comment by denisb411** [comment]
@gowthamkpr sorry it was a mistake when I mentioned tf 1.5 for the model. It is tf 1.15.
In this case I use tf 1.15 if I want to load the model and make predictions manually. I think that the tf version doesn't affect the tf-serving performance.

**Comment by lilao** [comment]
Did you send the request after the server finished startup and started to accept requests?

If so, can you send a few more requests after the first request to see if the latency problem is only for the first request or for all requests?

**Comment by denisb411** [comment]
> Did you send the request after the server finished startup and started to accept requests?
> 
> If so, can you send a few more requests after the first request to see if the latency problem is only for the first request or for all requests?

Yes. If I run the predictions on an infinite loop and switch between the scenarios the behavior switchs together, i.e. while running an infinite loop, without any interference on execution, if I disconnect from internet results are high delayed but if I connect back the delay is gone. I can switch this n times and keep this behavior.

I can simulate this, just tell me the instructions.

**Comment by lilao** [comment]
To confirm: if you run the predictions on an infinite loop without internet connection, all the requests have high latencies? If so, this seems like a problem with your network. Can you measure the network latency between the client and server (for example, by using "ping" command)?

**Comment by rmothukuru** [comment]
@denisb411,
Can you please respond to @lilao's comment. Thanks!

**Comment by denisb411** [comment]
@lilao Yes! Very high latency when connected to a network but no internet connection. I've tested this on two different computers (both Ubuntu 18.04) connected with two different networks and the problem still occurred.

I've managed to solve this problem with docker + docker-compose. Both server and client are now on containers sharing the same docker network and the problem gone away.

**Comment by lilao** [comment]
Thanks @denisb411 for the update!

**Comment by denisb411** [comment]
@lilao just noting that the problem still exists. I see that the Docker solution is just a workaround.
