### ISSUE TITLE
Update from the TF 1.14 version

### ISSUE THREAD

**Issue by sonfire86** [tensorflow/serving#1734]
Im used tf serving 1.14.
They plan to upgrade to version 2.X. Do I need to update the models on the server?

**Comment by rmothukuru** [comment]
@sonfire86,
Yes, you have to migrate your code from `Tensorflow Version 1.x to 2.x` and then `Save` the `Models` with the `new Version`. Please find the [migration guide](https://www.tensorflow.org/guide/migrate). Thanks!

**Comment by sonfire86** [comment]
@rcompton But the manipulation works for me without these.
I am migrating models from `tf serving 1.X` to `tf serving 2.X` And I get the same results.

**Comment by rmothukuru** [comment]
@sonfire86, 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
