### ISSUE TITLE
Is it feasible to serve a tflite model by TF-Serving on PC？

### ISSUE THREAD

**Issue by le8888e** [tensorflow/serving#1736]
Hi,

I convert a pb model to tflite model and tflite runs faster on PC's CPU.
I'm wondering can I serve a tflite model by TF-Serving on PC？

Thank you

**Comment by rmothukuru** [comment]
@le8888e,
No. For the `Model` to be served using `TF Serving`, the `Servable` should be in `TF Saved Model Format (.pb)`.

**Comment by rmothukuru** [comment]
@le8888e,
Closing the issue as it has been resolved in https://github.com/tensorflow/tensorflow/issues/43270. Thanks!

**Comment by ai2ys** [comment]
> @le8888e, No. For the `Model` to be served using `TF Serving`, the `Servable` should be in `TF Saved Model Format (.pb)`.

Apparently, it is possible to use a TF-Lite model using TF Serving:

[https://github.com/tensorflow/serving/blob/bbaa5a7165e06dd76f8f14691c0eb79d15b9d4fa/tensorflow_serving/model_servers/main.cc#L262%0A](https://github.com/tensorflow/serving/blob/bbaa5a7165e06dd76f8f14691c0eb79d15b9d4fa/tensorflow_serving/model_servers/main.cc#L262%0A)
