### ISSUE TITLE
Error: NodeDef mentions attr 'config_proto' not in Op<>

### ISSUE THREAD

**Issue by trantuan010692** [tensorflow/serving#1737]
I got below error when I deploy tensorflow model on sageMaker.
`2020-09-22 09:32:19.647978: E external/org_tensorflow/tensorflow/core/framework/op_segment.cc:54] Create kernel failed: Invalid argument: NodeDef mentions attr 'config_proto' not in Op<name=StatefulPartitionedCall; signature=args: -> output:; attr=Tin:list(type),min=0; attr=Tout:list(type),min=0; attr=f:func; is_stateful=true>; NodeDef: {{node StatefulPartitionedCall_2}} = StatefulPartitionedCall[Tin=[DT_STRING, DT_RESOURCE, DT_RESOURCE, DT_RESOURCE, DT_RESOURCE, ..., DT_RESOURCE, DT_RESOURCE, DT_RESOURCE, DT_RESOURCE, DT_RESOURCE], Tout=[DT_STRING], _collective_manager_ids=[], _output_shapes=[[]], _read_only_resource_inputs=[], config_proto="\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0002\002J\0008\001\202\001\000", f=__inference__traced_restore_2304[], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_saver_filename_0_0, dense/kernel, dense/bias, dense_1/kernel, dense_1/bias, dense_2/kernel, dense_2/bias, SGD/iter, SGD/decay, SGD/learning_rate, SGD/momentum, total, count, total_1, count_1). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).`

It seems problem from serving system.
Please give me suggest to fix this problem!

I tried to follow this tutorial:
https://aws.amazon.com/vi/blogs/machine-learning/deploy-trained-keras-or-tensorflow-models-using-amazon-sagemaker/

**Comment by gowthamkpr** [comment]
@trantuan010692 This looks like a versioning issue. What version of tensorflow and tensorflow are you using to build and deploy the model?

**Comment by trantuan010692** [comment]
@gowthamkpr Thank for your reply.
`sagemaker_model = sagemaker.tensorflow.serving.Model(model_data = 's3://bucket-test-12345-tuan1/model/model.tar.gz',
                                  role = role,
                                  framework_version = '1.12',
                                  entry_point = 'train.py')`
-> I think I'm using 
+ tensorflow serving : 1.12
+ tensorflow: 2.3.0

**Comment by gowthamkpr** [comment]
Use the latest version of Tensorflow serving as Tensorflow servion 1.12 doesn't support tensorflow 2.3.0

**Comment by trantuan010692** [comment]
Thanks for your help!
I could deploy model.
Love your team (heart)
