### ISSUE TITLE
Temporary network failures in loading new gs:// models cause old model to still be served

### ISSUE THREAD

**Issue by pselden** [tensorflow/serving#1738]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Kubernetes running on GKE
- **TensorFlow Serving installed from (source or binary)**: Using public docker image: `tensorflow/serving:2.3.0`
- **TensorFlow Serving version**: 2.3.0

### Describe the problem
We have our models hosted on google cloud storage and we have a promotion process that does a `gsutil cp` from our staging bucket to our production model bucket.

Sometimes when this process happens, our kubernetes node that is running tensorflow serving will be unable to reach google cloud storage and will show an error in the log [1]

Instead of retrying at some point later, tensorflow serving will happily continue to serve the old model and never attempt to retry the load of the new model later on.

### Exact Steps to Reproduce

1. Have a model config like:
```
model_config_list: {
  config: {
    name: "my-model",
    base_path: "gs://my-prod-models/my-model,
    model_platform: "tensorflow",
  },
}
```

2. Push a new model version to that gcs bucket
3. Somehow reproduce a network error (not quite sure how to do this... maybe with a host file to blackhole www.googleapis.com).
4. Observe that the old model is still being served.

### Source code / logs

[1]
```
2020-09-23 04:07:18.306397: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:362] FileSystemStoragePathSource encountered a filesystem access error: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'www.googleapis.com'
	 when reading gs://my-prod-models/my-model
2020-09-23 04:09:08.489447: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:362] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path gs://my-prod-models/my-model for servable my-model
```

**Comment by pselden** [comment]
I see that there are a few parameters that should be able to recover from this:

```
  // Maximum number of times we retry loading a model, after the first
    // failure, before we give up.
    //
    // If set to 0, a load is attempted only once.
    int32 max_num_load_retries = 5;

    // The interval, in microseconds, between each servable load retry. If set
    // negative, we don't wait.
    // Default: 1 minute.
    int64 load_retry_interval_micros = 1LL * 60 * 1000 * 1000;

    // Time interval between file-system polls, in seconds.
    int32 file_system_poll_wait_seconds = 30;
```

I don't have any of these set, but the defaults should already handle it yeah?

**Comment by shadowdragon89** [comment]
Could you verify if the network/storage issue last less than the time window of the retry?

One thing you can do is to check the model version after your update and retry the update if the model version is not updated successfully.

**Comment by pselden** [comment]
I can confirm that if the network issue is resolved before the retry window elapses it recovers, but if it does not, then it will never recover until a new version is uploaded and it tries again.

I confirmed this locally just by turning off/on my wifi during a load.

**Comment by shadowdragon89** [comment]
Thanks for verifying it. The behavior is expected. Could I know if the previous suggestion works for you?

**Comment by pselden** [comment]
We run this in Kubernetes so new machines come up and down constantly. I think to implement this logic we need custom code running along side the tensorflow serving pod which does that check. At that point though I would just have the code do the pulling itself into a local volume and not use the GCS file system at all.

Is there a way to increase the time it will try? The outages usually don’t last longer than a couple minutes.

**Comment by shadowdragon89** [comment]
I think you have pointed out the options in your previous comment, and you could find related flags defines here:
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc#L107
