### ISSUE TITLE
Is there a tf-serving document updated for tf2 ? 

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/serving#1739]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
[https://www.tensorflow.org/tfx/serving/serving_advanced](https://www.tensorflow.org/tfx/serving/serving_advanced)

## Description of issue (what needs changing):

This documment use tf1 function , Is there a new version for tf2 ?

**Comment by FatimahAdwan** [comment]
yes, tf2.2.0. check that out if you havent yet

**Comment by arghyaganguly** [comment]
@DachuanZhao , [doc](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple) is updated with tensorflow==2.4.1
