### ISSUE TITLE
Is there an implementation of Restful API in C++?

### ISSUE THREAD

**Issue by muween** [tensorflow/serving#1741]
Unlike the gRPC API, there is only  Restful API in Python, but I need an implementation in C++. Is there an example?

**Comment by gowthamkpr** [comment]
As mentioned in this [comment](https://github.com/tensorflow/serving/issues/1344#issuecomment-491124784), you can implement your client based on it.

**Comment by rmothukuru** [comment]
@muween,
Can you please respond to @gowthamkpr's comment. Thanks!

**Comment by muween** [comment]
> @muween,
> Can you please respond to @gowthamkpr's comment. Thanks!

The problem has been solved.
