### ISSUE TITLE
is there a way to access assets files over REST/GRPC API just like model metadata? 

### ISSUE THREAD

**Issue by amishra123** [tensorflow/serving#1743]
hi all, i wish to be able to access assets folder under a model with REST/GRPC API endpoint? Please let me know if it's supported. like http://localhost:8500/v1/models/foo/1/assets

**Comment by gowthamkpr** [comment]
@amishra123 It is not supported. You cannot access assets file over grpc or rest API endpoint.

**Comment by rmothukuru** [comment]
@amishra123,
Can you please respond to @gowthamkpr's comment. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again. Thanks!
