### ISSUE TITLE
TF Serving with Eager Execution or @tf.funtion

### ISSUE THREAD

**Issue by le8888e** [tensorflow/serving#1745]
Hi,

I'm wondering TF Serving runs inference with Eager Execution or @tf.funtion by default? Cause there is performance gap between them. 

Thank you

**Comment by gowthamkpr** [comment]
@le8888e Can you please explain in detail. Also can you provide an example if possible. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
