### ISSUE TITLE
How to get intermediate layer output from model using tensorflow serving at the client side?

### ISSUE THREAD

**Issue by muween** [tensorflow/serving#1746]
I want to get the intermediate lay output from my trained model using tensorflow serving at the client side using http or grpc.

**Comment by rmothukuru** [comment]
@muween, 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment]
@muween,
Can you please respond to the above comment. Thanks!

**Comment by muween** [comment]
> @muween,
> Can you please respond to the above comment. Thanks!

The problem  has been solved #338
