### ISSUE TITLE
Can the model status be included in the prediction results in RESTful method?

### ISSUE THREAD

**Issue by muween** [tensorflow/serving#1747]
While use grpc, the results of prediction from tf serving server contains the model status, like this
```

outputs {
  key: "y"
  value {
    dtype: DT_FLOAT
    tensor_shape {
      dim {
        size: 1
      }
      dim {
        size: 1
      }
    }
    float_val: 0.0007048547267913818
  }
}
model_spec {
  name: "recommended"
  version {
    value: 12
  }

  signature_name: "serving_default"
}

```
Could the restful way do this?

**Comment by muween** [comment]
`GET http://host:port/v1/models/${MODEL_NAME}[/versions/${VERSION}|/labels/${LABEL}]`
I don't want to use this way. The client knows the model status while receive the response by the way would be better.

**Comment by rmothukuru** [comment]
@muween,
Can you please elaborate on the statement,

> I don't want to use this way. The client knows the model status while receive the response by the way would be better.

Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
