### ISSUE TITLE
CI and binaries availability for s390x/big-endian machine

### ISSUE THREAD

**Issue by Sidong-Wei** [tensorflow/serving#1749]
### Describe the problem the feature is intended to solve
Hi, I am porting TensorFlow Serving to s390x architecture (a big-endian arch), and I have successfully built it from source and run the test cases. I just want to check whether it is possible to include s390x into CI buildand binary release.

On the CI side, `serving` seems to have one public CI (the google cloud one), and it seem to be running on a x86_64 ubuntu machine, so I am wondering is there any chance that I could help with include s390x into CI build?
On the binary side, it seems that binaries are only available for x86_64 arch, even the `tensorflow-model-server-universal` binary version is not working on s390x. I would also like to know if it is possible to have another binary version available.

### Describe the solution
Please let me know whether it is possible to include s390x arch into CI build and/or binary release; and if the community is interested in this proposal, I would love to provide any help and support that could make it happen, thanks a lot.

**Comment by netfs** [comment]
please see this comment:

https://github.com/tensorflow/serving/issues/1750#issuecomment-736978274
