### ISSUE TITLE
Enable Docker multi-architecture build and image for Tensorflow Serving

### ISSUE THREAD

**Issue by rposts** [tensorflow/serving#1750]
### Describe the problem the feature is intended to solve
Currently Tensorflow Serving images available at [Dockerhub](https://hub.docker.com/r/tensorflow/serving/tags/) are `linux/amd64` arch specific.  It would be nice to enable multi-arch images for other architectures such as s390x.

### Describe the solution
Enable multi-arch build for Tensorflow Serving docker images

### Describe alternatives you've considered
As of now Docker images have to be built using `docker build` on the Dockerfiles available [here](https://github.com/tensorflow/serving/tree/master/tensorflow_serving/tools/docker)

We are able to build Tensorflow Serving docker image on s390x arch based on [this](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel) Dockerfile so I think it is possible.

I would like to understand the feasibility of enabling this support and ultimately integrating it with Tensorflow Serving CI.

Thanks in advance for any help.

**Comment by netfs** [comment]
We presently do not have resources to support releasing official s390x images as part of TF serving release.

Note, supporting s390x will require supporting both TF Serving and TF on this platform. I do not think s390x is supported by official TF releases either. Having said that, you are more than welcome to build+publish s390x images to docker hub using TF Serving sources. And if we see widespread adoption, we can consider folding that into TF serving release (but that will be a while).
