### ISSUE TITLE
Bazel build fails for CUDA 11.1

### ISSUE THREAD

**Issue by BorhenJlidi** [tensorflow/serving#1751]
## Bug Report
When I try to build tensorflow serving either with docker build or locally with support for CUDA 11.1 (for RTX 30) it doesn't recognize this symbol 'cublasLtMatmulPreferenceCreate@@libcublasLt.so.11'.

The BUILD file where the error is produced is this : /home/ubuntu/.cache/bazel/_bazel_datavision/b3af3e0170c13b4be6cb825231e2f120/external/org_tensorflow/tensorflow/compiler/mlir/tools/kernel_gen/BUILD
Specifically in this section : 

`tf_cc_binary(
    name = "tf_to_gpu_binary",
    srcs = ["tf_to_gpu_binary.cc"],
    visibility = [
        "//tensorflow/compiler/mlir/tools/kernel_gen/tests/tf_to_gpu_binary:__pkg__",
        "//tensorflow/core/kernels/mlir_generated:__pkg__",
    ],
    deps = [
        ":kernel_creator",
        "//tensorflow/compiler/mlir:init_mlir",
        "//tensorflow/compiler/mlir/tensorflow",
        "//tensorflow/core:lib",
        "//tensorflow/stream_executor/lib",
        "@com_google_absl//absl/strings",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:Pass",
    ],
)`

### System information
Ubuntu 20.04
CUDA 11.1
CUDNN 8.0.4.30
tensorflow serving (cloned latest commit from master)
Bazel 3.6.0
My .bashrc :
`#CUDA  & TensorRT

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.1/lib64:/usr/local/cuda-11.1/include:/usr/local/TensorRT-7.2.0.14:/usr/local/TensorRT-7.2.0.14/include:/usr/local/TensorRT-7.2.0.14/lib
export PATH=/usr/local/cuda-11.1/bin${PATH:+:${PATH}}
export LIBRARY_PATH=/usr/local/cuda-11.1/lib64\${LIBRARY_PATH:+:${LIBRARY_PATH}}`
### Exact Steps to Reproduce
clone latest tensorflow serving from github and run this :
`bazel build --color=yes --curses=yes --config=cuda --copt="-fPIC"   --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     --config=release     tensorflow_serving/model_servers:tensorflow_model_server
`

### Source code / logs
 Bazel error output:
`ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/b3af3e0170c13b4be6cb825231e2f120/external/org_tensorflow/tensorflow/compiler/mlir/tools/kernel_gen/BUILD:86:13: Couldn't build file external/org_tensorflow/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary: Linking of rule '@org_tensorflow//tensorflow/compiler/mlir/tools/kernel_gen:tf_to_gpu_binary' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/ubuntu/.cache/bazel/_bazel_ubuntu/b3af3e0170c13b4be6cb825231e2f120/execroot/tf_serving && \
  exec env - \
    LD_LIBRARY_PATH=:/usr/local/cuda-11.1/lib64:/usr/local/cuda-11.1/include:/usr/local/TensorRT-7.2.0.14:/usr/local/TensorRT-7.2.0.14/include:/usr/local/TensorRT-7.2.0.14/lib \
    PATH=/home/ubuntu/.local/bin:/usr/local/cuda-11.1/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/host/bin/external/org_tensorflow/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary-2.params)
Execution platform: @local_execution_config_platform//:platform
/usr/bin/ld: bazel-out/host/bin/external/org_tensorflow/tensorflow/stream_executor/cuda/libcublas_plugin.lo(cuda_blas.o): undefined reference to symbol 'cublasLtMatmulPreferenceCreate@@libcublasLt.so.11'
/usr/bin/ld: /usr/local/cuda-11.1/lib64/libcublasLt.so.11: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status`

**Comment by BorhenJlidi** [comment]
@nrobeR Any other method to use tensorflow serving with gpu support for RTX 3080 would be sufficient.

**Comment by guanxinq** [comment]
The docker file Dockerfile.devel-gpu could build the GPU image with CUDA 11.0. However, it has not been upgraded to CUDA 11.1.  The NVIDIA’s nvcc sm flags for RTX 3080 is SM_86, compute_86, which is not covered in the docker image.

**Comment by guanxinq** [comment]
@BorhenJlidi, could you try to build the GPU Docker image with Dockerfile.devel-gpu? Theoretically, it should work with RTX 3080.

**Comment by BorhenJlidi** [comment]
@guanxinq I've built TF serving successfully once TensorRT for CUDA 11.1 was released. Yet there are some differences between images built with Dockerfile.devel-gpu and Dockerfile.gpu like entrypoint. For the meantime, I have to start containers then exec the model servers and it's a pain pulling the image across nodes due to large size (26Gb). Could you shed some light on the release date for the image official build on Docker hub?

**Comment by guanxinq** [comment]
@BorhenJlidi Did you mean the release date for image which is built with CUDA 11.1? For the TF Serving 2.4.0, we might target  on CUDA 11.0 and SM_86 might not be included.  When TF 2.4.0 is ready, we will start the release for TF Serving 2.4.0.

**Comment by BorhenJlidi** [comment]
@guanxinq Thanks for the heads up, I shall close this issue now.

**Comment by AndreV84** [comment]
Hi guys,
How could I add explicitly path to bazel build execution?
I have cuda 10.2 but bazel build seems missing cuda_runtime.h
is there a way to pass the argument manually somehow?
like 
bazel build --copt -D =/usr/local/cuda/ so that it will pick up the file from the folder specified?

**Comment by NaNAGISaSA** [comment]
Same error occurred, so any ideas to solve this problem?

**Comment by faustomorales** [comment]
I found that using Dockerfile.devel-gpu and Dockerfile.gpu resulted in a working image that functions on an RTX 3080 if I changed:

- All references to 11-0 to 11.1
- Set `TF_TENSORRT_VERSION=7.2.1`
- Set `CUDA=11.1`
- Set the base image for the development image (`Dockerfile.devel-gpu`) to `nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04`
- Set the base image for the runtime image (`Dockerfile.gpu`) to `nvidia/cuda:11.1-cudnn8-runtime-ubuntu18.04`

I also published the image [faustomorales/tensorflow-serving](https://hub.docker.com/repository/docker/faustomorales/tensorflow-serving). Hope this helps others looking for TensorFlow Serving on CUDA 11.1.
