### ISSUE TITLE
[Feature Request] A static url for k8s readiness probe

### ISSUE THREAD

**Issue by BorisPolonsky** [tensorflow/serving#1754]
## Feature Request
If this is a feature request, please fill out the following form in full:

### Describe the problem the feature is intended to solve
I have the need for deploying diffrent sets of models through tensorflow/serving on k8s cluster. K8s features a logic that helps the cluster determine whether a pod (i.e. the container running tensorflow/serving) is ready, via HTTP requests. In the current version of tensorflow-serving (2.3.0) I implement this by defining request url as `<tensorflow_serving_pod_ip>/v1/models/<one_of_the_model_served_via_tf_serving>` in the `yml` file for configuring k8s deployments. This may solution may not be optimal:

In case I have two sets of models without (a single model name in common) served on diffrent tf-serving k8s-deployments. I have to change the request url for readiness probe respectively for these two deployments. It would be helpful if one can determine whether tf-serving is already up and running via http request to some static (i.e. model independent) url like `/v1/readiness` so there's no need to change the readiness configuration in `yml` file when the corresponding model for is renamed/deleted.
### Describe the solution
A static url that accepts `GET` requests and return 200 if the model server is up and running may do the trick. In this context "up and running" means that the model is ready for handling http requests and k8s-services can route http traffics to this container given this signal.  

### Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've
considered.

**Comment by nrobeR** [comment]
Hi Boris, would [GetModelStatus API](https://github.com/tensorflow/serving/blob/5369880e9143aa00d586ee536c12b04e945a977c/tensorflow_serving/apis/model_service.proto#L17) work for your use case?

**Comment by BorisPolonsky** [comment]
> Hi Boris, would [GetModelStatus API](https://github.com/tensorflow/serving/blob/5369880e9143aa00d586ee536c12b04e945a977c/tensorflow_serving/apis/model_service.proto#L17) work for your use case?

Thanks for the reply. Could you please elaborate and tell me how this will opt out the need for configuring `<one_of_the_model_served_via_tf_serving>` accordingly when configuring k8s readiness probe that defines http `GET` requests to `http://<tensorflow_serving_pod_ip>/v1/models/<one_of_the_model_served_via_tf_serving>`?

I don't quite understand your solution. If you are suggesting that I use gRPC for readiness probe, please clarify how I should configure it in my k8s `.yaml` file.

**Comment by BorisPolonsky** [comment]
> Hi Boris, would [GetModelStatus API](https://github.com/tensorflow/serving/blob/5369880e9143aa00d586ee536c12b04e945a977c/tensorflow_serving/apis/model_service.proto#L17) work for your use case?

I discovered a workaround by setting the `--monitoring_config_file=`
and use the static defined in the file:
e.g.
```
prometheus_config {
    enable: true,
    path: "/metrics"
}
```
And set the URL of readiness probe as `/metrics`. This seems to fulfill the need for a static URL for readiness probe (so long as I configure the same URL for prometheus config in all tensorflow-serivng k8s deployments, which is practical for me).

**Comment by BorisPolonsky** [comment]
> > Hi Boris, would [GetModelStatus API](https://github.com/tensorflow/serving/blob/5369880e9143aa00d586ee536c12b04e945a977c/tensorflow_serving/apis/model_service.proto#L17) work for your use case?
> 
> I discovered a workaround by setting the `--monitoring_config_file=`
> and use the static defined in the file:
> e.g.
> 
> ```
> prometheus_config {
>     enable: true,
>     path: "/metrics"
> }
> ```
> 
> And set the URL of readiness probe as `/metrics`. This seems to fulfill the need for a static URL for readiness probe (so long as I configure the same URL for prometheus config in all tensorflow-serivng k8s deployments, which is practical for me).

I immediately regret closing the issue so soon... The problem of the workaround above is that the logs in `/metrics` may be flooded and sending `GET` periodically in readiness probe may consume more network resource due to the length of the body. I think it will be helpful to have static url that declares the readiness of the server with minimal message (i.e. body of http response).

**Comment by phred-unity** [comment]
Has there been any update on this?
