### ISSUE TITLE
[feature request]Docker run as non root

### ISSUE THREAD

**Issue by jingli0118** [tensorflow/serving#1759]
## Feature Request
If this is a feature request, please fill out the following form in full:

### Describe the problem the feature is intended to solve
I am trying to add tensorflow serving in production environment. But find the docker is run as root.
Do we have a option to run as non root?
### Describe the solution
An option to run as non root

Thank you very much

**Comment by lilao** [comment]
Thanks for the feature request. This seems to be more related to docker than tensorflow serving. Can you check docker documentation? Closing this now. Please feel free to reopen if you have any follow up comment.
