### ISSUE TITLE
Why need all models available to serve when the container is started

### ISSUE THREAD

**Issue by njustyangkai** [tensorflow/serving#1767]
## Feature Request
we use multiple models in one container, the model.config is like this:
![image](https://user-images.githubusercontent.com/20183284/98619120-8964e480-233d-11eb-8f67-b4d8ffda208d.png)
the problem is when the container pulled up, we often have only one savedModel file in the model directory, but why tfserving need both models available, otherwise it can not serve?

### Describe the problem the feature is intended to solve
we hope when one model can serve, the restful url is working, no need all models are ready.

### Describe the solution
as above.

### Describe alternatives you've considered
not yet.

### Additional context
our models are independent of each other and do not interfere with each other.

**Comment by rmothukuru** [comment]
@njustyangkai,
TF Serving Documentation about [Model Server Configuration](https://www.tensorflow.org/tfx/serving/serving_config#model_server_configuration)  states :

> However, if you would like to serve multiple models, or configure options like polling frequency for new versions, you may do so by writing a Model Server config file.

This means that your Model with Version 625 will be served first then the Model with Version 626.

**Comment by rmothukuru** [comment]
@njustyangkai,
Can you please respond to the above comment. Thanks!

**Comment by njustyangkai** [comment]
Sorry for reply late. I think i can not get the config you meant, you mean i need to add two Model Server Config file?

**Comment by rmothukuru** [comment]
@njustyangkai,
No. You need only one Config File.

> the problem is when the container pulled up, we often have only one savedModel file in the model directory, but why tfserving need both models available, otherwise it can not serve?

If you want to perform Inference using only 1 Model, you can do it directly without using Config File. Please correct me if I am not understanding your point. Thanks!

**Comment by rmothukuru** [comment]
@njustyangkai,
Can you please respond to the above comment. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
