### ISSUE TITLE
Simplify the implementation of predict server 

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/serving#177]
We're a little confused when we have read the source code of [predict_impl.cc](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/servables/tensorflow/predict_impl.cc). The interface of [prediction_service.proto](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/prediction_service.proto) is great and we use `map<string, TensorProto>` as inputs and `map<string, TensorProto>` as outputs.

The data structs of `predict_impl.cc` look like this.

```
std::vector<std::pair<string, Tensor>> inputs;
std::vector<string> output_tensor_names;
std::vector<Tensor> outputs;
```

I think it would be better to use `std::vector<std::pair<string, Tensor>>` for outputs. The format of inputs and outputs are quite familiar.

**Comment by chrisolston** [comment]
I think it's that way to mimic the API of tensorflow::Session::Run().

**Comment by tobegit3hub** [comment]
I'm not sure if you know what I mean. The data structs of inputs and outputs are the same. We use `std::vector<std::pair<string, Tensor>>` for inputs but `std::vector<string>` and `std::vector<Tensor>` for outputs. It would be great to combine the last two items.

**Comment by chrisolston** [comment]
This is the tensorflow::Session::Run() API:
virtual Status Run(const RunOptions& run_options,
                     const std::vector<std::pair<string, Tensor> >& inputs,
                     const std::vector<string>& output_tensor_names,
                     const std::vector<string>& target_node_names,
                     std::vector<Tensor>* outputs, RunMetadata* run_metadata)

predict_impl.cc calls it like so:
 TF_RETURN_IF_ERROR(
      bundle->session->Run(inputs, output_tensor_names, {}, &outputs));

That's the reason for having output_tensor_names and outputs as separate vectors, rather than a map. It follows from the Session::Run() API.

**Comment by tobegit3hub** [comment]
Thanks @chrisolston for the detailed explain. I knew the Python API for `tf.Session` could support map but not for C++ API. That makes seems if we can only use this in that way.
