### ISSUE TITLE
[New feature] Support serving of custom servables.

### ISSUE THREAD

**Issue by pranavsharma** [tensorflow/serving#1776]
## Feature Request
If this is a feature request, please fill out the following form in full:

### Describe the problem the feature is intended to solve
Can tfserving serve models other than tensorflow? I want to be able to serve models from disparate frameworks using the same server instance. tfserving has a concept of [servables](https://www.tensorflow.org/tfx/serving/custom_servable) that abstract any type of framework configured in a [platform config file](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/config/platform_config.proto#L18). TensorFlow itself is a servable in tfserving. These servables need to be [registered](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/servables/tensorflow/saved_model_bundle_source_adapter.cc#L131) in the source file. However, [no other type of servable is loaded and served other than TensorFlow](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/prediction_service_impl.h#L64). So adding a new servable also requires changes in the core tfserving code, not just implementing a new servable.

I came across [this](https://github.com/tensorflow/serving/issues/163#issuecomment-241917759), but looks like it applies even today.

### Describe the solution
tfserving should serve non-tensorflow servable as well. Allow registration of prediction services other than TensorFlowPredictor [here](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/server.cc#L353). 

### Describe alternatives you've considered
None

**Comment by pranavsharma** [comment]
Other related links that I just came across
* https://github.com/tensorflow/serving/issues/1694
* https://stackoverflow.com/questions/49571655/how-to-publish-custom-non-tensorflow-models-using-tensorflow-serving

**Comment by rmothukuru** [comment]
@pranavsharma,
Can you please confirm if we can close this issue as it's been already tracked in #1694? Thanks!

**Comment by pranavsharma** [comment]
> @pranavsharma,
> Can you please confirm if we can close this issue as it's been already tracked in #1694? Thanks!

Sure, you can close this. Do you've any ETA on this? Thanks!

**Comment by rmothukuru** [comment]
@pranavsharma,
Thank you for confirmation. Regarding ETA, the Status of #1694 has been marked as `Contributions Welcome` which means that the `Serving Engineers` are expecting the `Contribution` from the `Tensorflow Developer Community` for implementing this change.
