### ISSUE TITLE
Build newest version and get "`LoadSessionBundleFromPathUsingRunOptions` was not declared in this scope" error

### ISSUE THREAD

**Issue by yejw5** [tensorflow/serving#178]
I git pull the newest code from git@github.com:tensorflow/serving.git for the generic inference service in serving/tensorflow_serving/model_servers/main.cc. But when I built the example by: bazel build //tensorflow_serving/model_servers:tensorflow_model_server --verbose_failures, I got the error as following:

    ERROR: /home/mi/deeplearning/serving/tensorflow_serving/servables/tensorflow/BUILD:43:1: C++ 
    compilation of rule '//tensorflow_serving/servables/tensorflow:session_bundle_factory' failed: gcc 
    failed: error executing command 
     (cd /home/mi/.cache/bazel/_bazel_mi/847ef9632c0bb1c2ea786b1032f075e4/execroot/serving && \
    exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
    /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-
    relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-
    frame-pointer '-std=c++0x' -MD -MF bazel-out/local-
    fastbuild/bin/tensorflow_serving/servables/tensorflow/_objs/session_bundle_factory/
    tensorflow_serving/servables/tensorflow/session_bundle_factory.pic.d '-frandom-seed=bazel-
    out/local-fastbuild/bin/tensorflow_serving/servables/tensorflow/_objs/session_bundle_factory/
    tensorflow_serving/servables/tensorflow/session_bundle_factory.pic.o' -fPIC -DHAVE_CONFIG_H -
    iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/protobuf -iquote bazel-out/local-
    fastbuild/genfiles/external/protobuf -iquote external/bazel_tools -iquote bazel-out/local-
    fastbuild/genfiles/external/bazel_tools -iquote external/org_tensorflow -iquote bazel-out/local-
    fastbuild/genfiles/external/org_tensorflow -iquote external/farmhash_archive -iquote bazel-out/local-
    fastbuild/genfiles/external/farmhash_archive -iquote external/gif_archive -iquote bazel-out/local-
    fastbuild/genfiles/external/gif_archive -iquote external/highwayhash -iquote bazel-out/local-
    fastbuild/genfiles/external/highwayhash -iquote external/jpeg_archive -iquote bazel-out/local-
    fastbuild/genfiles/external/jpeg_archive -iquote external/png_archive -iquote bazel-out/local-
    fastbuild/genfiles/external/png_archive -iquote external/re2 -iquote bazel-out/local-
    fastbuild/genfiles/external/re2 -iquote external/eigen_archive -iquote bazel-out/local-
    fastbuild/genfiles/external/eigen_archive -iquote external/zlib_archive -iquote bazel-out/local-
    fastbuild/genfiles/external/zlib_archive -isystem external/protobuf/src -isystem bazel-out/local-
    fastbuild/genfiles/external/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -isystem 
    external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260 -isystem 
    bazel-out/local-fastbuild/genfiles/external/farmhash_archive/farmhash-
    34c13ddfab0e35422f4c3979f360635a8c050260 -isystem external/gif_archive/giflib-5.1.4/lib -isystem 
    bazel-out/local-fastbuild/genfiles/external/gif_archive/giflib-5.1.4/lib -isystem external/highwayhash -
    isystem bazel-out/local-fastbuild/genfiles/external/highwayhash -isystem external/jpeg_archive/jpeg
    -9a -isystem bazel-out/local-fastbuild/genfiles/external/jpeg_archive/jpeg-9a -isystem 
    external/png_archive/libpng-1.2.53 -isystem bazel-out/local-
    fastbuild/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local-
    fastbuild/genfiles/external/re2 -isystem external/eigen_archive -isystem bazel-out/local-
    fastbuild/genfiles/external/eigen_archive -isystem external/zlib_archive/zlib-1.2.8 -isystem bazel-
    out/local-fastbuild/genfiles/external/zlib_archive/zlib-1.2.8 -isystem 
    external/org_tensorflow/third_party/gpus/cuda -isystem bazel-out/local-
    fastbuild/genfiles/external/org_tensorflow/third_party/gpus/cuda -isystem 
    external/org_tensorflow/third_party/gpus/cuda/include -isystem bazel-out/local-
    fastbuild/genfiles/external/org_tensorflow/third_party/gpus/cuda/include -fno-canonical-system-
    headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-
    D__TIME__="redacted"' -c tensorflow_serving/servables/tensorflow/session_bundle_factory.cc -o 
    bazel-out/local-
    fastbuild/bin/tensorflow_serving/servables/tensorflow/_objs/session_bundle_factory/
    tensorflow_serving/servables/tensorflow/session_bundle_factory.pic.o): 
    com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    In file included from external/org_tensorflow/tensorflow/core/framework/tensor_shape.h:24:0,
                 from external/org_tensorflow/tensorflow/core/framework/tensor.h:24,
                 from external/org_tensorflow/tensorflow/contrib/session_bundle/signature.h:26,
                 from external/org_tensorflow/tensorflow/contrib/session_bundle/session_bundle.h:24,
                 from ./tensorflow_serving/servables/tensorflow/session_bundle_factory.h:19,
                 from tensorflow_serving/servables/tensorflow/session_bundle_factory.cc:16:
    tensorflow_serving/servables/tensorflow/session_bundle_factory.cc: In member function    
    'tensorflow::Status tensorflow::serving::SessionBundleFactory::CreateSessionBundle(const string&, 
    std::unique_ptr<tensorflow::serving::SessionBundle>*)':
    tensorflow_serving/servables/tensorflow/session_bundle_factory.cc:123:75: error: 
    'LoadSessionBundleFromPathUsingRunOptions' was not declared in this scope
         GetSessionOptions(this->config_), run_options, path, bundle->get()));
                                                                           ^
    external/org_tensorflow/tensorflow/core/lib/core/errors.h:42:43: note: in definition of macro 
    'TF_RETURN_IF_ERROR'
     const ::tensorflow::Status _status = (expr);         \
                                           ^
    Target //tensorflow_serving/model_servers:tensorflow_model_server failed to build

  But when I remove the following code in /home/mi/deeplearning/serving/tensorflow_serving/servables/tensorflow/session_bundle_factory.cc, and I can build successfully:

    TF_RETURN_IF_ERROR(LoadSessionBundleFromPathUsingRunOptions(GetSessionOptions(this->config_), run_options, path, bundle->get()));

  It is like that LoadSessionBundleFromPathUsingRunOptions() function is an api to be implemented in the future but not now. Is the way that delete the code snippet suitable for current release？

**Comment by kirilg** [comment]
It sounds like you ran `git pull` on TensorFlow Serving but the TensorFlow submodule is still the old version that doesn't have LoadSessionBundleFromPathUsingRunOptions (not the version that's currently pinned in TensorFlow Serving).

You can try:
1) `git submodule update --init` Or
2) Clone a new TensorFlow Serving repo which will also pull the right version of TensorFlow: `git clone --recurse-submodules https://github.com/tensorflow/serving`

**Comment by yejw5** [comment]
The first method update the TensorFlow submodule successfully. Thank you! 
And I'll close this issue now. Thanks again.
