### ISSUE TITLE
Dockerfile.devel-gpu fails to build tensorflow_model_server

### ISSUE THREAD

**Issue by Teng-xu** [tensorflow/serving#1781]
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow Serving installed from (source or binary)**: source
- **TensorFlow Serving version**: 2.4.0-rc3

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in
TensorFlow Serving.

I am trying to build the tensorflow_model_server through Dockerfile.devel-gpu, but if fails and reports an error.

### Exact Steps to Reproduce
Please include all steps necessary for someone to reproduce this issue on their
own machine. If not, skip this section.

Build a image using the Dockerfile.devel-gpu and it would fail.
Command: docker build -t tfs_modelserver -f Dockerfile.devel-gpu .

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached. Try to provide a reproducible test case that is the bare
minimum necessary to generate the problem.

The error log:
`ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/tensorflow/compiler/mlir/tools/kernel_gen/BUILD:112:1: Couldn't build file external/org_tensorflow/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_kernel: Linking of rule '@org_tensorflow//tensorflow/compiler/mlir/tools/kernel_gen:tf_to_kernel' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/execroot/tf_serving && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64/stubs:/usr/include/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 \
    PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/host/bin/external/org_tensorflow/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_kernel-2.params)
Execution platform: @local_execution_config_platform//:platform
/usr/bin/ld: bazel-out/host/bin/external/org_tensorflow/tensorflow/stream_executor/cuda/libcublas_plugin.lo(cuda_blas.o): undefined reference to symbol 'cublasLtMatmulPreferenceCreate@@libcublasLt.so.11'
/usr/local/cuda/lib64/libcublasLt.so.11: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Target //tensorflow_serving/model_servers:tensorflow_model_server failed to build`

**Comment by rmothukuru** [comment]
@Teng-xuM,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by Teng-xu** [comment]
> @Teng-xuM,
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

To reproduce the issue, run
`
git clone https://github.com/tensorflow/serving.git 
mkdir docker 
cp serving/tensorflow_serving/tools/docker/Dockerfile.devel-gpu docker 
cd docker && docker build -t tfs_modelserver -f Dockerfile.devel-gpu .
`

**Comment by netfs** [comment]
> > @Teng-xuM,
> > In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
> 
> To reproduce the issue, run
> `git clone https://github.com/tensorflow/serving.git`
> `mkdir docker`
> `cp serving/tensorflow_serving/tools/docker/Dockerfile.devel-gpu docker`
> `cd docker && docker build -t tfs_modelserver -f Dockerfile.devel-gpu . `

are you trying to build from master or `2.4` branch (original report said `2.4.0-rc3`)?

either ways, try this:

`docker build --build-arg TF_SERVING_BUILD_OPTIONS=--config=release --no-cache --pull -t ...`

**Comment by Teng-xu** [comment]
> > > @Teng-xuM,
> > > In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
> > 
> > 
> > To reproduce the issue, run
> > `git clone https://github.com/tensorflow/serving.git`
> > `mkdir docker`
> > `cp serving/tensorflow_serving/tools/docker/Dockerfile.devel-gpu docker`
> > `cd docker && docker build -t tfs_modelserver -f Dockerfile.devel-gpu . `
> 
> are you trying to build from master or `2.4` branch (original report said `2.4.0-rc3`)?
> 
> either ways, try this:
> 
> `docker build --build-arg TF_SERVING_BUILD_OPTIONS=--config=release --no-cache --pull -t ...`

I have tested on both master and r2.4 and both fails, I just tried the command you provided
`docker build --build-arg TF_SERVING_BUILD_OPTIONS=--config=release --no-cache --pull -t tfs_modelserver -f Dockerfile.devel-gpu .`
and it still fails due to the same error: /usr/bin/ld: bazel-out/host/bin/external/org_tensorflow/tensorflow/stream_executor/cuda/libcublas_plugin.lo(cuda_blas.o): undefined reference to symbol 'cublasLtMatmulPreferenceCreate@@libcublasLt.so.11' 
/usr/local/cuda/lib64/libcublasLt.so.11: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by netfs** [comment]
> Can you confirm that whether the docker file is able to build the image without any errors?

our nightly and release image builds (both green, presently) use the same commands and config. its odd why we do not see those errors. can you use images published on [docker hub](https://hub.docker.com/r/tensorflow/serving/tags) for now?

to root cause this further, download the nightly image from docker hub, dump the docker image metadata (that contains the github commit hash used to build that image), clone serving repo and checkout at that hash, and try a build on those sources -- this will be the closest on how the nightly got built (last night, and successfully).

**Comment by Teng-xu** [comment]
> to root cause this further, download the nightly image from docker hub, dump the docker image metadata (that contains the github commit hash used to build that image), clone serving repo and checkout at that hash, and try a build on those sources -- this will be the closest on how the nightly got built (last night, and successfully).

I will try that, but just to make sure if it is a problem with the build commands, can you try to build the image with that dockerfile locally, just to verify it could work.

**Comment by netfs** [comment]
@rmothukuru can you please try build this at your end? thanks!

**Comment by Teng-xu** [comment]
I tired to build the image with ARG TF_SERVING_VERSION_GIT_COMMIT=2.4.0, and it still fails due to the same error, is there anything that I might be missing for the building? And can you please try to build the image locally just to confirm whether it could work properly, thanks.

**Comment by NaNAGISaSA** [comment]
@Teng-xu come across with the same error, have you solved this problem?

**Comment by Teng-xu** [comment]
> @Teng-xu come across with the same error, have you solved this problem?

The issue was tensorrt, you need to export TF_NEED_TENSORRT=1 to fix the error
