### ISSUE TITLE
How to save and localize TF serving logs by day rather than output them to the screen

### ISSUE THREAD

**Issue by muween** [tensorflow/serving#1782]
With` &> my_log &` and `export TF_CPP_MIN_VLOG_LEVEL=3`, I can get a log file. But how to save it by day automatically?

**Comment by netfs** [comment]
use standard linux tools (e.g. `logrotate`) to rotate log files (limited by size, # days etc.).

is is one receipe:
https://serverfault.com/questions/828984/redirect-output-and-log-rotation
