### ISSUE TITLE
TFServing unable to utilise trt_engine_op for TF-TRT optimized ResNet50 model

### ISSUE THREAD

**Issue by AshishSardana** [tensorflow/serving#1784]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow Serving installed from (source or binary)**: Docker Image with GPU
- **TensorFlow Serving version**: 2.3

### Describe the problem

While deploying a TF-TRT optimized model using TFServing, I observe the following warning on the server logs:

`2020-12-10 13:02:29.734882: W external/org_tensorflow/tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:629] TF-TRT Warning: Engine retrieval for input shapes: [[8,224,224,3]] failed. Running native
segment for TRTEngineOp_0`

### Exact Steps to Reproduce

1. Download ResNet 50 SavedModel available [here](https://ngc.nvidia.com/catalog/models/nvidia:rn50_tf_amp_ckpt)
2. Apply TF-TRT optimizations to the saved_model present inside the above-downloaded checkpoint. Use TF 2.3 docker image from [NGC](https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow/tags), pull 20.09-tf2-py3 and run the following command inside the docker container.

```
converter = trt.TrtGraphConverter(
        input_saved_model_dir=FLAGS.saved_model_dir,
        input_saved_model_tags=['serve'],
        input_saved_model_signature_key='serving_default',
        precision_mode="FP32",
        max_workspace_size_bytes=(2 < 32),  # 8,589,934,592 bytes
        maximum_cached_engines=100,
        minimum_segment_size=3,
        is_dynamic_op=False
      )
converter.convert()
converter.save(FLAGS.export_tftrt_dir)
```

Make sure to change the `FLAGS.saved_model_dir` to provide the absolute path to saved_model.pb that you will find in `saved_model/nvidia_rn50_tf_amp/` directory of the extracted checkpoint.
In addition, also change the `FLAGS.export_tftrt_dir` to the absolute path where the optimized protobuf will get saved.

3. Serve the above generated TF-TRT optimized model in TFServing. You will observe the following logs once TFServing is up and running with the model.
[server_logs_before_request.txt](https://github.com/tensorflow/serving/files/5673091/server_logs_before_request.txt)
```
docker run --gpus "1" --rm -it \
   --shm-size=1g \
   --ulimit memlock=-1 \
   --ulimit stack=67108864 \
   -e MODEL_NAME=resnet50 \
   -p8500:8500 \
   -p8501:8501 \
   -p8502:8502 \
   -v $PWD/inference/resnet50/1/model.savedmodel/:/models/resnet50/1/ \
   tensorflow/serving:latest-gpu --enable_batching
```
Make sure to change the path that you're mounting from host inside the container (using `-v` flag) to correspond to where you have exported the TFTRT model, i.e. `FLAGS.export_tftrt_dir`

4. Send a request to this model with input vector of dimension (1,224,224,3). You will observe the above-mentioned warning.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached. Try to provide a reproducible test case that is the bare
minimum necessary to generate the problem.

**Comment by gaikwadrahul8** [comment]
@AshishSardana 

I apologies for the delay and I found some workaround from previous GitHub issue so could you please look into this comment [here](https://github.com/tensorflow/serving/issues/1388#issuecomment-512829968) and I have also added one reference for you [here](https://developer.ibm.com/tutorials/tensorrt-with-tensorflow-serving-on-wml-ce/) 

Please let us know Is it resolving your issue ? if Issue still persists please let us know ?

Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @AshishSardana 

Closing this issue due to lack of recent activity for couple of weeks. Please feel free to reopen the issue or post comments, if you need any further assistance or update. Thank you!
