### ISSUE TITLE
Tensorflow Serving - Error passing image to the server

### ISSUE THREAD

**Issue by gabriel-fsa** [tensorflow/serving#1792]
I managed to get the server to work, but I can't POST the image to my network. My network is a modification of the [example](https://keras.io/examples/vision/captcha_ocr/), and when I post it it gives the following error.

"error": "inputs is a plain value/list, but expecting an object as multiple input tensors required as per tensorinfo_map"

My cliente side is:
```
import requests
import json
import cv2
import numpy as np
from PIL import Image

import nsvision as nv

img = cv2.imread(r'./temp.png')
_, img_encoded = cv2.imencode('.png', img)


headers = {"content-type": "application/json"}


data = json.dumps({"signature_name": "serving_default", "inputs": [img_encoded.tolist()] })

json_response = requests.post(url="http://172.104.198.143:8501/v1/models/API_model:predict", data = data, headers = headers)


print(json_response.text)
```
My signature:
```
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['image'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 200, 50, 1)
        name: serving_default_image:0
    inputs['label'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1)
        name: serving_default_label:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['ctc_loss'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 50, 37)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predictll 
```

**Comment by rmothukuru** [comment]
@gabriel-fsa,
Please refer this [Official Example Code](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_client.py#L125-L155) to perform inference inference using Client File, for Images. Thanks!

**Comment by gabriel-fsa** [comment]
> @gabriel-fsa,
> Please refer this [Official Example Code](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_client.py#L125-L155) to perform inference inference using Client File, for Images. Thanks!

Tks, I was able to make the request, but I need to create my own signature to change the network output in the request. Can you help me ? #1793
