### ISSUE TITLE
Issues Building Dockerfile.devel-mkl

### ISSUE THREAD

**Issue by dcyoung** [tensorflow/serving#1797]
I've encountered some trouble attempting to build Dockerfile.devel-mkl. 
I'm using tag 2.4.0
Build seems to be failing on this step: 
```
# Copy MKL libraries
RUN cp /root/.cache/bazel/_bazel_root/*/external/mkl_linux/lib/* /usr/local/lib
```
https://github.com/tensorflow/serving/blob/2.4.0/tensorflow_serving/tools/docker/Dockerfile.devel-mkl#L126

with error:
```bash
cannot stat '/root/.cache/bazel/_bazel_root/*/external/mkl_linux/lib/*': No such file or directory
```
I can't seem to find the produced lib files anywhere in the intermediate containers.

Any insight?

**Comment by netfs** [comment]
@claynerobison -- can you help? you seem to be the maintainer of this docker file:

https://github.com/tensorflow/serving/blob/af33a247dae5486c712a5001845d06235e5b69d2/tensorflow_serving/tools/docker/Dockerfile.devel-mkl#L19

**Comment by 0400H** [comment]
I also encountered the same issue in v2.4.0. 
It seemed that the compilation was successful, but the link library was actually missing.
Compile successfully after backing to v2.3.0.

**Comment by dcyoung** [comment]
Yeah v2.3.0 seems to work alright. Unfortunately its not a fix for me. I am attempting to migrate to v2.4.0 for other included bug fixes that prevent me from using v2.3.0.

**Comment by dcyoung** [comment]
friendly bump

**Comment by jay-jang** [comment]
I don't have much idea. @claynerobison  or @penpornk (recent commit) would you help it out?

**Comment by penpornk** [comment]
I think @claynerobison is the right person to ask. Also tagging @TensorFlow-MKL.

**Comment by claynerobison** [comment]
Hi, @dcyoung. Thanks for reporting this. With TF 2.4, we removed the dependency on the mkl binaries and build straight from source. We haven't ported that here yet, but will soon after we publish the Intel Optimizations for TF 2.4 binary set. Adding @ashahba (who should probably be the maintainer of this Dockerfile).

**Comment by ashahba** [comment]
I'm looking in this issue now.

**Comment by dcyoung** [comment]
thanks for the update! Looking forward.
