### ISSUE TITLE
docker.md examples should explicitly warn it's opening the service to the internet, or use option for localhost-only ports

### ISSUE THREAD

**Issue by erno** [tensorflow/serving#1798]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **TensorFlow Serving installed from (source or binary)**: source
- **TensorFlow Serving version**: 2.4.0

### Describe the problem

The docker usage examples have a security problem if the user doesn't realize that using docker run -p 8501:8501 opens this up to the internet and even goes out of its way to make a hole in iptables to enable this.

### Exact Steps to Reproduce

Just run the example in the README and try curl'ing the example using your machines non-localhost ip address (or from another amchine)

You can fix this eg by telling Docker to bind to localhost, by docker run -p 127.0.0.1:8501:8501

### Source code / logs

n/a

**Comment by rmothukuru** [comment]
@erno,
Just to be clear, can you please share the link of the example you are referring to? Thanks!

**Comment by erno** [comment]
Sure thing: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md

But now that I searched for "docker run", there seem to be other places with the same problem:
 - https://github.com/tensorflow/serving/blob/db18c54f94ec478d74809bd7a6ec0fd64c6b6dd0/README.md
 - https://github.com/tensorflow/serving/blob/85470f6affd9da917538d2c181e1ff59163ea666/tools/run_in_docker.sh
 - https://github.com/tensorflow/serving/blob/b41a28bb2c815bd76010d3a39a3ea52b5da85f35/tensorflow_serving/g3doc/building_with_docker.md

**Comment by singhniraj08** [comment]
@erno,

Can you try with latest release of Tensorflow serving?
Tensorflow serving with docker uses `localhost` endpoints for predictions api requests, as shown [here](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple#make_rest_requests). Hope this resolves the security problem.
Thank you!
