### ISSUE TITLE
Sagemaker endpoint serving doesnt work for multiple timestep `and` multiple inputs (mulit input-output LSTM)

### ISSUE THREAD

**Issue by abdulbasitds** [tensorflow/serving#1799]
I have a LSTM network that has 3 inputs and 3 outputs(built with [functional api][1] in Tf.keras) , that I am trying to deploy as sagemaker endpoint. I have input shape of (None,10,1) for each input/feature, which means 10 timesteps.(I later concatenate the embeddings, but its irrelevant here) 

Everything works fine on training time on sagemaker training jobs as well and training completes and artifacts are made successfully. But at time of invocation, endpoint is not working to predict `1 example, having 10 timesteps with 3 inputs` , I have tried multiple things but cant provide three inputs for prediction(input_1,input_2,input_1).

As I said that each input has 10 timesteps, so have shape (10,1). Endpoint only returns the output if I format my payload as below, but by doing so, it treats each time-step as separate example/instance and return 10 predictions for each output

    {'inputs':{
               'input_1': [[0], [0], [0], [0], [2], [12], [11], [7], [7], [2]],
               'input_2': [[0], [0], [0], [0], [30], [21], [2], [15], [27], [30]],
               'input_3': [[0], [0], [0], [0], [6], [2], [3], [13], [15], [6]]}
              } # gives len(pred['output_1"])) == 10

This is expected as it consider this request as 10 examples, but in my case it is one example with 10-timesteps for each feature (1,10,1). So I tried different things from the [documentation][2]. Like using instances.

    {'instances': [
                    {
                          'input_1': [[0],[0], [0],[0],[2],[12],[11], [7], [7], [2]],
                          'input_2': [[0], [0], [0], [0], [30], [21], [2], [15], [27], [30]],
                          'input_3': [[0], [0], [0], [0], [6], [2], [3], [13], [15], [6]]
                    }
                  ]
    }

But it gives this error.

>  transpose expects a vector of size 4. But input(1) is a vector of
> size 3\\n\\t [[{{node transpose_1}}]]\\n\\t
> [[functional_1/lstm/PartitionedCall]]\\n\\t
> [[StatefulPartitionedCall/StatefulPartitionedCall]]\"\n}"}"

Document also gives example and says

> for models with multiple named inputs, just include all the keys in the input dict

but when I use this, I get error saying `Missing 'inputs' or 'instances' key\"\n}"`

    {'input_1': [[0], [0], [0], [0], [2], [12], [11], [7], [7], [2]],
     'input_2': [[0], [0], [0], [0], [30], [21], [2], [15], [27], [30]],
     'input_3': [[0], [0], [0], [0], [6], [2], [3], [13], [15], [6]]}

My invocation code is below.

    import boto3
    import json
    
    sm = boto3.client('sagemaker-runtime')    
    endpoint_name = "tensorflow--------------------4"
    response = sm.invoke_endpoint(EndpointName=endpoint_name, 
                                  Body=json.dumps(payload),
                                  ContentType='application/json')

Here is the architecture of the model

![Architecture](https://user-images.githubusercontent.com/33634518/105354704-d5a78d00-5be8-11eb-9dc5-90a2494beb00.png)

I am not sure how to solve this issue, looking forward for help

  [1]: https://keras.io/guides/functional_api/
  [2]: https://sagemaker.readthedocs.io/en/stable/frameworks/tensorflow/deploying_tensorflow_serving.html

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Sagemaker and Ubuntu 20
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.3.1
- Python version: 3.7

**Standalone code to reproduce the issue**

I am not sure about the standalone code as sagemaker endpoint is confidential, but I have created Minimum Reproducible code here

https://colab.research.google.com/drive/1RJ2ou705xfrqjeFGImvMk02lTxfFPZek?usp=sharing

**Comment by abdulbasitds** [comment]
@arghyaganguly , Hi, I am quite sure its a bug in TensorFlow and require a bug tag.

**Comment by arghyaganguly** [comment]
@abdulbasitds , could you please share the output of the input layer and 1,2 layers below that of your LSTM model to help understand/visualize the input format?
Thanks.

**Comment by abdulbasitds** [comment]
@arghyaganguly I have updated this issue and have attached the architecture picture

**Comment by singhniraj08** [comment]
@abdulbasitds,

As shown in [Predict API request format](https://www.tensorflow.org/tfx/serving/api_rest#request_format_2), For multiple named inputs, each item is expected to be an object containing input name/tensor value pair, one for each named input.
In row format input tensor, each named input is implicitly assumed have same 0-th dimension. If you have named inputs that have different 0-th dimension, use the columnar format as shown below.

I was unable to run the colab attached with the issues. Please try to pass your input as shown below and let us know if you face any challenges. Thank you!

Example code to specify input tensor with multiple inputs in columnar format:
```
{
 "inputs": {
   "tag": ["foo", "bar"],
   "signal": [[1, 2, 3, 4, 5], [3, 4, 1, 2, 5]],
   "sensor": [[[1, 2], [3, 4]], [[4, 5], [6, 8]]]
 }
}
```
Note, inputs is a JSON object and not a list like instances.
