### ISSUE TITLE
Versioning to Tensorflow

### ISSUE THREAD

**Issue by promiseofcake** [tensorflow/serving#180]
What is the versioning plan for Tensorflow Serving? Today's updates have pinned the [tensorflow](https://github.com/tensorflow/tensorflow) dependency to a master commit in that repo. Is there a plan to have a `master` > `master` link and then corresponding release branches to pin to, for example, `0.10.0` in serving that works with the `0.10.0` branch in Tensorflow?

Thanks for the work!

**Comment by kirilg** [comment]
Good question. We're currently always tracking TensorFlow at head and update to the latest version as long as we're not broken at current head (otherwise fix and then sync). In the future we may consider branching releases that will continue to work with the corresponding TF releases as you suggested (no concrete plans right now), but we haven't been doing that so far. Is this something you're just curious about or do you have a use case that you'd like supported?

**Comment by LiberiFatali** [comment]
I see a case for this. The function signatures in Tensorflow often change. So when we bring the model trained by newer Tensorflow version to Tensorflow Serving, there would be some mismatches in export process. I experienced this case when trying to deploy Inception_Resnet model, which needs nightly build of Tensorflow.

**Comment by promiseofcake** [comment]
Our use case would be that we have model training / exporting happening on the `r.0.10` branch of TensorFlow on a set of machines and then we'd want to serve that model over TensorFlow Serving. If using a model trained on a previous version of TensorFlow is a non-issue, then the current `HEAD` paradigm would suffice for us. 

@LiberiFatali, if the same model was exported using the appropriate version of TensorFlow for Serving's needs would that address the issue in that case, despite being trained on a different version?

**Comment by LiberiFatali** [comment]
@promiseofcake What do you mean by "appropriate version of TensorFlow for Serving's needs"? Does that mean Serving needs the same Tensorflow version that is used to train the model?

In my case, I go through the export code and change function signatures to fit current Tensorflow version in Serving. Then it works well.

**Comment by kirilg** [comment]
@promiseofcake TensorFlow strives to make all ops changes backwards compatible, so I think your use case should be fine. It could be common that a model may have been trained months ago but we still want it to be served in production on the latest released server. I can imagine some conditions under which this may not be the case and things break, but they should be very rare. To avoid them entirely, you can cut TensorFlow Serving at a certain commit that you know works well and not update until you also decide to update your training. (we'll also consider cutting release branches in the future).

@LiberiFatali Your use case is a bit more tricky, where you actually have newer TensorFlow than TensorFlow Serving. There isn't much of a forward compatibility promise for most ops, so we don't officially support this. It's possible that it'll work, but also possible that things will break. The recommended best practice is to always use TensorFlow Serving that's on the same commit or newer than the TensorFlow you used for training. Given your use case of using the nightly build of TensorFlow, it seems you won't benefit from us cutting release branches that will remain compatible with older TF releases like r0.10, and you'd instead want to use nightly TF serving as well (though even that can be older than TF@head).

**Comment by promiseofcake** [comment]
@kirilg, thanks for the update, appreciate the explanation, that works for us!
