### ISSUE TITLE
Implement API to get current server configuration through gRPC (HandleGetConfigRequest method returning a ModelServerConfig)

### ISSUE THREAD

**Issue by fidel-schaposnik** [tensorflow/serving#1800]
-----------------------
## Feature Request
If this is a feature request, please fill out the following form in full:

### Describe the problem the feature is intended to solve

I cannot access the current servable configuration through gRPC, just update it using `HandleReloadConfigRequest`. I would like to be able to see which models are being served, what their base paths are, etc, before deciding to update the configuration (and possibly use the current configuration as a starting point for the new one).

### Describe the solution

Define a `HandleGetConfigRequest` method in `model_service.proto`, essentially returning the `ModelServerConfig` currently being used by the server.

### Describe alternatives you've considered

One can try to use the model metadata to figure out some of the information in the server configuration, but in particular I currently see no way of obtaining the servable base paths.

**Comment by singhniraj08** [comment]
@fidel-schaposnik,

[Model Service](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/model_service.proto) gRPC API provides methods to query and update the state of the server, e.g. which models/versions are being served. It returns the status of a model in the ModelServer.

Please let us know if this helps your use-case. Thank you!
