### ISSUE TITLE
TF 2.4.1 to 2.3.0 Serving broken for experimental.preprocessing features

### ISSUE THREAD

**Issue by rafiqhasan** [tensorflow/serving#1812]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colab
- **TensorFlow Serving installed from (source or binary)**: Binary
- **TensorFlow Serving version**: 2.4.1( >2.3.0 )

### Describe the problem:
A bug was already opened for [same issue in TFMS 2.3](https://github.com/tensorflow/serving/issues/1720) nearly **6 months back** and still unresolved even in TFMS 2.4.1. There has been no resolution for that bug and I am not sure why TF team is not taking this one seriously. 

While serving a TF 2.4.1( any model >TF2.3 ) trained saved model created with **tf.keras.layers.experimental.preprocessing** features, TMS(Tensorflow model server ) gives error on inference. However inferencing on the model directly( ```model( )``` ) runs absolutely fine without any error, this seems to be something specific to TMS / saved_model_cli

**saved_model_cli** also throws an error that **Op type not registered 'DenseBincount' in binary. Make sure the Op and Kernel are registered in the binary running in this process** but the saved model can still be used without any issues for inferencing using ```model( )``` . If this is not a TMS issue, then can we please route it to correct team for the resolution. This is an overall TF issue and its impossible to serve TF models on GCP AI platform / AWS until this is resolved.

### Exact Steps to Reproduce
1. Run GIST - [Link](https://colab.research.google.com/gist/rafiqhasan/0512b573bdce392c8d2a673c7f8dd345/dl-e2e-structured-mixed-data-tf-2-keras.ipynb)
2. Error on cell - [Link](https://colab.research.google.com/gist/rafiqhasan/0512b573bdce392c8d2a673c7f8dd345/dl-e2e-structured-mixed-data-tf-2-keras.ipynb#scrollTo=vm3PEWoMLjGi&line=9&uniqifier=1)

### Source code / logs
```
import json
import requests

#Create payload
data_py = {"instances":[{'WERKS': ["ML01"],
                         'DIFGRIRD': [-80.0],
                         'SCENARIO': ["3"],
                         'TOTIRQTY': [80.0],
                         'VSTATU': ["1"],
                         'EKGRP': ["A"],
                         'TOTGRQTY': [0.0],
                         'VPATD': [30.0],
                         'EKORG': ["1"],
                         'NODLGR': [0.0],
                         'DIFGRIRV': [-38100.0],
                         'NODLIR': [90.0],
                         'KTOKK': ["1"]}]}

data = json.dumps(data_py)
print("payload: ", data)

#Run request on TMS
headers = {"content-type": "application/json"}
json_response = requests.post('http://localhost:8511/v1/models/model:predict', data=data, headers=headers)
json_response.text
```

Error message:
```
payload:  {"instances": [{"WERKS": ["ML01"], "DIFGRIRD": [-80.0], "SCENARIO": ["3"], "TOTIRQTY": [80.0], "VSTATU": ["1"], "EKGRP": ["A"], "TOTGRQTY": [0.0], "VPATD": [30.0], "EKORG": ["1"], "NODLGR": [0.0], "DIFGRIRV": [-38100.0], "NODLIR": [90.0], "KTOKK": ["1"]}]}
{\n    "error": "Shape must be at most rank 2 but is rank 3\\n\\t [[{{node model/category_encoding_2/bincount/DenseBincount}}]]"\n}
```

CC: @christisg

**Comment by arghyaganguly** [comment]
@rafiqhasan , as per my understanding this issue is a duplicate of [#1720 ](url).
Please confirm on this so that we can close this and  track it in the above link.
Thanks.

**Comment by rafiqhasan** [comment]
Hi @arghyaganguly ,

Although I would not suggest to close this one, as the other issue( #1720 ) was for TF2.3 and has no updates at all since last 6 months( strangely ). 

This one on the other hand is for TF2.4.1 and I opened it just to bring attention that this issue is unattended across series of sub-releases and the GIST attached here is also different. Full analysis was done and attached in #1720 and should be used in this bug as well for fixture.

Thanks,
Hasan

**Comment by rafiqhasan** [comment]
As per comment on #1720 by @DachuanZhao , a workaround here is to use "inputs" rather than the keyword "instances" during TMS inferencing.

The workaround seems to work but then why do saved models without experimental.processing work well with "instances" and why does saved_model_cli give error as stated above.

The difference in the results of "inputs" and "instances" is a good lead here to resolve the issue.

**Comment by gaikwadrahul8** [comment]
@rafiqhasan 

Apologies for the delay and I think this is similar issues like [#1720](https://github.com/tensorflow/serving/issues/1720) and [#2082](https://github.com/tensorflow/serving/issues/2082)


Could you please try Specifying input tensors in column format and In the columnar format, inputs are keyed to `inputs` key rather than `instances` in the JSON request ?

For your reference, I have added official documentation [here](https://www.tensorflow.org/tfx/serving/api_rest#specifying_input_tensors_in_column_format) so please follow it and I hope your issue will be resolved

Please let us know if you need any further assistance?

Thank You!

**Comment by gaikwadrahul8** [comment]
Hi, @rafiqhasan 

Closing this issue due to lack of recent activity for couple of weeks. Please feel free to reopen the issue or post comments, if you need any further assistance or update. Thank you!
