### ISSUE TITLE
GPU docker image massive increase in size from 2.3.0 to 2.4.0

### ISSUE THREAD

**Issue by miguelvr** [tensorflow/serving#1813]
### Describe the problem
The TensorFlow Serving GPU image has more than doubled in size between versions 2.3 and 2.4

Is there a reasonable explanation for this? We currently use these images in Kubernetes, and this has a considerable impact on the start-up time for each deployment.

![image (1)](https://user-images.githubusercontent.com/7456627/108054024-705f8400-704e-11eb-8dfb-163e0a77aa8c.png)

![image](https://user-images.githubusercontent.com/7456627/108054013-6b9ad000-704e-11eb-931f-387ceeef4f65.png)

EDIT: it seems that this is caused by the switch of base image from `nvidia/cuda-base` to `nvidia/cuda-devel`
I don't think the runtime image of TFS needs a development CUDA base image.

This commit seems to be the culprit:
https://github.com/tensorflow/serving/commit/b291c4df771b3a6767782bdcfa086f93512ca182

**Comment by guanxinq** [comment]
Thanks Miguel  for reporting this. Updated the docker image build files in commit 5a0dfd9468d718da1bd39687da0f80fe489ea0af, which reduced the size.

**Comment by kr-ish** [comment]
@miguelvr thank you for investigating and @guanxinq thank you for this fix! I'm seeing that the file size is now reduced but is still significantly larger for both the devel and the main GPU images.

<img width="1266" alt="Screen Shot 2021-03-11 at 1 22 23 AM" src="https://user-images.githubusercontent.com/12648956/110744961-8d7c1280-8208-11eb-8143-fde6981d948c.png">
<img width="1266" alt="Screen Shot 2021-03-11 at 1 22 46 AM" src="https://user-images.githubusercontent.com/12648956/110744978-91a83000-8208-11eb-9b0b-57104cfa2b09.png">

I'm not seeing any other changes between the 2.3.0 and 2.4.0 branches that stand out as potential causes of this- my best guess is the updated libraries are just that much heavier. Do either of you have any other ideas?
