### ISSUE TITLE
Error while compiling - _pywrap_tensorflow.so

### ISSUE THREAD

**Issue by pldelisle** [tensorflow/serving#182]
Hi. 

I'm running a Docker environment on CentOS. I successfully built the container from the official Dockerfile [https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel](url)

I followed the instructions for compiling using` bazel build tensorflow_serving/...`

But I get the following error : 

`ERROR: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/org_tensorflow/tensorflow/python/BUILD:1732:1: Linking of rule '@org_tensorflow//tensorflow/python:_pywrap_tensorflow.so' failed: gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/serving && \
  exec env - \
  /usr/bin/gcc -shared -o bazel-out/local-fastbuild/bin/external/org_tensorflow/tensorflow/python/_pywrap_tensorflow.so -Wl,--version-script external/org_tensorflow/tensorflow/tf_version_script.lds -pthread -Wl,-no-as-needed -B/usr/bin -B/usr/bin -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S -Wl,@bazel-out/local-fastbuild/bin/external/org_tensorflow/tensorflow/python/_pywrap_tensorflow.so-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 72.245s, Critical Path: 54.08s
`

Image : Ubuntu 14.04 LTS in Docker.
Building without GPU support. 
Using Bazel 0.3.1, GCC 4.8.4, Python 2.7.6

How can I resolve this error ?

Thank you very much.

**Comment by kirilg** [comment]
I wonder if it's another manifestation of the error fixed [here](https://github.com/tensorflow/serving/pull/183). The dockerfile used Bazel 0.3.0 but you say you used 0.3.1. Do you mean you manually updated [this line](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel#L59) before the fix PR was submitted? If not, the Bazel version that was used inside Docker was different from the one you may have installed on your machine, and it was still using 0.3.0 which had some issues. Could you please give it a try again now using the latest dockerfile (you'll need to rebuild the image and sync/reclone TensorFlow Serving)?

**Comment by pldelisle** [comment]
I tried compiling using Bazel 0.3.0 and it didn't work, bugging at the very beginning of the compilation.
That's why I installed Bazel using the binary file available on Github, and it passes until near the end of the compilation where this error pops in.
I'll try the dockerfile you said, but since I'm already using 0.3.1 version of Bazel inside the Docker Container (I confirm I had installed the binary inside the container itself), I doubt this will change anything. 
Thanks a lot for your help. Will try this and qill give you an update.

**Comment by pldelisle** [comment]
Tried recompiling it in two different containers. One on RHEL 7.2, the other on a CentOS 7. Both OS are virtualized with vSphere 5.5 and runs on different hosts. Both containers are failing at different points during the compilation. 

The first one, on CentOS gives me this error now : 
`ERROR: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/org_tensorflow/tensorflow/core/kernels/BUILD:1079:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:svd_op' failed: gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/serving && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/local-fastbuild/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/svd_op/external/org_tensorflow/tensorflow/core/kernels/svd_op.pic.d '-frandom-seed=bazel-out/local-fastbuild/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/svd_op/external/org_tensorflow/tensorflow/core/kernels/svd_op.pic.o' -fPIC -DHAVE_CONFIG_H -iquote external/org_tensorflow -iquote bazel-out/local-fastbuild/genfiles/external/org_tensorflow -iquote external/protobuf -iquote bazel-out/local-fastbuild/genfiles/external/protobuf -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -iquote external/com_googlesource_code_re2 -iquote bazel-out/local-fastbuild/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/local-fastbuild/genfiles/external/farmhash_archive -iquote external/gif_archive -iquote bazel-out/local-fastbuild/genfiles/external/gif_archive -iquote external/highwayhash -iquote bazel-out/local-fastbuild/genfiles/external/highwayhash -iquote external/jpeg_archive -iquote bazel-out/local-fastbuild/genfiles/external/jpeg_archive -iquote external/png_archive -iquote bazel-out/local-fastbuild/genfiles/external/png_archive -iquote external/eigen_archive -iquote bazel-out/local-fastbuild/genfiles/external/eigen_archive -iquote external/zlib_archive -iquote bazel-out/local-fastbuild/genfiles/external/zlib_archive -isystem external/protobuf/src -isystem bazel-out/local-fastbuild/genfiles/external/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260 -isystem bazel-out/local-fastbuild/genfiles/external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260 -isystem external/gif_archive/giflib-5.1.4/lib -isystem bazel-out/local-fastbuild/genfiles/external/gif_archive/giflib-5.1.4/lib -isystem external/highwayhash -isystem bazel-out/local-fastbuild/genfiles/external/highwayhash -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local-fastbuild/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local-fastbuild/genfiles/external/png_archive/libpng-1.2.53 -isystem external/eigen_archive -isystem bazel-out/local-fastbuild/genfiles/external/eigen_archive -isystem external/zlib_archive/zlib-1.2.8 -isystem bazel-out/local-fastbuild/genfiles/external/zlib_archive/zlib-1.2.8 -fno-exceptions -DEIGEN_AVOID_STL_ARRAY -pthread -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/org_tensorflow/tensorflow/core/kernels/svd_op.cc -o bazel-out/local-fastbuild/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/svd_op/external/org_tensorflow/tensorflow/core/kernels/svd_op.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
INFO: Elapsed time: 231.967s, Critical Path: 202.18s
`

Just before, here is the Cockpit view: 
![screenshot from 2016-09-20 09 01 27](https://cloud.githubusercontent.com/assets/22298876/18671213/38d7fd74-7f11-11e6-8c81-1dfdf207231d.png)

So I think it's a memory exhaustion error. 

I then tried with the --local_resources 5000,.80,1.0 command argument at compilation after building a brand new container and it finally compiled without error after more than an hour of compilation (longer du to limited CPU and memory resources)

So it all seems to be a memory consumption error. 

The VM had 10 GB RAM, 8 CPU threads. 

You can close the issue.

**Comment by kirilg** [comment]
Thanks for the investigation! Yeah the second error message you had suggests memory limits and that indeed fixed the problem. The first error message was still more of a mystery since I don't see any indications it's a resource problem.

I'll close this issue like you said, but worth following up with the Bazel team to see if we can do something about it in the future. @damienmg we've run into this memory constraint issue in the past where bazel would fail until the user added a manual --local_resources cap. Is there any way for Bazel to auto-discover this so that it doesn't fail when it could have just run slower? In the past it was on a very low memory machine, but here it was necessary to cap to 5G.
