### ISSUE TITLE
Supposed Behavior when folder of a currently used version is overridden

### ISSUE THREAD

**Issue by tianhuat** [tensorflow/serving#1822]
Given TensorFlow serving with one version folder (i.e., folder named `1`); if I override the folder with a new model (though there could be calls to an existing model), what will be the supposed behavior? Would it be

a. All the previous call for the previous model will fail, and the all-new call will use the new model or;

b. All the previous call will redirect to the new model and the new call will use the new model or;

c. All the calls will fail?

I need to know the behavior to decide whether to file an issue.

**Comment by arghyaganguly** [comment]
@tianhuat ,all the previous calls will redirect to new model and the new inference calls will use the new model.

**Comment by arghyaganguly** [comment]
@tianhuat , please confirm whether this issue can be closed.

**Comment by arghyaganguly** [comment]
Please feel free to reopen based on above comments.
Closing this as of now.
