### ISSUE TITLE
Multiple model with one gpu

### ISSUE THREAD

**Issue by tianhuat** [tensorflow/serving#1823]
If I have multiple models but with one GPU, can tensorflow serving allows multiple model to share one GPU? Also how do I enable the usage of GPU - as currently seems like only CPU is used though I have GPU installed (and is used with tensorflow training/inference without problem).

**Comment by arghyaganguly** [comment]
@tianhuat , for serving with GPU please check :- [serving with gpu](https://www.tensorflow.org/tfx/serving/docker#serving_with_docker_using_your_gpu)

**Comment by tianhuat** [comment]
On this link, https://github.com/tensorflow/serving/issues/335, it shows errors for concurrent requests of multiple models on single GPU, has it been fixed?

**Comment by arghyaganguly** [comment]
#335 is referencing to an earlier version of tf(1.1) and tf serving.
As per [comment#335](https://github.com/tensorflow/serving/issues/335#issuecomment-305886225),this was fixed.
Please try out with the latest stable versions and let us know if the issue exists.

**Comment by arghyaganguly** [comment]
This issue has been with the "awaiting response" tag for past 5 days.
Closing this as of now.
Please feel free to reopen with comment if you have questions based on the above trace.
