### ISSUE TITLE
Error while predict: [Not found: No algorithm worked!]

### ISSUE THREAD

**Issue by arthurfortes** [tensorflow/serving#1825]
I'm having the following error when making the prediction:

**Tensorflow Serving error log:**

`2021-03-05 13:03:57.174283: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops.cc:1106 : Not found: No algorithm worked!`

I usually resolve this error using the following code in my applications:

```
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
```

Based on log, GPU was loaded successfuly:

```
2021-03-05 14:59:36.231945: I external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:10:00.0 name: GeForce GTX 1660 computeCapability: 7.5
coreClock: 1.785GHz coreCount: 22 deviceMemorySize: 5.80GiB deviceMemoryBandwidth: 178.86GiB/s

2021-03-05 14:59:36.235748: I external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4859 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1660, pci bus id: 0000:10:00.0, compute capability: 7.5)
```

**GPU and Cuda Info:**

NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2 
GeForce GTX 1660

**Tensorflow version**: 2.4
**Tensorflow Serving**: tensorflow/serving:latest-gpu

**Command to run tf-serving:**

`sudo docker run --gpus all -it -p 8501:8501 -v /home/arthurfortes/Documents/tmp/converted:/models -t tensorflow/serving:latest-gpu --model_config_file=/models/models_docker.conf`

** Request **

`curl -X POST "http://127.0.0.1:5000/services/auto?token=123" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "image=@digital.jpg;type=image/jpeg"
`

**Comment by arghyaganguly** [comment]
@arthurfortes , please provide the code related to tensorflow serving which is causing the error.
The information you have provided is not enough to understand how this issue relates to serving.
Also mention the tensorflow and tensorflow serving versions you are using for your use case.

**Comment by arghyaganguly** [comment]
@arthurfortes , this feels like a gpu memory related bug.
Please check with two alternate probable workarounds to limit gpu memory growth by appending below snippets to your code :
1)First approach :-

```
import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU') tf.config.experimental.set_memory_growth(physical_devices[0], True)
```
2)Second approach :

```
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only allocate 4GB of memory on the first GPU
  try:
    tf.config.experimental.set_virtual_device_configuration(
        gpus[0],
        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=4096)])
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Virtual devices must be set before GPUs have been initialized
    print(e)
```
Observation : even though this error is thrown while doing inference call in serving,it might be related to how memory growth/limit is handled by GPU/GPUs and less to do with actual serving.

**Comment by arghyaganguly** [comment]
@arthurfortes , please confirm whether the above workaround worked.Thanks.
