### ISSUE TITLE
The memory of container is unstable?

### ISSUE THREAD

**Issue by victory-hsu** [tensorflow/serving#1836]
- **Linux Ubuntu 18.04

- **TensorFlow Serving version**:tensorflow/serving:latest-gpu

### Describe the problem
I restart the tensorflow serving service many time, i find the fact that the momory of docker container is unstable, here are the detailed results: **5.025G、7.27G、5.242G、5.464G、6.206G**. I did not  change any code, the total size of my model parameters are 1.5G. Can you tell me why the memory is unstable? The relation between the model parameters and the container memory? Many thanks~

### Exact Steps to Reproduce
Restart the service many time, Observe the container memory

**Comment by arghyaganguly** [comment]
@victory-hsu , would it be possible to provide a model and a set of requests to reproduce the issue?

**Comment by victory-hsu** [comment]
My code demo just like this:
import tensorflow as tf
import grpc
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2_grpc
from tensorflow.python.framework import tensor_util


def do_inference(stub, sequence):
    request = predict_pb2.PredictRequest()
    request.model_spec.name = "safe_danger"
    request.model_spec.signature_name = "danger_classifier"
    request.inputs['padded_sentence'].CopyFrom(tf.make_tensor_proto(sequence, dtype=tf.int32))
    request.inputs['dropout_keep_prob'].CopyFrom(tf.make_tensor_proto(1.0, dtype=tf.float32))
    response = stub.Predict.future(request, 1)
    result = response.result().outputs["label_distribution"]
    label_distribution = tensor_util.MakeNdarray(result)
    return label_distribution


if __name__ == "__main__":
    channel = grpc.insecure_channel("10.2.22.11:9011")  # replace with your own url
    stub = prediction_service_pb2_grpc.PredictionServiceStub(channel)
    test_sequence = [[4, 9, 29, 17, 134, 202, 23, 438, 7, 40, 168, 529, 530, 95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
    probability = do_inference(stub, test_sequence)
    print(probability)
`
Here is one of my model:


`
I have another question, for example: my model size is 10M, i find it will take more than 40M to serve the model, i want to know the relationship between the model and the memory?

Thanks ~

**Comment by arghyaganguly** [comment]
@victory-hsu , I am receiving the below error when I am trying to do inference using the code demo in a .py file :- 

```
2021-03-31 20:03:07.918863: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "serving_query.py", line 28, in <module>
    probability = do_inference(stub, test_sequence)
  File "serving_query.py", line 19, in do_inference
    result = response.result().outputs["label_distribution"]
  File "/home/odin/anaconda3/envs/tfx_test/lib/python3.7/site-packages/grpc/_channel.py", line 722, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
status = StatusCode.DEADLINE_EXCEEDED
details = "Deadline Exceeded"
debug_error_string = "{"created":"@1617201190.520109655","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":81,"grpc_status":4}"
```
I tried the approach shown in [link](https://github.com/tensorflow/serving/issues/1265#issuecomment-758101099) without success.

**Comment by jurampark** [comment]
Memory usage could be impacted due to storing activations, number of threads and etc. To investigate further, I recommend to do profiling. BTW did you check container memory size before sending inference requests?

**Comment by arghyaganguly** [comment]
@victory-hsu, request your comment on the question asked above by @jurampark .Thanks.

**Comment by victory-hsu** [comment]
OK, thank you very much and I will do profiling in the future. The container memory is just the start memory, and i did not send any requests. I did not change any code either(just docker restart)

**Comment by victory-hsu** [comment]
OK, thank you very much and I will do profiling in the future. The container memory is just the start memory, and i did not send any requests. I did not change any code either(just docker restart)

**Comment by arghyaganguly** [comment]
@victory-hsu , closing this as the activity thread is stale for sometime.Please feel free to reopen.Thanks.
