### ISSUE TITLE
Golang TF Serving gRPC Client

### ISSUE THREAD

**Issue by H-Shafiei** [tensorflow/serving#1848]
Hi, I have just started learning go and I want to use it as a backend middleware between tfserving and my client code. I am trying to call tf-serving  from golang and I have already read some helpful gists like [this](https://github.com/tensorflow/serving/issues/485), [this](https://mauri870.github.io/blog/posts/tensorflow-serving-inception-go/) and [this](https://github.com/AlexanderJLiu/tensorflow-serving-api/tree/master/golang).

These solutions are a little bit old and do not work as then without any modification. I used [this](https://mauri870.github.io/blog/posts/tensorflow-serving-inception-go/) post from @mauri870 as a start.

## First Issue: Protoc Compile Error
First of all as of protoc-gen-go v1.26.0 (May 2021), for compiling proto files the protoc go plugin throws an error for not stating the go_package for *.proto files. As far as I searched, this was a warning before and from the new version it's an error not to specify go_package option in the proto files (or with an M from the protoc cli).
### How did I resolve it?
I resolved this by downgrading my compiler and plugins.
### What else?
But I think it should be handled better. How should it be fixed correctly?

OK it's duct-tape fixed! But then I have another problem

## Second Issue: `cannot find package "."` Error when compiling the code
So I finally got the proto files compiled but when I run `go build .` or `go run main.go` I get the following errors:

```
vendor/tensorflow_serving/apis/classification.pb.go:10:2: cannot find package "." in:
	/tmp/tfgo/vendor/github.com/golang/protobuf/proto
main.go:14:2: cannot find package "." in:
	/tmp/tfgo/vendor/github.com/golang/protobuf/ptypes/wrappers
vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto/meta_graph.pb.go:11:2: cannot find package "." in:
	/tmp/tfgo/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/graph_go_proto
vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto/meta_graph.pb.go:12:2: cannot find package "." in:
	/tmp/tfgo/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/op_def_go_proto
vendor/tensorflow_serving/apis/predict.pb.go:11:2: cannot find package "." in:
	/tmp/tfgo/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_go_proto
vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto/meta_graph.pb.go:13:2: cannot find package "." in:
	/tmp/tfgo/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto
vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto/meta_graph.pb.go:14:2: cannot find package "." in:
	/tmp/tfgo/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/framework/types_go_proto
main.go:16:2: cannot find package "." in:
	/tmp/tfgo/vendor/google.golang.org/grpc
vendor/tensorflow_serving/apis/model_service_grpc.pb.go:8:2: cannot find package "." in:
	/tmp/tfgo/vendor/google.golang.org/grpc/codes
vendor/tensorflow_serving/apis/model_service_grpc.pb.go:9:2: cannot find package "." in:
	/tmp/tfgo/vendor/google.golang.org/grpc/status
vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/example/example_protos_go_proto/example.pb.go:14:2: cannot find package "." in:
	/tmp/tfgo/vendor/google.golang.org/protobuf/reflect/protoreflect
vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/example/example_protos_go_proto/example.pb.go:15:2: cannot find package "." in:
	/tmp/tfgo/vendor/google.golang.org/protobuf/runtime/protoimpl
vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto/meta_graph.pb.go:17:2: cannot find package "." in:
	/tmp/tfgo/vendor/google.golang.org/protobuf/types/known/anypb
vendor/tensorflow_serving/apis/model.pb.go:13:2: cannot find package "." in:
	/tmp/tfgo/vendor/google.golang.org/protobuf/types/known/wrapperspb
main.go:11:2: cannot find package "." in:
	/tmp/tfgo/vendor/tensorflow/core/framework
vendor/tensorflow_serving/apis/prediction_log.pb.go:15:2: cannot find package "." in:
	/tmp/tfgo/vendor/tensorflow_serving/core
```
From what I see the problem is related to not specifying packages for the compiled *.proto files. How can I fix this?

# My Issues
So there are two questions:

- What's the correct way of compiling tf & tfserving proto files for go?
- Considering my way of compiling the proto files, how can I resolve the `cannot find package .` error shown above?

Thanks for helping:)

**Comment by arghyaganguly** [comment]
related :- [link](https://github.com/tensorflow/tensorflow/issues/48017)

**Comment by shadowdragon89** [comment]
I am not personally familiar with go, but this seems more like a general question about how go works with proto. Please ensure the related library is included: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/BUILD#L197

**Comment by arghyaganguly** [comment]
Closing this as it has been awaiting a response for some time.Please feel free to reopen with more information/insights following the above comment trace.
