### ISSUE TITLE
[New feature] Support services for vector similarity retrieval

### ISSUE THREAD

**Issue by jingkl** [tensorflow/serving#1850]
## Feature Request
If this is a feature request, please fill out the following form in full:

### Describe the problem the feature is intended to solve
Tesnorflow Serving is a model serving system for machine learning that trains and acquires models and integrates with Tensorflow models. After integrating the models, it is often possible to get vectors, which represent various features (can be features of text, images, audio, video), and [Milvus](https://www.milvus.io/docs/overview.md) can then provide vector storage and similarity retrieval services, so it is hoped that Milvus and Tensorflow serving can be deeply combined to provide more services to users

### Describe the solution
Hopefully, the following things can be done in tensorflow serving to help add vector retrieval service to tensorflow serving:

- Provide the introduction of Milvus
- Provide the Milvus tool folder
   Milvus implements vector import and vector query service, we will provide a file milvus_tool, the script under this folder 
   provides two functions to store and recall vectors using Milvus
- Pull request to the tensorflow service
- Merge into the tensorflow serving GitHub project
- Add tutorials or use cases

### Describe alternatives you've considered
Might be able to contribute Milvus source code

### Additional context
What is Milvus : https://www.milvus.io/docs/overview.md
Milvus Github:   https://github.com/milvus-io/milvus/

I hope we can communicate further and look forward to further cooperation with the tensorflow serving team.

**Comment by windmaple** [comment]
For vector similarity search, I think you can maintain your own repo (w/o being coupled to Serving), right? It's how Google's ScaNN has done it anyway.

**Comment by jingkl** [comment]
> For vector similarity search, I think you can maintain your own repo (w/o being coupled to Serving), right? It's how Google's ScaNN has done it anyway.

We would like to make it easier for users in the tf community to use the vector similarity retrieval tool Milvus, and for users in the Milvus community to use tensorflow servering.
We have already cooperated with [paddlepaddle](https://aistudio.baidu.com/aistudio/projectdetail/1816335?channelType=0&channel=0), and hope to cooperate with tensorflow community in depth.

**Comment by xiaofan-luan** [comment]
any progress on this proposal? If there is a way to have a connector that seems to be another solution?
