### ISSUE TITLE
Unexpected prediction differences on a served model

### ISSUE THREAD

**Issue by PierreDa** [tensorflow/serving#1856]
### System information
- **OS Platform and Distribution**: Debian GNU/Linux 10 (buster)
- **TensorFlow Serving installed from (source or binary)**: Source
- **TensorFlow Serving version**: 2.1.0

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow Serving.
I load a pre-trained CNN model with tensorflow_model_server, that I want to use for predictions. I communicate with it by sending gRPC Requests, and receiving corresponding predictions.
However, when I send requests filled with the same data to the server, I receive different predictions.

I expect a model served for predictions to be invariant, and not giving me different outputs for the same inputs.

### Exact Steps to Reproduce
Please include all steps necessary for someone to reproduce this issue on their
own machine. If not, skip this section.
This is the general workflow I used to get this issue: 
- Saving a model after training using `tf.saved_model.save`
- Loading this model on tensorflow_model_server
- Creating a PredictRequest object & sending it to the server via gRPC port, following the Step 5 of [this guide](https://towardsdatascience.com/serving-deep-learning-model-in-production-using-fast-and-efficient-grpc-6dfe94bf9234) 
- Comparing response of 2 identical requests send one after the other

### Source code / logs
- When I use the `saved_model_cli show --dir {path} --all` command, I get:

```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['model_densenet_2D_new']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input'] tensor_info:
        dtype: DT_UINT8
        shape: (-1, 512, 512, 1)
        name: model_densenet_2D_new_input:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['semantic_labels'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 512, 512, 2)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict

Defined Functions:
  Function Name: 'served_model'
    Option #1
      Callable with:
        Argument #1
          input: TensorSpec(shape=(None, 512, 512, 1), dtype=tf.uint8, name='input')
```

- The client-side code I used to reproduce the issue is:
```
import cv2
import grpc
import numpy as np
import tensorflow as tf
from tensorflow_serving.apis import predict_pb2, prediction_service_pb2_grpc

channel = grpc.insecure_channel("0.0.0.0:9000")
stub = prediction_service_pb2_grpc.PredictionServiceStub(channel)

feature = cv2.imread("path/to/my/image.png", 0)  # grayscale
feature = np.expand_dims(feature, axis=[0, -1])

request = predict_pb2.PredictRequest()
request.model_spec.name = 'model_densenet_2D_new'
request.model_spec.signature_name = 'model_densenet_2D_new'
request.model_spec.version.value = 38
feature_proto = tf.make_tensor_proto(feature, shape=feature.shape)
request.inputs["input"].CopyFrom(feature_proto)

answer = stub.Predict(request, 20)

a = request.inputs['input'].tensor_content  # Request data
b = np.array(answer.outputs['semantic_labels'].float_val)  # Response data
```

**Comment by lilao** [comment]
Hi PierreDa,

Thanks for reaching out. Tensorflow Serving uses Tensorflow to run the requests under the covers and Tensorflow does not guarantee deterministic results. Can you use saved_model_cli to run the same inputs to see if you get repeatable results?

**Comment by PierreDa** [comment]
Hello,
Thanks for your answer. 
When I run `saved_model_cli run` with the same input twice, I get the same results. However, when I send the same request two times to my served model, I get the following:

- The first response is identical to the results i got from `saved_model_cli run`.
- The second response is different. My model output gives probability values for 2 classes, and when I compare the 2 server responses, the probability of one class can sometimes jump from ~0.1 to ~0.8, for the same input values.

Is it possible that the served model parameters are modified after each prediction request ?

**Comment by PierreDa** [comment]
To add to my previous post:

- When i use `saved_model_cli run` two times with the same input, i get the same results.
- But when I use `saved_model_cli run` on a batch of the same input, I get different results for each input of the batch.

So these differences may not come from the TensorFlow server. Can you confirm that?

Thank you for your help.

**Comment by lilao** [comment]
If you use saved_model_cli run and get different results, it seems that the root cause is in Tensorflow, because saved_model_cli doesn't involve Tensorflow Serving.
