### ISSUE TITLE
Question on XLA AOT optimizations

### ISSUE THREAD

**Issue by wilderfield** [tensorflow/serving#1858]
Does TensorFlow Serving support XLA's AOT (ahead of time compilation)?

https://www.tensorflow.org/xla/tfcompile

**Comment by arghyaganguly** [comment]
@wilderfield , please check this related stackoverflow answer in [link.](https://stackoverflow.com/questions/54671395/tensorflow-serving-with-xla)

**Comment by wilderfield** [comment]
@arghyaganguly thanks for looking at my question. The post doesn’t answer the question though. tf-compile allows for an inference model to be compiled and optimized based on its explicit layer parameters. It is a good idea to compile a model before you serve it. Does TF Serving support models that have gone through this tf-compile flow?

**Comment by guanxinq** [comment]
TF Serving currently only supports loading SavedModel servables. It doesn't support XLA AOT (tfcompile). TFCompile instead generates C++ object files that you're supposed to directly link against in your binary. 

However, TF Serving does experimentally support XLA JIT after https://github.com/tensorflow/serving/commit/3c1b2b34ec516afbb73543cc62d3979f013a33f1 by enabling the flag "xla_cpu_compilation_enabled".

**Comment by arghyaganguly** [comment]
@wilderfield , please confirm on the above comment by @guanxinq. Thanks.

**Comment by arghyaganguly** [comment]
Closing this as there has been no update from sometime.Please feel free to reopen with insights/information based on the discussion above.Thanks.
