### ISSUE TITLE
Use 0.0.0.0 for serving HTTP/Rest

### ISSUE THREAD

**Issue by Algirdyz** [tensorflow/serving#1864]
### Describe the problem the feature is intended to solve
Currently HTTP/Rest API is being served on localhost:8051. Using localhost instead of 0.0.0.0 is causing issues with kubernetes environments.

### Describe the solution
Either provide a configuration to change the host or change the host to 0.0.0.0. I believe it should not cause any issues if it is changed.

### Additional context
It is a common issue when trying to expose pods through services on kubernetes
https://stackoverflow.com/questions/53494039/how-can-tensorflow-model-server-bind-its-http-rest-on-0-0-0-0-default-localhost
https://stackoverflow.com/questions/51662015/service-not-exposing-in-kubernetes

I have also encountered it with my own code when I forget the host and changing it to 0.0.0.0 always fixes the problem. 
gRPC serving is already using 0.0.0.0

**Comment by yimingz-a** [comment]
Hi @Algirdyz,

Sorry this issue slipped through the crack. Apologize for the late reply!
Are you still seeing this issue? If so, let me know I'll bring this issue to our team and discuss the best way to support this.
In the meanwhile, if you would like to contribute to the project you're also more than welcomed to send out a PR for this, and we will review it asap.

Thanks!

**Comment by Algirdyz** [comment]
We ended up working around it, not sure if the issue persists. We are using a separate in cluster service to route through.
But thanks!

**Comment by UsharaniPagadala** [comment]
@Algirdyz 

Closing this issue based on the response and feel free to reopen if this issue still persists.Thanks

**Comment by taomanwai** [comment]
We are facing the same issue, @Algirdyz , what is the workaround of this issue? Thanks
