### ISSUE TITLE
tf-serving r1.14 gRPC example(resnet_client_cc) Failed with gRPC assertion

### ISSUE THREAD

**Issue by threeleafzerg** [tensorflow/serving#1870]
Software Environment:
OS: centos6.3
gcc: 8.2
tf-serving: official r1.14 

Reproduce steps:
build tensorflow model server
build resnet_client_cc (official example of gRPC)

run tf server:
./tensorflow_model_server --port=8500 --rest_api_port=8502  --model_config_file="${PWD}/resnet50.config"
run client:
sudo ./resnet_client_cc --server_port="localhost:8500" --image_file="/tmp/n03018349_china_cabinet.JPEG" --model_name="resnet50" --model_signature_name="serving_default"

Failure:
E0623 18:46:03.803914427   47180 channel_stack.cc:135]       assertion failed: (uintptr_t)(user_data - (char*)stack) == grpc_channel_stack_size(filters, filter_count)

**Comment by threeleafzerg** [comment]
I print out the assert failure details and found:
user_data=0x7f62e67ff438
stack=0x7f62e67ff078
user_data - stack=960
grpc_channel_stack_size=1166016752

grpc_channel_stack_size got from function grpc_channel_stack_size is wrong...

**Comment by jurampark** [comment]
I think it's an issue on grpc side? Please update again if you got an different answer from the issue[1] on grpc you created.

[1]: https://github.com/grpc/grpc/issues/26526

**Comment by threeleafzerg** [comment]
It's solved after I update the tf-serving from r1.14 -> r2.4.0. 
Since it's an issue exposed in old version. I suggest that we can close this issue.

**Comment by jurampark** [comment]
Thanks for the update!
