### ISSUE TITLE
How to transfer data in Bert model？？

### ISSUE THREAD

**Issue by 1148330040** [tensorflow/serving#1882]
env:
tf2.2/linux
docker:
tensorflow/serving   2.2.2-gpu 

After the model is successfully deployed, I need to pass ids, mask and token_types_ids to the model because it is a Bert model, how do I design the incoming data format?
If I use this format:
    request.inputs['ids'] = ids
    request.inputs["mask"] = masks
    request.inputs["target"] = target
    request.inputs["tokens"] = token_types_ids
Then he will report a mistake:
Traceback (most recent call last):
  File "/mnt/tang_cvs/Control/start.py", line 130, in <module>
    print(request_server(batch_data=batch_data, server_url='http://localhost:8501/v1/models/half_plus_two:predict'))
  File "/mnt/tang_cvs/Control/start.py", line 100, in request_server
    request.inputs['ids'] = ids
ValueError: Direct assignment of submessage not allowed

If I use this format:
    request.inputs['inputs'] = (ids, masks, token_types_ids, target)
Then he will report a mistake:
ValueError: Direct assignment of submessage not allowed

If I use this format:
    request.inputs = (ids, masks, token_types_ids, target)
Then he will report a mistake:
AttributeError: Assignment not allowed to repeated field "inputs" in protocol message object.

**Comment by arghyaganguly** [comment]
@1148330040 , please try the approach as shown in the grpc API snippet in [link](https://huggingface.co/blog/tf-serving):- 

```
request.inputs["attention_mask"].CopyFrom(tf.make_tensor_proto(batch["attention_mask"]))
```

**Comment by 1148330040** [comment]
> @1148330040 , please try the approach as shown in the grpc API snippet in [link](https://huggingface.co/blog/tf-serving):-
> 
> ```
> request.inputs["attention_mask"].CopyFrom(tf.make_tensor_proto(batch["attention_mask"]))
> ```
Thank you very much. As a self-taught scholar, I am very grateful for your timely reply. I hope you work smoothly and live happily!

**Comment by arghyaganguly** [comment]
@1148330040 , thank you for your reply.Please confirm whether the above approach worked for you or do we need to explore alternative paths.Thanks.

**Comment by 1148330040** [comment]
> @1148330040 , thank you for your reply.
> 
> Please confirm whether the above approach worked for you or do we need to explore alternative paths.

It solved my problem, thank you again！
