### ISSUE TITLE
Bazel building inside the 'nvidia-docker' occurs cudnn library problem.

### ISSUE THREAD

**Issue by Cheolhui** [tensorflow/serving#189]
My system configuration
Ubuntu 16.04
## nVidia GTX1080 (compatibility - 6.1)

I'm trying to use TensorFlow Serving via nvida-docker, for several clients to use this 

host PC. To make it succeed I'm folloing instructions of 

'https://gist.github.com/revilokeb/3940c2bbdcf9f25dc4eb809d5b51a220'.

At the step of building inception-v3 model with CUDA configuration, ( I succeed in configuration of it)

I got the following error messages described in the log.
## log

bazel-bin/tensorflow_serving/example/inception_client --server=localhost:9000 --image=
I external/tf/tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I external/tf/tensorflow/stream_executor/dso_loader.cc:99] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:
I external/tf/tensorflow/stream_executor/cuda/cuda_dnn.cc:1562] Unable to load cuDNN DSO
I external/tf/tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I external/tf/tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I external/tf/tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf_serving/tensorflow_serving/example/inception_client.py", line 56, in <module>
    tf.app.run()
  File "/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf_serving/tensorflow_serving/example/inception_client.py", line 46, in main
##     with open(FLAGS.image, 'rb') as f:

It says libcudnn.so can't be found on the specified directory " LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr

/local/nvidia/lib64". However, I checked that those library files exist in the /usr/local/cuda/lib64 in the 

nvidia-docker container. 

Also, in the host machine, /usr/local/nvidia/ directory doesn't even exist. 

I can't catch how the heck the bazel keeps trying finding the cudnn in that directory......

It would be really helpful if anyone could give me useful information or solutions regarding this problem!!

**Comment by gautamvasudevan** [comment]
Should be resolved by looking at the new [docker](https://github.com/tensorflow/serving/tree/master/tensorflow_serving/tools/docker) images.
