### ISSUE TITLE
TF serving GPU build fails to execute on CPU only machines without CUDA and TensorRT dependencies.

### ISSUE THREAD

**Issue by supercharleszhu** [tensorflow/serving#1899]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow Serving installed from (source or binary)**:
- **TensorFlow Serving version**:

### Describe the problem
Our team is trying to run tf serving within both CPU-only and GPU machines. However when we build TF serving with GPU version in CentOS7, the executables can only be run within a CUDA, TensorRT, and GPU ready environment. If we run the GPU serving in another CentOS7 environment, it will give some errors like: 
```
tensorflow_model_server: error while loading shared libraries: libcusolver.so.10: cannot open shared object file: No such file or directory
```

### Exact Steps to Reproduce
I was building in CentOS7 using the following command: 
``` bash
ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1 && \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:${LD_LIBRARY_PATH} \
    BAZEL_LINKLIBS=-l%:libstdc++.a /usr/local/bin/bazel build --color=yes --config=release --config=cuda --curses=yes -c opt --copt=-march=ivybridge --copt="-fPIC" --verbose_failures tensorflow_serving/model_servers:tensorflow_model_server
```
 The build was successful. And it can run successfully with machines with Cuda and TensorRT dependencies ready.

When running on machines without Cuda and TensorRT installed, it will give above error and terminate the execution.

### Source code / logs
Not available since the process exit with value 127

**Comment by UsharaniPagadala** [comment]
@supercharleszhu 

For CPU only environment to build from source please follow  this  [link](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel#L94).Thanks

**Comment by supercharleszhu** [comment]
@UsharaniPagadala Do we have a way to build an executable that can be running in both GPU and CPU-only environment? Our current approach is using two different executables and selects the one according to the environment.

**Comment by supercharleszhu** [comment]
Similar to Tensorflow is there something like dso_loader to load the dynamic library, and switch to CPU runtime if the shared object (library) is not existing in the environment?

**Comment by singhniraj08** [comment]
@supercharleszhu,

Similar Feature request is already in progress #1425 . Requesting you to close this issue and follow similar thread for updates. Thank you!
