### ISSUE TITLE
tensorflow serving batch predict  useless

### ISSUE THREAD

**Issue by xxllp** [tensorflow/serving#1904]
I have use bert clf model predict  in tf serving cpu 

but  find when increase the batch size of data ,then the data of requests delay  multipy  increase 

and I have also try the  [ batching  predict](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/batching/README.md)   have the same result  ,so what is the reason  ?

tf serving version :2.0.0  +cpu

**Comment by UsharaniPagadala** [comment]
@xxllp 

For better performance with CPU we suggest you to reduce the batch size or increase the available RAM.Thanks

**Comment by xxllp** [comment]
@UsharaniPagadala  thx for you  answer , I  have test batch size with small value =2 and  get the best result 。
 Multi threading predict can also less the time

**Comment by UsharaniPagadala** [comment]
@xxllp 
Could you please let us know, If this issue still persist.Thanks

**Comment by gaikwadrahul8** [comment]
Hi, @xxllp 

Apologies for the delay and sometimes only altering the batch size won't help to reduce latency with prediction inferences so you'll have to do hyper parameter tuning with other parameters like 1. `max_batch_size` 2. `batch_timeout_micros`3. `num_batch_threads` 4. `max_enqueued_batches` you can refer official documentation [here](https://github.com/tensorflow/serving/blob/r2.0/tensorflow_serving/batching/README.md) and I would also suggest playing around with the `TENSORFLOW_INTER_OP_PARALLELISM`, `TENSORFLOW_INTRA_OP_PARALLELISM`, `OMP_NUM_THREADS` arguments for TF Serving and [here](https://stackoverflow.com/questions/41233635/meaning-of-inter-op-parallelism-threads-and-intra-op-parallelism-threads) is explanation what those parameters do 

You can also refer our TF-Serving [Performance Guide](https://www.tensorflow.org/tfx/serving/performance) and one [youtube video](https://www.youtube.com/watch?v=fnZTVQ1SnDg) about TensorFlow Serving performance optimization

Could you please try above workaround and let us know is it resolving your issue or not, if issue still persists please let us know and if possible please help us with minimal code snippet with trained model to reproduce the issue from our end ?

Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @xxllp 

Closing this issue due to lack of recent activity for couple of weeks. Please feel free to reopen the issue or post comments, if you need any further assistance or update. Thank you!
