### ISSUE TITLE
Website Link Changed

### ISSUE THREAD

**Issue by dummy26** [tensorflow/serving#1907]
The about tab of github shows this link - www.tensorflow.org/serving
The new link is - https://www.tensorflow.org/tfx/guide/serving

**Comment by UsharaniPagadala** [comment]
@dummy26 

Could you please share the document where did you get this [link](https://www.tensorflow.org/serving).Thanks

**Comment by dummy26** [comment]
Not sure if this is what u r asking about -  
![Screenshot (382)](https://user-images.githubusercontent.com/40134444/130219601-b3967924-4f05-4d92-857b-d8f900866a38.png)

**Comment by singhniraj08** [comment]
@dummy26,

The old link http://www.tensorflow.org/serving shown in `tensorflow/serving` repo will redirect users to new link https://www.tensorflow.org/tfx/guide/serving

Thank you for bringing this up. Kindly let us know if this issue can be closed. Thank you!
