### ISSUE TITLE
prometheus metrics filtering

### ISSUE THREAD

**Issue by vjetname** [tensorflow/serving#1928]
### Describe the problem the feature is intended to solve
Our team is struggling with cumulation of metrics volume forcing us to preform regular restarts of tf-serving container.

### Describe the solution
To avoid that issue we propose more complex confuguration options, such as:
 * generate metrics only for enabled models (latest versions),
 * filter by type (name) of metric,
 * metrics rotation (similarly as common logs rotation feature),
 * time-based limit of produced metrics (eg. last 24hrs)

### Describe alternatives you've considered
We tried to implement our own filtering component using "proxy" REST API, but it was not sufficient as the original metrics are still growing in volume.

### Additional context
Relates to [Monitoring Configuration](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/serving_config.md#monitoring-configuration)

**Comment by singhniraj08** [comment]
@vjetname,

Prometheus will record both serving and core tensorflow metrics, which are defined separately. There is no option on filtering the metrics for particular models. Alternatively, you can use [tfio.experimental.IODataset.from_prometheus()](https://www.tensorflow.org/io/api_docs/python/tfio/experimental/IODataset#from_prometheus) to scrap the metrics for given length of the query (in seconds). 

Let us know if this helps your use-case. Thank you!
