### ISSUE TITLE
Confidence scores are different from hdf5 prediction & TF Serving Prediction

### ISSUE THREAD

**Issue by kalyangande96** [tensorflow/serving#1939]
### System information
- **OS Platform and Distribution **: RHEL 7.9
- **TensorFlow Serving installed from **: Docker Image
- **TensorFlow Serving version**: 2.4.1

### Describe the problem
CRNN model when used with hdf5 and with saved model format(.pb), confidence scores are not same. Model is trained with tensorflow: 2.4 and serving with 2.4. Is that the expected behaviour of tf-serving? Is there any other way to match both?

**Comment by pindinagesh** [comment]
@kalyangande96 

In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by pindinagesh** [comment]
@kalyangande96 

Closing this issue as it has been inactive for more than 2 weeks. Please refer the [Doc](https://www.tensorflow.org/guide/saved_model) and add additional comments for us to open this issue again. Thanks!
