### ISSUE TITLE
Convert TFlite to pb and deploy serving with TFserving

### ISSUE THREAD

**Issue by Luna0214** [tensorflow/serving#1943]
### Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've
considered.

I have different ML model's pbtxt file to test with TFserving for the alternative.

## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- **OS Platform and Distribution (MacOS Terminal):
- **TensorFlow Serving installed from (source)**:
- **TensorFlow Serving version_lastest:

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in
TensorFlow Serving.

As I know the tflite format doesn't not support on the TFserving. So, I was trying convert it to pb format.
But I could not. I was googling for more than 12 hrs. before I write this request post.
In this case, I can't find any way to use TFserving. 
For me, this is my baby-step study ML on TFserving. So I was trying to test a ML model on it and it is unfortunately tflite file fotmat.
please help me to get through this issue.

**Comment by pindinagesh** [comment]
@Luna0214 

Have you tried these approaches [#53664279](https://stackoverflow.com/questions/53664279/converting-tflite-to-pb) and [#19123](https://github.com/tensorflow/tensorflow/issues/19123)?

**Comment by pindinagesh** [comment]
@Luna0214 

Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again. Thanks!
