### ISSUE TITLE
Docker Hub has older tf version (2.5.1) for the latest tag

### ISSUE THREAD

**Issue by ronalddas** [tensorflow/serving#1961]
## Bug Report
Docker Hub has older tf version (2.5.1) for the latest tag, and is not matching with the one in github (currently 2.6.2 https://github.com/tensorflow/serving/releases/tag/2.6.2)

### Describe the problem
The latest tag in Docker Hub is tf version 2.5.1 https://hub.docker.com/layers/tensorflow/serving/latest/images/sha256-6651f4839e1124dbde75ee531825112af0a6b8ef082c88ab14ca53eb69a2e4bb?context=explore , it should be in sync with github releases

### Exact Steps to Reproduce
Check the 11th Layer in Image Layers

![Screenshot from 2022-01-15 23-09-49](https://user-images.githubusercontent.com/12792689/149631955-d674cb49-41f0-4b4c-ae60-b1c0a221f080.png)

**Comment by shan3290** [comment]
Hi, this is due to a historical reason 10 month ago, and this "latest" tag does not mean the latest docker.

Please use 2.8.0 or 2.8.0-gpu in https://hub.docker.com/r/tensorflow/serving/tags. Their tags match the tf serving version inside. Thanks!

**Comment by rtg0795** [comment]
This issue has been resolved. Now [latest docker images](https://hub.docker.com/r/tensorflow/serving/tags?page=1&name=latest) are pointing to correct TF-Serving version.
