### ISSUE TITLE
Log the payload and the output 

### ISSUE THREAD

**Issue by seftimie** [tensorflow/serving#1962]
Hello folks,

I've exported a BigQuery ML to GCP Storage and then using Tensorflow Serving and Cloud Run I've deployed the solution and everything works just fine. Don't know If it is possible / how to solve this...  but I would like to log the input (the payload from request) and the output (from the model) in cloud run/cloud logging. I've been looking, but frankly I have no clue. Any suggestions?

Thank you.

**Comment by sanatmpa1** [comment]
@seftimie,

Have you got a chance to look at [this documentation](https://cloud.google.com/run/docs/logging) about logging with `Cloud Run`? Thanks!

**Comment by sanatmpa1** [comment]
@seftimie,

Closing this issue due to lack of recent activity, Please feel free to reopen the issue with more details if the problem still persists. Thanks!
