### ISSUE TITLE
The repository '@local_cuda' could not be resolved and referenced by '@cub_archive//:cub'

### ISSUE THREAD

**Issue by 520jefferson** [tensorflow/serving#1967]
The error logs as follows when i compile the tf serving.

![image](https://user-images.githubusercontent.com/5691554/150779610-9c7dde3b-00cb-4ad0-b760-1ed860bb7b17.png)

**Comment by sanatmpa1** [comment]
@520jefferson,

Can you take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/4105#issuecomment-243639532) from a [similar issue](https://github.com/tensorflow/tensorflow/issues/9435) to see if it helps? Thanks!

**Comment by 520jefferson** [comment]
@sanatmpa1 it's not the same error, the log's about cannot find the @local_cuda.

**Comment by 520jefferson** [comment]
I download the master to compile,when i download the[ v1.15 version]，the problem gone.

**Comment by Jonghwanshin** [comment]
I could reproduce this error with TF v2.5.1 with CUDA 10.2. 
I downloaded the source code from release page but this issue happens on my machine.
I fixed `deps` in `third_party/cub.BUILD` file to the below code block to find cuda_headers correctly.
Now it can build successfully in my machine.
Please refer to the below code block if anyone is experiencing the same issue.

```
# file: third_party/cub.BUILD
# Description: CUB library which is a set of primitives for GPU programming.

package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # BSD

exports_files(["LICENSE.TXT"])

cc_library(
    name = "cub",
    hdrs = glob(["cub/**"]),
    deps = ["@local_config_cuda//cuda:cuda_headers"],
)
```
