### ISSUE TITLE
serving multiple version of the same model

### ISSUE THREAD

**Issue by waichee** [tensorflow/serving#197]
We are looking at serving multiple versions of the same model (i.e. `000001/` and `000002/`). The default behavior of `AspireVersionManager` is to eagerly load the newest version and unload all version before the latest version. What would be the recommended way of serving 2 versions of the same models in TS serving say for e.g. for AB testing purpose? The options that I could see are
- modify the eager unload policy to handle this.
- change to the Caching manager rather than AspireVersion Manager?
- change `FileSystemStoragePathSource` to aspire latest version and version before it?

Also if we do change the graph structure of the model (and not just updating the weights) in the new version, would Tensorflow serving be able to handle this or do we need to declare the new version as a different model (with different name in the model spec)?

**Comment by chrisolston** [comment]
The right way to do it is to define a new Source that aspires multiple versions at the same time.

And no, TF-Serving doesn't care if the model structure varies across versions.

**Comment by waichee** [comment]
cool thanks good to know @chrisolston

**Comment by sukritiramesh** [comment]
Hi @waichee, it looks like this issue is now resolved. Closing for now; but please feel free to reopen if you have further questions.
