### ISSUE TITLE
Curl header files dependency missing or cloud building by mistake?

### ISSUE THREAD

**Issue by Mazecreator** [tensorflow/serving#198]
I recently had to run a new compilation of the tensorflow-serving.  It is significantly different than about 2 months ago.  I needed to remove my serving repository and start fresh from this build:
https://github.com/tensorflow/serving/commit/e9d01c00aba8f843a20afb9117c1347a9f4b3b2f

I request during configuration to not include "Cloud", but during compilation I got a curl.h file not found and it failed.  This seemed to be related to some cloud features.  So the configure script may not disable the cloud function or there is a missing dependency for the curl development header files.

I am running Ubuntu 16.04 and requested no GPU support on this build.  I had to install the header files:
sudo apt-get install libcurl4-openssl-dev

The code compiled once I installed libcurl4 libraries.

**Comment by derek121** [comment]
Same problem. @Mazecreator: did you find a solution?

**Comment by derek121** [comment]
Based on http://askubuntu.com/questions/78183/installing-curl-h-library I just did the _apt-get install libcurl4-openssl-dev_ to get on with it, and that allowed things to work.

**Comment by kirilg** [comment]
Thanks @derek121. That's right, it simply means there's a missing curl package. You'll need to run `sudo apt-get install curl` and possibly also `sudo apt-get install libcurl3-dev`
