### ISSUE TITLE
How to return image in tensorflow serving?

### ISSUE THREAD

**Issue by rohanmuplara** [tensorflow/serving#1993]
What is the best way to return an image in tensorflow serving? I imagine it is something such as tf.encode_png 
or tf.encode_jpeg but those are causing me problems 
I am trying to write a tensor to a png. As seen in colab link at bottom, when I take the encoded bytes and write it a file using python, it doesn't work. Trying opening the image it gets corrupted
When I use tf.io.write_file it works. I also tried taking a png and using tf.io_decode_png and than tf.io.encoding_png and the image string bytes differ from the original png. I am using tensorflow serving and using this png result through the rest api, where I don't have access to tf.io.wrte_file so I was wondering what encode_png does differently, than traditional png encodings.

https://www.loom.com/share/4b32b330a0e742cab2ea3a1a9af11b22
https://colab.research.google.com/drive/13Y4ET8jAHZDq7qwUYgg8nuBkxqniUqGu#scrollTo=IcXVZepnhkW4

**Comment by gaikwadrahul8** [comment]
@rohanmuplara 

Apologies for the delay and If you're looking to specific to return image from Tensorflow Serving then please have a look into these articles : [[1](https://stfs.readthedocs.io/en/latest/image_model.html)],[[2](https://towardsdatascience.com/getting-started-with-tensorflow-serving-b03c130bdb5c)],[[3](https://neptune.ai/blog/how-to-serve-machine-learning-models-with-tensorflow-serving-and-docker)] and for image processing operations with Tensorflow you can refer official documentation [here](https://www.tensorflow.org/api_docs/python/tf/image) and let us know if it helps you to resolve your issue ?

If you need any further assistance, please let us know ?

Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @rohanmuplara 

Closing this issue due to lack of recent activity for couple of weeks. Please feel free to reopen the issue or post comments, if you need any further assistance or update. Thank you!
