### ISSUE TITLE
Dockerfile + tensorflow serving + osx (no nvidia card)

### ISSUE THREAD

**Issue by johndpope** [tensorflow/serving#200]
I have this docker file
https://gist.github.com/johndpope/d41a7d6daf8652cbdaff41a2b063c801

it downloads a script
https://gist.githubusercontent.com/johndpope/fc1c2327a4ae255d9c44dda9b67b5288/raw/00db760e28631cfc94a9c366da5d5a934368b375/parseyapi.sh

which ultimately fails with 
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file not found. Unable to load package for '//third_party/gpus:cuda_configure.bzl': BUILD file not found on package path.

I've tried running this on mac and get same problem. Did I miss something? 
Unfortunately - my macbook pro has an intel iris card - I set the export TF_NEED_CUDA=0 but can't force it to switch off. Is there another config parameter besides --config=cuda 

fyi - Docker (with osx) doesn't have nvidia access.
https://github.com/NVIDIA/nvidia-docker/issues/101

**Comment by johndpope** [comment]
fyi - I re-ran the build process using do the dockerfile sample file https://gist.github.com/johndpope/d916029bdea7d7e4b93bd5bbc3541f9c
but  get the same error.

**Comment by johndpope** [comment]
related bug 
https://github.com/tensorflow/tensorflow/issues/4216

**Comment by johndpope** [comment]
@kirilg  looks like this commit fixed it. this should be merged.
https://github.com/tensorflow/serving/tree/89e9dfbea055027bc31878ee8da66b54a701a746/

**Comment by kirilg** [comment]
Following https://github.com/dsindex/syntaxnet/issues/10 it looks like you're syncing to an old commit that predates cuda_configure.bzl in TensorFlow and that works for you. That commit is already merged into TensorFlow Serving master, it's just that since then other changes were introduced that caused the issue you observed.
