### ISSUE TITLE
remote Docker or invalid path hangs while following quickstart

### ISSUE THREAD

**Issue by alfredodeza** [tensorflow/serving#2004]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX (M1) using Docker for Desktop client, and OSX (Intel) on the remote side
- **TensorFlow Serving installed from (source or binary)**: Using docker image
- **TensorFlow Serving version**: Can't tell, used the _latest_ tag for the container

### Describe the problem
While following the quickstart guide, I had an invalid path for the volume which caused the container to hang and not allow me to  cancel the process.

This problem will happen anytime that an incorrect path is used. 

I forgot that I'm using a remote Docker instance. This means that the _local_ path must exist in the remote server when binding volumes. In my case, this path wasn't on the remote server and caused the _serve_ to hang (couldn't Ctrl-C out of it):

```
$ docker run -t --rm -p 8501:8501 -v "$TESTDATA/saved_model_half_plus_two_cpu:/models/half_plus_two" -e MODEL_NAME=half_plu
s_two tensorflow/serving
2022-05-18 14:29:55.887915: I tensorflow_serving/model_servers/server.cc:89] Building single TensorFlow model file config:  model_name: half_plus_two model_base_path: /models/half_plus_two
2022-05-18 14:29:55.888309: I tensorflow_serving/model_servers/server_core.cc:465] Adding/updating models.
2022-05-18 14:29:55.888383: I tensorflow_serving/model_servers/server_core.cc:591]  (Re-)adding model: half_plus_two
2022-05-18 14:29:55.891480: W tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:268] No versions of servable half_plus_two found under base path /models/half_plus_two. Did you forget to name your leaf directory as a number (eg. '/1/')?
2022-05-18 14:29:56.901813: W tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:268] No versions of servable half_plus_two found under base path /models/half_plus_two. Did you forget to name your leaf directory as a number (eg. '/1/')?
2022-05-18 14:29:57.904190: W tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:268] No versions of servable half_plus_two found under base path /models/half_plus_two. Did you forget to name your leaf directory as a number (eg. '/1/')?
2022-05-18 14:29:58.908832: W tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:268] No versions of servable half_plus_two found under base path /models/half_plus_two. Did you forget to name your leaf directory as a number (eg. '/1/')?
```

Since it is impossible to cancel the operation, I had to find the PID and issue a `kill -9` to terminate the process.

### Exact Steps to Reproduce
Although I got into this issue with a remote Docker instance, it is reproducible by passing an invalid path to the volume to get into this problem. For example, missing the absolute path to it:

```
$ docker run -t --rm -p 8501:8501 -v "saved_model_half_plus_two_cpu:/models/half_plus_two" -e MODEL_NAME=half_plus_two tensorflow/serving
```

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached. Try to provide a reproducible test case that is the bare
minimum necessary to generate the problem.

**Comment by pindinagesh** [comment]
Can you please try the docker command in the following format and try adding a **/** before $ in Git bash.

docker run -t --rm -p 8501:8501 \
    -v /$TESTDATA/my_model:/models/my_model \
     -e MODEL_NAME=my_model \
     tensorflow/serving &

**Comment by alfredodeza** [comment]
Thanks for the reply @pindinagesh . By using the ampersand the command goes into the background, but the problem persists. The issue here is that the service doesn't tolerate an invalid path and it is impossible to exit out of it.

**Comment by singhniraj08** [comment]
@alfredodeza, @yalcinaa,

Setting [servable_versions_always_present](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/server_core.h#L169-L174) param to `True` will allow TF Serving to fail if wrong model or model path is provided to the model. Once model server fails, you can start the model server again by providing the correct model.

Let us know if this helps. Thank you!

**Comment by yalcinaa** [comment]
@singhniraj08 No such parameter exists in `tensorflow_model_server` command. I can't change it.

**Comment by singhniraj08** [comment]
@yalcinaa, we have to add the `servable_versions_always_present: true` param in [model_config_list](https://www.tensorflow.org/tfx/serving/serving_config#model_server_config_details) and pass it to model server. Thanks

**Comment by alfredodeza** [comment]
@singhniraj08 the problem with that approach is that it assumes that the developer will understand what that parameter does and that it is relevant to an incorrect path. 
This issue should address the fact that it is possible to pass an incorrect path, and provide an error that explains what the path is where things were looked at and how or why the expected model couldn't be loaded - in this case, because it couldn't be found.

Asking to pass a parameter doesn't seem like the right approach here.

**Comment by singhniraj08** [comment]
@alfredodeza, This sounds like a feature we need to work on to implement. Let me bring this up to the team internally. 
In meanwhile, Please feel free to create a PR if you are interested in the feature implementation. Thank you!

**Comment by Sergiodiaz53-Dedalus** [comment]
> @alfredodeza, @yalcinaa,
> 
> Setting [servable_versions_always_present](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/server_core.h#L169-L174) param to `True` will allow TF Serving to fail if wrong model or model path is provided to the model. Once model server fails, you can start the model server again by providing the correct model.
> 
> Let us know if this helps. Thank you!

Hi there,

Stuck with the same problem. _servable_versions_always_present_ seems to be not present neither as a flag while calling the tensorflow_model_server neither as an option in the model_config_list, but I can still see it in the server_core.h. Could you provide an example on how to use it? Currently running 2.14.1. 

Thanks in advance.
