### ISSUE TITLE
Unable to build Dockerfile.devel-gpu

### ISSUE THREAD

**Issue by marqueurs404** [tensorflow/serving#2006]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow Serving installed from (source or binary)**: source
- **TensorFlow Serving version**: 2.8.0

### Describe the problem
I have a specific need that required me to customize some code and build Tensorflow Serving from source. I was able to build the CPU image successfully but the GPU image failed to build as the **libnvinfer7-\* packages are no longer available in the `https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/` repository.** 

Are there any recommended solutions or workarounds around this? 

### Exact Steps to Reproduce
`docker build --pull -t $USER/tensorflow-serving-devel-gpu -f Dockerfile.devel-gpu .`

### Source code / logs
```
E: Unable to locate package libnvinfer7
E: Version '7.2.2-1+cuda11.1' for 'libnvinfer-dev' was not found
E: Version '7.2.2-1+cuda11.1' for 'libnvinfer-plugin-dev' was not found
E: Unable to locate package libnvinfer-plugin7
E: Unable to locate package libnvonnxparsers7
E: Unable to locate package libnvparsers7
E: Version '7.2.2-1+cuda11.1' for 'libnvonnxparsers-dev' was not found
E: Version '7.2.2-1+cuda11.1' for 'libnvparsers-dev' was not found
```

**Comment by pindinagesh** [comment]
Can you take a look at the workaround proposed in this [link](https://github.com/tensorflow/serving/issues/691) and see if it helps in resolving your issue? Also you can refer to this [issue](https://github.com/tensorflow/serving/issues/1781) which discusses about similar problem. Thanks!

**Comment by marqueurs404** [comment]
Thanks but the issue is different from the ones you have linked.

Anyway, it seems that the missing packages had been added back to the nvidia repository so the build is working again. Seems like it was an issue on nvidia's side.

Closing this issue.
