### ISSUE TITLE
Outdated inception_k8s.json

### ISSUE THREAD

**Issue by robertlacok** [tensorflow/serving#201]
The [replication controller](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_k8s.json) for deploying the example inception model on container engine is not in line with the newest changes (from 3 weeks ago).  

Line 28 should look more like this: 
`"/serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=inception --model_base_path=inception-export"`

**Comment by vinuraja** [comment]
Thanks for the heads up. Please feel free to send in a patch.

**Comment by chrisolston** [comment]
Fixed via https://github.com/tensorflow/serving/pull/213.
