### ISSUE TITLE
tfserving hot reload neew double memory cause OOM

### ISSUE THREAD

**Issue by chenwenjun-github** [tensorflow/serving#2017]
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- CentOS
- **TensorFlow Serving installed from (source or binary)**:
- use docker image from this registory
- **TensorFlow Serving version**:
- 1.15.0

### Describe the problem
tfserving support hotreload, but the problem is that it need double memory,  this will cause OOM when I use tfserving docker images in k8s and configure memory limit for tfserving container

### Exact Steps to Reproduce
use tfserving docker images as deployment in k8s and configgure memory limit, use hotreload mode and use a large model which is half of memory limit at least.

### Source code / logs
see problem describe

**Comment by pindinagesh** [comment]
Hi @chenwenjun-github 

Could you please provide a snippet of your code and full error stack trace to help us debug this issue. Thank you!

**Comment by pindinagesh** [comment]
Hi @chenwenjun-github 

Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again. Thank you!
