### ISSUE TITLE
Unable to install TensorFlow Serving dependencies

### ISSUE THREAD

**Issue by vasantivmahajan** [tensorflow/serving#202]
On running the command
 sudo apt-get update && sudo apt-get install -y \
        build-essential \
        curl \
        git \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python-dev \
        python-numpy \
        python-pip \
        software-properties-common \
        swig \
        zip \
        zlib1g-dev

The following error is displayed:

![image](https://cloud.githubusercontent.com/assets/17990840/19285524/37e63ed6-8fc8-11e6-9bda-dcb9d222b95f.png)

Any help is appreciated.

**Comment by kirilg** [comment]
Are you running on Windows (I see mingw64 references)? TensorFlow Serving doesn't compile in Windows right now. `sudo` and the mentioned libraries should be defined in a Linux environment though.

**Comment by vasantivmahajan** [comment]
Yes, I am running on a Windows machine. How should I compile and use TensorFlow Servings from my windows machine?

**Comment by kirilg** [comment]
There is no Windows support, so you can't compile it natively. Your best bet would be to try building it in a Docker container using [these instructions](https://tensorflow.github.io/serving/docker.html).
