### ISSUE TITLE
gpg key expired

### ISSUE THREAD

**Issue by gaborchris** [tensorflow/serving#2031]
### System information
- Linux Ubuntu 20.04
- binary
- **stable**

### Describe the problem
gpg public key expired on 7/19/22

### Exact Steps to Reproduce
```
$ echo "deb [arch=amd64] http://storage.googleapis.com/tensorflow-serving-apt stable tensorflow-model-server tensorflow-model-server-universal" | sudo tee /etc/apt/sources.list.d/tensorflow-serving.list && \
curl https://storage.googleapis.com/tensorflow-serving-apt/tensorflow-serving.release.pub.gpg | sudo apt-key add -

$ apt-get update
W: GPG error: http://storage.googleapis.com/tensorflow-serving-apt stable InRelease: The following signatures were invalid: EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>
E: The repository 'http://storage.googleapis.com/tensorflow-serving-apt stable InRelease' is not signed

$ apt-key list
...
pub   rsa4096 2017-07-13 [SC] [expired: 2022-07-19]
uid           [ expired] Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>
...
```

**Comment by pindinagesh** [comment]
Hi @gaborchris 

Could you please refer the similar issues [issue1](https://github.com/tensorflow/serving/issues/1395) and [issue2](https://github.com/tensorflow/serving/issues/1896) and also look at this [documentation](https://www.tensorflow.org/tfx/serving/setup#installation_2). Hope this helps, Thank you!

**Comment by gaborchris** [comment]
Hi @pindinagesh, yes this is the same issue but the key has expired again after one year.

**Comment by whdc** [comment]
Just chiming in to say that I'm facing this issue too. Would be great if addressed soon.

**Comment by KDmytro** [comment]
+1

**Comment by MachineITSvcs** [comment]
Also facing this issue. You'd think a company as big as Google would have automatic renewal. Linux Google repository certificate is also expired.

**Comment by bmzhao** [comment]
This should be fixed now.
