### ISSUE TITLE
tensorflow serving with mino s3

### ISSUE THREAD

**Issue by 521bibi** [tensorflow/serving#2037]
I started a minio S3 with docker locally
![image](https://user-images.githubusercontent.com/38529261/183051641-0d2f0d8a-bd9b-4e68-80b2-3cfe0f4a165f.png)
![image](https://user-images.githubusercontent.com/38529261/183051713-d57a7af0-309b-4b8e-b195-7f82629c7290.png)
Then,
`docker run --rm -p 8501:8501 --name tfs-s3 -e AWS_ACCESS_KEY_ID=minioadmin -e AWS_SECRET_ACCESS_KEY=minioadmin  -e S3_ENDPOINT=http://127.0.0.1:9000 -e AWS_REGION=us-east-1 -t tensorflow/serving:2.4.1 --model_config_file=s3://models/models.config`
error：
![image](https://user-images.githubusercontent.com/38529261/183053336-1b82253c-e01f-4b57-91b7-78c2fbc54838.png)
Tried tensorflow/serving version 2.4, 2.5, 2.6, all the same. Maybe my problem is with S3_ENDPOINT=http://127.0.0.1:9000? Or am I missing a step?
Hope someone can help me, thanks a lot

**Comment by sanatmpa1** [comment]
@521bibi,

As per [this comment](https://github.com/tensorflow/serving/issues/1963#issuecomment-1055903347) from a similar issue, `tensorflow_io` should be imported separately to your code to have `s3` access. Please confirm if you have already imported the same.

Also you can change the `S3_ENDPOINT` from loop back address to the actual endpoint IP to see if helps.

Thank you!

**Comment by 521bibi** [comment]
@sanatmpa1 

Adding tf_io will not work. When using tensorflow, import tf_io. It is useful to use the tf_io function, but I am using tensorflow serving now, and I want to use the official image directly.

The second solution is effective, I changed S3_ENDPOINT=http://127.0.0.1:9000 to other IP of my computer and it worked

Thank you very much

**Comment by 521bibi** [comment]
tensorflow serving with s3 has been solved, the next step I will try to deploy tensorflow serving with hdfs.

**Comment by 521bibi** [comment]
tensorflow serving with s3 has been solved, the next step I will try to deploy tensorflow serving with hdfs.

**Comment by MinH-09** [comment]
can you tell me how to use tensorflow serving with s3, thanks
