### ISSUE TITLE
Bazel test fails while executing "bazel test tensorflow_serving/..."

### ISSUE THREAD

**Issue by vasantivmahajan** [tensorflow/serving#204]
I followed the instructions for setting TensorFlow Serving using Docker on a Windows machine. I was able to successfully build and run the container. I also cloned and configured TensorFlow Serving, however, while testing Bazel using the command "bazel test tensorflow_serving/...", the following error is displayed.

![image](https://cloud.githubusercontent.com/assets/17990840/19357809/2eeee934-9141-11e6-806a-71e5ee7f45ef.png)

Any help is appreciated.

**Comment by vinuraja** [comment]
Did you run ./configure on the tensorflow directory ?

**Comment by vasantivmahajan** [comment]
@vinuraja Yes I executed the ./configure command in the TensorFlow directory

**Comment by sukritiramesh** [comment]
Hi @vasantivmahajan, looks like you were able to successfully build the tensorflow model server (based on https://github.com/tensorflow/serving/issues/209). Is this still an issue?

**Comment by vasantivmahajan** [comment]
@sukritiramesh: Yes, I was able to successfully build the model. Closing the issue.
