### ISSUE TITLE
Fastest way to install TF Serving in RHEL 8

### ISSUE THREAD

**Issue by shantanu-deepquanty** [tensorflow/serving#2053]
I'd like to know the fastest way to install Tensorflow Serving in an RHEL 8 system(with GPU support) which has a CUDA version 11.0

The official documentation in the tensorflow website only contains a Model Server binary for Ubuntu (using APT) but not for RHEL  
I had attempted to build a container with a Dockerfile according to the steps given in https://www.tensorflow.org/tfx/serving/building_with_docker#dockerfiles
and the docker file "Dockerfile.devel-gpu" to be specific and the build was not complete and gave a 404 Error at step 37

If not this method, is there a faster method to install in RHEL 8?

**Comment by singhniraj08** [comment]
@shantanu-deepquanty,

Kindly try to install using steps given in this [file](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.gpu).

You can also refer to below links for installing TF serving using GPU.
- [Serving with Docker using your GPU](https://www.tensorflow.org/tfx/serving/docker#serving_with_docker_using_your_gpu)
- [Using apt and pip to install TensorFlow Serving](https://towardsdatascience.com/getting-started-with-tensorflow-serving-b03c130bdb5c)

**Comment by shantanu-deepquanty** [comment]
@singhniraj08 
Thank you very much. The dockerfile that you had linked to (Dockerfile.gpu) worked like a charm. The other dockerfile I had used was erroneous (Dockerfile.devel-gpu)

**Comment by singhniraj08** [comment]
@shantanu-deepquanty,

Since this issue is resolved, closing this issue. 
Feel free to reopen and post your comments(if you still have queries on this). Thank you!
