### ISSUE TITLE
Why "-tmp" is added to version path in the checkpoint file when use exporter?

### ISSUE THREAD

**Issue by yejw5** [tensorflow/serving#207]
Firstly, we use exporter.Exporter(saver) to get the checkpoint and model files. And then, we hope that the model can be restored and continue our previous trains through the saver.restore() function. But when use the function saver.restore(), the checkpoint generate by exporter.Exporter(saver) is a little different with saver.save().
The content of checkpoint file is:
  ```
  model_checkpoint_path: "/tmp/linear_model/00000001-tmp/export-?????-of-00001"
  all_model_checkpoint_paths: "/tmp/linear_model/00000001-tmp/export-?????-of-00001"
  ```
However, there is no directory `/tmp/linear_model/00000001-tmp/`, only `/tmp/linear_model/00000001/` exists. But when running with Saver.save(), the path in the checkpoint file is the real filepath. 
What's the reason to add string `-tmp` behind the version? Besides, is there any other way to restore and continue train the model generated by exporter.Exporter()

**Comment by sukritiramesh** [comment]
Hi @yejw5, the exporter uses a temp location to export to and then copies that over to the final location. The reason for this is to ensure the export itself is created at the final location atomically.

The saver (supplied to the exporter) is used to 'save' checkpoints and when it is invoked, it is supplied with the temp path. See:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/session_bundle/exporter.py#L268

As a result, the 'checkpoint' text file that is written by the Saver is only aware of the `-tmp` path.

If you run Saver.save(...) directly, and supply it with the actual path, that would create a checkpoint file with the actual path (i.e. no `-tmp`).

To restore models exported using the Exporter, you can use the load functionality supported in Python and C++ here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/session_bundle

(Closing this issue; please feel free to reopen if you might have any further questions)

**Comment by tobegit3hub** [comment]
Thanks @sukritiramesh for the detailed explaination.

We use `exporter` to save the checkpoints for TensorFlow serving. And the program may want to restore the session from this files to continuing training. We always use `tf.Session` to create new session and use `saver.restore` if we find the checkpoint files exist. 

Is it possible for us to restore the session with native `saver.restore` instead of the `contrib.session_bundle`?

If we have moved the checkpoint files to the final location, why not edit the `checkpoint` file by the way?

**Comment by sukritiramesh** [comment]
One option here might be to simply use saver.save(...) to save and restore intermediate checkpoints and then use exporter periodically or at the very end to just save the final exported model. Would that work for you?

**Comment by tobegit3hub** [comment]
Thanks @sukritiramesh . This could help and makes sense. `exporter` do more things than `saver` and it's designed for inference service.

**Comment by sukritiramesh** [comment]
That's right; good to hear that solution should work for your use-case then.
