### ISSUE TITLE
Unable to load exported model with standard TensorFlow model server

### ISSUE THREAD

**Issue by vasantivmahajan** [tensorflow/serving#209]
While loading and exported model in the Tensorflow server , I successfully implemented the "bazel build //tensorflow_serving/model_servers:tensorflow_model_server" command. However, while running the "bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=mnist --model_base_path=/tmp/mnist_model/" the command stops at "File system polling update: Servable :{name:mnist version:1}; servable path: /tensorflow_serving/00000001; Polling frequency: 30" for a long time and need to interrupt the keyboard to come out of the execution.

![image](https://cloud.githubusercontent.com/assets/17990840/19493428/902ef94a-9548-11e6-83be-85d8889817ce.png)

Can someone please confirm if this means the server has started successfully?

**Comment by pldelisle** [comment]
Yes. The server is waiting for gRPC call. It's the normal behaviour.

**Comment by sukritiramesh** [comment]
Hi @vasantivmahajan, that is right -- the server was brought up correctly. The file system polling messages simply indicate which models were currently found at the exported path and were loaded in the server.

(Closing; please feel free to reopen if you have more questions)

**Comment by vasantivmahajan** [comment]
@sukritiramesh: So what is the best way to get back to terminal for executing further commands?

**Comment by sukritiramesh** [comment]
@vasantivmahajan If you'd just like to try out some queries and/or send requests programatically, you could open up another terminal window/tab to send the requests to the server.

**Comment by vasantivmahajan** [comment]
I need to execute the following command "bazel-bin/tensorflow_serving/example/mnist_client --num_tests=1000 --server=localhost:9000" and on executing it, the following error is displayed
![image](https://cloud.githubusercontent.com/assets/17990840/19494282/5e2446a4-954c-11e6-8e2c-b0af8e3fb06c.png)

**Comment by sukritiramesh** [comment]
Does this happen consistently? There is a 5 second timeout on the request which is usually sufficient. Can you try increasing that and rerunning the mnist client to see if it might have an impact?
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_client.py#L149

**Comment by vasantivmahajan** [comment]
@sukritiramesh I increased it to 15 seconds, however, the problem still persists.

**Comment by vasantivmahajan** [comment]
@sukritiramesh Could you please re-open the issue?

**Comment by sukritiramesh** [comment]
Can you check the version of grpc you are using?

**Comment by sukritiramesh** [comment]
Also, can you please confirm the following?
- the server is still running in the first terminal window when the client sends requests from another window, and
- the port specified when the client is run matches that where the server is running.

**Comment by vasantivmahajan** [comment]
The issue was resolved on restarting the machines and running the server in one window and making call from another window.

**Comment by sukritiramesh** [comment]
Glad it worked!

**Comment by peachyDinosaur** [comment]
Can someone explain how to run the client ? Do you need a separate container ? How do you run two windows without them being connected in the same bash terminal ?
