### ISSUE TITLE
Docker file instructions for building gpu dockers are not compatible with new tensorflow code.

### ISSUE THREAD

**Issue by rrkarim** [tensorflow/serving#2093]
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04

### Describe the problem
Trying to build the `Dockerfile.devel-gpu` image I'm running into the problem. Compiler can't find `CUBLASLT_MATRIX_LAYOUT_STRIDED_BATCH_OFFSET` (and more) attribute in cublas headers. I think this is the breaking change: https://github.com/tensorflow/tensorflow/commit/fb9dcd19ab4b4d109beae1e9ff838f42b480e15b#diff-ad24359a46ac20404fa3d12efb6fbc3eb0ee6095a9fa02b2bf7cb3425ea66be2.
I guess we need to support more recent cublas libraries in docker instructions.

**Comment by singhniraj08** [comment]
@rrkarim,

Could you please try [Dockerfile.gpu](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.gpu) file and let us know if that works. Thank you!

**Comment by rrkarim** [comment]
[Dockerfile.gpu](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.gpu) doesn't build tf serving

**Comment by singhniraj08** [comment]
@christisg,

`Dockerfile.devel-gpu` and `Dockerfile.gpu` images fails to build TF serving. Could you please take a look? Thank you!

**Comment by rrkarim** [comment]
@singhniraj08 sorry, no, when I said Dockerfile.gpu doesn't build I meant it doesnt run bazel build but the dockerfile is successful in building the image. Dockerfile.devel-gpu is not though and the problem is with cublas version.

**Comment by singhniraj08** [comment]
@rrkarim, Thank you for the clarification.

@christisg,  Dockerfile.devel-gpu image fails to build TF serving because of cublas version. Could you please take a look. Thank you!

**Comment by singhniraj08** [comment]
@rrkarim,

`Dockerfile.devel` is updated with Python 3.8 installed Ref: https://github.com/tensorflow/serving/commit/68d92ff3fdca0641f465cc3ba3858a619c8b82a6
Please try the updated Dockerfile.devel to build TF Serving and let us know if you face any issues. Thank you!
