### ISSUE TITLE
Cannot load model when training with python2.7

### ISSUE THREAD

**Issue by pldelisle** [tensorflow/serving#211]
Hi, 

I'm having trouble with loading my model in tensorflow_model_server when I trained it using Python 2.7.

The training runs fine. The model is successfully exported. But when I load it in tensorflow_model_server, I have this error :
`E tensorflow_serving/core/loader_harness.cc:104] Servable: {name: myModel version: 1} load failure: Invalid argument: NodeDef mentions attr 'Tdim' not in Op<name=ExpandDims; signature=input:T, dim:int32 -> output:T; attr=T:type>; NodeDef: embedding/ExpandDims = ExpandDims[T=DT_FLOAT, Tdim=DT_INT32, _device="/device:CPU:0"](embedding/embedding_lookup, embedding/ExpandDims/dim)`

And when I train my model using Python3.4, I don't have any issue.

Here is the code in the model : 

```

1. with tf.device('/cpu:0'), tf.name_scope("embedding"):
2.         W = tf.Variable(tf.random_uniform([vocab_size, embedding_size], -1.0, 1.0), name="W")
3.         self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)
4.         self.embedded_chars_expanded = tf.expand_dims(self.embedded_chars, -1)

```

On the other hand, during training, the vocabulary of my model is saved in a file. I wrote a client app to poll my model by sending it a sentence to classify. When I launch the client, this error pops out : 

`pldelisl@buck:~/Documents/tensorflow_serving/serving$ bazel-bin/tensorflow_serving/example/inception_client --server=localhost:9000 --sentence="schedule payment" > /tmp/log.txtTraceback (most recent call last):
  File "/home/pldelisl/Documents/tensorflow_serving/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf_serving/tensorflow_serving/example/inception_client.py", line 73, in <module>
    tf.app.run()
  File "/home/pldelisl/Documents/tensorflow_serving/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/pldelisl/Documents/tensorflow_serving/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf_serving/tensorflow_serving/example/inception_client.py", line 59, in main
    x_sentence = convert_external_inputs(FLAGS.sentence)
  File "/home/pldelisl/Documents/tensorflow_serving/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf_serving/tensorflow_serving/example/inception_client.py", line 45, in convert_external_inputs
    vocab_processor = learn.preprocessing.VocabularyProcessor.restore("/home/pldelisl/Documents/bot/bot/bot/cnn/experiments/runs/1476993973/vocab")
  File "/home/pldelisl/Documents/tensorflow_serving/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/contrib/learn/python/learn/preprocessing/text.py", line 226, in restore
    return pickle.loads(f.read())
ValueError: unsupported pickle protocol: 3`

So I'm screwed. It cannot read the vocabulary file since it seems like GRPC or Bazel doesn't support Python 3.4 and thus give me the error above, while tensorflow_model_server cannot load my model training in Python2.7 for an obscure reason.

I have the latest version of gprcio (I installed this week).

Any help would be really appreciated. 

Thank you.

**Comment by sukritiramesh** [comment]
Hi @pldelisle, with 2.7, could you share some code snippets of how the export was done? At a high level, it looks like the node def is not recognized because of the attribute. Could it be that the op requires to be linked in for the tensorflow model server to work correctly with it?

**Comment by kirilg** [comment]
@pldelisle the original error message says that op ExpandDims only has attr `T:type` and not `Tdim`, but Tdim was added in early September. My guess is your export used a newer version of TensorFlow than TensorFlow serving and there were some forward compatibility issues.

What commit is your TF Serving synced to? Can you try at current head with Python 2.7? (gRPC does not work well with 3.4 like you mentioned). Note that if you sync now, you'll want to also update submodules with `git submodule update --init` or perhaps simpler is to clone a new TF Serving repo with `git clone --recurse-submodules https://github.com/tensorflow/serving`

I don't think you'll need to re-export your model.

**Comment by pldelisle** [comment]
@kirilg  You were right (sorry for the delay). 

Updating both TensorFlow and Serving to current head solved the issue. 

Thank you very much !
