### ISSUE TITLE
Custom Metadata in SignatureDef

### ISSUE THREAD

**Issue by ndeepesh** [tensorflow/serving#2126]
## Feature Request
If this is a feature request, please fill out the following form in full:

### Describe the problem the feature is intended to solve
Is there a way to specify custom metadata to SignatureDef after training. We dont need this metadata for actual TF Serving but need it to create requests to TF Serving.

Also will TF Serving fail if we add this custom metadata to SignatureDef?

### Describe the solution
Ideally if there is a way to add custom metadata that will let us serve our models with all info contained at one place

### Describe alternatives you've considered
No alternatives yet

### Additional context
No additional context

**Comment by singhniraj08** [comment]
@ndeepesh,

[tf.keras.Model](https://www.tensorflow.org/api_docs/python/tf/keras/Model) automatically specify serving signatures, but you can explicitly declare a serving signature for your custom modules.  If you're looking for a way of enforcing an input signature for a specific function, see the [input_signature](https://www.tensorflow.org/api_docs/python/tf/function#args_1) argument to [tf.function](https://www.tensorflow.org/api_docs/python/tf/function).

To export multiple signatures, pass a dictionary of signature keys to ConcreteFunctions. Each signature key corresponds to one ConcreteFunction. For example, please refer [Specifying signatures during export](https://www.tensorflow.org/guide/saved_model#specifying_signatures_during_export).

For custom metadata, please use the signature constants defined [here](https://www.tensorflow.org/tfx/serving/signature_defs#related_constants_and_utils) that will be supported in TensorFlow Serving. In addition, SavedModel provides a [util](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/signature_def_utils.py) to help build a signature-def. Please refer [Sample structures](https://www.tensorflow.org/tfx/serving/signature_defs#sample_structures) for examples of the specific SignatureDefs that TensorFlow Serving supports for each API.

Hope this helps. Thank you!

**Comment by ndeepesh** [comment]
Hi @singhniraj08 
Thanks for your response. Can you please point me to an example that adds any custom metadata to SavedModel? Ideally I was looking for something like below

After Training 
signature_def= SignatureDef(..)
signature_def["custom_key"] = "custom_value"

In Serving Pipeline but before sending inference request to TF Serving
value = signature_def["custom_key"]
--> send predict request to TF Serving

**Comment by singhniraj08** [comment]
@ndeepesh,

Unfortunately adding logic to allow serving metadata other than signaturedefs is not on the roadmap right now.

Regarding how to serve the metadata stored in the saved model, I couldn't find any example to point to. Presumably, you'd add a constant to your graph holding the tensor value of interest (the input/output shape), create a new signature [1] and do inference with that signature. To implement this, you can refer to above links. 

To support custom metadata in Serving, there is a similar feature request #1248 in works . I would suggest you to +1 that issue and follow the issue for updates. 

Thank you!

**Comment by ndeepesh** [comment]
Thanks for your help @singhniraj08
