### ISSUE TITLE
Error when running tensorflow serving using docker

### ISSUE THREAD

**Issue by vusirikala** [tensorflow/serving#2133]
## Bug Report
I was following the https://www.tensorflow.org/tfx/serving/docker tutorial and got the following error. 

### System information
I am using Macbook M2 Pro. I am running tensorflow serving using docker. 

```
$ protoc --version                                           
libprotoc 3.21.4
```

### Exact Steps to Reproduce
I ran the below set of commands. 
``` 
docker pull tensorflow/serving
git clone https://github.com/tensorflow/serving
TESTDATA="$(pwd)/serving/tensorflow_serving/servables/tensorflow/testdata"
docker run --platform linux/amd64 -t --rm -p 8501:8501 -v "$TESTDATA/saved_model_half_plus_two_cpu:/models/half_plus_two" -e MODEL_NAME=half_plus_two tensorflow/serving 
```
And got the following error
``` 
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2345] CHECK failed: file != nullptr: 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: file != nullptr: 
qemu: uncaught target signal 6 (Aborted) - core dumped
/usr/bin/tf_serving_entrypoint.sh: line 3:     8 Aborted                 tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"
```

**Comment by singhniraj08** [comment]
@vusirikala,

This error looks like protobuf version compatibility issue. You can try again with below versions.



```
python:3.9
tensorflow-serving-api-2.11.1
tensorflow-2.11.1
protobuf-3.19.6
```

Also, Tensorflow serving with docker fails to run on Mac M1 which is an known issue and our team is already working to bring  tensorflow serving docker support on Macs. Please follow and +1 similar issue #1948 for updates. In Meantime, several users have reported success with custom builds as mentioned [here](https://github.com/tensorflow/serving/issues/1816#issuecomment-1173923041). Hope this helps.

Thank you!
