### ISSUE TITLE
cannot install tensorflow_serving_api 2.12.0 along with tensorflow 2.12.0

### ISSUE THREAD

**Issue by hengdashi** [tensorflow/serving#2138]
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **TensorFlow Serving installed from (source or binary)**: binary
- **TensorFlow Serving version**: 2.12.0

### Describe the problem
Cannot install tensorflow_serving_api 2.12.0 along with tensorflow 2.12.0 because the protobuf version dependencies are conflicting.

### Exact Steps to Reproduce
Please include all steps necessary for someone to reproduce this issue on their
own machine. If not, skip this section.

```python
pip install tensorflow==2.12.0 tensorflow_serving_api==2.12.0
```

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached. Try to provide a reproducible test case that is the bare
minimum necessary to generate the problem.

```
ERROR: Cannot install tensorflow-serving-api==2.12.0 and tensorflow==2.12.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    tensorflow 2.12.0 depends on protobuf!=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.20.3
    tensorflow-serving-api 2.12.0 depends on protobuf<3.20 and >=3.9.2
```

**Comment by singhniraj08** [comment]
@hengdashi,

Tensorflow Serving 2.12.1 is updated to match protobuf requirements to Tensorflow. Ref Commit: https://github.com/tensorflow/serving/commit/24028778d11bf67992d481ff573de171c396119b
Please try latest 2.12.1 version of TF Serving and let us know if you face any issues. Thank you!
