### ISSUE TITLE
Memory increases due to hot deployment

### ISSUE THREAD

**Issue by 749145134** [tensorflow/serving#2142]
After hot deployment,log has seen the output of the old model unloaded, but the memory has not been freed, has not been freed, which version is fixed?

**Comment by singhniraj08** [comment]
@749145134,

I came across similar issue #1664, where few users have confirmed that the memory usage increases at the beginning, but become stable after a while. Also, users have reported success by using `jemalloc` as LD_PRELOAD resolves the issue.

You can try to pull the latest TF Serving docker image, and install the jemalloc with apt, then set it to LD_PRELOAD environment variable in dockerfile and build a new image. As the result, the serving will run with jemalloc. You could refer to the following code snippet.

Please try the above steps and let us know if this resolves the issue. Thank you.

```
FROM tensorflow/serving:latest

RUN apt-get update && apt-get install -y libjemalloc-dev
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1
```

**Comment by 749145134** [comment]
Thanks for trying
