### ISSUE TITLE
What's the match relationship between the docker `tensorflow/serving:xx-devel` and serving version?

### ISSUE THREAD

**Issue by rhdong** [tensorflow/serving#2153]
Hi there, I'd like to know the right docker of `tensorflow/serving:xx-devel` for serving r2.8. I want to add customized OPs in serving and I find the `tensorflow version` in `tensorflow/serving:2.8.3-devel` is `2.10.0` which is confused.
So my question is what is the accurate compatible relationship among the `serving devel docker`, `serving`, and `tensorflow`?
Thank you so much~

**Comment by singhniraj08** [comment]
@rhdong,

For TF Serving compatible Tensorflow versions, you can refer to [TF Serving releases](https://github.com/tensorflow/serving/releases) which will includes the TF version on which TF Serving version is based on.
Ex: TF Serving 2.11.1 release is based on TF version 2.11.1. 


[Dockerfile.devel](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel) pulls the latest master branch to build TF Serving as shown [here](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel#L16). Thank you.

**Comment by rhdong** [comment]
Thank you all for the help~
