### ISSUE TITLE
Monitor memory usage of TensorFlow models

### ISSUE THREAD

**Issue by ndeepesh** [tensorflow/serving#2156]
We want to monitor memory usage of TensorFlow serving runtime on a per model basis. Currently we can get the memory used by Tensorflow completely but we dont have a way to get this information on a per model basis. We would like to have a solution that can work for both CPU and GPU memory

No alternatives are available that we know of

**Comment by singhniraj08** [comment]
@ndeepesh,

Similar Issue #1407 is already in progress. I will bump up the issue to the team and discuss on the implementation. Meanwhile, you can refer to similar [thread](https://stackoverflow.com/questions/40190510/tensorflow-how-to-log-gpu-memory-vram-utilization) in SO where an alternative is TF's Profiler being used for memory profiling if this helps.

Thank you!

**Comment by ndeepesh** [comment]
Hi @singhniraj08 
Apologies for not following up on this. We are primarily interested in CPU memory usage. The above two threads points to GPU memory usage

**Comment by singhniraj08** [comment]
@ndeepesh, I see new issue #2173 is created by you, Please track new issue for update. Thank you!
