### ISSUE TITLE
Expired GPG Key for Linux binary

### ISSUE THREAD

**Issue by codekevinthumbtack** [tensorflow/serving#2165]
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow Serving installed from (source or binary)**: apt
- **TensorFlow Serving version**: 2.13.0

### Describe the problem
We install tensorflow-model-server 2.13.0 through APT but it seems that the GPG key used to sign the package is expired. Looks like the issue of https://github.com/tensorflow/serving/issues/1395 and https://github.com/tensorflow/serving/issues/1896 resurfaced again.

### Exact Steps to Reproduce
See documentation: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md#installing-using-apt

### Source code / logs
logs:
09:08:16 1.067 Err:4 http://storage.googleapis.com/tensorflow-serving-apt stable InRelease
09:08:16 1.067   The following signatures were invalid: EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>
09:08:16 
09:08:16 2.208 W: GPG error: http://storage.googleapis.com/tensorflow-serving-apt stable InRelease: The following signatures were invalid: EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>
09:08:16 2.208 E: The repository 'http://storage.googleapis.com/tensorflow-serving-apt stable InRelease' is not signed.

**Comment by singhniraj08** [comment]
@codekevinthumbtack,

Thank you for brining this to our attention. We will update this thread asap as we have an update.

**Comment by singhniraj08** [comment]
@codekevinthumbtack,

Thank you for brining this to our attention. We will update this thread asap as we have an update.

**Comment by singhniraj08** [comment]
@codekevinthumbtack,

We have updated the GPG key. Could you try installing `tensorflow-model -server` as shown on [installation page](https://www.tensorflow.org/tfx/serving/setup#installing_using_apt). I am able to install `tensorflow-model -server` successfully now. Ref: screenshot below. Thank you!

![image](https://github.com/tensorflow/serving/assets/110809167/9e120fdc-fa06-43bf-b39a-6dc13757421d)

**Comment by erikhubers** [comment]
Thanks for updating the key, also works on my machine!

**Comment by codekevinthumbtack** [comment]
Thank you. It works.
