### ISSUE TITLE
GPG Key expired: EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key)

### ISSUE THREAD

**Issue by la210** [tensorflow/serving#2166]
Installation steps of [Serving installation](https://www.tensorflow.org/tfx/serving/setup#installation_2) fails with an error:
`Err:2 http://storage.googleapis.com/tensorflow-serving-apt stable InRelease
  The following signatures were invalid: EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>`
  
  Bypassing gpg-key checking helps with installations, but this is not an option due to security reasons.
  
```
apt-get -o Acquire::AllowInsecureRepositories=true \
    -o Acquire::AllowDowngradeToInsecureRepositories=true \
    update && \
apt-get install -o APT::Get::AllowUnauthenticated=true -y tensorflow-model-server 
```

**Comment by anjalirai-intel** [comment]
I am also facing the same issue

```apt-key list
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2017-07-13 [SC] [expired: 2023-07-27]
      916E 2B2F EBC2 7493 0BAC  A9D9 544B 7F63 BF9E 4D5F
uid           [ expired] Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>```

**Comment by singhniraj08** [comment]
@la210, @anjalirai-intel,

Thank you for bringing this issue to our attention. We already have a similar issue #2165 for tracking this issue. I would request you to close this issue, follow and +1 similar thread for updates.
