### ISSUE TITLE
Failed to build Tensorflow serving Dockerfile(TF2.4.4)

### ISSUE THREAD

**Issue by kbpark102** [tensorflow/serving#2167]
- My model can be used in tensorflow 2.4.x serving environment.
  I referenced the tf 2.4.4 docker file (https://github.com/tensorflow/serving/blob/2.4.4/tensorflow_serving/tools/docker/Dockerfile.devel-gpu)
  but i can't build it  
- **nvidia/cuda:11.0 was removed and nvidia/cuda:11.0.3 can be found**
  but when i change to nvidia/cuda:11.0.3 image i found the cuda library problem
- when i check  tensorflow_model_server (from 2.4.4) need the libvinfer7. but cuda:11.0.3 provides only libvinfer8
  how can i build the 2.4.4 dockerfile without cuda library error?

**Comment by singhniraj08** [comment]
@kbpark102,

We would recommend you to use latest version of TF Serving DockerFile as matching dependencies for older releases is difficult and not supported. Your model should run successfully with latest [TF Serving 2.13 release](https://github.com/tensorflow/serving/releases/tag/2.13.0). Thank you!
