### ISSUE TITLE
TF 2.11 on CUDA 11.8

### ISSUE THREAD

**Issue by ndeepesh** [tensorflow/serving#2169]
From this (https://www.tensorflow.org/install/source#linux) doc it seems for TF 2.4 CUDA 11.0 and for TF 2.11 CUDA 11.2 is required. Can we have both versions run on a newer version of CUDA (same major version) 11.8?

Do we have dockerfile references for such use case?

**Comment by singhniraj08** [comment]
@ndeepesh,

CUDA 11.8 support is introduced in TF Serving 2.12 release and updating CUDA versions in may lead to dependency issues.
I would recommend you to install Tensorflow Serving 2.12 or higher with CUDA 11.8 support. Ref: [TF Serving 2.12 Dockerfile](https://github.com/tensorflow/serving/blob/r2.12/tensorflow_serving/tools/docker/Dockerfile.devel-gpu#L26)

Thank you!

**Comment by ndeepesh** [comment]
@singhniraj08 What Dependency issues can we face? Can you provide some more details around it?

**Comment by singhniraj08** [comment]
@ndeepesh,

Few users reported issue with libvinefer version mismatch while bumping up the CUDA versions. Although, I tried to setting up base image as `nvidia/cuda:11.8.0-base-ubuntu20.04` in [TF Serving 2.11 Dockerfile.devel-gpu](https://github.com/tensorflow/serving/blob/r2.11/tensorflow_serving/tools/docker/Dockerfile.devel-gpu) and tried building the image but it failed with below error. Ref: Screenshot.

I would recommend you to use latest TF release >2.12 if you want CUDA 11.8 support. Thank you!

![image](https://github.com/tensorflow/serving/assets/110809167/3a68eda7-3dcc-47a2-9238-dec562a8d7a7)
