### ISSUE TITLE
Failed to build TF serving from source

### ISSUE THREAD

**Issue by nhatleSummer22** [tensorflow/serving#2170]
### System information
- **OS Platform and Distribution**: CentOS Linux release 8.5.2111
- **TensorFlow Serving installed from (source or binary)**: Building TF Serving from source

### Describe the problem
I followed the steps here to build TF serving from source: https://www.tensorflow.org/tfx/serving/setup, the command line `tools/run_in_docker.sh bazel build -c opt tensorflow_serving/...` caused error:
```
WARNING: Download from https://github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'bazel_skylib':
```
### Exact Steps to Reproduce
```
git clone https://github.com/tensorflow/serving.git
cd serving
tools/run_in_docker.sh bazel build -c opt tensorflow_serving/...
```

**Comment by singhniraj08** [comment]
@nhatleSummer22,

I tried building TF Serving from source in CentOS and it was running successfully. I was not able to complete the whole build since it's time consuming. Could you help us at which step of building did you faced this error? 

Also, You can try building a container from Dockerfile as shown [here](https://www.tensorflow.org/tfx/serving/building_with_docker#building_a_container_from_a_dockerfile). Please let us know if this helps. 

Thank you!

**Comment by nhatleSummer22** [comment]
@singhniraj08 
Thank you for your response. It seems that the build process is having trouble download the tar file from bazel_skylib repo. Here is the full error log:

WARNING: Download from https://github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'bazel_skylib':
   Traceback (most recent call last):
        File "/tf_serving/serving/.cache/_bazel_nhatle/27779cb87963ffbbb27f83adfbb38cc1/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz] to /tf_serving/serving/.cache/_bazel_nhatle/27779cb87963ffbbb27f83adfbb38cc1/external/bazel_skylib/temp10299663733471532390/bazel-skylib-1.3.0.tar.gz: connect timed out
ERROR: /localdisk2/nhatle/tf_serving/serving/WORKSPACE:36:21: fetching http_archive rule //external:bazel_skylib: Traceback (most recent call last):
        File "/tf_serving/serving/.cache/_bazel_nhatle/27779cb87963ffbbb27f83adfbb38cc1/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz] to /tf_serving/serving/.cache/_bazel_nhatle/27779cb87963ffbbb27f83adfbb38cc1/external/bazel_skylib/temp10299663733471532390/bazel-skylib-1.3.0.tar.gz: connect timed out
ERROR: Error computing the main repository mapping: no such package '@bazel_skylib//lib': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz] to /tf_serving/serving/.cache/_bazel_nhatle/27779cb87963ffbbb27f83adfbb38cc1/external/bazel_skylib/temp10299663733471532390/bazel-skylib-1.3.0.tar.gz: connect timed out
Loading:

**Comment by nhatleSummer22** [comment]
Problem is due to http issue within docker. Got a fix. Thank you!
