### ISSUE TITLE
Not using anaconda python virtual environment

### ISSUE THREAD

**Issue by prats226** [tensorflow/serving#218]
I am trying to run inception module as service using tensorflow serving. I have anaconda environment setup and all packages including tensorflow installed in it. However bazel compiled bins as specified in tutorial (https://tensorflow.github.io/serving/serving_inception) are not using python from conda virtual environment.

**Comment by enizhibitsky** [comment]
You can try whis workaround after building `inception_client` (edit anaconda path if needed):
```bash
chmod +w bazel-bin/tensorflow_serving/example/inception_client
sed -ie 's/usr\/bin\/python/home\/$USER\/\anaconda\/bin\/python/g' \
    bazel-bin/tensorflow_serving/example/inception_client
chmod -w bazel-bin/tensorflow_serving/example/inception_client
```
And then use modified version:
```bash
./bazel-bin/tensorflow_serving/example/inception_client \
  --server=localhost:9000 \
  --image=/tmp/image.jpg
```

**Comment by prats226** [comment]
Thanks for the workaround. I moved to docker now so no issues for now.
