### ISSUE TITLE
TensorBoard profile showing high usage of relu

### ISSUE THREAD

**Issue by law-lin** [tensorflow/serving#2180]
Hi, I'm trying to understand this TensorBoard profile
![Screenshot 2023-08-09 at 4 17 53 PM (1)](https://github.com/tensorflow/serving/assets/35390215/e37b196c-c660-4fe2-9e24-c20faa73692d)

Here, the op type _FusedMatMul is taking up a considerable amount of time, but the op specified is relu which should be a very simple op
Is relu the only op being formed for these entries (first and third row in the table) or is performing other ops (like matmul) as well?

**Comment by law-lin** [comment]
@singhniraj08 Makes sense. We're also seeing a high usage of SparseToDense in another model. Do you know if increasing the TF thread pool count in the CPU can help optimize SparseToDense?

**Comment by singhniraj08** [comment]
@law-lin,

I could find much on SpareToDense op to assist you, but got [Working with sparse tensors](https://www.tensorflow.org/guide/sparse_tensor) for efficient use of sparse tensors in Tensorflow graph if that helps. Thank you!
