### ISSUE TITLE
Unable to open Jupyter notebook from docker container running on a windows machine

### ISSUE THREAD

**Issue by vasantivmahajan** [tensorflow/serving#219]
I have set up Tensorflow Serving using a docker image by following the instructions from the given website https://tensorflow.github.io/serving/docker. I have successfully built and ran the container and I am able to execute the inbuilt models. 

I am trying to connect my container to Jupyter notebook so that I can execute my program on the TensorFlow Server. I executed pip install jupyter to install Jupyter notebook and ran the notebook using jupyter notebook command. The notebook seems to be running in the docker container, however I am unable to run it in local machine's web browser.

![image](https://cloud.githubusercontent.com/assets/17990840/19652615/72a3cae0-99df-11e6-9435-27fbf3ec79c9.png)

![image](https://cloud.githubusercontent.com/assets/17990840/19652645/8390335c-99df-11e6-9316-7a1e476b3b6e.png)

Any help is appreciated.

**Comment by kirilg** [comment]
I'm not very familiar with Jupyter notebooks. It looks like TF Serving is running fine but you're having trouble accessing the server in your web browser. Your best bet would probably be to ask for help from Jupyter support on either their GitHub or stackoverflow page - [community link](http://jupyter.org/community.html).

Please reopen if it ends up being an issue with TF Serving.

**Comment by fernandogarcia547** [comment]
Hello, i'm currently facing the same issue, i'm wondering if you found how solve it. Thanks!
