### ISSUE TITLE
TensorFlow serving seems to have no version attribute

### ISSUE THREAD

**Issue by zhangggzh** [tensorflow/serving#2194]
I built and installed the whl package for serving on ROCM myself, but found that only the pip list method was used to view the version of serving, while the    " import tensorflow_serving tenorflow_ serving.__ version__  " An error was reported, TensorFlow serving does not have the version attribute. May I ask if this attribute was not added to the source code during development

**Comment by singhniraj08** [comment]
@zhangggzh, Can you try using below command to check TF Serving version. Thank you!
```
tensorflow_model_server --version
```
For docker image you can do this:
```
docker run --rm -it tensorflow/serving tensorflow_model_server --version
```

**Comment by zhangggzh** [comment]
@singhniraj08 Hello, can you add the version attribute in Python? For example, after entering the Python environment, use " tensorflow_ serving__.version__ " to return the version information of serving

**Comment by janasangeetha** [comment]
Hi @zhangggzh 
As this is an old issue, please let us know if you are still looking for it. I am not sure if we are planning to pick this up. Meanwhile, you can try the solution mentioned in [comment](https://github.com/tensorflow/serving/issues/2194#issuecomment-1820226543).
