### ISSUE TITLE
Version 2.15 release?

### ISSUE THREAD

**Issue by ustramooner** [tensorflow/serving#2204]
## Feature Request
Please release version 2.15

### Describe the problem the feature is intended to solve
We want to upgrade to tensorflow version 2.15 but are blocked by a requirement on tensorflow-serving-api

### Describe the solution
Can someone please do a release of 2.15? Tensorflow 2.15 was released mid november, it would be helpful to have a tensorflow serving api upgraded to 2.15

**Comment by singhniraj08** [comment]
@ustramooner,

TF Serving 2.15 is already in progress and stuck because of some internal dependencies which needs to be taken care of. I will pass you issue internally and update the thread once we have an update on new release. Thank you.

**Comment by saimidu** [comment]
Hi, are there any updates on the TensorFlow 2.15 Serving release?

**Comment by supercoderhawk** [comment]
Are there any updates on the TensorFlow 2.15 Serving release? The new feature "mixed precision" is very important for me ..

**Comment by svenstaro** [comment]
Seems to me this can be closed now.

**Comment by singhniraj08** [comment]
@ustramooner, [Tensorflow Serving 2.16.1](https://github.com/tensorflow/serving/releases/tag/2.16.1) is released and should support TF 2.15. Please let us know if you face any issues. Thank you!
