### ISSUE TITLE
java.lang.RuntimeException: Unexpected code Response{protocol=http/1.1, code=400, message=Bad Request, url=http://localhost:8501/v1/models/myfruit:predict}

### ISSUE THREAD

**Issue by x13872140520** [tensorflow/serving#2215]
**System information**
operating system：
`win11 64bit`
tensorflow/serving version:
`2.14.1 `
TFserving Deployment mode:
`RESTful API`
python requirements.txt：
`tensorflow-cpu == 2.3.0
pyqt5
pillow
opencv-python
matplotlib`

**Describe the problem**

Hello everyone, my demand is to build an interface with java, the front-end transmits an arbitrary image, java uses `tensorflow for java` or `tensorflow serving` to use the model to make predictions, java gets the prediction results and returns to the front-end.
Now I am ready to experiment with python to train the model, save the model as saved_model, and then set up tensorflow serving. Now the local docker container has been successfully started.

![Image](https://github.com/tensorflow/serving/assets/24297104/900d700d-b6f4-4a9b-ad20-6df40a571581)

The python code for model training is copied online, and the specific code is as follows:

![PKU{ W4NKMQERFEW23GQ}X](https://github.com/tensorflow/serving/assets/24297104/8be36488-09a1-4b52-ab22-da504e8520da)

The model training is also trained, and it is predictable in the python version using the h5 format. The model information is as follows:

![Weixin Screenshot_20240408144143](https://github.com/tensorflow/serving/assets/24297104/cc9dcb9b-8883-4f79-a224-8b953329ac5d)

java as the client request code:

![QQ截图20240408144632](https://github.com/tensorflow/serving/assets/24297104/9bf89c08-97cf-40c9-9bec-763d375fd3da)

java is having trouble making requests to `tensorflow serving` and is not sure what to do. The error is as follows:
`java.lang.RuntimeException: Unexpected code 
Response{protocol=http/1.1, code=400, message=Bad Request, url=http://localhost:8501/v1/models/myfruit:predict}`

Look at https://tensorflow.google.cn/tfx/serving/api_rest#classify_and_regress_api here document as is can use base64 as parameters.
I tried the following formats, all failed, all reported similar to 400 errors
![Weixin Screenshot_20240408144510](https://github.com/tensorflow/serving/assets/24297104/06976af6-cfa5-40e9-ac29-4c6eb3b2aea8)

I am a java novice, tensorflow is also a novice, a lot of operations, basic terminology is not clear, do not know what knowledge is missing. Thank you for your generous advice. Do the parameters in sensory model training have a strong relationship with tfserving entry here? How do I organize parameters?

**Comment by singhniraj08** [comment]
@x13872140520, The error indicates that the Java client code for sending REST request to TF Serving API is sending a bad request. Please make sure you are making request in correct [format](https://tensorflow.google.cn/tfx/serving/api_rest#request_format). Here is a [python example](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple#make_rest_requests) for making REST request to your model in  TF Serving. Thank you!

**Comment by x13872140520** [comment]
Thanks for the answer, this problem is solved, the problem is that the code training the model needs to add base64 related processing, as follow:
![Image](https://github.com/tensorflow/serving/assets/24297104/0f4e5ce1-d6b0-4c3b-84b0-9e5c74e589b4)

and then it can return the result of probability distribution as follow:
TensorFlow Serving response: {
    "predictions": [[0.0142633133, 0.000105166473, 0.0256272946, 0.00341447047, 0.157596678, 0.00203850493, 0.561303079, 0.000357849116, 0.00741964, 0.227874041]
    ]
}。 but the new problem is that no matter what picture is predicted, this probability distribution is always the 7th largest.
I use the folder name as a label, to achieve the classification of pictures, everything in the python code environment is running well, can be correctly trained and predicted.

**Comment by singhniraj08** [comment]
@x13872140520, The probability distribution issue would be caused by some issue in model or when interpreting predictions from client side. Please make sure the model predictions are working correctly. And since there are no issues pending from Tensorflow Serving side, requesting you to close this issue. Thank you!
