### ISSUE TITLE
Build wide_n_deep_tutorial model in TensorFlow Serving

### ISSUE THREAD

**Issue by vasantivmahajan** [tensorflow/serving#222]
I have set up the TensorFlow server in a docker machine running on a windows machine by following the instructions from https://tensorflow.github.io/serving/serving_basic. I am successfully able to build and run the mnist_model. However, when I am trying to build the model for the wide_n_deep_tutorial example by running the following command "bazel build //tensorflow_serving/example:wide_n_deep_tutorial.py" the model is not successfully built as there are no files generated in bazel-bin folder.

![image](https://cloud.githubusercontent.com/assets/17990840/19695864/d246e062-9ab2-11e6-8004-7a60be933b07.png)

Since there is no error message displayed while building the model, I am unable to figure out the problem. I would really appreciate if someone can help me debug and solve the problem.

**Comment by kirilg** [comment]
tensorflow_serving/example doesn't contain wide_n_deep_tutorial.py

If those were local changes, did you make the appropriate changes to the BUILD file to include this new target? If the BUILD file target was named `wide_n_deep_tutorial` for example, the command should be:

`bazel build tensorflow_serving/example:wide_n_deep_tutorial`  // note no ".py" suffix.

**Comment by vasantivmahajan** [comment]
I manually added the following at the end of the BUILD file:

py_binary(
    name = "wide_n_deep_tutorial",
    srcs = [
        "wide_n_deep_tutorial.py",
    ],
    deps = [
        "@org_tensorflow//tensorflow:tensorflow_py",
        "@org_tensorflow//tensorflow/contrib/session_bundle:exporter",
    ],
) 
And build using the following command :  
bazel build tensorflow_serving/example:wide_n_deep_tutorial
