### ISSUE TITLE
Why TF Serving using one CUDA Compute Stream

### ISSUE THREAD

**Issue by ndeep27** [tensorflow/serving#2221]
Trying to understand why TF uses one CUDA compute stream? Is there a metric which shows if ops are waiting to be scheduled on that one compute stream? I want to understand if the ops are waiting in high QPS scenarios

**Comment by singhniraj08** [comment]
@ndeep27,
Looks like this is not an issue from Tensorflow Serving side. This question is better asked on [TensorFlow Forum](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there. Thank you!
