### ISSUE TITLE
gpg key expired (again)

### ISSUE THREAD

**Issue by sander110419** [tensorflow/serving#2247]
Like every year around this time, the GPG key used when installing from APT has expired again: https://storage.googleapis.com/tensorflow-serving-apt/tensorflow-serving.release.pub.gpg

**Comment by sander110419** [comment]
![image](https://github.com/user-attachments/assets/44c8cf05-a4c0-4f15-92f3-1abbb96f716c)

**Comment by tdstein** [comment]
For reference, here is last year's issue: https://github.com/tensorflow/serving/issues/2165

We are also seeing this issue. Here is the relevant error from console when running `apt-get update` on a machine with this installed.

```console
root@a4c3d99fc792:/connect# apt-get update | grep http://storage.googleapis.com/tensorflow-serving-apt
Get:1 http://storage.googleapis.com/tensorflow-serving-apt stable InRelease [3026 B]
Err:1 http://storage.googleapis.com/tensorflow-serving-apt stable InRelease
W: http://storage.googleapis.com/tensorflow-serving-apt/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: GPG error: http://storage.googleapis.com/tensorflow-serving-apt stable InRelease: The following signatures were invalid: EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>
E: The repository 'http://storage.googleapis.com/tensorflow-serving-apt stable InRelease' is not signed.
W: http://apt.postgresql.org/pub/repos/apt/dists/jammy-pgdg/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

**Comment by leegang** [comment]
How to Fix?

**Comment by sander110419** [comment]
Wait for them to update it, and hope this time they set a reminder to update it ahead of time or automate it.

**Comment by singhniraj08** [comment]
@sander110419, The gpg Key has been updated, Please try installing TF Serving using APT and let us know if you are still facing any issues. Thank you!

**Comment by tdstein** [comment]
The issue is resolved on my end @singhniraj08.

How can we avoid this from happening again in the future? Unfortunately, this issue is a significant interruption for anyone who has installed via APT.

**Comment by sander110419** [comment]
Confirmed fixed.
