### ISSUE TITLE
Build installable python package

### ISSUE THREAD

**Issue by llhe** [tensorflow/serving#229]
Currently the example code included in tensorflow serving project can be only run after bazel build, and it's also hard to write customized export and generic inference code (need to compile and import the extra protos which are not included in tensorflow core package).

It's better to build an installable package for tensorflow serving.

**Comment by kirilg** [comment]
All c++ code needs to be built with bazel, but if you're just modifying the export you should be able to use your installed TF package which includes session_bundle.

The Python clients only need the service API protos (gRPC is used as an installed package), which should be quick to build with `bazel build tensorflow_serving/example:mnist_client` for example.

We have very little Python in TF Serving, so the installable package would essentially only contain the API protos, which I think might not be worth it.

**Comment by kirilg** [comment]
It would be nice to have an installable package for the actual model_server though so you can avoid compiling all the C++ code.

**Comment by llhe** [comment]
@kirilg  Thanks for your comments. For our case, installable package for the model_server is not a strong requirement since only few people need to compile it.

**Comment by oxydron** [comment]
Would be nice if TF team focus on the installation problems, there are several.
Trying for some hours now to compile TF and use it, just because conda or pip versions aren't compiled with SSE4.1, SSE4.2 and AVX optimizations.

**Comment by EvenOldridge** [comment]
Agreed.  The tensorflow serving documentation itself suggests using 
pip install tensorflow-serving-api
but doing so results in:
Could not find a version that satisfies the requirement tensorflow-serving-api (from versions: )
No matching distribution found for tensorflow-serving-api

**Comment by kirilg** [comment]
The PIP package is new, so first as an update on this issue, we now have such a package and you can install it using `sudo pip install tensorflow-serving-api`

@EvenOldridge it sounds like you likely don't have the prerequisites that the package needs (tensorflow>=1.2.0 and grpcio >=1.0). I believe newer versions of PIP will install dependencies if they're missing, but older ones print an error. You can try installing the dependencies manually or updating pip with `sudo pip install -U pip setuptools`.

After that, you should be able to run `sudo pip install tensorflow-serving-api`.

**Comment by oxydron** [comment]
I did 
```shell
pip install -U pip setuptools
pip install tensorflow-serving-api
```
got
```
Could not find a version that satisfies the requirement tensorflow-serving-api (from versions: )
No matching distribution found for tensorflow-serving-api
``

**Comment by kirilg** [comment]
The PIP package is only available for python 2 (2.7 specifically). Could the issue be that you're using Python 3? If you're using 2.7 and it's not finding it still, can you try manually installing the prereqs just to check if it fixes things? For the latest release it's tensorflow>=1.3.0 and grpcio >=1.0.

**Comment by bmlis** [comment]
@kirilg Will you be supporting python 3 any time soon? Rewriting whole application stack to a way-outdated version of python is not an option for us, and I don't really see any other option than copying all proto files to our project and preparing .py by ourselves. Maybe I'm missing some more obvious solution here.

**Comment by oxydron** [comment]
Indeed I'm using python 3. Python 2 is outdated.

**Comment by iainhallam** [comment]
Speaking as an administrator of research desktops, rather than a user of the software, an RPM would be great.

**Comment by oxydron** [comment]
For those with this problem I suggest `pip install tensorflow-gpu`, while compiling from source is such a pain.
