### ISSUE TITLE
tf serving docker build failed at apt-get update/install

### ISSUE THREAD

**Issue by zsyet** [tensorflow/serving#232]
i'm trying to build docker image following the instruction, when i execute 
`docker build --pull -t $USER/tensorflow-serving-devel -f Dockerfile.devel .`

errors raised:
dl@dl127:~/tfserving$ docker build --pull -t $USER/tensorflow-serving-devel -f Dockerfile.devel .
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu
bf5d46315322: Pull complete 
9f13e0ac480c: Pull complete 
e8988b5b3097: Pull complete 
40af181810e7: Pull complete 
e6f7c7e5c03e: Pull complete 
Digest: sha256:147913621d9cdea08853f6ba9116c2e27a3ceffecf3b492983ae97c3d643fbbe
Status: Downloaded newer image for ubuntu:14.04
 ---> 1e0c3dd64ccd
Step 2 : MAINTAINER Jeremiah Harmsen <jeremiah@google.com>
 ---> Running in 337f6ae3afdf
 ---> 387f9a7bac30
Removing intermediate container 337f6ae3afdf
Step 3 : RUN apt-get update && apt-get install -y         build-essential         curl         git         libfreetype6-dev         libpng12-dev         libzmq3-dev         pkg-config         python-dev         python-numpy         python-pip         software-properties-common         swig         zip         zlib1g-dev         libcurl3-dev         &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 6eb2f5be2687
Err http://archive.ubuntu.com trusty InRelease
  
Err http://archive.ubuntu.com trusty-updates InRelease
  
Err http://archive.ubuntu.com trusty-security InRelease
  
Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-security Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libpng12-0

E: Unable to locate package build-essential
E: Unable to locate package curl
E: Unable to locate package git
E: Unable to locate package libfreetype6-dev
E: Package 'libpng12-dev' has no installation candidate
E: Unable to locate package libzmq3-dev
E: Unable to locate package pkg-config
E: Unable to locate package python-dev
E: Unable to locate package python-numpy
E: Unable to locate package python-pip
E: Unable to locate package software-properties-common
E: Unable to locate package swig
E: Unable to locate package zip
E: Unable to locate package zlib1g-dev
E: Unable to locate package libcurl3-dev
The command '/bin/sh -c apt-get update && apt-get install -y         build-essential         curl         git         libfreetype6-dev         libpng12-dev         libzmq3-dev         pkg-config         python-dev         python-numpy         python-pip         software-properties-common         swig         zip         zlib1g-dev         libcurl3-dev         &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

my docker version information:
dl@dl127:~/tfserving$ docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64

my os version information:
dl@dl127:~/tfserving$ uname -a
Linux dl127 4.2.0-36-generic #42~14.04.1-Ubuntu SMP Fri May 13 17:27:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

my network is behind proxy

**Comment by kirilg** [comment]
This looks like a connectivity problem on your machine where Docker cannot access the network. Please make sure that your machine can access the internet, and if it still doesn't work I would recommend asking Docker support to help configure it to work with your proxy.

**Comment by zsyet** [comment]
my docker can pull image, search from docker hub, as the error message shows, STEP 1 successfully pulled the ubuntu:14.04 image, so i think the proxy and network connectivity is already working correctly

**Comment by kirilg** [comment]
It's some kind of connectivity issue. Either it can't access the network or there is some DNS resolution error. A simple thing that might help is simply restarting the Docker service with the command `sudo service docker restart`

If that doesn't fix your issue, there is some additional network configuration steps you can try, but I'm not an expert on that and would recommend you reach out Docker support for that (either their GitHub or forum).
