### ISSUE TITLE
bazel build gcc err（gcc: internal compiler error: Killed (program cc1plus)）

### ISSUE THREAD

**Issue by gowtdy** [tensorflow/serving#236]
when I build tensorflow like “bazel build -c opt //tensorflow/tools/pip_package:build_pip_package”， I got the err， like：ERROR: /home/gowtd/ml/tf/src/tensorflow/tensorflow/core/kernels/BUILD:1089:1: C++ compilation of rule '//tensorflow/core/kernels:cwise_op' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 103 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

There is no enough error info， and I search from web, but I don't get useful information. Please help!
The environment：gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)。

**Comment by gowtdy** [comment]
And user tensorflow version： origin/r0.10

**Comment by rayglover-ibm** [comment]
I doubt you'd be able to compile cpu-only TensorFlow with gcc `4.8.5`. The earliest version I've used successfully is `4.9.3`, with or without cuda. Earlier versions would segfault.

**Comment by kirilg** [comment]
Seems to be an internal compiler error. Did you try @rayglover-ibm's suggestion? Closing for now due to inactivity.

**Comment by cfregly** [comment]
this worked for me, fwiw.  

i was seeing this error on ubuntu 14.04.  upgraded to gcc 4.9.x and the error went away.

i was only seeing this with ubuntu 14.04 / tensorflow 1.0 / gpu.  

ubuntu 14.04 / tensorflow 1.0 / cpu seems fine.
