### ISSUE TITLE
Support native build on windows

### ISSUE THREAD

**Issue by wenlele** [tensorflow/serving#240]
I find there is windows support for Bazel and gRPC. But the package dependencies required for TF serving are not available on windows, which makes it unable to have a native build of TF serving on windows. 
Is my understanding correct?
if so, is there any plan to support native build on windows?
if not, how to?

Any help is appreciated.

**Comment by kirilg** [comment]
There is no official support for TensorFlow Serving on Windows. The current best practice that works on Windows is building inside a [docker container](https://tensorflow.github.io/serving/docker), but we don't currently have plans to add native support.

Bazel support for Windows is highly experimental at this point, but if anyone from the community is interested in making TF Serving compile on Windows, we welcome contributions!
