### ISSUE TITLE
which tensorflow do tensorflow_serving use

### ISSUE THREAD

**Issue by KeyKy** [tensorflow/serving#246]
I have installed tensorflow using sudo pip install --upgrade $TF_BINARY_URL. After I git clone --recurse-submodules https://github.com/tensorflow/serving, I find that tensorflow_serving has its own tensorflow submodule. which tensorflow do tensorflow_serving use, in the dist-package folder or its own folder.

**Comment by kirilg** [comment]
The one in the submodule folder that gets cloned along with the repo.

You could choose to link in the installed TF module in your python code to export a model, but C++ server code relies on Bazel and links in TF code directly from the submodule.
