### ISSUE TITLE
Unable to make predictions on TensorFlow's Wide and Deep model loaded in TensorFlow Servings model_server

### ISSUE THREAD

**Issue by vasantivmahajan** [tensorflow/serving#251]
I have loaded the wide and deep model in the TensorFlow Serving's model server and I need to make predictions on the model. 

The following is the client program that I wrote to make the predictions:

```
def main(_):
  host, port = FLAGS.server.split(':')
  channel = implementations.insecure_channel(host, int(port))
  stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
  data  =['Z4OhA8nJHTz1jz8UEBLV','1475232207','57640c5a55a94','www.matchedcars.com','57640d9ba12fd','8','73.72.223.220','Personal Computer','Windows','1232134','48bf3cc222fcf952eb15dc1f55577d4','9'];
  # Send request
    # See prediction_service.proto for gRPC request/response details.
  request = predict_pb2.PredictRequest()
  request.model_spec.name = 'wide_n_deep'
  request.inputs['x'].CopyFrom(
        tf.contrib.util.make_tensor_proto(data))
  result = stub.Predict(request, 10.0)  # 10 secs timeout
  print(result)
```

However, on running ` bazel-bin/tensorflow_serving/example/wide_n_deep_model_predictions_client --server=localhost:9000` the following error is displayed.

![image](https://cloud.githubusercontent.com/assets/17990840/20444673/f73b9e6c-ad9f-11e6-954c-c160231855ef.png)

Can someone guide me a way in which I can make predictions on my model? Iff someone can point me to the documentation for making the predict_pb2.PredictRequest() requests that would be really helpful.

**Comment by vasantivmahajan** [comment]
Can someone assist me with this? Is there any documentation which describes the way in which prediction request is made?

**Comment by sukritiramesh** [comment]
Hi @vasantivmahajan, it looks like the signatures exported as part of the graph do not include an entry corresponding to "inputs" as a named generic signature.

Related comment for the requirement: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/predict.proto#L17

Named signature field in signatures:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/session_bundle/manifest.proto#L14

Generic signature structure:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/session_bundle/manifest.proto#L68

Can you try this change to see if it works? Thanks!

**Comment by vasantivmahajan** [comment]
I created a signature function which is called while exporting the model. The following is the code for the same.

```
classifier.export(export_dir=model_dir,signature_fn=my_classification_signature_fn)

def my_classification_signature_fn(examples, unused_features, predictions):
  """Creates classification signature from given examples and predictions.
  Args:
    examples: `Tensor`.
    unused_features: `dict` of `Tensor`s.
    predictions: `Tensor` or dict of tensors that contains the classes tensor
      as in {'classes': `Tensor`}.
  Returns:
    Tuple of default classification signature and empty named signatures.
  Raises:
    ValueError: If examples is `None`.
  """
  if examples is None:
    raise ValueError('examples cannot be None when using this signature fn.')

  if isinstance(predictions, dict):
    default_signature = exporter.classification_signature(
        examples(dtype=dtypes.int32), classes_tensor=predictions['classes'])

  else:

    default_signature = exporter.classification_signature(
        examples, classes_tensor=predictions)
  named_graph_signatures={
        'inputs': exporter.generic_signature({'x_values': examples}),
        'outputs': exporter.generic_signature({'preds': predictions})}    
  return default_signature, named_graph_signatures
```

By this, I specified the key `x_values` which could be used as the entry point. Using this approach the model is successfully exported. However, on making the predictions using the following `request.inputs["x_values"].CopyFrom(tf.contrib.util.make_tensor_proto(new_samples))`

However, it throws an error `output-0-of-type-double-does-not-match-declared-output-type-string`.

Is the default output type set as a string? If yes how can I set it to double?

**Comment by AshutoshDongare** [comment]
Check out this sample for [performing local predictions on Tensorflow Wide and Deep and save the results to CSV](https://github.com/AshutoshDongare/Tensorflow-Wide-Deep-Local-Prediction)

**Comment by wt-huang** [comment]
@AshutoshDongare thanks for pointing out the documentation.
