### ISSUE TITLE
+[-𝗟𝗜𝗩𝗘-𝐖𝐀𝐓𝐂𝐇-]— Orlando Pride vs Washington Spirit LiVe 𝐒𝐭𝐫𝐞𝐚𝐦𝐬 FrEe NWSL Final BrOaDcAsT oN TV Guide & 𝐒𝐭𝐫𝐞𝐚𝐦𝐢𝐧𝐠 23 November 2024

### ISSUE THREAD

**Issue by trdfcaft** [tensorflow/serving#2544]
Playoff soccer can be a fickle beast, but the 2024 NWSL season has provided a matchup of titans in the league final as the regular season champions Orlando Pride take on second-place finisher Washington Spirit.

[CLICK HERE TO WATCH LIVE STREAM NOW](https://tvchannelpass.live/soccer/)

[CLICK HERE TO WATCH LIVE STREAM NOW](https://tvchannelpass.live/soccer/)

[CLICK HERE TO WATCH LIVE STREAM NOW](https://tvchannelpass.live/soccer/)

It's a fitting matchup as the top two teams all year long make good on that with a spot in the title match. It's especially notable for the Orlando Pride, who reached the playoffs just once in their seven previous NWSL seasons until this year.

Across 2024, Orlando were far and away the best team in the league, reaching 23 matches unbeaten to start the year before suffering two defeats in their final three regular season games. They have put those brief struggles behind them when it matters most, though, as they knocked off the Chicago Red Stars and Kansas City Current in the playoffs to reach this stage.

STREAM:Free trial of Fubo to watch the 2024 NWSL final LIVE

Washington, meanwhile, finished the year with a flourish, losing just once since the start of July to rocket up the table and grab the second spot. After knocking off newcomers Bay FC in their first playoff match, it took a penalty shootout to down defending champions Gotham FC and reach the final.

Orlando Pride vs. Washington Spirit live stream, TV channel
Date: Saturday, November 23, 2024
Time: 8 p.m. ET / 5 p.m. PT
TV channel: CBS
Streaming: Fubo, Paramount+

WATCH LIVE SOCCER WITH FUBO. START YOUR FREE TRIAL TODAY

WATCH LIVE
The 2024 NWSL final will be broadcast on network television in the United States, aired live on CBS. Jacqui Oatley and Lori Lindsey will have the commentary duties for the match, with Emily Proud as the sideline reporter.

Fans in the U.S. can access CBS live on Fubo, who is offering a free trial for new users. For a limited time, you can get your first month of Fubo for as low as $59.99, a $20 savings. Stream ESPN, ABC, CBS, Fox, NBC and 200+ top channels of live TV and sports without cable. (Participating plans only. Taxes and fees may apply).

The match can also be found streaming on CBS's dedicated platform Paramount+, which is also the home of the UEFA Champions League, Italian Serie A, Scottish Premiership, and the CONCACAF Nations League.

What time is kickoff of the 2024 NWSL final?
The 2024 NWSL final between the Orlando Pride and Washington Spirit kicks off from CPKC Stadium on Saturday, November 23 at 7 p.m. local time in Kansas City, MO.

Here's how that time translates across the time zones in North America:

 	Date	Kickoff time
Eastern Time	Sat, Nov. 23	8 p.m.
Central Time	Sat, Nov. 23	7 p.m.
Mountain Time	Sat, Nov. 23	6 p.m.
Pacific Time	Sat, Nov. 23	5 p.m.
Orlando Pride vs. Washington Spirit lineups & team news
The Orlando Pride are led by superstar attacking duo Barbra Banda and Marta, who complement each other beautifully up front. Banda, an MVP nominee, finished second in the league's Golden Boot race with 16 goals, while 38-year-old Marta enjoyed a renaissance season with 11 of her own.

Anchoring the back line is emerging U.S. international Emily Sams who was named to the NWSL Best XI, while full-back Kerry Abello was given second-team honors.

Orlando Pride projected starting lineup (4-4-2): Moorhouse (GK) — Dyke, Sams, Strom, Abello — Watt, Angelina, Hanson, Adriana — Marta, Banda.

The Washington Spirit boasts USWNT superstar Trinity Rodman, who should be healthy and ready to go after being rested for the recent international break. She has not picked up a goal contribution since mid-September, however, and will need to lift her performances if the Spirit are to win a trophy.

Other USWNT stars present in the XI are Casey Krueger at full-back and 22-year-old Hal Hershfelt who like Sams has emerged as one for the national team's future at the No. 6 position. So too has Croix Bethune, but the NWSL Rookie of the Year was felled for the season with a freak knee injury back in early September.

Washington Spirit projected starting lineup (4-2-3-1): Kingsbury (GK) — Metayer, McKeown, Morgan, Krueger — Hershfelt, Stainbrook — Rodman, Stanos, Kouassi — Hatch.

**Comment by Acanthopterygian** [comment]
cfsde


[![wer](https://github.com/user-attachments/assets/3025ba76-8ee1-4fe9-9119-6f60093e082b)](https://bit.ly/3Z0z1cz)



[![wer](https://github.com/user-attachments/assets/ba76c8db-fa4a-437e-8405-af0335443109)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/199ab3a9-0845-41ab-9231-1912a342d29b)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/329599bf-77a4-411b-b577-cdb3c94986d8)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/90096759-ff09-4c3b-9e49-6f4397652bbc)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/482dc188-8847-4bd3-9501-139d9f62ca46)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/b5bdb8f4-f3e9-4c9d-ac6e-a10a1da352e2)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/0b7ea2a3-83ca-4ff6-8c7f-e716ff6e7ff9)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/b4472ec9-5d7c-4dc0-b64e-c6191fa0ca4d)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/5bc2de97-151d-46a0-914e-b4c70e8b9a39)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/a0c47e7c-d44d-4a0b-8c83-9d0622f4dc91)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/d28ae9c2-62c5-4486-a839-6448c139d66f)](https://bit.ly/3Z0z1cz)


[![wer](https://github.com/user-attachments/assets/33ebab5b-a38c-4fd2-91d5-033c1967965f)](https://bit.ly/3Z0z1cz)


xswq
