### ISSUE TITLE
Ways to reduce client response time?

### ISSUE THREAD

**Issue by mogumogu2333** [tensorflow/serving#255]
Hi,

I'm trying to use a tensorflow serving service. The model is a standard convolution neural network text classifier. I deployed the grpc server and client on separate machines(4 cores each). I tried Jmeter to test the performance. With increasing concurrent threads, the max throughput is about 800, and 90% users response time is about 1.8s. 

My question is, is there any solutions to improve the performance and decrease the response time? I know this may not be a tf serving question, but the system level optimization. But still hope any one can give some advises about it. 

Thanks.

**Comment by chrisolston** [comment]
Hi,

I have a couple of thoughts:

1. Do you know how much time the raw tensorflow component of the inference takes. Generally speaking, TF-Serving should only add a tiny overhead on whatever the tensorflow::Session::Run() call costs. If that's no the case then either there's a bug or misconfiguration somewhere (see #2 for one possibility).

2. Do you have batching turned on? If you do, be sure to set the batch_timeout_micros parameter carefully. If you set it to a large number, then a single request can wait for a long time if no other requests arrive quickly to fill up a batch. See BatchingParameters in session_bundle_config.proto.



-Chris
