### ISSUE TITLE
too many data in PredictRequest resulting to RPC error returned to client

### ISSUE THREAD

**Issue by zsyet** [tensorflow/serving#256]
`request = predict_pb2.PredictRequest()
request.model_spec.name = 'criteo'
_label = batch_labels[i * batch_size: (i + 1) * batch_size]
_cols = batch_ids[i * batch_size: (i + 1) * batch_size].flatten()
_vals = batch_wts[i * batch_size: (i + 1) * batch_size].flatten().astype(np.float32)
print 'cols len=', len(_cols), ', vals len=', len(_vals)
pl1 = tf.contrib.util.make_tensor_proto(_cols, shape=[1, len(_cols)])
request.inputs['cols'].CopyFrom(pl1)
pl2 = tf.contrib.util.make_tensor_proto(_vals, shape=[1, len(_vals)])
request.inputs['vals'].CopyFrom(pl2)
result_counter.throttle()
result_future = stub.Predict.future(request, 5.0)  # 5 seconds
result_future.add_done_callback(_create_rpc_callback(_label, result_counter))`

as the above code shown, sorry for codes in such a mess, i don't how to let github make them look orderly,  the length of _cols is about 390k, and client print the error:

`AbortionError(code=StatusCode.INTERNAL, details="{"created":"@1479909701.782441304","description":"RST_STREAM","file":"src/core/ext/transport/chttp2/transport/frame_rst_stream.c","file_line":107,"http2_error":2}")
E1123 14:01:41.783720887    6623 chttp2_transport.c:1810]    close_transport: {"created":"@1479909701.783697419","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427}`

but if i change the array length smaller, the error will not happen, it seems RPC or tensorflow serving can't accept too many request data, 

but in my applicatioin, it does need to send so long an array to server to inferrence, 
is there any parameter can be set to support large data request?

**Comment by chrisolston** [comment]
From what I can ascertain it seems like an error/limitation in the gRPC layer. Perhaps you can ask in a gRPC forum?

**Comment by kirilg** [comment]
The max request size has since been increased from 4MB to [MaxInt](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc#L255), so the problem should be resolved.
