### ISSUE TITLE
TF model import & export documentation

### ISSUE THREAD

**Issue by Arsakes** [tensorflow/serving#260]
I wonder why I have to use
tensorflow.contrib.session_bundle and following code for model exporting:
```
Saver = tf.train.Saver(sharded=True)
model_exporter = exporter.Exporter(saver)
model_exporter.init(
    sess.graph.as_graph_def(),
    named_graph_signatures={
        'inputs': exporter.generic_signature({'images': x}),
        'outputs': exporter.generic_signature({'scores': y})})
model_exporter.export(export_path, tf.constant(FLAGS.export_version), sess)
```
Obviously I need to tell TFServing where are the input & output points for model - but  is it configurable?
If not where it is defined that TFServing looks for those particular names?

Can I write custom servable loader that would rather use regular saver and would check graph for collections named "inputs" and "outputs" for i/o instead?

How does this ` tensorflow.contrib.session_bundle`  fits into TensorFlow serving?

**Comment by chrisolston** [comment]
The SourceAdapter/Loader that comes with TF-Serving supports SessionBundle without the need to write any custom code. Of course, as you mentioned you're welcome to write your own SourceAdapter/Loader for whatever export format you like, if SessionBundle doesn't suit your needs.

**Comment by Arsakes** [comment]
Can get to know why it is written that way? Where in the code is the part responsible for loading tf models into serving server?

**Comment by chrisolston** [comment]
The code for loading SessionBundles is in servables/tensorflow/session_bundle_factory.{h,cc}.

FYI the signatures are primarily there to facilitate possible future stylized APIs e.g. Classify() or Regress().

**Comment by kirilg** [comment]
@Arsakes you can write a custom loader like Chris mentioned, but from your original question, if you just want to customize the input and output, you can do that with Signatures. Specifically [GenericSignature](https://github.com/tensorflow/tensorflow/blob/57d72f088059cdd5e71234e3d7dcd1ce456d0643/tensorflow/contrib/session_bundle/manifest.proto#L41) for the Predict API. You can read more about Signatures in this [tutorial](https://tensorflow.github.io/serving/serving_basic).
