### ISSUE TITLE
how to serve a chatbot's model

### ISSUE THREAD

**Issue by Samurais** [tensorflow/serving#264]
# Description
After checking the examples, it is for how to serve a mnist model. 
**tensorflow_model_server** can be used to serve a model in such manner. 

```
tensorflow_model_server --enable_batching --port=9000 --model_name=mnist --model_base_path=/tmp/monitored
```

But in my condition, there are embedding words and vocabulary, how to load them and use it?

**Comment by sukritiramesh** [comment]
Hi @Samurais, can you share a bit about how you export your model for serving? If you are using the exporter, as in the mnist example, you can specify vocabs, etc. as part of the assets collection during export here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/session_bundle/exporter.py#L160

These will then be loaded in the tensorflow_model_server.

**Comment by tobegit3hub** [comment]
`assets_collection` seems what we need for vocabulary file. 

Is there any example code or tutorial about using this? @sukritiramesh

**Comment by sukritiramesh** [comment]
A simple example of how to specify asset collections during export and import can be found at:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/session_bundle/exporter_test.py#L78

Hope this helps!

**Comment by zakizhou** [comment]
exporter is going to be deprecated, is there an example of assets in saved_model?

**Comment by sukritiramesh** [comment]
Hi @zakizhou, the flow should be pretty similar. Here is an example with SavedModel:

1. Build time: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/saved_model/saved_model_half_plus_two.py

2. Load time:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/saved_model/loader_test.cc
