### ISSUE TITLE
Documentation for using tensorflow serving with minikube

### ISSUE THREAD

**Issue by dlorenc** [tensorflow/serving#265]
Right now the documentation at http://tensorflow.github.io/serving/serving_inception walks users through creating a docker image, running that locally in Docker, then deploying to a production Kubernetes cluster in GCP.

I work on the [Minikube](github.com/kubernetes/minikube) project, which is the official local development environment for kubernetes. Would anyone mind if I send a PR to add some steps for running tensorflow serving locally using minikube?

**Comment by dlorenc** [comment]
cc @r2d4 @aaron-prindle @elibixby

**Comment by kirilg** [comment]
A PR with documentation would be great! Thanks @dlorenc!

**Comment by woodbor** [comment]
@dlorenc : could you share in the meantime some gists , about what are the steps for running tensorflow serving locally using minikube?
thx

**Comment by chakpongchung** [comment]
Are there any updates abouot running tensorflow serving locally using minikube?

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
