### ISSUE TITLE
Compatibility for 3.0 compute graphics cards ?

### ISSUE THREAD

**Issue by dangithubs** [tensorflow/serving#274]
Just did a build of TensorFlow Serving on AWS and it at the end informed me that it is ignoring the K520 Grid GPU because it is only compute compatible 3.0.

Regular TensorFlow appears to work with the GPU without any issues, is there a reason why Serving does not ? Reading previous strands it looks like there was a patch applied to allow 3.0 work on regular TensorFlow. Can this same patch be applied to Serving ?

**Comment by nfiedel** [comment]
Hi,
  Do you know when the patch was applied to TensorFlow? Our last sync of the serving repo to the latest TensorFlow repo was done ~7 days ago, so it's possible we just don't have it _yet_.

**Comment by gautamvasudevan** [comment]
I'm pretty sure this is resolved - please let me know if it's not.
