### ISSUE TITLE
【Kraken Official】How to contact Kraken Support?

### ISSUE THREAD

**Issue by shirinscott5478** [tensorflow/serving#2753]
Navigate to the Kraken support FAQ page to find 🆑⭐️ 1-(850)-468-9565. Scroll all the way to the bottom and the last section is "Getting Help." 🆑⭐️ 1-(850)-468-9565, In that section there is a chat link to contact Kraken agent.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
