### ISSUE TITLE
【Kraken Official】How do you contact Kraken?

### ISSUE THREAD

**Issue by shirinscott5478** [tensorflow/serving#2754]
【Kraken Official】How do you contact Kraken?
Contact Kraken Support on 🆑⭐️ 1-(850)-468-9565 for immediate assistance. Please complete the form at our support 🆑⭐️ 1-(850)-468-9565 web page and allow up to 24 hours for an e-mail response from a customer service representative.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
