### ISSUE TITLE
【Kraken Support™】How do you contact Kraken Number?

### ISSUE THREAD

**Issue by shirinscott5478** [tensorflow/serving#2756]
【Kraken Support™】How do you contact Kraken Number?
You can contact support at Kraken via email, phone 🆑⭐️ 1-(850)-468-9565, or chat without needing special permission - it's completely legal and encouraged to call on 🆑⭐️ 1-(850)-468-9565 if you need assistance.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
