### ISSUE TITLE
Op type not registered 'TreePredictions'

### ISSUE THREAD

**Issue by sushant-hiray** [tensorflow/serving#278]
I'm currently using the latest serving `master` branch [(85db9d3)](https://github.com/tensorflow/serving/commit/85db9d3aa7f03c4be10329d2b7697ee07884687e) and trying to load a random forest model trained in tensor flow. However, it is throwing a `Op type not registered` error.

This is the entire trace I get while trying to load the model.

```
bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9999 --model_name=rf --model_base_path=/home/tensorflowserv/rf/
I tensorflow_serving/model_servers/main.cc:146] Building single TensorFlow model file config:  model_name: rf model_base_path: /home/tensorflowserv/rf/ model_version_policy: 0
I tensorflow_serving/model_servers/server_core.cc:261] Adding/updating models.
I tensorflow_serving/model_servers/server_core.cc:298]  (Re-)adding model: rf
I tensorflow_serving/core/basic_manager.cc:664] Successfully reserved resources to load servable {name: rf version: 100}
I tensorflow_serving/core/loader_harness.cc:74] Approving load for servable version {name: rf version: 100}
I tensorflow_serving/core/loader_harness.cc:89] Loading servable version {name: rf version: 100}
I external/org_tensorflow/tensorflow/contrib/session_bundle/session_bundle.cc:161] Attempting to load a SessionBundle from: /home/tensorflowserv/rf/00000100
I external/org_tensorflow/tensorflow/contrib/session_bundle/session_bundle.cc:162] Using RunOptions:
E external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:925] OpKernel ('op: "NegTrain" device_type: "CPU"') for unknown op: NegTrain
E external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:925] OpKernel ('op: "Skipgram" device_type: "CPU"') for unknown op: Skipgram
I external/org_tensorflow/tensorflow/contrib/session_bundle/session_bundle.cc:244] Loading SessionBundle: fail. Took 63909 microseconds.
E tensorflow_serving/core/loader_harness.cc:108] Servable: {name: rf version: 100} load failure: Not found: Op type not registered 'TreePredictions'
```

Here is the basic snippet of creating and exporting the random forest model.

```
hparams = tf.contrib.tensor_forest.python.tensor_forest.ForestHParams(
     num_trees=3, max_nodes=1000, num_classes=3, num_features=4)

classifier = tf.contrib.learn.TensorForestEstimator(hparams, model_dir=out_dir)

classifier.fit(input_fn=lambda: input_fn(train_data, train_labels), steps=100)
classifier.export(export_dir=out_dir, input_fn=export._default_input_fn)
```

Any help or pointers would be appreciated.

**Comment by sukritiramesh** [comment]
Hi @sushant-hiray, is this the TreePredictions class defined here?
https://github.com/tensorflow/tensorflow/blob/dbe5e17e2ed307e86e1a6e79e558ec3e335d46fc/tensorflow/contrib/tensor_forest/core/ops/tree_predictions_op.cc

It looks like the set of supported ops for tensorflow_serving/model_servers/tensorflow_model_server may not include this op: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/BUILD#L80

Can you include the op, rebuild with Bazel and check if it works? Thanks.

**Comment by sushant-hiray** [comment]
Hi @sukritiramesh, 

I just tried the suggestion and it worked. The issue was the missing op in the BUILD file.
Should I send a PR to include those ops in the BUILD for model_servers so that the model_server can support these out of box.

Thanks.

**Comment by kirilg** [comment]
@sushant-hiray We'd like to only keep stable ops in the "out of the box" model server, so are only depending on [TensorFlow's support ops](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/BUILD#L80). I'm not sure about the status of `TreePredictions` or whether it's ready to be considered stable, but I would recommend discussing with the TensorFlow team about promoting that op to include it in `tensorflow/contrib:contrib_kernels` and `tensorflow/contrib:contrib_ops_op_lib` instead of adding new deps directly to the model server.
