### ISSUE TITLE
How do I contact Uphold support number?

### ISSUE THREAD

**Issue by vipsscott** [tensorflow/serving#2842]
How do I contact Uphold support number?
Contact the Uphold Wallet Registry team on 🆑⭐️ 1-(850)-468-9565 through Customer Central: Go to Uphold Support Central via 🆑⭐️⭐ 1-(850)-468-9565, click Help, then Contact Us, and select the appropriate issue.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
