### ISSUE TITLE
【Uphold Official】How to contact Uphold Support?

### ISSUE THREAD

**Issue by vipsscott** [tensorflow/serving#2844]
【Uphold Official】How to contact Uphold Support?
Navigate to the Uphold support FAQ page to find 🆑⭐️ 1-(850)-468-9565. Scroll all the way to the bottom and the last section is "Getting Help." 🆑⭐️ 1-(850)-468-9565, In that section there is a chat link to contact Uphold agent.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
