### ISSUE TITLE
Uphold Customer Service ⭐ 1-(850)-468-9565 Number?

### ISSUE THREAD

**Issue by vipsscott** [tensorflow/serving#2845]
Uphold Customer Service ⭐ 1-(850)-468-9565 Number?
If you want to place an order over the phone 🆑⭐️ 1-(850)-468-9565 or have an urgent support matter related to Uphold wallet, please call customer support at 🆑⭐️ 1-(850)-468-9565, or Email thread at [contact@Uphold.com](mailto:contact@uphold.com).

**Comment by janasangeetha** [comment]
Closing this issue as a spam
