### ISSUE TITLE
How do I contact Kraken support? {{Fast Help}}

### ISSUE THREAD

**Issue by vipsscott** [tensorflow/serving#2847]
How do I contact Kraken support? {{Fast Help}}
Use the general enquiry number, 🆑⭐️ 1-(850)-468-9565, and ask to be transferred to Kraken Support. Then there's also the users' customer support hotline 🆑⭐️ 1-(850)-468-9565 by which Kraken be contacted immediately for live assistance.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
