### ISSUE TITLE
How do I contact Kraken support, Is Kraken 24/7 [Kraken]

### ISSUE THREAD

**Issue by vipsscott** [tensorflow/serving#2848]
How do I contact Kraken support, Is Kraken 24/7?
Kraken has a dedicated customer support number 🆑⭐️ 1–850–468–9565, team is available 24/7 through various channels such as phone 🆑⭐️ 1–850–468–9565, email, chat, and social media to provide prompt and instant assistance.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
