### ISSUE TITLE
How to debug with TensorFlow Serving

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/serving#285]
Now we have the internal error in TensorFlow Serving, refer to https://github.com/tensorflow/serving/issues/284 .

Can we add the flag for `tensorflow_model_server` so that everyone can get the error from internal?

**Comment by chrisolston** [comment]
Hi,

Feel free to submit a PR that adds a line of logging. As long as the logging isn't too verbose it should be fine. The best is to use VLOG(1) so that it's off by default.

(You may want to add the logging in a branch and do your debugging first, so you're sure what logging statement(s) turn out to be useful, before merging it with head.)

-Chris

**Comment by xiaop1987** [comment]
@chrisolston Hi, How to turn on VLOG when running Tensorflow Serving?

**Comment by chrisolston** [comment]
Try this flag: --v=1.

**Comment by xiaop1987** [comment]
@chrisolston  this flag didn't work for me, I turn on VLOG by add an env: TF_CPP_MIN_VLOG_LEVEL=1

**Comment by nbajason** [comment]
@xiaop1987 may I ask where is the log by default? or where can I set the log dir?

**Comment by cchung100m** [comment]
@nbajason 
I also tried the flag : -v=1, -v=2, -v=3, and -v=4 but nothing happened
You can use command: "export TF_CPP_MIN_VLOG_LEVEL=3", it works to me.

reference : https://stackoverflow.com/questions/46359852/logging-requests-being-served-by-tensorflow-serving-model

**Comment by lxl910915** [comment]
@nbajason Can you share how to debug using gdb?

**Comment by hgadig** [comment]
Please post support related questions in StackOverflow as we encourage users to post only bug/feature request here.

**Comment by sathyamoorthyrr** [comment]
Could anyone help with this [question](https://stackoverflow.com/questions/55585087/how-to-debug-models-running-in-tensorflow-serving)?
