### ISSUE TITLE
Configure Tensorflow Serving in Docker container failed

### ISSUE THREAD

**Issue by jianpingliu** [tensorflow/serving#286]
I was trying to set up tensorflow serving via docker following the instructions from the documentation https://tensorflow.github.io/serving/docker. I ran the following commands:

```
git clone --recurse-submodules https://github.com/tensorflow/serving
cd serving/tensorflow
./configure
cd ..
bazel test tensorflow_serving/...
```

However, it failed at` ./configure`. It failed to connect to GitHub with the following error:

`INFO: Failed to connect to https://github.com/polymerelements/paper-tabs/archive/v1.7.0.tar.gz tryin\`

I'm running docker on macOS Sierra.

Here is the complete output:

```
root@95bd9db7a4cb:/serving/tensorflow# ./configure
/serving/tensorflow /serving/tensorflow
Please specify the location of python. [Default is /usr/bin/python]:
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N]
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N]
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N]
No CUDA support will be enabled for TensorFlow
Configuration finished
INFO: Reading 'startup' options from /root/.bazelrc: --batch

INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: Reading 'startup' options from /root/.bazelrc: --batch
____Loading package: tensorflow
____Loading package: tensorflow/contrib/android
____Loading package: tensorflow/python/saved_model/example
____Failed to connect to https://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz trying again in 100ms
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 3,612,342 bytes
INFO: Reading 'startup' options from /root/.bazelrc: --batch
INFO: Failed to connect to https://github.com/polymerelements/paper-tabs/archive/v1.7.0.tar.gz tryin\
INFO: Failed to connect to https://github.com/polymerelements/iron-overlay-behavior/archive/v1.10.1.\
tar.gz trying again in 100ms
```

I really appreciate if anyone can help me figure out the problem. Thanks.

**Comment by kirilg** [comment]
This seems like a TensorFlow configuration issue. My guess it's it's a transient network error; do you still consistently get the same error when running `./configure`?

**Comment by jianpingliu** [comment]
Yes. I tried it multiple times during different days. I also tried it on a Centos machine.

**Comment by ColeMurray** [comment]
I am also experiencing this issue.

> INFO: Reading 'startup' options from /root/.bazelrc: --batch
____Loading package: tensorflow/examples/android
____Loading package: tensorflow/contrib/android
____Loading package: tensorflow/stream_executor
____Failed to connect to https://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz trying again in 100ms
____Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: 2,453,804 bytes
INFO: Reading 'startup' options from /root/.bazelrc: --batch
ERROR: /serving/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@three_js_orbitcontrols_js//file': Error downloading [https://raw.githubusercontent.com/mrdoob/three.js/r77/examples/js/controls/OrbitControls.js] to /root/.cache/bazel/_bazel_root/5071e8dca1385fb776f72b33971bf157/external/three_js_orbitcontrols_js/OrbitControls.js: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: /serving/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@weblas_weblas_js//file': Error downloading [https://raw.githubusercontent.com/waylonflinn/weblas/v0.9.0/dist/weblas.js] to /root/.cache/bazel/_bazel_root/5071e8dca1385fb776f72b33971bf157/external/weblas_weblas_js/weblas.js: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and referenced by '//tensorflow/tensorboard/bower:bower'.

**Comment by kirilg** [comment]
@jianpingliu I'm not sure why, but it seems that you're having a connection problem and are unable to download the necessary dependencies. You can try the solution below, but I doubt it'll work for this case.

@ColeMurray I think your issue a bit different. You're running into `java.security.InvalidAlgorithmParameterException` errors, see https://github.com/tensorflow/tensorflow/issues/6750. The solution is there, but I'll just copy it here:
`sudo apt-get install ca-certificates-java`
`sudo update-ca-certificates -f`

**Comment by ColeMurray** [comment]
@kirilg That was the fix, thank you. 👍

**Comment by jianpingliu** [comment]
@kirilg You were probably right. The problem disappeared when I tried it again today.
