### ISSUE TITLE
Does Kraken have 24-7 support?{USA}

### ISSUE THREAD

**Issue by luna2343** [tensorflow/serving#2870]
Does Kraken have 24-7 support?{USA}

Contact Kraken support by calling ☎️⭐1-(831)-257-5999 (Suggested) or by clicking the "CHAT NOW" button beneath our website. Contact our 24/7 Support hotline for the US at ☎️⭐1-(831)-257-5999 to get help right now.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
