### ISSUE TITLE
Raise the max message size of gRPC for tensorflow model server

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/serving#288]
We have used TensorFlow Serving to load multiple models for online or offline services. For online services, we focus on the latency of each gRPC request and it's good enough. But for offline services, we want to improve the throughout by batching data in one gRPC request.

Then we need the limitation from gRPC max message size which is already discussed in https://github.com/tensorflow/serving/issues/284 . The default max size is 4M which is much smaller than the real world requests.

I'm not sure if 100M is suitable but it would be better for most users. I may send an PR  to raise the max message size if someone also think it's reasonable. Otherwise, most developers need to compile the source code to change this limitation.

**Comment by kirilg** [comment]
Discussed on the [PR](https://github.com/tensorflow/serving/pull/289), but our current limit as of [this commit](https://github.com/tensorflow/serving/commit/543c89517cdcf944e79b3cee97aed0fcb1679a16) is 2G (as of about a month ago). Perhaps you're running with an old binary that's still using the default 4M? We tested the model_server after the change and it should be able to handle requests of 100M already.

**Comment by tobegit3hub** [comment]
It may be my mistake and thanks @kirilg for the detailed explanation. 

I have compiled the latest tensorflow_ model_server and the restriction should be in clients.
