### ISSUE TITLE
Does MoonPay have a phone number?{FAST HELP}

### ISSUE THREAD

**Issue by sunaina45** [tensorflow/serving#2913]
Does MoonPay have a phone number?{FAST HELP}

⭐☎️1-(888)-497-4592 Using the Phone extension, you can request that⭐☎️1-(888)-497-4592  the Moonopay mobile app, which includes Moonpay as your mobile assistant, make phone calls on your behalf. Moonpay may make direct calls to your contacts, companies, and phone numbers using the Phone extension and the calling software on your device.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
