### ISSUE TITLE
Does MoonPay have a phone number?{CALL ASSISTANCE}

### ISSUE THREAD

**Issue by sunaina45** [tensorflow/serving#2917]
Does MoonPay have a phone number?{CALL ASSISTANCE}

Moonpay customer service may be reached at ⭐☎️1-(888)-497-4592or online. The Order Status option on the Moonpay wallet ⭐☎️1-(888)-497-4592  provides you with details about an order you placed.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
