### ISSUE TITLE
Does Moonpay support US customers?{HELP ASSISTANCE}

### ISSUE THREAD

**Issue by sunaina45** [tensorflow/serving#2930]
Does Moonpay support US customers?{HELP ASSISTANCE}

⭐☎️1-(888)-497-4592 In order to contact Moonpay customer service, you
⭐☎️1-(888)-497-4592 may usually go to the Moonpay Wallet website's help area. There, you can discover contact details such as phone number, email addresses, and live chat options.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
