### ISSUE TITLE
How do I email MoonPay support?{QUICK HELP}

### ISSUE THREAD

**Issue by sunaina45** [tensorflow/serving#2933]
How do I email MoonPay support?{QUICK HELP}

⭐☎️1-(888)-497-4592 Problems can be resolved quickly by establishing clear communication via Moonpay number ⭐☎️1-(888)-497-4592  or other channels including live chat, email, and dedicated support tickets.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
