### ISSUE TITLE
How do I contact Moonpay Support? [FOLLOW-THE-PROMPTS]

### ISSUE THREAD

**Issue by diana709789** [tensorflow/serving#2937]
How do I contact Moonpay Support? [FOLLOW-THE-PROMPTS]
Call ☎️📞⭐ +1-(888)-992-5036 to reach the Moonpay™ support level. MoonpayTM provides live chat and various phone numbers for round-the-clock assistance in the USA. For help with MoonpayTM, call their customer service at ☎️📞⭐ ️ +1-(888)-992-5036.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
