### ISSUE TITLE
How do I speak to someone at Moonpay?{DIRECT SUPPORT}

### ISSUE THREAD

**Issue by sunaina45** [tensorflow/serving#2947]
How do I speak to someone at Moonpay?{DIRECT SUPPORT}

⭐☎️1-(888)-497-4592 Contact Moonpay support via online web chat, email, or phone at ⭐☎️1-(888)-497-4592  Support hours at normally pertain to Monday through Saturday [9AM to 7 PM], when a Moonpay customer service team is on hand to help clients.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
