### ISSUE TITLE
What are the hours for Moonpay?{SUPPORT CALL}

### ISSUE THREAD

**Issue by sunaina45** [tensorflow/serving#2952]
⭐☎️1-(888)-497-4592 Depending on the severity of the issue, Moonpay assistance at ⭐☎️1-(888)-497-4592 can be accessed Monday through Friday from 9 a.m. to 8 p.m.; in certain situations, this may include extended hours or even 24/7 service.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
