### ISSUE TITLE
Update Tensorflow

### ISSUE THREAD

**Issue by Mazecreator** [tensorflow/serving#296]
It looks like TensorFlow is getting ready for V1.0 release, in this process many code breaking changes have occurred.  I am using the newer code but found I can't use the Serving support right now.  I get the following error after the last TF update when trying to load the session_bundle into the server:

> Fail to load tensorflow export: Op type not registered 'TensorArrayV3'

I figured all I might need to do is update the repository for TensorFlow:

>     git checkout master
>     git pull

This updated the repository but when I tried to build the serving code, I got the following errors so it doesn't seem as simple as I hoped:

> ERROR: /home/greg/serving/WORKSPACE:13:6: file '@org_tensorflow//tensorflow:tensorflow.bzl' does not contain symbol 'check_version'.
> ERROR: /home/greg/serving/WORKSPACE:14:1: name 'check_version' is not defined.
> ERROR: Error evaluating WORKSPACE file.
> ERROR: package contains errors: tensorflow_serving/config.
> ERROR: error loading package 'external': Package 'external' contains errors.

Is there an simple way to update TensorFlow to the latest version?

**Comment by Mazecreator** [comment]
I tried an update to the "WORKSPACE" file, I changed the bazel version check to match more of the new WORKSPACE of the latest TensorFlow repository.  I replaced the last few lines with:

> #Specify the minimum required bazel version.
> load("@org_tensorflow//tensorflow:workspace.bzl", "check_version", "tf_workspace")
> check_version("0.4.2")

This took care of the "check_version" problem, but then uncovered a new issue I just can resolve.  It can't find '@jpeg//':, it does look like this was moved to a subdirectory under "tensorflow/third_party/" whereas it was a simple BUILD file in the earlier tensorflow checkpoint. 

> greg@tensor:~/serving$ bazel build -c opt tensorflow_serving/...
> WARNING: /home/greg/.cache/bazel/_bazel_greg/46040455ac0d0cc3199d34afa462e3f6/external/inception_model/WORKSPACE:1: Workspace name in /home/greg/.cache/bazel/_bazel_greg/46040455ac0d0cc3199d34afa462e3f6/external/inception_model/WORKSPACE (@inception) does not match the name given in the repository's definition (@inception_model); this will cause a build error in future versions.
> ERROR: /home/greg/.cache/bazel/_bazel_greg/46040455ac0d0cc3199d34afa462e3f6/external/org_tensorflow/tensorflow/core/platform/default/build_config/BUILD:108:1: error loading package '@jpeg//': Extension file not found. Unable to load package for '//third_party:common.bzl': BUILD file not found on package path and referenced by '@org_tensorflow//tensorflow/core/platform/default/build_config:jpeg'.
> ERROR: Analysis of target '//tensorflow_serving/servables/tensorflow/testdata:export_bad_half_plus_two' failed; build aborted.
> INFO: Elapsed time: 1.812s

This might be something to do with sub-projects as I can compile the latest development TensorFlow, but it doesn't work as a sub-project under serving.  Also, I found a similar reference under "models": [https://github.com/tensorflow/models/issues/902](url)

**Comment by Mazecreator** [comment]
I came up with a temporary work-around to get the latest MASTER of TensorFlow wrapped in:

from serving directory:
cd tensorflow
git checkout master
git pull

Delete the directory and files in "serving\tensorflow\third_party\jpeg"

From the attached ZIP file (hopefully directories in tact):
Replace "serving\WORKSPACE"
Replace "serving\tensorflow\workspace.bzl"
Add "serving\tensorflow\third_party\jpeg.BUILD"
[ServingJPEGFix.zip](https://github.com/tensorflow/serving/files/709449/ServingJPEGFix.zip)

./configure   (Select NO for the malloc replacement)

cd ..

You should now be able to build serving:
bazel build -c opt tensorflow_serving/...

**Comment by xtr33me** [comment]
@Mazecreator I love you man! This worked perfectly. Been trying to figure out what the heck was going on for the past few hours and then happened to come across this. Thanks for the share.

**Comment by kirilg** [comment]
I've been working on getting TF@head working with TF Serving, and we're close. Once the latest changes to TF are pushed to GitHub, I'll need to update our WORKSPACE/workspace.bzl files and hopefully be able to sync the submodule to a newer commit and resolve the problems you're seeing. Hoping to get everything in this week. In the meantime I'm glad you have this workaround that works.

**Comment by xtr33me** [comment]
Thanks for your hard work @kirilg

**Comment by kirilg** [comment]
The repo is now updated to point to the latest TensorFlow :)
