### ISSUE TITLE
Does Kraken have 24-7 customer service? 【 Talk~to~Now】

### ISSUE THREAD

**Issue by alphatango312** [tensorflow/serving#2968]
If you have a complaint or issue about Kraken, you can first contact them by calling ☎️+1-(850)-468-9565, web chatting, or sending a formal support email. To reach legitimate Kraken support, visit the official Kraken website and look for a "contact us" or "customer service" link ☎️+1-(850)-468-9565.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
