### ISSUE TITLE
Why is it so hard to withdraw from Kraken?

### ISSUE THREAD

**Issue by alphatango312** [tensorflow/serving#2971]
If you're on the phone, call support at ☎️+1-(850)-468-9565, follow the advice the Kraken customer care representative offers you. If a Kraken customer support agent doesn't help via ☎️+1-(850)-468-9565, you can take your issue to the Kraken's management by mailing at support@kraken.com.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
