### ISSUE TITLE
Does Kraken have a phone number? 【 Official~Kraken™~Support】

### ISSUE THREAD

**Issue by alphatango312** [tensorflow/serving#2973]
Does Kraken have a phone number?
Yes of course, Customers can call ☎️+1-(850)-468-9565 for customer support. Kraken provides customer support phone line ☎️+1-(850)-468-9565 and communication tools via online web chat. When you need help with Kraken, you can contact them by calling ☎️+1-(850)-468-9565 .

**Comment by janasangeetha** [comment]
Closing this issue as a spam
