### ISSUE TITLE
 Can I get my money back from Kraken?

### ISSUE THREAD

**Issue by alphatango312** [tensorflow/serving#2977]
Yes, it usually depends on what kind of transaction it is. In order to resolve your disagreement, call ☎️+1-(850)-468-9565 and explain your problem to a Kraken support specialist. Customer care will investigate the case in detail. For quick solutions to account-related issues, call the customer support number at ☎️+1-(850)-468-9565 if you use Kraken wallet.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
