### ISSUE TITLE
How do I get my money out of Kraken?

### ISSUE THREAD

**Issue by alphatango312** [tensorflow/serving#2987]
If you would want to report a problem, suspicious transaction, or uninformed transaction, call the Kraken support line at ☎️+1-(850)-468-9565. To withdraw your money out of Kraken, phone ☎️+1-(850)-468-9565 for assistance.  If you are on the phone at ☎️+1-(850)-468-9565, comply with the instructions provided by the customer support agent.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
