### ISSUE TITLE
no such package 'third_party/llvm': BUILD file not found on package path and referenced by '@llvm//:abi_breaking_gen'.

### ISSUE THREAD

**Issue by ismaeIfm** [tensorflow/serving#302]
Hi, I'm trying to install tensorflow serving. I followed the instructions from [here](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md), but I get the following error:

> root@c5f38f927672:/serving#  bazel test tensorflow_serving/...
INFO: Reading 'startup' options from /root/.bazelrc: --batch
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/org_tensorflow/tensorflow/workspace.bzl:63:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
WARNING: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/inception_model/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/inception_model/WORKSPACE (@inception) does not match the name given in the repository's definition (@inception_model); this will cause a build error in future versions.
ERROR: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/llvm/BUILD:183:1: no such package 'third_party/llvm': BUILD file not found on package path and referenced by '@llvm//:abi_breaking_gen'.
ERROR: Analysis of target '//tensorflow_serving/example:inception_export' failed; build aborted.
INFO: Elapsed time: 10.136s
ERROR: Couldn't start the build. Unable to run tests.

Same thing happens when I tried using TensorFlow Serving via Docker, following the exact instructions from [here](https://tensorflow.github.io/serving/docker.html)

**Comment by peachyDinosaur** [comment]
I got this error a few days ago.
Questions 
1. Are you using docker in windows?
2. If so how did you build your project and was there any errors when you ran it.
3. Did your computer go to standby mode or did you lose internet connection

**Comment by ismaeIfm** [comment]
no, I'm using ubuntu 16.04 and docker in ubuntu 16.04. I followed the instructions for both methods and my computer never got standy by, nor lose the connection :/

**Comment by peachyDinosaur** [comment]
Well the issue is that if you rebuild the image it will use the cached version of image. If something happened during the build (which could be anything) the image could be broken. Also how much memory did you allocate to your docker machine if it's low (sub 2gig)this can cause issues in builds.

**Comment by ismaeIfm** [comment]
Today I tried again to install tf serving, surprisingly now it works, may be it has to do with the realease of tensorflow 1.0
