### ISSUE TITLE
How do I contact Kraken support? [Assist Live]

### ISSUE THREAD

**Issue by alphatango312** [tensorflow/serving#3026]
How can I get in touch with Kraken support? [Assist Live]
Contacting Kraken support at ☎️+1-(850)-468-9565 'In case of need' is undoubtedly a very formal procedure. If you need assistance, click the button, dial ☎️+1-(850)-468-9565 for immediate Kraken support over the phone, and participate in the session.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
