### ISSUE TITLE
Does Kraken help get back to you? [Help Live]

### ISSUE THREAD

**Issue by alphatango312** [tensorflow/serving#3027]
Yes, it is accurate. Kraken support answers the phone quickly ☎️+1-(850)-468-9565, understands the customer's problems, and apologizes if the business is incorrect. Customer care at Kraken ☎️+1-(850)-468-9565 gets right to the point and provides detailed information on how to fix the problem.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
