### ISSUE TITLE
How to contact Kraken support? [Help Live]

### ISSUE THREAD

**Issue by alphatango312** [tensorflow/serving#3028]
How to contact Kraken support? [Help Live]
Kraken support may be reached at ☎️+1-(850)-468-9565 if you need great advice on building a successful cryptocurrency portfolio. Responses from Kraken customer support at ☎️+1-(850)-468-9565 are consistently professional and provide flawless solutions to any concerns or issues pertaining to your account.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
