### ISSUE TITLE
Tensorflow Serving Basics Instructions Unclear 

### ISSUE THREAD

**Issue by peachyDinosaur** [tensorflow/serving#303]
At the end of the basic example for the mnist data set it tell you to run

Load Exported Model With Standard TensorFlow Model Server

$>bazel build //tensorflow_serving/model_servers:tensorflow_model_server
$>bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=mnist --model_base_path=/tmp/mnist_model/
Test The Server

We can use the provided mnist_client utility to test the server. The client downloads MNIST test data, sends them as requests to the server, and calculates the inference error rate.

To run it:

$>bazel build //tensorflow_serving/example:mnist_client
$>bazel-bin/tensorflow_serving/example/mnist_client --num_tests=1000 --server=localhost:9000
...
Inference error rate: 10.5%

For docker users this is unclear because are we to assume that you need to create a second container for to run the client from. This should be added into the instructions because there are many questions online with very poor and incorrect solutions.

**Comment by gautamvasudevan** [comment]
Fixed by 8a6dc8e
