### ISSUE TITLE
How do I contact Uphold?[[FAQ: Support]

### ISSUE THREAD

**Issue by zofia555** [tensorflow/serving#3050]
How do I contact Uphold?[[FAQ: Support]

⭐☎️1-858-858-6950  Only in extreme circumstances, after arranging a⭐☎️1-858-858-6950   time and date via email, would the Uphold Customer Support staff give their clients a call.You can receive a call from the Uphold Credit Card support team for credit card-specific activities or service requirements.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
