### ISSUE TITLE
Serving with QueueRunner

### ISSUE THREAD

**Issue by elbaro** [tensorflow/serving#306]
Can I use Tensorflow Serving on a model with QueueRunner?
In a Python code, one needs to manage threads like this:

```
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess, coord)

sess.run([op1, op2, ..])  # <- model part

coord.request_stop()
coord.join(threads)
```

But when exporting the model to Serving, where should I start/manage threads?
(Without start_queue_runners, the execution from Serving hangs)

**Comment by chrisolston** [comment]
Generally you don't want to have any asynchronous behavior, such as queues, in your *serving* graph. If you have queues in your training graph (often a good idea e.g. to buffer I/O for reading training examples) you generally want to strip them out for the graph you export for serving.

**Comment by cjviper** [comment]
Could you please give an example of how to do this @chrisolston ?

**Comment by chrisolston** [comment]
The pattern I've seen is that your python code that generates the graph has a branch (training vs. serving), and in the serving branch it doesn't insert the queue. With the new SavedModel export format, you can export multiple graphs with different tags, e.g. one tagged as the training graph and one as the serving graph.
