### ISSUE TITLE
Is there a phone number for Uphold? [Emergency Hotline]

### ISSUE THREAD

**Issue by kraken-wallet** [tensorflow/serving#3065]
Is there a phone number for Uphold? [Emergency Hotline]
Yes, you can get assistance with product, payment, return, and technical support concerns by calling the Uphold Support hotline ☎️+1(850)-565-2086. Get in touch with Uphold Customer Service at ☎️+1(850)-565-2086. Our knowledgeable staff will listen to your worries, show empathy, and resolve any Uphold wallet-related issues.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
