### ISSUE TITLE
How do I contact Uphold support?

### ISSUE THREAD

**Issue by kraken-wallet** [tensorflow/serving#3069]
How do I contact Uphold support?
To contact great Uphold customer support, you can try ☎️️📞⭐ +1-(850)-565-2086  Phone: Customers still love to speak to someone - especially when it comes to urgent issues. For Uphold support at ☎️ +1-(850)-565-2086  , providing good customer service is key to building long-term customer relationships.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
