### ISSUE TITLE
Inference error "Default serving signature not found"

### ISSUE THREAD

**Issue by sskgit** [tensorflow/serving#307]
Followed the installation instructions for Tensorflow serving from https://tensorflow.github.io/serving/serving_basic

Setup:
Ubuntu 16.04
No GPU
Python 2.7
gRPC
bazel 0.43
 and all other dependencies.

Most of the installation went well (with few glitches which I was able to resolve) and loaded the exported model to Tensorflow server using:
$>bazel build //tensorflow_serving/model_servers:tensorflow_model_server
$>bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=mnist --model_base_path=/tmp/mnist_model/

While testing the server using mnist_client with the command:
$>bazel-bin/tensorflow_serving/example/mnist_client --num_tests=1000 --server=localhost:9000

received error:
**AbortionError(code=StatusCode.FAILED_PRECONDITION, details="Default serving signature key not found.")**

I see that mnist_export.py has reference to the Signature and predict_imply.py has the exact message in the code. Tried to go thru Tensorflow serving issues and also search, did not find anything helpful to resolve this problem.

What may be the cause of this error and how do I fix it?

Thanks

**Comment by lilao** [comment]
How did you generate the export? We have changed mnist_client.py to work
with mnist export in SavedModel format (instead of the deprecated
SessionBundle format). Can you follow the instructions at
https://tensorflow.github.io/serving/serving_basic to generate the
SavedModel export to see if it works?

**Comment by sskgit** [comment]
@lilao Thanks for your response.
I followed the instructions at https://tensorflow.github.io/serving/serving_basic
and ran these 2 commands to generate the export before loading the model with Tensorflow Serving server

$>bazel build //tensorflow_serving/example:mnist_saved_model
$>bazel-bin/tensorflow_serving/example/mnist_saved_model /tmp/mnist_model

Also, tried with Docker image and see the same error:

grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.FAILED_PRECONDITION, details="Default serving signature key not found.")

**Comment by sskgit** [comment]
@lilao Another observation:
On Ubuntu, mnist_model under /tmp has sub-directory **00000001,** whereas in the Docker container in mnist_model under /tmp subdirectory is **1**. Earlier, I do see the sub-directory as 00000001 in the documentation of serving_basic. Not sure if the document has been updated today to subdirectory 1.

I will delete /tmp/mnist_model from Ubuntu and export the model again. But still surprised that the Docker image has the right sub-directory **1** but it also gave the same error while running inference.

**Comment by sskgit** [comment]
Deleting and running the steps export model onwards to inference worked.. 
@lilao Thanks for the pointer.

**Comment by lilao** [comment]
Good to know it worked! I suspect the sub-directory *00000001 *was from a
previous run with mnist_export.py.
