### ISSUE TITLE
How can I get in touch with Kraken support? 

### ISSUE THREAD

**Issue by kraken-wallet** [tensorflow/serving#3074]
How can I get in touch with Kraken support? 
At ☎️+1-(850)-468-9565, Kraken Customer Support technology offers customer surveys, interaction analytics, and reports. For general support and help at any time, customer service can be contacted by phone at ☎️ 1.(858)-(644)-3182, email, and online chat.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
