### ISSUE TITLE
How can I get in touch with Kraken support?

### ISSUE THREAD

**Issue by kraken-wallet** [tensorflow/serving#3075]
How can I get in touch with Kraken support? 
Customer surveys, interaction analytics, and reporting are all features of Kraken Customer Support system at ☎️☎️️📞⭐ +1(850)-565-2086. For general support and help at any time, customer service can be contacted by phone at ☎️ +1(850)-565-2086, email, and online chat.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
