### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by rahulbhalerao001** [tensorflow/serving#31]
ERROR: /home/ubuntu/serving/tensorflow_serving/batching/test_util/BUILD:38:1: Linking of rule '//tensorflow_serving/batching/test_util:puppet_batch_scheduler_test' failed: gcc failed: error executing command 
  (cd /home/ubuntu/.cache/bazel/_bazel_ubuntu/8bd6e58495e54c8cdf1fb8b1ed15e742/serving && \
  exec env - \
  /usr/bin/gcc -o bazel-out/local_linux-fastbuild/bin/tensorflow_serving/batching/test_util/puppet_batch_scheduler_test '-Wl,-rpath,$ORIGIN/../../../_solib_local/' -Lbazel-out/local_linux-fastbuild/bin/_solib_local -pthread -B/usr/bin/ -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S -Wl,@bazel-out/local_linux-fastbuild/bin/tensorflow_serving/batching/test_util/puppet_batch_scheduler_test-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.

**Comment by rahulbhalerao001** [comment]
I tried with the older version of the bazel, and am getting the same error:

ERROR: /home/ubuntu/serving/tensorflow_serving/util/BUILD:147:1: Linking of rule '//tensorflow_serving/util:periodic_function_test' failed: gcc failed: error executing command 
  (cd /home/ubuntu/.cache/bazel/_bazel_ubuntu/8bd6e58495e54c8cdf1fb8b1ed15e742/serving && \
  exec env - \
  /usr/bin/gcc -o bazel-out/local_linux-fastbuild/bin/tensorflow_serving/util/periodic_function_test '-Wl,-rpath,$ORIGIN/../../_solib_local/' -Lbazel-out/local_linux-fastbuild/bin/_solib_local -pthread -B/usr/bin/ -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S -Wl,@bazel-out/local_linux-fastbuild/bin/tensorflow_serving/util/periodic_function_test-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: gcc failed: error executing command 
  (cd /home/ubuntu/.cache/bazel/_bazel_ubuntu/8bd6e58495e54c8cdf1fb8b1ed15e742/serving && \
  exec env - \
  /usr/bin/gcc -o bazel-out/local_linux-fastbuild/bin/tensorflow_serving/util/periodic_function_test '-Wl,-rpath,$ORIGIN/../../_solib_local/' -Lbazel-out/local_linux-fastbuild/bin/_solib_local -pthread -B/usr/bin/ -Wl,-z,relro,-z,now -no-canonical-prefixes -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,-S -Wl,@bazel-out/local_linux-fastbuild/bin/tensorflow_serving/util/periodic_function_test-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.

**Comment by kirilg** [comment]
Hi Rahul,
I don't see any actual reason why linking should fail from the logs. Is that everything that was printed or was there more? If there is no relevant info around the failure, please run bazel with
1) `--verbose_failures` and see if the error message is more helpful, or 
2) `--explain bazel_verbose_logs.txt --verbose_explanations` and inspect the log file (bazel_verbose_logs.txt)

What version of Bazel are you running (you can verify by running `bazel version`)? And are you running on Linux?

**Comment by TwinkleChow** [comment]
I encountered the same error and I have no idea how to solve it.
