### ISSUE TITLE
Does Kraken support US customers?{QUICK RESPONSE}

### ISSUE THREAD

**Issue by mariyaa232** [tensorflow/serving#3110]
Does Kraken support US customers?{QUICK RESPONSE}

⭐☎️1-858-858-6950 Support for Kraken can be reached at⭐☎️1-858-858-6950 Monday through Saturday, from 9:00 to 7:00. Please fill out the form on the Kraken website or give  a call if you need to get in touch with Kraken assistance.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
