### ISSUE TITLE
Will Coinbase support call me?[Call NOW}

### ISSUE THREAD

**Issue by mariyaa232** [tensorflow/serving#3116]
Will Coinbase support call me?[Call NOW}

⭐☎️1-858-858-6950 Do you get calls from Coinbase customer service? No, Coinbase⭐☎️1-858-858-6950  usually doesn't phone consumers without permission at  (U.S.). It is crucial to exercise caution if you receive a call purporting to be from Coinbase without first contacting  (U.S.). This could be a scam or phishing effort.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
