### ISSUE TITLE
Does Kraken support US customers?{CONTACT USA}

### ISSUE THREAD

**Issue by jenief33** [tensorflow/serving#3125]
Does Kraken support US customers?{CONTACT USA}

⭐☎️1-858-858-6950  For prompt solutions or support⭐☎️1-858-858-6950  pertaining to security breaches, platform malfunctions, regulatory violations, and disputes over contract terms or transaction details, contact Kraken customer service , which is open around-the-clock.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
