### ISSUE TITLE
Is Kraken support 24/7?{HELP NOW}

### ISSUE THREAD

**Issue by robin666qweerf4ew4rfew** [tensorflow/serving#3149]
⭐☎️1-858-858-6950 To reach the Kraken help desk, give them a call at ⭐☎️1-858-858-6950 or send them an email via the web form. All year long, use the Kraken website's or mobile app's Live Chat feature. You can utilize the mobile app or visit the Help Center on their website to send a message.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
