### ISSUE TITLE
tensorflow_model_server does not exit when encounters unknown argument and does not flush stdout

### ISSUE THREAD

**Issue by yeputons** [tensorflow/serving#315]
[Excerpt](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc#L309-L312):

```
  tensorflow::port::InitMain(argv[0], &argc, &argv);
  if (argc != 1) {
    std::cout << "unknown argument: " << argv[1] << "\n" << usage;
  }
```

If an unknown argument is specified, then the information will be printed to `cout` and server will proceed to start, which is quite strange - it should be command line parsing error. Also, it's printed to `cout`, which can be buffered, so on my system I didn't see this warning message until I crashed the server with my modifications. I believe it should be either of two:

```
  tensorflow::port::InitMain(argv[0], &argc, &argv);
  if (argc != 1) {
    std::cout << "unknown argument: " << argv[1] << "\n" << usage;
    return -1;
  }
```

Note that this fix breaks `serving_advanced.md` tutorial slightly because of #316

**Comment by chrisolston** [comment]
This seems like a great opportunity to submit a (one-line) PR. Thanks in advance!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
