### ISSUE TITLE
tensorflow_model_server does not accept `--logtostderr` parameter, which is specified in tutorials

### ISSUE THREAD

**Issue by yeputons** [tensorflow/serving#316]
Both source code and tutorial specify that `tensorflow_model_server` accepts `--logtostderr` parameter:
1. [In source code](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc#L44) (note that there here it's called `alsologtostderr`, which is strange):
```
// To log on stderr (default disabled): --alsologtostderr
```
2. [In `serving_advanced.md`](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/serving_advanced.md):
```
$>bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --enable_batching --port=9000 --model_name=mnist --model_base_path=/tmp/monitored --logtostderr
```

However, this parameter is not specified in [`flag_list`](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc#L269-L302) in the source code. Nor it's parsed afterwards, nor it's specified in the `--help`'s output. Error message about this is not visible when running command line from the tutorial because of #315 .

**Comment by chrisolston** [comment]
Does the flag work? (i.e. if you supply it, do you get some logs printed to stderr?)

It's a low-level flag that we inherit from some low-level library, and is not parsed explicitly in TF-Serving's main.cc.

If it works, let's close the issue :). If it doesn't work, let's dig further. Thanks.

**Comment by yeputons** [comment]
@chrisolston It looks like all logs go to stderr regardless of that option (except messages directly printed to `cout` in `main.c`, like "usage"). I have also tried `--logtostdout` just in case; with no effect.

Btw, I saw a bunch of `--alsologtostderr` mentions in TensorFlow source code, so probably the comment in `main.c` is not a simple mistake.

**Comment by kirilg** [comment]
I looked into it a bit, and it appears TensorFlow's logging library doesn't define that flag, but it is defined internally. The flag was only recently added to the .md files, and is not strictly necessary, so I think we can remove all references to logtostderr. I'll submit a fix.

**Comment by kirilg** [comment]
The change is now in GitHub. All references to logtostderr have been removed.

Sorry for the confusion!
