### ISSUE TITLE
How do I contact MoonPay support?{FAST SERVICE}}

### ISSUE THREAD

**Issue by marina234gtegter** [tensorflow/serving#3178]
How do I contact MoonPay support?{FAST SERVICE}}

⭐☎️1-858-858-6950 Indeed, Moonpay provides flexible customer service around-the-clock at ⭐☎️1-858-858-6950  Dial to receive assistance, resources & advice, account tools, troubleshooting suggestions, account administration, capital monetization, and more.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
