### ISSUE TITLE
Question about latency/throughput

### ISSUE THREAD

**Issue by dougsouza** [tensorflow/serving#319]
I have a face recognition system composed of two models, one for face detection and another to perform face recognition. I would like to perform detection + recognition in real time (~30fps) so I'm considering deploying them on tensorflow serving, but I have some questions:

1. I have read that tf serving is designed for throughput rather than latency. So in my case, where I would submit small batches (usually of size 1), tf serving would perform better (faster) than run `sess.run(...)` from a python script?
2. Also, would GPU help in this case? It is a very small batch, so I don't know if GPU processing would help. Any ideas on that?

Thanks!

**Comment by chrisolston** [comment]
There is a tradeoff between latency and throughput that is governed by the batching parameters documented in batching/README.md. One deficiency is that we don't currently provide a way to specify the batching parameters in main.cc (so you're stuck with the defaults). Contributions welcome :)

**Comment by dougsouza** [comment]
@chrisolston,

Thanks for the reply, but you didn't really answer my questions. Do you think tf serving is suitable for a use case like the one I mentioned?

**Comment by chrisolston** [comment]
Sorry, you're right. I only addressed one part of your question. If you use tf-serving you'll be running the c++ evaluation engine for tensorflow (vs. python). I imagine the c++ one is likely faster but I don't know for sure. And no with small batch sizes you are unlikely to get benefit from GPUs.

**Comment by kirilg** [comment]
Closing issue, please reopen if there are any more questions.
