### ISSUE TITLE
How do I connect to MoonPay?{CALL SUPPORT}

### ISSUE THREAD

**Issue by marked33** [tensorflow/serving#3216]
⭐☎️1-858-858-6950  You can use the Moonpay mobile app or visit the⭐☎️1-858-858-6950   Help Centre on their website to send a message.There are several ways to get in touch with Moonpay support, including live chat and request submission. You can also call Moonpay customer care  if you require quick assistance. An overview.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
