### ISSUE TITLE
Is MoonPay legal in the US?{SUPPORT CALL]

### ISSUE THREAD

**Issue by marked33** [tensorflow/serving#3218]
Is MoonPay legal in the US?{SUPPORT CALL}}

⭐☎️1-858-858-6950   the Moonpay  support services offered by your⭐☎️1-858-858-6950 Google Cloud company, including Premium Support or Enhanced Support. The availability of case help around-the-clock (24/7) is determined by your service. If not, customer service is accessible during business days or operating hours

**Comment by janasangeetha** [comment]
Closing this issue as a spam
