### ISSUE TITLE
How do I contact MoonPay support?{GET HELP}

### ISSUE THREAD

**Issue by marked33** [tensorflow/serving#3221]
How do I contact MoonPay support?{GET HELP}

⭐☎️1-858-858-6950  Moonpay help can be reached via chat, phone 🆑 ⭐☎️1-858-858-6950 or email. In the US, you can reach Moonpay support by calling Operating Hours. 9am to 8 pm, Monday through Saturday.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
