### ISSUE TITLE
How do I email Kraken support?{{DIRECT SUPPORT}}

### ISSUE THREAD

**Issue by saida234** [tensorflow/serving#3233]
⭐☎️1-858-858-6950  Yes, Kraken's online help system offers round-the-⭐☎️1-858-858-6950  clock customer service. Through their Kraken Credit Card, you can make a request at any time. You can reach their 24/7 phone service at  by going to the Card Settings area of your account.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
