### ISSUE TITLE
Is Coinbase available in the USA?{HELP SUPPORT}

### ISSUE THREAD

**Issue by saida234** [tensorflow/serving#3243]
⭐☎️ 1-858-858-6950Yes, Coinbase offers live customer service by phone at ⭐☎️1-858-858-6950 You can buy or sell your cryptocurrency assets, obtain pricing information, ask a question about your issue, or get your wallet details by calling Coinbase.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
