### ISSUE TITLE
Can you delete your old Coinbase account?{{Easy Steps to Follow}}

### ISSUE THREAD

**Issue by Jacks3343png** [tensorflow/serving#3255]
To delete your old Coinbase account, simply reach out to Coinbase’s technical support at +1-((855))-998-0300 - Coinbase Helpline Number. Coinbase requires you to go through a security verification before proceeding with account deletion. If you’ve forgotten your login credentials or need guidance, their Customer Support Number is available 24/7 to assist. Always make sure to withdraw any funds before closing your account, as they cannot be recovered once the account is deleted. If you encounter any issues, the company's Official Helpline Number is ready to help you with each step of the way.
![Blue And White Modern Call For Volunteers Poster ](https://github.com/user-attachments/assets/6b51f87e-b3a2-4a02-be11-8fa17642b0d7)

**Comment by janasangeetha** [comment]
Closing this issue as a spam
