### ISSUE TITLE
Question about the saved model format

### ISSUE THREAD

**Issue by perdasilva** [tensorflow/serving#329]
Is it/will it be agnostic to the version of tensorflow used to train the underlying model?
i.e. can TFS serve SavedModel models trained in a different version of TF that is used to serve the model in TFS?

Thanks in advance

**Comment by JVillella** [comment]
This isn't a canonical answer but from my own testing I have exported a SavedModel with TF 0.12, and it's running in TFS using TF 1.0 without any problem. This may just be because there were no breaking changes to how the SavedModels are written/read.

**Comment by perdasilva** [comment]
I've found the answer. TF uses semantic versioning. That means that everything should be backwards compatible within major versions but not necessarily between mejor versions. E.g. something trained in 1.0 will work in 1.9, but not necessarily in 2.0.
