### ISSUE TITLE
Using Re-trained Inception Model in Tensorflow Serving Example

### ISSUE THREAD

**Issue by oweingrod** [tensorflow/serving#33]
Hi

Trying to use a retrained inception model (as in the transfer learning tutorial) with Tensorflow serving as described by the example, (https://tensorflow.github.io/serving/serving_basic)[here]. However, I am unclear how to set up the exporter.

The exporter flow as shown in the tutorial looks as such:
`
export_path = sys.argv[-1]
print 'Exporting trained model to', export_path
saver = tf.train.Saver(sharded=True)
model_exporter = exporter.Exporter(saver)
signature = exporter.classification_signature(input_tensor=x, scores_tensor=y)
model_exporter.init(sess.graph.as_graph_def(),
                    default_graph_signature=signature)
model_exporter.export(export_path, tf.constant(FLAGS.export_version), sess)
`

Since there is no "input_tensor" and "scores_tensor" as described by this tutorial within the Inception transfer learning, I am unsure of what tensors to use to get the signature. The bottleneck tensor? The ground_truth tensor? 

I'd love an explanation of how to set up this retrained model with Tensorflow Serving as shown in this example!

Thanks

Oren

**Comment by kirilg** [comment]
I believe you're referring to this example: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/image_retraining/index.md

If so, the retrained inception model uses the same input_tensor, and they remove the final output layer and replaced it with a new layer. I think `input_tensor=jpeg_data_tensor`
The output is what's passed in the final_tensor_name flag. If you didn't modify it yourself, the default value is "final_result"
