### ISSUE TITLE
workspace.bzl contains absolute paths which prevents some targets from building when TFS is included as submodule

### ISSUE THREAD

**Issue by yeputons** [tensorflow/serving#334]
Specifically, `@inception_model` external dependency is added [in `workspace.bzl`](https://github.com/tensorflow/serving/blob/f100a35aff0e9050a93371877d88f478db1569fe/tensorflow_serving/workspace.bzl#L10-L13) (`tf_serving_workspace` macro). Meaning, if I include TensorFlow Serving as a submodule, `//tensorflow_serving/example:inception_saved_model` target won't even start building if inception model is not located at `tf_models/inception` _relative to my repository's root_ (as Bazel's `local_repository` rule is relative to workspace root). Steps to reproduce:

1. Clone [this repository](https://github.com/yeputons/tensorflow-serving-external-build-issue/) (almost same as used in #328 - see detailed description there), switch to the `inception-saved-model` branch and check out all submodules:

~~~shell
git clone git@github.com:yeputons/tensorflow-serving-external-build-issue.git
cd tensorflow-serving-external-build-issue
git checkout inception-saved-model
git submodule update --init --recursive
~~~
2. Try building `inception_saved_model`:

~~~shell
bazel build @tf_serving//tensorflow_serving/example:inception_saved_model
~~~
3. Note that Bazel fails with:

~~~
WARNING: /home/egor/.cache/bazel/_bazel_egor/c1d9c48b2e5a834d2e5c59c0b77b313b/external/org_tensorflow/tensorflow/workspace.bzl:71:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
ERROR: /home/egor/.cache/bazel/_bazel_egor/c1d9c48b2e5a834d2e5c59c0b77b313b/external/tf_serving/tensorflow_serving/example/BUILD:89:1: no such package '@inception_model//inception': local_repository rule //external:inception_model must specify an existing directory and referenced by '@tf_serving//tensorflow_serving/example:inception_saved_model'.
ERROR: Analysis of target '@tf_serving//tensorflow_serving/example:inception_saved_model' failed; build aborted.
INFO: Elapsed time: 2.376s
~~~

Even though I didn't configure TensorFlow before building, it's pretty much clear that this Bazel error is very high-level - it cannot find `inception_model` repository. Fuller check can be done with `./reproduce.sh` - it configures TensorFlow to all defaults, checks that the target builds from inside the submodule and then from the outside workspace.

One can argue that when I create my own workspace, I should carefully gather all dependencies from TensorFlow Serving and other Bazel projects instead of using macros from the repositoreis. On the other hand, I'd expect that macro is provided for a reason: get rid of burden of setting up complex dependencies. If that's the case, then it'd be very nice for the macro to behave appropriately if TensorFlow Serving itself is external dependency. I'm not sure whether Bazel provides such opportunity at all, though.

**Comment by gautamvasudevan** [comment]
Closing due to staleness - I suspect this is no longer an issue as well. If you disagree, feel free to comment. Thanks!
