### ISSUE TITLE
𝕎𝕙𝕪 𝕕𝕚𝕕 𝕞𝕪 𝕤𝕥𝕠𝕔𝕜 𝕠𝕣𝕕𝕖𝕣 𝕗𝕒𝕚𝕝 𝕥𝕠 𝕖𝕩𝕖𝕔𝕦𝕥𝕖?

### ISSUE THREAD

**Issue by Hellboy1200** [tensorflow/serving#3362]
𝕊𝕥𝕠𝕔𝕜 𝕠𝕣𝕕𝕖𝕣 𝕗𝕝𝕠𝕡𝕡𝕖𝕕? ℂ𝕠𝕟𝕥𝕒𝕔𝕥 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟 𝕗𝕠𝕣 𝕚𝕟𝕤𝕚𝕘𝕙𝕥𝕤! 𝕀𝕥 𝕔𝕠𝕦𝕝𝕕 𝕓𝕖 𝕕𝕦𝕖 𝕥𝕠 𝕚𝕟𝕤𝕦𝕗𝕗𝕚𝕔𝕚𝕖𝕟𝕥 𝕗𝕦𝕟𝕕𝕤, 𝕚𝕟𝕔𝕠𝕣𝕣𝕖𝕔𝕥 𝕠𝕣𝕕𝕖𝕣 𝕥𝕪𝕡𝕖, 𝕠𝕣 𝕡𝕣𝕚𝕔𝕖 𝕔𝕙𝕒𝕟𝕘𝕖𝕤 𝕕𝕦𝕣𝕚𝕟𝕘 𝕖𝕩𝕖𝕔𝕦𝕥𝕚𝕠𝕟. ℝ𝕖𝕧𝕚𝕖𝕨 𝕪𝕠𝕦𝕣 𝕠𝕣𝕕𝕖𝕣 𝕤𝕖𝕥𝕥𝕚𝕟𝕘𝕤 𝕒𝕟𝕕 𝕗𝕦𝕟𝕕𝕤 𝕚𝕟 𝕥𝕙𝕖 𝕒𝕡𝕡. 𝕊𝕥𝕚𝕝𝕝 𝕔𝕠𝕟𝕗𝕦𝕤𝕖𝕕? 𝕁𝕦𝕤𝕥 𝕔𝕒𝕝𝕝 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟 𝕗𝕠𝕣 𝕔𝕝𝕒𝕣𝕚𝕥𝕪. ℕ𝕖𝕖𝕕 𝕒 𝕗𝕒𝕤𝕥 𝕗𝕚𝕩? 𝔻𝕚𝕒𝕝 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟 𝕒𝕟𝕕 𝕝𝕖𝕥 𝕥𝕙𝕖 𝕡𝕣𝕠𝕤 𝕙𝕒𝕟𝕕𝕝𝕖 𝕚𝕥. 𝔻𝕠𝕟’𝕥 𝕨𝕒𝕚𝕥—ℝ𝕠𝕓𝕚𝕟𝕙𝕠𝕠𝕕’𝕤 𝕤𝕦𝕡𝕡𝕠𝕣𝕥 𝕒𝕥 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟 𝕚𝕤 𝕒𝕝𝕨𝕒𝕪𝕤 𝕣𝕖𝕒𝕕𝕪 𝕥𝕠 𝕙𝕖𝕝𝕡.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
