### ISSUE TITLE
𝕎𝕙𝕪 𝕚𝕤 𝕞𝕪 𝕤𝕥𝕠𝕔𝕜 𝕠𝕣𝕕𝕖𝕣 𝕡𝕖𝕟𝕕𝕚𝕟𝕘 𝕠𝕟 ℝ𝕠𝕓𝕚𝕟𝕙𝕠𝕠𝕕?

### ISSUE THREAD

**Issue by Hellboy1200** [tensorflow/serving#3363]
𝕎𝕒𝕚𝕥𝕚𝕟𝕘 𝕠𝕟 𝕒 𝕥𝕣𝕒𝕕𝕖? ℂ𝕒𝕝𝕝 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟 𝕥𝕠 𝕔𝕝𝕖𝕒𝕣 𝕥𝕙𝕖 𝕔𝕠𝕟𝕗𝕦𝕤𝕚𝕠𝕟! ℙ𝕖𝕟𝕕𝕚𝕟𝕘 𝕠𝕣𝕕𝕖𝕣𝕤 𝕦𝕤𝕦𝕒𝕝𝕝𝕪 𝕙𝕒𝕡𝕡𝕖𝕟 𝕨𝕙𝕖𝕟 𝕥𝕙𝕖 𝕞𝕒𝕣𝕜𝕖𝕥 𝕚𝕤 𝕔𝕝𝕠𝕤𝕖𝕕 𝕠𝕣 𝕥𝕙𝕖𝕣𝕖’𝕤 𝕒 𝕕𝕖𝕝𝕒𝕪 𝕚𝕟 𝕖𝕩𝕖𝕔𝕦𝕥𝕚𝕠𝕟. ℂ𝕙𝕖𝕔𝕜 𝕚𝕗 𝕪𝕠𝕦’𝕧𝕖 𝕤𝕖𝕥 𝕒 𝕝𝕚𝕞𝕚𝕥 𝕠𝕣𝕕𝕖𝕣, 𝕒𝕤 𝕚𝕥 𝕨𝕠𝕟’𝕥 𝕖𝕩𝕖𝕔𝕦𝕥𝕖 𝕦𝕟𝕥𝕚𝕝 𝕥𝕙𝕖 𝕔𝕠𝕟𝕕𝕚𝕥𝕚𝕠𝕟𝕤 𝕒𝕣𝕖 𝕞𝕖𝕥. 𝕀𝕗 𝕚𝕥’𝕤 𝕥𝕒𝕜𝕚𝕟𝕘 𝕥𝕠𝕠 𝕝𝕠𝕟𝕘, 𝕔𝕒𝕝𝕝 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟 𝕥𝕠 𝕔𝕙𝕖𝕔𝕜 𝕥𝕙𝕖 𝕤𝕥𝕒𝕥𝕦𝕤. ℕ𝕖𝕖𝕕 𝕚𝕥 𝕗𝕚𝕩𝕖𝕕 𝕗𝕒𝕤𝕥? 𝔻𝕚𝕒𝕝 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟, 𝕒𝕟𝕕 𝕥𝕙𝕖 𝕥𝕖𝕒𝕞 𝕨𝕚𝕝𝕝 𝕒𝕤𝕤𝕚𝕤𝕥. 𝕐𝕠𝕦 𝕔𝕒𝕟 𝕒𝕝𝕨𝕒𝕪𝕤 𝕔𝕒𝕝𝕝 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟 𝕗𝕠𝕣 𝕣𝕖𝕒𝕝-𝕥𝕚𝕞𝕖 𝕦𝕡𝕕𝕒𝕥𝕖𝕤.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
