### ISSUE TITLE
ℍ𝕠𝕨 𝕕𝕠 𝕀 𝕝𝕚𝕟𝕜 𝕠𝕣 𝕦𝕡𝕕𝕒𝕥𝕖 𝕞𝕪 𝕓𝕒𝕟𝕜 𝕒𝕔𝕔𝕠𝕦𝕟𝕥 𝕠𝕟 ℝ𝕠𝕓𝕚𝕟𝕙𝕠𝕠𝕕?

### ISSUE THREAD

**Issue by Hellboy1200** [tensorflow/serving#3364]
ℕ𝕖𝕖𝕕 𝕥𝕠 𝕦𝕡𝕕𝕒𝕥𝕖 𝕪𝕠𝕦𝕣 𝕓𝕒𝕟𝕜 𝕚𝕟𝕗𝕠? 𝕊𝕥𝕒𝕣𝕥 𝕓𝕪 𝕔𝕒𝕝𝕝𝕚𝕟𝕘 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟 𝕗𝕠𝕣 𝕢𝕦𝕚𝕔𝕜 𝕘𝕦𝕚𝕕𝕒𝕟𝕔𝕖! 𝕆𝕡𝕖𝕟 𝕥𝕙𝕖 ℝ𝕠𝕓𝕚𝕟𝕙𝕠𝕠𝕕 𝕒𝕡𝕡, 𝕥𝕒𝕡 𝕥𝕙𝕖 𝔸𝕔𝕔𝕠𝕦𝕟𝕥 𝕀𝕔𝕠𝕟, 𝕘𝕠 𝕥𝕠 𝕊𝕖𝕥𝕥𝕚𝕟𝕘𝕤, 𝕒𝕟𝕕 𝕤𝕖𝕝𝕖𝕔𝕥 𝕃𝕚𝕟𝕜𝕖𝕕 𝔸𝕔𝕔𝕠𝕦𝕟𝕥𝕤. 𝔽𝕠𝕝𝕝𝕠𝕨 𝕥𝕙𝕖 𝕤𝕥𝕖𝕡𝕤 𝕥𝕠 𝕒𝕕𝕕 𝕠𝕣 𝕦𝕡𝕕𝕒𝕥𝕖 𝕪𝕠𝕦𝕣 𝕓𝕒𝕟𝕜. 𝕀𝕗 𝕥𝕙𝕖𝕣𝕖’𝕤 𝕒𝕟 𝕚𝕤𝕤𝕦𝕖, 𝕕𝕚𝕒𝕝 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟 𝕗𝕠𝕣 𝕤𝕥𝕖𝕡-𝕓𝕪-𝕤𝕥𝕖𝕡 𝕙𝕖𝕝𝕡. 𝔻𝕠𝕟’𝕥 𝕤𝕥𝕣𝕖𝕤𝕤—𝕛𝕦𝕤𝕥 𝕔𝕒𝕝𝕝 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟, 𝕒𝕟𝕕 𝕥𝕙𝕖 𝕤𝕦𝕡𝕡𝕠𝕣𝕥 𝕥𝕖𝕒𝕞 𝕨𝕚𝕝𝕝 𝕤𝕠𝕣𝕥 𝕚𝕥 𝕠𝕦𝕥. 𝔾𝕠𝕥 𝕞𝕠𝕣𝕖 𝕢𝕦𝕖𝕤𝕥𝕚𝕠𝕟𝕤? ℝ𝕖𝕒𝕔𝕙 𝕥𝕙𝕖𝕞 𝕒𝕥 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
