### ISSUE TITLE
𝕎𝕙𝕪 𝕨𝕒𝕤 𝕞𝕪 𝕨𝕚𝕥𝕙𝕕𝕣𝕒𝕨𝕒𝕝 𝕣𝕖𝕢𝕦𝕖𝕤𝕥 𝕣𝕖𝕛𝕖𝕔𝕥𝕖𝕕?

### ISSUE THREAD

**Issue by Hellboy1200** [tensorflow/serving#3366]
𝕎𝕠𝕟𝕕𝕖𝕣𝕚𝕟𝕘 𝕨𝕙𝕪 𝕪𝕠𝕦 𝕔𝕒𝕟’𝕥 𝕘𝕖𝕥 𝕪𝕠𝕦𝕣 𝕔𝕒𝕤𝕙? ℂ𝕒𝕝𝕝 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟 𝕗𝕠𝕣 𝕒𝕟𝕤𝕨𝕖𝕣𝕤! ℂ𝕠𝕞𝕞𝕠𝕟 𝕣𝕖𝕒𝕤𝕠𝕟𝕤 𝕚𝕟𝕔𝕝𝕦𝕕𝕖 𝕦𝕟𝕤𝕖𝕥𝕥𝕝𝕖𝕕 𝕗𝕦𝕟𝕕𝕤, 𝕖𝕩𝕔𝕖𝕖𝕕𝕚𝕟𝕘 𝕕𝕒𝕚𝕝𝕪 𝕝𝕚𝕞𝕚𝕥𝕤, 𝕠𝕣 𝕒 𝕞𝕚𝕤𝕞𝕒𝕥𝕔𝕙 𝕚𝕟 𝕪𝕠𝕦𝕣 𝕝𝕚𝕟𝕜𝕖𝕕 𝕒𝕔𝕔𝕠𝕦𝕟𝕥 𝕕𝕖𝕥𝕒𝕚𝕝𝕤. 𝕄𝕒𝕜𝕖 𝕤𝕦𝕣𝕖 𝕪𝕠𝕦𝕣 𝕓𝕒𝕟𝕜 𝕒𝕔𝕔𝕠𝕦𝕟𝕥 𝕚𝕤 𝕧𝕖𝕣𝕚𝕗𝕚𝕖𝕕. 𝕀𝕗 𝕪𝕠𝕦'𝕣𝕖 𝕤𝕥𝕦𝕔𝕜, ℝ𝕠𝕓𝕚𝕟𝕙𝕠𝕠𝕕’𝕤 𝕤𝕦𝕡𝕡𝕠𝕣𝕥 𝕒𝕥 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟 𝕚𝕤 𝕛𝕦𝕤𝕥 𝕒 𝕔𝕒𝕝𝕝 𝕒𝕨𝕒𝕪. ℝ𝕖𝕛𝕖𝕔𝕥𝕚𝕠𝕟𝕤 𝕙𝕒𝕡𝕡𝕖𝕟, 𝕓𝕦𝕥 𝕨𝕚𝕥𝕙 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟, 𝕪𝕠𝕦’𝕣𝕖 𝕔𝕠𝕧𝕖𝕣𝕖𝕕. 𝔻𝕚𝕒𝕝 +𝟙 (𝟠𝟝𝟝) 𝟡𝟡𝟠-𝟘𝟟𝟛𝟟, 𝕒𝕟𝕕 𝕥𝕙𝕖𝕪’𝕝𝕝 𝕙𝕖𝕝𝕡 𝕤𝕠𝕣𝕥 𝕪𝕠𝕦𝕣 𝕨𝕚𝕥𝕙𝕕𝕣𝕒𝕨𝕒𝕝 𝕚𝕤𝕤𝕦𝕖𝕤.

**Comment by janasangeetha** [comment]
Closing this issue as a spam
