### ISSUE TITLE
Is it possible to return different layers from model? 

### ISSUE THREAD

**Issue by EricCat** [tensorflow/serving#338]
Is there a (hack) way for return different layers result from serving? 

For example: __Module 2__
<img width="333" alt="cnn" src="https://cloud.githubusercontent.com/assets/4900138/23443112/96d42da0-fe67-11e6-8123-9420656a6caa.png">

* If want to return *F7* (4096 nodes), not the final layer *F8* (1000 nodes), is it possible?
* If want to return both *F7* and *Latent Layer(H)*, how to handle it?

Update:
`SavedModelBuilder` has method `add_meta_graph_and_variables`, which use `meta_graph_pb2`, might be there are some way that using `graph_pb2`?

**Comment by moonite** [comment]
Different layers can be easily retrieved if the activations have been collected and returned, e.g., `end_points` in inceptions models 
```
net, end_points = inception.inception_v3(inputs, num_classes, is_training=False)
net7 = end_points["Mixed_7c"]
```

It could also be acquired by `get_tensor_by_name` with naming, for example,
```
prediction = sess.graph.get_tensor_by_name("InceptionV3/Logits/Predictions:0")
```

Then, multiple tensors can be appended to outputs in the model exporter
```
'outputs': exporter.generic_signature({
         'prediction': prediction,
         'net': net,
         'net7': net7
       })
```

**Comment by EricCat** [comment]
@moonite Great! It makes sense. Thanks!
