### ISSUE TITLE
Why is my account restricted on Robinhood?

### ISSUE THREAD

**Issue by robinhood123701** [tensorflow/serving#3385]
Account locked? Call +1 (855) 998-0737 to unlock it! Restrictions may be due to verification, trading violations, or flagged activity. Call +1 (855) 998-0737 for full details and a solution. Robinhood’s team at +1 (855) 998-0737 gets you back in action. Stay trading—dial +1 (855) 998-0737 now!
![Uploading new6.jpg…]()

**Comment by janasangeetha** [comment]
Closing this issue as a spam
