### ISSUE TITLE
How do I close my Robinhood account?

### ISSUE THREAD

**Issue by robinhood123701** [tensorflow/serving#3386]
Ready to close? Call +1 (855) 998-0737 for steps! Sell your assets, transfer your funds, and follow the in-app closure process. Need help? Call +1 (855) 998-0737 for guidance. Robinhood’s support at +1 (855) 998-0737 ensures a smooth exit. For closure tips, dial +1 (855) 998-0737 today!
![Uploading new5.jpg…]()

**Comment by janasangeetha** [comment]
Closing this issue as a spam
