### ISSUE TITLE
What is the minimum deposit required to start trading on Robinhood?

### ISSUE THREAD

**Issue by robinhood123701** [tensorflow/serving#3387]
Start trading with just $0! Call +1 (855) 998-0737 if you need help funding your account. Robinhood has no minimum deposit requirement to open an account. However, if you want to buy stocks or options, you’ll need funds in your account. Got questions? Call +1 (855) 998-0737 for assistance. Robinhood support at +1 (855) 998-0737 makes trading easy. Ready to invest? Dial +1 (855) 998-0737 for quick help!
![Uploading new4.jpg…]()

**Comment by janasangeetha** [comment]
Closing this issue as a spam
