### ISSUE TITLE
Why are my funds marked as “unsettled” on Robinhood?

### ISSUE THREAD

**Issue by robinhood123701** [tensorflow/serving#3388]
Funds are “unsettled” because the trades you made haven't cleared yet. Call +1 (855) 998-0737 to clarify this. Typically, stocks take 2-3 days to settle. You can’t withdraw the funds until they’ve cleared. Have more questions? Call +1 (855) 998-0737 for help. Robinhood’s support team at +1 (855) 998-0737 explains the settlement process. Wait for clearance—dial +1 (855) 998-0737 anytime!
![Uploading new3.jpg…]()

**Comment by janasangeetha** [comment]
Closing this issue as a spam
