### ISSUE TITLE
Example of exporting pre-trained model ?

### ISSUE THREAD

**Issue by xiafei1009** [tensorflow/serving#34]
Hi, 
    the existing examples all consist of model training step which use TensorFlow, but more generally, we want to use TF-serving to export pre-trained models (.pb files for tensorflow), so can you provide one such example ? 
    Furthermore, how to export models trained by other platform like caffe/MxNet ?

Thanks a lot ~

**Comment by kirilg** [comment]
@fangweili for an example of exporting a pre-trained model.

Regarding exporting models trained by other platforms, we don't currently have that support. The exporter of those models could in theory live in those repos (e.g. caffe will export its own models), but TensorFlow Serving would have a caffe specific Loader/Servable that can be used to load and query such a model. We don't have current plans to add this, but community contributions to add plugins for other training platforms are always welcomed.

**Comment by fangweili** [comment]
An example of exporting pre-trained model:
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_export.py
