### ISSUE TITLE
Too much context switching In TensorflowServing

### ISSUE THREAD

**Issue by xiaop1987** [tensorflow/serving#340]
I started a Tensorflow-Serving on a machine with 64 virtual cores,  and start many clients to test latency,

I found situation that the cpu usage is high and the latency is also high, vmstats as flows:

procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
64  0      0 64174440      0     76    0    0    46  7508  148  696  2  7 91  0  0
66  0      0 64093436      0     76    0    0     0    30 115413 230976 11 31 57  0  0
68  0      0 64008884      0     76    0    0     0    10 124406 214773 12 33 54  0  0
75  0      0 63936236      0     76    0    0     0   282 122836 229664 12 33 55  0  0
 2  0      0 64002156      0     76    0    0     0    30 115859 211744 11 31 57  0  0
 6  0      0 63987948      0     76    0    0     0     6 110226 200891 11 30 59  0  0
57  0      0 63958056      0     76    0    0     0    31 115729 218898 11 31 58  0  0
 3  0      0 63953724      0     76    0    0     0     2 110963 202765 11 30 58  0  0
 1  0      0 63979004      0     76    0    0     0    42 116847 198888 11 31 57  0  0

and there are a lot of context switching. 

When I limited the cores(such as 8) TensorflowServing used，it can achieve lower latency.

I guess that TFServing starts too many threads.

**Comment by yuantaocai** [comment]
Hi, Recently, I'm doing tf-serving performance, could you share your example?
