### ISSUE TITLE
How do I report fraud or a scam on Robinhood?

### ISSUE THREAD

**Issue by sukritisharmabbi** [tensorflow/serving#3401]
Don’t wait—call +1 (855) 998-0737 now to report fraud or scams! Go to Help Center in the app, select Contact Us, and explain the issue. Provide as many details as possible, including screenshots or transaction IDs. Robinhood’s support team will investigate and take necessary action to secure your account. For immediate assistance, call +1 (855) 998-0737. Don’t let scammers win—Robinhood is here to help! Dial +1 (855) 998-0737 anytime.
![+1-855-998-0737 (10)](https://github.com/user-attachments/assets/083f7ae0-6442-4af1-8419-7735f184899f)

**Comment by janasangeetha** [comment]
Closing this issue as a spam
