### ISSUE TITLE
Is Kraken customer service 24 hours?{HELPLINE NO}

### ISSUE THREAD

**Issue by Surya99grdrg** [tensorflow/serving#3407]
⭐☎️1-858-858-6950 Indeed, Kraken offers top-notch assistance via ⭐☎️1-858-858-6950 [24/7 Helpline]. You can reach Kraken assistance via the Agent assistance option in the Kraken web portal, by phone at  [US], or by email at [expertcare@kraken.com](mailto:expertcare@kraken.com).

**Comment by janasangeetha** [comment]
Closing this issue as a spam
