### ISSUE TITLE
How do I contact support on Kraken?{USA}

### ISSUE THREAD

**Issue by Surya99grdrg** [tensorflow/serving#3414]
⭐☎️1-858-858-6950 Detailed information about Kraken support, the app,
⭐☎️1-858-858-6950 markets, CRO lockup, deposits and withdrawals, referral programs, and security may be found at the Kraken.com Help Center at . The phone number for Kraken Customer Care .

**Comment by janasangeetha** [comment]
Closing this issue as a spam
