### ISSUE TITLE
bazel build tenrsorflow_server error,download error

### ISSUE THREAD

**Issue by nkuzhixin** [tensorflow/serving#347]
centos 7.2
cuda 8.0
cudnn 5.1
bazel version
Build label: 0.4.4
tensorflow version: 1.0

when i build tensorflow server ,and I encount such error:
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': Error downloading [http://bazel-mirror.storage.googleapis.com/github.com/bazelbuild/rules_closure/archive/5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz, https://github.com/bazelbuild/rules_closure/archive/5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz] 

and in wordspace.bzl do not have 
but in my workspace.bzl do not have  "http://bazel-mirror.storage.googleapis.com/github.com/bazelbuild/rules_closure/archive/5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz"
and if i upload 5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz in my dir, could not solve.

**Comment by novawill** [comment]
I got a similar issue showed as [Bazel issue while building a pip package for TensorFlow with CPU-only support](https://stackoverflow.com/questions/44115259/bazel-issue-while-building-a-pip-package-for-tensorflow-with-cpu-only-support). I solved that issue by setting a proxy before $ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package. Hope it can help u. 这可能是天朝网络原因吧

**Comment by kohn1001** [comment]
I got the similar issue as well, as @novawill mentioned just setting the proxy solved it  (as an environment variable via the terminal) just adding more elaborate solution:
`export http_proxy=http://<your proxy>:<your proxy port>`
`export https_proxy=http://<your proxy>:<your proxy port>`
Notice that if your https proxy is different you may need to use it there and consider the prefix: "https://"
