### ISSUE TITLE
Cannot using GPU

### ISSUE THREAD

**Issue by tsaiian** [tensorflow/serving#355]
I want to use GPU for training, after added `with tf.device("/gpu")` to `mnist_saved_model.py`, I got follow error message:

> tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device to node 'Variable_1': Could not satisfy explicit device specification '/device:GPU:*' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0

It seems that serving is not correctly build for GPU device.

**Steps to reproduce:**
```sh
git clone --recurse-submodules https://github.com/tensorflow/serving
cd serving

export TF_NEED_CUDA=1
export TF_NEED_GCP=1
export TF_NEED_JEMALLOC=1
export TF_NEED_HDFS=0
export TF_NEED_OPENCL=0
export TF_ENABLE_XLA=0
export TF_CUDA_VERSION=8.0
export TF_CUDNN_VERSION=5
export TF_CUDA_COMPUTE_CAPABILITIES="3.5,5.2,6.1"
export CUDA_TOOLKIT_PATH="/usr/local/cuda"
export CUDNN_INSTALL_PATH="/usr/local/cuda"
export GCC_HOST_COMPILER_PATH="/usr/bin/gcc"
export PYTHON_BIN_PATH="/home/opt/anaconda/envs/py2/bin/python"
export CC_OPT_FLAGS="-march=native"
export PYTHON_LIB_PATH="/home/opt/anaconda/envs/py2/lib/python2.7/site-packages"

cd tensorflow
./configure
cd ..

# Ref: https://github.com/tensorflow/serving/issues/318#issuecomment-283498443
sed -i.bak 's/@org_tensorflow\/\/third_party\/gpus\/crosstool/@local_config_cuda\/\/crosstool:toolchain/g' tools/bazel.rc

bazel build -c opt --config=cuda --spawn_strategy=standalone //tensorflow_serving/model_servers:tensorflow_model_server

# add `with tf.device("/gpu")` to `mnist_saved_model.py`
sed -i '138s/.*/with tf.device("\/gpu"):/' tensorflow_serving/example/mnist_saved_model.py
sed -i '139s/.*/  if __name__ == "__main__":/' tensorflow_serving/example/mnist_saved_model.py
sed -i '140s/.*/    tf.app.run()/' tensorflow_serving/example/mnist_saved_model.py

bazel build //tensorflow_serving/example:mnist_saved_model
bazel-bin/tensorflow_serving/example/mnist_saved_model /tmp/mnist_model
```

**Environment:**
CUDA 8.0
cuDNN 5.1.10
```
$~/serving$ uname -a
Linux NLP-DevBox 3.19.0-59-generic #65~14.04.1-Ubuntu SMP Tue Apr 19 18:57:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$~/serving$ which python
/home/opt/anaconda/envs/py2/bin/python

$gcc -v
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
```

**Comment by jorgemf** [comment]
`with tf.device("/gpu")` is not a valid device it should be `with tf.device("/gpu:0")`. You have to say which GPU with the number.

**Comment by tsaiian** [comment]
@jorgemf same error after adding `with tf.device("/gpu:0")`

**Comment by jorgemf** [comment]
@tsaiian if nvidia-smi doesn't use all GPU memory when launching your program (even before loading the graph), then you don't have support for GPU. Try another commit, I couldn't make it compile with the latest commit.

**Comment by sugartom** [comment]
@tsaiian , when running `bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=mnist --model_base_path=/tmp/mnist_model/`, do you have log message like
> I external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:03:00.0)

If yes, from my understanding, your TF serving should be using GPUs.

**Comment by jorgemf** [comment]
I have updated the script I use to compile tensorflow serving:  https://gist.github.com/jorgemf/0f2025a45e1568663f4c20551a5881f1

**Comment by gautamvasudevan** [comment]
Closing due to staleness - we have new dockerfiles that should make this a lot easier.
