### ISSUE TITLE
Is there a way to graceful shutdown of Tensorflow Serving Server?

### ISSUE THREAD

**Issue by sskgit** [tensorflow/serving#356]
Tensorflow Serving Server right now has to be stopped by killing the process or logging of the VM. Is there a better way to graceful shutdown of the Serving server?

**Comment by chrisolston** [comment]
To implement this we can call server->Shutdown():
https://github.com/grpc/grpc/blob/master/include/grpc%2B%2B/impl/codegen/server_interface.h#L83

The question is what would trigger our main.cc to call that? An RPC?

I'm not sure what is the standard way to structure this for open-source servers. Maybe I'll open an issue on the grpc github for suggestions.

**Comment by chrisolston** [comment]
I posted an inquiry to grpc: https://github.com/grpc/grpc/issues/10223

**Comment by yupbank** [comment]
how about a `SIGTERM` or `SIGINT` ?  we are deploying tf/serving from docker, and it would benefit us from being able to handle such signal

**Comment by chrisolston** [comment]
If you can send a PR that adds a SIGTERM handler we can review it. Thanks!

**Comment by ymodak** [comment]
Closing this issue since [inquiry to grpc](https://github.com/grpc/grpc/issues/10223) provides the solution.

**Comment by jordanhurwitz** [comment]
So has a SIGTERM handler been implemented? or is there a separate issue tracking that?

Thanks!

**Comment by junneyang** [comment]
why close, how to gracefully shutdown the server
