### ISSUE TITLE
Fail to load the models from HDFS

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/serving#359]
We have tested the integration of TensorFlow and HDFS. It works for training and we can use TensorFlow APIs to access HDFS data.

However, I use that version of TensorFlow to build TensorFlow Serving and the server could not load the files from HDFS. I think TensorFlow Serving use the native TensorFlow Filesystem APIs and it should support HDFS well.

We pass the path of HDFS like this.

```
--model_base_path=hdfs://namenode:10000/user/u_chendihao/deep_recommend_system/model/
```

Here is the error log.

```
E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:304] FileSystemStoragePathSource encountered a file-system access error: Could not find base path hdfs://namenode:10000/user/u_chendihao/deep_recommend_system/model/ for servable dense
```

**Comment by chrisolston** [comment]
When you run 'configure' on tensorflow, did you say "Y" to including hadoop support? (By default it is not included.)

**Comment by tobegit3hub** [comment]
Thanks @chrisolston . Yes, we have set "Y" for hadoop support when `./configure`.

I'm also set all the environment variables for Java and hadoop although it's not documented for TensorFlow Serving. It may be the same as TensorFlow itself. But it doesn't work and throw those errors.

**Comment by terryKing1992** [comment]
@tobegit3hub did you find the approach on loading model from HDFS？if not perhaps i will download the model to local, and serving it.

**Comment by tobegit3hub** [comment]
Thanks @terryKing1992 and downloading model files into local filesystem can always work without doubt.

**Comment by manuzhang** [comment]
The error is from the following codes.

```cpp
  if (!Env::Default()->FileExists(servable.base_path()).ok()) {
    return errors::InvalidArgument("Could not find base path ",
                                   servable.base_path(), " for servable ",
                                   servable.servable_name());
  }
```

After diving into `Env::FileExists` I found null is returned with error `Unimplemented: File system scheme hdfs not implemented` although I'd set `Y` for Hadoop support when `./configure`.

**Comment by tobegit3hub** [comment]
@chrisolston Can you have a look at this which is easy to re-produced?

**Comment by llhe** [comment]
Adding `@org_tensorflow//tensorflow/core/platform/hadoop:hadoop_file_system` [here](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/BUILD#L134) should solve this.

**Comment by llhe** [comment]
Another option (after proper `./configure`):
```
bazel build --define with_hdfs_support=true tensorflow_serving/model_servers:tensorflow_model_server
```

**Comment by tobegit3hub** [comment]
This works like a charm and thanks @llhe

**Comment by JohnHerry** [comment]
Again, the  tensorflow_model_server built can not listen on hdfs address. tensorflow serving branch r1.5

**Comment by chentianyou** [comment]
I have this problem too.
 @JohnHerry Have you solved the problem？

**Comment by JohnHerry** [comment]
Yes, I missed some environment variable about hadoop before.
If you still have such problem, try as follows:
# in $HOME/.bash_profile.
`export HADOOP_HOME=/home/john/tests/hdfs_tensorflow/hadoop/hadoop-2.8.0
export HADOOP_INSTALL=$HADOOP_HOME
export HADOOP_MAPRED_HOME=$HADOOP_HOME
export HADOOP_COMMON_HOME=$HADOOP_HOME
export HADOOP_HDFS_HOME=$HADOOP_HOME
export YARN_HOME=$HADOOP_HOME
export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin`

**Comment by KeithTt** [comment]
Same problem here with docker image `tensorflow/serving:2.10.0`.

It seems there is no hdfs in the image, maybe I should add it to the Dockerfile and build a new image?
