### ISSUE TITLE
Exporting models interactively in python

### ISSUE THREAD

**Issue by eriophora** [tensorflow/serving#36]
It looks like the examples for TensorFlow Serving rely on c code only for running the server. Things like querying the server and exporting models can be done in Python. However, it also seems like you're obliged to write the python code then compile the damn thing with Bazel (what is it with the documentation's obsessive love for Bazel?) into executables, making rapid iteration difficult (at least for me). 

Is there a way to use the pure python parts of TF Serving interactively? I.e., actually run `from tensorflow_serving.session_bundle import exporter` in an interpreter? With regular TF, you can build a pip repo and install it that way, but this doesn't appear to be an option for TF Serving. Are there plans to implement one?

**Comment by nfiedel** [comment]
Thanks eriophora@ for filing this issue. It does sound like a pip repo would make things easier. We don't have plans to implement this (yet), but we'll keep track of this. Pull requests are welcome too.

For future reference, the TF pip script is at tensorflow/tools/ci_build/builds/pip.sh.

**Comment by kirilg** [comment]
The exporter (along with the rest of session_bundle) were moved to Tensorflow/contrib in the main Tensorflow repo, so the exporter is now part of the regular release. That means that you can either link it in directly and compile using Bazel (as was always possible), or install Tensorflow using the pip package and import directly in your Python program as you would any other Tensorflow python code.
