### ISSUE TITLE
Feature Request: Support Binaries or an apt-get Version

### ISSUE THREAD

**Issue by speedplane** [tensorflow/serving#365]
Building TensorFlow Serving takes an inordinate amount of time, well more than 20 minutes on my decently modern laptop. Further, there are numerous issues that arise in its compilation as shown by the number of compilation issues filed on github. There should be an `apt-get` style installation procedure that does not require building so many components (i.e., completes in less than 5 minutes on a standard computer).

**Comment by kirilg** [comment]
We just released TensorFlow Serving 1.0.0 which comes with a pre-built binary that you can install using apt-get. Please check out the instructions [here](https://www.tensorflow.org/serving/setup#installing_using_apt-get).
