### ISSUE TITLE
How to host .ckpt and .meta files ?

### ISSUE THREAD

**Issue by dangithubs** [tensorflow/serving#371]
I have recently been looking into using tensorflow_serving to serve some models. The models I have been handed include .ckpt and .meta files. To be clear I do not have the source code that was used to generate these files. I simply want to serve the model up.

From what I can see, the way to make tensorflow_serving serve the files you may have to convert them to .pb

I have seen mention the freeze_graph.py which is supposed to do this for you. However freeze_graph.py appears to require 3 arguments and I can find very little documentation or a working example to make it work with just the two files (.ckpt and .meta).

Can someone please give me an example of how I can use freeze_graph.py with the files I have above ?

**Comment by terryKing1992** [comment]
currently, the compatibility between `tensorflow` and `tensorflow serving` on model saver and loader is no supported very well. i am also working on it.

**Comment by sukritiramesh** [comment]
Hi @dangithubs, can you provide some more information about your model on disk? Does it contain an export.meta file?

If so, the export format you are looking at is likely the deprecated SessionBundle. Here is some documentation about the format: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/session_bundle/README.md

The new export format that will work with TensorFlow Serving is SavedModel, which is documented here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/README.md

To up-convert from the deprecated SessionBundle format to the new SavedModel format, please check out the APIs in bundle shim.
- Python: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/session_bundle/bundle_shim.py
- C++: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/session_bundle/bundle_shim.cc

**Comment by dangithubs** [comment]
Hi Sukritiramesh,

I was looking at the files that are hosted here : 

https://github.com/ry/tensorflow-resnet

The files are linked on that page are :

https://raw.githubusercontent.com/ry/tensorflow-resnet/master/data/tensorflow-resnet-pretrained-20160509.tar.gz.torrent

If you download and unzip you will see the .ckpt files and .meta files that are supplied.

I am not sure if there is an export.meta file present.

Thank you for assisting with this.

**Comment by sukritiramesh** [comment]
Upconverting from the .meta format to the SavedModel format (see previous response) should work with TensorFlow Serving. Resolving issue, but please feel free to reopen if required. Thanks!
