### ISSUE TITLE
tensorflow_serving/apis/prediction_service.grpc.pb.h

### ISSUE THREAD

**Issue by GaelReinaudi** [tensorflow/serving#377]
Hi,
I am following the installation instructions in order to run the example cpp client.
The files in the _tensorflow_serving/api directory_ , such as the much needed _tensorflow_serving/apis/prediction_service.grpc.pb.h_ don't seem to be generated. I can manually generate model.grpc.pb.h by running protoc3, but the others complain about the -I path or other proto files missing.

Am I missing any obvious step here?
thanks

os: Ubuntu 16.04

**Comment by kirilg** [comment]
You shouldn't need to manually generate those files, Bazel will do that for you. You'll just need to run `bazel build <path>` and `bazel-bin/...` following the instructions (e.g. https://tensorflow.github.io/serving/serving_basic).

If it doesn't work, please include what instructions you were using and what was the failing command + the error.

**Comment by GaelReinaudi** [comment]
I looked closer at the result after building and I could actually find the files in the hard linked folder bazel-genfiles.
Assuming I point at it for the includes path of my code, it now complains about another file from the tensorflow tree:
`../../../../.cache/bazel/_bazel_user/579e58e75b46e15f3f5336dadb5c99e4/execroot/serving/bazel-out/local-fastbuild/genfiles/tensorflow_serving/apis/input.pb.h:31: error: tensorflow/core/example/example.pb.h: No such file or directory`

What I am trying to do is a small c++ program that can send data to the tensorflow server and get the prediction back from my model. It is not obvious to me how to generate the includes files in a clean and reliable way.

**Comment by kirilg** [comment]
See my previous reply which still stands. You can use Bazel to build all proto dependencies in a clean and reliable way. Are you explicitly trying to avoid using Bazel or do you have other reasons to manually generate pb.h files?

[This](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_client.cc#L5) is an example client that sends requests to a model server, and [this](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/BUILD#L125) is the place in the BUILD file that declares the dependency which makes Bazel build the proto file.

**Comment by GaelReinaudi** [comment]
Hi,
thank you for your answer.
I am using bazel alright.
The only reason why I try to build those files manually is because I can't find them in the tensorflow_serving folder after executing bazel build tensorflow_serving/...

My solution for now is to run the a modified python client and to communicate by Tcp messages between my c++ and python. 

Thx
