### ISSUE TITLE
How can i export model into HDFS?

### ISSUE THREAD

**Issue by terryKing1992** [tensorflow/serving#381]
I follow the basic guide of tensorflow serving [https://tensorflow.github.io/serving/serving_basic](https://tensorflow.github.io/serving/serving_basic). just change the saved model path like `hdfs://127.0.0.1:10000/mnist_model`.

the guide script as follow:
```
$>bazel build //tensorflow_serving/example:mnist_saved_model
$>bazel-bin/tensorflow_serving/example/mnist_saved_model /tmp/mnist_model
```
and I change the script like this:

```
$>bazel build //tensorflow_serving/example:mnist_saved_model
$>bazel-bin/tensorflow_serving/example/mnist_saved_model hdfs://127.0.0.1:10000/mnist_model
```
 and then the program hang up at 

`builder = saved_model_builder.SavedModelBuilder(export_path)`

when i  deep into call stack, i find it stucked by  

`file_io.recursive_create_dir(self._export_dir)`

 when recursively to create hdfs directory.

I try to use

 `hdfs dfs -mkdir hdfs://127.0.0.1:10000/mnist_model`

 it works well. anyone else have met this issue?

what should I Do to fix it? thanks

**Comment by gautamvasudevan** [comment]
Closing due to staleness.
