### ISSUE TITLE
How to build tensorflow serving on MAC

### ISSUE THREAD

**Issue by terryKing1992** [tensorflow/serving#389]
the solution is that just removing the lines which contains copts = [ "-std=gnu99",] in this [https://github.com/tensorflow/tensorflow/blob/master/third_party/grpc.BUILD](https://github.com/tensorflow/tensorflow/blob/master/third_party/grpc.BUILD)file, then there is no error when building tensorflow serving. Hope it does work for you who want to build serving on MAC

**Comment by promiseofcake** [comment]
Once this is merged: https://github.com/tensorflow/tensorflow/pull/11768, we should no longer need to do this.

**Comment by promiseofcake** [comment]
This issue is now stale.

**Comment by chikubee** [comment]
@promiseofcake I still face issues serving it on mac.
I intend to do it without Docker.
Can you please suggest me a way?

**Comment by promiseofcake** [comment]
Unfortunatley we are running in container for everything now, we do have builds succeeding on Darwin however. We are using 1.8 for tf/tf_serving so not sure if anything has changed since then.
