### ISSUE TITLE
Kubernetes deployments fails

### ISSUE THREAD

**Issue by sebgoa** [tensorflow/serving#390]
the Kubernetes deployment manifest at:

https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_k8s.yaml

Fails to run.

The server is not there in the image.

```
$ kubectl logs inception-deployment-1543703507-042r7
/bin/sh: 1: /serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server: not found
```

The image on gcr has no `model_servers` directory:

```
docker run -ti --rm gcr.io/tensorflow-serving/inception /bin/bash
root@cd0d1569d74c:/# cd /serving/bazel-bin/tensorflow_serving/
root@cd0d1569d74c:/serving/bazel-bin/tensorflow_serving# ls -l
total 36
drwxr-xr-x  7 root root 4096 Mar 21  2016 batching
drwxr-xr-x 19 root root 4096 Mar 21  2016 core
drwxr-xr-x 10 root root 4096 Mar 21  2016 example
drwxr-xr-x  5 root root 4096 Mar 21  2016 resources
drwxr-xr-x  4 root root 4096 Mar 21  2016 servables
drwxr-xr-x  8 root root 4096 Mar 21  2016 session_bundle
drwxr-xr-x  3 root root 4096 Mar 21  2016 sources
drwxr-xr-x  3 root root 4096 Mar 21  2016 test_util
drwxr-xr-x 12 root root 4096 Mar 21  2016 util
```

Is there an image tag we can use to make sure we got a working image ?

thanks, just trying to follow this guide https://tensorflow.github.io/serving/serving_inception

**Comment by sebgoa** [comment]
the tag was changed to latest in #268 

`0.0.2` tag does not exist.

**Comment by sebgoa** [comment]
fwiw, this is a dupe of #287 

it would be great to have a tag of a working image.

**Comment by sebgoa** [comment]
Also relates to #265 

so closing.

@dlorenc I am also trying to test this on minikube.

**Comment by gautamkmr** [comment]
Just realized that tensorflow_model_server binary moved to /usr/bin folder
