### ISSUE TITLE
How to configure `the number of client threads` when batching is enabled

### ISSUE THREAD

**Issue by pgplus1628** [tensorflow/serving#394]
In  [session_bundle_config.proto](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/servables/tensorflow/session_bundle_config.proto), it says, 

> IMPORTANT: With batching enabled, client threads will spend most of their
> time blocked on Session::Run() calls, waiting for enough peer threads to
> also call Session::Run() such that a large batch can be formed. For good
> throughput, we recommend setting the number of client threads equal to
> roughly twice the maximum batch size ('max_batch_size' below). 

My question is how to set **the number of client threads**? Does the **client threads** means the grpc server threads? Since once a request comes, the grpc server will get one handler thread from thread pool and handle the request.

**Comment by chrisolston** [comment]
If you're using the model_servers/main.cc binary then yes, it's the grpc threads. I'm not sure off the top of my head how to configure the size of the grpc thread pool. The default size is probably fine unless you have a gigantic batch size.

**Comment by pgplus1628** [comment]
Thanks.
