### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [tensorflow/serving#4]
Would you like to [replace any double quotes](https://github.com/tensorflow/serving/blob/458b7f3b2e1dabafd317c8d5a6ed94e7f9e7fa95/tensorflow_serving/core/dynamic_manager.h#L24 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by kirilg** [comment]
Linking in https://github.com/tensorflow/tensorflow/issues/1178 which is a similar issue opened in Tensorflow. Let's resolve this discussion there, and it would make sense for us to be consistent and adopt the same decision.

**Comment by kirilg** [comment]
Closing issue as per the discussion in TensorFlow. We can revisit if that decision changes. Thanks for bringing this up and the discussion on that thread.
