### ISSUE TITLE
Verbose logging for prediction

### ISSUE THREAD

**Issue by waichee** [tensorflow/serving#402]
Hi 

Just wondering is it possible to turn on more verbose logging such it will log out information on the requests being processed?

**Comment by kirilg** [comment]
You should be able to enable VLOG log statements that are not printed by default (search code for VLOG(1) for example) by setting the environment variable TF_CPP_MIN_VLOG_LEVEL=1. If the existing logging is insufficient, you can also add your own VLOG statements to help in your debugging.

**Comment by waichee** [comment]
thanks @kirilg any chance that there's also an environment variable to specify the log output format (example to have it spit out json logs)?

**Comment by kirilg** [comment]
I'm not aware of a way to log the output in any other format, sorry. We use TensorFlow's logging libraries so perhaps you can file a feature request in the TensorFlow repo and they can triage. If they add support, we'll be able to pull that in here as well.

**Comment by joekiqin** [comment]
it can just print request and response? TF_CPP_MIN_VLOG_LEVEL=1、2、3，print too much log and continuous output
