### ISSUE TITLE
404 Not Found Error when building from Docker image

### ISSUE THREAD

**Issue by MtDersvan** [tensorflow/serving#407]
Hi, when building a docker container on mac, i'm getting the following error:

curl: (22) The requested URL returned error: 404 Not Found

![image](https://cloud.githubusercontent.com/assets/7069222/25130786/463bc32e-23f8-11e7-9a7b-132d1bd6355f.png)

This is due to the fact, that 'https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE.txt' returns 404: Not Found.
If someone will have the same error, try modifing this link in Dockerfile.devel to 'https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE', then everything builds perfectly.

**Comment by kirilg** [comment]
Thanks @MtDersvan! The dockerfile is now fixed, so this should work from head.
