### ISSUE TITLE
Error at model server startup if logging_config is set

### ISSUE THREAD

**Issue by giavjeko** [tensorflow/serving#408]
Model server config (text formatted protobuf):
```
model_config_list {
  config {
    name: "default"
    base_path: "/data/model"
    model_platform: "tensorflow"
    version_policy: ALL_VERSIONS
    logging_config {
      log_collector_config {
        type: "",
        filename_prefix: "/log/model-server"
      }
      sampling_config {
        sampling_rate: 1
      }
    }
  }
}
```

Startup fails with the following error:
```
F tensorflow_serving/model_servers/main.cc:445] Check failed: ::tensorflow::Status::OK() == (ServerCore::Create(std::move(options), &core)) (OK vs. Invalid argument: No request-logger-creator provided.)
```

**Comment by sukritiramesh** [comment]
From a quick check, it looks like it attempts to perform an update without access to a request logger creator when the logging config map is not empty.

@vinuraja, is this expected?

**Comment by giavjeko** [comment]
This still happens in `r0.6` branch. Any info?

**Comment by tvkamara** [comment]
I also stumbled across this error. I'm just trying to get some logging out of the sample model server. Specifically to log the requests and responses.

**Comment by giavjeko** [comment]
This still happens in r1.5 branch. Any info?

**Comment by vinuraja** [comment]
Thanks for reporting this. Sorry, this is expected at this point in time. We haven't yet added full support for logging requests to the model-server. We are having design discussions on this within the team, and will get back to you.

**Comment by nbajason** [comment]
so how shall we check the logs? @vinuraja 
please kindly advise.

**Comment by hgadig** [comment]
@vinuraja  Any update on this ?

**Comment by mraduldubey** [comment]
Please provide an update on this. Thanks.

**Comment by mcf330** [comment]
Is there any workaround to log the requests rather than enable the TF_CPP_MIN_VLPG_LEVEL flag? thanks.

**Comment by mikezhang95** [comment]
any updates on this?

**Comment by krislc** [comment]
any updates?

**Comment by krislc** [comment]
I've tried "docker ....-e TF_CPP_MIN_VLOG_LEVEL=1....",  it outputs too many logs and make the inference too slow,  I just need an easy way to redirect the predicitions to a log file.

**Comment by H-Yin** [comment]
any updates? @vinuraja

**Comment by singhniraj08** [comment]
@giavjeko,

PredictStreamed is introduced to PredictionLog which represents a logged stream of PredictRequests and PredictResponses in [TF Serving 2.12 release](https://github.com/tensorflow/serving/releases/tag/2.12.0). Ref Commit: https://github.com/tensorflow/serving/commit/557f68a88d6be9a0f53beeca02a366359d787d4d

Additionally, tracking for additional metadata for request logs is also introduced. Ref Commit: https://github.com/tensorflow/serving/commit/e0a3b5f990b9801d21c739dd27b8430c49353d8b

Please try the new 2.12 release of TF Serving and let us know if it resolves the logging issue. Thank you!
