### ISSUE TITLE
Unable to start the server, load failure

### ISSUE THREAD

**Issue by mikucy** [tensorflow/serving#411]
Hello everyone, when I run

`root@95343676d628:/serving# bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=shiguoyu --model_base_path=shiguoyu_export`

It shows that

`E tensorflow_serving/core/loader_harness.cc:104] Servable: {name: shiguoyu version: 1} load failure: Not found: Op type not registered 'FIFOQueueV2'`

What's the problem? Thanks.

**Comment by xiaop1987** [comment]
The version of tensorflow of your training and exporting model may not match the version of tensorflow of tensorflow-serving dependent;

ps: Exporting FIFOQueue  maybe not a good idea.

**Comment by sukritiramesh** [comment]
That sounds right; ensuring the same TensorFlow version is used for training and serving should allow the op registration to work correctly.
