### ISSUE TITLE
Add support for HDFS model loading

### ISSUE THREAD

**Issue by llhe** [tensorflow/serving#415]
There are some issues complains about HDFS support for tensorflow serving, like https://github.com/tensorflow/serving/issues/381, https://github.com/tensorflow/tensorflow/issues/8861 and https://github.com/tensorflow/serving/issues/359. From the source code, the HDFS code is not linked in to the tensorflow serving binary.

It's suggested to add configure support or simply link HDFS in all the time.

**Comment by xiaop1987** [comment]
@llhe 
The dependency of supporting HDFS is linked by tensorflow, If you enabled HDFS support when running `./configure`, then tensorflow serving can load model from hdfs.

**Comment by llhe** [comment]
@xiaop1987  Checked the latest build script, the [refered target](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/BUILD#L762) indeed links [tf_additional_core_deps](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/BUILD#L1536) which actually links HDFS. Some dependencies are duplicated.

**Comment by llhe** [comment]
Tested with the latest code, it still does not work as expected. You still need specify bazel configs like this after `./configure`:
```
bazel build --define with_hdfs_support=true tensorflow_serving/model_servers:tensorflow_model_server
```
Because [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/BUILD#L141) definition is not included in the target.

**Comment by manuzhang** [comment]
@llhe Can you reopen this issue ? It is either related to code or to (missing) document but it's not resolved.

**Comment by llhe** [comment]
@manuzhang
The root cause of this issue is [the build config_setting](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/BUILD#L141) is not included in tensorflow serving.

**Comment by manuzhang** [comment]
@llhe How is it different from Google Cloud Storage ? Do you have a PR ready ?

**Comment by llhe** [comment]
@manuzhang GCS is supported by [hard coded dependency](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/BUILD#L134).

A better solution could be move [these configurations](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/BUILD#L140) to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/BUILD. @kirilg, @chrisolston What do you think?

**Comment by jimdowling** [comment]
HDFS support for tensorflow model serving would be a great feature. Any progress on this?

**Comment by tobegit3hub** [comment]
Hi @jimdowling . I think it has been fixed with https://github.com/tensorflow/serving/pull/432 .

**Comment by lxl910915** [comment]
If model size is large, such as 20G, tf serving failed with log : "W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Invalid argument: hdfs://**"

**Comment by abop** [comment]
Hdfs supported by default since TensorflowServing 1.4.
For more information : https://www.tensorflow.org/deploy/hadoop
