### ISSUE TITLE
Batching requests get higher latency

### ISSUE THREAD

**Issue by ismaeIfm** [tensorflow/serving#416]
Hi, I didn't use the batching implementation from TF Serving, I simply sent a request with an array of shape (batch_size, input_size) instead of (1, input_size).

`request.inputs['input_name'].CopyFrom(
            tf.contrib.util.make_tensor_proto(
                in_, shape=in_.shape, dtype=tf.float32))`

I understand that this batching shouldn't be faster, even though it's getting slower. For example I'm getting:
- ~ 0.8 seconds - for a prediction of 1 element 

- ~ 1.4 seconds - for a prediction of 2 elements

- ~ 1.8 seconds - for a prediction of 3 elements

- ~ 2.0 seconds - for a prediction of 4 elements
etc.

Any idea what might be the reason?

NOTE: This model has 7 inputs each of input_size of ~ 128. So to get a prediction for one element it consumes 7 vectors of size ~128.

**Comment by lilao** [comment]
+1 to xiaop1987.

**Comment by ricardocorral** [comment]
I'm sorry, what is the conclusion of this issue?
What is the advantage of using TF serving batching if it is slower at the end?

**Comment by xiaop1987** [comment]
@ricardocorral In some extreme cases, the batching will reduce the latency. When using full resource of your machine, batching will get better performance for every request from average. 

In another case, when using GPU for TF serving prediction, for the overhead of coping data from memory to GPU is expensive, each request coping small data to GPU does not make full use of bandwidth, batching the requests can reduce the average overhead of coping data which makes better performance.
