### ISSUE TITLE
Bazel build - ERROR: couldn't determine target from filename ''.

### ISSUE THREAD

**Issue by vanzytay** [tensorflow/serving#418]
Hi,

I followed the tutorials and when executing `bazel build tensorflow_serving/..`, I got the error

ERROR: couldn't determine target from filename ''.
INFO: Elapsed time: 0.098s

I'm on Ubuntu 14.04, with Bazel 0.4.5. 

Wondering if I'm missing something obvious. 

Thanks in advance!

**Comment by kirilg** [comment]
I should be `bazel build tensorflow_serving/...` (3 dots)
