### ISSUE TITLE
Model server binary

### ISSUE THREAD

**Issue by anandanand84** [tensorflow/serving#423]
I haven't seen any binaries released for tensorflow model server in this repository.  I would like to skip the building of tensorflow_model_server binary files for linux(ubuntu), Can I use the binary from the CI link below

http://ci.tensorflow.org/view/Serving/job/serving-master-cpu/ws/bazel-bin/tensorflow_serving/model_servers/

**Comment by chrisolston** [comment]
Sorry, we don't currently have a binary release process. Please refer to https://github.com/tensorflow/serving/issues/365
