### ISSUE TITLE
inception_inference.proto no longer in master / not available in https://github.com/tensorflow/serving/tree/master

### ISSUE THREAD

**Issue by johndpope** [tensorflow/serving#425]
it seems to have existed previously in another commit. was the file deprecated? 
should it be put back into master? or did things get shoved over to tensorflow models (which is also missing the proto file)
https://github.com/tensorflow/models/tree/master/inception

https://github.com/tensorflow/serving/tree/master/tensorflow_serving/example
no proto

proto here -> 
https://github.com/tensorflow/serving/blob/c948af73268c8071fed17a6edcf95b34e40583f2/tensorflow_serving/example/inception_inference.proto

are there other missing proto files ?
eg. 
https://github.com/tensorflow/serving/blob/c948af73268c8071fed17a6edcf95b34e40583f2/tensorflow_serving/example/mnist_inference.proto

**Comment by chrisolston** [comment]
Please see https://github.com/tensorflow/serving/commit/156e52b9835ed2d84eda7da31845a5deb86b1abe
