### ISSUE TITLE
Predict Response in Multi-inference API

### ISSUE THREAD

**Issue by rbrthogan** [tensorflow/serving#426]
Hi there, thanks for your work on the Multi-inference API, it's great. 

I am however limited for my use case when using just Regress and Classify APIs. Is there any plan to add Predict Responses to the Multiinference API?

My use case should be quite common, I have a feed forward network for classification but also want to optionally use it for feature extraction without repeating the computation. The feature layer has a several thousand outputs so packaging it nicely into Regression or Classification isn't possible. The Predict API gives me the flexibility I need.

Alternatively, the Regression API could be extended to regress on vectors i.e. `repeated float value`

Or am I missing something? Could I get a large vector response using Regress or Classify?

**Comment by chrisolston** [comment]
Indeed, we have been discussing that very thing. We haven't fully decided exactly how to package it, but something morally equivalent to adding Predict to Multi-Inference is in the works. Stay tuned.

**Comment by rbrthogan** [comment]
Thanks for the quick response and glad you are thinking of it. For now I'll just use the Classification API without specifying "classes" and just manually unpack the result. Will keep my eye out new additions that make it less ugly

**Comment by sukritiramesh** [comment]
Sounds good! Resolving this issue for now then.
