### ISSUE TITLE
Reshaping an input tensor via C++ API

### ISSUE THREAD

**Issue by viksit** [tensorflow/serving#43]
In the python world, the tf.reshape API works well to do this. But whats a good example in the C++ API?

The use case is that my graph needs a tensor of shape (1, x, y), and my input is coming in as (1, x* y). I'd like to transform the latter into the former, but can't find any examples to go on (yet).

**Comment by fangweili** [comment]
you will need to use TF C++ API to cast it to an Eigen vector/tensor/matrix and, use Eigen API for the transformation/reshape, and cast it back to a TF tensor.

**Comment by fangweili** [comment]
Examples can be found in `inception_inference.cc`:
`batched_input.vec<string>()`
`batched_classes.matrix<int>()`

Those are to **cast** TF tensors into Eigen realm. The underlying memory is the same, therefore whatever you modify/transform through Eigen APIs are reflected in TF tensors.

**Comment by viksit** [comment]
@fangweili thanks for your response - but in that file, I can't see something being cast using the Eigen API?
