### ISSUE TITLE
build failed on Centos6.7 with Error: suffix or operands invalid for ""

### ISSUE THREAD

**Issue by dzl0912** [tensorflow/serving#431]
when I build tensorflow with：
(1) 
cd tensorflow
export TF_NEED_CUDA=0
export TF_NEED_GCP=0
export TF_NEED_JEMALLOC=1
export TF_NEED_HDFS=0
export TF_NEED_OPENCL=0
export TF_ENABLE_XLA=0
export TF_NEED_VERBS=0
export TF_CUDA_VERSION=8.0
export TF_CUDNN_VERSION=5
export TF_CUDA_COMPUTE_CAPABILITIES="6.1"
export CUDA_TOOLKIT_PATH="/usr/local/cuda"
export CUDNN_INSTALL_PATH="/usr/local/cuda"
export GCC_HOST_COMPILER_PATH="/usr/local/bin/gcc"
export PYTHON_BIN_PATH="/data/opt/anaconda/anaconda2/bin/python"
export CC_OPT_FLAGS="-march=native"
export PYTHON_LIB_PATH="/data/opt/anaconda/anaconda2/lib/python2.7/site-packages"
 ./configure 

(2) bazel build -c opt tensorflow_serving/...
encounter an error:

external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1096: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1097: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1098: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1099: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1100: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1101: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1102: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1103: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1104: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1105: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1106: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1107: Error: no such instruction: `vbroadcasti128 (%r10),%ymm15'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1108: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1109: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1110: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1111: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1112: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1117: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1118: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1119: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1120: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1121: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1122: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1123: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1124: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1125: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1126: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1127: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1128: Error: no such instruction: `vbroadcasti128 (%r11),%ymm14'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1129: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1130: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1131: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1132: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1133: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1134: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1135: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1136: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1137: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1138: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1139: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1140: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1141: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1142: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1143: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1144: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1145: Error: no such instruction: `vbroadcasti128 (%r10),%ymm15'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1146: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1147: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1148: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1149: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1150: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1151: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1152: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1153: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1154: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1155: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1156: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1157: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1158: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1159: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1160: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1161: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1162: Error: no such instruction: `vbroadcasti128 (%r11),%ymm14'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1163: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1164: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1165: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1166: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1167: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1168: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1169: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1170: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1171: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1172: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1173: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1174: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1175: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1176: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1177: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1178: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1179: Error: no such instruction: `vbroadcasti128 (%r10),%ymm15'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1180: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1181: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1182: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1183: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1184: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1189: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1190: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1191: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1192: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1193: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1194: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1195: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1196: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1197: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1198: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1199: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1200: Error: no such instruction: `vbroadcasti128 (%r11),%ymm14'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1201: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1202: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1203: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1204: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1205: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1206: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1207: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1208: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1209: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1210: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1211: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1212: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1213: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1214: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1215: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1216: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1217: Error: no such instruction: `vbroadcasti128 (%r10),%ymm15'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1218: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1219: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1220: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1221: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1222: Error: suffix or operands invalid for `vpor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1227: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1228: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1229: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1230: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1232: Error: suffix or operands invalid for `vpunpckldq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1233: Error: suffix or operands invalid for `vpunpckldq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1234: Error: suffix or operands invalid for `vpunpckhdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1235: Error: suffix or operands invalid for `vpunpckhdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1236: Error: suffix or operands invalid for `vpunpcklqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1237: Error: suffix or operands invalid for `vpunpckhqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1238: Error: suffix or operands invalid for `vpunpcklqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1239: Error: suffix or operands invalid for `vpunpckhqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1240: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1241: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1242: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1243: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1245: Error: suffix or operands invalid for `vpunpckldq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1246: Error: suffix or operands invalid for `vpunpckldq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1247: Error: suffix or operands invalid for `vpunpckhdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1248: Error: suffix or operands invalid for `vpunpckhdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1249: Error: suffix or operands invalid for `vpunpcklqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1250: Error: suffix or operands invalid for `vpunpckhqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1251: Error: suffix or operands invalid for `vpunpcklqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1252: Error: suffix or operands invalid for `vpunpckhqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1253: Error: no such instruction: `vperm2i128 $0x20,%ymm1,%ymm9,%ymm15'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1254: Error: no such instruction: `vperm2i128 $0x31,%ymm1,%ymm9,%ymm1'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1255: Error: no such instruction: `vperm2i128 $0x20,%ymm10,%ymm14,%ymm9'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1256: Error: no such instruction: `vperm2i128 $0x31,%ymm10,%ymm14,%ymm10'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1257: Error: no such instruction: `vperm2i128 $0x20,%ymm3,%ymm11,%ymm14'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1258: Error: no such instruction: `vperm2i128 $0x31,%ymm3,%ymm11,%ymm3'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1259: Error: no such instruction: `vperm2i128 $0x20,%ymm0,%ymm8,%ymm11'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1260: Error: no such instruction: `vperm2i128 $0x31,%ymm0,%ymm8,%ymm0'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1266: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1267: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1268: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1269: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1271: Error: suffix or operands invalid for `vpunpckldq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1272: Error: suffix or operands invalid for `vpunpckldq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1273: Error: suffix or operands invalid for `vpunpckhdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1274: Error: suffix or operands invalid for `vpunpckhdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1275: Error: suffix or operands invalid for `vpunpcklqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1276: Error: suffix or operands invalid for `vpunpckhqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1277: Error: suffix or operands invalid for `vpunpcklqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1278: Error: suffix or operands invalid for `vpunpckhqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1279: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1280: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1281: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1282: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1284: Error: suffix or operands invalid for `vpunpckldq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1285: Error: suffix or operands invalid for `vpunpckldq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1286: Error: suffix or operands invalid for `vpunpckhdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1287: Error: suffix or operands invalid for `vpunpckhdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1288: Error: suffix or operands invalid for `vpunpcklqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1289: Error: suffix or operands invalid for `vpunpckhqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1290: Error: suffix or operands invalid for `vpunpcklqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1291: Error: suffix or operands invalid for `vpunpckhqdq'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1292: Error: no such instruction: `vperm2i128 $0x20,%ymm5,%ymm13,%ymm8'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1293: Error: no such instruction: `vperm2i128 $0x31,%ymm5,%ymm13,%ymm5'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1294: Error: no such instruction: `vperm2i128 $0x20,%ymm15,%ymm2,%ymm13'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1295: Error: no such instruction: `vperm2i128 $0x31,%ymm15,%ymm2,%ymm15'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1296: Error: no such instruction: `vperm2i128 $0x20,%ymm7,%ymm9,%ymm2'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1297: Error: no such instruction: `vperm2i128 $0x31,%ymm7,%ymm9,%ymm7'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1298: Error: no such instruction: `vperm2i128 $0x20,%ymm4,%ymm12,%ymm9'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1299: Error: no such instruction: `vperm2i128 $0x31,%ymm4,%ymm12,%ymm4'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1306: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1307: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1308: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1309: Error: suffix or operands invalid for `vpxor'
......

my build environment are:
the original gcc version is 4.4.7 。then I compile ans make install the gcc -4.8.5 with
----wget http://ftp.gnu.org/gnu/gcc/gcc-4.8.1/gcc-4.8.1.tar.gz
----tar -xvzf gcc-4.8.1.tar.gz
----cd gcc-4.8.1
----./contrib/download_prerequisites
----cd ..
----mkdir build_gcc_4.8.1
----cd build_gcc_4.8.1
       ../gcc-4.8.5/configure --enable-checking=release --enable-languages=c,c++ --disable-multilib  
       make -j23  && make install
----/usr/sbin/update-alternatives --install  /usr/bin/gcc gcc /usr/local/bin/x86_64-unknown-linux-gnu-gcc-4.8.5 40
----/usr/sbin/update-alternatives --install /usr/bin/g++ g++ /usr/local/bin/g++ 40

so the gcc version = 4.8.5,g++  version = 4.8.5。
and  my bazel version=0.4.5
libgomp  is libgomp-4.4.7-18.el6.x86_64 
binutils is binutils-2.20.51.0.2-5.47.el6_9.1.x86_64
libgcc is  libgcc-4.4.7-18.el6.x86_64
Please help me solve it , thank  you very much!

**Comment by daira** [comment]
This is likely because binutils is too old to support AVX instructions. Try upgrading to binutils 2.22 or newer.

**Comment by rothn** [comment]
Our cluster only supports binutils/2.2.5. Is that new enough?

**Comment by gautamvasudevan** [comment]
The dependencies are pretty specific (any variances aren't really guaranteed to work) - please see the latest [Docker examples](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) for bringing up a build environment.
