### ISSUE TITLE
Create smaller size shared libraries for deployed servers.

### ISSUE THREAD

**Issue by nfiedel** [tensorflow/serving#44]
[Per viksit](https://github.com/tensorflow/serving/issues/40)@: "the compiled version of the dependencies are almost 1.5G with tf taking up a lot of it."

Options:
1. Add a shared library. [Example in TensorFlow](https://github.com/tensorflow/tensorflow/pull/695).
2. Look at compilation options, e.g. -c opt.

**Comment by apollo-time** [comment]
How can I create smaller size shared library for use pre-trained tensorflow model,  for Android, iOS, Windows application?

**Comment by unclepeddy** [comment]
Closing as the size of the binary has been reduced significantly. Feel free to re-open if this is still an issue!
