### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by yiakwy** [tensorflow/serving#443]
Hello, I developed a new repository for people to use distributed tensorflow.
As part of choices, I provided "Dockerfile.devel" with some modification to resolve "Amazon signature request" error.

https://github.com/yiakwy/distributed-tensorflow

What should I do to acknowledge your work in License part. I prefer to use BSD license?

Thanks for your help !

**Comment by gautamvasudevan** [comment]
Please follow the instructions in the apache license.
