### ISSUE TITLE
Inference using pre-trained model on Tensorflow Serving taking almost 12 secs

### ISSUE THREAD

**Issue by ashavish** [tensorflow/serving#444]
I am using Google Cloud (4 CPU,15 GB RAM) to host tensorflow serving. The model is a pre-trained Resnet which I imported using Keras and converted to .pb format using SavedModelBuilder.I followed tensorflow serving installation and compilation steps as mentioned in the Tensorflow Serving installation docs.I did a bazel build using ..

> bazel build tensorflow_serving/...

Doing inference on an image from my local machine using python client, gave me results in approximately 23 secs.This I was able to fine tune a bit by following the advice here- https://github.com/tensorflow/serving/issues/401. Replaced the bazel build by 

> bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.2    //tensorflow_serving/model_servers:tensorflow_model_server

 to use CPU optimization. This brought the response time down to 12 secs.

Other stuff I tried which resulted in no difference to response times..
1. Increased 4 CPU to 8 CPU machine 
2. Tried on a GPU Tesla K80 + 4 CPU machine 

I haven't tried batch optimisation, as I am currently just testing it out with a single inference request. The configuration doesn't use  docker or Kubernettes.

Appreciate any pointers which can help in bringing down the inference times. Thanks !

**Comment by KernelSight** [comment]
Following this. What is the best parameter set to use if we expect to get about 1 request a second. We do not want to wait and batch requests initially. Does this mean that using a GPU will not help much? How can we estimate the inference time for a given model?

**Comment by ashavish** [comment]
Solved and closing this issue. Now am able to get a sub second prediction time. There were multiple problems. One was the image upload/download times which was playing a role. The second was when I was running using the GPU, it wasnt really using it. The GPU issue got resolved using two approaches outlined in these links - ttps://github.com/tensorflow/serving/issues/318 and https://github.com/tensorflow/tensorflow/issues/4841
