### ISSUE TITLE
Tensorflow serving retrained inception

### ISSUE THREAD

**Issue by Mdrbhatti** [tensorflow/serving#449]
I am trying to serve a retrained inception model, but haven't had luck for the past few days. Every question that relates to my situation has not been answered on stackoverflow or anywhere else. If anyone can help regarding this, I would be very grateful!
This question pretty much describes what I am trying to do.
http://stackoverflow.com/questions/38892976/tensorflow-serving-retrained-inception?rq=1

How are you actually supposed to export a retrained inception model so that it can be served? I have trouble understanding the whole exporting process in the retrain.py file. Similar to this: http://stackoverflow.com/questions/37237940/how-to-serve-the-tensorflow-graph-file-output-graph-pb-via-tensorflow-serving

Please help!

**Comment by chrisolston** [comment]
Based on the error message "FetchOutputs node : not found", it looks like the core issue is that the output node it's requesting from tensorflow is not found in the graph. So likely the signature and/or the inference request has the wrong output node name.

**Comment by nsahaytech** [comment]
I have written a small utility which helps in exporting a retrained inception model so that it can be served. If it adds value to the community, I would be happy to contribute.

**Comment by vitalyli** [comment]
Sounds good

**Comment by hecforga** [comment]
@nsahaytech Where can I find that utility you mention in your comment? It would be really useful for a project I'm working on.

**Comment by nsahaytech** [comment]
I would be sending the pull request soon.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jda91** [comment]
@nsahaytech Hey any hope of you posting that pull soon? Or could you show us how you did it :)? I have been stuck on this for a while and I'm really hoping to get my model up and running soon

**Comment by gmercey** [comment]
Hi @nsahaytech, I'm also interested by your utility. I not a PR, can you share it as a gist? Thank you

**Comment by ksindi** [comment]
Have a PR that shows how to do it: https://github.com/tensorflow/serving/issues/449

The client would look like:
```
from grpc.beta import implementations
import tensorflow as tf

from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2


tf.app.flags.DEFINE_string('server', 'localhost:9000', 'PredictionService host:port')
tf.app.flags.DEFINE_string('image', '', 'path to image in JPEG format')
FLAGS = tf.app.flags.FLAGS


def main(_):
    host, port = FLAGS.server.split(':')
    channel = implementations.insecure_channel(host, int(port))
    stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
    # Send request
    image = tf.gfile.FastGFile(image_path, 'rb').read()
    request = predict_pb2.PredictRequest()
    request.model_spec.name = 'inception'
    request.model_spec.signature_name = tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY
    request.inputs['image'].CopyFrom(tf.contrib.util.make_tensor_proto(data))
    result = stub.Predict(request, 10.0)  # 10 secs timeout
    print(result)


if __name__ == '__main__':
  tf.app.run()
```

**Comment by pgpgpg** [comment]
For anybody else who needs human readable class names in the output, change the outputs to the following, making sure to pass image_lists.keys() to `def export_model()`:

```
outputs = {'prediction': tf.saved_model.utils.build_tensor_info(out_classes),
             'classes': tf.saved_model.utils.build_tensor_info(tf.convert_to_tensor(list(keys))),}
```

Gist here:  https://gist.github.com/pgpgpg/9f212cba5c77bc9b49b14f6fd0b4868b

**Comment by heng2j** [comment]
Hi @ksindi,

I am new to Tensorflow serving, so will need some help on the client side. 
For the client you show, when use directly I see the following error. Can you advise? Is it possible that I can use the default inception_client.py?


    request.inputs['image'].CopyFrom(tf.contrib.util.make_tensor_proto(data))
NameError: global name 'data' is not defined

**Comment by heng2j** [comment]
Hi @ksindi 

No worries, I figured out that the data should be replace with the variable name image

Thank you so much for putting this PR.

**Comment by heng2j** [comment]
Hi @ksindi  and everyone, with this retrained inception, from the client end. How do we also show labels from the prediction? My goal is to get he  label with the highest accuracy.

And now my outputs just look like this. And suggestions?

outputs {
  key: "prediction"
  value {
    dtype: DT_FLOAT
    tensor_shape {
      dim {
        size: 1
      }
      dim {
        size: 4
      }
    }
    float_val: 0.0137002402917
    float_val: 0.0319225639105
    float_val: 0.869793236256
    float_val: 0.0845839455724
  }
}

**Comment by ksindi** [comment]
@heng2j this is what I did:

```
import json

from grpc.beta import implementations
from google.protobuf import json_format
import tensorflow as tf
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2

from inception.config import config


def request_score(image):
    channel = implementations.insecure_channel(config['SCORER_HOST'], int(config['SCORER_PORT']))
    stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
    with tf.gfile.Open(image, mode='rb') as f:
        # See prediction_service.proto for gRPC request/response details.
        data = f.read()
        data = tf.image.decode_jpeg(data, channels=3)
        request = predict_pb2.PredictRequest()
        request.model_spec.name = 'inception'
        request.model_spec.signature_name = tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY
        request.inputs['image_bytes'].CopyFrom(tf.contrib.util.make_tensor_proto(data))
        result = stub.Predict(request, 10.0)  # 10 secs timeout
        json_string = json_format.MessageToJson(result)
        d = json.loads(json_string)
        scores = d['outputs']['prediction']['floatVal']
        return scores
```

**Comment by heng2j** [comment]
Hi @ksindi 

Thank you for your quick response.

I see that you also used **from inception.config import config**

Do you know where I can get or generate this import as well?

Currently I received this error since I don't have inception.config
ImportError: No module named config

**Comment by ksindi** [comment]
Sorry the config import was from a personal project. You don't need it.

**Comment by heng2j** [comment]
Hi @ksindi ,

Thank you then I guess I will also need to modify the retrain.py to include the signature_def_map to  get the classes and scores

Currently with DEFAULT_SERVING_SIGNATURE_DEF_KEY I can only get scores but not the labels.

**Comment by heng2j** [comment]
Hi @pgpgpg 

No worries, I figured out that the on and off exceeded run time was due to multiple processes were running on port 9000. So it jammed

**Comment by ksindi** [comment]
The retrain script changed a bit where the input tensor name changed from `'DecodeJpeg/contents:0'` to `'Mul:0'`. So you have to decode the image and normalize the image first.

```
import tensorflow as tf
from grpc.beta import implementations
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2

tf.enable_eager_execution()

tf.app.flags.DEFINE_string('server', 'localhost:9000',
                           'PredictionService host:port')
tf.app.flags.DEFINE_string('image', '', 'path to image in JPEG format')
FLAGS = tf.app.flags.FLAGS


def read_tensor_from_image_file(file_name,
                                input_height=299,
                                input_width=299,
                                input_mean=0,
                                input_std=255):
    input_name = "file_reader"
    file_reader = tf.read_file(file_name, input_name)
    if file_name.endswith(".png"):
        image_reader = tf.image.decode_png(
            file_reader, channels=3, name="png_reader")
    elif file_name.endswith(".gif"):
        image_reader = tf.squeeze(
            tf.image.decode_gif(file_reader, name="gif_reader"))
    elif file_name.endswith(".bmp"):
        image_reader = tf.image.decode_bmp(file_reader, name="bmp_reader")
    else:
        image_reader = tf.image.decode_jpeg(
            file_reader, channels=3, name="jpeg_reader")
    float_caster = tf.cast(image_reader, tf.float32)
    dims_expander = tf.expand_dims(float_caster, 0)
    resized = tf.image.resize_bilinear(
        dims_expander, [input_height, input_width])
    normalized = tf.divide(tf.subtract(resized, [input_mean]), [input_std])

    return normalized


def main(args):
    host, port = FLAGS.server.split(':')
    channel = implementations.insecure_channel(host, int(port))
    stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
    # Send request
    image = read_tensor_from_image_file(FLAGS.image)

    request = predict_pb2.PredictRequest()
    request.model_spec.name = 'inception'
    request.model_spec.signature_name = tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY
    request.inputs['image'].CopyFrom(tf.contrib.util.make_tensor_proto(image))
    result = stub.Predict(request, 10.0)  # 10 secs timeout
    print(result)


if __name__ == '__main__':
    tf.app.run()
```

**Comment by BiondiVini** [comment]
Hi @ heng2j, I am currently working with this same purpose (show tags: values) in the retreine script and had to make some changes to get the tags in the result.  
First I pass ``image_lists.keys()`` from the ``main`` method to the ``export_model`` method, and construct the variable outpus with this:

```python
outputs = {  
    'classes': tf.saved_model.utils.build_tensor_info(tf.convert_to_tensor(list(labels))),  
    'prediction': tf.saved_model.utils.build_tensor_info(out_classes)  
}
```
On my client I can get they with:  
```python
prediction = result.outputs['prediction'].float_val
classes = result.outputs['classes'].string_val
```

**Comment by wt-huang** [comment]
Closing as this issue is resolved.
