### ISSUE TITLE
Documentation to develop code outside of tensorflow_serving namespace

### ISSUE THREAD

**Issue by viksit** [tensorflow/serving#46]
Currently, all docs point to simply building things within the tf serving directory. One issue with that is that there's not much information on how to position BUILD and .bzl files in a custom project, in say, a separate code repo than the TF serving's own git repo.

Specifically, 

- How do I include tensorflow_serving/servables/* into my own code without specifying visibility public in the BUILD files?
- Is there way to include tensorflow_serving as a prebuilt binary shared lib in the deps in a bazel BUILD file?

**Comment by fangweili** [comment]
What components do you need to extend? We are happy to open up visibility.
There's currently no plan to release as prebuilt binary.

**Comment by viksit** [comment]
@fangweili  How do you guys deploy a TF Serving system today? Do you simply build in one location, and then zip up and deploy to servers via Omega/K8s?

I see that most of the bazel-bin/ directories only use symlinks to the actual code and protos - how do I ensure that all dependencies are in fact physically located in one place without having to have all the code present as well? (See issue #44)

**Comment by viksit** [comment]
Re extending I wanted to extend `BasicManager` with something similar to aspired managers, and `periodic_function` seems to be a dependency. There are a few other things like that. Eg - extending `HashmapSourceAdapter` for the tutorial.

**Comment by fangweili** [comment]
I will submit a change to open up visibility of `BasicManager` and `HashmapSourceAdapter`. However I am curious of why you want to extend `BasicManager` with something similar to `AspiredVersionManager` - why not just use the latter?

**Comment by fangweili** [comment]
As for binary build -- currently we build in one location and zip up for deployment.

**Comment by viksit** [comment]
@fangweili the `AspiredVersionManager` is great - one issue is that it insists on having servable_name and version.servable_name be the same, which for me is an issue since I have multiple models. So I've restructured it for that purpose.

**Comment by fangweili** [comment]
visibility change submitted.

**Comment by vinuraja** [comment]
Viksit, why not call the SetAspiredVersionsCallback multiple times grouping together servables with the same name ? That would make it possible for you to use AspiredVersionsManager.
