### ISSUE TITLE
why "bazel build tensorflow_serving/example/..." command  doesn't generate mnist_inference file?

### ISSUE THREAD

**Issue by zhaochunhua** [tensorflow/serving#463]
I run two step:
1 ./configure
2.bazel build tensorflow_serving/example/...
The two steps are successful ,and don't have any errors but some warning.
In dictionary ./bazel-bin/tensorflow_serving/example/, there are mnist_client/ mnist_export/ mnist_saved_model and so on.
But  I can't find file "mnist_inference" file?

Who know why?

**Comment by zhaochunhua** [comment]
I can successfully run the command
"bazel-bin/tensorflow_serving/example/mnist_export --training_iteration=10000 --export_version=1 /tmp/mnist_export".

**Comment by kirilg** [comment]
The [tensorflow_serving/example](https://github.com/tensorflow/serving/tree/master/tensorflow_serving/example) folder doesn't have mnist_inference as a file or a build target, so it's not generated in the final bazel-bin output. We had it before but it was renamed so now you should use mnist_saved_model and mnist_client instead.

I think we have an outdated comment in setup.md that refers to mnist_inference. I'll update the documentation, sorry for the confusion.
