### ISSUE TITLE
How does *.ckpt file converted to *.pb file with labels.

### ISSUE THREAD

**Issue by aaronsarkissian** [tensorflow/serving#467]
As I followed this walkthrough [serving_inception](https://tensorflow.github.io/serving/serving_inception) a question arised for me that how does that checkpoint file convert to a graph.pb file.

The script which does it is the following:
`bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --output_dir=inception-export` 
which runes [this](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_saved_model.py) script.
So, I checked the output directory and I found the .pb file which were only 1.4MB and I couldnet find the labels file. By assuming that the normal trained graph is over 70MB plus one label file it is weird to have small file as 1.4MB.
Can someone explain this for me? Where does the huge graph.pb goes and where should i replace my own trained graph.pb.
Thanks

**Comment by lilao** [comment]
By .pb file, I assume you mean saved_model.pb? The saved_model.pb file is the serialized SavedModel message (tensorflow/tensorflow/core/protobuf/saved_model.proto). The variables and assets (if any) associated with the model should be under the same directory as saved_model.pb .

**Comment by aaronsarkissian** [comment]
@lilao I got my graph.pb from this tutorial: [Tensorflow for poets](https://www.google.am/url?sa=t&source=web&rct=j&url=https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/&ved=0ahUKEwjoyvTi6KnUAhXIuBQKHSVuDqMQFggbMAA&usg=AFQjCNG2TDplBTQZpt8GrfEnAT36GWn4Mw&sig2=qMzpCMra2hsOej9xK_kAmw).
Then started doing inception serving tutorial. So, know I have my graph.pb and the labels.txt. But as far I understood it needs something caled checkpoint (.ckpt) But I don't know how can i convert it or get that checkpoint.

**Comment by haiy** [comment]
@aaronsarkissian  ckpt file is the intermediate file of  model training, while pb is the special file for serving.Inception serving is some kind of confused. [mnist serving example](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_saved_model.py) is more clearly.Here is the [serving doc](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/serving_basic.md) more precisely.

**Comment by sukritiramesh** [comment]
To add, if exported as a SavedModel, the checkpoints should be available under the sub-directory called "variables/". Please see: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/README.md for more about SavedModel.

(Resolving for now; please feel free to reopen if required)
