### ISSUE TITLE
SignatureDefs and SavedModel

### ISSUE THREAD

**Issue by josauder** [tensorflow/serving#469]
I am wondering where I can find any Documentation regarding strict rules for SignatureDefs for Tensorflow serving. Concisely, I want to ask the following:

1) What is the point of the Signature Constants that are given? I realize that these are commonly used and reused and therefore are encouraged to use, but are there any real advantages of using them? 

2) Are there any repercussions to overriding the Signature Constant method names given? For example use the `tensorflow/serving/classify` method name while NOT using `classes` and `scores` as outputs?

3) In Tensorflow serving code it seems (main.cc) it seems that each predict_impl only registers 4 methods, namely the given Signature Constants. This makes it look like all custom method names are ignored. Am I misunderstanding something?

4) In the `mnist_saved_model` example, there is an example given for using the signature defs. What is the difference between the key given as `signature_def_map` and the `method_name` given to each signature?

**Comment by kirilg** [comment]
1. They are used to standardize signature and request formats so the server knows what to look for. Hopefully the answers below offer more insight as well.

2. The RPC handlers are expecting these constants, so for regress and classify, you should use the constants. For the example you mentioned, if the signature method_name is `tensorflow/serving/classify`, the input key should be `inputs` and the outputs can be either `classes` or `scores`, or both (but of course use the constants, not actual strings). You'll get a request time error if you use unexpected keys. Predict is more flexible so you can use any input/output keys as long as they make sense in your model and the request is built using the same keys. Predict is built to be more general, so it can use predict, regress, or classify signatures (method_names).

3. PredictionServiceImpl implements the gRPC service as defined by the proto. We have support for Regress, Classify, Predict, and MultiInference. If you have a custom API that expects a custom signature method_name, you'd need to provide an implementation of it.

4. The key in the `signature_def_map` is basically the name of the signature and can be anything you want. You can give it a descriptive name so if the same model can be used to predict different things, you can switch between then by changing the signature_name at request time. For example, one signature can be named "predicted_ctr" and another "predicted_cvr".
`method_name` is like the type of the signature, and is always one of `tensorflow/serving/classify`, `tensorflow/serving/regress`, `tensorflow/serving/predict`, at least for now.

**Comment by emamurho** [comment]
@kirilg  From consolidating  point 2 and 4, I gather there is currently no support for signatureDefs with arbitrary number of inputs and outputs ( e.g. 3 inputs and 4 outputs) Is my assumption correct? or may I use predict signature for this purpose?

**Comment by kirilg** [comment]
You can use `tensorflow/serving/predict` and the predict API for that case.

**Comment by hushuangwei** [comment]
@kirilg Can you give me some advices on how to build a service of encoder-decoder model? I am not sure the way to represent TensorInfor since the input length is not fixed. And which Signature Constants shall I choose? Thanks if you provide some related tutorial on RNN serving.

**Comment by sukritiramesh** [comment]
You can build tensor-info using the utils provided here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/utils_impl.py#L28

**Comment by sukritiramesh** [comment]
For more documentation in SignatureDefs, please see: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/signature_defs.md

(Resolving for now; feel free to reopen if required)
