### ISSUE TITLE
how can I convert saver.save() to exporting model

### ISSUE THREAD

**Issue by zhaozhichao4515** [tensorflow/serving#474]
When I use saver.save to save my model I got three file:
model-20170512-110547.ckpt-250000.data-00000-of-00001
model-20170216-091149.ckpt-250000.index 
model-20170216-091149.meta 

but the model exporting is:
|--save-model.pb
|--variable
|-- |--variables.data-00000-of-00001 
|-- |--variables.index

how can I convert it? some one can give me idea?

**Comment by kirilg** [comment]
TensorFlow `Saver` is used to save a checkpoint of your variables, but doesn't include other information needed for serving (like the MetaGraphDef).

A `SavedModelBuilder` is used to export your model to be used for serving, and that will generate the structure you mentioned (saved_model.pb, variables/, etc.) Take a look at the SavedModel documentation [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/README.md) to see how to export the files you want (specifically the usage section). You can also take a look at [this example](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_saved_model.py).

**Comment by sukritiramesh** [comment]
Resolving, please feel free to reopen if you have questions.

**Comment by zakariachatria** [comment]
what is the solution to convert saver().save to SavedModel ?
i can't creat SavedModel directly because i use tensorflow 0.9.0 and  there is no class called tf.saved_model.builder.SavedModelBuilder in this version .
help please !!!

**Comment by xu-song** [comment]
@kirilg 

1. what is `model-20170216-091149.meta` in the above case? Is it the `MetaGraphDef`?
1. will `tf.train.export_meta_graph` export `MetaGraphDef`?
1. Can TensorFlow `Saver` and `tf.train.export_meta_graph` work for serving?
