### ISSUE TITLE
tensorflow_model_server compilation error boringssl

### ISSUE THREAD

**Issue by Nukesor** [tensorflow/serving#475]
Hi!

I get an error during the compilation of the tensorflow_model_server on arch-linux.
It looks like a 64bit to 32bit cast error:

```
ERROR: /home/nuke/.cache/bazel/_bazel_nuke/6ec0d1215de4f75ec889540214e3c5dd/external/boringssl/BUILD:91:1: C++ compilation of rule '@boringssl//:crypto' failed: gcc failed: error executing command 
  (cd /home/nuke/.cache/bazel/_bazel_nuke/6ec0d1215de4f75ec889540214e3c5dd/execroot/serving && \
  exec env - \
    PATH=/home/nuke/work/neuro/solar/venv/bin:./bin:/home/nuke/.cargo/bin:/home/nuke/.scripts/:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/adobe-air-sdk/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/nuke/.screenlayout/:/home/nuke/.screenlayout/ \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/local-opt/bin/external/boringssl/_objs/crypto/external/boringssl/src/crypto/asn1/a_bitstr.d -iquote external/boringssl -iquote bazel-out/local-opt/genfiles/external/boringssl -iquote external/bazel_tools -iquote bazel-out/local-opt/genfiles/external/bazel_tools -isystem external/boringssl/src/include -isystem bazel-out/local-opt/genfiles/external/boringssl/src/include -isystem external/bazel_tools/tools/cpp/gcc3 -Wa,--noexecstack '-D_XOPEN_SOURCE=700' -Wall -Werror '-Wformat=2' -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -Wshadow -fno-common '-std=c11' -Wmissing-prototypes -Wold-style-definition -Wstrict-prototypes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/boringssl/src/crypto/asn1/a_bitstr.c -o bazel-out/local-opt/bin/external/boringssl/_objs/crypto/external/boringssl/src/crypto/asn1/a_bitstr.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from /usr/include/string.h:639:0,
                 from external/boringssl/src/crypto/asn1/a_bitstr.c:59:
In function 'memcpy',
    inlined from 'i2c_ASN1_BIT_STRING' at external/boringssl/src/crypto/asn1/a_bitstr.c:118:5:
/usr/include/bits/string3.h:53:10: error: '__builtin_memcpy': specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Target //tensorflow_serving/model_servers:tensorflow_model_server failed to build
INFO: Elapsed time: 34.578s, Critical Path: 8.33s
```
Any ideas where this error originates from? 
Maybe a local lib32? 

Used:
serving: master
tensorflow: 7fda1bb11

gcc version 7.1.1 20170516 (GCC) 
Python 3.6.1 (default, Mar 27 2017, 00:27:06)

**Comment by kirilg** [comment]
Sorry, I'm not sure. It's likely related to your local environment, we've never tested on arch-linux.

[This issue](https://github.com/grpc/grpc/issues/10843) seems to be relevant.

If it is indeed related to your environment, you might want to try running in a docker container - https://tensorflow.github.io/serving/docker

**Comment by Nukesor** [comment]
Thanks, I'll try to resolve it and maybe write a guide for arch users in our wiki.

Regarding the docker container setup:
I already managed to get a container up and running, but the docker container setup for tensorflow fails because of [this issue](https://github.com/tensorflow/serving/issues/114).
[File with line](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel#L64):
`curl -fSsL -o /bazel/LICENSE.txt https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE.txt`

There is a manual fix, but I hope the issue will be reopened :).

**Comment by kirilg** [comment]
Sounds good.

Regarding the Docker issue you mentioned, it should have been fixed in [this commit](https://github.com/tensorflow/serving/commit/5ffe1ac9215215443615cab11f16aab63913c41d), are you using the latest TF and do you see that change in your docker file?

**Comment by sathyamoorthyrr** [comment]
I'm facing the exact problem.
**OS:** Ubuntu Linux 18.04
**Tensorflow Serving(trying to build):** **1.3**
**gcc, g++ version:** (Ubuntu 7.3.0-16ubuntu3) 7.3.0
**Python:** 2.7.15

Could you find the solution?
Will changing the gcc, g++ version work?
