### ISSUE TITLE
TensorFlow Model Server returns incorrect results

### ISSUE THREAD

**Issue by amirj** [tensorflow/serving#476]
Following [tf-serving basic tutorial](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_saved_model.py), I'm training a simple neural net and save checkpoints occasionally:

```
// creating the model: placeholders, variables and etc.  
sess = tf.InteractiveSession()
// train for number of iterations
// saved the final checkpoint 
// saved the model by SavedModel
```

After training, I have a folder for saved checkpoints (`checkpoint_folder `) and a separate folder for [`SavedModel`](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/saved_model) (`saved_model_folder`). 

I'm sure that the model is completely trained because when I load the latest checkpoint and pass a sample data, it works perfectly but when serving the model in tf-serving, **the output results are completely incorrect**!

I found that the values of different variables are exactly the same between the latest checkpoint and the SavedModel. On the other hand, the outputs of these two snippets are exactly the same:

```
import tensorflow as tf
sess = tf.InteractiveSession()
saver = tf.train.import_meta_graph(
              '%s.meta' % tf.train.latest_checkpoint(checkpoint_folder))
saver.restore(sess, tf.train.latest_checkpoints(checkpoint_folder))
sess.run('weights:0')
```

```
import tensorflow as tf
from tensorflow.python.saved_model import tag_constants
from tensorflow.python.saved_model import loader
sess = tf.InteractiveSession()
tf.saved_model.loader.load(sess, [tag_constants.SERVING], saved_model_folder)
sess.run('weights:0')
```

What's the problem?
Is it possible that different graphs have been saved in the SavedModel and when I serve the model in tf-serving, it leverage the initial graph instead of well-trained graph?

How can I ensure the health of the generated SavedModel?

**Comment by chrisolston** [comment]
If the weights inside the SavedModel look right then I don't think the problem is inside SavedModel. The serving binary will automatically load/serve the latest version of the model, so be sure the highest version# in your source directory is the one you want to serve (i.e. the one with the correct weights).

If you have batching enabled, and something not batching compatible in your graph (e.g. something nondeterministic) you could get some weird outputs.

Other than that I can't think of other things to look into.

**Comment by amirj** [comment]
@chrisolston Thank you.
I just have a single version (SavedModel after the training).
Regarding batching, I just call the following command:
```
bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=my_model --model_base_path=../project/training/model_serving/
```
As I know, since I don't leverage `--enable_batching` in the above command, batching is disabled.

I compiled tf-serving with and without `cuda` option but it doesn't solve the problem.

I really dont know what I have to do! 
Everything seems ok but I dont know why serving returns incorrect results.

Any help?

**Comment by amirj** [comment]
Haaa, my fault, this was a bug in my code.

**Comment by EvenOldridge** [comment]
@amirj Can you provide any details on what the bug was and how you solved it?

**Comment by Atlas7** [comment]
Just to add (might or might not help) - one thing I've notice about TensorFlow is that it likes absolute path name (instead of relative path name). So, for things like `model_base_path`, instead of a relative path, use absolute path. For example `/tmp/helloworld/`. It got me previously.
