### ISSUE TITLE
What should I use *_export.py or *_saved_model.py

### ISSUE THREAD

**Issue by mahnunchik** [tensorflow/serving#479]
What should I use:
* mnist_saved_model.py or mnist_export.py
* inception_saved_model.py or inception_export.py

Files almost similar.

**Comment by chrisolston** [comment]
Please prefer the _saved_model ones, which is based on the newer SavedModel tensorflow graph serialization format. The _export ones are based on the older SessionBundle format, which is deprecated and will ultimately be removed.

**Comment by mahnunchik** [comment]
Hi @chrisolston thank you for the clarification.

It would be really helpful to have this information in files while they are present in the repository.

**Comment by sukritiramesh** [comment]
Sure, added a comment in both files:
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_export.py#L19
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_export.py#L20
