### ISSUE TITLE
DynamicManager in advanced serving tutorial renamed to AspiredVersionsManager?

### ISSUE THREAD

**Issue by viksit** [tensorflow/serving#48]
Unless I'm missing something in the advanced serving tutorial. 

It's there in commit https://github.com/tensorflow/serving/commit/3985fca728405140673c38d01a4e29c782834d70#diff-ca07f0e4bbb8e03072059aea8b5ce227, but seems to have moved since then.

/cc @fangweili

**Comment by viksit** [comment]
Also, looks like the tutorial may be out of date.

`  UniquePtrWithDeps<tensorflow::serving::Manager> manager` is the actual code, although it references `std::unique_ptr<DynamicManager> manager = ...;`

**Comment by fangweili** [comment]
Yes. It was renamed. I will update the tutorial doc.

**Comment by fangweili** [comment]
updated.
