### ISSUE TITLE
How to call Tensorflow Serving from Golang?

### ISSUE THREAD

**Issue by mauri870** [tensorflow/serving#485]
Hi, I'm trying to implement a tensorflow serving client specifically for the inception example.

What I have so far is:

```go
imageBytes, err := ioutil.ReadFile('image.jpg')
ImageTensor, err := tf.NewTensor(string(imageBytes))
if err != nil {
    ...
}
```
This tensor has a DType 0x7(DataType_DT_STRING)
Then I use `tensorString, ok := imageTensor.Value().(string)` to get the tensor value as string since `Value()` return an interface.

And the grpc request trying to mimic the python and c++ examples:
```go
request := &pb.PredictRequest{
	ModelSpec: &pb.ModelSpec{
		Name:          "inception",
		SignatureName: "predict_images",
		Version: &google_protobuf.Int64Value{
			Value: 1,
		},
	},
	Inputs: map[string]*tfframework.TensorProto{
		"images": &tfframework.TensorProto{
			Dtype: tfframework.DataType_DT_STRING,
			TensorShape: &tfframework.TensorShapeProto{
				Dim: []*tfframework.TensorShapeProto_Dim{
					&tfframework.TensorShapeProto_Dim{
						Size: int64(1),
					},
				},
			},
			TensorContent: []byte(tensorString),
		},
	},
}

resp, err := h.GrpcClient.Predict(context.Background(), request)
```

When I run the code I get the following error back:
```
rpc error: code = InvalidArgument desc = tensor parsing error: images
```

I can't see any related logs in the tensorflow serving container.

Edit: My problem seems to be related with this [piece of code](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/servables/tensorflow/predict_impl.cc#L187-L190). Any workround to get a valid proto tensor from Go?

**Comment by mauri870** [comment]
Got it 😓 
I change `TensorContent: []byte(tensorString),` to `StringVal: [][]byte{[]byte(tensorString)},` and its working like a charm

Can I add a golang client to the examples folder?

**Comment by grafael** [comment]
For instance, @mauri870  could you share the client code in a gist ?

**Comment by mauri870** [comment]
Yes, sure. See this [gist](https://gist.github.com/mauri870/1f953a183ee6c186e70a0a72e78b088c)

You need to follow the tensorflow instructions for go and compile the proto files as described in the gist

**Comment by grafael** [comment]
Thanks @mauri870 !!

**Comment by JaxSONG** [comment]
I have `Tensor,DataType:0x1,shape:[]int64{28, 28, 1}` , and how can i call grpc witch request, Inputs paraemeter how to write 




 
    request := &pb.PredictRequest{
        ModelSpec: &pb.ModelSpec{
          Name:          "mnist",
          SignatureName: "predict_images",
          Version: &google_protobuf.Int64Value{
            Value: int64(1),
          },  
        },  
        Inputs: map[string]*tf_core_framework.TensorProto{
          "images": &tf_core_framework.TensorProto{
            Dtype: tf_core_framework.DataType_DT_FLOAT,
            TensorShape: &tf_core_framework.TensorShapeProto{
              Dim: []*tf_core_framework.TensorShapeProto_Dim{
                &tf_core_framework.TensorShapeProto_Dim{
                  Size:28 ,
                },  
                
                &tf_core_framework.TensorShapeProto_Dim{
                  Size: 28,
                },  
                
                &tf_core_framework.TensorShapeProto_Dim{
                  Size: 1,
                },  
              },  
            },  
            FloatVal: tensor.Value(),
          },  
        },  
    }
  
tensor.Value() type is [][][]float32, how can i transfrom the [][][]float32 tensor value to []float32?

**Comment by JaxSONG** [comment]
@mauri870

**Comment by orian** [comment]
Is it possible / how to generate protos using `bazel`?

**Comment by mauri870** [comment]
Updated version [here](https://mauri870.github.io/blog/posts/tensorflow-serving-inception-go)

:smile:

**Comment by frpunzalan** [comment]
@mauri870 
Thanks for the tutorial.
I tried building the go inception-client in your tutorial but I ran into this error:
vendor/tensorflow_serving/apis/prediction_log.pb.go:9:8: cannot find package "tensorflow_serving/core" in any of:
/home/../vendor/tensorflow_serving/core (vendor tree)
/usr/local/go/src/tensorflow_serving/core (from $GOROOT)

Any idea what is causing this error?

**Comment by mauri870** [comment]
@frpunzalan What commands are you running to compile the proto files? Honestly I didn't test against the 1.8 version.

**Comment by frpunzalan** [comment]
I tried protocol buffers v3.5 and 3.6 and using the latest golang version (1.10). Can you tell me which versions are you using? thanks

**Comment by mauri870** [comment]
I was able to generate the protobufs using tensorflow and serving branch r1.7 and golang 1.10, protoc 3.5.1

**Comment by mauri870** [comment]
Unfortunately I can't build with latest r1.8 tf / serving branch.

But the following is working for the r1.7 branch:

```bash
PROTOC_OPTS='-I lib/tensorflow -I lib/serving --go_out=plugins=grpc:vendor'

eval "protoc $PROTOC_OPTS lib/serving/tensorflow_serving/apis/*.proto"
eval "protoc $PROTOC_OPTS lib/serving/tensorflow_serving/config/*.proto"
eval "protoc $PROTOC_OPTS lib/serving/tensorflow_serving/util/*.proto"
eval "protoc $PROTOC_OPTS lib/serving/tensorflow_serving/sources/storage_path/*.proto"
eval "protoc $PROTOC_OPTS lib/tensorflow/tensorflow/core/framework/*.proto"
eval "protoc $PROTOC_OPTS lib/tensorflow/tensorflow/core/example/*.proto"
eval "protoc $PROTOC_OPTS lib/tensorflow/tensorflow/core/lib/core/*.proto"
eval "protoc $PROTOC_OPTS lib/tensorflow/tensorflow/core/protobuf/{saver,meta_graph}.proto"
```

**Comment by frpunzalan** [comment]
great! got it working with tf /serving branch 1.7. Thanks
Hopefully they fix that in later versions soon.

**Comment by wt-huang** [comment]
This is likely a sync issue.

**Comment by azer** [comment]
Serving works, but I can't compilete tensorflow/core/framework. It fails with following error message;

```
2019/07/06 00:45:24 protoc-gen-go: error:inconsistent package import paths: "github.com/tensorflow/tensorflow/tensorflow/go/core/framework", "tensorflow/core/framework"
--go_out: protoc-gen-go: Plugin failed with status code 1.
```

**Comment by eulerwang** [comment]
@JaxSONG ,loop image into a slice , slice is []float32 type , size is  28*28*1

**Comment by filipecosta90** [comment]
@azer regarding the error:
`protoc-gen-go: error:inconsistent package import paths: "github.com/tensorflow/tensorflow/tensorflow/go/core/framework", "tensorflow/core/framework"`

if you do in this manner you avoid it:
```

$ PROTOC_OPTS=' -I serving --go_out=plugins=grpc:vendor'
$ protoc $PROTOC_OPTS serving/tensorflow_serving/apis/*.proto
$ protoc $PROTOC_OPTS serving/tensorflow_serving/config/*.proto
$ protoc $PROTOC_OPTS serving/tensorflow_serving/util/*.proto
$ protoc $PROTOC_OPTS serving/tensorflow_serving/sources/storage_path/*.proto
$ PROTOC_OPTS=' -I tensorflow --go_out=plugins=grpc:vendor'
$ protoc $PROTOC_OPTS tensorflow/tensorflow/core/framework/*.proto
$ protoc $PROTOC_OPTS tensorflow/tensorflow/core/example/*.proto
$ protoc $PROTOC_OPTS tensorflow/tensorflow/core/lib/core/*.proto
$ protoc $PROTOC_OPTS tensorflow/tensorflow/core/protobuf/{saver,meta_graph}.proto

```

**Comment by filipecosta90** [comment]
@azer if you use up to [v1.13.2](https://github.com/tensorflow/tensorflow/tree/v1.13.2) you should be able to run:
`protoc $PROTOC_OPTS tensorflow/tensorflow/core/framework/*.proto`

**Comment by ledaiduongvnth123456** [comment]
> @JaxSONG ,loop image into a slice , slice is []float32 type , size is 28_28_1

@eulerwang : How can i do with an color image ? I did that, but it seems incorrect :+1: 
`
inputTensorValues := make([]float32, 3*160*160)
	for i := 0; i < 160; i++ {
		for j := 0; j < 160; j++ {
			r, g, b, _ := Image.At(i, j).RGBA()
			inputTensorValues[i*160 + j] = float32(r/255)
			inputTensorValues[i*160 + j + 1] = float32(g/255)
			inputTensorValues[i*160 + j + 2] = float32(b/255)
		}
	}
`

**Comment by AlexanderJLiu** [comment]
[This](https://github.com/AlexanderJLiu/tensorflow-serving-api/tree/master/golang) could be help for anyone who want to generate tensorflow serving api for go step by step.

https://github.com/AlexanderJLiu/tensorflow-serving-api/blob/ae6d50b421bc84286e608f4eb004506482c6d953/golang/main.go#L23-L47

**Comment by haruyama480** [comment]
I was also confused when handling multi-dementional array as well as @jaxsongqd and @ledaiduongvnth123456.

> how can i transfrom the [][][]float32 tensor value to []float32?

In conclusion, Given a shape of multi-dementional array
```
[I,J,K]
```
We need to construct a one-dimensional array with the following index in `FloatVal `, `StringVal` or etc.
```
i*(J*K) + j*(K) + k
```

Some tests in tensorflow would be good examples.
https://github.com/tensorflow/tensorflow/blob/0b6b491d21d6a4eb5fbab1cca565bc1e94ca9543/tensorflow/core/framework/tensor_test.cc#L940-L954

This ordering is also observed when interacting with python
```
>>> import tensorflow as tf
>>> tf.__version__
'2.8.0'
>>> t = tf.constant(["hello", "world", "machine", "learning", "new", "york"], dtype="string",shape=[3,2])
>>> t
<tf.Tensor: shape=(3, 2), dtype=string, numpy=
array([[b'hello', b'world'],
       [b'machine', b'learning'],
       [b'new', b'york']], dtype=object)>
>>> t[0,1]
<tf.Tensor: shape=(), dtype=string, numpy=b'world'>
```
