### ISSUE TITLE
Does TensorFlow Serving work on MacOS 10.12.* or 10.13.*?

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/serving#487]
I saw the following issue from last year but wasn't sure if the status had been updated:

https://github.com/tensorflow/serving/issues/1

Has anything changed since the instructions are for the Linux machines?

**Comment by SeanYanxml** [comment]
I build it on mac yesterday, but failed. I  recommend to use docker .
For more to read this article. https://tensorflow.github.io/serving/docker

**Comment by shyamalschandra** [comment]
Anyone else with some ideas of the exact `brew` installation packages to installation before using bazel to install tensorflow_serving?

**Comment by SeanYanxml** [comment]
@shyamalschandra  As you can see in #1 .
It has a bug in Mac OSX system. It is not the bug of bazel or tensorflow serving.
So , maybe we can not to compile it on Mac OSX sysetm until the bug has been fixed. The content of bug as follow: 
>  Shaikjalal commented on 26 Jun 2016
>  I have issues compiling serving on mac, i guess its still not supported for mac.
tensorflow_serving/core/test_util/BUILD:52:1: C++ compilation of rule '//tensorflow_serving/core/test_util:fake_loader' failed: osx_cc_wrapper.sh failed: error executing command external/bazel_tools/tools/cpp/osx_cc_wrapper.sh '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote ... (remaining 101 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from tensorflow_serving/core/test_util/fake_loader.cc:16:
./tensorflow_serving/core/test_util/fake_loader.h:59:10: error: thread-local storage is not supported for the current target
static thread_local bool was_deleted_in_this_thread_;
^
tensorflow_serving/core/test_util/fake_loader.cc:24:1: error: thread-local storage is not supported for the current target
thread_local bool FakeLoader::was_deleted_in_this_thread_;
^
2 errors generated.
INFO: Elapsed time: 1583.096s, Critical Path: 1409.25s

**Comment by terryKing1992** [comment]
please try this [#Issue389](https://github.com/tensorflow/serving/issues/389) solution;
