### ISSUE TITLE
I followed the instructions on tensorflow/serving website and it is taking forever and gets stuck?

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/serving#490]
What is going on?  Anyone have a clue?

**Comment by mountaintom** [comment]
Taking forever -- Normal. 

Over time the reasons for getting stuck have varied. For a while many of the getting stuck issues revolved around limiting the memory resources needed by the build. As of late, more of the issues have revolved around needing to make corrections to build.

Example threads are:
https://github.com/tensorflow/serving/issues/379
https://github.com/tensorflow/serving/issues/482

Try Googling the last part of your error messages and see if you get any hits.

**Comment by chrisolston** [comment]
Thanks for the info & pointers, @mountaintom. Closing this issue.
