### ISSUE TITLE
Does Tensorflow  serving support tf.py_func

### ISSUE THREAD

**Issue by iswaverly** [tensorflow/serving#495]
I encountered the same problem as in [""](https://github.com/tensorflow/serving/issues/54). Unfortunately, the issue is closed without fine solution.
As is mentioned, "Tensorflow Serving supports only C++." As far as I am concerned, the model is actually run on tensorflow. And the tensorflow support python defined Op. The is no reason that serving does not support it.
And is there any solution to it?
@fangweili , why using SessionBundle can solve it?

**Comment by Multihuntr** [comment]
... does it?

**Comment by kirilg** [comment]
TensorFlow Serving supports ~everything available in TF in C++. py_func does not work in TF in a C++ environment, but there might be some effort on the TF side to add support for it in the future.
