### ISSUE TITLE
tensorflow serving: confusion on feature_configs data format

### ISSUE THREAD

**Issue by robi56** [tensorflow/serving#497]
I have followed the tensorflow serving tutorial [mnist_saved_model.py][1]
 and try to train and export a text-cnn-classifier model 
The pipeline is 

    *embedding layer -> cnn->maxpol->cnn->dropout->output layer     

Tensorflow data input : 

    data_in = tf.placeholder(tf.int32,[None, sequence_length] , name='data_in')

transformed to 

      serialized_tf_example = tf.placeholder(tf.string, name='tf_example')
      feature_configs = {'x': tf.FixedLenFeature(shape=[sequence_length], dtype=tf.int64),}
      tf_example = tf.parse_example(serialized_tf_example, feature_configs)
      data_in = tf.identity(tf_example['x'], name='x')  # use tf.identity() to assign name

This works for training phase 
but at test time 
it tells 
**AbortionError(code=StatusCode.INVALID_ARGUMENT, details="Expects arg[0] to be int64 but string is provided")**

I am confused about the above line 

     feature_configs = {'x': tf.FixedLenFeature(shape=[sequence_length], dtype=tf.int64),}

I changed the line to 
   

      feature_configs = {'x': tf.FixedLenFeature(shape=[sequence_length], dtype=tf.string),}
but it gives the following error at training time:
 

    Traceback (most recent call last):
      File "/serving/bazel-bin/tensorflow_serving/example/twitter-sentiment-cnn_saved_model.runfiles/tf_serving/tensorflow_serving/example/twitter-sentiment-cnn_saved_model.py", line 222, in <module>
        embedded_chars = tf.nn.embedding_lookup(W, data_in)
      File "/serving/bazel-bin/tensorflow_serving/example/twitter-sentiment-cnn_saved_model.runfiles/org_tensorflow/tensorflow/python/ops/embedding_ops.py", line 122, in embedding_lookup
        return maybe_normalize(_do_gather(params[0], ids, name=name))
      File "/serving/bazel-bin/tensorflow_serving/example/twitter-sentiment-cnn_saved_model.runfiles/org_tensorflow/tensorflow/python/ops/embedding_ops.py", line 42, in _do_gather
        return array_ops.gather(params, ids, name=name)
      File "/serving/bazel-bin/tensorflow_serving/example/twitter-sentiment-cnn_saved_model.runfiles/org_tensorflow/tensorflow/python/ops/gen_array_ops.py", line 1179, in gather
        validate_indices=validate_indices, name=name)
      File "/serving/bazel-bin/tensorflow_serving/example/twitter-sentiment-cnn_saved_model.runfiles/org_tensorflow/tensorflow/python/framework/op_def_library.py", line 589, in apply_op
        param_name=input_name)
      File "/serving/bazel-bin/tensorflow_serving/example/twitter-sentiment-cnn_saved_model.runfiles/org_tensorflow/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
        ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
    TypeError: Value passed to parameter 'indices' has DataType string not in list of allowed values: int32, int64

  [1]: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_saved_model.py

**Comment by wenfeixiang1991** [comment]
I totally don't understand what
 `feature_configs = {'x': tf.FixedLenFeature(shape=[sequence_length], dtype=tf.int64),}`
  ` tf_example = tf.parse_example(serialized_tf_example, feature_configs)`
means?
do you figure out what input/output looks like in this function? I thought it just a data pre-process way to process images problem, but I noticed your problem is a text classify problem which you want do deal with it using CNN model, so your input is string right?
This is how I do it with cnn in TF-serving:
`# Placeholders for input, output and dropout

        self.input_x = tf.placeholder(tf.string, [None], name="input_x")
        self.input_y = tf.placeholder(tf.float32, [None, num_classes], name="input_y")
        self.dropout_keep_prob = tf.placeholder(tf.float32, name="dropout_keep_prob")
        #self.dropout_keep_prob = tf.constant(0.5)
        # Keeping track of l2 regularization loss (optional)
        l2_loss = tf.constant(0.0)`

        # load vocabubary to word index and Map data into vocabulary
        table = lookup.index_table_from_file(vocabulary_file = vocab_path, num_oov_buckets=1, default_value=-1)
    
        sentences_words = tf.string_split(self.input_x)
        
        # 稀疏矩阵转换为稠密矩阵 填充为 default_value 维数与输入维数一致
        dense_sentences_words = tf.sparse_tensor_to_dense(sentences_words, default_value = PADWORD)
        
        dense_sentences_words_num_index = table.lookup(dense_sentences_words)
    
        padding = tf.constant([[0,0],[0, sequence_length]])
        
        padded = tf.pad(dense_sentences_words_num_index, padding)
        
        self.dealed_input_x = tf.slice(padded, [0,0], [-1, sequence_length])`

**Comment by JoelGooch** [comment]
@wenfeixiang1991  

Could you please help out with a full example of how to create a servable using a placeholder that takes string as input? I am trying to serve the model found in this tutorial: https://www.oreilly.com/learning/perform-sentiment-analysis-with-lstms-using-tensorflow

Your help is much appreciated!

**Comment by firewu** [comment]
@JoelGooch I also quite confuse about how to create a servable using a placeholder that takes string as input,how did you solve it? Thks!

**Comment by vitalyli** [comment]
Here is basic string example, (if your graph had x_strings tensor), the rest would look like this:

            x_strings = tf.placeholder(tf.string, [None])

            builder = saved_model_builder.SavedModelBuilder(export_path)

            tensor_info_y = tf.saved_model.utils.build_tensor_info(y)

            x1 = tf.saved_model.utils.build_tensor_info(x_strings)
        
            classification_signature = (
                tf.saved_model.signature_def_utils.build_signature_def(
                        inputs={
                            tf.saved_model.signature_constants.CLASSIFY_INPUTS: x1
                            
                        },
                        outputs={
                            tf.saved_model.signature_constants.CLASSIFY_OUTPUT_SCORES:
                                tensor_info_y
                        },
                        method_name=tf.saved_model.signature_constants.CLASSIFY_METHOD_NAME))

            prediction_signature = (
                tf.saved_model.signature_def_utils.build_signature_def(
                        inputs={'x_strings': x1},
                        outputs={'scores': tensor_info_y},
                        method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME))

            legacy_init_op = tf.group(tf.tables_initializer(), name='init_op')

            builder.add_meta_graph_and_variables(
                    sess, [tf.saved_model.tag_constants.SERVING],
                    signature_def_map={
                        'predict_click':
                            prediction_signature,
                        tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:
                            classification_signature,
                    },
                    legacy_init_op=legacy_init_op)

            sess.graph.finalize()
            builder.save(as_text=False)

**Comment by firewu** [comment]
@vitalyli Thank you very munch! I fellow the advice you given,it works now.I was lost at first,because I thought the serving side input should be serialized,it turns out that I was misunderstand.
       But I met anthor strange problem:the same input got the different output scores and values of top 5  when predict,any advice may be much appreciated!
