### ISSUE TITLE
Are there ways to make the tensorflow-serving verbose so you know what is going?

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/serving#501]
Is there a -v command for tensorflow-serving when using with bazel?

**Comment by mountaintom** [comment]
The option "--verbose_failures" provides some additional information when when he build fails. Example below:

 bazel  build --jobs 1 --local_resources 5000,1.0,1.0  --verbose_failures tensorflow_serving/... 

You might want to try the other options on this example command line, as they will help if you have limited RAM available.

**Comment by chrisolston** [comment]
Thanks @mountaintom!
