### ISSUE TITLE
Multiple GPUs yield different result as single GPU for same model training

### ISSUE THREAD

**Issue by CHELSEA234** [tensorflow/serving#507]
I am newbie in Tensorflow, I am doing a project that requires for training on multiple GPUs, following example here: [https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/5_MultiGPU/multigpu_basics.py](url)
I did many experiments and I met some problem I couldn't figure out! 

**Q1**. If I split data, each GPU( two in total) gets one half, the training result would be different with result I got when I trained model on single GPU for whole data. I attached my code snippet after my result.
![single_node_3](https://user-images.githubusercontent.com/24967323/27663560-cbae9d4a-5c17-11e7-97e4-a68a00d70f4c.png)
![two_node_2](https://user-images.githubusercontent.com/24967323/27663564-d0d2797c-5c17-11e7-97a8-7c03856231b7.png)
**Single GPU:**
![single_device](https://user-images.githubusercontent.com/24967323/27663686-7609b176-5c18-11e7-97e1-8c4637c74682.png)
![single_device_1](https://user-images.githubusercontent.com/24967323/27663687-760d62e4-5c18-11e7-8946-9c6fb5422a41.png)
**Two GPUs:**
![two_node](https://user-images.githubusercontent.com/24967323/27663699-7d60458e-5c18-11e7-92ac-57b48996bf88.png)
![two_node_1](https://user-images.githubusercontent.com/24967323/27663700-7d62b634-5c18-11e7-8a57-eedf4ef6b84d.png)

Q2: Here is what I did to compare my 'orignial' and 'device claim' methods. In 'original', I don't specify what device should be used in different process( code without 'with tf.device('...') '). Why are running speeds so different with these two, all results I did are from one hour training time, 'original' one is as fast as when I used two GPUs speed, but result is way better.
'Original':
![single_node_1](https://user-images.githubusercontent.com/24967323/27663964-dae46cfc-5c19-11e7-8038-42511822473a.png)
![single_node_2](https://user-images.githubusercontent.com/24967323/27663963-dae0aa04-5c19-11e7-8db8-e3f758fe78ab.png)
![single_node](https://user-images.githubusercontent.com/24967323/27663932-b110f38c-5c19-11e7-8d2c-36983329dd55.png)

**Comment by CHELSEA234** [comment]
I think the answer to first question is like [https://stackoverflow.com/questions/43221730/tensorflow-same-code-but-get-different-result-from-cpu-device-to-gpu-device](url), but I am not very sure about this. I tried to print out loss_1 loss_2 for two separate parts, I got Nan.
For the second question I ask, I think it might be cpu shouldn't be assigned calcualtion job? I have no idea here...
@Derek Murray, I think you are really good, can you help out here?

**Comment by kirilg** [comment]
This appears to be a TensorFlow question not related to Serving, please ask this on TensorFlow's stackoverflow page.

**Comment by CHELSEA234** [comment]
@kirilg 
really sorry, but why I can't ask this question here? :( 
I think some same question can be posted here...

**Comment by kirilg** [comment]
Unless I'm mistaken, this is a training question and not related to serving. This is the Tensorflow/serving repo, which is different from core [TensorFlow](https://github.com/tensorflow/tensorflow), which is maintained by different teams.
