### ISSUE TITLE
No prediction_service_pb2 file

### ISSUE THREAD

**Issue by mathetes87** [tensorflow/serving#509]
Hi, I'm trying to send a request to a custom model. I've successfully loaded the model with tensorflow serving, but I'm having difficulties in testing the server.

I run the following commands:
```bash
(edge) mathetes@JR-Toth-Mint ~/serving $ bazel build //tensorflow_serving/apis:predict_proto_py_pb2
WARNING: /home/mathetes/.cache/bazel/_bazel_mathetes/95cb65ea68c2ada9e41b539c283c8b43/external/org_tensorflow/tensorflow/workspace.bzl:147:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
INFO: Found 1 target...
Target //tensorflow_serving/apis:predict_proto_py_pb2 up-to-date:
  bazel-genfiles/tensorflow_serving/apis/predict_pb2.py
INFO: Elapsed time: 0.219s, Critical Path: 0.02s
(edge) mathetes@JR-Toth-Mint ~/serving $ bazel build //tensorflow_serving/apis:prediction_service_proto_py_pb2
WARNING: /home/mathetes/.cache/bazel/_bazel_mathetes/95cb65ea68c2ada9e41b539c283c8b43/external/org_tensorflow/tensorflow/workspace.bzl:147:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
INFO: Found 1 target...
Target //tensorflow_serving/apis:prediction_service_proto_py_pb2 up-to-date (nothing to build)
INFO: Elapsed time: 0.206s, Critical Path: 0.02s
```

The files were successfully generated, but when I try to run code based on the official [inception_client example](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_client.py) I get this error:

```bash
(edge) mathetes@JR-Toth-Mint ~/Desktop/SVHN/Redes/modelos_finales $ python test_serving.py Traceback (most recent call last):
  File "test_serving.py", line 12, in <module>
    from tensorflow_serving.apis import prediction_service_pb2
ImportError: cannot import name prediction_service_pb2
```

![serving_apis_files](https://user-images.githubusercontent.com/13398475/27701318-8120bc7e-5cce-11e7-9177-b835a6f2f5c2.png)

I'm running the latest version of tensorflow serving, synced today and installed from source.

Thanks!

**Comment by kirilg** [comment]
Running `python test_serving.py` is not sufficient to pick up all the necessary dependencies and it will fail to find the right modules (e.g. prediction_service_pb2). You'll want to use bazel to run your target like we do in the [inception example](https://tensorflow.github.io/serving/serving_inception).

```
bazel build tensorflow_serving/example:inception_client
bazel-bin/tensorflow_serving/example/inception_client --server=localhost:9000 --image=/path/to/my_cat_image.jpg
```

You'll just want to change to your client, and add the corresponding target to the BUILD file like we have for [inception_client](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/BUILD#L92)

**Comment by mathetes87** [comment]
Thanks for your reply, I've been trying to do what you say, but I'm still confused, sorry...
What do you mean with 

> You'll just want to change to your client, and add the corresponding target to the BUILD file like we have for inception_client

I tried changing the BUILD file, but I don't know what I should change and what I should leave as it is. Basically I tried replacing every "inception" string with "regression" as that is the name of my custom model, but I get this error:

```bash
(edge) mathetes@JR-Toth-Mint ~/serving $ bazel build tensorflow_serving/apis:regression
WARNING: /home/mathetes/.cache/bazel/_bazel_mathetes/95cb65ea68c2ada9e41b539c283c8b43/external/org_tensorflow/tensorflow/workspace.bzl:147:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
ERROR: no such target '//tensorflow_serving/apis:regression': target 'regression' not declared in package 'tensorflow_serving/apis' (did you mean 'regressor'?) defined by /home/mathetes/serving/tensorflow_serving/apis/BUILD.
INFO: Elapsed time: 0.062s
```

Is there another file I should generate/copy to the apis's folder?

Maybe I'm even approaching this the wrong way... I just want to set up a REST api in a server with the model. Is this the path I should take? To receive the call and in turn call the model through a script that would use the file generated here? Or is there an easier/simpler way?

Thank you very much for your help. I feel helpless with the scarce documentation I find online!

**Comment by Kingeng** [comment]
@mathetes87

Hi, I want to serve my own model
but same issue can you help me ..

ls output on api directory : 
classification_pb2.py      inference_pb2.py  model_pb2.py    regression_pb2.py
get_model_metadata_pb2.py  input_pb2.py      predict_pb2.py

**Comment by kirilg** [comment]
What command were you running? Did you use an approach similar to the codelabs? [basic](https://www.tensorflow.org/serving/serving_basic) and [inception](https://www.tensorflow.org/serving/serving_inception).

You shouldn't need to fiddle with the api protos, you can just use bazel commands to export your model (e.g. mnist_saved_model.py) and to query a loaded model (e.g. bazel-bin/tensorflow_serving/example/mnist_client ...)

**Comment by Kingeng** [comment]
Thanks for your reply

For now i only have access to extracted model & docker image
source is in university pc and no remote acces

for serve it i follow tensorflow website & https://medium.com/zendesk-engineering/how-zendesk-serves-tensorflow-models-in-production-751ee22f0f4b

can you tell me what should i do ?

**Comment by kirilg** [comment]
I'm not sure what is the exact issue you're encountering. I would recommend you follow the tutorials I linked to and report any issues. If you already have a model exported in the SavedModel format, you can skip the first part (e.g. running mnist_saved_model.py in the basic tutorial) and continue with bringing up a ModelServer and sending RPCs with your client.

**Comment by haotianteng** [comment]
Hi I am try to serving my own model as well, and I adopt your suggestion by change the mnist BUILD file into a custom BUILD file which describe the dependency(see below) for bazel to compile, however when I compile it using bazel under the serving folder:
bazel build //absolute-path-to-my-package:my_client, 
it reports the error that BUILD file can't be found, but it's just in the package folder. 
After I copying my whole package to the tensorflow_serving folder solve the problem, now it can be correctly compiled.

But this is annoying as the absolute path does not work, any idea how I can using the existed configuration in the tensorflow_serving folder but make the bazel build to correctly detect the BUILD file in the package path?

# Description: Tensorflow Serving examples.

package(
    default_visibility = ["//tensorflow_serving:internal"],
    features = ["no_layering_check"],
)

licenses(["notice"])  # Apache 2.0

load("//tensorflow_serving:serving.bzl", "serving_proto_library")

filegroup(
    name = "all_files",
    srcs = glob(
        ["**/*"],
        exclude = [
            "**/METADATA",
            "**/OWNERS",
        ],
    ),
)

py_library(
    name = "chiron_eval",
    srcs = ["chiron_eval.py"],
    srcs_version = "PY2AND3",
)
py_library(
    name = "chiron_input",
    srcs = ["chiron_input.py"],
    srcs_version = "PY2AND3",
)
py_library(
    name = "raw",
    srcs = ["utils/raw.py"],
    srcs_version = "PY2AND3",
)
py_library(
    name = "easy_assembler",
    srcs = ["utils/easy_assembler.py"],
    srcs_version = "PY2AND3",
)

py_binary(
    name = "chiron_client",
    srcs = [
        "chiron_client.py",
    ],
    srcs_version = "PY2AND3",
    deps = [
        ":chiron_eval",
	":chiron_input",
	":raw",
	":easy_assembler",
        "//tensorflow_serving/apis:predict_proto_py_pb2",
        "//tensorflow_serving/apis:prediction_service_proto_py_pb2",
        "@org_tensorflow//tensorflow:tensorflow_py",
    ],
)

**Comment by david30907d** [comment]
@Kingeng `pip install tensorflow-serving-api` works for me~
