### ISSUE TITLE
Changing python bin after tree build

### ISSUE THREAD

**Issue by Jflima92** [tensorflow/serving#512]
Hi, 

I've built tensorflow serving using bazel in a aws instance, and all tests pass successfully.
But when I try to run the mnist example using:
` bazel-bin/tensorflow_serving/example/mnist_saved_model /tmp/mnist_model`
I get and error saying that it cannot find mock.
I've checked pip and pip3 and both have mock 2.0.0 installed.
I've already tried to reinstall with no success.

Was someone able to fix this issue?

EDIT:
I've found that python2.7 does not have mock installed, even if I pip install it installs in the 3.5 dist-packages. I initially configured  tensorflow to point to python2.7. Is there a way to point tensorflow to other python bin after building? Or should I rebuild after rerun ./configure? (I really don't want to rebuild because it took a long time to build in this instance)

**Comment by csscaps** [comment]
Same error!

**Comment by kirilg** [comment]
mock is available for python 2.7 - https://pypi.python.org/pypi/mock
I have it installed and I use 2.7, so it should work.

If you changed python versions half way through, you'll need to rerun ./configure and probably will need to recompile. My guess is that it will only need to recompile some python deps, so the second the time around it should be much faster, though this is really not the normal use case so I'm not sure.
