### ISSUE TITLE
Stderr: java.io.IOException: Cannot run program "patch" (in directory "/root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/protobuf"): error=2, No such file or directory

### ISSUE THREAD

**Issue by houkx** [tensorflow/serving#519]
**Step**:
[root@localhost serving]# bazel build tensorflow_serving/...

**Result**:
ERROR: error loading package 'tensorflow_serving/core/test_util': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/org_tensorflow/tensorflow/workspace.bzl", line 116
		_apply_patch(repo_ctx, repo_ctx.attr.patch_file)
	File "/root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/org_tensorflow/tensorflow/workspace.bzl", line 107, in _apply_patch
		_execute_and_check_ret_code(repo_ctx, cmd)
	File "/root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/org_tensorflow/tensorflow/workspace.bzl", line 91, in _execute_and_check_ret_code
		fail("Non-zero return code({1}) when ..., <2 more arguments>))
Non-zero return code(256) when executing 'patch -p1 -d /root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/protobuf -i /root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/org_tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout: 
Stderr: java.io.IOException: Cannot run program "patch" (in directory "/root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/protobuf"): error=2, No such file or directory.
ERROR: error loading package 'tensorflow_serving/core/test_util': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/org_tensorflow/tensorflow/workspace.bzl", line 116
		_apply_patch(repo_ctx, repo_ctx.attr.patch_file)
	File "/root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/org_tensorflow/tensorflow/workspace.bzl", line 107, in _apply_patch
		_execute_and_check_ret_code(repo_ctx, cmd)
	File "/root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/org_tensorflow/tensorflow/workspace.bzl", line 91, in _execute_and_check_ret_code
		fail("Non-zero return code({1}) when ..., <2 more arguments>))
Non-zero return code(256) when executing 'patch -p1 -d /root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/protobuf -i /root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/org_tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout: 
Stderr: java.io.IOException: Cannot run program "patch" (in directory "/root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/protobuf"): error=2, No such file or directory.
INFO: Elapsed time: 10.330s

**Comment by houkx** [comment]
[root@localhost serving]# **ls /root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/protobuf**
appveyor.bat  benchmarks   cmake          conformance       docs      generate_changelog.py         java      js       Makefile.am  php                   protobuf-lite.pc.in  protoc-artifacts  ruby       tests.sh              util
appveyor.yml  BUILD        composer.json  CONTRIBUTORS.txt  editors   generate_descriptor_proto.sh  javanano  LICENSE  more_tests   post_process_dist.sh  protobuf.pc.in       python            six.BUILD  third_party           WORKSPACE
autogen.sh    CHANGES.txt  configure.ac   csharp            examples  gmock.BUILD                   jenkins   m4       objectivec   protobuf.bzl          Protobuf.podspec     README.md         src        update_file_lists.sh

**Comment by brandyaptx** [comment]
just  yum install patch

**Comment by namrata-ibm** [comment]
Faced same while building TensorFlow from source. Installing `patch` resolves this error.
