### ISSUE TITLE
Build error on macOS 10.12.5.

### ISSUE THREAD

**Issue by ufosky** [tensorflow/serving#526]
I build this project follow the documents https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md ,but when I run `bazel build tensorflow_serving/...`, after many steps then get an error message:
```
ERROR: /private/var/tmp/_bazel_ufo/1f9c46805f97686640b52c294ff528b7/external/grpc/BUILD.bazel:1256:1: C++ compilation of rule '@grpc//:grpc++' failed: wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -MD -MF ... (remaining 63 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
error: invalid argument '-std=gnu99' not allowed with 'C++/ObjC++'
```

My environment:
macOS 10.12.5
Xcode 8.3.3
Python 3.6.1

**Comment by lucasgreene** [comment]
Im also having issues running `bazel build tensorflow_serving/...`

`
ERROR: /private/var/tmp/_bazel_lucas.adams/4b1ae2becc8f60421423f409d502caa5/external/grpc/BUILD.bazel:1256:1: C++ compilation of rule '@grpc//:grpc++' failed: wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -MD -MF ... (remaining 63 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
error: invalid argument '-std=gnu99' not allowed with 'C++/ObjC++'
INFO: Elapsed time: 1398.206s, Critical Path: 196.57s
`


Env:
macOS 10.12
xcode 8.3.3
python 3.6.0
Bazel:
Build label: 0.5.2-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jul 13 12:29:40 2017 (1499948980)
Build timestamp: 1499948980
Build timestamp as int: 1499948980

**Comment by mountaintom** [comment]
Hi,

I use a VM and do a Linux install on my Mac, so I have not tried this personally. However, I remember seeing this a while back. Hopefully it may help. 

https://github.com/tensorflow/serving/issues/194

The build requires C++11 so the included '-std=gnu99' flag is an error.
Installing on the Mac is not supported, but adventurous people have done it.

**Comment by gautamvasudevan** [comment]
Closing due to staleness.
