### ISSUE TITLE
CUDA/GPU Fails to Build

### ISSUE THREAD

**Issue by Mazecreator** [tensorflow/serving#53]
I have been staring at this problem for a few days now and cant figure it out.  I have tried a few clean installs and nothing seems to work.  The current setup is as follows:
gcc/g++: V 4.9
bazel: .22
CUDA Toolkit: V7.5
cuDnn: V4
TensorFlow: GPU version/0.8 (requires CUDA TOOLKIT 7.4 & cuDnn V4)
PATH contains: /usr/local/cuda-7.5/bin
LD_LIBRARY_PATH contains: /usr/local/cuda-7.5/lib64

I must not have everything setup right yet, maybe missing a dependency?  I can compile the "serving" directory with bazel without the CUDA flag, but as soon as I add the flag:
bazel build -c opt --config=cuda --verbose_failures tensorflow_serving/...

I get the attached error (after a lot of compiling).  I am not sure where to go after this as I have tried many combinations.  I did compile the CUDA 7.5 sample files and ran the deviceQuery which passed.

Thanks for the help.

[error.txt](https://github.com/tensorflow/serving/files/233261/error.txt)

**Comment by kirilg** [comment]
Just to confirm:
1) Are there any local changes?
2) Did you run ./configure inside the tensorflow directory and configure it with GPU?
3) If you haven't already, please also try adding the line `cxx_builtin_include_directory: "/usr/local/cuda-7.5/include"` (or the path where your cuda is installed) to tensorflow/third_party/gpus/crosstool/CROSSTOOL

**Comment by Mazecreator** [comment]
Thank you,

It looks like adding the following to the CROSSTOOL file solved the problem:
cxx_builtin_include_directory: "/usr/local/cuda-7.5/include"
