### ISSUE TITLE
Problems with bazel build 

### ISSUE THREAD

**Issue by SivaGabbi** [tensorflow/serving#531]
![image](https://user-images.githubusercontent.com/8449151/28529178-83895b9a-70ad-11e7-9e9a-3134c1902553.png)

I am getting an error saying the python path is not configured.. when it is already configured.. i am getting the same error in my mac too.. in the end it fails with some compilation error..

**Comment by kirilg** [comment]
That seems like a warning, not an error. Does the build succeed at the end or does it fail? If it fails, could you please provide the actual error?
