### ISSUE TITLE
How to use tensorflow serving client in Android apk?

### ISSUE THREAD

**Issue by banderuilq** [tensorflow/serving#533]
I want to know how to use tensorflow serving client in Android apk? Have you anybody have try this?
I saw the https://github.com/tensorflow/serving/pull/447. It look's like google have't support this?

But I see the From Research to Production with TensorFlow Serving (Google I/O '17) video carefully.
The lectuer always said one sample is one video rank apk. So I don't understand why still not support? And the tensorflow serving just used on PC now?

**Comment by banderuilq** [comment]
@kchodorow @pprett @chrisolston Did you know this question?

**Comment by chrisolston** [comment]
We don't currently support serving on android, although perhaps one day :)

**Comment by luolugithub** [comment]
@chrisolston ur guys still not supporting android client?
pls reply asap!!

**Comment by giannisfourfouris** [comment]
Is the tensorflow serving client still unavaliable for android? If yes do you know a way to use cloud for inference at an object detection mobile app (using tensorflow lite and inference on device)?

**Comment by figroc** [comment]
@giannisfourfouris If you are looking for a client library, my repo maybe helpful ( https://github.com/figroc/tensorflow-serving-client ). Beware that there are lots of stuff to concern of serving model as a public service. That can't be done only by a bare client library. 

You may need to do some tweak for android project according to https://github.com/google/protobuf-gradle-plugin.
