### ISSUE TITLE
Build error with docker on OSX 10.12.5

### ISSUE THREAD

**Issue by vigbk** [tensorflow/serving#534]
I am using this https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel dockerfile.

ERROR: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/org_tensorflow/tensorflow/core/kernels/BUILD:2120:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:self_adjoint_eig_op' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 107 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)

**Comment by igoingdown** [comment]
I also encountered this problem, but I have a temporary solution now. You can use the docker image offered by Aliyun Team if you don't mind.
```bash
docker run -ti --name tensorflow-serving registry.cn-hangzhou.aliyuncs.com/denverdino/tensorflow-serving
```

**Comment by vigbk** [comment]
It turned out to be a memory issue in the end. Needed around 4gb of free
memory.
