### ISSUE TITLE
How do I swap between modules during runtime?

### ISSUE THREAD

**Issue by davidvuong** [tensorflow/serving#537]
I understand that Tensorflow-serving will reload automatically when a new model version is added (0, 1, 2, 3, ...) but AFAIK, there's no way to do that for a new model.

I could only find documentation to change models either by specifying all models beforehand via a static configuration file (then changing between them somehow) or via the command line but is it possible to change to a model during runtime without Tensorflow-serving knowing about it upfront?

**Comment by atomextranova** [comment]
Change main.cc under tensorflow_serving/model_serversto to manually call ServerCore::ReloadConfig() method. Currently I did not see any examples, but this is what serving itself does.

**Comment by chrisolston** [comment]
Yes, @atomextranova is right. Currently that is the only way. Contributions welcome, though, if somebody wants to add an RPC handler for supplying new configs at runtime (the handler would in turn call ServerCore::ReloadConfig()).

**Comment by calhamdower** [comment]
If anyone can do this (I'm going to try...maybe): 
@perdasilva supplied some base code in #294 that is basically along the lines of what @chrisolston / @atomextranova are saying:
```
class ConfigurationServiceImpl final : public ConfigurationService::Service {
  public:
	explicit ConfigurationServiceImpl(std::unique_ptr<ServerCore>* core)
	  : core_(core) {}

	grpc::Status Configure(ServerContext* context, const ModelServerConfig* request,
			ConfigurationResponse* response) override {
		LOG(INFO) << "Attempting to reconfigure..." << std::endl;
		if(core_->get()) { // check server core is there
			const grpc::Status status = ToGRPCStatus(core_->get()->ReloadConfig(*request));

			if (!status.ok()) {
				VLOG(1) << "Configuration Failed: " << status.error_message();
			}

			response->set_success(status.ok());
			return status;
		}

		return grpc::Status::OK; // should probably return fail here...
	}

  private:
	std::unique_ptr<ServerCore>* core_;
};
```

Similarly this is referenced by #380

**Comment by Kindrat** [comment]
Added https://github.com/tensorflow/serving/pull/774. Could someone review it?

**Comment by chrisolston** [comment]
I'll review it when I'm back from my vacation. I should be able to get to it next week.

-Chris

**Comment by chrisolston** [comment]
FYI this thread is closely related to https://github.com/tensorflow/serving/issues/422

**Comment by wt-huang** [comment]
Closing as this is resolved
