### ISSUE TITLE
models/object_detection/, how to build tensor model on iOS platform with GRPC

### ISSUE THREAD

**Issue by zyg1982527** [tensorflow/serving#538]
Our project is tensorflow/models/object_detection. We use GRPC as the tool for server and iOS client communication. When I use predictWithRequest API , I don't know how to build "tensor" correcttly.
I did a lot of trying, but no success. Who know something about this, please give me some suggestions or help.

PredictRequest *predictRequest = [PredictRequest message];

ModelSpec *model=[[ModelSpec alloc]init];
model.signatureName=@"signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY";
model.name=@"vehicle_detection";
predictRequest.modelSpec =model;

UIImage *image=[UIImage imageNamed:@"IMG_4262.jpg"];
NSData *data=UIImagePNGRepresentation(image);
TensorShapeProto *tensorShape=[[TensorShapeProto alloc]init];
tensorShape=@[@1,@4032,@3024,@3];

TensorProto *tensor=[[TensorProto alloc]init];
tensor.tensorContent=data;
tensor.tensorShape= tensorShape;
NSMutableDictionary *inputDic=[[NSMutableDictionary alloc]init];
[inputDic setObject:tensor forKey:@"inputs"];
predictRequest.inputs=inputDic;
[client predictWithRequest:predictRequest handler:^(PredictResponse *response, NSError *error) {
    NSLog(@"response=%@",response );
}];

**Comment by mountaintom** [comment]
Hi,

I’m making the assumptions that you have compiled the complete chain of protos needed for the Prediction Service and the Tensor proto with protoc. And you have not changed your model so much, that it still resembles the Inception model. So, hopefully some percentage of this will apply and be useful.

The Tensor proto should have inherited the size property from the TensorSize proto automatically. So, you most likely should not need to create a TensorSize object and feed it into the Tensor object. The predictRequest service should have inherited the modelSpec proto.

Looking at your example section of code, here are some possible things to check.

Also, there is a good C++ example here: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_client.cc. It should be of some help.

model.signatureName=@"signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY";
If you wrote your model server and chose the “default” name this is OK. However, the inception model used the name ‘predict_images’.

[inputDic setObject:tensor forKey:@"inputs"];
The key most likely should be “images”.

tensorShape=@[@1,@4032,@3024,@3];
At this point the client is just sending a vector.
So, probably should be tensorShape=@[@1]; 
But, set as a property of the Tensor. Along the lines of the C++ code: mutable_tensor_shape()->add_dim()->set_size(1);

NSData *data=UIImagePNGRepresentation(image);
Unless you changed your model to use PNG data, likely this should be UIImageJPEGRepresentation.

tensor.tensorContent=data;
Assuming you Tensor proto resembles the one from the TensorFlow code base. This should be something like:
tensor.add_string_val(data, imageFileSize);

And you need to tell the Tensor proto the data type it is going to serialize.
tensor.set_dtype(tensorflow::DataType::DT_STRING);

If you are writing your own tensor work alike proto, keep in mind the Google Tensor will encode data of type DT_STRING (implemented as repeated bytes) into base64 before serializing and sending it.

— Tom

Related Issue: https://github.com/tensorflow/models/issues/2062

**Comment by zyg1982527** [comment]
Thank you your suggestions,it's very useful. I have solve the problem, and it can communicate with server successfully.

**Comment by zyg1982527** [comment]
-(void)callGrpc{
    NSString * const kHostAddress = @"111.202.46.21:18053";
    [GRPCCall useInsecureConnectionsForHost:kHostAddress];
    [GRPCCall setUserAgentPrefix:@"PredictionService/1.0" forHost:kHostAddress];
    
    ModelSpec *model=[[ModelSpec alloc]init];
    NSMutableArray *array=@[@"signature_def"];
    model.name=@"vehicle_detection";
    model.signatureName=@"signature_def";
    GetModelMetadataRequest *request = [GetModelMetadataRequest message];
    request.modelSpec =model;
    request.metadataFieldArray=array;
    PredictionService *client = [[PredictionService alloc] initWithHost:kHostAddress];
    [client getModelMetadataWithRequest:request handler:^(GetModelMetadataResponse *response, NSError *error) {
        NSLog(@"response.message=%@",response);
    }];
 
    //make tensorShapeArray
    TensorShapeProto_Dim *dic1=[[TensorShapeProto_Dim alloc]init];
    [dic1 setValue:@1.0 forKey:@"size"];
    TensorShapeProto_Dim *dic2=[[TensorShapeProto_Dim alloc]init];
    [dic2 setValue:[NSNumber numberWithDouble:4032.2] forKey:@"size"];
    TensorShapeProto_Dim *dic3=[[TensorShapeProto_Dim alloc]init];
    [dic3 setValue:[NSNumber numberWithDouble:3024.2] forKey:@"size"];
    TensorShapeProto_Dim *dic4=[[TensorShapeProto_Dim alloc]init];
    [dic4 setValue:[NSNumber numberWithDouble:3.0] forKey:@"size"];

    NSMutableArray *dimArray=[[NSMutableArray alloc]initWithObjects:dic1,dic2,dic3,dic4,nil];
    

    TensorShapeProto *tensorShape=[[TensorShapeProto alloc]init];
    NSMutableArray *tensorShapeArray=@[@1,@4032,@3024,@3];
    tensorShape.dimArray=dimArray;
    
    enum DataType dtype  =DataType_DtFloat;
    UIImage *image=[UIImage imageNamed:@"IMG_4262.jpg"];
    NSData *data=UIImageJPEGRepresentation(image,1.0);
    GPBFloatArray *floatArray=[GPBFloatArray arrayWithValue:55555.5];
    TensorProto *tensor=[[TensorProto alloc]init];
    tensor.tensorShape=tensorShape;
    tensor.dtype=dtype;
//    tensor.hasTensorShape=YES;
    tensor.versionNumber=0;
    tensor.floatValArray=floatArray;
    
    NSMutableDictionary *inputDic=[[NSMutableDictionary alloc]init];
    [inputDic setObject:tensor forKey:@"inputs"];

    PredictRequest *predictRequest = [PredictRequest message];
    model.signatureName=@"signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY";
    model.name=@"vehicle_detection";
    predictRequest.modelSpec =model;
    predictRequest.inputs=inputDic;
    [client predictWithRequest:predictRequest handler:^(PredictResponse *response, NSError *error)    {
        NSLog(@"response.message=%@",response );
    }];
}

**Comment by mountaintom** [comment]
Hi,

In the chance you are still working on this issue, I created an example iOS TensorFlow Client.

The code is here:
https://github.com/mountaintom/TensorFlowServing-InceptionClient
