### ISSUE TITLE
Op type not registered 'PyFunc'

### ISSUE THREAD

**Issue by Mazecreator** [tensorflow/serving#54]
I am working on a project and have use the **tf.py_func()** to create my own OP in python.  I can compile the training script and properly train the model.  I get the exported model and can see it in TensorBoard.

The problem is after I compile the "inference.cc".  I can compile the inference.cc file and have used it to load other models to test in production.  When I try to load the model with the tf.py_func() in it, I get the following error:

> I tensorflow_serving/session_bundle/session_bundle.cc:130] Attempting to load a SessionBundle from: /tmp/export/00000001
> E tensorflow_serving/ProductLoadModel/inference.cc:198] Fail to load tensorflow export: Op type not registered 'PyFunc'

Is there something I need to do to export the py_func() for TensorFlow Serving?  Is there a missing import?

> using tensorflow::serving::ClassificationSignature;
> using tensorflow::serving::NT8Request;
> using tensorflow::serving::ResponseToNT8;
> using tensorflow::serving::NT8Service;
> using tensorflow::serving::SessionBundle;
> using tensorflow::string;
> using tensorflow::Tensor;
> using tensorflow::TensorShape;

Thanks

**Comment by fangweili** [comment]
I don't think ops registered with PyFunc() are supported under C++. They can only be executed under the same python interpreter that PyFunc() is invoked.

**Comment by Mazecreator** [comment]
Thanks, seems like that might be the case.  I tried adding some includes to the build to get the Python code to compile with the inference.cc but nothing worked.

Is there a way to compiler the Python directly as an inference to include the py_func() code?  I only found an example by which compiling the C++ code will provide the service.

**Comment by fangweili** [comment]
Unfortunately, Tensorflow Serving supports only C++.
However, if all you need is the SessionBundle functionality, it can be easily written in Python. We welcome community contributions.

**Comment by Mazecreator** [comment]
I can look into coding the SessionBundle, I may need some pointers as to where to start for the details of what needs to be added.

The other issue here, the PyFunc() I am using is only needed for training.  It seems like this should be pruned from the graph.  So this might be an improvement of that SessionBundle import as well for the C++ version.

Is there a way for me to manually delete nodes prior to my final export?  My other thought is to create a second Python script which is just the model for the strict purpose of loading saved weights for the model and exporting the model for the inference.  An extra step but might remove the PyFunc() from the graph for serving.

**Comment by fangweili** [comment]
When your training graph T and inference graph I differ, there're two options:
1. Construct them at the same time, train with T, but initialize and export the model with `Export.init(graph_def=I.as_graph_def(), ...)`.
2. As you described, build I and load saved weights of T - similar to `inception_export.py`.
