### ISSUE TITLE
GPU Docker Fails to Find libcudnn

### ISSUE THREAD

**Issue by mhamilton723** [tensorflow/serving#540]
Ubuntu 16.06 Nvidia K80 GPU

When I run the gpu docker image with 

docker build --pull -t $USER/tensorflow-serving-devel-gpu -f tensorflow_serving/tools/docker/Dockerfile.devel-gpu .

It fails at building tensorflow and just repeats the following:

"Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 6.0]: Please specify the location where cuDNN 6 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:Invalid path to cuDNN 6 toolkit. None of the following files can be found:
/usr/local/cuda-8.0/lib64/libcudnn.so.6
/usr/local/cuda-8.0/libcudnn.so.6
/usr/lib/x86_64-linux-gnu/libcudnn.so.6
"Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 6.0]: Please specify the location where cuDNN 6 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:Invalid path to cuDNN 6 toolkit. None of the following files can be found:
/usr/local/cuda-8.0/lib64/libcudnn.so.6
/usr/local/cuda-8.0/libcudnn.so.6
/usr/lib/x86_64-linux-gnu/libcudnn.so.6

**Comment by mhamilton723** [comment]
After investigating inside the docker image it appears that tensorflow defaults to use cudnn6 instead of cudnn5. Working on a fix now but if anyone has tips please post them here

**Comment by kirilg** [comment]
The PR was merged, so I'm closing this issue.
