### ISSUE TITLE
Apt-get Install does not use GPU

### ISSUE THREAD

**Issue by dylanrandle** [tensorflow/serving#549]
Hi, 

I have tensorflow 1.1.0 GPU version installed with CUDA 8.0 and CUDNN 5.1.10. Tensorflow works fine on GPU. My nvidia driver versions are 375.66. 

When I use the new (thank you) installation method with apt-get (sudo apt-get install tensorflow-model-server), and I load my models with:
`tensorflow_model_server --port=9000 --enable_batching=true --batching_parameters_file="BatchingParametersProto.txt" --model_config_file="ModelProtoConfig.txt" `
it does not use my GPU (tesla K80). 

Can anyone explain how to resolve this issue? I have had tensorflow-serving working on GPU before by using `bazel build -c opt --config=cuda tensorflow_serving/...` 

Thanks,
Dylan

**Comment by kirilg** [comment]
For GPU support, you can continue to use `bazel build -c opt --config=cuda tensorflow_serving/...`, the apt-get version is currently CPU only.

**Comment by dylanrandle** [comment]
Thanks for the fast reply.

**Comment by aniketmaurya** [comment]
> For GPU support, you can continue to use `bazel build -c opt --config=cuda tensorflow_serving/...`, the apt-get version is currently CPU only.

is  apt-install now availble for GPU ?
