### ISSUE TITLE
Returning a text label via an export with classes_tensor

### ISSUE THREAD

**Issue by viksit** [tensorflow/serving#55]
Could someone elaborate on how the classes tensor gets used when a model is exported?

Lets say I have a list of labels that I can convert into a tensor of type text.

```
labels = ["label1", "label2"]
labels_tensor = tf.constant(labels)
..
..

signature = exporter.classification_signature(input_tensor=input,
                                                classes_tensor=labels_tensor,
                                                scores_tensor=output)
```

Now - when using this in a C++ inference server, you use them via `session->run()` or `RunClassification`, like so,

```
const tensorflow::Status run_status =
      RunClassification(signature, batched_input, bundle->session.get(),
                        &batched_classes, &batched_scores);
```

- What does batched_classes contain? Numerical identifiers or text?
- If it only contains numerical identifiers, why do we even needs this? Isn't the shape of the `batched_scores` allowing us to select the index of the right class by running an `argmax`? The problem with this approach is that the client also needs to be aware of the model details (eg labels), which I'd rather avoid.

Main question - how do I return a text label rather than a scores tensor for a given request?

**Comment by fangweili** [comment]
It can be anything, numerical identifier or text or anything you choose it to be. The point is, your model usually wants to return only top K result of a large scale classification of N, `class_tensor` is to store the top K index/label, as `argmax` will not help in such case.

You are correct that ideally we want to return labels directly so that client does not need to be aware of model details. For that, your model will need looks up label based on index. One TF op I am aware of that can do this is [lookup_ops](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lookup). There could be others.

**Comment by viksit** [comment]
@fangweili ah right - I get the topK part.

from https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_inference.cc#L308

This is just adding the numerical classes to batched_classes, right?
```
  for (int j = 0; j < kNumTopClasses; j++) {
     
      classes->Add(batched_classes.matrix<int>()(i, j));
      scores->Add(batched_scores.matrix<float>()(i, j));
    }

```

and in the inception_client, we do the lookup.

```
    for i in range(NUM_CLASSES):
      index = result.classes[i]
      score = result.scores[i]
      print '%f : %s' % (score, texts[synsets[index - 1]])
```

I'm not sure I understand your lookup_ops coment - thats only for Python, correct? So instead of this manual look up, we could've done this lookup via that op.

But is there an equivalent in C++ too? Instead of doing,
```
classes->Add(batched_classes.matrix<int>()(i, j));
```

I could do something like,

```
classes->Add(getLabelFromLookupTable(batched_classes.matrix<int>()(i, j)));
```

**Comment by fangweili** [comment]
That op is a TF op. So if you use it to construct the TF graph of your model, the label lookup will be done as part of the graph. The output will then be a tensor of string (labels) directly, and there's no need to do transformation in C++ serving code.

**Comment by viksit** [comment]
Ahh, I see what you mean. I'll try this out, thanks.

**Comment by jharmsen** [comment]
@viksit 
Please checkout c948af73268c8071fed17a6edcf95b34e40583f2 which moves the lookup from the client to inside the graph on the server.

In particular the snippet,
```
 +    # Create a constant string Tensor where the i'th element is
 +    # the human readable class description for the i'th index.
 +    class_tensor = tf.constant([texts[s] for s in synsets])
 +
 +    classes = tf.contrib.lookup.index_to_string(tf.to_int64(indices),
 +                                                mapping=class_tensor)
```

**Comment by jollysean** [comment]
Do we need to add classes in mnist_inference_2.py as well? Coz, I m getting constant output by running the example with changes.
How to replace nullptr in mnist_inference_2.cc at line 322

```
322   const tensorflow::Status run_status = 
323       RunClassification(signature, input, bundle->session.get(), 
324                         nullptr /* classes */, &scores); 
```

**Comment by fangweili** [comment]
returning 'classes' in mnist case is less useful -- it is always categorizing images into just [0-9] digits. 'scores' return the probability of each, and 'classes' is implicit.
