### ISSUE TITLE
Usage of the client

### ISSUE THREAD

**Issue by harelfar2** [tensorflow/serving#555]
I successfully created a server that receives a TF `saved_model`, but now I want to send it queries and get predictions.
However, I'm having a hard time of understanding how the client works and how to implement it. 
All I found online is the [basic tutorial](https://tensorflow.github.io/serving/serving_basic.html), but they only give the client code for mnist, and it doesn't fit my own mdoel. 
So can anyone refer me to how to use or implement the client for a different model?

**Comment by JoelGooch** [comment]
Here is the client code for the Inception Model:
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_client.py

The tutorial that points to this code in reference at the same place you found that basic tutorial under 'Serving Inception...'

**Comment by kirilg** [comment]
[inception_client.py](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_client.py) and [mnist_client.py](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_client.py) are two such examples. You can refer to the corresponding tutorials as mentioned by @JoelGooch and see how the [request is built](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_client.py#L49).

For your client, you'll likely just want to build the request differently depending on your model's inputs and use the right signature depending on what signatures your model exports.
