### ISSUE TITLE
Where's the brew install or pip install for tensorflow serving?

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/serving#556]
I installed the tensorflow serving on my Mac with minor modifications to the makefile.

Then, I tried to run it with an example script but it because unresponsive and I couldn't find out the progress of the work in terms training and saving the model.

**Comment by chrisolston** [comment]
We are working on offering a pre-built binary so users who don't need customization won't need to build their own binaries. Please stay tuned.

re: unresponsiveness, you could try --logtostderr to see some logging. If you are still having problems you could post more details about what is (not) happening.

**Comment by shyamalschandra** [comment]
Thanks, @chrisolston !  I look forward to the pre-built binaries.  I am going to try out your suggestion.

**Comment by kirilg** [comment]
pre-built binaries are available, you can check out https://www.tensorflow.org/serving/setup (see the apt-get section and PIP for python client code).

**Comment by jtlz2** [comment]
@kirilg Link is now dead :( Any ideas?
