### ISSUE TITLE
why servable_handle.h include itself ?

### ISSUE THREAD

**Issue by enqu** [tensorflow/serving#561]
https://github.com/tensorflow/serving/blob/9a0e768b66061e53ac24004d6a3f63738d7d2f4b/tensorflow_serving/core/servable_handle.h#L25

the servable_handle.h include itself at this line, Is there some reason ?

**Comment by chrisolston** [comment]
It looks like that was added automatically by an include-what-you-use script. I guess it's a bug, but a rather harmless one given the header guards. Feel free to send a PR to remove it.
