### ISSUE TITLE
TypeError: Parameter to CopyFrom() must be instance of same class: expected TensorProto got tensorflow.TensorProto.

### ISSUE THREAD

**Issue by dingqs447** [tensorflow/serving#571]
I would like to write an inception of the GRPC client, not using tensorflow serving compiled inception_client.

Here are my steps:
1，mkdir  -p /home/dqs/python_tf-serving
2, cd /home/dqs/python_tf-serving  && tree
.
├── google
│   ├── api
│   │   ├── annotations_pb2_grpc.py
│   │   ├── annotations_pb2.py
│   │   ├── annotations_pb2.pyc
│   │   ├── annotations.proto
│   │   ├── http_pb2_grpc.py
│   │   ├── http_pb2.py
│   │   ├── http_pb2.pyc
│   │   ├── http.proto
│   │   ├── __init__.py
│   │   └── __init__.pyc
│   ├── __init__.py
│   └── __init__.pyc
├── inception_client.py
└── pb
    ├── __init__.py
    ├── __init__.pyc
    ├── model_pb2_grpc.py
    ├── model_pb2.py
    ├── model_pb2.pyc
    ├── model.proto
    ├── prediction_service_pb2_grpc.py
    ├── prediction_service_pb2.py
    ├── prediction_service_pb2.pyc
    ├── prediction_service.proto
    ├── predict_pb2_grpc.py
    ├── predict_pb2.py
    ├── predict_pb2.pyc
    ├── predict.proto
    ├── resource_handle_pb2_grpc.py
    ├── resource_handle_pb2.py
    ├── resource_handle_pb2.pyc
    ├── resource_handle.proto
    ├── tensor_pb2_grpc.py
    ├── tensor_pb2.py
    ├── tensor_pb2.pyc
    ├── tensor.proto
    ├── tensor_shape_pb2_grpc.py
    ├── tensor_shape_pb2.py
    ├── tensor_shape_pb2.pyc
    ├── tensor_shape.proto
    ├── types_pb2_grpc.py
    ├── types_pb2.py
    ├── types_pb2.pyc
    └── types.proto

3 directories, 43 files

3,here is inception_client.py ：
   ============================================
#!/usr/bin/env python2.7
from __future__ import print_function

# This is a placeholder for a Google-internal import.
from grpc.beta import implementations
import tensorflow as tf

from pb import predict_pb2
from pb import prediction_service_pb2

tf.app.flags.DEFINE_string('server', 'localhost:9000',
							'PredictionService host:port')
tf.app.flags.DEFINE_string('image', '', 'path to image in JPEG format')
FLAGS = tf.app.flags.FLAGS

def main():
	host, port = FLAGS.server.split(':')
	channel = implementations.insecure_channel(host, int(port))
	stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
	# Send request
	with open(FLAGS.image, 'rb') as f:
		# See prediction_service.proto for gRPC request/response details.
		data = f.read()
		request = predict_pb2.PredictRequest()
		request.model_spec.name = 'inception'
		request.model_spec.signature_name = 'predict_images'
		tensor_proto_data = tf.contrib.util.make_tensor_proto(data, shape=[1])
		print(type(tensor_proto_data))
		request.inputs['images'].CopyFrom(tensor_proto_data)
		result = stub.Predict(request, 10.0)  # 10 secs timeout
		print(result)

if __name__ == '__main__':
	main()
 ============================================
4，Tensorflow serving has been loaded with the inception model，When I run this inception_client.py, the following error is reported:
$ ./inception_client.py --server=192.168.74.205:9000 --image=/home/dqs/dog.jpg
<class 'tensorflow.core.framework.tensor_pb2.TensorProto'>
Traceback (most recent call last):
  File "./inception_client.py", line 40, in <module>
    main()
  File "./inception_client.py", line 35, in main
    request.inputs['images'].CopyFrom(tensor_proto_data)
TypeError: Parameter to CopyFrom() must be instance of same class: expected TensorProto got tensorflow.TensorProto.

hope someone help me, thanks.

**Comment by kirilg** [comment]
It looks like you're getting import collisions with the python files that you copied to the local directory.

Can you explain what you're trying to do? If you're just trying to avoid using Bazel, you can install the TensorFlow Serving PIP package (tensorflow-serving-api) using the instructions [here](https://www.tensorflow.org/serving/setup) and run the provided inception_client.py without having to copy any python files locally.

**Comment by dingqs447** [comment]
thank you for your reply.@kirilg

I would like to put the tensorflow model together with the tensorflow serving in the docker image. In order to make this docker image as small as possible (delete bazel and  translated tensorflow serving without use, docker mirror has reached 3.3GB), of course, I must also install Tensorflow 
 in docker image because I need to write GRPC client for my own tensorflow model. At the same time, I also need to grpc client program on the docker image.The inception model is just an example. So, I have to make grpc client program for my own new model。

I would like to make the grpc client program in the docker mirror for my own tensorflow model. At the same time I also want the docker mirror to be smaller. So I copied the python files to local directory that I needed it.

If i installed【 pip install tensorflow-serving-api】, how would i use it? thanks.

**Comment by kirilg** [comment]
You can install the ModelServer using `apt-get install` and the Python client API using `pip install`. Instructions for both are [here](https://www.tensorflow.org/serving/setup). Then you can run the ModelServer binary and your client code without needing Bazel or compiling anything yourself.

Take a look at this [tutorial](https://www.tensorflow.org/serving/serving_basic) and go through the apt-get and PIP flow to see how to run a client using the PIP package.

**Comment by dingqs447** [comment]
thank you @kirilg.
it is work, I am so happy.
thanks again.
