### ISSUE TITLE
Add custom layer

### ISSUE THREAD

**Issue by ruiluis** [tensorflow/serving#575]
good day.
I have a network already being served in tensorflow serving. in the client i obtain the result and i do some processing. i want to pass this end processing to the serving part in particular i wish to convert to a numpy array. 
i did a custom layer, added to the network. however i could convert the tensor.
"Tensor(\"myoutput\", shape=(?, 13, 13, 30), dtype=float32)

values = sess.graph.get_tensor_by_name('myoutput')
outout = custom_layer(values,process_res)
predict_output_tensor_info = tf.saved_model.utils.build_tensor_info(outout)
....
def custom_layer(incoming, custom_fn, **kwargs):
    name = "CustomLayer"
    if 'name' in kwargs:
        name = kwargs['name']
    with tf.name_scope(name):
        inference = custom_fn(incoming, **kwargs)

    return tf.constant(inference,dtype=tf.string)

def process_res(predicts):
    not working --> tt = tensor_util.MakeNdarray(predicts[0])
    return str(predicts)

**Comment by chrisolston** [comment]
This looks like a core tensorflow (not tf serving) issue. Maybe post to the tensorflow github or stackoverflow.
