### ISSUE TITLE
serving behind a https proxy

### ISSUE THREAD

**Issue by ismaeIfm** [tensorflow/serving#577]
Hi there, I've been trying to establish with a docker container with tensorflow serving that is behind a nginx proxy (https) without a satisfactory attempt. Here is my code in python:

`channel = implementations.insecure_channel(
        'https://some.domain.com/serving/', 443)`
`stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)`
`response = stub.Predict(request, 5.0)`

I've tried with these combinations of hosts:
- some.domain.com/serving/
- https://some.domain.com/serving/

and ports:
- 80
- 443
- 8500

But everytime I tried I got the following errors:

`grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.UNAVAILABLE, details="Trying to connect an http1.x server")
`

or

`grpc.framework.interfaces.face.face.ExpirationError: ExpirationError(code=StatusCode.DEADLINE_EXCEEDED, details="Deadline Exceeded")
`

Does anyone knows if that's possible?

**Comment by wjarek** [comment]
Are you running the model server (sudo apt-get install tensorflow-model-server)? Currently the model server exposes a gRPC service only (Protobuf over HTTP/2).  Looks like HTTP/2 is not quite supported yet by nginx? https://github.com/grpc/grpc.github.io/issues/230 
I also found this may be of potential interest in the meantime: https://grpc.io/blog/coreos (RESTful proxy).

**Comment by ismaeIfm** [comment]
Yes I installed tensoflow-serving via apt-get. Thanks. I'll take a look to it.

**Comment by zihuaweng** [comment]
Did you specify the localhost as the docker container IP?
python tensorflow_serving/example/inception_client.py --server=172.17.0.2:9000 --image=/path/to/image.jpg
Get IP from : docker network inspect bridge | grep IPv4Address

**Comment by gautamvasudevan** [comment]
TF Serving now supports a RESTful API end point, which should make this way easier.

**Comment by lozuwa** [comment]
Hey in case anybody needs to know this is because nginx did not support http2 or grpc. From March 2018 it does. So, your configuration should be something like this:

server {
  listen 80 http2;
  server_name localhost;
  
  location / {
    grpc_pass grpc_server_ip:grpc_server_port;
  }

}
