### ISSUE TITLE
Java Tensorflow Serving Prediction Client Too Slow

### ISSUE THREAD

**Issue by sumsuddin** [tensorflow/serving#578]
I have created a tensorflow object detection model and served it using tensorflow serving. I have created a python client to test the serving model and that takes around 40ms time to receive all the prediction.

```
t1 = datetime.datetime.now()
result = stub.Predict(request, 60.0)  # 60 secs timeout
t2 = datetime.datetime.now()
print ((t2 - t1).microseconds / 1000)
```

Now, my problem is when I do the same on java, it takes way too much time (about 10 times) of 450 to 500ms.

```
ManagedChannel channel = ManagedChannelBuilder.forAddress("localhost", 9000)
        .usePlaintext(true)
        .build();
PredictionServiceGrpc.PredictionServiceBlockingStub stub = PredictionServiceGrpc.newBlockingStub(channel);

......

Instant pre = Instant.now();
Predict.PredictResponse response = stub.predict(request);
Instant curr = Instant.now();
System.out.println("time " + ChronoUnit.MILLIS.between(pre,curr));
```
Can anyone help me to resolve the issue? Thanks in advanced.
Same thing on [SO here](https://stackoverflow.com/q/45917449/5330223)

**Comment by sumsuddin** [comment]
The issue was the network overhead, as I was sending image pixels. Changing it to encoded image resolved the issue.

**Comment by PayneJoe** [comment]
@sumsuddin I am wondering what is the final performance result of your solution?

**Comment by sumsuddin** [comment]
It was about the same in both Python and Java APIs

**Comment by PayneJoe** [comment]
Hi, @sumsuddin , how about the QPS?  I'am really confusing about the performance of it.

**Comment by sumsuddin** [comment]
As I have said earlier, I got about 40 to 50 ms in CPU using mobile-net-v1, using Nvidia-980 GPU it was about 20ms or less. Using SSD-300 model took about twice the time as far as I remember.

**Comment by PayneJoe** [comment]
Only one single request takes 40-50ms? It costs hundreds of microseconds per request with 500 concurrent threads on my side.

**Comment by sumsuddin** [comment]
I'm not sure why, If you can share your approaches and the exact model you used I could have a look. 

But generally, it happens when you try to predict an image with pixel data eg. 2048 * 2048 ~= 4 * 10^6 pixels which is about 4MB. So when transferring using network you get slow performance. But if you encode the image eg jpg format and send the binary data to the server it's generally smaller size data like 200KB or so. 
There are many other factors that may be responsible too.
