### ISSUE TITLE
tensorflow-serving-api don't support python 3.x officially?

### ISSUE THREAD

**Issue by scotthuang1989** [tensorflow/serving#581]
I get an error: 
"  Could not find a version that satisfies the requirement tensorflow-serving-api (from versions: )
No matching distribution found for tensorflow-serving-api
"
when I try to execute this command: pip install tensorflow-serving-api
so I google around, find that [this lib only have py2 version](https://pypi.python.org/pypi/tensorflow-serving-api/1.3.0). But, I don't see other people complain about it.  So, I am not sure I am doing it wrong or I need compile this lib myself?

**Comment by wenfeixiang1991** [comment]
Yes, only py2 version

**Comment by scotthuang1989** [comment]
ok. thanks.

**Comment by chrisolston** [comment]
Currently our pip package only supports python 2. We are looking into adding python 3 support.

**Comment by KevinZhao** [comment]
Yes, I need that one too, as my client environment is py3, keep posted

**Comment by kavishrastogi** [comment]
I am trying to install Tensor-flow serving on Windows 10 64-bit machine, where tensor-flow installation can not happen with python 2, atleast python 3.5 is required.

Is there any workaround?

Sources: Internet

**Comment by jacklone** [comment]
Just download the package, and extract the source files, put them in the root of your project, and import just like you have installed the package. It will be ok in python3.6.

**Comment by kavishrastogi** [comment]
Ok Thanks

**Comment by pruthvishetty** [comment]
Yes, pip installation is not yet supported for Python 3.x. Here's a workaround - 

- Follow `Installation` > `Prerequisites` > `Bezel` (Steps 1 & 2) from [here](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md).

- Copy the folder (unzipped) and paste it in `/Users/<username>/anaconda3/lib/python3.6/site-packages/`

- Import as usual.

PS - If you are not using anaconda or if your python is configured differently, you can still find the location of site-packages by importing any working library first and then execute <library>.__file__

Example:

>`import numpy`
> `numpy.__file__`
> `'/Users/<username>/anaconda3/lib/python3.6/site-packages/numpy/__init__.py'`

**Comment by nadavb** [comment]
Any news regarding the python 3?
