### ISSUE TITLE
Could not build tf and tfserving with a proper GCP support.

### ISSUE THREAD

**Issue by MtDersvan** [tensorflow/serving#583]
When building tfserving even with the [Dockerfile.devel](github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel) and stock commands:

```
git clone --recurse-submodules https://github.com/tensorflow/serving
cd serving/tensorflow
./configure
cd ..
bazel build -c opt tensorflow_serving/example/...
```
And specifying TF_NEED_GCP=1:

```
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]: y
Google Cloud Platform support will be enabled for TensorFlow.
```
TF still does not work: 
a] `bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server` + models that are stored on a GCS, by getting a following error:

```
Non-OK-status: ServerCore::Create(std::move(options), &core) status: Invalid argument: Expected model ${MODEL_NAME} to have an absolute path; got base_path()=gs://${BUCKET_NAME}
```
b] client.py (`tf.gfile.Open(...)`) to access parameter configs stored on GCS:
```
Traceback (most recent call last):
  ...
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/serving/bazel-bin/tensorflow_serving/example/${client.py}.runfiles/org_tensorflow/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    c_api.TF_GetCode(status))
tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme gs not implemented
```

NOTE: When I used the older built container (≈ 2-3 weeks ago), the first error **a]** goes away (`Running ModelServer at 0.0.0.0:9000 `), but **b]** - persists.

Is this an intended behaviour? 
What should be done to mitigate this.

**Comment by kirilg** [comment]
The first error was a bug and was fixed in [this commit](https://github.com/tensorflow/serving/commit/d2c5b658f5a1b00692be43bed25cd726222c1695) so getting the latest ModelServer should fix that problem.

I'm not as familiar with the second error with `tf.gfile.Open`, but it looks to be in TF's libraries and since you configured TF to include GCP support, this should work. I saw a [similar issue](https://github.com/tensorflow/tensorflow/issues/11280) in tensorboard, so it's possible the same issue is encountered here.

**Comment by MtDersvan** [comment]
@kirilg I started updating our production tfserving API lately, and this issue in addition to https://github.com/tensorflow/serving/issues/406#issuecomment-336680601 kept coming back.
My `.tf_configure.bazelrc` certainly has `build --define with_gcp_support=true` enabled, so I truly don't know what can go wrong. Standalone TF builds work perfectly.
~~~console
Traceback (most recent call last):
  File "/serving/bazel-bin/tensorflow_serving/example/....runfiles/tf_serving/tensorflow_serving/example/....py", line 34, in <module>
    hps = load_hps_path(hps_path)
  File "/serving/bazel-bin/tensorflow_serving/example/....runfiles/tf_serving/tensorflow_serving/example/....py", line 22, in load_hps_path
    if tf.gfile.Exists(hps_file):
  File "/serving/bazel-bin/tensorflow_serving/example/....runfiles/org_tensorflow/tensorflow/python/lib/io/file_io.py", line 253, in file_exists
    pywrap_tensorflow.FileExists(compat.as_bytes(filename), status)
  File "/serving/bazel-bin/tensorflow_serving/example/....runfiles/org_tensorflow/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme 'gs' not implemented (file: 'gs://...')
~~~

Is this a TF, TFSERVING/TF linking or BAZEL issue?

**Comment by MtDersvan** [comment]
@kirilg I ran some tests, and bazel seems to work if the parameters are specified directly, e.g.:
~~~console
bazel build -c opt \
  --verbose_failures \
  --action_env PYTHON_BIN_PATH="/usr/bin/python3" \
  --action_env PYTHON_LIB_PATH="/usr/local/lib/python3.5/dist-packages" \
  --define PYTHON_BIN_PATH="/usr/bin/python3" \
  --define PYTHON_LIB_PATH="/usr/local/lib/python3.5/dist-packages" \
  --force_python=py3 \
  --host_force_python=py3 \
  --python_path="/usr/bin/python3" \
  --force_python=py3 \
  --host_force_python=py3 \
  --define with_jemalloc=true \
  --define with_gcp_support=true \
  //tensorflow_serving/example:...
~~~
for GCP & Python 3 build just fine, but for some reasons it ignores fully the `.tf_configure.bazelrc` specifications.
This might help resolve several issues like https://github.com/tensorflow/serving/issues/406, here.

**Comment by gautamvasudevan** [comment]
Thanks for the suggestion! Closing this issue for now.
