### ISSUE TITLE
instruction of prediction_service_pb2_grpc.py

### ISSUE THREAD

**Issue by aforwardz** [tensorflow/serving#585]
I have my own model served at tf serving and I only define a predict_signature(i need only predict api) when I export the saved_model. Then I use the command `python -m grpc.tools.protoc --python_out=. --grpc_python_out=. -I. tensorflow_serving/apis/prediction_service.proto` to generate python compiled files: _prediction_service_pb2.py_ and _prediction_service_pb2_grpc.py_. I use the *_pb2.py in my project like the example in tensorflow_serving/example/inception_client.py BUT it indicates that the *_pb2.py has deprecated in this new version and use *_pb2_grpc.py instead. I just wonder how to the class in the substitute for the example has outdated. Do I have to create an extra service and add it to tf serving or do other things? 

Thanks!

**Comment by aforwardz** [comment]
The counterpart compiled _predict_pb2_grpc.py_ is blank...

**Comment by kirilg** [comment]
My first recommendation would be to just use prediction_service_pb2.py that's defined in the repo and simply use the predict API. There will be other functions defined in the API, but that's fine, your model will only work with Predict. If you do that, you can use the prebuilt ModelServer (installed with apt-get) and the python client library that you can `pip install` without worrying about prediction_service_pb2.py.

If you really need to restrict the API and regenerate your own proto, can you elaborate on what exactly says it's deprecated? If you just regenerate prediction_service_pb2.py like you did and replace the existing one in the repo, can you run the tutorials? try running `git diff` on that file and make sure all changes are expected (i.e. only change is the removal of other service functions).

**Comment by aforwardz** [comment]
@kirilg Thanks a lot for your comment. 
Actually when I re-compiled the predict.proto, the newly generated two files prediction_service_pb2.py and prediction_service_pb2_grpc.py are different with those used to be.
In prediction_service_pb2.py, there is a code snippet:
```
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
```
and I use 'beta_create_PredictionService_stub' function to create a stub
![screenshot from 2017-09-06 11 34 10](https://user-images.githubusercontent.com/19967761/30093617-1c9e733e-92f9-11e7-8a70-2877519dae5c.png)
So I suppose the *_pb2.py has deprecated but maybe I misunderstand.
HOWEVER, I still use the functions in *_pb2.py to create my grpc client and it also works well.

In general, thanks again.
