### ISSUE TITLE
Tensorflow Serving Test Failing

### ISSUE THREAD

**Issue by jsawruk** [tensorflow/serving#589]
I am unable to get TensorFlow Serving to pass all of the tests. 
When I run:
`bazel test -c opt tensorflow_serving/...`

I get the following error:

`//tensorflow_serving/model_servers:tensorflow_model_server_test         TIMEOUT in 315.0s`

When I view the log file, I only see:
`exec ${PAGER:-/usr/bin/less} "$0" || exit 1`

I opened up [this StackOverflow post](https://stackoverflow.com/questions/46062749/tensorflow-serving-test-failing), but received no response yet.

How I built TensorFlow Serving:
```
git clone --recurse-submodules https://github.com/tensorflow/serving
cd serving/
cd tensorflow/
./configure (used defaults for everything)
cd ..
bazel build -c opt tensorflow_serving/...
bazel test -c opt tensorflow_serving/...
```

System details:
OS: Ubuntu 17.04 (x86_64)
Python: 2.7 (Anaconda)
Bazel: 0.5.3
TensorFlow: I am working with 1.3, but it does not appear to be compiled (cannot import into python). Not sure why TensorFlow didn't compile using the commands above.

It appears the issue is TensorFlow not available in Python, even though the TensorFlow Serving build succeeded. I also tried building TensorFlow by itself; the build succeeded, but it did not resolve my issue.

**Comment by djph29** [comment]
I got the same issue on redhat 7.0

**Comment by kirilg** [comment]
We encountered similar timeouts with this test in Jenkins recently and [this commit](https://github.com/tensorflow/serving/commit/75e95416b0c649bf2b4f5652d886f3d20d13999a) fixed the problem. Sorry for the delay in answering on this thread, but I think it should be resolved. Please reopen this issue if you're still seeing timouts with TensorFlow Serving at head.

**Comment by jsawruk** [comment]
I was able to install the binary distribution, but I am glad this specific issue has been resolved. Thanks!
