### ISSUE TITLE
Faux load balancing?

### ISSUE THREAD

**Issue by eriophora** [tensorflow/serving#60]
I'm trying to implement some (extremely) rudimentary load balancing by having multiple machines serve up the same model. As mentioned in #10, submitting lots of jobs to the server will case the `StreamingBatchScheduler` to return:

```
io.grpc.StatusRuntimeException: UNAVAILABLE: This task would start a fresh batch, but all batch threads are busy, so at present there is no processing capacity available for this task
```

While normally resubmitting the job wouldn't be difficult, the way my system is architected makes this sort of hard to do without blocking. It looks a bit like this:

`client <---> predictor <---> server`, where `predictor` is actually akin to `inception_client.py`. However, `predictor` returns the result future to `client`, which then figures out which callbacks to attach depending on why it requested this particular prediction. Since `predictor` has a list of available servers it can submit to, it would be great if there was some way for `predictor` to work like:
1. Get job
2. Submit job to server `n`
3. Check if job was added / not rejected, and
   - if so, return result future to client.
   - otherwise go to (2) with server `n+1`

Edits:
#10 does contain three suggestions for handling this, although I don't think they apply here. (1) Even with arbitrary optimization of the serving parameters, we will still hit this issue, I think. (2) I don't want the request to block until it's been submitted; I want it to refuse the request so that `client` can try the next server in the list. (3) Would hide the load from the client.

**Comment by viksit** [comment]
I might be missing something but - why not use a simple load balancer such as nginx/haproxy or the amazon Elastic LB in case you're on AWS, for this? 

If it's the same model on all machines, a simple round robin should work, and you could expose a simple /status endpoint on your server which the load balancer knows how to read and not direct requests to?

**Comment by eriophora** [comment]
Not missing anything! The load balancer would totally work; the only issue
is the expense (theyre priced based on the number [and size!?] of the
requests) and it would be cheaper to just implement it myself--as you say,
I'm just using a round robin. But the nginx suggestion is interesting; Ill
look into it (coming from academia i realize i have very limited experience
in the practicalities of these kinda things). The round robin has nice
properties in terms of expected load value, but it could still potentially
dispatch many requests to the same machine. Hence it would be nice to query
the servers for their queue sizes or number of pending batches, for
instance.

On Saturday, April 30, 2016, Viksit Gaur <notifications@github.com> wrote:

> I might be missing something but - why not use a simple load balancer such
> as nginx/haproxy or the amazon Elastic LB in case you're on AWS, for this?
>
> If it's the same model on all machines, a simple round robin should work,
> and you could expose a simple /status endpoint on your server which the
> load balancer knows how to read and not direct requests to?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tensorflow/serving/issues/60#issuecomment-215983357>
>


-- 
Nick Dufour
Machine Learning Engineer
Neon Labs <https://www.neon-lab.com/>

**Comment by viksit** [comment]
Ah - I would say though, that not knowing how large your requests are, Amazon ELBs and Google Cloud charge $0.025 an hour, which for 30 days is $18, and $0.008 per GB, which for 100GB would be $0.8 :) [And less messing around with nginx config settings]

**Comment by yeputons** [comment]
@eriophora Have you looked at the <a href="https://tensorflow.github.io/serving/serving_inception">"Serving Inception Model with TensorFlow Serving and Kubernetes"</a> tutorial on TensorFlow? They show how to "pack" model into a Docker container and later run several containers with Kubernetes, which also provides a load balancer out-of-the-box (see <a href="https://kubernetes.io/docs/user-guide/load-balancer/">here</a>), it's even included in their example setting.

**Comment by Pingze-github** [comment]
I use Nginx to implement load banlancing of multiple dockerized Tensorflow-serving.
Because [Nginx starts to support gRPC from1.13.10](https://www.nginx.com/blog/nginx-1-13-10-grpc/).

I run multiple dockerized Tensorflow-serving servers to serve the same model, and proxy them by a nginx sever. I runned pressure test using jmeter, and then try to restart the containters. The result shows that the clients can have a continuous and uninterrupted service.

But there still one problem. Sometimes when I restart the containers, one request may be failed (only one because my model server deal one request at the same time). My clients report as below:

```
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.CANCELLED
	details = "Received http2 header with status: 502"
	debug_error_string = "{"created":"@1543454947.014000000","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":100,"grpc_message":"Received http2 header with status: 502","grpc_status":1,"value":"502"}"
```

I guess that because when I restarted the docker (within server), It's just dealing a request. And when its process received a stop signal, it closed immediatelly without finishing dealing that request.

In my HTTP web server, I always close the server receiving request immediatelly, but stop the process only after all requests have been dealed. I hope Tensorflow-serving can supports this default.

**Comment by Pingze-github** [comment]
> 
> 
> @eriophora Have you looked at the ["Serving Inception Model with TensorFlow Serving and Kubernetes"](https://tensorflow.github.io/serving/serving_inception) tutorial on TensorFlow? They show how to "pack" model into a Docker container and later run several containers with Kubernetes, which also provides a load balancer out-of-the-box (see [here](https://kubernetes.io/docs/user-guide/load-balancer/)), it's even included in their example setting.

The url has been removed. Have you read something that tells how to solve the problem below?
when RESTART a dockerized Tensorflow-serving sever, if the server just dealing a request, that request will failed. The client will receive an error:

```
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "{"created":"@1543458849.986000000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Stream removed","grpc_status":2}"
```

If this problem cannot be solved, service is not stable even using load banlancing.

**Comment by unclepeddy** [comment]
I may be missing something here but this is correct, if tf serving receives a sigstop it will be stopped - I'm not aware of any way to get around that. Please feel free to elaborate if I'm misunderstanding.
