### ISSUE TITLE
Sharing ServerCore with another gRPC service

### ISSUE THREAD

**Issue by nvgoldin** [tensorflow/serving#606]
I'm building another gRPC service, that needs to use ``ServerCore``, while trying to keep the current ``PredictionServiceImpl`` service in place at https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc#L185. 

The ``PredictionServiceImpl`` class is constructed with a `unique_ptr` to ServerCore, using move semantics. This is a problem as it means the ServerCore object can only be called inside the ``PredictionServiceImpl``, which in turn means that in order to add new gRPC calls that use ServerCore, the prediction service protobuff has to be updated directly(versus creating a new one, outside of the current source code).

I've been able to overcome this by changing the `unique_ptr` type in ``PredictionServiceImpl``, but I dislike this solution as it means diverging from the current `PredictionServiceImpl`, which I don't really need to change it(functionality wise at least).

Any ideas how to tackle this? Would a PR changing it to a pointer to unique_ptr make sense? (as done in https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/server_core.h#L150)?

**Comment by chrisolston** [comment]
It seems to me that you can just change PredictionServiceImpl to take a raw (not unique) pointer to the ServerCore object. The class is just defined and used in main.cc so you wouldn't be breaking an interface that's used elsewhere.

**Comment by nvgoldin** [comment]
Thanks, I tried to avoid changing it at all, but I guess as you say it is not that bad.
