### ISSUE TITLE
GPU Tensorflow Serving hangs

### ISSUE THREAD

**Issue by bloodymeli** [tensorflow/serving#608]
Hi,
I have successfully (?) compiled GPU tensorflow server, after a loose adaption of the instruction here:
[https://docs.bitnami.com/bch/how-to/enable-nvidia-gpu-tensorflow-serving/](url)

I have created the basic mnist model from the mnist example by using the command:
`python mnist_saved_model --training_iteration=2000 --model_version=2 /tmp/mnist_model`

but when I try to load this model to the server it hangs on restoring model.

If I try to plug the same to the CPU version by 
`tensorflow_model_server --port=9000 --model_name=mnist --model_base_path=/tmp/mnist-mode`

It works. Do I need to bazel build this model for the GPU version? If so, how to do it? I've tried:
`bazel build -c opt --config=cuda  --crosstool_top=@local_config_cuda//crosstool:toolchain //tensorflow_serving/example:mnist_saved_model`

but it failed with:
> no such package '@local_config_cuda//crosstool'

**Comment by vitalyli** [comment]
I believe I had seen this error; build GPU docker with Bazel 5.4; CUDA8 CUDNN6

**Comment by gautamvasudevan** [comment]
Try again with the latest version. Thanks!
