### ISSUE TITLE
c++ client for tensorflow serving

### ISSUE THREAD

**Issue by dailyncepu** [tensorflow/serving#625]
how can I develop a c++ client for tensorflow serving? ,I means like python version:
![image](https://user-images.githubusercontent.com/1561348/31767384-6a3fad9e-b4fd-11e7-9979-f3f5209dfe25.png)

**Comment by kirilg** [comment]
Did you take a look at [this example client](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_client.cc)?

**Comment by liang8065** [comment]
have you solve this problem? @dailyncepu

**Comment by kirilg** [comment]
The link included is an example client in C++. Closing the issue, but please reopen with additional details if there are any issues.
