### ISSUE TITLE
would `build_signature_def` accept `tf.Operation` as output ?

### ISSUE THREAD

**Issue by yupbank** [tensorflow/serving#629]
is it possible that user can specify some operation as a type of output as the saved model/ graph definition?

**Comment by kirilg** [comment]
Both inputs and outputs of the signature have to be Tensors, not ops - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/meta_graph.proto#L297

I'm not sure what it would mean for an op to be the output, can you describe your use case? You can specify the outputs of that op (themselves tensors) as the output.

**Comment by yupbank** [comment]
there are some ops that produce no tensor. 

i'm trying to pack a server with tf.write_file enabled. so the input would be both the input_file and outpt_file name

and the server auto saves the output into the output_file.

previously my client would need to that manually but with this server the client can be really thin

**Comment by yupbank** [comment]
i guess i can use `builder.add_meta_graph(save_ops.graph.as_graph_def)` ? but i'm not sure how it would go.. they are just protobuf under the hood anyway.

**Comment by yupbank** [comment]
Hi... i haven't find solutions to work around this..

imagine i have a service, which would save the inference result to a `gs://bucket` and return success. how can i achieve that if i still want to use C++ server? 

right now i'm using a python server and create extra `tf.write_file()` aside from the savedModel

**Comment by yupbank** [comment]
or.. would it being possible to make `tf.write_file()` return a status tensor as to make both read and write operation compatible with graph

**Comment by yupbank** [comment]
just in case anyone run into this.. i find a walk around 
```
def success_write(file_name_tensor, file_content_tensor):
    with tf.control_dependencies([tf.write_file(file_name_tensor, file_content_tensor)]):
        return tf.constant("success")

output_write_status_tensor =  success_write(file_name_tensor, file_content_tensor)
```
