### ISSUE TITLE
How can I reduce the interval `retrier` uses to reload a saved_model?

### ISSUE THREAD

**Issue by davidvuong** [tensorflow/serving#631]
> Loading servable: failed: Out of range: Read less bytes than requested

I would often encounter this problem when copying a model into `base_path`. Tensorflow-serving always seems itself after a while when it retries:

```
I tensorflow_serving/core/basic_manager.cc:705] Successfully reserved resources to load servable {name: XXX version: 1}
I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: XXX version: 1}
I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: XXX version: 1}
I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:360] Attempting to load native SavedModelBundle in bundle-shim from: /root/app/models/xxx/1
I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:236] Loading SavedModel from: /root/app/models/xxx/1
I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:284] Loading SavedModel: fail. Took 19917 microseconds.
E tensorflow_serving/util/retrier.cc:38] Loading servable: {name: XXX version: 1} failed: Out of range: Read less bytes than requested
... after a while
I tensorflow_serving/util/retrier.cc:34] Retrying of Loading servable: {name: XXX version: 1} retry: 1
I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:360] Attempting to load native SavedModelBundle in bundle-shim from: /root/appmodels/xxx/1
I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:236] Loading SavedModel from: /root/app/models/xxx/1
I external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GRID K520, pci bus id: 0000:00:03.0, compute capability: 3.0)
I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:155] Restoring SavedModel bundle.
I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:190] Running LegacyInitOp on SavedModel bundle.
I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:284] Loading SavedModel: success. Took 540109 microseconds.
I tensorflow_serving/servables/tensorflow/saved_model_bundle_factory.cc:93] Wrapping session to perform batch processing
I tensorflow_serving/servables/tensorflow/bundle_factory_util.cc:153] Wrapping session to perform batch processing
I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: XXX version: 1}
```

In this example, it took roughly 1 minute for serving to retry and successfully load the model.

```
2017-10-30 23:14:51.995377
2017-10-30 23:15:52.536522
```

I'm wondering if the config to reduce the interval between retries is exposed anywhere. 1 minute is awfully long. I had a look at the source and found the maximum retry attempts is exposed but couldn't find the interval.

I'm currently running TF v1.3.

**Comment by chrisolston** [comment]
This might happen if your model files are arriving on disk progressively (non-atomically). Perhaps the first attempt read just a prefix of one of the files, and thus failed. You could try making the writes atomic, e.g. by first writing to a temp location and then performing an atomic move (mv) operation.

The parameter that controls the load retry interval is AspiredVersionsManager::Options::load_retry_interval_micros. It is not currently piped through to a top level flag but if you like you can create a PR that would do that. If I'm not mistaken you would need to pipe it through ServerCore and to main.cc. You can copy what is done for max_num_load_retries, which *is* piped through, so it would be easy to set up.

**Comment by davidvuong** [comment]
Thanks, that really helped. I've made your suggested changes on how I should be copying models to tensorflow-serving. After a few rounds of testing, I'm no longer seeing this error. Regarding the work to pipe through `load_retry_interval_micros`, I can give it a shot.

**Comment by sukritiramesh** [comment]
Thanks @davidvuong for reporting back. Resolving this issue.
