### ISSUE TITLE
go code by protoc have `import cycle not allowed` err

### ISSUE THREAD

**Issue by llvim** [tensorflow/serving#634]
I use go to call grpc serving's grpc service(already succeed with java)

In  https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/predict.proto#L7
```proto
import "tensorflow_serving/apis/model.proto";
```
will make `tensorflow_serving/apis/predict.pb.go` by protoc
```
import tensorflow_serving1 "tensorflow_serving/apis"
```
this line of code make the err `import cycle not allowed`, this there any way work around?

**Comment by zachgrayio** [comment]
I'm also running into this (or a very similar) issue, there's import cycles in pb generated files. Any thoughts?

**Comment by frpunzalan** [comment]
+1
prediction_log seems to require core in
``package tensorflow_serving
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "tensorflow_serving/core"

**Comment by frpunzalan** [comment]
I tried to build a serving go client from here https://mauri870.github.io/blog/posts/tensorflow-serving-inception-go
but the following error showed up. Adding the tensorflow_serving/core in the packages results in import cycle. Anyone knows how to fix this?

vendor/tensorflow_serving/apis/prediction_log.pb.go:9:8: cannot find package "tensorflow_serving/core" in any of:
        /home/../vendor/tensorflow_serving/core (vendor tree)
        /usr/local/go/src/tensorflow_serving/core (from $GOROOT)

**Comment by biolee** [comment]
maybe i can help by submmiting a pr this weekend

**Comment by kavemun** [comment]
I am having the same problem as @frpunzalan from the same tutorial 
error says : 
import cycle not allowed
package .
	imports tensorflow_serving/apis
	imports tensorflow_serving/core
	imports tensorflow_serving/apis

**Comment by harshini-gadige** [comment]
@llvim  -  Hi, any update on the PR ?

**Comment by hgadig** [comment]
Closing this at it is in "awaiting response" status for more than a week. Feel free to add comments(if any) or share the PR details, we will reopen the issue. Thanks !
