### ISSUE TITLE
use this great tool for other models

### ISSUE THREAD

**Issue by geoHeil** [tensorflow/serving#637]
Hi,
reading https://research.googleblog.com/2017/11/latest-innovations-in-tensorflow-serving.html I learnt that this great tool can be used to server other models as well. 
But so far I could not find much documentation about i.e. serving a sklearn / xgboost / R / ... via TensorFlow serving.

It would be great if you could point me to some resources

**Comment by eggie5** [comment]
Serving has an extensible API that will allow you to define arbitrary Servable that conform to an interface that Serving understands. So what I think it means is that you can in theory, for example, run a scikit, etc model in Serving if you write a Servable plugin.

**Comment by geoHeil** [comment]
thx.

**Comment by hzy001** [comment]
> Hi,
> reading https://research.googleblog.com/2017/11/latest-innovations-in-tensorflow-serving.html I learnt that this great tool can be used to server other models as well.
> But so far I could not find much documentation about i.e. serving a sklearn / xgboost / R / ... via TensorFlow serving.
> 
> It would be great if you could point me to some resources

I have implemented [XGBoost Serving](https://github.com/iqiyi/xgboost-serving) that is a fork of TensorFlow Serving. It supports serving XGBoost models and XGBoost && FM models. You can read the README for more details and try it in a few minutes. If you encounter any problems, please submit an issue or email me directly.
