### ISSUE TITLE
tensorflow_serving build testing with gpu fails after successful build

### ISSUE THREAD

**Issue by donghwicha** [tensorflow/serving#642]
Hello. 

I built and tested tensorflow_serving with cuda option.
but some units keeps failing on **unit testing** as shown below. 
Is this expected as usual with GPU? 

## test command 
bazel test -c opt --config=cuda  --crosstool_top=@local_config_cuda//crosstool:toolchain  tensorflow_serving/...

## Test Passed 
> INFO: Elapsed time: 2380.277s, Critical Path: 737.43s
> //tensorflow_serving/batching:batch_scheduler_retrier_test               PASSED in 0.3s
> //tensorflow_serving/batching:batching_session_test                      PASSED in 2.1s
> //tensorflow_serving/batching:batching_util_test                         PASSED in 0.3s
> //tensorflow_serving/batching:streaming_batch_scheduler_test             PASSED in 4.1s
> //tensorflow_serving/batching/test_util:puppet_batch_scheduler_test      PASSED in 0.4s
> //tensorflow_serving/core:aspired_version_policy_test                    PASSED in 0.1s
> //tensorflow_serving/core:aspired_versions_manager_benchmark             PASSED in 27.9s
> //tensorflow_serving/core:aspired_versions_manager_builder_test          PASSED in 0.5s
> //tensorflow_serving/core:aspired_versions_manager_test                  PASSED in 6.2s
> //tensorflow_serving/core:availability_preserving_policy_test            PASSED in 0.1s
> //tensorflow_serving/core:basic_manager_test                             PASSED in 7.1s
> //tensorflow_serving/core:caching_manager_test                           PASSED in 0.2s
> //tensorflow_serving/core:dynamic_source_router_test                     PASSED in 0.3s
> //tensorflow_serving/core:loader_harness_test                            PASSED in 0.5s
> //tensorflow_serving/core:log_collector_test                             PASSED in 0.1s
> //tensorflow_serving/core:manager_test                                   PASSED in 0.1s
> //tensorflow_serving/core:request_logger_test                            PASSED in 0.1s
> //tensorflow_serving/core:resource_preserving_policy_test                PASSED in 0.1s
> //tensorflow_serving/core:servable_data_test                             PASSED in 0.1s
> //tensorflow_serving/core:servable_id_test                               PASSED in 0.1s
> //tensorflow_serving/core:servable_state_monitor_test                    PASSED in 0.3s
> //tensorflow_serving/core:server_request_logger_test                     PASSED in 0.1s
> //tensorflow_serving/core:simple_loader_test                             PASSED in 0.1s
> //tensorflow_serving/core:source_adapter_test                            PASSED in 1.1s
> //tensorflow_serving/core:source_router_test                             PASSED in 2.1s
> //tensorflow_serving/core:static_manager_test                            PASSED in 0.1s
> //tensorflow_serving/core:static_source_router_test                      PASSED in 0.5s
> //tensorflow_serving/core:storage_path_test                              PASSED in 0.1s
> //tensorflow_serving/model_servers:server_core_test                      PASSED in 32.4s
> //tensorflow_serving/resources:resource_tracker_test                     PASSED in 0.1s
> //tensorflow_serving/resources:resource_util_test                        PASSED in 1.1s
> //tensorflow_serving/servables/hashmap:hashmap_source_adapter_test       PASSED in 0.7s
> //tensorflow_serving/servables/tensorflow:classifier_test                PASSED in 0.3s
> //tensorflow_serving/servables/tensorflow:curried_session_test           PASSED in 0.3s
> //tensorflow_serving/servables/tensorflow:regressor_test                 PASSED in 0.7s
> //tensorflow_serving/servables/tensorflow:saved_model_bundle_factory_test PASSED in 1.8s
> //tensorflow_serving/servables/tensorflow:saved_model_bundle_source_adapter_test PASSED in 1.7s
> //tensorflow_serving/servables/tensorflow:session_bundle_factory_test    PASSED in 2.0s
> //tensorflow_serving/servables/tensorflow:session_bundle_source_adapter_test PASSED in 1.6s
> //tensorflow_serving/servables/tensorflow:simple_servers_test            PASSED in 1.4s
> //tensorflow_serving/servables/tensorflow:util_test                      PASSED in 0.1s
> //tensorflow_serving/sources/storage_path:file_system_storage_path_source_test PASSED in 0.3s
> //tensorflow_serving/sources/storage_path:static_storage_path_source_test PASSED in 0.1s
> //tensorflow_serving/util:any_ptr_test                                   PASSED in 0.1s
> //tensorflow_serving/util:class_registration_test                        PASSED in 0.1s
> //tensorflow_serving/util:cleanup_test                                   PASSED in 0.3s
> //tensorflow_serving/util:event_bus_test                                 PASSED in 0.3s
> //tensorflow_serving/util:fast_read_dynamic_ptr_benchmark                PASSED in 26.5s
> //tensorflow_serving/util:fast_read_dynamic_ptr_test                     PASSED in 0.3s
> //tensorflow_serving/util:inline_executor_test                           PASSED in 0.3s
> //tensorflow_serving/util:observer_test                                  PASSED in 0.2s
> //tensorflow_serving/util:optional_test                                  PASSED in 0.1s
> //tensorflow_serving/util:retrier_test                                   PASSED in 0.1s
> //tensorflow_serving/util:threadpool_executor_test                       PASSED in 0.2s
> //tensorflow_serving/util:unique_ptr_with_deps_test                      PASSED in 0.1s

## Test Failed
> //tensorflow_serving/model_servers:tensorflow_model_server_test          **FAILED** in 251.8s
>   /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/tf_serving/bazel-out/local_linux-opt/testlogs/tensorflow_serving/model_servers/tensorflow_model_server_test/test.log
> //tensorflow_serving/servables/tensorflow:bundle_factory_util_test       **FAILED** in 1.4s
>   /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/tf_serving/bazel-out/local_linux-opt/testlogs/tensorflow_serving/servables/tensorflow/bundle_factory_util_test/test.log
> //tensorflow_serving/servables/tensorflow:get_model_metadata_impl_test   **FAILED** in 2.1s
>   /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/tf_serving/bazel-out/local_linux-opt/testlogs/tensorflow_serving/servables/tensorflow/get_model_metadata_impl_test/test.log
> //tensorflow_serving/servables/tensorflow:multi_inference_test           **FAILED** in 31.0s
>   /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/tf_serving/bazel-out/local_linux-opt/testlogs/tensorflow_serving/servables/tensorflow/multi_inference_test/test.log
> //tensorflow_serving/servables/tensorflow:predict_impl_test              **FAILED** in 33.8s
>   /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/tf_serving/bazel-out/local_linux-opt/testlogs/tensorflow_serving/servables/tensorflow/predict_impl_test/test.log
> Executed 60 out of 60 tests: 55 tests pass and 5 fail locally

**Comment by gautamvasudevan** [comment]
Closing - please see the latest [Docker examples](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) for bringing up a build environment.
