### ISSUE TITLE
building tensorflow_serving/apis fails

### ISSUE THREAD

**Issue by donghwicha** [tensorflow/serving#643]
Hello. 
I'm trying to build "tensorflow_serving/apis" as shown below
but it fails. Is there anything missing? 

I want to build python3 compatible whl of tensorflow_serving_apis

> bazel build -c opt  tensorflow_serving/apis/...
> ...
> bazel-out/local-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
> INFO: Elapsed time: 112.622s, Critical Path: 20.50s
>

**Comment by kirilg** [comment]
That seems to be a warning, can you please include the error message with relevant context in the logs?

**Comment by donghwicha** [comment]
No error but just warnings and the command line ends without any output. Could you share any doc if it exists? I will try to contribute if possible.

**Comment by kirilg** [comment]
If there were no errors it sounds like the build succeeded. You can find the output under the bazel-bin/tensorflow_serving/... directory. You were only building the apis directory so it will only generate some proto files, no binaries.
