### ISSUE TITLE
update grpc version to 1.7.0

### ISSUE THREAD

**Issue by donghwicha** [tensorflow/serving#644]
Hello. 

grpcio should be upgraded to grpcio (1.7.0)

The available version of it on https://testpypi.python.org/simple/grpcio/ is 1.5.0
and client fails. 

https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel-gpu#L33

> 
> bazel-bin/tensorflow_serving/example/mnist_client --num_tests=1000 --server=localhost:9000
> D1105 17:42:12.649371318    3474 ev_posix.c:101]             Using polling engine: poll
> Extracting /tmp/train-images-idx3-ubyte.gz
> Extracting /tmp/train-labels-idx1-ubyte.gz
> Extracting /tmp/t10k-images-idx3-ubyte.gz
> Extracting /tmp/t10k-labels-idx1-ubyte.gz
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 658, in _call_spin
>     completed_call = event.tag(event)
>   File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 174, in handle_event
>     callback()
>   File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 294, in <lambda>
>     self._state.callbacks.append(lambda: fn(self))
>   File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 135, in <lambda>
>     self._future.add_done_callback(lambda ignored_callback: fn(self))
>   File "/serving/bazel-bin/tensorflow_serving/example/mnist_client.runfiles/tf_serving/tensorflow_serving/example/mnist_client.py", line 107, in _callback
>     exception = result_future.exception()
>   File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 120, in exception
>     return _abortion_error(rpc_error_call)
>   File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 74, in _abortion_error
>     code = rpc_error_call.code()
> AttributeError: 'NoneType' object has no attribute 'code'
>

**Comment by gautamvasudevan** [comment]
Closing due to staleness.
