### ISSUE TITLE
failed call to cuInit: CUresult(-1) ; Centos7 kubernetes pod 

### ISSUE THREAD

**Issue by sub-mod** [tensorflow/serving#646]
Issue
=====
When I run tensorflow_model_Server with mnist model the tensorflow_model_Server is unable to locate cuda libs 

Environment
=============
I am running tensorflow_model_Server in kubernetes pod with GPU support enabled.
The docker image has CUDA-8 and CuDNN-6.0 installed.

```
# echo -e “$CUDA_HOME \\n $CUDA_PATH \\n $LD_LIBRARY_PATH”
“/usr/local/cuda
 /usr/local/cuda
 /usr/local/cuda/lib64/stubs/:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64;”
```

```
sh-4.2$ ls -l /usr/local/cuda/lib64/stubs/
total 1652
-rwxr-xr-x. 1 root root  52208 Jun  6 18:47 libcublas.so
-rwxr-xr-x. 1 root root  40096 Jan 13  2017 libcuda.so
lrwxrwxrwx. 1 root root     38 Nov  5 23:23 libcuda.so.1 -> /usr/local/cuda/lib64/stubs/libcuda.so
-rwxr-xr-x. 1 root root  11616 Jan 13  2017 libcufft.so
-rwxr-xr-x. 1 root root  10696 Jan 13  2017 libcufftw.so
-rwxr-xr-x. 1 root root   7640 Jan 13  2017 libcurand.so
-rwxr-xr-x. 1 root root  57680 Jan 13  2017 libcusolver.so
-rwxr-xr-x. 1 root root  83136 Jan 13  2017 libcusparse.so
-rwxr-xr-x. 1 root root   6528 Jan 13  2017 libnppc.so
-rwxr-xr-x. 1 root root 597936 Jan 13  2017 libnppi.so
-rwxr-xr-x. 1 root root 102760 Jan 13  2017 libnppial.so
-rwxr-xr-x. 1 root root  51584 Jan 13  2017 libnppicc.so
-rwxr-xr-x. 1 root root   7640 Jan 13  2017 libnppicom.so
-rwxr-xr-x. 1 root root  84352 Jan 13  2017 libnppidei.so
-rwxr-xr-x. 1 root root 109840 Jan 13  2017 libnppif.so
-rwxr-xr-x. 1 root root  38008 Jan 13  2017 libnppig.so
-rwxr-xr-x. 1 root root  15712 Jan 13  2017 libnppim.so
-rwxr-xr-x. 1 root root 190848 Jan 13  2017 libnppist.so
-rwxr-xr-x. 1 root root   7848 Jan 13  2017 libnppisu.so
-rwxr-xr-x. 1 root root  28944 Jan 13  2017 libnppitc.so
-rwxr-xr-x. 1 root root 106952 Jan 13  2017 libnpps.so
-rwxr-xr-x. 1 root root   6872 Jan 13  2017 libnvgraph.so
-rwxr-xr-x. 1 root root  24632 Jan 13  2017 libnvidia-ml.so
-rwxr-xr-x. 1 root root   5176 Jan 13  2017 libnvrtc.so
sh-4.2$
```

```
# nvidia-docker version
NVIDIA Docker: 1.0.1
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-61.git85d7426.el7.x86_64
 Go version:      go1.8.3
 Git commit:      85d7426/1.12.6
 Built:           Tue Sep 26 15:30:51 2017
 OS/Arch:         linux/amd64
Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-61.git85d7426.el7.x86_64
 Go version:      go1.8.3
 Git commit:      85d7426/1.12.6
 Built:           Tue Sep 26 15:30:51 2017
 OS/Arch:         linux/amd64
```

```
# uname -r
3.10.0-693.el7.x86_64
```

```
# nvidia-smi
Sun Nov  5 23:34:28 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|=================+======================+=============|
|   0  Tesla M60           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   33C    P8    13W / 150W |     11MiB /  7613MiB |      0%      Default |
```

logs
=======
2017-11-05 23:33:05.414050: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUresult(-1)
2017-11-05 23:33:05.414106: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: tf-app-server-1-w2sk5
2017-11-05 23:33:05.414119: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: tf-app-server-1-w2sk5
2017-11-05 23:33:05.414334: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to findlibcuda.so DSO loaded into this program
2017-11-05 23:33:05.414371: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIXx86_64 Kernel Module  384.81  Sat Sep  2 02:43:11 PDT 2017
GCC version:  gcc version 4.8.5 20150623 (Red Hat 4.8.5-22) (GCC)
"""
2017-11-05 23:33:05.414424: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 384.81.0
2017-11-05 23:33:05.438206: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:155] Restoring SavedModel bundle.

**Comment by ralogon** [comment]
I have exactly the same problem when running regular tensorflow on my CentOS cluster,

Have you solved the problem?

**Comment by sub-mod** [comment]
Yes i was able to solve it.
I was on CUDA-8 and CuDNN-6.0
I moved to CUDA-9 and CuDNN-7.0
