### ISSUE TITLE
ImportError: No module named tensorflow_serving.session_bundle

### ISSUE THREAD

**Issue by shahinsh** [tensorflow/serving#65]
I installed and configured Tensorflow Serving successfully . I ran the test command as well and everything was successful .

Now I'm trying to use the MNIST tutorial and when I put  
` from tensorflow_serving.session_bundle import exporter`

I get following error ,

`ImportError: No module named tensorflow_serving.session_bundle`

I wonder what the problem is , my operating system is CentOs and I use the latest version of Tensoflow and Tensorflow serving without GPU support .

**Comment by kirilg** [comment]
TensorFlow Serving doesn't get installed as a system library, it's a set of libraries that you can link in directly though. You'd need to have the include statement you have `from tensorflow_serving.session_bundle import exporter` in you python file, and the dependency `tensorflow_serving/session_bundle:exporter` in your BUILD file.

See for example this python include: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/session_bundle/exporter_test.py#L28
and BUILD file: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/session_bundle/BUILD#L48
