### ISSUE TITLE
tensorflow_model_server: not found

### ISSUE THREAD

**Issue by Higgins2718** [tensorflow/serving#651]
I'm trying to deploy the Inception-v3 model using the tutorial at [Serving Inception Model with TensorFlow Serving and Kubernetes](https://www.tensorflow.org/serving/serving_inception)

Everything went fine until I ran the command:

`kubectl create -f tensorflow_serving/example/inception_k8s.yaml`

The terminal output suggested that the service "inception-service" and the deployment "inception-deployment" were successfully created.
However, when I ran:
`kubectl get pods`
I received this output:
`NAME                                    READY     STATUS             RESTARTS   AGE
inception-deployment-2217120516-ntmfl   0/1       CrashLoopBackOff   6          8m
inception-deployment-2217120516-s8xlx   0/1       CrashLoopBackOff   6          8m
inception-deployment-2217120516-tnzbl   0/1       CrashLoopBackOff   6          8m
`

I got information on the error by getting the logs for the first pod.
Running:
`kubectl logs inception-deployment-2217120516-ntmfl`
returned this:
/bin/sh: 1: serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server: not found

I was able to run the server locally, however, the image used in the tensorflow-serving inception-k8s.yaml file does not have a model server.

Please fix this bug. I did everything correctly, as shown in the linked tensorflow serving tutorial.

**Comment by LingboTang** [comment]
I got the same error when I configured the containers with my own gcr url, but I'm getting the same error here.

**Comment by LingboTang** [comment]
Try this dup: #287 , you should confirm your working directory of you docker containers, your path to `serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server` might be wrong. I request someone close this issue now.

**Comment by sukritiramesh** [comment]
@Higgins2718 @LingboTang Please see related issue and follow-up with questions, if any.

**Comment by gautamkmr** [comment]
Just realized that tensorflow_model_server binary moved to /usr/bin folder
