### ISSUE TITLE
build pip package and get a not valid wheel filename

### ISSUE THREAD

**Issue by Leechen2014** [tensorflow/serving#657]
i read [tensroflow install from source ](https://www.tensorflow.org/install/install_sources) and [tensorflow serving install from source](https://www.tensorflow.org/serving/setup) 
i find when i install tensorflow from source , i can get a *whl by `bazel-bin/tensorflow/tools/pip_package/build_pip_package` 

but when i install tensorlow serving from source , i only find run this server by baze-bin, and when i run 'bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package' , and get a ` tensorflow_serving_api-undefined-py2-none-any.whl` , which is  not a valid wheel filename. 

why ? and i can run `bazel test -c opt tensorflow_serving/... `success

**Comment by kirilg** [comment]
The PIP package is just for the python API, not the actual server. The [install documentation](https://www.tensorflow.org/serving/setup) contains instructions to install the server using `apt-get install` if you'd like, or you can compile it locally and run using bazel-bin like you mentioned.

The [basic tutorial](https://www.tensorflow.org/serving/serving_basic) contains instructions for both building/running from source and using apt-get/PIP.

**Comment by jinpeng** [comment]
@Leechen2014 You could edit tensorflow_serving/tools/pip_package/setup.py and change verison from 'undefined' to a version string, like '1.4.0', then you could build pip package wheel with correct name.
