### ISSUE TITLE
Python Client 

### ISSUE THREAD

**Issue by Kingeng** [tensorflow/serving#658]
Hi 

I try to serve NSFW tensorflow model which in it's code use a feed_dict for predict
now i wrote a client (read grpc document & use inception_client ) and get error : 
 Inputs expected to be in the set {inputs}.

can any one help ? 

https://github.com/mdietrichstein/tensorflow-open_nsfw/issues/5

**Comment by chrisolston** [comment]
Just based on a quick glance, at the error message and your code, I noticed:
error: Inputs expected to be in the set {inputs}.
versus
code: req=request.inputs['input'].CopyFrom(data)

So perhaps it is expecting you to populate an input called "inputs" but you are instead populating one called "input" (singular; no 's').

**Comment by zhapeng** [comment]
Hi, I am confused , when request.inputs is two data, like {'x':data, 'p':prob}, how to deal ?

**Comment by chrisolston** [comment]
In that case you would write:
req=request.inputs['x'].CopyFrom(data)
req=request.inputs['p'].CopyFrom(other_data)

I would suggest catting the meta-graph-def of the SavedModel you are trying to use, to find out what signature it expects.

**Comment by sukritiramesh** [comment]
To see the available signatures in the SavedModel (and the specific meta graph def), you can also use the SavedModel command-line tool, that allows one-off inspections and executions of the SavedModel. See: https://www.tensorflow.org/versions/master/programmers_guide/saved_model#cli_to_inspect_and_execute_savedmodel.
