### ISSUE TITLE
How can i use multiple server in client?

### ISSUE THREAD

**Issue by xf4fresh** [tensorflow/serving#662]
If I deploy services on multiple machines, how do I call them in the client?
We can find the demo code `channel = implementations.insecure_channel(host, int(port))` in the [mnist_client.py](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_client.py#L141). But It needs to be pointed out the host and port, which can only call one server. 
May I read 'grpc' doc?
Is Load Balancing in gRPC a solution?
Thanks for your reply.

**Comment by kirilg** [comment]
@nathanielmanistaatgoogle what's the recommended approach to extend a channel/stub to multiple servers?

**Comment by nathanielmanistaatgoogle** [comment]
@markdroth: can you comment on the current state of load balancing or other solutions for this use case?

**Comment by markdroth** [comment]
The easiest thing would probably be to use the `round_robin` LB policy, which you can select via the `grpc.lb_policy_name` channel arg.  However, when used with DNS, this probably requires that all servers use the same port number.

**Comment by gautamvasudevan** [comment]
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!
