### ISSUE TITLE
Feature Request: Continuous Deployment of a Single Model

### ISSUE THREAD

**Issue by knightcode** [tensorflow/serving#664]
I'm trying to figure out how to set up and support continuous deployment with the model server, and I'm stuck at the point when the server automatically unloads an old version of a model. ....How I see it working:
1. A dev alters the model definition, trains, and evaluates the model in a local environment
1. The model is exported to the `model_base_path` directory to be picked up by the model server
1. The production webserver (or the like) continues running with the old model using possibly incompatible, outdated software
1. The version number can be obtained from the path returned after exporting
1. A dev makes sufficient changes to the software to properly support the new version, which includes hard coding the version number to set in each prediction request to the model server
1. The changes are committed to version management
1. A CI/CD server goes to town running tests on the software and the new version of the model.
1. The tests pass (hurray!!) and the code is shipped out to production
1. The universe is once again using a single version of the model

I'm new to TF, so that, please, disabuse me of any preconceived notions I bring to this. I finally got all this set up, and my first request with an old version number got a StatusCode.NOT_FOUND response.

It doesn't seem appropriate to commit a tarball of the exported model to the repo, but that would let the CI server unpack it at each stage of the pipeline. No matter what though, obliterating the old version in production as soon as the new is detected creates a moment in time where the model server and the web server are out of sync: either we update the code on the webserver first and it can't find the newer model, or we update the model server first and the outdated webserver code starts getting errors for like up to a minute. Is there a way to handle this?

**Comment by vitalyli** [comment]
By default only latest model is running. You need to configure it to run more than one model.

**Comment by chrisolston** [comment]
Indeed, as vitalyli says you can override the default behavior here. See 'model_version_policy' in https://github.com/tensorflow/serving/blob/master/tensorflow_serving/config/model_server_config.proto

**Comment by sukritiramesh** [comment]
@knightcode please loop back if you have additional questions.
