### ISSUE TITLE
Should I build tensorflow_serving module every time?

### ISSUE THREAD

**Issue by posutsai** [tensorflow/serving#665]
I installed and tried to serve Inception model with tfserving successfully. After that I try to apply it on my own model.
But when I looked into source code of the [example client](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_client.py), it depend on `tensorflow_serving` module which was built by bazel. So here comes the problem, should I copy recursively whole tensorflow_serving directory beneath serving to my repo and build it additionally, or just copy the file in bazel-bin directory. In my opinion, I would choose first way, however that means I would spend a lot of time building the module each time. Seems not to be a great way. Could someone offer me a better way to do this?

**Comment by gautamvasudevan** [comment]
You should be able to just install the [TensorFlow Serving APIs from PyPI](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md#tensorflow-serving-python-api-pip-package-pip)
