### ISSUE TITLE
[Question] loading models with tensorflow_model_server from s3

### ISSUE THREAD

**Issue by mateusz-callstats** [tensorflow/serving#669]
Like in the topic - loading model from s3 is not working for me. As per #615 I compiled the server using: 
bazel build -s -c opt --define with_s3_support=true //tensorflow_serving/model_servers:tensorflow_model_server

and now when I run it using
bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --model_base_path=s3://bucketname/
I'm getting FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3://bucketname/ for servable default

Any tips on how to fix that?

**Comment by zacharynevin** [comment]
This isn't going to work because you can't query the filesystem contents in S3 using `ls` - you have to use the S3 API and Tensorflow Serving isn't going to magically know how to do that.

What you should do is download the file from S3 into a folder on your host, and reference that. If you need the model to be automatically updated from S3, you can run a background script that periodically polls S3 and replaces the model files when they are updated.

**Comment by zacharynevin** [comment]
I misread - Tensorflow Serving appears to have S3 support based on the `with_s3_support=true ` flag. Sorry

**Comment by eggie5** [comment]
27 days ago: https://github.com/tensorflow/serving/commit/2191b205a28c871a51ab8d07d2381c9b60e3c793

**Comment by mateusz-callstats** [comment]
I'm aware of that commit, but I'm having troubles with how that's supposed to help me?

**Comment by zacharynevin** [comment]
@mateusz-callstats I believe @eggie5 is trying to tell you that your Tensorflow Serving version may be out of date? Maybe try recompiling to the latest version?

**Comment by mateusz-callstats** [comment]
@eggie5 @zacharynevin Oh it was freshly pulled, definitely not over a month ago

**Comment by kirilg** [comment]
Fresh TF Serving (master branch) pulled now should in theory work. In addition to using with_s3_support when building, could you please confirm that you also ran ./configure on TensorFlow and specified to configure TF with s3 support?

**Comment by sukritiramesh** [comment]
@mateusz-callstats Can you confirm if this works for you now with the master branch? (See comment from @kirilg for details)

**Comment by mateusz-callstats** [comment]
I have long given up on the issue and went for a workaround as suggested by @zacharynevin - forgot to keep checking here after that. The workaround works quite well so I'm afraid I won't have time to check that in near future. All I can say is that back when it didn't work I pulled fresh master, ran ./configure to specify s3 support, built it, and it did not work (as described in original message)

**Comment by timonbimon** [comment]
I still get the same error

`tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:370] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3://mybucket/saved_model/ for servable test`

The S3 support works when using it with Tensorflow, but not when trying to use an s3 base path with tensorflow_model_server. I didn't build it myself, but just used `apt-get install`. 

Should this be working by now? (or in other words: did I do sth wrong or is it not my bad? ;)

**Comment by kirilg** [comment]
I believe the last version that you can install with apt-get did not include the change and was not built with S3 support, so it's not expected to work. Please try to build it from source if you'd like S3 support, and make sure to:
1) run ./configure on TensorFlow and specify to include S3.
2) bazel build -s -c opt --define with_s3_support=true tensorflow_serving/model_servers:tensorflow_model_server

**Comment by gautamvasudevan** [comment]
Closing due to staleness.
