### ISSUE TITLE
service ping

### ISSUE THREAD

**Issue by mazorigal** [tensorflow/serving#671]
Hi,

is there any option to ping tensorflow serving, in order to check if the service is up and running ?
That is especially helpful in environments where each service monitored via ping and health endpoints.

Thanks,

**Comment by bknl** [comment]
As far as I know the tensorflow_model_server does not support a health check RPC as in 

 https://github.com/grpc/grpc/blob/master/doc/health-checking.md

What I've used instead in my project are GetModelMetadataRequest calls to the servers to check for liveness and model presence.

**Comment by mazorigal** [comment]
Thanks, I eventually ended up doing same, but still, feels as not the correct approach :-)
I think that they can implement sort of ping/health end point

**Comment by kkozmic** [comment]
Another scenario (which I'm facing) is using TF Serving behind ELB (Network Load Balancer to be precise) where you don't control what the health request looks like.

Would there be any interest in adding that feature?

**Comment by chrisolston** [comment]
Sounds like a reasonable feature to add. We would want to do it in a separate RPC service (not the model inference one). Contributions welcome :)

**Comment by marceloboeira** [comment]
It does make a lot of sense, on my scenario, running under a k8s cluster, the `/healthz` endpoint helps a lot to keep the infrastructure monitored, rather than collecting errors from the clients.

**Comment by ghisvail** [comment]
I'd be interested to know how `serving` is used in production without some form of health checking. What do people rely on in production then? I like @bknl's approach as a temporary fallback.

**Comment by vitalyli** [comment]
If you know the list of model names, then it can be done using GetModelMetadata, except there is a bug in there: https://github.com/tensorflow/serving/issues/784

**Comment by Zhiqiang-Ye** [comment]
I have the same requirement to get model status. I find some new protos in tf-serving 1.5 such as get_model_status.proto and model_service.proto, but have no idea how to use them. Reading the java code generated from these proto files, it does look like a separate RPC service mentioned by @chrisolston . I ask the same question on stackoverflow: [how-to-get-model-status](https://stackoverflow.com/questions/49051968/how-to-get-model-status-in-tensorflow-serving). Could anyone explain it a bit?

**Comment by AswathKiruba** [comment]
@bknl @mazorigal  Could please let me know how to use GetModelMetadataRequest calls to the servers to check for liveness and model presence, as I am not able to use the GetModelStatus API #961 . Thank in advance

**Comment by gmiejski** [comment]
Any way to use this GetModelMetadataRequest as a healthcheck via REST API? Or only predict API is exposed right now?

**Comment by AswathKiruba** [comment]
@mazorigal @bknl. Considering the Restful API implementation in TFS >= 1.8.0, is there any way can we use the RESTful API to access GetModelMetadataRequest or the GetModelStatus. Please let me know.

**Comment by etheleon** [comment]
@ianchen06

**Comment by b-r-oleary** [comment]
It looks like the a REST endpoint has now been added here https://github.com/tensorflow/serving/commit/00e459f1604c40c073cbb9cb92d72cb6a88be9cd to access `GetModelStatus`, which can reasonably be used for a server health check.

Nevertheless, I wanted to jump in here to not that I would also be interested in a `status` REST endpoint that could be used as a generic health check for the server.

**Comment by neil-119** [comment]
Agreed, we need a legit health check REST endpoint too.

**Comment by helmuthva** [comment]
You can easily provide a health endpoint as such: https://github.com/helmuthva/jetson/blob/master/workflow/deploy/tensorflow-serving/src/webservice/health/healthz.py

**Comment by jxtps** [comment]
@helmuthva Yes, but then you need to make sure that your health check service keeps running too ;)

**Comment by yuzliu** [comment]
It is important to have an appropriate health check endpoint so users can add liveness check.

**Comment by salanki** [comment]
Is there any endpoint, at all that can be used as a health check for the server itself ie. when serving multiple models?

**Comment by cgmckeever** [comment]
Following .. Having an issue where the time to fully stand up TensorFlow after a docker is started is sometimes longer than the healthcheck against the LoadBalancer causing a cycle of failovers. Would be nice to have something that responds quicker while the system starts up

**Comment by codycollier** [comment]
For anyone interested, I made a small tensorflow serving health probe.  It communicates with tensorflow serving over grpc, calling the `ModelService.GetModelStatus()` rpc, and ensures a model status of `AVAILABLE`.  It can be used as a kubernetes exec probe, similar to [grpc_health_probe](https://github.com/grpc-ecosystem/grpc-health-probe).

tfs_model_status_probe - TensorFlow Serving Model Status Probe
https://github.com/codycollier/tfs-model-status-probe

**Comment by pindinagesh** [comment]
Hi @mazorigal 

Could you kindly look at this [PR](https://github.com/mKaloer/TFServingCache/pull/10) and confirm if this issue can be closed? Thanks

**Comment by pindinagesh** [comment]
Hi @mazorigal 

Closing this issue due to lack of inactivity. Please feel free to reopen if this still exists.Thanks

**Comment by lsnetsinger** [comment]
Has a health check been added?   If so can you point me to it?  I think everyone on this issue agrees a health check is necessary.   Why would the ticket be closed due to inactivity?

**Comment by elina-israyelyan** [comment]
> As far as I know the tensorflow_model_server does not support a health check RPC as in
> 
> https://github.com/grpc/grpc/blob/master/doc/health-checking.md
> 
> What I've used instead in my project are GetModelMetadataRequest calls to the servers to check for liveness and model presence.

I am trying to do this but the GetModelMetadata succeeds event though the Predict doesn't.
when I am making the service unavailable stub.Predict throws the following error:
`<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
`
However GetModelMetadata does not throw any error.

**Comment by jCrompton** [comment]
Why is this closed? How is it that a flagship google product (tensorflow serving) doesn’t implement its own company’s health check protocol? Seems wild to me
