### ISSUE TITLE
Official docker images

### ISSUE THREAD

**Issue by vaibhavsood** [tensorflow/serving#672]
Hi, 

Are there any docker images which are officially supported for tensorflow serving? I could not find one here: https://hub.docker.com/explore/

If not, are there any plans to publish an official image on dockerhub? thanks!

**Comment by kirilg** [comment]
Unfortunately we don't currently have official images on dockerhub, see https://github.com/tensorflow/serving/issues/513 as a duplicate issue. Looks like there are some unofficial images provided by the community.

Note also that if you want to use TF Serving 1.4, it can be easy to setup and install the ModelServer with `apt-get install` (see https://www.tensorflow.org/serving/setup) in a clean docker image using our dockerfile.
