### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by maybeluo** [tensorflow/serving#673]
I'm installing `serving` from source. I clone the latest serving from github and run `./configure` in serving/tensorflow. Then I run 
```bash
bazel build -c opt tensorflow_serving/...
```
But I got 
```python
In file included from external/org_tensorflow/tensorflow/python/lib/core/py_seq_tensor.cc:16:0:
external/org_tensorflow/tensorflow/python/lib/core/py_seq_tensor.h:19:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
```
I have set `PYTHONPATH` and `PYTHON_INCLUDE_PATH`, and I'm sure `Python.h` is in `PYTHON_INCLUDE_PATH`. My python env is installed through Anaconda and the python version is `2.7.14`.
The weird thing is I can compile tensorflow successfully using bazel under the directory of serving/tensorflow.

**Comment by kirilg** [comment]
Usually this means python-dev is not installed. Can you try running 
```
sudo apt-get install python-dev 
```

**Comment by maybeluo** [comment]
Thanks, but I'm not root... BTW. The OS is rehat.

**Comment by kirilg** [comment]
Being able to install python-dev is one of the prerequisites of TensorFlow - https://www.tensorflow.org/install/install_linux, so unfortunately there is no way around that.

You can try installing without `sudo` in the command (unlikely to work but could try) or if you just don't have the permissions, try installing in a Docker container - https://www.tensorflow.org/serving/docker where you'll have root.

**Comment by oscarriddle** [comment]
@maybeluo Hi, I encountered the exactly same issue. How did you solve it afterwards?

**Comment by tpham3783** [comment]
This issue does not happen on Ubuntu <= 22.04; however, on Rocky8 Linux, I had to apply the below patch.  None of the above methods worked for me!

```
iff --git a/.bazelrc b/.bazelrc
index b1d4eee9..c045198e 100644
--- a/.bazelrc
+++ b/.bazelrc
@@ -295,7 +295,7 @@ build:ios --noenable_platform_specific_config
 # Suppress C++ compiler warnings, otherwise build logs become 10s of MBs.
 build:android --copt=-w
 build:ios --copt=-w
-build:linux --copt=-w
+build:linux --copt=-w --cxxopt=-I/usr/include/python3.8
 build:linux --host_copt=-w
 build:macos --copt=-w
 build:windows --copt=/W0

```
