### ISSUE TITLE
Tensorflow serving for new Dataset API based model

### ISSUE THREAD

**Issue by efeiefei** [tensorflow/serving#676]
With new dataset api, we can provide data with iterator for traning, like `dataset.make_initializable_iterator()`.
We can `sess.run(iterator.initializer, feed_dict{})` before using it.
But we can not export valid savedModel when serving:
```
FailedPreconditionError (see above for traceback): GetNext() failed because the iterator has not been initialized. Ensure that you have run the initializer operation for this iterator before getting the next element.
```
@mrry provide a solution in [google groups](https://groups.google.com/a/tensorflow.org/d/msg/discuss/SxF8LMlQUHE/KZL-Sf-UAgAJ)
He pointed out that "I'm not sure how efficient this approach would be though", and "It might be worth adding special support for compiling datasets down to a simple TF op".

Is there a plan for it ?
Or is there any other recommended method to serving dataset/iterator based model ?

Thanks

**Comment by sukritiramesh** [comment]
Hi @efeiefei, perhaps one option is to create a single op by using grouping or using control dependencies for the iterator initializers and supplying that as the legacy_init_op to the SavedModel builder. SavedModel itself does not have any special ops for this purpose.

**Comment by sukritiramesh** [comment]
Hi @efeiefei, resolving this issue for now. Please reopen if there are additional questions.

**Comment by ruanchong** [comment]
But I think it's better to provide an API which export models with Dataset APIs to `SavedModel` for `TF Serving` purpose.

**Comment by iiapache** [comment]
> Hi @efeiefei, perhaps one option is to create a single op by using grouping or using control dependencies for the iterator initializers and supplying that as the legacy_init_op to the SavedModel builder. SavedModel itself does not have any special ops for this purpose.

Hi，can you show more details for resolving this issue?
