### ISSUE TITLE
Run Tensor_flow_server on Ubuntu 16.04 Virtualbox

### ISSUE THREAD

**Issue by Wertugo** [tensorflow/serving#677]
Good Day!
I have tried to run tensorflow_model_server  on Ubuntu 16.04 Virtualbox (python 2.7).
tensorflow_model_server version 1.4.0 installed with pip. 
But there is no luck to start, program crashed:
Illegal instruction (core dumped)

According dumps error is:
tensorflow_model_server crashed with SIGILL in tensorflow::Env::RegisterFileSystem()

Is there any chanse to repair or configure with a diff way it?

Thanks,
Igor

**Comment by kirilg** [comment]
Do you mean you installed the model server with `apt-get install`? Can you include the full output of the server as it was coming up and when it crashed?

**Comment by Wertugo** [comment]
Kirill, I have uninstalled tensorflow-model-server and then install tensorflow-model-server-universal version, which non optimised. Now it works, so issue, can be closed.
