### ISSUE TITLE
Build TensorFlow Serving in a Docker container: failure

### ISSUE THREAD

**Issue by cris1403** [tensorflow/serving#679]
I'm trying to build a container with tensorflow serving, but it doesn't work.
I followed [https://www.tensorflow.org/serving/docker](https://www.tensorflow.org/serving/docker) and
[https://towardsdatascience.com/how-to-deploy-machine-learning-models-with-tensorflow-part-2-containerize-it-db0ad7ca35a7](https://towardsdatascience.com/how-to-deploy-machine-learning-models-with-tensorflow-part-2-containerize-it-db0ad7ca35a7).

Here you find what I've done:
OS: Ubuntu 16.04

1) bazel installed
Build label: 0.8.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Nov 27 13:19:39 2017 (1511788779)
Build timestamp: 1511788779
Build timestamp as int: 1511788779

2) conda environment created
conda list

```
# packages in environment at /home/cristian/anaconda3/envs/tensorflow2:#
backports.weakref         1.0.post1                 <pip>
bleach                    1.5.0                     <pip>
ca-certificates           2017.08.26           h1d4fec5_0  
certifi                   2017.11.5        py27h71e7faf_0  
enum34                    1.1.6                     <pip>
funcsigs                  1.0.2                     <pip>
futures                   3.2.0                     <pip>
grpcio                    1.7.0                     <pip>
grpcio-tools              1.7.0                     <pip>
html5lib                  0.9999999                 <pip>
intel-openmp              2018.0.0             hc7b2577_8  
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                h7cc24e2_2  
libstdcxx-ng              7.2.0                h7a57d05_2  
Markdown                  2.6.9                     <pip>
mkl                       2018.0.1             h19d6760_4  
mock                      2.0.0                     <pip>
ncurses                   6.0                  h9df7e31_2  
numpy                     1.13.3           py27hbcc08e0_0  
openssl                   1.0.2m               h26d622b_1  
pbr                       3.1.1                     <pip>
pip                       9.0.1            py27ha730c48_4  
protobuf                  3.5.0.post1               <pip>
python                    2.7.14              hdd48546_24  
readline                  7.0                  ha6073c6_4  
setuptools                36.5.0           py27h68b189e_0  
six                       1.11.0                    <pip>
sqlite                    3.20.1               hb898158_2  
tensorflow                1.4.0                     <pip>
tensorflow-serving-api    1.4.0                     <pip>
tensorflow-tensorboard    0.4.0rc3                  <pip>
tk                        8.6.7                hc745277_3  
Werkzeug                  0.12.2                    <pip>
wheel                     0.30.0           py27h2bc6bb2_1  
zlib                      1.2.11               ha838bed_2
```

Then:

```
git clone --recurse-submodules https://github.com/tensorflow/serving
cd serving

docker build --pull -t $USER/tensorflow-serving-devel-gpu -f tensorflow_serving/tools/docker/Dockerfile.devel-gpu .

docker run --name=tf_container_gpu -it $USER/tensorflow-serving-devel-gpu

cd tensorflow
./configure

location of python: /usr/bin/python
python path library: /usr/local/lib/python2.7/site-packages

Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: y
Do you wish to build TensorFlow with Google Cloud Platform support? [Y/n]: y
Do you wish to build TensorFlow with Hadoop File System support? [Y/n]: y
Do you wish to build TensorFlow with Amazon S3 File System support? [Y/n]: y
Do you wish to build TensorFlow with XLA JIT support? [y/N]: n
Do you wish to build TensorFlow with GDR support? [y/N]: n
Do you wish to build TensorFlow with VERBS support? [y/N]: n
Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
Do you wish to build TensorFlow with CUDA support? [y/N]: n
Do you wish to build TensorFlow with MPI support? [y/N]: n

cd ..
bazel build -c opt tensorflow_serving/...

bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server
bash: bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server: No such file or directory

```
I attached the logs. There is no way to configure it properly.
Please help!

Thanks!

[bazel-build.log](https://github.com/tensorflow/serving/files/1531349/bazel-build.log)
[bazel-test.log](https://github.com/tensorflow/serving/files/1531350/bazel-test.log)
[docker.log](https://github.com/tensorflow/serving/files/1531351/docker.log)

**Comment by kirilg** [comment]
Your Bazel log shows compilation failed, so the binary was never created.

```
#error "SIMD not enabled, you'd be getting a slow software fallback. Consider enabling SIMD extensions (for example using -msse4 if you're on modern x86). If that's not an option, and you would like to continue with the slow fallback, define GEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK."
```

You can try building an optimized binary (preferred) using:
`bazel build -c opt --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-O3 tensorflow_serving/...`
or if some of those flags can't be used on your machine, use a subset (ensuring you keep at least msse)

**Comment by cris1403** [comment]
Hi Kiril,
Thank you for your help!

I re-open the docker, and execute those commands:
```
bazel build -c opt --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-O3 tensorflow_serving/...
bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server
bazel test -c opt --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-O3 tensorflow_serving/... > 20171207_bazel-test.log 2>&1
[20171207_bazel-test.log](https://github.com/tensorflow/serving/files/1538570/20171207_bazel-test.log)
```
It looks working now right?

[20171207_bazel-build.log](https://github.com/tensorflow/serving/files/1538518/20171207_bazel-build.log)
[20171207_bazel-bin.log](https://github.com/tensorflow/serving/files/1538519/20171207_bazel-bin.log)
[20171207_bazel-test.log](https://github.com/tensorflow/serving/files/1538572/20171207_bazel-test.log)

Then I tried with the TensorFlow Serving mnist tutorial and it didn't work.

[20171207_bazel-build-mnist.log](https://github.com/tensorflow/serving/files/1538673/20171207_bazel-build-mnist.log)
[20171207_bazel-bin-mnist.log](https://github.com/tensorflow/serving/files/1538674/20171207_bazel-bin-mnist.log)

I checked the  [issue 421](https://github.com/tensorflow/serving/issues/421) and modified the __init__.py file but it didn't work for me. Why is that?

**Comment by gautamvasudevan** [comment]
Closing - please see the latest [Docker examples](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) for bringing up a serving or development environment.
