### ISSUE TITLE
Simple client stub definitions

### ISSUE THREAD

**Issue by sanchom** [tensorflow/serving#680]
I have the gRPC C++ API and a running tensorflow model server. I would like to just call the model server over gRPC using the C++ client stubs. I don't want to have to build all of tensorflow serving for this. What's the simplest way to get the protobuf definitions compiled for use by a C++ client?

**Comment by kirilg** [comment]
You shouldn't need to compile all of tensorflow serving just for the client. You can take a look at [this](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/BUILD#L86) example C++ client.

Notice the deps include the API proto library (prediction_service_proto) as the only TensorFlow Serving dep. If you can avoid using any TF libraries, you can get rid of "@org_tensorflow//tensorflow/core:framework" so compilation should be quick.

**Comment by sanchom** [comment]
Yeah, all I need is to be able to use the PredictionService/Request/Response structures to make the gRPC call with. Will that create headers and a library that I can pull out and use standalone in other projects? I am not familiar with bazel.

**Comment by kirilg** [comment]
TensorFlow Serving makes heavy use of Bazel so I would strongly recommend using it when building the client. It handles linking TensorFlow proto dependencies and auto-generated proto headers for you, and the entire build rule will look as simple as the link I provided.

It's possible to use the proto compiler to generate headers from source proto files, like we do with the python equivalent [here](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/prediction_service_pb2.py) but I've never done that manually.

**Comment by sanchom** [comment]
Thanks. What I did was build a shared-library target like this:

```
cc_binary(                                                                                                                                                                                                                                                             
    name = "libtf_serving_api.so",                                                                                                                                                                                                                                     
    linkshared=1,                                                                                                                                                                                                                                                      
    deps = [                                                                                                                                                                                                                                                           
        "//tensorflow_serving/apis:prediction_service_proto",                                                                                                                                                                                                          
        "@grpc//:grpc++_unsecure",                                                                                                                                                                                                                                     
        "@protobuf_archive//:protobuf_lite",                                                                                                                                                                                                                           
    ],                                                                                                                                                                                                                                                                 
)
```

I manually copied out the `.so` and the `pb.h` header files. Only complication is that this requires my non-bazel build environment and runtime to be using the same-ish version of protobuf and grpc as this bazel setup used, but that was easy to satisfy in this case.

**Comment by kirilg** [comment]
Thanks for reporting back with the solution you went with!
