### ISSUE TITLE
Excluding Outputs from TF serving doesn't seem to quite work

### ISSUE THREAD

**Issue by zmjjmz** [tensorflow/serving#682]
With the caveat that I'm probably doing *something* wrong:

I have a `keras.models.Model` with a bunch of intermediate outputs hooked up for analysis purposes. However when I want to export the model for TF serving to use, I don't want some of these intermediate outputs to be returned so I'm excluding them from the output signature. But, when I export the model and get some outputs from it thru TF serving, I see an empty output for the excluded layers (which shouldn't be empty, so that's weird).

So this is what the `predict` signature looks like:

```
inputs {
  key: "text"
  value {
    name: "text:0"
    dtype: DT_STRING
    tensor_shape {
      dim {
        size: -1
      }
      dim {
        size: 1
      }
    }
  }
}
outputs {                              
  key: "oov_code"                      
  value {                              
    name: "oov_code/LogicalOr:0"       
    dtype: DT_BOOL                     
    tensor_shape {                     
      dim {                            
        size: -1                       
      }                                
      dim {                            
        size: 1                        
      }                                
    }                                  
  }                                    
}
outputs {                                 
  key: "softmax"                          
  value {                                 
    name: "softmax/Softmax:0"             
    dtype: DT_FLOAT                       
    tensor_shape {                        
      dim {                               
        size: -1                          
      }                                   
      dim {                               
        size: 2                           
      }                                   
    }                                     
  }                                       
}                                         
method_name: "tensorflow/serving/predict" 
```

And here's the output I'm seeing for a small test case:
```
outputs {
  key: "avg"
  value {
  }
}
outputs {
  key: "oov_code"
  value {
    dtype: DT_BOOL
    tensor_shape {
      dim {
        size: 5
      }
      dim {
        size: 1
      }
    }
    bool_val: false
    bool_val: false
    bool_val: true
    bool_val: true
    bool_val: false
  }
}
outputs {
  key: "softmax"
  value {
    dtype: DT_FLOAT
    tensor_shape {
      dim {
        size: 5
      }
      dim {
        size: 2
      }
    }
    float_val: 1.23842525568e-07
    float_val: 0.999999880791
    float_val: 1.23842525568e-07
    float_val: 0.999999880791
    float_val: 0.599020779133
    float_val: 0.400979250669
    float_val: 0.599020779133
    float_val: 0.400979250669
    float_val: 0.0277454275638
    float_val: 0.972254633904
  }
}
```

Notice that the `avg` output is *not* in the signature, but is part of the actual model's output. 

The code I'm using for the export step is here: https://gist.github.com/zmjjmz/00ee658007b57111b9b936e1ae94c0cd                         

And the model definition is here: https://gist.github.com/zmjjmz/0e9dd22c175ce6cde1c9120c8fbea464

This is kind of a minor annoyance but it would be nice to make sure there isn't a larger issue here...

**Comment by chrisolston** [comment]
Hi,

That is indeed strange.

Take a look at the relevant bit of the implementation, which is just a couple dozen LoC, in https://github.com/tensorflow/serving/blob/master/tensorflow_serving/servables/tensorflow/predict_impl.cc lines 86-112.

So I guess either "avg" *is* in the output_filter, or your signature doesn't specify any outputs so it's using all of the tensors (and grabbing "avg" as well). You can cat the meta-graph-def in your SavedModel file to see what's actually there.

More concerning, and I think this is why you filed the bug, is why the "avg" is empty. I *think* our TF-Serving code is just piping through whatever came back from the tensorflow Session::Run() call so it may have been empty in your graph as well. One possibility: some chunk of the graph that's used for "avg" got omitted from the export to SavedModel?

For both of these concerns, you can add some printfs in a couple spots in predict_impl.cc to pin down what's happening.
