### ISSUE TITLE
how to fill the input and get output from C++ client

### ISSUE THREAD

**Issue by yuimo** [tensorflow/serving#687]
hi all, i have trained a model and prepare to use it through tf serving
but i have some questions when writing the C++ client code
first of all, my input and output are all 2-d arrays (int32)
and how can i construct the input to model and parse the output of the model?

i have read the example of tf serving:
inception_client.cc
it's input is a image and the code is below:
    proto.set_dtype(tensorflow::DataType::DT_STRING);
    proto.add_string_val(image, fileSize);

    proto.mutable_tensor_shape()->add_dim()->set_size(1);

but i'm still wondering how to code for my demand
thanks a lot.

**Comment by chrisolston** [comment]
You'll want to look at two things: (1) protocol buffer definition of TensorProto; (2) c++ protocol buffer API.

(1) https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.proto
(2) https://developers.google.com/protocol-buffers/docs/reference/cpp/

**Comment by chrisolston** [comment]
Actually, a better way would be to create a Tensor [1] and then convert it to a TensorProto.

[1] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.h

**Comment by sukritiramesh** [comment]
Hi @yuimo, please check out the links @chrisolston has provided. Resolving this issue for now, but feel free to reopen if you need more information.
