### ISSUE TITLE
tensorflow_model_server gpu is out of memory when running server

### ISSUE THREAD

**Issue by zhejiangyyf** [tensorflow/serving#693]
tensorflow_model_server is builded with --config=cuda following https://docs.bitnami.com/google/how-to/enable-nvidia-gpu-tensorflow-serving/.
tf model is from a python file by tf.saved_model.builder.SavedModelBuilder not compiled by bazel.
When tensorflow_model_server start serving it take all the memory nearly 40GB, killed finally.

![2017-12-14 5 51 18](https://user-images.githubusercontent.com/6621874/33986622-15b42d54-e0f9-11e7-88a0-d5a23a27448f.jpg)
![2017-12-14 5 51 49](https://user-images.githubusercontent.com/6621874/33986623-1604ff04-e0f9-11e7-89e1-8e2cb0f0620b.jpg)

**Comment by chrisolston** [comment]
How large is/are the model(s) you are attempting to load? Most of the memory usage is for models, or transient memory use while loading them.

**Comment by zhejiangyyf** [comment]
model folder total just 231M

**Comment by chrisolston** [comment]
Wow, that seems rather gigantic for the bazel-bin folder. You might need to run some tools to see the sizes of things you are linking in. I'm not familiar with the bitnami instructions.

**Comment by zhejiangyyf** [comment]
I try this in many times on different pc and docker, this problem never miss.
I think something must be wrong.
I use ubuntu 14.04, cuda 8.0,cudnn 6.0,bazel 0.8.1,tensorflow serving 0.4

**Comment by sukritiramesh** [comment]
@zhejiangyyf You can also try profiling the server to see what might be expensive, including restoring and initialization of the model variables and state.
