### ISSUE TITLE
Set TensorShape in C#

### ISSUE THREAD

**Issue by Rahza** [tensorflow/serving#695]
I was trying to use TensorFlow Serving with batching using a C# client. It didn't work with zero-dimensional tensors:

> Grpc.Core.RpcException: 'Status(StatusCode=InvalidArgument, Detail="Batching session Run() input tensors must have at least one dimension")'

I was then trying to set the shape of my `TensorShapeProto` to `[1, 1]`, but it is `readonly`. After removing the `readonly` constraint and setting the tensor shape, everything is working just fine.

So, why is the `Dim` property in `TensorShapeProto` readonly? Am I supposed to set the dimension differently?

**Comment by Rahza** [comment]
@R-Miner I created a repository here: https://github.com/Rahza/.NET-Tensorflow-Classification-Client 

Please notice that it is not generic at all and will probably only work with our model. If you find out a better way to write the client or know how I'm supposed to set the dimension please let me know.

**Comment by R-Miner** [comment]
I was following this [https://github.com/Wertugo/TensorFlowServingCSharpClient] as a reference.Hope this will of some help to your requirement.

**Comment by R-Miner** [comment]
One more question....How did you generate the .cs files of the required
 proto files?

**Comment by Rahza** [comment]
@R-Miner Have a look at the **Compiling your protocol buffers** section in [this tutorial](https://developers.google.com/protocol-buffers/docs/csharptutorial#compiling-your-protocol-buffers)

**Comment by gautamvasudevan** [comment]
Closing due to staleness.
