### ISSUE TITLE
Train model failed,input_data error

### ISSUE THREAD

**Issue by R1994** [tensorflow/serving#699]
> python tensorflow_serving/example/mnist_saved_model.py /tmp/mnist_model
> Training model...
> Extracting /tmp/train-images-idx3-ubyte.gz
> Traceback (most recent call last):
>   File "tensorflow_serving/example/mnist_saved_model.py", line 143, in <module>
>     tf.app.run()
>   File "/home/rui/miniconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "tensorflow_serving/example/mnist_saved_model.py", line 58, in main
>     mnist = mnist_input_data.read_data_sets(FLAGS.work_dir, one_hot=True)
>   File "/home/rui/tensorflow_serving/example/mnist_input_data.py", line 185, in read_data_sets
>     train_images = extract_images(local_file)
>   File "/home/rui/tensorflow_serving/example/mnist_input_data.py", line 57, in extract_images
>     magic = _read32(bytestream)
>   File "/home/rui/tensorflow_serving/example/mnist_input_data.py", line 51, in _read32
>     return numpy.frombuffer(bytestream.read(4), dtype=dt)[0]
> IndexError: index 0 is out of bounds for axis 0 with size 0

i havent found any useful reference,anyboby can help me?thx

**Comment by HITxuefeng** [comment]
Have you solved this problem? I have encountered the same mistake as you.if you solved this problem,please help me. thank you.
