### ISSUE TITLE
Google Inception example

### ISSUE THREAD

**Issue by billidani7** [tensorflow/serving#7]
I would appreciate it If you provide the Google Inception example compatible with TensorFlow serving like MNIST example. 

Recently you have introduced a very nice transfer learning example for image retraining.  Please provide some informations about exporting the retrained inception model with TensorFlow Serving Exporter module. It would be very helpful if you make a full working example like MNIST.

@kirilg I would greatly appreciate it if you could provide us a tutorial on how to send an image to a tensorflow serving server and get a response with the results.

Regards

**Comment by kirilg** [comment]
Thanks for the suggestion. This interesting and is something we're also thinking about.

**Comment by Irtza** [comment]
Second that, A TF-serving example would be of great help. Thank-you very much.

**Comment by gitfrida** [comment]
Hi @kirilg I'm trying to add the exporter code into retrain.py 
I have the signature missing: 
signature = exporter.classification_signature(input_tensor=x, scores_tensor=y) from mnist_exporty.py 
Using retrain.py, can you confirm for me if x is bottleneck_tensor and y is the tensor named final_tensor_name?

**Comment by billidani7** [comment]
Thank you @kirilg.

We look forward to hearing from you soon.

**Comment by kirilg** [comment]
@gitfrida adding @fangweili  regarding the signature question and modifying retrain.py in general. We're now thinking about potential future improvements to the exporter, so it would be worth discussing your proposed changes with him to see how that lines up.

**Comment by fangweili** [comment]
We have released the serving example for the Inception model:
http://tensorflow.github.io/serving/serving_inception

@gitfrida - I am not familiar with the model of retrain.py, and it really depends on how you want to build your inference graph. But if you want to use classification_signature, x should be the input for your inference graph, and y should be the classification score tensor.

**Comment by Irtza** [comment]
Excellent, just what I was looking for. thank-you @fangweili

**Comment by kirilg** [comment]
Closing this issue since it was originally meant to track the release of an Inception example, which is now available.

@gitfrida if you have followup questions, please feel free to open a new issue and we'll continue the discussion there. Thanks.
