### ISSUE TITLE
multiple inputs with prediction signature not working

### ISSUE THREAD

**Issue by walterwang** [tensorflow/serving#702]
When run a model with multiple placeholders and prediction signature, it will not work.

$saved_model_cli run --dir /tmp/saved_model_dir --tag_set serve \
--signature_def x1_x2_to_y --inputs x1=/tmp/my_data1.npy;x2=/tmp/my_data2.npy \
--outdir /tmp/out
Creating a graph with the above input will not result in the second placeholder being found

**Comment by kirilg** [comment]
Can you confirm that your model has that signature and that the signature takes x1 and x2 as inputs? Please include the output of the two commands below in your reply:

```
saved_model_cli show --dir /tmp/saved_model_dir --tag_set serve
```
// Output should include the signature 'x1_x2_to_y'

```
saved_model_cli show --dir /tmp/saved_model_dir --tag_set serve --signature_def x1_x2_to_y
```
// output should include and "inputs['x1']" and a "inputs['x2']" section. If that's the case and you're still seeing errors, please also include the full output of the `saved_model_cli run` command you tried.

**Comment by walterwang** [comment]
Ok I figured out the issue, when you have multiple inputs you must put quotes around, so instead of 
--inputs x1=/tmp/my_data1.npy;x2=/tmp/my_data2.npy 
it should be:
--inputs 'x1=/tmp/my_data1.npy;x2=/tmp/my_data2.npy'
but when its a single input, it does not need quotation marks. 
The tutorial section needs to be fixed: https://www.tensorflow.org/programmers_guide/saved_model
