### ISSUE TITLE
Building tensorflow_serving with --config=cuda option fails with an error

### ISSUE THREAD

**Issue by asheshjain399** [tensorflow/serving#704]
After following the instructions on the [setup page](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md). I get the following error when building `tensorflow_serving` with `--config=cuda` option. 

`bazel build -c opt --config=cuda tensorflow_serving/...`
`DEBUG: /home/ashesh/.cache/bazel/_bazel_ashesh/a533d29f1bea7442323ae910ee02f9f0/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:197:9: @//tensorflow_serving/model_servers:tensorflow_model_server_tar: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
ERROR: no such target '@org_tensorflow//third_party/gpus/crosstool:crosstool': target 'crosstool' not declared in package 'third_party/gpus/crosstool' defined by /home/ashesh/.cache/bazel/_bazel_ashesh/a533d29f1bea7442323ae910ee02f9f0/external/org_tensorflow/third_party/gpus/crosstool/BUILD
INFO: Elapsed time: 5.181s
FAILED: Build did NOT complete successfully (22 packages loaded)
    currently loading: @bazel_tools//tools/jdk`

I have configured tensorflow with CUDA support before running the above command.

**Comment by asheshjain399** [comment]
I managed to solve this by following the instructions here: https://github.com/tensorflow/serving/issues/186#issuecomment-251152755

Any plans to fix this bug in the future releases? (and have test coverage to prevent it from breaking?)

**Comment by gautamvasudevan** [comment]
Yep! The docker images we provide now are intended to be validated environments where building will work. These are being tested before deployment and should catch this in the future.
