### ISSUE TITLE
What's the default scheduler while servering with multiple models?

### ISSUE THREAD

**Issue by bluemandora** [tensorflow/serving#710]
I read something about this in [here](https://github.com/tensorflow/serving/tree/master/tensorflow_serving/batching#servers-with-multiple-models-model-versions-or-subtasks)
But I have no idea how to use SharedBatchScheduler in my project. Do I need write some cpp code and rebuild tf_serving?
Or SharedBatchScheduler is the default scheduler while servering with multiple models, so I don't need to change anything.

**Comment by chrisolston** [comment]
The vanilla binary we release uses SharedBatchScheduler under the hood, so you'll get it automatically. You only need to use SharedBatchScheduler explicitly if you are using our libraries to build your own, custom binary.

**Comment by bluemandora** [comment]
I build the GPU version with `bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --config=cuda`. Does that use SharedBatchScheduler ?

**Comment by chrisolston** [comment]
If you built the tensorflow_serving/model_servers:tensorflow_model_server target, then yes it uses SharedBatchScheduler.

**Comment by bluemandora** [comment]
@chrisolston Thank you. I did build tensorflow_serving/model_servers:tensorflow_model_server.
