### ISSUE TITLE
did not successfully load saved model

### ISSUE THREAD

**Issue by aforwardz** [tensorflow/serving#714]
> 2018-01-04 20:30:49.099060: external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:360] Attempting to load native SavedModelBundle in bundle-shim from: /w
> ebapps/algorithm-training/algorithm/algorithm/models/saved_model/ner/1
> 2018-01-04 20:30:49.099075: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:236] Loading SavedModel from: /webapps/algorithm-training/algorithm/algorithm/models
> /saved_model/ner/1
> 2018-01-04 20:30:49.198251: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not co
> mpiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
> 2018-01-04 20:30:49.198283: I external/org_tensorflow/tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 4
> 2018-01-04 20:30:49.283397: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:241] found DLL info with name: /usr/lib/x86_64-linux-gnu/libcuda.so.
> 1
> 2018-01-04 20:30:49.283426: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:246] found DLL info with resolved path: /usr/lib/x86_64-linux-gnu/li
> bcuda.so.384.59
> 2018-01-04 20:30:49.283500: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), 
> but there must be at least one NUMA node, so returning NUMA node zero
> 2018-01-04 20:30:49.283783: I external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc:1062] Found device 0 with properties: 
> name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.721
> pciBusID: 0000:01:00.0
> totalMemory: 7.92GiB freeMemory: 272.69MiB
> 2018-01-04 20:30:49.283834: I external/org_tensorflow/tensorflow/core/common_runtime/gpu/gpu_device.cc:1152] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: G
> eForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
> 2018-01-04 20:30:49.998581: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: ner version: 1}; Ser
> vable path: /webapps/algorithm-training/algorithm/algorithm/models/saved_model/ner/1; Polling frequency: 1
> 2018-01-04 20:30:49.998673: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: ner version: 1}
> 2018-01-04 20:30:49.999198: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: ner version: 1}
> 2018-01-04 20:30:50.998643: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: ner version: 1}; Ser
> vable path: /webapps/algorithm-training/algorithm/algorithm/models/saved_model/ner/1; Polling frequency: 1
> 2018-01-04 20:30:50.998729: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: ner version: 1}
> 2018-01-04 20:30:50.999922: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: ner version: 1}

I turn on VLOG and found that after serving my saved model, there was no information such as 'successfully load SaverdModel' or 'serving at 0.0.0.0:8500' and it indeed fails to load SavedModel because when I use grpc client to request the server, it showed the server was unavaliable

What's the problem and how to solve it? Is it completely the matter of my savedmodel?
THX

**Comment by chrisolston** [comment]
Hmmm. I don't see any log indicating an error to load, nor a successful load (as you said), which indicates to me that loading is taking a long time or possibly stuck somehow. Perhaps you need to either wait longer, or debug inside the TF code to see why it might be taking a long time or getting stuck.

The "aspired versions" stuff is normal, since our file-system Source is oblivious to what the loading status is doing and is just telling our Manager that it found version 1 on disk (this is by design, and it's idempotent) -- so that part should be harmless.

**Comment by aforwardz** [comment]
@chrisolston thanks for reply
It loads the model successfully now! BUT it takes over 20 minutes. So weird. Previously, it took only 1-2 minutes to load single model and about 10 minutes for 3 models.
