### ISSUE TITLE
In tensorflow-serving on GPU computation is slower than the CPU？

### ISSUE THREAD

**Issue by fengyu10** [tensorflow/serving#716]
I add time-consuming calculation in Predict interface implementation，as shown below
![image](https://user-images.githubusercontent.com/31887880/34600181-306ecf7a-f231-11e7-8308-467ebec3b0ec.png)
CPU tensorflow-serving test time-consuming for an average of 12 ms
but GPU tensorflow-serving test time-consuming for an average of 88 ms
GPU tensorflow-serving compile command: 
```bazel build --config=opt --config=cuda --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-O3 tensorflow_serving/...```
In tensorflow-serving on GPU computation is slower than the CPU？
Someone come across this kind of situation?
Someone to help me explain this phenomenon？

**Comment by theflyfish** [comment]
hi，guy, is the  problem  solved ? I also catch  this problem.

**Comment by chrisolston** [comment]
Please see https://github.com/tensorflow/serving/issues/798
