### ISSUE TITLE
errormsg: "input size does not match signature"

### ISSUE THREAD

**Issue by dingqs447** [tensorflow/serving#719]
I train a model using  [facenect](https://github.com/davidsandberg/facenet).
I want load this model using tensorflow-serving。
step 1：
       freezing the model (converting all variables into constants) using [freeze_graph.py](https://github.com/davidsandberg/facenet/blob/master/src/freeze_graph.py)

step2：
       exported the servable model， using：
model_dir = compat.as_str(FLAGS.checkpoint_dir)
with tf.Graph().as_default():
      
        with tf.Session() as sess:
            load_model(model_dir)

            # Retrieve the protobuf graph definition and fix the batch norm nodes
            input_graph_def = sess.graph.as_graph_def()

            # Export inference model.
            output_path = os.path.join(
                compat.as_bytes(FLAGS.output_dir),
                compat.as_bytes(str(FLAGS.model_version)))
            print('Exporting trained model to', output_path)
            builder = tf.saved_model.builder.SavedModelBuilder(output_path)
             
            # Get input and output tensors
            images_placeholder = sess.graph.get_tensor_by_name("input:0")
            embeddings = sess.graph.get_tensor_by_name("embeddings:0")
            phase_train_placeholder = sess.graph.get_tensor_by_name("phase_train:0")                
            
            # Build the signature_def_map.
       
            prediction_signature = tf.saved_model.signature_def_utils.build_signature_def(
                inputs={'images': tf.saved_model.utils.build_tensor_info(images_placeholder),
                        'phase': tf.saved_model.utils.build_tensor_info(phase_train_placeholder)},
                outputs={
                    'embeddings': tf.saved_model.utils.build_tensor_info(embeddings)
                },
                method_name = tf.saved_model.signature_constants.PREDICT_METHOD_NAME)
            
            legacy_init_op = tf.group(
                tf.tables_initializer(), name='legacy_init_op')
            
            builder.add_meta_graph_and_variables(
                sess, [tf.saved_model.tag_constants.SERVING],
                signature_def_map={
                    'calculate_embeddings': prediction_signature,
                })
            
            builder.save()
            print('Successfully exported model to %s' % FLAGS.output_dir)
step 3：
          load the model using tensorflow-serving:
tensorflow_model_server --port=9000 --model_name=model_output_18 --model_base_path=/******/facenet_train/model_output_18

       I can serve it using tensorflow serving

step 4:
         test the server using client code:
  1 #!/usr/bin/env python2.7
  2 
  3 from __future__ import print_function
  4 from grpc.beta import implementations
  5 import tensorflow as tf
  6 
  7 from google.protobuf.json_format import MessageToDict, ParseDict
  8 from tensorflow_serving.apis import predict_pb2
  9 from tensorflow_serving.apis import prediction_service_pb2
 10 
 11 import requests
 12 import os
 13 import os.path
 14 
 15 tf.app.flags.DEFINE_string('server', 'localhost:9000',
 16                             'PredictionService host:port')
 17 FLAGS = tf.app.flags.FLAGS
 18 
 19 image = os.path.join(os.getcwd(), 'test_image.png')
 20 
 21 def main(_):
 22     host, port = FLAGS.server.split(':')
 23     channel = implementations.insecure_channel(host, int(port))
 24     stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
 25 
 26     # Send request
 27     with open(image, 'rb') as f:
 28         # See prediction_service.proto for gRPC request/response details.
 29         data = f.read()
 30         print(len(data))
 31         request = predict_pb2.PredictRequest()
 32         request.model_spec.name = 'model_output_18'
 33         request.model_spec.signature_name = 'calculate_embeddings'
 34         request.inputs['images'].CopyFrom(
 35             tf.contrib.util.make_tensor_proto(data, shape=[1])) 
 36         result = stub.Predict(request, 10.0)  # 10 secs timeout
 37         print(result)
 38 
 39 
 40 
 41 if __name__ == '__main__':
 42     tf.app.run()

the error msg is :
  $ python test.py --server=10.21.**.**:9000
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
46146
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "test.py", line 36, in main
    result = stub.Predict(request, 10.0)  # 10 secs timeout
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 309, in __call__
    self._request_serializer, self._response_deserializer)
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="input size does not match signature")
$ 

Please help me or give some information, thanks!

**Comment by chrisolston** [comment]
The error means that the number of tensors in the predict request rpc does not match the number specified in the signature. It looks like you set up the signature to have two tensors: 'images' and 'phase'. Your code that populates the request seems to populate 'images' but not 'phase'. You probably need to add a line starting with request.inputs['phase'].CopyFrom(...

**Comment by dingqs447** [comment]
thanks for @chrisolston help. 
It's really loss a tensor ‘phase’，now new client code this：

from grpc.beta import implementations
import tensorflow as tf
import numpy as np

from google.protobuf.json_format import MessageToDict, ParseDict
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2

import requests
import os
import os.path

tf.app.flags.DEFINE_string('server', 'localhost:9000', 'PredictionService host:port')
FLAGS = tf.app.flags.FLAGS

image = os.path.join(os.getcwd(), 'test_image.jpg')

def main(_):
	host, port = FLAGS.server.split(':')
	channel = implementations.insecure_channel(host, int(port))
	stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
	with open(image, 'rb') as f:
		data = f.read()
		request = predict_pb2.PredictRequest()
		request.model_spec.name = 'model_output_18'
		request.model_spec.signature_name = 'calculate_embeddings'
		request.inputs['images'].CopyFrom(tf.contrib.util.make_tensor_proto(data, shape=[1]))
		request.inputs['phase'].CopyFrom(tf.contrib.util.make_tensor_proto(data, shape=[1]))
		result = stub.Predict(request, 10.0)
		print(result)

if __name__ == '__main__':
	tf.app.run()

and new error msg ：


$ python tf-serving_client.py  --server=localhost:9080
Traceback (most recent call last):
  File "tf-serving_client.py", line 46, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tf-serving_client.py", line 42, in main
    result = stub.Predict(request, 10.0) # 10 secs timeout
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 309, in __call__
    self._request_serializer, self._response_deserializer)
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="Expects arg[0] to be float but string is provided")


Please give me some information, thanks!

**Comment by chrisolston** [comment]
If I understand your code correctly you are passing the same data to both 'images' and 'phase'. Are you sure that's the right thing to do? Perhaps you are passing the wrong kind of data to 'phase' hence the type error? Stepping back, if 'phase' is for training, do you want your inference requests to be supplying it? Maybe you should eliminate it from the serving signature?

**Comment by daikankan** [comment]
@chrisolston , can I serve a FCN model , when the input shape or the output shape is not determined before inference ?

**Comment by chrisolston** [comment]
You always have the option to drop down to the low-level tensors-in/tensors-out API, which should work for any kind of model: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/predict.proto#L12
