### ISSUE TITLE
bazel test failing after successful build on python3

### ISSUE THREAD

**Issue by marcokuchla** [tensorflow/serving#723]
Plataform Info:
Ubuntu 16.04
Cuda 8.0
cuDNN 6
python 3.5.3
tensorflow_serving master branch commit c1ec435

I successfully built tensorflow serving with CUDA support on python3 but when running `bazel test -c opt tensorflow_serving/...` 1 test has failed:

> INFO: Elapsed time: 71.895s, Critical Path: 30.64s
INFO: Build completed, 1 test FAILED, 61 total actions
//tensorflow_serving/batching:batch_scheduler_retrier_test               PASSED in 0.1s
//tensorflow_serving/batching:batching_session_test                      PASSED in 0.2s
//tensorflow_serving/batching:batching_util_test                         PASSED in 0.1s
//tensorflow_serving/batching:streaming_batch_scheduler_test             PASSED in 3.9s
//tensorflow_serving/batching/test_util:puppet_batch_scheduler_test      PASSED in 0.1s
//tensorflow_serving/core:aspired_version_policy_test                    PASSED in 0.1s
//tensorflow_serving/core:aspired_versions_manager_benchmark             PASSED in 29.6s
//tensorflow_serving/core:aspired_versions_manager_builder_test          PASSED in 0.4s
//tensorflow_serving/core:aspired_versions_manager_test                  PASSED in 6.3s
//tensorflow_serving/core:availability_preserving_policy_test            PASSED in 0.2s
//tensorflow_serving/core:basic_manager_test                             PASSED in 7.4s
//tensorflow_serving/core:caching_manager_test                           PASSED in 0.4s
//tensorflow_serving/core:dynamic_source_router_test                     PASSED in 0.2s
//tensorflow_serving/core:loader_harness_test                            PASSED in 0.2s
//tensorflow_serving/core:log_collector_test                             PASSED in 0.1s
//tensorflow_serving/core:manager_test                                   PASSED in 0.1s
//tensorflow_serving/core:request_logger_test                            PASSED in 0.1s
//tensorflow_serving/core:resource_preserving_policy_test                PASSED in 0.2s
//tensorflow_serving/core:servable_data_test                             PASSED in 0.1s
//tensorflow_serving/core:servable_id_test                               PASSED in 0.1s
//tensorflow_serving/core:servable_state_monitor_test                    PASSED in 0.1s
//tensorflow_serving/core:server_request_logger_test                     PASSED in 0.1s
//tensorflow_serving/core:simple_loader_test                             PASSED in 0.1s
//tensorflow_serving/core:source_adapter_test                            PASSED in 1.1s
//tensorflow_serving/core:source_router_test                             PASSED in 2.1s
//tensorflow_serving/core:static_manager_test                            PASSED in 0.1s
//tensorflow_serving/core:static_source_router_test                      PASSED in 0.1s
//tensorflow_serving/core:storage_path_test                              PASSED in 0.1s
//tensorflow_serving/model_servers:server_core_test                      PASSED in 29.6s
//tensorflow_serving/resources:resource_tracker_test                     PASSED in 0.1s
//tensorflow_serving/resources:resource_util_test                        PASSED in 0.2s
//tensorflow_serving/servables/hashmap:hashmap_source_adapter_test       PASSED in 0.1s
//tensorflow_serving/servables/tensorflow:bundle_factory_util_test       PASSED in 0.1s
//tensorflow_serving/servables/tensorflow:classifier_test                PASSED in 0.1s
//tensorflow_serving/servables/tensorflow:curried_session_test           PASSED in 0.1s
//tensorflow_serving/servables/tensorflow:get_model_metadata_impl_test   PASSED in 30.3s
//tensorflow_serving/servables/tensorflow:multi_inference_test           PASSED in 30.2s
//tensorflow_serving/servables/tensorflow:predict_impl_test              PASSED in 30.6s
//tensorflow_serving/servables/tensorflow:regressor_test                 PASSED in 0.1s
//tensorflow_serving/servables/tensorflow:saved_model_bundle_factory_test PASSED in 0.2s
//tensorflow_serving/servables/tensorflow:saved_model_bundle_source_adapter_test PASSED in 0.1s
//tensorflow_serving/servables/tensorflow:session_bundle_factory_test    PASSED in 0.2s
//tensorflow_serving/servables/tensorflow:session_bundle_source_adapter_test PASSED in 0.1s
//tensorflow_serving/servables/tensorflow:simple_servers_test            PASSED in 1.1s
//tensorflow_serving/servables/tensorflow:util_test                      PASSED in 0.1s
//tensorflow_serving/sources/storage_path:file_system_storage_path_source_test PASSED in 0.2s
//tensorflow_serving/sources/storage_path:static_storage_path_source_test PASSED in 0.1s
//tensorflow_serving/util:any_ptr_test                                   PASSED in 0.1s
//tensorflow_serving/util:class_registration_test                        PASSED in 0.1s
//tensorflow_serving/util:cleanup_test                                   PASSED in 0.1s
//tensorflow_serving/util:event_bus_test                                 PASSED in 0.1s
//tensorflow_serving/util:fast_read_dynamic_ptr_benchmark                PASSED in 26.2s
//tensorflow_serving/util:fast_read_dynamic_ptr_test                     PASSED in 2.0s
//tensorflow_serving/util:inline_executor_test                           PASSED in 0.1s
//tensorflow_serving/util:observer_test                                  PASSED in 0.2s
//tensorflow_serving/util:optional_test                                  PASSED in 0.1s
//tensorflow_serving/util:retrier_test                                   PASSED in 0.1s
//tensorflow_serving/util:threadpool_executor_test                       PASSED in 0.4s
//tensorflow_serving/util:unique_ptr_with_deps_test                      PASSED in 0.1s
//tensorflow_serving/model_servers:tensorflow_model_server_test          FAILED in 0.1s
  /home/marco/.cache/bazel/_bazel_marco/1710768e7be27f1ae88cd8999b286d87/execroot/tf_serving/bazel-out/k8-opt/testlogs/tensorflow_serving/model_servers/tensorflow_model_server_test/test.log

> Executed 60 out of 60 tests: 59 tests pass and 1 fails locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.

The log's output is as follow:

> exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
>  File "/home/marco/.cache/bazel/_bazel_marco/1710768e7be27f1ae88cd8999b286d87/execroot/tf_serving/bazel-out/k8-opt/bin/tensorflow_serving/model_servers/tensorflow_model_server_test.runfiles/tf_serving/tensorflow_serving/model_servers/tensorflow_model_server_test.py", line 72
    print 'Server is ready'
                          ^
SyntaxError: Missing parentheses in call to 'print'

The error is self-explanatory, just reporting it.

**Comment by zhangqinghao0811** [comment]
Do you means that we can ignore this error? I get same error and logs, will this problem cause any bug for tensorflow serving?

**Comment by marcokuchla** [comment]
I can't safely say to ignore this error, but, as the output shows, 59 of 60 tests successfully completed... so **maybe** there is no bug at all. In the end, It's up to you to decide.

**Comment by Redcxl** [comment]
So,how do you solved the problem. I met the same error.

**Comment by wt-huang** [comment]
In this case this error can be ignored. There are some syntax errors (python 2 to python 3 migration) that need to be fixed.

**Comment by xiaoyangnihao** [comment]
Do you solve this problem, I also met the same error ? "tensorflow_model_server_test" seems as one important test.
