### ISSUE TITLE
Add support for stateful models

### ISSUE THREAD

**Issue by riklopfer** [tensorflow/serving#724]
RNNs (for example) require that the internal state be maintained between sub-segments of a larger segment. Implementing this with the current version of TF Serving would require passing the state matrices over the network, which is less than ideal. 

SO: https://stackoverflow.com/questions/43710693/tensorflow-serving-stateful-lstm

**Comment by chrisolston** [comment]
You could eliminate the per-rnn-iteration network round-trips by building a custom binary that uses the TF-Serving "ServerCore" library. But the TF-Serving pre-packaged binaries do not support this use-case.

**Comment by Marko-Stamenovic-Bose** [comment]
> There's no good integration for stateful models in the model server yet. As you noted, it basically assumes models are pure functions. We're working on this, and you should see this functionality appear eventually, but it's too far out to promise a time. So in the meantime, you can write a simple wrapper which keeps state on the server (and assigns some sort of session ID which is passed around in requests), or you can write your own server which maintains the TensorFlow session state (and similarly returns some session ID). The latter is more performant. Both will require some sort of garbage collection/session timeout logic.

**Comment by michaelarfreed** [comment]
Is it possible add this information (the limitations of tf.saved_model API) to the documentation? I understand why this limitation exists, but I see no mention in the tf.saved_model documentation that the models cannot save state. If I am overlooking something, please let me know, but I spent a few weeks looking for documentation like this post and the SO link in the initial post, and it would've been nice to have clearer use-cases/platform limitations in [the docs](https://www.tensorflow.org/api_docs/python/tf/saved_model).

**Comment by nmatare** [comment]
I don't think this issue should be closed, as there doesn't appear to be a public discussion on plans (if any) to support stateful serving. We're currently holding state at the client before sending to the serving container, but a discussion of this limitation would be helpful to add to the `saved_model` documentation, per michael's above comment. (Happy to write and contribute) @chrisolston 

See the below link for a helpful internet sleuth summary of the issue:
https://stackoverflow.com/questions/49471395/adding-support-for-stateful-rnn-models-within-the-tf-serving-api
