### ISSUE TITLE
Is there a support for a multiple methods in single signature?

### ISSUE THREAD

**Issue by KineticCookie** [tensorflow/serving#726]
Hello.
I developed a simple model and I want to use Mutlitask Inference for it. But I got confused by the definition of a signature and methods, e.g.:
Signature(or is it a method?) is defined as:
```
classification_signature = (
      tf.saved_model.signature_def_utils.build_signature_def(
          inputs={
              tf.saved_model.signature_constants.CLASSIFY_INPUTS:
                  classification_inputs
          },
          outputs={
              tf.saved_model.signature_constants.CLASSIFY_OUTPUT_CLASSES:
                  classification_outputs_classes,
              tf.saved_model.signature_constants.CLASSIFY_OUTPUT_SCORES:
                  classification_outputs_scores
          },
method_name=tf.saved_model.signature_constants.CLASSIFY_METHOD_NAME))
```
Compose it to the metagraph (note the `signature_def_map`):
```
  builder.add_meta_graph_and_variables(
      sess, [tf.saved_model.tag_constants.SERVING],
      signature_def_map={
          'predict_images':
              prediction_signature,
          tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:
              classification_signature,
      },
legacy_init_op=legacy_init_op)
```
As you can see there is signature with method_name `f.saved_model.signature_constants.CLASSIFY_METHOD_NAME` and it lies within `signature_def_map` with the key `tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY`.

Could you please elaborate what `signature_def_map` is?
Is it possible to have multiple signatures, e.g. `classify_1` and `classify_2` inside the single key in `signature_def_map`, e.g. `classifiers`?

Thanks.

**Comment by kirilg** [comment]
For more about signatures, please read [this doc](https://github.com/tensorflow/serving/blob/f34e79a1ef0315d0f2d86eb0751a4c3700f8a433/tensorflow_serving/g3doc/signature_defs.md).

In short, a `signature_def_map` is a map of all signatures defined in a model.

The key in the map is the name of the signature, often called signature def key. It can be anything, and DEFAULT_SERVING_SIGNATURE_DEF_KEY is just a special constant that defines the default signature. This signature will be used if your request doesn't have a signature specified in the ModelSpec.

The signature_def_map can have many signatures, only one default signature, and each signature must have a unique key. So "classify_1", "classify_2", etc. will each point to a separate SignatureDef. To use a specific signature at request time, you'll need to set [signature_name](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/model.proto#L21) to the signature key you want to use.

**Comment by kirilg** [comment]
To answer the original question, there is no support for multiple methods in a single signature. Each signature corresponds to one method.
