### ISSUE TITLE
Not able to make predictions AbortionError(code=StatusCode.INVALID_ARGUMENT)

### ISSUE THREAD

**Issue by goodrahstar** [tensorflow/serving#732]
I am trying to make predictions but getting 2 version of error with the details below:

**Request data**

model_spec {
  name: "text"
  signature_name: "predict_class"
}
inputs {
  key: "dropout_keep_prob"
  value {
    dtype: DT_FLOAT
    tensor_shape {
    }
    float_val: 1.0
  }
}
inputs {
  key: "text"
  value {
    dtype: DT_INT64
    tensor_shape {
      dim {
        size: 100
      }
    }
    tensor_content: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\00"
}}

Errors:
`AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="You must feed a value for placeholder tensor 'dropout' with dtype float
	 [[Node: dropout  = Placeholder[_output_shapes=[<unknown>], dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]")`

and 

`AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="You must feed a value for placeholder tensor 'input_x' with dtype int64 and shape [?,100]
	 [[Node: input_x = Placeholder[_output_shapes=[[?,100]], dtype=DT_INT64, shape=[?,100], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]")`

The above 2 are the inputs for my model and it alternatively gives exception pointing out that the DTYPE is not correct.

Please help me to resolve this issue.

**Comment by kirilg** [comment]
It sounds like your model is configured with tensors `dropout` and `input_x` as placeholders and so they have to have a value in the request (currently you're only setting `dropout_keep_prob` and `text`). See https://www.tensorflow.org/api_docs/python/tf/placeholder for more details about placeholder.

**Comment by goodrahstar** [comment]
Thanks @kirilg , I tried to make the names of the placeholders same but still the same issue.

**Comment by goodrahstar** [comment]
I have provided values in the request body too.
`float_val: 1.0` for the dropout_keep_prob placeholder and
`tensor_content:"000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"` for the text placeholder.

Is this not sufficient, do I need to input something else?

Thanks

**Comment by kirilg** [comment]
Yes, but not for all tensors that are marked as placeholders. From the error message I think you need to feed a value for placeholder tensors `dropout` and `input_x`.

**Comment by gautamvasudevan** [comment]
Closing due to staleness.
