### ISSUE TITLE
Latency high after loading a new model. 

### ISSUE THREAD

**Issue by rmminusrslash** [tensorflow/serving#733]
we experience a similar problem to https://github.com/tensorflow/serving/issues/385 

Could you elaborate on how to do the warmup call to the model? 

What we tried to encode the request:

Normal request:
`      output = session.run(output_tensor, feed_dict={input_tensor_1: input_value_1, input_tensor_2: input_value_2})`

Request encoded as an operation that can be passed to the model saver:

- feed_dict: cannot be passed. Instead, we set default values to the placeholder input tensors that will be used if no parameters are given. That is ok since we don't care about the result of the warm up call.
- output_tensor: can be passes as the operation to be executed

Result:
```
legacy_init_op = tf.group(tf.tables_initializer(),output_tensor, name='legacy_init_op')
builder.add_meta_graph_and_variables(
        sess, [tf.saved_model.tag_constants.SERVING],
        signature_def_map={
            'output': signature,
        },
        legacy_init_op=legacy_init_op)
```

Remaining problem:
Grouping the operations does not insure sequential execution of the tables_initializer and the output_tensor, thus sometimes resulting in an exception. Trying other operations that insure ordering was also not successful.

Any ideas how to best do the warmup call?

**Comment by chrisolston** [comment]
A different approach would be to simply send some prediction request rpcs after the model has been loaded, containing dummy input data, which will force the model to warm itself up.

**Comment by rmminusrslash** [comment]
yes, we thought about that too, but only as the second best option, model intrinsic would be nicer since you have to remember to add it to all deployment pipelines. Ok, I will close the issue.
