### ISSUE TITLE
Serving tensorflow code in container

### ISSUE THREAD

**Issue by Pokharaa** [tensorflow/serving#738]
bazel build -c opt tensorflow_serving/example/..
Do I have to run this line everytime I restart the docker ?
It takes so much time. Isn`t there any alternative way?

**Comment by kirilg** [comment]
You only need to run that to build the example tutorials. Your Docker container should in theory keep the compiled files so you can just run them with bazel-bin/.... If you want just the server, you can simply install the prebuilt binary using apt-get (see [here](https://www.tensorflow.org/serving/setup) for instructions).
