### ISSUE TITLE
How to serve distributed models from TensorFlow distributed training

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/serving#739]
Now TensorFlow Serving can load the whole model in single server, but not for distributed training.

It would be great If the community is working on supporting the distributed models. Any progress about this?

If we want to load and serve the model, how can we do with/without TensorFlow Serving?

**Comment by chrisolston** [comment]
TF-Serving does not have built-in support for distributed model serving at this time, although we are considering adding some support in open-source. (Of course you can add a layer on top that does the sharding/routing/what-not of your model on top of a set of TF-Serving model servers that each serve one portion of a large model.)
