### ISSUE TITLE
add server status http endpoints support

### ISSUE THREAD

**Issue by yupbank** [tensorflow/serving#741]
if we are deploying a dedicated  serving server in docker, if would be nice if we expose http endpoints for status indicating..

**Comment by vitalyli** [comment]
This works, except there is bug there..
https://github.com/tensorflow/serving/issues/784

**Comment by unclepeddy** [comment]
This is available at https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/api_rest.md#model-status-api
