### ISSUE TITLE
Timeline C++ class to generate chrome trace format not available

### ISSUE THREAD

**Issue by agupta74** [tensorflow/serving#746]
I am not able to find C++ Timeline class (similar to Python Timeline API -- https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/timeline.py) to generate chrome trace format for the profiling data collected during session Run call using RunMetadata data structure. I would like to use it for profiling the TensorFlow serving and analyzing the performance.

**Comment by chrisolston** [comment]
Please ask on the main tensorflow github site.

**Comment by ydp** [comment]
@agupta74  Hi, sorry to bother you, did you find the way to generate timeline with C++? I need to profiling tensorflow serving too.
