### ISSUE TITLE
Add optional HTTP Rest endpoint for tensorflow_model_server

### ISSUE THREAD

**Issue by brunoklein99** [tensorflow/serving#754]
Would be great if `tensorflow_model_server` opened by default an HTTP REST endpoint for better interoperability.

**Comment by yupbank** [comment]
https://github.com/kubeflow/kubeflow/tree/master/components/k8s-model-server/http-proxy

There is one here... 

and if you are using k8s, you can deploy like this https://github.com/yupbank/cmle_proxy/blob/master/app.yaml

**Comment by gautamvasudevan** [comment]
This is also now supported natively.
