### ISSUE TITLE
serving/tensorflow does not exist

### ISSUE THREAD

**Issue by VeryVeryGoodNews** [tensorflow/serving#755]
Dear All,

I am attempting to create a tensorflow server in accordance with the instructions. The docker build command works, as does the docker run command after it. However, when I attempt to cd into serving/tensorflow it tells me file does not exist. Indeed 'ls' command reveals that the serving directory contains a tensorflow_server directory but no tensorflow directory. I looked at the repository on github and yes indeed the cloning was done correctly -- the repository does/did not contain(s) a tensorflow directory. 

What is going on? Help needed. 

**What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?:**

None

**Environment info:**
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

**Some reproducible code:**
Cloned the repo with no apparent problem:
```
:~$ git clone --recursive https://github.com/tensorflow/serving
Cloning into 'serving'...
Checking connectivity... done.
```

Performed docker build command, with no apparent problem:
```
~/serving$ docker build --pull -t $USER/tensorflow-serving-devel -f
 tensorflow_serving/tools/docker/Dockerfile.devel .
Sending build context to Docker daemon  6.178MB
Step 1/9 : FROM ubuntu:16.04 ...
Step 6/9 : ENV BAZEL_VERSION 0.5.4 ...
Successfully built 
Successfully tagged ../tensorflow-serving-devel:latest
```

Performed docker run command, with no apparent problem:
```
~/serving$ docker run --name=tensorflow_container -it $USER/tensorflow-serving-devel
root@26f2fg3e417:/#
`` `

Cloned repo from within docker container with no apparent problem:
```root@26f2fg3e417:/# git clone --recursive https://github.com/tensorflow/serving
Cloning into 'serving'...
remote: Counting objects: 6130, done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 6130 (delta 85), reused 103 (delta 59), pack-reused 5977
Receiving objects: 100% (6130/6130), 2.38 MiB | 0 bytes/s, done.
Resolving deltas: 100% (4358/4358), done.
Checking connectivity... done.
```

Attempt to cd into serving/tensorflow was problematic!:
```
:/# cd serving/tensorflow
bash: root@26f2fg3e417:/#: No such file or directory
``` 

-ls output:

```
root@...:/# ls
bazel  boot  etc   lib    media  opt   root  sbin     srv  tmp  var
bin    dev   home  lib64  mnt    proc  run   serving  sys  usr
```

cd serving, then ls:
```
/serving# ls
AUTHORS          LICENSE    RELEASE.md  tensorflow_serving
CONTRIBUTING.md  README.md  WORKSPACE   tools
```

**Comment by VeryVeryGoodNews** [comment]
I've been looking into what could be the problem. It seems that there was a new release on Jan 29th 2018 based on tf 1.5.0, and that repository has a different structure -- it is missing a /tensorflow directory. If this is intentional, then the tensorflow serving docs and tutorials are now stale and need to be updated.

**Comment by VeryVeryGoodNews** [comment]
Hello Friends, Why are these tensorflow forums so dormant? Does anyone know how I can get past the above described problem?

**Comment by zf109** [comment]
you can try manually clone it:
```bash
cd /serving && git clone --recursive https://github.com/tensorflow/tensorflow.git
```
not sure if that helps but it solves my problem :)

**Comment by ericbro64** [comment]
Linking this thread with the commit that made this change.
https://github.com/tensorflow/serving/commit/2c450d295765fe5f1871ecc2db65c4ffa9ca8c73

**Comment by VeryVeryGoodNews** [comment]
Thanks @zf109  your above solution worked for me!

**Comment by kirilg** [comment]
Sorry for the confusion. TensorFlow Serving moved to using TensorFlow as a bazel rule dependency instead of a submodule, so we no longer need the 'tensorflow' directory. Documentation should be updated soon, for now please disregard any instructions that say 'cd tensorflow', you no longer need to do that or run ./configure.

@case540

**Comment by VeryVeryGoodNews** [comment]
Problems persist. I was able to get past the 'cd serving/tensorflow' issue above, either by ignoring both it and the './configure' step, or by using method suggested by @zf109 above, i.e. cd into \serving and then run git clone command from there.

Next, Bazel build step works fine in either case.

However, Bazel crashed upon attempted model export. 

I suspect this latest problem may be related to issue #250, but I also suspect it is not unrelated to incongruities inadvertently introduced by the latest commit -- release 9. Help needed, please.

See crash code below:

```
/serving# bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --export_dir=inception-export

Traceback (most recent call last):
  File "/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/tf_serving/tensorflow_serving/example/inception_saved_model.py", line 204, in <module>
    tf.app.run()
  File "/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/tf_serving/tensorflow_serving/example/inception_saved_model.py", line 200, in main
    export()
  File "/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/tf_serving/tensorflow_serving/example/inception_saved_model.py", line 93, in export
    table = tf.contrib.lookup.index_to_string_table_from_tensor(class_tensor)
  File "/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/contrib/__init__.py", line 84, in <module>
    from tensorflow.contrib.eager.python import tfe as eager
  File "/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/contrib/eager/python/tfe.py", line 78, in <module>
    from tensorflow.contrib.eager.python.datasets import Iterator
  File "/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/contrib/eager/python/datasets.py", line 23, in <module>
    from tensorflow.contrib.data.python.ops import prefetching_ops
  File "/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/prefetching_ops.py", line 25, in <module>
    resource_loader.get_path_to_datafile("../../_prefetching_ops.so"))
  File "/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/../../_prefetching_ops.so: undefined symbol:  _ZN6google8protobuf8internal9ArenaImpl10AddCleanupEPvPFvS3_E

```

**Comment by ghisvail** [comment]
I was also able to build the model server by simply ignoring the configure step in the former `tensorflow` submodule and run the bazel build straight after checkout. I guess the content of the Docker images should be modified too?

**Comment by case540** [comment]
Yes, you should no longer have to run TensorFlow's configure script manually. The previous

serving/tensorflow/
serving/tf_models/

directories are no longer used in as part of the build and should be disappearing soon. Sorry if some of the documentation is out of date. Serving now depends on TensorFlow as a Bazel http_archive rule. https://docs.bazel.build/versions/master/be/workspace.html#http_archive

**Comment by pbrazdil** [comment]
This issue is related to this [commit](https://github.com/tensorflow/serving/commit/2c450d295765fe5f1871ecc2db65c4ffa9ca8c73) which broke the Dockerfiles inside this repository.

Can somebody fix it?

**Comment by fennudehaogua** [comment]
hello everyone!
try my images may be useful to everyone.
In fact, I do not know which part of my operation is important, but occasionally my tensorflow-serving worked correctly.
1.docker pull fennudehaogua/tensorflowserving:v1
(or docker pull registry.cn-hangzhou.aliyuncs.com/fennudehaogua/tensorflowserving:v1)
2. docker run -it fennudehaogua/tensorflowserving:v1 /bin/bash
3.cd serving
4. bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=inception --model_base_path=/tmp/inception-export &> inception_log &
5.bazel-bin/tensorflow_serving/example/inception_client --server=localhost:9000 --image=/serving/mycat.png

**Comment by Pokharaa** [comment]
Dear all, 
Hope this video tutorial will help to solve the above problem.
https://www.youtube.com/watch?v=SsaJJsRvwIs&lc=z22rvfpiaxfrdlavdacdp430a5bbb1smq04hvhfsh3dw03c010c
Check it once.

**Comment by zf109** [comment]
I took the Dockervile.devel's content out and made the following docker file and try to run it separately, 
```dockerfile
FROM ubuntu:16.04
RUN apt-get update && apt-get install -y \
        build-essential \
        curl \
        git \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        mlocate \
        pkg-config \
        python-dev \
        python-numpy \
        python-pip \
        software-properties-common \
        swig \
        zip \
        zlib1g-dev \
        libcurl3-dev \
        openjdk-8-jdk\
        openjdk-8-jre-headless \
        wget \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set up grpc
RUN pip install mock grpcio

# Set up Bazel.
ENV BAZELRC /root/.bazelrc
# Install the most recent bazel release.
ENV BAZEL_VERSION 0.5.4
WORKDIR /
RUN mkdir /bazel && \
    cd /bazel && \
    curl -fSsL -O https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh && \
    curl -fSsL -o /bazel/LICENSE.txt https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE && \
    chmod +x bazel-*.sh && \
    ./bazel-$BAZEL_VERSION-installer-linux-x86_64.sh && \
    cd / && \
    rm -f /bazel/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh

RUN git clone --recurse-submodules https://github.com/tensorflow/serving
RUN cd /serving && bazel test tensorflow_serving/...

CMD ["/bin/bash"]
```

but the build still fails and through the following error:
```bash
____Downloading https://mirror.bazel.build/github.com/aws/aws-sdk-cpp/archive/1.3.15.tar.gz: 5,658,119 bytes
____Downloading https://github.com/tensorflow/models/archive/6fc65ee60ac39be0445e5a311b40dc7ccce214d0.tar.gz via codeload.github.com: 33,523,718 bytes
ERROR: /serving/tensorflow_serving/example/BUILD:55:1: no such package '@inception_model//inception': Error downloading [https://mirror.bazel.build/github.com/tensorflow/models/archive/6fc65ee60ac39be0445e5a311b40dc7ccce214d0.tar.gz, https://github.com/tensorflow/models/archive/6fc65ee60ac39be0445e5a311b40dc7ccce214d0.tar.gz] to /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/inception_model/6fc65ee60ac39be0445e5a311b40dc7ccce214d0.tar.gz: Premature EOF and referenced by '//tensorflow_serving/example:inception_saved_model'.
ERROR: Analysis of target '//tensorflow_serving/example:inception_saved_model' failed; build aborted.
____Elapsed time: 153.126s
ERROR: Couldn't start the build. Unable to run tests.
```

from the looks of it it cannot find the inception_model package, interestingly, I tried it again and got different error:
```bash
ERROR: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/org_tensorflow/tensorflow/core/kernels/BUILD:2696:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:argmax_op' failed (Exit 1).
____Building complete.
____Elapsed time: 1407.844s, Critical Path: 51.65s
//tensorflow_serving/util:inline_executor_test                           PASSED in 0.2s
//tensorflow_serving/util:observer_test                                  PASSED in 0.3s
//tensorflow_serving/util:optional_test                                  PASSED in 0.2s
//tensorflow_serving/util:retrier_test                                   PASSED in 0.2s
//tensorflow_serving/util:status_util_test                               PASSED in 0.2s
//tensorflow_serving/util:threadpool_executor_test                       PASSED in 1.1s
//tensorflow_serving/util:unique_ptr_with_deps_test                      PASSED in 0.2s
//tensorflow_serving/batching:batch_scheduler_retrier_test            NO STATUS
//tensorflow_serving/batching:batching_session_test                   NO STATUS
//tensorflow_serving/batching:batching_util_test                      NO STATUS
//tensorflow_serving/batching:streaming_batch_scheduler_test          NO STATUS
//tensorflow_serving/batching/test_util:puppet_batch_scheduler_test   NO STATUS
//tensorflow_serving/core:aspired_version_policy_test                 NO STATUS
//tensorflow_serving/core:aspired_versions_manager_benchmark          NO STATUS
//tensorflow_serving/core:aspired_versions_manager_builder_test       NO STATUS
//tensorflow_serving/core:aspired_versions_manager_test               NO STATUS
//tensorflow_serving/core:availability_preserving_policy_test         NO STATUS
...
```

and every time I run it it gives different but similar error, whether some link failed or no such package. Not sure what went wrong in my local docker environment (checked resources as in men and volumes, they seem fine). Just wondering, could anyone help on this? or anyone give this a go and see if this docker file works?

**Comment by IvanJobs** [comment]
just run: 
git submodule update --init

**Comment by gary918** [comment]
Any further update about this issue?

**Comment by gunanadar** [comment]
The docs are still not updated. Did anyone find a solution?

**Comment by ZeroEffort** [comment]
It works fine for me on docker when installing tensorflow manually using `git clone --recursive https://github.com/tensorflow/tensorflow.git`  and then installed Bazel following the instructions here [https://github.com/tensorflow/tensorflow/issues/18450](url) (just make sure you installed Bazel version 0.11.1 and not 0.12.0 !! )  

Hope it helps you :)

**Comment by gunanadar** [comment]
Yeah Got it.. Thanks

**Comment by eduohe** [comment]
Thanks, @ZeroEffort using the bazel version 0.11.1 (https://github.com/tensorflow/serving/blob/fcfefeb1a321f955efce20bba2c9ba97fdbcc601/tensorflow_serving/tools/docker/Dockerfile.devel#L37) also worked here. 

The `bazel build -c opt tensorflow_serving/...` worked without need run clone `https://github.com/tensorflow/tensorflow.git` or the `./configure`

**Comment by aarorasimbulus** [comment]
Thanks @eduohe ! :D

**Comment by aroraakshit** [comment]
Thanks @eduohe ! :D

**Comment by lj200987** [comment]
为什么说明安装说明文档不更新呢？

**Comment by gautamvasudevan** [comment]
Docs have been updated, as has the Dockerfile.devel.
