### ISSUE TITLE
Installation of bazel takes lots of time..How to avoid it when creating new container in TF serving

### ISSUE THREAD

**Issue by Pokharaa** [tensorflow/serving#761]
I have already one container in my docker and now I want to add new container in it.
Is it not possible to add container without installing bazel each time I create new container.
Since I had already installed bazel while creating the previous container, Is it not possible to use it.
The installation of bazel really take more than 2 hours, so is there any solution to avoid it?
I a talking about this command line :
"bazel build -c opt tensorflow_serving/..."

**Comment by gautamvasudevan** [comment]
We now have development docker images you can pull without having to build everything at [Docker Hub](https://hub.docker.com/r/tensorflow/serving/tags). Pulling the latest-devel version should work for you.
