### ISSUE TITLE
How to support xgboost models in R? 

### ISSUE THREAD

**Issue by donigian** [tensorflow/serving#768]
Hi,
I've read the basic, [advanced](https://www.tensorflow.org/serving/serving_advanced) serving tutorials as well as source code of [tfdeploy](https://github.com/rstudio/tfdeploy), but I am still unclear for how to support xgboost (lightgbm etc) models developed in R.

Any help or suggestions would be appreciated...

**Comment by IvanJobs** [comment]
@donigian  I have actually the same question, but only I want to serve mxnet models. Any progress will be my interest :)

**Comment by yupbank** [comment]
hey... you should check this out https://github.com/yupbank/tree_to_tensorflow
i'm working on a branch to support xgboost.. but what really missing is to parse the model files dumped from xgboost

**Comment by gautamvasudevan** [comment]
Closing due to staleness.
