### ISSUE TITLE
Fixing tensorflow serving binary version

### ISSUE THREAD

**Issue by ankitspoke** [tensorflow/serving#773]
In order to install binaries for a particular version can I use these commands?

```
wget 'http://storage.googleapis.com/tensorflow-serving-apt/pool/tensorflow-model-server/t/tensorflow-model-server/tensorflow-model-server_1.5.0_all.deb'

dpkg -i tensorflow-model-server_1.5.0_all.deb
```

**Comment by bknl** [comment]
What is the actual question ? Your commands work if the machine you are doing this on has the right operating system and CPU type. They will sort of work but deliver a garbage installation if things do not match up.

**Comment by gautamvasudevan** [comment]
Closing due to staleness.
