### ISSUE TITLE
/serving/tensorflow# ./configure - Configuring the TensorFlow Serving

### ISSUE THREAD

**Issue by soumya-ranjan-sahoo** [tensorflow/serving#778]
Hi team,

I cloned github.com/tensorflow/serving  repo.  Sadly, it doesn't have any directory - tensorflow and a configure file in the directory.

Would, highly appreciate any help/fix.

Thanks in advance

**Comment by jhyan** [comment]
Same issue here.

**Comment by Kindrat** [comment]
Previously there was a git submodule pointing to a tensorflow repo. Just clone it to the same root, or extract released .tar.gz of the same version

**Comment by soumya-ranjan-sahoo** [comment]
Can you please provide the version name of the repo which had the sub-module tensorflow. Would be of great help.
Thanks.

**Comment by Kindrat** [comment]
Just skip that step. It is not required anymore. Just outdated docs. Look through https://github.com/tensorflow/serving/issues/755

**Comment by gautamvasudevan** [comment]
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!
