### ISSUE TITLE
Local deployment of TensorFlow Model using TensorFlow Serving build using bazel

### ISSUE THREAD

**Issue by soumya-ranjan-sahoo** [tensorflow/serving#786]
I was trying to follow the tutorial at https://www.tensorflow.org/serving/serving_basic.

It was all good until I ran the following command:
bazel-bin/tensorflow_serving/example/mnist_client --num_tests=1000 --server=localhost:9000 

(For testing the server using a built-in client utility given that I have already deployed my model successfully using tensorflow serving and it is up and running). It returned me with the following error:

mportError: dlopen(/Users/soumya.ranjan.sahoo/serving/bazel-bin/tensorflow_serving/example/mnist_client.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Symbol not found: _PyCObject_Type Referenced from: /Users/soumya.ranjan.sahoo/serving/bazel-bin/tensorflow_serving/example/mnist_client.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so Expected in: flat namespace in /Users/soumya.ranjan.sahoo/serving/bazel-bin/tensorflow_serving/example/mnist_client.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so

Failed to load the native TensorFlow runtime.

I was trying to follow the tutorial at https://www.tensorflow.org/serving/serving_basic.

I am all good until I ran this command:

bazel-bin/tensorflow_serving/example/mnist_client --num_tests=1000 --server=localhost:9000 
(For testing the server using a built-in client utility). It returned me with the following error:

ImportError: dlopen(/Users/soumya.ranjan.sahoo/serving/bazel-bin/tensorflow_serving/example/mnist_client.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Symbol not found: _PyCObject_Type Referenced from: /Users/soumya.ranjan.sahoo/serving/bazel-bin/tensorflow_serving/example/mnist_client.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so Expected in: flat namespace in /Users/soumya.ranjan.sahoo/serving/bazel-bin/tensorflow_serving/example/mnist_client.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

A quick help on this is highly appreciable.

**Comment by RayTsui** [comment]
This case when you use bazel-bin/tensorflow_serving/example/mnist_client --num_tests=1000 --server=localhost:9000 to request the service from server, it will produce the issue (I have it, either). If possible, install tensorflow-serving api python pip package, and instead using "python tensorflow_serving/example/mnist_client --num_tests=1000 --server=localhost:9000" (under serving/ directory) to request model service. 

I think it should work, at least it works for me. 

If you search online, when you use bazel-bin/.... to request the service, there are issues not to be solved yet.

**Comment by gautamvasudevan** [comment]
You can also see the latest [Docker examples](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) for bringing up a serving environment, which should be easier to deal with.
