### ISSUE TITLE
[Feature request] Java library in Maven central

### ISSUE THREAD

**Issue by Kindrat** [tensorflow/serving#790]
Any chances to get java library in maven central, guys? Tensorflow itself provides `protos`, but serving is not published yet.

**Comment by Kindrat** [comment]
Any news or ETA?

**Comment by si-you** [comment]
+1 to this. Any new or ETA? Maven package that includes proto definitions in serving/tensorflow_serving/apis would be extremely useful.

**Comment by debasish83** [comment]
I would like to publish it as part of tensorflow-java project to maven...which project I should use ? we are doing it internally through scrooge but I feel it should be included as part of mvn package...

**Comment by AnXi-TieGuanYin-Tea** [comment]
+1 to this. Maven package is need

**Comment by figroc** [comment]
Since there is no update from official team. I've setup a repo contains only proto generated library. It's published to maven central under the name `io.opil:tensorflow-serving-client`. You can checkout the repo: https://github.com/figroc/tensorflow-serving-client. May it be helpful.

**Comment by kevinashaw** [comment]
This would be very helpful!

**Comment by singhniraj08** [comment]
@Kindrat,

We don't offer active support for java (or scala) clients -- but of course you can maintain your own via the gRPC/proto interfaces. However there are community [builds](https://github.com/junwan01/tensorflow-serve-client) which can help setup Java client for Tensorflow Server. Thanks.

**Comment by Kindrat** [comment]
@singhniraj08 Sorry. In last 4 years we've already implemented own serving engine. So no need in this request any more, at least from my side.

**Comment by singhniraj08** [comment]
@Kindrat,

Requesting you to close this issue, if your request if fulfilled or not required anymore. Thank you for your contributions.
