### ISSUE TITLE
Compilation error ModuleNotFoundError: No module named 'StringIO'

### ISSUE THREAD

**Issue by maria8899** [tensorflow/serving#793]
Hi,
I have this problem when trying to compile serving with bazel
```
ERROR: /home/maria/serving/tensorflow_serving/model_servers/BUILD:277:1: MakeDeb tensorflow_serving/model_servers/tensorflow-model-server_undefined_all.deb failed (Exit 1)
Traceback (most recent call last):
  File "/home/maria/.cache/bazel/_bazel_maria/2fcd3367a80bb5bedac64bbf8613c54b/execroot/tf_serving/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb.runfiles/tf_serving/../bazel_tools/tools/build_defs/pkg/make_deb.py", line 19, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'
INFO: Elapsed time: 1171.787s, Critical Path: 70.01s
FAILED: Build did NOT complete successfully
```
It looks like it's using python3 and cannot find the python2 StringIO module. I can load StringIO using python2.
I've tried
``
$ bazel build --force_python=PY3 --host_force_python=PY3 -c opt --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-O3 tensorflow_serving/...
``
and
``
$ bazel build --force_python=PY2 --host_force_python=PY2 -c opt --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-O3 tensorflow_serving/...
``
but it  did not work. I also have tried to modify directly `make_deb.py`,  but then bazel is complaining about a corrupted file.

Any ideas?

**Comment by maria8899** [comment]
Solution: upgrade to bazel 0.11.0

**Comment by wangyi888** [comment]
Hello, I have the same problem with you when trying to compile serving with bazel-0.21.0
I've tried 
`bazel build -c opt --local_resources 2048,.5,1.0 --verbose_failures --action_env PYTHON_BIN_PATH=/home/abc/anaconda3/bin/python --action_env PYTHON_LIB_PATH=/home/abc/anaconda3/lib/python3.6/site-packages --define PYTHON_BIN_PATH=/home/abc/anaconda3/bin/python --define PYTHON_LIB_PATH=/home/abc/anaconda3/lib/python3.6/site-packages  --python_path=/home/abc/anaconda3/bin/python --force_python=py3 --host_force_python=py3 --define with_jemalloc=true --define with_gcp_support=true tensorflow_serving/...`
and it have the problem "ModuleNotFoundError: No module named 'StringIO'"

can you have some suggestions?

thanks
