### ISSUE TITLE
GPU as slow as CPU

### ISSUE THREAD

**Issue by TonyChouZJU** [tensorflow/serving#798]
I checked that the GPU is occupied and consumes GPU memory, but why the response is as slow as CPU serving. I'll be very appreciated if anyone could help me. Hope that someone could post a config about how to use GPU correctly. Thanks in advance.

**Comment by gareth-ferneyhough** [comment]
I would image that you will not see latency improvements when using the GPU for a single request. The benefit from using GPUs is that you can batch multiple requests and send them all to the GPU at once to be classified, which will give you higher throughput.

**Comment by chrisolston** [comment]
Thanks for the excellent answer gareth! Closing this issue.

**Comment by xxllp** [comment]
too bad ~~~
