### ISSUE TITLE
Pointer being freed was not allocated exception on mac sierra 

### ISSUE THREAD

**Issue by thub1** [tensorflow/serving#801]
the build completed with few warnings
`(tfenv) thubs@MacBook-Pro:~/Documents/Projects/serving$ bazel build -c opt //tensorflow_serving/example:mnist_saved_model`

> WARNING: /private/var/tmp/_bazel_thubs/f08c16d76711b4533e5b398b3d281cba/external/protobuf_archive/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_thubs/f08c16d76711b4533e5b398b3d281cba/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions
> WARNING: /private/var/tmp/_bazel_thubs/f08c16d76711b4533e5b398b3d281cba/external/org_tensorflow/tensorflow/core/BUILD:1865:1: in includes attribute of cc_library rule @org_tensorflow//tensorflow/core:framework_headers_lib: '../../../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'external/org_tensorflow/tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_thubs/f08c16d76711b4533e5b398b3d281cba/external/org_tensorflow/tensorflow/tensorflow.bzl:1163:30
> WARNING: /private/var/tmp/_bazel_thubs/f08c16d76711b4533e5b398b3d281cba/external/org_tensorflow/tensorflow/core/BUILD:1865:1: in includes attribute of cc_library rule @org_tensorflow//tensorflow/core:framework_headers_lib: '../../../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'external/org_tensorflow/tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_thubs/f08c16d76711b4533e5b398b3d281cba/external/org_tensorflow/tensorflow/tensorflow.bzl:1163:30
> WARNING: /private/var/tmp/_bazel_thubs/f08c16d76711b4533e5b398b3d281cba/external/grpc/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_thubs/f08c16d76711b4533e5b398b3d281cba/external/grpc/WORKSPACE (@com_github_grpc_grpc) does not match the name given in the repository's definition (@grpc); this will cause a build error in future versions
> WARNING: /private/var/tmp/_bazel_thubs/f08c16d76711b4533e5b398b3d281cba/external/org_tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule @org_tensorflow//tensorflow/contrib/learn:learn: target '@org_tensorflow//tensorflow/contrib/learn:learn' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
> WARNING: /private/var/tmp/_bazel_thubs/f08c16d76711b4533e5b398b3d281cba/external/org_tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule @org_tensorflow//tensorflow/contrib/learn:learn: target '@org_tensorflow//tensorflow/contrib/learn:learn' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately.
> INFO: Analysed target //tensorflow_serving/example:mnist_saved_model (1 packages loaded).
> INFO: Found 1 target...
> Target //tensorflow_serving/example:mnist_saved_model up-to-date:
>   bazel-bin/tensorflow_serving/example/mnist_saved_model
> INFO: Elapsed time: 8.783s, Critical Path: 1.11s
> INFO: Build completed successfully, 1 total action
> 

`
(tfenv) thubs@MacBook-Pro:~/Documents/Projects/serving$ bazel-bin/tensorflow_serving/example/mnist_saved_model /tmp/mnist_model`

> 
> Training model...
> Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
> Extracting /tmp/train-images-idx3-ubyte.gz
> Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
> Extracting /tmp/train-labels-idx1-ubyte.gz
> Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
> Extracting /tmp/t10k-images-idx3-ubyte.gz
> Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
> Extracting /tmp/t10k-labels-idx1-ubyte.gz
> 2018-03-12 13:42:27.854460: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX
> python(61477,0x7fff97620340) malloc: *** error for object 0x106ab4760: pointer being freed was not allocated
> *** set a breakpoint in malloc_error_break to debug
> Abort trap: 6
> 

No /tmp/mnist_model got generated either

**Comment by chrisolston** [comment]
This looks like an error on the training side, not serving. You might be able to get some answers on the main tensorflow github site.
