### ISSUE TITLE
build failed on linux

### ISSUE THREAD

**Issue by WinterW** [tensorflow/serving#802]
gcc: gcc version 4.8.1 (Ubuntu 4.8.1-2ubuntu1~12.04)
python: 2.7
bazel: 0.11.1
tensorflow_server:  
>branch:master 
sha:79d3354cd8a408fb981670512d661c2b7e89f5bf

error info:

> ERROR: /home/ganji/.cache/bazel/_bazel_ganji/eaefa8938b24102356d6cc3ba6fccbba/external/org_tensorflow/tensorflow/core/kernels/BUILD:2650:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:sparse_matmul_op' failed (Exit 1)
external/org_tensorflow/tensorflow/core/kernels/sparse_matmul_op.cc: In instantiation of 'tensorflow::SparseMatMul<TL, TR>::CreateSparseSlices(const ConstMatrixMapL&, bool, int, int, int, std::vector<std::vector<tensorflow::{anonymous}::SparseSlice<TL>*> >*, const tensorflow::DeviceBase::CpuWorkerThreads*) [with TL = float; TR = float; tensorflow::SparseMatMul<TL, TR>::ConstMatrixMapL = Eigen::TensorMap<Eigen::Tensor<const float, 2, 1, long int>, 16, Eigen::MakePointer>]::__lambda10':
external/org_tensorflow/tensorflow/core/kernels/sparse_matmul_op.cc:1175:62:   required from 'struct tensorflow::SparseMatMul<TL, TR>::CreateSparseSlices(const ConstMatrixMapL&, bool, int, int, int, std::vector<std::vector<tensorflow::{anonymous}::SparseSlice<TL>*> >*, const tensorflow::DeviceBase::CpuWorkerThreads*) [with TL = float; TR = float; tensorflow::SparseMatMul<TL, TR>::ConstMatrixMapL = Eigen::TensorMap<Eigen::Tensor<const float, 2, 1, long int>, 16, Eigen::MakePointer>]::__lambda10'
external/org_tensorflow/tensorflow/core/kernels/sparse_matmul_op.cc:1174:7:   required from 'static std::unique_ptr<tensorflow::BlockingCounter> tensorflow::SparseMatMul<TL, TR>::CreateSparseSlices(const ConstMatrixMapL&, bool, int, int, int, std::vector<std::vector<tensorflow::{anonymous}::SparseSlice<TL>*> >*, const tensorflow::DeviceBase::CpuWorkerThreads*) [with TL = float; TR = float; tensorflow::SparseMatMul<TL, TR>::ConstMatrixMapL = Eigen::TensorMap<Eigen::Tensor<const float, 2, 1, long int>, 16, Eigen::MakePointer>]'
external/org_tensorflow/tensorflow/core/kernels/sparse_matmul_op.cc:1536:77:   required from 'static void tensorflow::SparseMatMul<TL, TR>::Compute(tensorflow::SparseMatMul<TL, TR>::TensorInfoCache*, const ConstMatrixMapL&, const ConstMatrixMapR&, bool, const tensorflow::DeviceBase::CpuWorkerThreads*, bool, tensorflow::{anonymous}::MatrixMap*) [with TL = float; TR = float; tensorflow::SparseMatMul<TL, TR>::ConstMatrixMapL = Eigen::TensorMap<Eigen::Tensor<const float, 2, 1, long int>, 16, Eigen::MakePointer>; tensorflow::SparseMatMul<TL, TR>::ConstMatrixMapR = Eigen::TensorMap<Eigen::Tensor<const float, 2, 1, long int>, 16, Eigen::MakePointer>; tensorflow::{anonymous}::MatrixMap = Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long int>, 16, Eigen::MakePointer>]'
external/org_tensorflow/tensorflow/core/kernels/sparse_matmul_op.cc:1054:55:   required from 'void tensorflow::SparseMatMulOp<TL, TR, DoMatMul>::Compute(tensorflow::OpKernelContext*) [with TL = float; TR = float; DoMatMul = tensorflow::SparseMatMul]'
external/org_tensorflow/tensorflow/core/kernels/sparse_matmul_op.cc:1645:1:   required from here
external/org_tensorflow/tensorflow/core/kernels/sparse_matmul_op.cc:1175:24: error: use of 'tensorflow::SparseMatMul<TL, TR>::CreateSparseSlices(const ConstMatrixMapL&, bool, int, int, int, std::vector<std::vector<tensorflow::{anonymous}::SparseSlice<TL>*> >*, const tensorflow::DeviceBase::CpuWorkerThreads*) [with TL = float; TR = float; tensorflow::SparseMatMul<TL, TR>::ConstMatrixMapL = Eigen::TensorMap<Eigen::Tensor<const float, 2, 1, long int>, 16, Eigen::MakePointer>]::__lambda10::__sparse_slice' before deduction of 'auto'
           [=]() { work(sparse_slice, slice, slice_num_cols * j); });

**Comment by gautamvasudevan** [comment]
Closing - please see the latest [Docker examples](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) for bringing up a build environment.
