### ISSUE TITLE
create pip package path issue

### ISSUE THREAD

**Issue by brentian** [tensorflow/serving#804]
I'm trying to build the pip package from source using bazel

compiling is fine using the guide:

```sh
bazel test -c opt tensorflow_serving/...
```
then I tried to create pip package

```sh
bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package /tmp/
```
with error
```
cp: cannot stat 'bazel-serving/tensorflow_serving/apis/*_pb2.py': No such file or directory
```
 I looked into the script at serving/tensorflow_serving/tools/pip_package/build_pip_package.sh and found the problem is that it uses path `bazel-serving` instead of `bazel-tensorflow-serving`.

I changed output directory `bazel-tensorflow-serving` back to `bazel-serving`  and it works well. I suppose it could also be a quick fix by changing paths in the script.

**Comment by gautamvasudevan** [comment]
The script assumes you didn't clone into the directory you're in. The default directory that will be created is ./serving/, as this script is called from another script that follows that pattern.
