### ISSUE TITLE
[Feature request] Thread-safe model deployment

### ISSUE THREAD

**Issue by Kindrat** [tensorflow/serving#811]
**Existing problem:**
`ConfigReload` expects full list of models client wants to have with called serving instance, making it impossible to add single model definition per request. This forces client to host master copy of config list to be able add and remove entries to make gRPC calls (see https://github.com/tensorflow/serving/pull/809).

If there is only one remote client - it is possible to synchronise calls to guarantee `happens before` updates, but such approach adds limitation to use single thread for model deployment. If you'll try to make calls from different threads, you'll override first added model with second added model as second thread is not able to see list updates without synchronisation.

**Possible solution:**
Add gRPC APIs to add/remove single entries from global list on serving side. Synchronisation would be made by mutex on server side and would allow to write simple stateless remote clients.

**Affected version:**
1.5.0 (current)

**Comment by chrisolston** [comment]
After further discussion with my TF-Serving colleagues I unfortunately must retract my green light for an API for adding/removing models. We have an alternative proposal, which is described in the comment thread of https://github.com/tensorflow/serving/pull/809

**Comment by Kindrat** [comment]
Hi, guys. Do we have any API now?
