### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by Mazecreator** [tensorflow/serving#82]
In the section "**Generic Signatures (custom or advanced usage)**" of "serving/tensorflow_serving/session_bundle/README.md", "named_graph_signatures=signatures" is missing the "s" in the parameter name.  The example causes an error due to the incorrect parameter name.

> signatures = {
>     "regression": exporter.regression_signature(input_tensor=v0,
>                                                 output_tensor=v1),
>     "generic": exporter.generic_signature(named_tensor_bindings)}
> export = exporter.Exporter(saver)
> export.init(sess.graph.as_graph_def(),
>             named_graph_signature**s**=signatures)

**Comment by chrisolston** [comment]
I created a PR to fix that; will check it in shortly. Thanks.

#83

**Comment by chrisolston** [comment]
I merged the PR. Closing this issue.
