### ISSUE TITLE
Allow non-default Python paths?

### ISSUE THREAD

**Issue by KillPinguin** [tensorflow/serving#820]
Hi, I'm using conda on my machine, so e.g. numpy is not installed in the default ```/usr/lib/python2.7/dist-packages```. The build script can't cope with this though. Is there any way to build without installing numpy twice?

Example:
```tensorflow/third_party/toolchains/cpus/py/BUILD:195:cp "/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/oldnumeric.h"```
The path to numpy is hardcoded and thus the build fails on my machine with

```
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
```

**Comment by harshini-gadige** [comment]
@KillPinguin  -  Hi, is this still an issue ?

**Comment by KillPinguin** [comment]
I did not use TensorFlow or TensorFlow Serving for the last few months, so I'm fine.

**Comment by gautamvasudevan** [comment]
Feel free to file this with tensorflow/tensorflow. Thanks!
