### ISSUE TITLE
bazel takes more time to build

### ISSUE THREAD

**Issue by dhinar1991** [tensorflow/serving#822]
I am building tensorflow_serving inside docker using bazel. when i run this line `bazel build -c opt tensorflow_serving/...`

it takes more than 3 hours to build, I don't know if something is wrong here or any error. It still in the same process for three hours.

> 
> [1221,1224] Still waiting for 1 job to complete:
>     Running (local):
>          compiling external/org_tensorflow/tensorflow/core/kernels/batch-uti.c\c, 9221 s

is this an error? or does it usually takes this long? In few blogs, it is mentioned as 20-30 mins. Also i don't know if can come out of bazel while building. i tried closing the docker machine and re-entered the container it is still running. 

Any information is much appreciated.

**Comment by turowicz** [comment]
@dhinar1991 did it finish? I'm waiting for a GPU build with CPU optimisations. It's been 6 hours already and still going...

**Comment by turowicz** [comment]
cc @chrisolston maybe you can help?
