### ISSUE TITLE
Update TF commit to fix tensorflow_serving with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [tensorflow/serving#825]
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/178#79a684ed-3299-40c4-a16b-8d69452a39be

 TensorFlow Serving is failing with Bazel@HEAD due to https://github.com/bazelbuild/bazel/issues/4652

The fix has been merged to TensorFlow repo, please update TF commit to fetch the fix:
https://github.com/tensorflow/tensorflow/commit/15bda92cdb12bceb7c96404a3abafeed1a416651

**Comment by chrisolston** [comment]
I will try to get to it this week.

**Comment by jin** [comment]
@chrisolston Hi, this is the Bazel sheriff. Do you have an ETA for the TF commit fix?

**Comment by jin** [comment]
@chrisolston Hi, this is the Bazel sheriff. Do you have an ETA for the fix?

**Comment by lkmokadam** [comment]
Found same issue during building TensorFlow.

**Comment by sagnik** [comment]
same here.

**Comment by lkmokadam** [comment]
I was using bazel version 0.12.0, and getting this issue. I downgraded my bazel to 0.11.1, no repro of this issue.

**Comment by paul-mesnilgrente** [comment]
I could compile with Bazel 0.12.0 and the TensorFlow head. But if you want to compile TensorFlow 1.7.0 or previous, you have to downgrade Bazel to 0.11.0. And that is annoying. So I guess it is a bazel problem. Is it not?

**Comment by Oldpan** [comment]
I used Bazel 0.12.0 before and got the issue.And then I use Bazel 0.11.1 to build Tensorflow-1.7.0 to make tf work with CUDA9.1. But though I build it successfully with Bazel my cuda9.1 still doesn't work with tf-1.7.0,still the same "ImportError: libcublas.so.9.1: cannot open shared object file: No such file or directory"...

**Comment by meteorcloudy** [comment]
@chrisolston Any progress?

**Comment by gautamvasudevan** [comment]
I believe this issue is resolved.
