### ISSUE TITLE
 Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'index_type' not in Op

### ISSUE THREAD

**Issue by ecJon** [tensorflow/serving#831]
When I run grpc to request serving the serving post this fail~I make sure it all runing in tf 1.6.0 

2018-03-29 17:09:35.204261: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'index_type' not in Op<name=Fill; signature=dims:int32, value:T -> output:T; attr=T:type>; NodeDef: rnn/MultiRNNCellZeroState/BasicLSTMCellZeroState/zeros = Fill[T=DT_FLOAT, _output_shapes=[[?,8]], index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](rnn/MultiRNNCellZeroState/BasicLSTMCellZeroState/concat, rnn/MultiRNNCellZeroState/BasicLSTMCellZeroState/zeros/Const). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
  [[Node: rnn/MultiRNNCellZeroState/BasicLSTMCellZeroState/zeros = Fill[T=DT_FLOAT, _output_shapes=[[?,8]], index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](rnn/MultiRNNCellZeroState/BasicLSTMCellZeroState/concat, rnn/MultiRNNCellZeroState/BasicLSTMCellZeroState/zeros/Const)]]

**Comment by 12wzy** [comment]
Get similar error when I user tf 1.4.0 and tf-serving api 1.4.0. (**_output_type_**)
`AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="NodeDef mentions attr 'output_type' not in Op<name=ArgMax; signature=input:T, dimension:Tidx -> output:int64; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT64, DT_INT32, DT_UINT8, DT_UINT16, DT_INT16, DT_INT8, DT_COMPLEX64, DT_COMPLEX128, DT_QINT8, DT_QUINT8, DT_QINT32, DT_HALF]; attr=Tidx:type,default=DT_INT32,allowed=[DT_INT32, DT_INT64]>; NodeDef: output/score/output = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, _output_shapes=[[1]], output_type=DT_INT64, _device="/job:localhost/replica:0/task:0/cpu:0"](output/score/Softmax_1, output/score/output/dimension). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).`
And after I upgrade the tf to 1.5.0, the error is also similar. (**_dilation_**)
`ERR AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="NodeDef mentions attr 'dilation' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: output/cnn/conv-maxpool-3/conv = Conv2D[T=DT_FLOAT, _output_shapes=[[-1,598,1,256]], data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](output/ExpandDims, output/cnn/conv-maxpool-3/W/read). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).`

**Comment by lilao** [comment]
This could be caused by different tensorflow versions used to train and serve the model. You can try retraining your model with the same tensorflow version as tf serving. Here are some discussions on similar issues:
https://github.com/tensorflow/models/issues/1714
https://github.com/tensorflow/tensorflow/issues/1528
