### ISSUE TITLE
MODEL_SERVER : Using tag batch_parameters_file when platform_config_file is not empty

### ISSUE THREAD

**Issue by Li-Shu14** [tensorflow/serving#836]
The Flags of tensorflow_model_server says  `--platform_config_file=""        	string	If non-empty, read an ascii PlatformConfigMap protobuf from the supplied file name, and use that platform config instead of the Tensorflow platform. (If used, --enable_batching is ignored.)` and `--enable_batching` enables  `--batching_parameters_file`
But now I want to use both `platform_config_file` and  `batching_parameters_file`. Is there any ways to set both tags work or can `platform_config_file` includes the content of `batching_parameters_file` ?  Followings are the platform_config_file and batching_parameters_file I have written:
platform_config_file:
(platform_config_file is from #Is there an example of platform_config_file #342 )
```javascript
platform_configs {
  key: "tensorflow"
  value {
    source_adapter_config {
      [type.googleapis.com/tensorflow.serving.SavedModelBundleSourceAdapterConfig] {
        legacy_config {
          session_config {
            allow_soft_placement: true
            gpu_options {
              per_process_gpu_memory_fraction: 0.4
              allow_growth: true
            }
          }
        }
      }
    }
  }
}
```

batching_parameters_file:
( batching_parameters_file is from #Batching parameters #344)
 ```javascript
max_batch_size { value: 10000000 }
batch_timeout_micros { value: 200000000 }
max_enqueued_batches { value: 1000000 }
num_batch_threads { value: 36 }
```

**Comment by chrisolston** [comment]
If you --platform_config_file then you must supply the batching parameters by putting them inside your SavedModelBundleSourceAdapterConfig under legacy_config.batching_parameters.

**Comment by Li-Shu14** [comment]
@chrisolston Thanks so much for your suggestion and it works! 
Here's the final `platform_config_file` I used:
```javascript
platform_configs {
  key: "tensorflow"
  value {
    source_adapter_config {
      [type.googleapis.com/tensorflow.serving.SavedModelBundleSourceAdapterConfig] {
        legacy_config {
		  batching_parameters {
		  max_batch_size { value: 1000000 }
		  batch_timeout_micros { value: 200000000 }
		  max_enqueued_batches { value: 1000000 }
		  num_batch_threads { value: 36 }  
		  }
          session_config {
            allow_soft_placement: true
            gpu_options {
              per_process_gpu_memory_fraction: 0.4
              allow_growth: true
            }
          }
        }
      }
    }
  }
}
```
