### ISSUE TITLE
Why does a gRPC client needs the proto files?

### ISSUE THREAD

**Issue by R-Miner** [tensorflow/serving#837]
I successfully generated a python-python client-server tensorflow servings procedure.

 Now I am trying to develop a C3-python client-server with tensorflow serving, with a C# client that runs in windows with no python installed it that machine. 

My question is why I need the proto file in the client side when using gRPC. The whole purpose is to send the model, version of the model and the image for the server to do the predication and send back the result right?

rather 
Why a gRPC client needs  proto files?

Any help is appreciated!

**Comment by chrisolston** [comment]
The client needs to formulate an RPC request. The request is a protocol buffer. The proto files need to be compiled into the client so it knows how to write the TF-Serving request protocol buffers.

**Comment by pharrellyhy** [comment]
Hi, @chrisolston 

I'm not quite familiar with protocol buffer. Do it mean we need to install tensorflow in client side?

**Comment by gautamvasudevan** [comment]
No, protocol buffers are independent from tensorflow. See https://developers.google.com/protocol-buffers/ for more info.
