### ISSUE TITLE
error happens while "bazel build serving":  no such package '@org_tensorflow//tensorflow': java.io.IOException: thread interrupted

### ISSUE THREAD

**Issue by mona-abc** [tensorflow/serving#844]
When I tried to build tensorflow serving using bazel: **bazel build -c opt tensorflow_serving/...**
This error happened and the build failed:
**ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: thread interrupted**
My system is ubuntu, and the tensorflow version is 1.5. I can not solve this problem, looking forward to your help

**Comment by LuBingtan** [comment]
@mona-abc @jjz921024 did you solve this problem? Is it a download error？

**Comment by LuBingtan** [comment]
Tried to build again. The error message became this:
ERROR: build interrupted
INFO: Elapsed time: 228.822s
FAILED: Build did NOT complete successfully (266 packages loaded)

**Comment by YulinGUO** [comment]
@LuBingtan  Did you finally solve this error? I met this problem too....

**Comment by gautamvasudevan** [comment]
Closing - please see the latest [Docker examples](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) for bringing up a build environment.
