### ISSUE TITLE
Build error when using ENV BAZEL_VERSION 0.5.4 with TFS 1.6 master

### ISSUE THREAD

**Issue by AswathKiruba** [tensorflow/serving#854]
Hi, 
    When I was trying to install the Bazel(in the docker image) from docker file at `serving/ tensorflow_serving/ tools/ docker/ Dockerfile.devel` and build the tensorflow serving branch 1.6 (master), I was getting a build error stating 
ERROR: /root/.cache/bazel/_bazel_root/b0d74a6dd47d0a8ce4a61876568d3bad/external/org_tensorflow/third_party/clang_toolchain/cc_configure_clang.bzl:3:1: file '@bazel_tools//tools/cpp:cc_configure.bzl' does not contain symbol 'cc_autoconf_impl'.
ERROR: error loading package '': Extension file 'third_party/clang_toolchain/cc_configure_clang.bzl' has errors.

This because my bazel version was still 0.5.4. This could be avoided by updating the bazel version to the latest 0.12.0. 

It would be great to update the ENV BAZEL_VERSION (=0.5.4) at  `serving/ tensorflow_serving/ tools/ docker/ Dockerfile.devel` to latest bazel build version as the tensorflow tutorials reference this build the docker image.

**Comment by Yakings** [comment]
Try it. #863

**Comment by AswathKiruba** [comment]
Thanks, @Yakings , I have already mentioned in the post that it is working when we use 0.12.0 in the dockerfile. I tried it with multiple bazel versions. For TFS 1.6. and TF 1.7, bazel version 0.10.0 - 0.11.1 should work fine.
