### ISSUE TITLE
[1.7.0] Minimum Bazel Version mismatch with TensorFlow

### ISSUE THREAD

**Issue by shrutisharmavsco** [tensorflow/serving#862]
For TensorFlow 1.7.0, the [minimum version of bazel ](https://github.com/tensorflow/tensorflow/blob/r1.7/configure.py#L1383)required is `0.10.0` but for Tensorflow Serving 1.7.0, the [minimum version](https://github.com/tensorflow/serving/blob/r1.7/WORKSPACE#L37) is still `0.5.4`. Should that be changed to `0.10.0` since serving code has a dependency on the `tensorflow` repository? 

I realized this as I tried to build Tensorflow Serving code from source and failed because my Bazel version is `0.8.1`.

**Comment by Hijiao** [comment]
I've been stuck in the same problem when build  an image from [Dockerfile](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel), and  I update it :)  #863

**Comment by gautamvasudevan** [comment]
This has been fixed. Thanks!
