### ISSUE TITLE
class registry should compare with full name

### ISSUE THREAD

**Issue by ydp** [tensorflow/serving#868]
I am customize serving for my specialized usage, and come across this issue, code in [here](https://github.com/tensorflow/serving/blob/fcfefeb1a321f955efce20bba2c9ba97fdbcc601/tensorflow_serving/util/class_registration.h#L199) seems should use full_name compare, not the pointer address, can someone help me verify this?

current code:

```
    if (config.GetDescriptor() != config_descriptor_) {
      return errors::InvalidArgument(
          "Supplied config proto of type ", config.GetDescriptor()->full_name(),
          " does not match expected type ", config_descriptor_->full_name());
    }
```

should be ?

```
    if (config.GetDescriptor()->full_name() != config_descriptor_->full_name()) {
      return errors::InvalidArgument(
          "Supplied config proto of type ", config.GetDescriptor()->full_name(),
          " does not match expected type ", config_descriptor_->full_name());
    }
```

**Comment by chrisolston** [comment]
The code definitely works as-is, at least in our environment. It might work equally well with the full_name comparison.

Are you having a problem where the code is doing the wrong thing? If not let's leave it as-is.

**Comment by ydp** [comment]
Thanks for your reply, I think the problem occurred when config file was reloaded AND its path changed. I am using serving as dynamic library, which need to reload occasionally. When the library reload and its path changed, the program will core dump in this line of code.

When I changed it to full_name compare, it works fine now.  

So what exactly we want to compare here?  Do we want to make sure the config proto type correct like error message implied or we want to make sure the message never changed by someone else for security reason?

Sorry to bother, it not so important, just ignore here since it works for me now.

**Comment by ydp** [comment]
Sorry, opened PR twice, please use #873 .  

I closed 872 due to CLA issue.
