### ISSUE TITLE
bazel build failed in centOS

### ISSUE THREAD

**Issue by kylezhang1983** [tensorflow/serving#869]
I had a build failed when I follow https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md like that:

git clone --recurse-submodules https://github.com/tensorflow/serving
cd serving
 
bazel build -c opt tensorflow_serving/...

the error is : 
[kevin@sj-r15-svr31 serving]$ bazel build -c opt tensorflow_serving/...
ERROR: /home/ipa/kevin/.cache/bazel/_bazel_kevin/6c699de50d20346d3eca9a0fd8192f77/external/org_tensorflow/third_party/clang_toolchain/cc_configure_clang.bzl:3:1: file '@bazel_tools//tools/cpp:cc_configure.bzl' does not contain symbol 'cc_autoconf_impl'
ERROR: error loading package '': Extension file 'third_party/clang_toolchain/cc_configure_clang.bzl' has errors
ERROR: error loading package '': Extension file 'third_party/clang_toolchain/cc_configure_clang.bzl' has errors
INFO: Elapsed time: 0.067s
FAILED: Build did NOT complete successfully (0 packages loaded)

my bazel vesion is Build label: 0.9.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Aug 3 22:57:11 +50281 (1524566530631)
Build timestamp: 1524566530631
Build timestamp as int: 1524566530631

and I had install all prerequisites. 

could  anyone comment it?

thanks...

**Comment by lkluo** [comment]
@kylezhang1983: Have you finally successfully installed tf-serving on CentOS?

**Comment by lkluo** [comment]
@kylezhang1983: That is a little disappointed, but at least you solved your problem.

**Comment by kylezhang1983** [comment]
@lkluo Thanks for your kindly response! I need finish a  quick demo for my project as boss pushed to tight. 40 concurrency and there is a lot space to improve the performance. I believe tf_serving is a better solution. I will reserch it later

**Comment by gautamvasudevan** [comment]
Instructions for how to build have been updated since this was filed. Closing due to staleness. If you continue to have issues building, feel free to file a new bug.
