### ISSUE TITLE
latest tensorflow-serving-api (pip install) overwrite tensorflow1.7.0 with tensorflow1.8.0

### ISSUE THREAD

**Issue by daikankan** [tensorflow/serving#870]
my tensorflow version is 1.7.0, pip install tensorflow-serving-api will overwrite my tensorflow1.7.0 with tensorflow1.8.0, and tensorboard as well, what version of tensorflow-serving-api should I choose with tensorflow1.7.0?

**Comment by pockyym** [comment]
pip install tensorflow-serving-api==1.7.0

**Comment by ymodak** [comment]
Closing this issue since above solution is correct. Please feel free to reopen if issue still persists or want to add new information. Thanks!
> pip install tensorflow-serving-api==1.7.0
