### ISSUE TITLE
Runtime variability for batching

### ISSUE THREAD

**Issue by YuchenJin** [tensorflow/serving#874]
I want to find out the execution time vs. batch size when serving an inception-v3 model using TF-serving. I measured the duration of executing a batch by adding timers to the **wrapped_->Run** funtion in [/batching/batching_session.cc](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/batching/batching_session.cc#L611).

My code is below:
```cpp
auto t1 = std::chrono::high_resolution_clock::now();
status = wrapped_->Run(run_options, merged_inputs, output_tensor_names,
                         {} /* target node names */, &combined_outputs,
                         &run_metadata);
auto t2 = std::chrono::high_resolution_clock::now();
auto time_diff = std::chrono::duration_cast<std::chrono::microseconds>(t2-t1).count();
LOG(INFO) << (batch->num_tasks()) << ": " << (time_diff);  // This will log the batch size and the execution time of running this batch.
````

My batching_parameters_file is configured as:
```txt
max_batch_size { value: 128 }
batch_timeout_micros { value: 0 } 
```

**Setting**:
- Model served: Inception-v3.
- GPU: TITAN X (Pascal)
- Client request rate: 100req/s. A client at the same machine sends requests (images) to the server at uniform rate of 100 requestes per second.

I did an experiment with 9000 requests sent in total. The execution latency vs. batch size is plotted below. 
![tf_serving_latency](https://user-images.githubusercontent.com/15164320/39783360-a4f75486-52c9-11e8-8ebe-11009c334245.png)

We can observe the high variance of execution time of the same batch size, and some very small batches have larger execution time than batches with large batch size like 128. (I also tried tuning the batching parameters including num_batch_threads and max_enqueued_batches but this problem persists.) Do you guys know why it happens? Any idea is appreciated!

**Comment by harshini-gadige** [comment]
@netfs - Hi, could you please look into this ?

**Comment by hgadig** [comment]
Please go through this [batching guide](https://github.com/tensorflow/serving/tree/master/tensorflow_serving/batching) for Tensorflow Serving.

**Comment by hgadig** [comment]
Please look at the following issue related to performance and optimization tips.

https://github.com/tensorflow/serving/issues/89

**Comment by hgadig** [comment]
Closing this issue as it is in "awaiting response" status for more than a week. Feel free to add your comments and we will reopen.
