### ISSUE TITLE
 fatal error: third_party/nccl/nccl.h: No such file or directory

### ISSUE THREAD

**Issue by rickragv** [tensorflow/serving#875]
Hi i m using new tf_serving 1.7
third_party/nccl/nccl.h: No such file or directory
and i am not finding BUILD file in new directory , can anybody knows
As currently tensorflow is build by bazel.

ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/8bd6e58495e54c8cdf1fb8b1ed15e742/external/org_tensorflow/tensorflow/contrib/nccl/BUILD:23:1: error while parsing .d file: /home/ubuntu/.cache/bazel/_bazel_ubuntu/8bd6e58495e54c8cdf1fb8b1ed15e742/execroot/tf_serving/bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/contrib/nccl/_objs/python/ops/_nccl_ops_gpu/external/org_tensorflow/tensorflow/contrib/nccl/kernels/nccl_manager.pic.d (No such file or directory)
In file included from external/org_tensorflow/tensorflow/contrib/nccl/kernels/nccl_manager.cc:15:0:
external/org_tensorflow/tensorflow/contrib/nccl/kernels/nccl_manager.h:23:35: fatal error: third_party/nccl/nccl.h: No such file or directory
compilation terminated.
INFO: Elapsed time: 545.332s, Critical Path: 222.39s
FAILED: Build did NOT complete successfully

**Comment by cyberwillis** [comment]
Hi...
at tensorflow/third_party/nccl/nccl_configure.bzl
Exists a comment that says :

```
Repository rule for NCCL configuration.

nccl_configure depends on the following environment variables:

  TF_NCCL_VERSION : The NCCL version.
  NCCL_INSTALL_PATH: The installation path of the NCCL library.
```

you must set the these two variables on environment to succeed as mensioned here:

#327

**Comment by rickragv** [comment]
ok will try that

**Comment by cyberwillis** [comment]
If your problem get solved. Close this issue.

**Comment by rickragv** [comment]
Thanks @cyberwillis  it worked 
wget -q https://developer.download.nvidia.com/compute/redist/nccl/v2.1/nccl_2.1.15-1%2Bcuda9.0_x86_64.txz

and added 
TF_NCCL_VERSION : The NCCL version.
NCCL_INSTALL_PATH: The installation path of the NCCL library.

**Comment by cyberwillis** [comment]
That All I was talking about since the beginning!
