### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by zeliu** [tensorflow/serving#876]
centos6.5

when I execute "bazel build tensorflow_serving/..."

errors:
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /home/spider/serving/WORKSPACE:20:1: //external:io_bazel_rules_closure: no such attribute 'urls' in 'http_archive' rule.
ERROR: /home/spider/serving/WORKSPACE:20:1: //external:io_bazel_rules_closure: missing value for mandatory attribute 'url' in 'http_archive' rule.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': error loading package 'external': Could not load //external package.

**Comment by gautamvasudevan** [comment]
Try using the latest docker images to build. Closing due to staleness.
