### ISSUE TITLE
Latency high when reloading large model

### ISSUE THREAD

**Issue by pockyym** [tensorflow/serving#881]
version: r1.4
os: centos 7.2

I'm serving multiple models online using --model_config_file (over 10 models).   Under normal circumstance, each gRPC query costs less than 10ms with qps=70. When tf-serving starts to reload a new version of one model, gRPC latency gets extremely high, over hundreds of milliseconds, which causes massive gRPC timeout errors( _gRPC call return code: 4:Deadline Exceeded_ )

From tf-serving log file,  reloading a 3GB model takes over 10 seconds under online serving.  In the meantime, gRPC requests for other unchanged models get affected too. 

Any ideas or optimization methods?

**Comment by ymodak** [comment]
@pockyym Is this still an issue?. Please refer to the discussion [latency in serving](https://github.com/tensorflow/tensorflow/issues/20740)

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
