### ISSUE TITLE
Batching doesn't support sparse tensor input

### ISSUE THREAD

**Issue by pockyym** [tensorflow/serving#883]
We are trying --enable_batching for gpu acceleration.  Batching mode requires same dim0 size of all inputs, however, we have sparse tensor input .
https://www.tensorflow.org/api_docs/python/tf/sparse_to_dense
 And server returns an error 
_"Batching session Run() input tensors must have equal 0th-dimension size"_

Any Ideas of how to support sparse tensor in batching mode?

**Comment by chrisolston** [comment]
The ModelServer's batching capability only supports dense tensors. The tensorflow batch ops [1], which are special ops you embed in your tensorflow graph, do support sparse tensors ... although they are somewhat experimental.

[1] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/batching/python/ops/batch_ops.py

**Comment by ymodak** [comment]
Closing this issue since batching capability only supports dense tensors.
>https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/batching/python/ops/batch_ops.py
