### ISSUE TITLE
unable to compile in docker 

### ISSUE THREAD

**Issue by rnunziata** [tensorflow/serving#884]
Getting error compiling for gpu: running under docker tag: 9.0-cudnn7-devel-ubunut16.04. Have not idea what this ERROR means...can anyone help.

bazel build -c opt --config=cuda tensorflow_serving/...

WARNING: /root/.cache/bazel/_bazel_root/1b03e6b0b95a8320062041ca0659e00e/external/protobuf_archive/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/1b03e6b0b95a8320062041ca0659e00e/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions
ERROR: no such target '@org_tensorflow//third_party/gpus/crosstool:crosstool': target 'crosstool' not declared in package 'third_party/gpus/crosstool' defined by /root/.cache/bazel/_bazel_root/1b03e6b0b95a8320062041ca0659e00e/external/org_tensorflow/third_party/gpus/crosstool/BUILD
INFO: Elapsed time: 0.097s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

```

**Comment by ghisvail** [comment]
Same here with a CPU build:
```
Step 11/12 : RUN bazel build -c opt tensorflow_serving/... &&     cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server /usr/local/bin/ &&     bazel clean --expunge
 ---> Running in b25830f91639
Extracting Bazel installation...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
WARNING: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/protobuf_archive/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions
Loading: 21 packages loaded
Analyzing: 305 targets (22 packages loaded)
Analyzing: 305 targets (45 packages loaded)
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'PACKAGE:@org_tensorflow//tensorflow/contrib/seq2seq' (requested by nodes '@org_tensorflow//tensorflow/contrib:contrib_py com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@f14db7bd false (1405659652)')
INFO: Elapsed time: 14.799s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (137 packages loaded)
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:@org_tensorflow//tensorflow/contrib/seq2seq' (requested by nodes '@org_tensorflow//tensorflow/contrib:contrib_py com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@f14db7bd false (1405659652)')
[...java stack trace...]
```

**Comment by gautamvasudevan** [comment]
I think you're running out of memory. Try the latest [Docker instructions](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) and see if that ends up working for you.

**Comment by elvys-zhang** [comment]
Changing "@org_tensorflow//third_party/gpus/crosstool" in tools/bazel.rc to "@local_config_cuda//crosstool:toolchain" will fix it.

**Comment by ymodak** [comment]
@rnunziata Just wanted to follow up. Is still an issue?

**Comment by rnunziata** [comment]
no...you can close this.
