### ISSUE TITLE
New Instructions needed since Tensorflow Serving github repo has changed

### ISSUE THREAD

**Issue by johncleveland** [tensorflow/serving#892]
What are the new instructions for the basic tutorials for using the docker image and serving the inception model. The github repo https://github.com/tensorflow/serving has been modified but the instructions for the tutorials have not been. 
For example, https://github.com/tensorflow/serving no longer has a tensorflow directory and hence one cannot ./configure.

**Comment by cxfire16** [comment]
Here's what I did.
I drew guide from Siraj Raval's [Tutorial](https://github.com/llSourcell/How-to-Deploy-a-Tensorflow-Model-in-Production/blob/master/demo.ipynb)

I followed the instructions from the [repo](https://github.com/tensorflow/serving). Installed prerequisites like the packages and bazel.

then
`git clone --recursive https://github.com/tensorflow/serving`
but upon issuance of 
`cd serving/tensorflow` 
You get an error stating that there is no tensorflow directory. I simply cloned the whole tensorflow repository and went into the repo's folder and issued
`./configure`

I then encountered a warning stating that I'm using bazel 0.5.4 and that I need to update to 0.10.0 but I ignored it. I then executed the build command
`bazel build -c opt tensorflow_serving/...`
and encountered errors I wasn't able to log. But I immediately suspect the bazel to be behind it so I looked for a way to remove the current bazel and installed the version 0.10.0 which thankfully went flawless. Upon rerunning the build command, I then encountered another error still I wasn't able to log. But upon quick research here and there I was pointed towards updating the whole ubuntu package. And so I did thru apt-get update/upgrade and dist-upgrade. Took a while to finish then did a reboot. 
I Reran the build command again and this time it was successful. Note that the build took around 30 minutes. I then did a quick test using
`bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server`
and it was successful.

You can try recreating what I did. I'm stuck at loading models to the server atm as I'm yet to learn it.
Goodluck!

**Comment by gnobre** [comment]
Yesterday @netfs updated the `Dockerfile.devel` solving the bazel issues. The only thing left as I see is to add a git clone step for the tensorflow directory to be able to run `./configure` as the current instructions states.

**Comment by Shivang44** [comment]
This is a pretty big hole in the documentation... took me like an hour to figure out what to do until I found this bug issue. How can we get the documentation updated?

**Comment by netfs** [comment]
can you please point to the page that is incorrect, so i can fix it?

i thought the instructions for compiling from source were incorrect here:
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md#installing-from-source

but these look ok to me. hence the question.

thanks!

**Comment by gnobre** [comment]
It's the docker one: https://www.tensorflow.org/serving/docker

**Comment by netfs** [comment]
do these instructions look sane?
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md

if yes, i need to get these to the devsite (tensorflow.org).

**Comment by gnobre** [comment]
yes, it looks reasonable :+1:

**Comment by netfs** [comment]
thanks for taking a look. will have the devsite updated.
