### ISSUE TITLE
Does TF serving-1.7 build with cuda support ?

### ISSUE THREAD

**Issue by gautamkmr** [tensorflow/serving#895]
I don't see any message regarding cuda support on TF serving in README. 
I do see people tried to build with "--config=cuda" but there is no clear instruction which has succeeded.  Has this been supported officially if so what is the instruction.  Given the fact that TFServing does compilation of TF inside it but not sure how to pass instruction for TF from TFserving build to enable the GPU (Cuda) support.

**Comment by jorgemf** [comment]
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel-gpu

**Comment by gautamvasudevan** [comment]
Fixed by 8b567e2
