### ISSUE TITLE
Serving 1.8

### ISSUE THREAD

**Issue by OmriShiv** [tensorflow/serving#899]
Is there a timeline for Serving 1.8 or would it be possible to grab the current master and use the override method to build against the 1.8 release of Tensorflow?

**Comment by netfs** [comment]
we plan to release 1.8 early next week. this will be based off TF 1.8 release.

**Comment by OmriShiv** [comment]
Awesome, thanks!

**Comment by netfs** [comment]
jfyi 1.8.0 released few days back:

https://github.com/tensorflow/serving/releases/tag/1.8.0
