### ISSUE TITLE
About Serving API HandleReloadConfigRequest method

### ISSUE THREAD

**Issue by JohnHerry** [tensorflow/serving#909]
Hi, all,
    In serving r1.7 there is a HandleReloadConfigRequest method in the  model_service.proto file, but I can not find any relative method generated from it in the model_service_pb2.py file. Is this method used to hot-reload new model configs? why it is not provided in the python api?

**Comment by chrisolston** [comment]
Ah, we neglected to regenerate model_service_pb2.py. I'll do that shortly.

**Comment by JohnHerry** [comment]
@chrisolston  Thanks,  Found the update.
