### ISSUE TITLE
Yet another problem about high latency when loading a new model

### ISSUE THREAD

**Issue by weberxie** [tensorflow/serving#910]
I have noticed https://github.com/tensorflow/serving/issues/385, and have read https://ai.googleblog.com/2017/11/latest-innovations-in-tensorflow-serving.html.

Now, even if loading new models in a isolated thread pool, but the main operation process is RestoreOpsV2, which is run in the thread pool of session run, This means that the load operation is not completely run in a separate thread pool. **So, the serving query may be blocked by load operation.**

In our environment, the model file are stored on HDFS, when loading new model, the latency from a few milliseconds to thousands of milliseconds, I confirm this does not include model warm up time.

**Comment by weberxie** [comment]
I have resolved this problem by modify some code in tensorflow:
Adding a new thread pool only for load new model when construct DirectSession,
before loading new model I choose the specific thread pool instead of the default thread pool by set run_options.

**Comment by weberxie** [comment]
I would like to ask whether this is a bug, whether the community welcomes the submission of a patch, or whether there is a better way to solve this problem.

**Comment by weberxie** [comment]
@chrisolston @nfiedel sorry to bother you, I have read your [blog](https://ai.googleblog.com/2017/11/latest-innovations-in-tensorflow-serving.html),  can you give some advice?

**Comment by AlphaSue** [comment]
can you share how to do warm up? @weberxie

**Comment by weberxie** [comment]
@AlphaSue you can construct a fake input tensor from model signature, then call session run to warm up the whole model.

**Comment by tianyapiaozi** [comment]
@weberxie can you share your modification to tensorflow?

**Comment by ymodak** [comment]
@weberxie Just wanted to follow up. Is this still an issue?

**Comment by weberxie** [comment]
@ymodak I will see if I can reproduce it under the of version 1.10.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
