### ISSUE TITLE
Bazel CI failing since PR #902

### ISSUE THREAD

**Issue by laurentlb** [tensorflow/serving#911]
https://buildkite.com/bazel/tensorflow-serving/builds?page=2

On our CI, tensorflow serving is failing.
Culprit: https://github.com/tensorflow/serving/commit/c42810c1e149269d3bdeefa0fca56092215b1bb6
Logs: https://buildkite.com/bazel/tensorflow-serving/builds/636#cc0a7044-988a-4c18-9535-3f24fa9d9e4c

**Comment by gautamvasudevan** [comment]
Is this still failing?

**Comment by laurentlb** [comment]
@mhlopko

**Comment by mhlopko** [comment]
cc @meteorcloudy, current bazel sheriff

**Comment by meteorcloudy** [comment]
No, this issue has been fixed. 

But we still have an issue with Bazel@HEAD: https://github.com/bazelbuild/bazel/issues/5945
which should be fixed by https://github.com/tensorflow/serving/pull/1066

**Comment by chrisolston** [comment]
Closing this issue since apparently it has been fixed. (Thanks for the update @meteorcloudy )
