### ISSUE TITLE
Installing tensorflow serving in windows 10

### ISSUE THREAD

**Issue by R-Miner** [tensorflow/serving#926]
I am trying to install tensorflow serving with docker.
I installed docker following the instructions.
Then I followed the instructions in installing tensorflow servings.
The first step is a docker build command which throws me an error:
docker build Error checking context: 'can't stat '\\?\C:\Users\username\AppData\...

Any help appreciated!

**Comment by gautamvasudevan** [comment]
Sounds like this: https://github.com/docker/for-win/issues/338
