### ISSUE TITLE
Does TFServing support comparison strategy between multiple versions of model?

### ISSUE THREAD

**Issue by cchung100m** [tensorflow/serving#938]
Dear all,

I am a newbie to tensorflow serving and I'd like to know that does TFServing support comparison strategy between multiple versions of model and response the inference based on strategy to client? Because the client application usually know the model name but doesn't know the version number which model server offered and also want to get the best inference result in one request. Does anyone encounter this scenario/requirement in the production environment? 

Thanks in advance.
Best regards,

**Comment by chrisolston** [comment]
No, TF-Serving does not provide built-in support for doing any sort of comparison across versions. You can consider adding that to your client.

**Comment by cchung100m** [comment]
Hi @chrisolston,

Thanks for your reply.

Once I have a TF server serving multiple models, is there a way to query such server to know which models are served?

I run multiple versions of the model at server side but the client only get the latest version number through **GetModelMetadata** API

my client code:
```
request = get_model_metadata_pb2.GetModelMetadataRequest()
request.model_spec.name = 'model_name'
request.metadata_field.append("signature_def")
response = stub.GetModelMetadata(request, 10)

print(response.model_spec.version.value)
print(response.metadata['signature_def'])
```

**Comment by chrisolston** [comment]
Try GetModelStatus(): https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/model_service.proto#L17

**Comment by cchung100m** [comment]
Hi @chrisolston 

Thank you for the prompt reply.
I try to use  GetModelStatus() but encounter the import error issue, can you help to check my code?
Thank you very much.

mnist_client_query_model_version_v2.py code:
```
from __future__ import print_function
import sys
from grpc.beta import implementations
import tensorflow as tf
from tensorflow_serving.apis import model_service_pb2_grpc
from tensorflow_serving.apis import get_model_status_pb2
from tensorflow_serving.apis import get_model_metadata_pb2
from tensorflow_serving.apis import prediction_service_pb2
from tensorflow_serving.apis import predict_pb2, classification_pb2, inference_pb2, regression_pb2

tf.app.flags.DEFINE_string('server', '', 'PredictionService host:port')
FLAGS = tf.app.flags.FLAGS

def get_model_status(hostport):
        request = get_model_status_pb2.GetModelStatusRequest()
        request.model_spec.name = 'mnist'
        request.metadata_field.append("signature_def")

        host, port = hostport.split(':')
        channel = implementations.insecure_channel(host, int(port))
        stub = model_service_pb2_grpc.ModelServiceStub(channel)
        response = stub.GetModelStatus(request, 10)
        print(response.model_spec.version.value)

def main(_):
  if not FLAGS.server:
    print('please specify server host:port')
    return

  print('Sending GetModelStatus request...')
  get_model_status(FLAGS.server)

if __name__ == '__main__':
  tf.app.run()

```

root@59dbb35082c6:/notebooks/downloads# python3 mnist_client_query_model_version_v2.py --server=localhost:9000

> /usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Traceback (most recent call last):
>   File "mnist_client_query_model_version_v2.py", line 23, in <module>
>     from tensorflow_serving.apis import model_service_pb2_grpc
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow_serving/apis/model_service_pb2_grpc.py", line 24, in <module>
>     import tensorflow_serving.apis.get_model_status_pb2 as tensorflow__serving_dot_apis_dot_get__model__status__pb2
> ImportError: No module named 'tensorflow_serving.apis.get_model_status_pb2'


System Information:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

pip list | grep -i "tensorflow"
tensorflow (1.8.0)
tensorflow-gpu (1.4.0)
tensorflow-serving-api-python3 (1.7.0)
tensorflow-tensorboard (0.4.0)

apt list | grep -i "tensorflow"
tensorflow-model-server/unknown,now 1.8.0 all [installed]
tensorflow-model-server-universal/unknown 1.8.0 all
```

reference : 

> https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/tensorflow_model_server_test.py

**Comment by cchung100m** [comment]
Dear all,

I closed this issue and open another ticket because I am stuck with the import problem which is already irrelevant to original issue.
