### ISSUE TITLE
Compile warnings

### ISSUE THREAD

**Issue by robertcrowe** [tensorflow/serving#94]
I'm getting a lot of compile warnings from bazel, mostly around comparisons between signed and unsigned integers.  Wouldn't it make sense to clean these up?  Or are other people not getting them?

**Comment by nfiedel** [comment]
Hi robertcrowe@,
  Are you seeing any of these specific to Serving, or are these general TensorFlow? If so, it looks like there have been some ongoing efforts to clean them up. E.g. https://github.com/tensorflow/tensorflow/issues/128

**Comment by robertcrowe** [comment]
Hi nfiedel@,

They're specific to Serving, and I haven't seen any warnings for Tensorflow itself (but I also haven't compiled it).  I saw them during installation of Serving when running bazel.

`bazel build tensorflow_serving/...`

**Comment by sukritiramesh** [comment]
Hi @robertcrowe, thanks for reporting. Most of the compile warnings I see are from tensorflow/core/*. If you are still seeing warnings specific to tensorflow_serving, could you add them here? Would help investigate further; thanks.

**Comment by kirilg** [comment]
Confirmed that all the `bazel build` warnings we get are indeed from TensorFlow (a dependency) and other repos that TensorFlow Serving depends on. As mentioned in the GitHub issue that Noah linked, TensorFlow is working on cleaning those warnings up, but signed/unsigned comparison warnings will likely continue to creep up (and individually fixed).
