### ISSUE TITLE
NMT TF model checkpoints conversion to TF JS compatible format.

### ISSUE THREAD

**Issue by Ak-sky** [tensorflow/serving#941]
Hi All,
I am very new to NMT field and with the help of NMT tutorial I have built a NMT system for French-English translation. I am successfully able to do the inference but now I want to use TensorFLow JS to do the  translations. In **out_dir** folder I have the checkpoints but I am not sure how to convert those check points into TensoFlow JS compatible models. Below is the screen shot for checkpoints

![image](https://user-images.githubusercontent.com/4889052/41397275-51f75554-6fd1-11e8-9c99-96545e890a00.png)

I believe the checkpoints are nothing but session bundles as mentioned here -
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/session_bundle/README.md

"**The TensorFlow Saver writes checkpoints (graph variables) while training so it can recover if it crashes. A TensorFlow Serving export contains a checkpoint with the current state of the graph variables along with a MetaGraph definition that's needed for serving.** "

Please help me how do I proceed in converting those models in TF JS format.
Thanks!

**Comment by gautamvasudevan** [comment]
This might be better answered on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow.js), as this isn't particularly related to TensorFlow Serving or a code issue. Thanks!
