### ISSUE TITLE
Serve Multiple Versions simultaneously Error

### ISSUE THREAD

**Issue by brianalois** [tensorflow/serving#945]
I am trying to serve multiple version of a model at the same time. 
Mt goal is to get both these API endpoints working at the same time
http://localhost:8501/v1/models/xor/versions/3:predict
http://localhost:8501/v1/models/xor/versions/4:predict

right now only the higher number version will work so that is the one with version 4. How would I get both to work at the same time?

**Comment by chrisolston** [comment]
By default, only the latest version is served. To serve multiple versions simultaneously you'll have to change the "version policy" configuration. See https://github.com/tensorflow/serving/blob/master/tensorflow_serving/config/model_server_config.proto#L48

**Comment by cchung100m** [comment]
Hi @brianalois,

You can assign the version policy when starting the server.
Please check the issue I had encountered. #918 

Hope helps,

**Comment by brianalois** [comment]
Thanks that Solves the Issue just to have it in this answer as well, the config file that should look something like this.

```
model_config_list: {
  config: {
    name:  "xor",
    base_path:  "/home/models/xor",
    model_platform: "tensorflow",
    model_version_policy: {
        all: {}
    }
  }
}
```
