### ISSUE TITLE
serving java proto to maven

### ISSUE THREAD

**Issue by debasish83** [tensorflow/serving#947]
tensorflow proto are available in maven but serving proto are not available. I would like to provide a pull request to push it to maven so that it can be used in conjunction with tensorflow proto...Most project (including my current fix) copies the protos from serving.api and I used tensorflow proto for avoiding some of the copy but now I have 2 variants of some common java protos... Publishing them possibly with tensorflow proto will make life easier for java/scala clients..Please provide some feedbacks that whether it should be separate jar published from serving along with tensorflow proto which are possibly getting published from tensorflow repo.

**Comment by chrisolston** [comment]
Sorry, we don't offer active support for java (or scala) clients -- but of course you can maintain your own via the gRPC/proto interfaces.

**Comment by rahulsmehta** [comment]
Can this request be revisited? Given that TF core publishes these I don't quite see why this should be unsupported

**Comment by chenjia123** [comment]
why your don't offer java client?

**Comment by chenjia123** [comment]
Why don't you offer java client?

**Comment by rahulsmehta** [comment]
If this won't be done, are the .proto files published to any maven repo? I'd like to include something in my buildscript to download the proto defs from a particular version
