### ISSUE TITLE
Quick Help Please! Resful API classify example

### ISSUE THREAD

**Issue by brianalois** [tensorflow/serving#954]
I am having trouble getting the **classify** action on the rest api to work at all. 
I have looked at this extensively: https://www.tensorflow.org/serving/api_rest
 
does anyone have and example using classify on the restful api that tensorflow serving provides?
Here is my request url: POST
```
http://localhost:8501/v1/models/iris:classify
```
Data being sent
```
{
	"examples":[{
		"x": [5.1, 3.5, 1.4, 0.2]
	}]
}
```

Need help please

**Comment by netfs** [comment]
did classify work with the example described here:
https://www.tensorflow.org/serving/api_rest#example
