### ISSUE TITLE
BatchingSession Example?

### ISSUE THREAD

**Issue by viksit** [tensorflow/serving#96]
- Are there any pointers to examples for `BatchingSession` in the servable/manager use case?
- Also for `SharedBatchScheduler`?
- Assuming I have n models being served on one server, my guess is that the `SharedBatchScheduler` is the ideal system to use -- given that the Basic or Streaming schedulers are dependent on one model and will block concurrent requests to multiple models citing batch size issues.

My question around SharedBatchScheduler usage is around queue creation - does one need to create a queue for all n models that are loaded in memory (as the unit test seems to suggest)? 

@kirilg (I asked this question on the perf thread but now moving it here since I'm adding a few more things about `BatchingSession` as well that are related.)

**Comment by chrisolston** [comment]
Hi @viksit,

The best usage example of BatchingSession used in conjunction with SharedBatchScheduler is SessionBundleFactory [1]. SessionBundleFactory underlies SessionBundleSourceAdapter, which our demo code uses but with batching disabled (our demos do batching over the top). If you want SessionBundleSourceAdapter to produce Session objects that do batching internally (with SharedBatchScheduler), you just have to populate SessionBundleSourceAdapterConfig->SessionBundleConfig->BatchingParameters.

Yes, you'll need one queue per model / model-version to which you want to issue requests. SessionBundleSourceAdapter automatically creates a queue for each, and tears them down in its destructor.

[1] https://github.com/tensorflow/serving/blob/master/tensorflow_serving/servables/tensorflow/session_bundle_factory.cc

**Comment by chrisolston** [comment]
For an end-to-end example of using BatchingSession+SharedBatchScheduler, see mnist_inference.cc, specifically this part of the code that populates the BatchingParameters: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_inference.cc#L194 .  It is discussed in the basic serving tutorial at https://tensorflow.github.io/serving/serving_basic (grep for "BatchingParameters").

Note, however, that mnist_inference only loads a single model so it doesn't really take advantage of the "sharing" aspect of the scheduler. Hopefully it's easy to see how you could load multiple models or multiple versions of a model -- each one would get its own BatchingSession via the source adapter that internally contains a SharedBatchScheduler queue for that model/version.

-Chris
