### ISSUE TITLE
docker image for tensorflow serving is too big

### ISSUE THREAD

**Issue by coffeedjimmy** [tensorflow/serving#963]
Hi, folks.

I've encountered one problem in building tensorflow serving.

I pull the docker image for tensorflow-gpu_1.7.0. After that I install several dependencies.

Lastly, I clone the tensorflow serving repo and build it with bazel. 

However, after the build process, the commited image is larger than 8GB. Before the build process, it was about 4GB. 

Is this normal situation when build tensorflow serving? or any problem in my process?

I tested this on docker container with `Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial`.

Thanks.

**Comment by gautamvasudevan** [comment]
Not sure. Are you looking for an environment in which you build a custom version of Tensorflow Serving? 

Try building our recently (as of a few hours ago) updated [Dockerfiles](https://github.com/tensorflow/serving/tree/master/tensorflow_serving/tools/docker). The GPU image for TF Serving looks to be about 4GB, of which 1GB is TF Serving and it's build artifacts, with the rest being dependencies pulled in from apt-get.

**Comment by hienduyph** [comment]
I think we can separate the build container and the binary image. In build container, just pull the deps from apt-get, and then pack the tensorflow_model_server (along with cuda, cudnn if you use cuda) to the binary image.

**Comment by gautamvasudevan** [comment]
Yes, this is how it's arranged currently (the standard Dockerfile is just as you said). This is also reflected in Docker Hub as latest vs. latest-devel.
