### ISSUE TITLE
How to convert checkpoint files to tf-servable format (tf.Builder)

### ISSUE THREAD

**Issue by gr8Adakron** [tensorflow/serving#966]
I have following checkpoint files of tensorflow model:

![nasnet-checkpoints](https://user-images.githubusercontent.com/16715364/42088998-323608b6-7bb9-11e8-8af9-0c3ed146a7cf.png)

And, I am trying to convert this checkpoint files into the tensorflow-serving acceptable format that is; this structure:

![sample_model_2](https://user-images.githubusercontent.com/16715364/42089033-50091c5c-7bb9-11e8-9fa6-8add82b9048d.png)

As from the reference of these two scripts,
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_saved_model.py
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_saved_model.py

 I can figure out that it requires to save the model using [Save Builder](https://www.tensorflow.org/api_docs/python/tf/saved_model/builder/SavedModelBuilder) function.

But I am not able to find out, anybody can help? How can I convert and serve the model on the Tensorflow-Serving.

**Comment by Aurora11111** [comment]
Maybe you can try as the link:https://towardsdatascience.com/how-to-deploy-machine-learning-models-with-tensorflow-part-2-containerize-it-db0ad7ca35a7
