### ISSUE TITLE
PC-relative offset overflow in GOT PLT entry for `cublasDsyr2k_v2@@libcublas.so.9.0'

### ISSUE THREAD

**Issue by yuandaxing** [tensorflow/serving#968]
Hi: 
  I build a docker image use "Dockerfile.devel-gpu" file.  And the head of the docker file as below:

FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

LABEL maintainer=gvasudevan@google.com

# Install NCCL
ENV NCCL_VERSION=2.2.12-1+cuda9.0
RUN echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list

Then i start the docker and build serving use this command:
bazel --output_user_root=./tmp/ build --copt="-lm" --color=yes --curses=yes --config=cuda  --output_filter=DONT_MATCH_ANYTHING  --crosstool_top=@local_config_cuda//crosstool:toolchain ${TF_SERVING_BUILD_OPTIONS} --verbose_failures  tensorflow_serving/...
after solving a lot of problems, i stuck in the problem below:
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o: In function `_init':    [54/1630]
(.init+0x7): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symbol `__gmon_s
tart__'
/usr/lib/gcc/x86_64-linux-gnu/5/crtbeginS.o: In function `deregister_tm_clones':
crtstuff.c:(.text+0x3): relocation truncated to fit: R_X86_64_PC32 against `.tm_clone_table'
crtstuff.c:(.text+0xa): relocation truncated to fit: R_X86_64_PC32 against symbol `__TMC_END__' def
ined in .nvFatBinSegment section in bazel-out/k8-fastbuild/bin/tensorflow_serving/servables/tensorf
low/session_bundle_source_adapter_test
crtstuff.c:(.text+0x1e): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symb
ol `_ITM_deregisterTMCloneTable'
/usr/lib/gcc/x86_64-linux-gnu/5/crtbeginS.o: In function `register_tm_clones':
crtstuff.c:(.text+0x43): relocation truncated to fit: R_X86_64_PC32 against `.tm_clone_table'
crtstuff.c:(.text+0x4a): relocation truncated to fit: R_X86_64_PC32 against symbol `__TMC_END__' de
fined in .nvFatBinSegment section in bazel-out/k8-fastbuild/bin/tensorflow_serving/servables/tensor
flow/session_bundle_source_adapter_test
crtstuff.c:(.text+0x6b): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symb
ol `_ITM_registerTMCloneTable'
/usr/lib/gcc/x86_64-linux-gnu/5/crtbeginS.o: In function `__do_global_dtors_aux':
crtstuff.c:(.text+0x92): relocation truncated to fit: R_X86_64_PC32 against `.bss'
crtstuff.c:(.text+0x9c): relocation truncated to fit: R_X86_64_GOTPCREL against symbol `__cxa_final
ize@@GLIBC_2.2.5' defined in .text section in /lib/x86_64-linux-gnu/libc.so.6
crtstuff.c:(.text+0xaa): additional relocation overflows omitted from the output
bazel-out/k8-fastbuild/bin/tensorflow_serving/servables/tensorflow/session_bundle_source_adapter_te
st: PC-relative offset overflow in GOT PLT entry for `cublasDsyr2k_v2@@libcublas.so.9.0'
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 1874.213s, Critical Path: 1349.35s
FAILED: Build did NOT complete successfully

it is really frustrating to build, please help.

**Comment by yuandaxing** [comment]
finally I build tensorflow with --copt="-O3" and the build succeed.
but when  I run the binary.
./bazel-bin/tensorflow_serving/model
_servers/tensorflow_model_server --port=9000 --model_name=inception --model_base_path=/data/noteboo
ks/yuandaxing1/OCR/CNN_LSTM_CTC_Tensorflow/export/
I got the error below:
2018-07-01 13:25:59.343164: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc
:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-01 13:25:59.346457: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.c
c:397] failed call to cuInit: CUresult(-1)
2018-07-01 13:25:59.346515: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnost
ics.cc:163] retrieving CUDA diagnostic information for host: df55e1c6ae78
2018-07-01 13:25:59.346675: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnost
ics.cc:170] hostname: df55e1c6ae78
2018-07-01 13:25:59.346820: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnost
ics.cc:194] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into t
his program

**Comment by netfs** [comment]
there have been numerous fixes to GPU docker files in past few days. can you please retry build using latest Dockerfile.devel-gpu from master tip (or any of release branch r1.9, r1.8 tip) sources?

alternatively you can use the official release or nightly docker images (xxx-devel-gpu):
https://hub.docker.com/r/tensorflow/serving/tags/

(note, you will need [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) to use them)
