### ISSUE TITLE
Compiling error 

### ISSUE THREAD

**Issue by oak-tree** [tensorflow/serving#97]
Hello
I'm trying to follow the instruction at https://tensorflow.github.io/serving/serving_inception. 
It all good up until the line 
`bazel build -c opt tensorflow_serving/...`
After very very long run this command fails with the following error 

## ERROR: 

/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/tf/tensorflow/core/kernels/BUILD:857:1: C++ compilation of rule '@tf//tensorflow/core/kernels:argmax_op' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 70 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)

## BAZEL CONFIGURATION

/serving/tensorflow# cat ~/.bazelrc
startup --batch
build --spawn_strategy=standalone --genrule_strategy=standalone

**Comment by kirilg** [comment]
This is likely a problem with your environment. Could you include what OS/version you're using and what version of Bazel you have installed?

Also, could you include the full error message that was printed? I don't see what target it was trying to compile when the error occurred.

This [issue](https://github.com/tensorflow/models/issues/80) seems to have a similar problem but in tensorflow/models, could you see if your root cause is the same?

**Comment by eeriee** [comment]
Hi kirilg,
I met the same problem when I run ` bazel build -c opt tensorflow_serving/... ` in a docker container.
The error message is as below:
```
INFO: Found 145 targets...
INFO: From Compiling external/tf/tensorflow/python/lib/core/py_func.cc [for host]:
In file included from external/tf/third_party/py/numpy/numpy_include/numpy/ndarraytypes.h:1761:0,
                 from external/tf/third_party/py/numpy/numpy_include/numpy/ndarrayobject.h:17,
                 from external/tf/third_party/py/numpy/numpy_include/numpy/arrayobject.h:4,
                 from external/tf/tensorflow/python/lib/core/py_func.cc:19:
external/tf/third_party/py/numpy/numpy_include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
INFO: From Compiling external/tf/tensorflow/core/kernels/ops_util.cc [for host]:
external/tf/tensorflow/core/kernels/ops_util.cc: In function 'std::string tensorflow::SanitizeThreadSuffix(std::string)':
external/tf/tensorflow/core/kernels/ops_util.cc:123:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < suffix.size(); ++i) {
                                   ^
ERROR: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/tf/tensorflow/core/kernels/BUILD:646:1: C++ compilation of rule '@tf//tensorflow/core/kernels:argmax_op' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 71 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)
```
My system is Ubuntu 16.04 LTS and bazel version is 0.2.0.

**Comment by kirilg** [comment]
@eeriee the Docker file we provide should set the environment in the same way for everyone. I just verified using a new docker image and everything ran successfully. For reference, use the [instructions here](https://tensorflow.github.io/serving/docker).

I see "external/tf/..." mentioned in your logs, which suggests to me that you're running with an old instance of Tensorflow Serving (should be "external/org_tensorflow/..." as of a couple of weeks ago). Can you try syncing to head and retrying if that's the case? Make sure submodules were also updated to what TF Serving is using at head. You'll probably want to run `bazel clean` before compiling again.
