### ISSUE TITLE
build error:adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by infichen** [tensorflow/serving#971]
When I build with command "bazel build --config=cuda   -c opt tensorflow_serving/..." ,it takes error:
ERROR: /opt/serving/tensorflow_serving/util/net_http/client/testing/BUILD:12:1: Linking of rule '//tensorflow_serving/util/net_http/client/testing:evhttp_echo_client' failed (Exit 1)
/usr/bin/ld: bazel-out/k8-opt/bin/external/com_google_absl/absl/time/libtime.a(duration.o): undefined reference to symbol 'floor@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Can anyone help me!

**Comment by netfs** [comment]
there are devel gpu docker images available here:

https://hub.docker.com/r/tensorflow/serving/tags/

(try tensorflow/serving:latest-devel-gpu). this will allow you to quickly bootstrap you devel environment for gpus. if docker is not an option, you can see the dependencies and compile steps in the dockerfile here (and try and replicate that in your environment manually):

https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel-gpu

**Comment by netfs** [comment]
just realized latest-devel-gpu is not published yet. will have it out by EOD.

**Comment by infichen** [comment]
I need to build tensorflow serving which integrated tensorrt.
My environments:  ubuntu16.04   cuda 8.0  cudnn 7.0.5    TensorFlow-serving 1.8.0    TensorFlow 1.9.0   TensorRT 4.0.3

**Comment by netfs** [comment]
i pulled in (https://github.com/tensorflow/serving/pull/974) bunch of docker fixes from master that should fix your build issue. specifically the change to libevent.BUILD:

https://github.com/tensorflow/serving/pull/974/commits/9b26b41793321bb5cd9a7684e8f9a10cbc3d0ebc#diff-6b0a1c1839d8d8718c94e015963e8320

please try building from tip of r1.8 branch

**Comment by Bucca1992** [comment]
I was caught up with the same error. I found the cause was that libm.so.6 was not automatically linked in the compiling process, so I added an linkopt in tensorflow_serving/util/net_http/client/testing/BUILD:
`cc_binary(
  ...
  linkopts = ["-lm"],
)`.

**Comment by CLIsVeryOK** [comment]
@Bucca1992  tensorflow_serving/util/net_http/client/testing/BUILD looks like below, but I still get the error, could you help me out? I used tensorflow-serving(master) + tensorflow(r1.10).
```
# Description: net_http/client/testing
package(
    default_visibility = [
        "//tensorflow_serving:internal",
    ],
    features = ["-layering_check"],
)

licenses(["notice"])  # Apache 2.0

cc_binary(
    name = "evhttp_echo_client",
    srcs = ["evhttp_echo_client.cc"],
    deps = [
        "//tensorflow_serving/util/net_http/client:evhttp_client",
    ],
    linkopts = ["-lm"],
)
'''
the error like this:
'''ERROR: /tensorflow-serving/serving-r1.10/serving-r1.10/tensorflow_serving/util/net_http/server/testing/BUILD:12:1: Linking of rule '//tensorflow_serving/util/net_http/server/testing:evhttp_echo_server' failed (Exit 1)
/usr/bin/ld: bazel-out/k8-opt/bin/external/com_google_absl/absl/time/libtime.a(duration.o): undefined reference to symbol 'floor@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 58.230s, Critical Path: 19.92s
INFO: 162 processes: 162 local.
FAILED: Build did NOT complete successfully
'''

**Comment by CLIsVeryOK** [comment]
@infichen  have you yet fix your problem?

**Comment by Bucca1992** [comment]
@CLIsVeryOK server BUILD file needs to be changed like client BUILD file: `util/net_http/server/testing/BUILD `

**Comment by CLIsVeryOK** [comment]
@Bucca1992 thanks, it works.

but I met another problem when running, have you met this?

`bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=8000  --model_config_file=model_config.cfg --platform_config_file=platform_config_file.cfg
`
2018-08-13 03:33:04.644205: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUresult(-1)
2018-08-13 03:33:04.644271: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: 3d8ad1d819fb
2018-08-13 03:33:04.644293: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: 3d8ad1d819fb
2018-08-13 03:33:04.644434: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
2018-08-13 03:33:04.644499: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 384.130.0
2018-08-13 03:33:05.125355: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:113] Restoring SavedModel bundle.
2018-08-13 03:33:17.695824: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:233] SavedModel load for tags { serve }; Status: fail. Took 13577229 microseconds.
2018-08-13 03:33:17.695998: E tensorflow_serving/util/retrier.cc:37] Loading servable: {name: common_detect_models version: 2} failed: Invalid argument: Tensor :0, specified in either feed_devices or fetch_devices was not found in the Graph

**Comment by CLIsVeryOK** [comment]
@Bucca1992 thanks, it works!

**Comment by Victorsoukhov** [comment]
Hi!
I have the same error:
ERROR: /home/tmsadm/serving/tensorflow_serving/util/net_http/socket/testing/BUILD:12:1: Linking of rule 

'//tensorflow_serving/util/net_http/socket/testing:ev_print_req_server' failed (Exit 1)
/usr/bin/ld: bazel-out/k8-opt/bin/external/com_google_absl/absl/strings/libstrings.a(charconv.o): undefined reference to symbol 

'nan@@GLIBC_2.2.5'
//usr/lib64/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

I tried to correct BUILD files, but this doesn't help.
Any recommendations is highly appreciated.
Thank you.

**Comment by Victorsoukhov** [comment]
So it seems that 
/util/net_http/socket/testing/BUILD
should be corrected too - as it uses math library...

**Comment by Victorsoukhov** [comment]
Thank you! 
After that build works OK!
/util/net_http/socket/testing/BUILD - two places to change...

**Comment by ymodak** [comment]
@infichen Just wanted to follow up. Is this still an issue for you?

**Comment by Victorsoukhov** [comment]
Issue,  solved.  Thank you!
