### ISSUE TITLE
Problem with multiple models and server availability

### ISSUE THREAD

**Issue by 4ds23d** [tensorflow/serving#979]
Consider following scenario

Configuration file is as follows:
```
model_config_list: {
    config: {
        name: "detection1",
		base_path: "/data/tf-models/m1",
		model_platform: "tensorflow",
		model_version_policy: {
			all: {}
		}
	},
    config: {
              name: "detection2",
              base_path: "/data/tf-models/m2",
              model_platform: "tensorflow",
              model_version_policy: {
                        all: {}
              }
}
```
Server is being started with following args: ``` --port=9100 --model_config_file=/etc/tf-serving.conf --file_system_poll_wait_seconds=1```

Tensorflow Serving starts serwer when there is at least one model in both paths: 
* /data/tf-models/m1
* /data/tf-models/m2

How to force tensorflow serving to start server when there is at least one model in provided paths? For example there is model in path   /data/tf-models/m1 and path  /data/tf-models/m2 is empty?

**Comment by chrisolston** [comment]
I don't think there's a way to do that. I haven't heard that use case before so I'm not sure it's common.
