### ISSUE TITLE
Nested Bazel Projects with Tensorflow Serving

### ISSUE THREAD

**Issue by snakecharmer1024** [tensorflow/serving#98]
Hello, I'm trying to make a bazel project that has serving as a sub-project and I am stuck on something that is probably simple. I elaborate here, but no answers, yet. 

http://stackoverflow.com/questions/37581247/nested-bazel-projects

Basically I want to be able to tell @tf, the sub-sub-project to put it's generated files into its grandparent projects bazel-out directory.

**Comment by chrisolston** [comment]
Glad to see that the stack-overflow thread has an accepted response.
