### ISSUE TITLE
C++ compilation of rule '@boringssl//:crypto' failed (Exit 1)

### ISSUE THREAD

**Issue by zjfheart** [tensorflow/serving#982]
[jingfeng@Jingfeng_redhat tensorflow]$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

ERROR: /home/jingfeng/.cache/bazel/_bazel_jingfeng/29120beece5f660cdcebf72073ed1bba/external/boringssl/BUILD:115:1: C++ compilation of rule '@boringssl//:crypto' failed (Exit 1)
external/boringssl/src/crypto/cipher_extra/e_chacha20poly1305.c: In function 'poly1305_update_length':
external/boringssl/src/crypto/cipher_extra/e_chacha20poly1305.c:145:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (unsigned i = 0; i < sizeof(length_bytes); i++) {
   ^
external/boringssl/src/crypto/cipher_extra/e_chacha20poly1305.c:145:3: note: use option -std=c99 or -std=gnu99 to compile your code
external/boringssl/src/crypto/cipher_extra/e_chacha20poly1305.c: In function 'aead_chacha20_poly1305_seal_scatter':
external/boringssl/src/crypto/cipher_extra/e_chacha20poly1305.c:229:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (size_t done = 0; done < extra_in_len; block_counter++) {
     ^
external/boringssl/src/crypto/cipher_extra/e_chacha20poly1305.c:233:7: error: 'for' loop initial declarations are only allowed in C99 mode
       for (size_t i = offset; i < sizeof(block) && done < extra_in_len;
       ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.244s, Critical Path: 6.30s
INFO: 5 processes: 5 local.
FAILED: Build did NOT complete successfully

[jingfeng@Jingfeng_redhat ~]$ uname -a 
Linux Jingfeng_redhat 3.10.0-862.3.2.el7.ppc64le #1 SMP Tue May 15 22:31:16 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux

[jingfeng@Jingfeng_redhat ~]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/ppc64le-redhat-linux/4.8.5/lto-wrapper
Target: ppc64le-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/cloog-install --enable-gnu-indirect-function --enable-secureplt --with-long-double-128 --enable-targets=powerpcle-linux --disable-multilib --with-cpu-64=power8 --with-tune-64=power8 --build=ppc64le-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 

jingfeng@Jingfeng_redhat ~]$ bazel version
Extracting Bazel installation...
Build label: 0.11.0- (@non-git)
Build target: bazel-out/ppc-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 13 14:25:29 +50491 (1531191651929)
Build timestamp: 1531191651929
Build timestamp as int: 1531191651929

May I know the reason for this problem? & how to solve it?  Many thanks for this

**Comment by netfs** [comment]
there is no //tensorflow/tools/pip_package:build_pip_package target in the [serving repo](https://github.com/tensorflow/serving). did you intend to open this issue with tensorflow rep [here](https://github.com/tensorflow/tensorflow/issues)?

**Comment by zjfheart** [comment]
done! thanks for the reminder.
