### ISSUE TITLE
RESTful Predict API returning a list with an invalid scientific notation number representing a float value that python cannot parse 

### ISSUE THREAD

**Issue by LearnedVector** [tensorflow/serving#989]
Hello, I have tensorflow serving working using the RESTful Predict API. My use case is for speech synthesis so the predictions is a long array of float values that represents an audio wav, usually shown in scientific notation, for example `[3.69139e-07, 9e-07.0, 1.80245e-06, 3.30261e-06, ...]`. However, you can see that the second value `9e-07.0` is not a legit float value in python and therefore when I try to parse the response from the RESTful Predict API I get a JSON parsing error`json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2 column 827383 (char 827384)` with column 827383 being whatever column the invalid value is in. Any ideas on how to get around this?

**Comment by netfs** [comment]
this is a bug in json_tensor library. we incorrectly convert whole numbers >6 digits as such numbers get represented (by absl::StrCat()) in scientific notation, and we add a trailing ".0" to such numbers:

https://github.com/tensorflow/serving/blob/01ea36b337073ed3e6949d078c7e742373321d70/tensorflow_serving/util/json_tensor.cc#L709

yielding incorrect scientific notation (that cannot then be parsed by JSON readers). will submit a fix shortly.
