### ISSUE TITLE
build error: Linking of rule '@com_googlesource_code_re2//:re2' failed  when compile serving1.8 on Ubuntu 16.04

### ISSUE THREAD

**Issue by IvyTang** [tensorflow/serving#990]
OS Env：
1.  Ubuntu 5.4.0-6ubuntu1~16.04.9
2. TF Serving 1.8 ;
     Cuda9.0 
     Cudnn7.0
3.  gcc version 5.4.0
5. bazel 0.15.0

And I want to compile Serving with GPU supported.
The cmd is:
```
export TF_NEED_CUDA=1  
bazel build -c opt --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-O3 --config=cuda  tensorflow_serving/...
```

> ERROR: /root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/external/com_googlesource_code_re2/BUILD:11:1: Linking of rule '@com_googlesource_code_re2//:re2' failed (Exit 1)
> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
> (.text+0x20): undefined reference to `main'
> collect2: error: ld returned 1 exit status
>

**Comment by netfs** [comment]
can you try using [tensorflow/serving:1.8.0-devel-gpu](https://hub.docker.com/r/tensorflow/serving/tags/) docker image for a more hermetic environment to do your builds. once you pull the docker image you can use https://github.com/tensorflow/serving/blob/master/tools/bazel_in_docker.sh to do the builds.

or just use the GPU docker image to run GPU enabled ModelServer. note you will require nvidia-docker to run the image on a GPU.
