### ISSUE TITLE
 failed: Not found: Op type not registered 'PyFunc'

### ISSUE THREAD

**Issue by betterhalfwzm** [tensorflow/serving#992]
E tensorflow_serving/util/retrier.cc:37] Loading servable: {name: deeplab version: 1} failed: Not found: Op type not registered 'PyFunc' in binary running on iva. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Comment by chrisolston** [comment]
It looks like the op you need (PyFunc) isn't linked into the TF-Serving binary. You'll need to add it as a dependency in the BUILD rule and re-run "bazel build ...".

That said, I'm not sure if PyFunc will work with TF-Serving because PyFunc wraps a Python lambda as an op, and TF-Serving is C++.
