### ISSUE TITLE
Latency high while loading new model after upgrading to tf1.8

### ISSUE THREAD

**Issue by tianyapiaozi** [tensorflow/serving#996]
Currently we are using tf1.1 to serve online prediction request. We have used warmup according to #385 and a separate thread pool to load new model according to TFX paper. Latency is smooth even during loading a new model.
We're planing to upgrade to t1.8. However, high latency is noted while loading new model using tf1.8. 
Your help is needed and appreciated!

**Comment by netfs** [comment]
assuming you are using the binary debian packages, yes there is an ongoing issue with them (the binaries were compiled using sub-optimal compiler flags) from 1.8 and upwards -- that is causing high model load latency. we plan to re-release these debian packages by EOD today (July 19, PST).

until then, you can use the "devel" docker images (these are fine) to serve your models. these are available here: https://hub.docker.com/r/tensorflow/serving/tags/.

if you observe high latency for devel docker images, please do report back (we have not see any issues on our side).

thanks!

**Comment by netfs** [comment]
new binaries and docker images for 1.8.0 and 1.9.0 has been released.

please re-open if you see high load times with these new binaries.
