### ISSUE TITLE
How to handle model names on serving to get model status/metrics

### ISSUE THREAD

**Issue by ynqa** [tensorflow/serving#997]
Now, the model name in `ModelSpec` is required (version is optional) for gRPC services. In particular, `GetModelStatus` and `GetModelMetrics` (in #800) are too.

These services could be also used to collect model metrics, which are exported to monitoring systems (such as prometheus). That means the metrics exporters must know what model names are deployed in advance. It's not good.

Before, there are PR to get all model names on tf serving in #797. It's a simple solution for this issue, but closed now.

There is possibility that it will be happend in kubeflow/kubeflow#1036. I kindly ask for your cooperation to tackle it.

cc. @chrisolston

**Comment by chrisolston** [comment]
This debate already happened (in #797 as you pointed out). Sorry we cannot support this feature.
